Repository cyberbotics/webots, pull requests merged in 2018-12, with the labels that each got.

#91 Update docs/README.md
  docs/README.md
Labels: invalid

#92 Improve readme
  README.md
Labels: enhancement

#94 Better README title sizes
  README.md
Labels: enhancement

#95 Improve the documentation relatively with the open source migration
  docs/guide/building-webots.md
  docs/guide/foreword.md
  docs/guide/menu.md
Labels: enhancement

#96 Fix date
  docs/guide/foreword.md
Labels: invalid

#87 Refactor Post-Processing for Cameras
  src/webots/Makefile
  src/webots/wren/WbWrenAbstractPostProcessingEffect.cpp
  src/webots/wren/WbWrenAbstractPostProcessingEffect.hpp
  src/webots/wren/WbWrenCamera.cpp
  src/webots/wren/WbWrenCamera.hpp
  src/webots/wren/WbWrenColorNoise.cpp
  src/webots/wren/WbWrenColorNoise.hpp
  src/webots/wren/WbWrenDepthOfField.cpp
  src/webots/wren/WbWrenDepthOfField.hpp
  src/webots/wren/WbWrenLensDistortion.cpp
  src/webots/wren/WbWrenLensDistortion.hpp
  src/webots/wren/WbWrenMotionBlur.cpp
  src/webots/wren/WbWrenMotionBlur.hpp
  src/webots/wren/WbWrenNoiseMask.cpp
  src/webots/wren/WbWrenNoiseMask.hpp
  src/webots/wren/WbWrenRangeNoise.cpp
  src/webots/wren/WbWrenRangeNoise.hpp
  src/webots/wren/WbWrenRangeQuantization.cpp
  src/webots/wren/WbWrenRangeQuantization.hpp
  src/webots/wren/WbWrenRenderingContext.hpp
  src/wren/PostProcessingEffect.cpp
  src/wren/Scene.cpp
  src/wren/Viewport.cpp
Labels: enhancement

#97 Enable Travis
  .travis.yml
  README.md
  docs/.travis.yml
  jenkins.sh
  tests/sources/bin/cfg/std.cfg
  tests/sources/bin/cppcheck
  tests/sources/requirements.txt
  tests/sources/test_cppcheck.py
Labels: enhancement

#103 Fixed Compilation of Java Controller when Swig is not Installed.
  resources/Makefile.java.include
Labels: bug

#102 Advanced Post-Processing on Cameras
  change_logs/ChangeLog.html
  docs/reference/camera.md
  resources/nodes/Camera.wrl
  resources/wren/shaders/gtao.frag
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbCamera.hpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/wren/WbWrenCamera.cpp
  src/webots/wren/WbWrenCamera.hpp
  src/webots/wren/WbWrenGtao.cpp
  src/webots/wren/WbWrenGtao.hpp
  src/webots/wren/WbWrenShaders.cpp
  src/wren/Viewport.cpp
Labels: enhancement
