Repository cyberbotics/webots, pull requests merged in 2019-12, with the labels that each got.

#1147 Add compass.wbt in the documentation
  docs/guide/images/samples/compass.png
  docs/guide/images/samples/compass.thumbnail.jpg
  docs/guide/samples-devices.md
Labels: enhancement

#1137 Fix physicsReset() functions
  docs/reference/changelog-r2019.md
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbBallJoint.hpp
  src/webots/nodes/WbHinge2Joint.cpp
  src/webots/nodes/WbHinge2Joint.hpp
  src/webots/nodes/WbHingeJoint.cpp
  src/webots/nodes/WbJoint.cpp
  src/webots/nodes/WbJoint.hpp
  src/webots/nodes/WbSliderJoint.cpp
  src/webots/nodes/WbSolid.cpp
  tests/api/controllers/supervisor_reset_physics_hinge/supervisor_reset_physics_hinge.c
  tests/api/controllers/supervisor_set_position_of_dynamic_object/.gitignore
  tests/api/controllers/supervisor_set_position_of_dynamic_object/Makefile
  tests/api/controllers/supervisor_set_position_of_dynamic_object/supervisor_set_position_of_dynamic_object.c
  tests/api/worlds/supervisor_set_position_of_dynamic_object.wbt
  tests/lib/ts_assertion.h
Labels: enhancement

#1148 Improve documentation about Kinematics mode
  docs/reference/motor.md
Labels: enhancement

#1153 Document login to old Webots releases
  docs/guide/general-faq.md
Labels: enhancement

#705 Improve E-puck Model
  docs/guide/epuck.md
  docs/guide/images/robots/epuck/e-puck2_pi-puck.wbt.png
  docs/guide/images/robots/epuck/e-puck2_pi-puck.wbt.thumbnail.jpg
  docs/guide/images/robots/epuck/icon.png
  docs/guide/images/robots/epuck/model.png
  docs/guide/images/robots/epuck/model.thumbnail.png
  docs/reference/changelog-r2020.md
  projects/appearances/protos/Copper.proto
  projects/appearances/protos/Pcb.proto
  projects/appearances/protos/icons/Copper.png
  projects/appearances/protos/icons/Pcb.png
  projects/appearances/protos/textures/copper/copper_base_color.jpg
  projects/appearances/protos/textures/copper/copper_metalness.jpg
  projects/appearances/protos/textures/copper/copper_roughness.jpg
  projects/appearances/protos/textures/pcb/pcb_base_color.jpg
  projects/appearances/protos/textures/pcb/pcb_metalness.jpg
  projects/appearances/protos/textures/pcb/pcb_normal.jpg
  projects/appearances/protos/textures/pcb/pcb_occlusion.jpg
  projects/appearances/protos/textures/pcb/pcb_roughness.jpg
  projects/objects/solids/protos/SolidBox.proto
  projects/objects/solids/protos/SolidPipe.proto
  projects/objects/solids/protos/SolidRoundedBox.proto
  projects/objects/solids/protos/SolidTorus.proto
  projects/robots/gctronic/e-puck/protos/E-puck.proto
  projects/robots/gctronic/e-puck/protos/E-puckDistanceSensor.proto
  projects/robots/gctronic/e-puck/protos/E-puckGroundSensors.proto
  projects/robots/gctronic/e-puck/protos/Pi-puck.proto
  projects/robots/gctronic/e-puck/protos/icons/Pi-puck.png
  projects/robots/gctronic/e-puck/protos/textures/pi-puck_bottom.jpg
  projects/robots/gctronic/e-puck/protos/textures/pi-puck_top_base_color.jpg
  projects/robots/gctronic/e-puck/protos/textures/pi-puck_top_normal.jpg
  projects/robots/gctronic/e-puck/protos/textures/pi-puck_top_occlusion.jpg
  projects/robots/gctronic/e-puck/protos/textures/raspberry_pi_bottom.jpg
  projects/robots/gctronic/e-puck/protos/textures/raspberry_pi_top_base_color.jpg
  projects/robots/gctronic/e-puck/protos/textures/raspberry_pi_top_normal.jpg
  projects/robots/gctronic/e-puck/protos/textures/raspberry_pi_top_occlusion.jpg
  projects/robots/gctronic/e-puck/worlds/.e-puck2_pi-puck.wbproj
  projects/robots/gctronic/e-puck/worlds/e-puck2_pi-puck.wbt
  scripts/icon_studio/controllers/icon_creator/appearances.json
Labels: enhancement

#1154 Merge master to revision
  docs/guide/general-faq.md
Labels: enhancement

#1158 Merge revision to develop
  docs/guide/general-faq.md
Labels: invalid

#1157 Update node values in MATLAB API
  docs/reference/changelog-r2020.md
  docs/reference/supervisor.md
  lib/controller/matlab/WB_NODE_CYLINDER.m
  lib/controller/matlab/WB_NODE_DIRECTIONAL_LIGHT.m
  lib/controller/matlab/WB_NODE_ELEVATION_GRID.m
  lib/controller/matlab/WB_NODE_FOG.m
  lib/controller/matlab/WB_NODE_GROUP.m
  lib/controller/matlab/WB_NODE_IMAGE_TEXTURE.m
  lib/controller/matlab/WB_NODE_INDEXED_FACE_SET.m
  lib/controller/matlab/WB_NODE_INDEXED_LINE_SET.m
  lib/controller/matlab/WB_NODE_MATERIAL.m
  lib/controller/matlab/WB_NODE_MUSCLE.m
  lib/controller/matlab/WB_NODE_NORMAL.m
  lib/controller/matlab/mgenerate.py
  lib/controller/matlab/wb_supervisor_node_get_number_of_contact_points.m
  src/lib/Controller/api/node.c
Labels: bug

#1145 Extend Supervisor
  docs/reference/changelog-r2020.md
  docs/reference/supervisor.md
  include/controller/c/webots/supervisor.h
  include/controller/cpp/webots/Field.hpp
  include/controller/cpp/webots/Node.hpp
  lib/controller/matlab/mgenerate.py
  lib/controller/matlab/wb_supervisor_field_import_sf_node.m
  lib/controller/matlab/wb_supervisor_field_import_sf_node_from_string.m
  lib/controller/matlab/wb_supervisor_field_remove_sf.m
  lib/controller/matlab/wb_supervisor_node_add_force.m
  lib/controller/matlab/wb_supervisor_node_add_force_with_offset.m
  lib/controller/matlab/wb_supervisor_node_add_torque.m
  projects/default/controllers/ros/RosSupervisor.cpp
  projects/default/controllers/ros/RosSupervisor.hpp
  projects/default/controllers/ros/include/srv/node_add_force_or_torque.srv
  projects/default/controllers/ros/include/srv/node_add_force_with_offset.srv
  projects/languages/ros/webots_ros/CMakeLists.txt
  projects/languages/ros/webots_ros/src/complete_test.cpp
  resources/languages/cpp/Field.cpp
  resources/languages/cpp/Node.cpp
  src/lib/Controller/Controller.def
  src/lib/Controller/api/messages.h
  src/lib/Controller/api/supervisor.c
  src/webots/app/WbApplication.cpp
  src/webots/app/WbApplication.hpp
  src/webots/core/WbLanguage.cpp
  src/webots/editor/WbBuildEditor.cpp
  src/webots/editor/WbBuildEditor.hpp
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/engine/WbSimulationWorld.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbRobot.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  src/webots/nodes/utils/WbWorld.hpp
  tests/api/controllers/supervisor_force_torque/.gitignore
  tests/api/controllers/supervisor_force_torque/Makefile
  tests/api/controllers/supervisor_force_torque/supervisor_force_torque.c
  tests/api/controllers/supervisor_import_remove/supervisor_import_remove.c
  tests/api/controllers/supervisor_reset_simulation/supervisor_reset_simulation.c
  tests/api/worlds/supervisor_force_torque.wbt
  tests/api/worlds/supervisor_import_remove.wbt
  tests/api/worlds/supervisor_reset_simulation.wbt
Labels: enhancement

#1160 Fix wb_robot_set_mode argument type
  docs/guide/controller-plugin.md
  docs/reference/changelog-r2020.md
  docs/reference/robot.md
  include/controller/c/webots/remote_control.h
  include/controller/c/webots/robot.h
  include/controller/cpp/webots/Robot.hpp
  lib/controller/matlab/mgenerate.py
  lib/controller/matlab/wb_robot_set_mode.m
  projects/default/controllers/ros/Ros.cpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/Wrapper.cpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/Wrapper.hpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/Wrapper.cpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/Wrapper.hpp
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/RemoteControlWidget.cpp
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.c
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Wrapper.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Wrapper.hpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/RemoteControlWidget.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Wrapper.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Wrapper.hpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/TransferWidget.cpp
  resources/languages/cpp/Robot.cpp
  src/lib/Controller/api/remote_control.c
  src/lib/Controller/api/remote_control_private.h
  src/lib/Controller/api/robot.c
  tests/api/plugins/remote_controls/remote_control/remote_control.c
Labels: enhancement

#1161 Update worlds
  projects/robots/pal_robotics/tiago++/worlds/tiago++.wbt
  projects/robots/pal_robotics/tiago_iron/worlds/tiago_iron.wbt
  projects/robots/pal_robotics/tiago_steel/worlds/tiago_steel.wbt
  projects/robots/pal_robotics/tiago_titanium/worlds/tiago_titanium.wbt
  projects/samples/curriculum/worlds/advanced_pattern_recognition.wbt
  projects/samples/robotbenchmark/pick_and_place/worlds/pick_and_place.wbt
Labels: enhancement

#1167 HDR Reflection Fallback
  resources/web/wwi/x3d.js
  resources/web/wwi/x3d_scene.js
Labels: bug

#1172 Improve doc about old license system
  docs/guide/general-faq.md
Labels: enhancement

#1174 Merge revision to develop
  docs/guide/general-faq.md
Labels: enhancement, invalid

#1176 macOS: Fix new clang warnings coming from swig
  resources/languages/python/Makefile
Labels: enhancement

#1175 macOS: Fix RPATH of openssl
  dependencies/Makefile.mac
  src/packaging/check_rpath.py
Labels: enhancement

#1163 Improve Splash Screen
  resources/images/splash_images/abb.jpg
  resources/images/splash_images/bmw.jpg
  resources/images/splash_images/eole.jpg
  resources/images/splash_images/pr2.jpg
  resources/images/splash_images/tesla.jpg
  resources/images/splash_images/thymio.jpg
  resources/images/splash_images/youbot.jpg
Labels: enhancement

#1177 Improved receiver warnings
  src/lib/Controller/api/receiver.c
Labels: enhancement

#1180 Fix Reset
  src/webots/app/WbApplication.hpp
  src/webots/engine/WbSimulationWorld.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/gui/WbStreamingServer.cpp
  src/webots/nodes/utils/WbWorld.hpp
Labels: bug

#1181 Fix memory leak
  src/webots/nodes/WbCamera.cpp
Labels: bug, enhancement

#1186 Fix wrong clean target.
  resources/Makefile
Labels: bug

#1189 Fixed Changelog
  docs/reference/changelog-r2020.md
Labels: enhancement

#1190 Fixed Warnings in Tiago Titanium.
  projects/robots/pal_robotics/tiago_titanium/controllers/tiago_titanium/tiago_titanium.c
Labels: bug

#1194 Fix background export of robot component.
  scripts/web_component_studio/controllers/web_component_studio_supervisor/web_component_studio_supervisor.py
Labels: bug, enhancement

#1196 Rename 'physics' fields into 0enablePhysics'
  docs/guide/appearances.md
  docs/guide/camera-sensors.md
  docs/guide/lidar-sensors.md
  docs/guide/object-factory.md
  docs/reference/changelog-r2020.md
  projects/devices/multisense/protos/MultiSenseS21.proto
  projects/devices/robotis/protos/RobotisLds01.proto
  projects/devices/sick/protos/SickLdMrs.proto
  projects/objects/factory/tools/protos/CapScrew.proto
Labels: bug

#1199 Fix typo in Help menu
  src/webots/gui/WbMainWindow.cpp
Labels: enhancement

#1200 Update TurtleBot3 Burger splash screen to include the lidar.
  resources/images/splash_images/turtlebot3.jpg
Labels: enhancement

#1202 Remove link to Support Ticket from Help menu
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
Labels: invalid

#1201 Fix robot component rotation
  docs/guide/scenes/aibo-ers7/aibo-ers7.meta.json
  docs/guide/scenes/altino/altino.meta.json
  docs/guide/scenes/atlas/atlas.meta.json
  docs/guide/scenes/bb8/bb8.meta.json
  docs/guide/scenes/bioloid/bioloid.meta.json
  docs/guide/scenes/boebot/boebot.meta.json
  docs/guide/scenes/create/create.meta.json
  docs/guide/scenes/elisa3/elisa3.meta.json
  docs/guide/scenes/epuck/epuck.meta.json
  docs/guide/scenes/firebird6/firebird6.meta.json
  docs/guide/scenes/ghostdog/ghostdog.meta.json
  docs/guide/scenes/hemisson/hemisson.meta.json
  docs/guide/scenes/hoap2/hoap2.meta.json
  docs/guide/scenes/ipr/ipr.meta.json
  docs/guide/scenes/irb4600-40/irb4600-40.meta.json
  docs/guide/scenes/khepera1/khepera1.meta.json
  docs/guide/scenes/khepera2/khepera2.meta.json
  docs/guide/scenes/khepera3/khepera3.meta.json
  docs/guide/scenes/khepera4/khepera4.meta.json
  docs/guide/scenes/khr-2hv/khr-2hv.meta.json
  docs/guide/scenes/khr-3hv/khr-3hv.meta.json
  docs/guide/scenes/koala/koala.meta.json
  docs/guide/scenes/mantis/mantis.meta.json
  docs/guide/scenes/mavic-2-pro/mavic-2-pro.meta.json
  docs/guide/scenes/microbot/microbot.meta.json
  docs/guide/scenes/mindstorms/mindstorms.meta.json
  docs/guide/scenes/moose/moose.meta.json
  docs/guide/scenes/nao/nao.meta.json
  docs/guide/scenes/pioneer-3at/pioneer-3at.meta.json
  docs/guide/scenes/pioneer-3dx/pioneer-3dx.meta.json
  docs/guide/scenes/pioneer2/pioneer2.meta.json
  docs/guide/scenes/portal/portal.meta.json
  docs/guide/scenes/pr2/pr2.meta.json
  docs/guide/scenes/puma/puma.meta.json
  docs/guide/scenes/qrio/qrio.meta.json
  docs/guide/scenes/robotis-op2/robotis-op2.meta.json
  docs/guide/scenes/robotis-op3/robotis-op3.meta.json
  docs/guide/scenes/salamander/salamander.meta.json
  docs/guide/scenes/shrimp/shrimp.meta.json
  docs/guide/scenes/sojourner/sojourner.meta.json
  docs/guide/scenes/surveyor/surveyor.meta.json
  docs/guide/scenes/thymio2/thymio2.meta.json
  docs/guide/scenes/tiago-base/tiago-base.meta.json
  docs/guide/scenes/tiago-iron/tiago-iron.meta.json
  docs/guide/scenes/tiago-steel/tiago-steel.meta.json
  docs/guide/scenes/tiago-titanium/tiago-titanium.meta.json
  docs/guide/scenes/tiagopp/tiagopp.meta.json
  docs/guide/scenes/turtlebot3burger/turtlebot3burger.meta.json
  docs/guide/scenes/ure/ure.meta.json
  docs/guide/scenes/yamor/yamor.meta.json
  docs/guide/scenes/youbot/youbot.meta.json
  docs/js/viewer.js
  src/webots/nodes/utils/WbWorld.cpp
Labels: bug, enhancement

#1206 Update path to lib/controller in documentation
  docs/guide/running-extern-robot-controllers.md
Labels: enhancement

#1205 Various Fixes
  projects/robots/festo/robotino3/controllers/robotino3/robotino3.c
  projects/robots/festo/robotino3/worlds/robotino3.wbt
  projects/robots/pal_robotics/tiago++/worlds/tiago++.wbt
  projects/robots/pal_robotics/tiago_base/worlds/tiago_base.wbt
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoFrontArm.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoLeftArm.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightArm.proto
  projects/robots/pal_robotics/tiago_iron/worlds/tiago_iron.wbt
  projects/robots/pal_robotics/tiago_steel/worlds/tiago_steel.wbt
  projects/robots/pal_robotics/tiago_titanium/worlds/tiago_titanium.wbt
Labels: bug, enhancement

#1188 webots.min.js: hotfix rendering frequency
  resources/web/wwi/x3d_scene.js
Labels: bug

#1208 Nao demo - instructions displayed corrected
  projects/robots/softbank/nao/controllers/nao_demo/nao_demo.c
Labels: enhancement

#1211 Improve Nao Controller Messages
  projects/robots/softbank/nao/controllers/nao_demo/nao_demo.c
Labels: enhancement

#1209 Fix Visual Studio Controller Launch
  resources/templates/controllers/c.vcxproj.user
  resources/templates/controllers/cpp.vcxproj.user
  src/webots/gui/WbNewControllerWizard.cpp
Labels: bug, enhancement

#1146 Fix test sources after creating package
  tests/manual_tests/test_worlds_warnings.py
  tests/sources/generate_diff.py
  tests/sources/test_header_version.py
  tests/sources/test_textures.py
Labels: bug

#1217 Fix libssl and libcrypto symlinks.
  src/packaging/webots_distro.c
Labels: bug

#1214 Avoid including XC16 in the snap release.
  src/packaging/generate_projects_files.py
  src/packaging/omit_in_projects_snap.txt
Labels: bug, enhancement

#1218 Update version to R2020a-rev1
  Contents/Info.plist
  docs/js/showdown-extensions.js
  resources/version.txt
  src/packaging/webots_version.txt
  src/webots/core/WbApplicationInfo.cpp
Labels: enhancement

#1221 Fix abb default controller
  docs/reference/changelog-r2020.md
  projects/robots/abb/irb/protos/Irb4600-40.proto
Labels: bug

#1222 Fix missing argument in the supervisor doc
  docs/reference/supervisor.md
Labels: bug

#1224 Fixed installation instructions
  docs/guide/installation-procedure.md
Labels: enhancement
