Repository cyberbotics/webots, pull requests merged in 2019-01, with the labels that each got.

#107 Hotfix Windows compilation.
  src/webots/nodes/utils/WbVirtualRealityHeadset.cpp
  src/webots/nodes/utils/WbVirtualRealityHeadset.hpp
Labels: bug

#109 Fix Java Make Clean.
  resources/Makefile.java.include
Labels: bug

#112 Fix default floor creation
  resources/osm_importer/utils/misc_utils.py
Labels: enhancement

#115 Regenerate Docs
  docs/guide/generate_objects_doc.py
  docs/guide/object-backgrounds.md
  docs/guide/object-road.md
  projects/objects/backgrounds/protos/TexturedBackground.proto
  projects/objects/backgrounds/protos/TexturedBackgroundLight.proto
Labels: bug

#117 StripBuilding PROTO
  change_logs/ChangeLog.html
  docs/guide/images/objects/buildings/StripBuilding/model.png
  docs/guide/object-buildings.md
  projects/objects/buildings/protos/StripBuilding.proto
  projects/objects/buildings/protos/icons/StripBuilding.png
  scripts/icon_studio/controllers/icon_creator/objects.json
Labels: enhancement

#113 Extend Streaming Server
  resources/web/server/simulation_server.py
  resources/web/wwi/images/fast.png
  resources/web/wwi/images/revert.png
  resources/web/wwi/webots.js
  resources/web/wwi/wwi.css
  src/webots/gui/WbStreamingServer.cpp
  src/webots/gui/WbStreamingServer.hpp
Labels: enhancement

#118 Transfer all Textures to GPU at Load
  include/wren/scene.h
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbView3D.hpp
  src/webots/gui/WbWrenWindow.cpp
  src/webots/gui/WbWrenWindow.hpp
  src/webots/nodes/utils/WbVirtualRealityHeadset.cpp
  src/webots/wren/WbWrenCamera.cpp
  src/webots/wren/WbWrenPicker.cpp
  src/wren/Scene.cpp
  src/wren/Scene.hpp
Labels: bug, enhancement

#121 Fix Emitter-Receiver Matlab API
  docs/reference/emitter.md
  docs/reference/receiver.md
Labels: bug

#123 Fixed Missleading Changelog entry
  change_logs/ChangeLog.html
Labels: enhancement

#128 Fix OpenGl Required Version in Docs
  docs/guide/system-requirements.md
Labels: bug

#126 Fix Various Crash in Python API.
  change_logs/ChangeLog.html
  resources/languages/python/controller.i
Labels: bug

#129 Fixed missing tar dependency (needed on Windows 7)
  src/install_scripts/msys64_installer.sh
Labels: bug

#131 Add gdb Package to MSYS Installer as Optional Package
  src/install_scripts/msys64_installer.sh
Labels: enhancement

#130 Document the OSM Importer Supported Keywords.
  docs/automobile/openstreetmap-importer.md
Labels: enhancement

#135 Fix VRML Export Crash.
  change_logs/ChangeLog.html
  src/webots/nodes/WbAbstractAppearance.hpp
  src/webots/nodes/WbPbrAppearance.cpp
Labels: bug

#111 Fix SUMO exporter
  change_logs/ChangeLog.html
  resources/sumo_exporter/exporter.py
  resources/sumo_exporter/node_extractor.py
Labels: bug

#139 Fix typo
  resources/sumo_exporter/node_extractor.py
Labels: enhancement

#140 Fix 3D Feature of OSM Importer.
  resources/osm_importer/elevation.py
Labels: bug

#136 Remove binary strip
  src/webots/Makefile
Labels: enhancement

#144 Add Missing Muscle in nodes-and-api-functions Page
  docs/reference/nodes-and-api-functions.md
Labels: bug

#145  Improve OpenGL version detection
  src/webots/gui/WbWrenWindow.cpp
Labels: enhancement

#146 Fixed OSM Importer not Finding Config File.
  change_logs/ChangeLog.html
  docs/automobile/openstreetmap-importer.md
  resources/osm_importer/importer.py
  resources/osm_importer/settings.py
Labels: bug

#133 Fix Crash due to Baking Size
  change_logs/ChangeLog.html
  include/glad/glad.h
  include/wren/gl_state.h
  include/wren/texture_cubemap_baker.h
  src/glad/glad.c
  src/webots/core/WbSysInfo.cpp
  src/webots/core/WbSysInfo.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbView3D.cpp
  src/webots/nodes/WbCubemap.cpp
  src/webots/nodes/WbPbrAppearance.cpp
  src/wren/GlState.cpp
  src/wren/GlState.hpp
  src/wren/TextureCubeMapBaker.cpp
  src/wren/TextureCubeMapBaker.hpp
Labels: bug
