Repository cyberbotics/webots, pull requests merged in 2019-07, with the labels that each got.

#682 Windows nightly builds
  .appveyor-build.yml
  .appveyor.yml
  .travis.yml
  Makefile
  dependencies/Makefile.windows
Labels: enhancement

#684 Hotfix rounding issues
  src/webots/maths/WbPrecision.cpp
  src/webots/maths/WbPrecision.hpp
  src/webots/scene_tree/WbDoubleEditor.cpp
  src/webots/scene_tree/WbVector2Editor.cpp
  src/webots/scene_tree/WbVector3Editor.cpp
Labels: bug

#686 Avoid Nighlty Release During Weekend
  .travis.yml
  src/packaging/publish_release.py
Labels: enhancement

#685 Write changelog with a single word
  docs/blog/Webots-2018-a-release.md
  docs/blog/Webots-2018-b-release.md
  docs/blog/Webots-2019-a-release.md
  docs/blog/Webots-2019-b-release.md
  docs/blog/Webots-8-6-0-release.md
  docs/reference/change-log.md
  docs/reference/changelog-4.md
  docs/reference/changelog-5.md
  docs/reference/changelog-6.md
  docs/reference/changelog-7.md
  docs/reference/changelog-8.md
  docs/reference/changelog-r2018.md
  docs/reference/changelog-r2019.md
  docs/reference/changelog.md
  docs/reference/menu.md
  src/webots/gui/WbAboutBox.cpp
  src/webots/gui/WbWebotsUpdateDialog.cpp
Labels: enhancement

#687 Update JDK installation instructions
  docs/guide/using-java.md
Labels: bug

#683 Feature build on appveyor
  .appveyor-build.yml
  .appveyor.yml
  .travis.yml
  Makefile
  dependencies/Makefile.windows
  docs/guide/generate_objects_doc.py
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/SSH.cpp
  src/install_scripts/bash_profile.appveyor
  src/packaging/publish_release.py
  src/packaging/set_commit_and_date_in_version.py
  tests/sources/test_pep8.py
Labels: enhancement

#692 Fix Travis
  .travis.yml
Labels: bug

#691 Fixed Travis source tests
  .travis.yml
  tests/sources/generate_diff.py
  tests/sources/test_pep8.py
Labels: bug

#694 Stripped down openvr download
  dependencies/.gitignore
  dependencies/Makefile.windows
Labels: enhancement

#688 Enhancement ROS Launch Files
  projects/default/controllers/ros/RosCamera.cpp
  projects/default/controllers/ros/RosReceiver.cpp
  projects/default/controllers/ros/RosSensor.cpp
  projects/languages/ros/webots_ros/CMakeLists.txt
  projects/languages/ros/webots_ros/launch/catch_the_bird.launch
  projects/languages/ros/webots_ros/launch/complete_test.launch
  projects/languages/ros/webots_ros/launch/e_puck_line.launch
  projects/languages/ros/webots_ros/launch/keyboard_teleop.launch
  projects/languages/ros/webots_ros/launch/panoramic_view_recorder.launch
  projects/languages/ros/webots_ros/launch/pioneer3at.launch
  projects/languages/ros/webots_ros/launch/robot_information_parser.launch
  projects/languages/ros/webots_ros/launch/webots.launch
  projects/languages/ros/webots_ros/package.xml
  projects/languages/ros/webots_ros/src/catch_the_bird.cpp
  projects/languages/ros/webots_ros/src/complete_test.cpp
  projects/languages/ros/webots_ros/src/e_puck_line.cpp
  projects/languages/ros/webots_ros/src/keyboard_teleop.cpp
  projects/languages/ros/webots_ros/src/panoramic_view_recorder.cpp
  projects/languages/ros/webots_ros/src/pioneer3at.cpp
  projects/languages/ros/webots_ros/src/pr2_beer.cpp
  projects/languages/ros/webots_ros/src/robot_information_parser.cpp
  projects/languages/ros/webots_ros/src/webots_launcher.py
  projects/languages/ros/worlds/e-puck_line.wbt
  tests/ros.sh
  tests/ros_test_suite.py
  tests/rosconsole.config
Labels: enhancement

#696 Add a newsletter link in the 'new version dialog'
  src/webots/gui/WbNewVersionDialog.cpp
Labels: enhancement

#699 Fix Nightly Build Draft
  src/packaging/publish_release.py
Labels: bug

#701 Fix Unprotected Underscore
  docs/guide/running-extern-robot-controllers.md
Labels: bug

#703 Added links to nightly build descriptions
  src/packaging/publish_release.py
Labels: enhancement

#690 Skip AppVeyor test on merge
  .appveyor.yml
Labels: enhancement

#709 Fix Texture Picking
  docs/reference/change-log-r2019.md
  src/webots/nodes/WbImageTexture.cpp
Labels: bug

#713 Fix Texture Picking 2
  src/webots/nodes/WbImageTexture.cpp
Labels: bug

#717 Merge master in revision
  docs/blog/Webots-2018-a-release.md
  docs/blog/Webots-2018-b-release.md
  docs/blog/Webots-2019-a-release.md
  docs/blog/Webots-2019-b-release.md
  docs/blog/Webots-8-6-0-release.md
  docs/guide/running-extern-robot-controllers.md
  docs/guide/using-java.md
  docs/reference/change-log.md
  docs/reference/changelog-4.md
  docs/reference/changelog-5.md
  docs/reference/changelog-6.md
  docs/reference/changelog-7.md
  docs/reference/changelog-8.md
  docs/reference/changelog-r2018.md
  docs/reference/changelog-r2019.md
  docs/reference/changelog.md
  docs/reference/menu.md
  src/webots/gui/WbAboutBox.cpp
  src/webots/gui/WbWebotsUpdateDialog.cpp
Labels: bug

#710 Enhance Solid Following Behavior
  docs/guide/the-user-interface.md
  docs/reference/change-log-r2020.md
  docs/reference/viewpoint.md
  resources/nodes/Viewpoint.wrl
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbView3D.hpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/nodes/WbViewpoint.hpp
  src/webots/user_commands/WbActionManager.cpp
  src/webots/user_commands/WbActionManager.hpp
  src/webots/user_commands/WbContextMenuGenerator.cpp
  tests/protos/protos/TemplateViewpoint.proto
Labels: enhancement

#721 Speed-up Inno Setup compression
  src/packaging/webots_distro.c
Labels: enhancement

#722 Attempt to fix the build on tag except nightly
  .appveyor-build-tag.yml
Labels: bug

#727 Add webots.debug.js to gitignore
  resources/web/wwi/.gitignore
Labels: bug

#726 Fix template_viewpoint_proto test
  tests/protos/protos/TemplateViewpoint.proto
Labels: bug

#734 Fix CrossRoad PROTO
  projects/objects/traffic/protos/CrossRoadsTrafficLight.proto
Labels: bug

#735 Fix Windows Dependencies Makefile
  dependencies/Makefile.windows
Labels: bug

#730 Feature new sample worlds
  docs/guide/images/samples/accelerometer.png
  docs/guide/images/samples/accelerometer.thumbnail.jpg
  docs/guide/images/samples/brake.png
  docs/guide/images/samples/brake.thumbnail.jpg
  docs/guide/samples-devices.md
  docs/reference/changelog-r2019.md
  projects/guided_tour.txt
  projects/samples/devices/controllers/accelerometer/.gitignore
  projects/samples/devices/controllers/accelerometer/Makefile
  projects/samples/devices/controllers/accelerometer/accelerometer.c
  projects/samples/devices/controllers/brake/.gitignore
  projects/samples/devices/controllers/brake/Makefile
  projects/samples/devices/controllers/brake/brake.c
  projects/samples/devices/worlds/.accelerometer.wbproj
  projects/samples/devices/worlds/.brake.wbproj
  projects/samples/devices/worlds/accelerometer.wbt
  projects/samples/devices/worlds/brake.wbt
Labels: enhancement

#739 Fix External Controller
  docs/reference/changelog-r2019.md
  src/webots/control/WbController.cpp
  src/webots/control/WbController.hpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbRobot.hpp
Labels: bug

#738 Fix typo in External Controller Doc
  docs/guide/running-extern-robot-controllers.md
Labels: bug

#724 webots.min.js: fix viewpoint reset and other improvements
  projects/samples/robotbenchmark/viewpoint_control/plugins/robot_windows/viewpoint_control/topview.png
  projects/samples/robotbenchmark/viewpoint_control/plugins/robot_windows/viewpoint_control/viewpoint_control.js
  resources/web/wwi/animation.js
  resources/web/wwi/dialog_window.js
  resources/web/wwi/mouse_events.js
  resources/web/wwi/selector.js
  resources/web/wwi/stream.js
  resources/web/wwi/toolbar.js
  resources/web/wwi/viewpoint.js
  resources/web/wwi/x3d_scene.js
Labels: bug

#741 Feature Background Luminosity
  docs/reference/background.md
  docs/reference/changelog-r2020.md
  projects/objects/backgrounds/protos/TexturedBackground.proto
  resources/nodes/Background.wrl
  resources/web/wwi/x3d.js
  resources/web/wwi/x3d_scene.js
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbBackground.hpp
  src/webots/nodes/WbPbrAppearance.cpp
Labels: enhancement

#745 Improve Mavic 2 PRO lights
  projects/robots/dji/mavic/worlds/mavic_2_pro.wbt
Labels: enhancement

#746 Improve the vertical stabilization of the drone
  projects/robots/dji/mavic/controllers/mavic2pro/mavic2pro.c
Labels: enhancement

#729 Update simulation server documentation
  docs/guide/images/web_simulation_network_infrastructure.png
  docs/guide/menu.md
  docs/guide/web-interface.md
  docs/guide/web-simulation.md
  docs/guide/web-streaming.md
  resources/web/README.md
  resources/web/doc/overview.odg
  resources/web/doc/overview.svg
  resources/web/server/README.md
  resources/web/server/session_server.py
  resources/web/server/simulation_server.py
  resources/web/templates/download-project.php
  resources/web/templates/upload-file.php
  resources/web/wwi/webots.js
Labels: enhancement

#750 Include the new Mavic 2 PRO movie
  docs/guide/mavic-2-pro.md
Labels: enhancement

#756 Fix the insertion of a PROTO containing a BallJoint
  docs/reference/changelog-r2019.md
  src/webots/nodes/utils/WbNodeUtilities.cpp
Labels: bug

#758 Fix roughness and metalness in `realistic_village.wbt`
  docs/reference/changelog-r2019.md
  projects/vehicles/worlds/village_realistic.wbt
Labels: bug

#759 Improve OSM importer
  resources/osm_importer/webots_objects/area.py
  resources/osm_importer/webots_objects/road.py
Labels: enhancement

#763 Update tutorial 4
  docs/guide/tutorial-4-more-about-controllers-20-minutes.md
Labels: bug

#765 webots.min.js: Compute normals for ElevationGrids
  docs/reference/changelog-r2019.md
  resources/web/wwi/x3d.js
Labels: enhancement

#766 webots.min.js: Fix background color
  docs/reference/changelog-r2019.md
  resources/web/wwi/x3d_scene.js
Labels: bug

#767 webots.min.js: Fix fog type
  docs/reference/changelog-r2019.md
  resources/web/wwi/x3d.js
Labels: bug

#770 Hotfix modal window images background issues
  docs/css/webots-doc.css
Labels: enhancement

#771 Merge master to revision
  docs/css/webots-doc.css
  docs/guide/running-extern-robot-controllers.md
  docs/guide/tutorial-4-more-about-controllers-20-minutes.md
Labels: invalid
