Repository cyberbotics/webots, pull requests merged in 2019-05, with the labels that each got.

#398 Fix pasting in a PROTO regenerating field
  change_logs/ChangeLog.html
  src/webots/nodes/utils/WbNodeOperations.cpp
Labels: bug

#412 Fix DistanceSensors with Pen
  change_logs/ChangeLog.html
  src/webots/nodes/utils/WbPaintTexture.cpp
Labels: bug

#416 Fixed broken links and added new links
  docs/guide/samples-environments.md
Labels: bug

#417 Add Test for Github Links.
  docs/guide/samples-devices.md
  docs/guide/samples-geometries.md
  docs/guide/samples-rendering.md
  docs/guide/web-streaming.md
  docs/reference/plugin-setup.md
  docs/tests/test_hyperlinks.py
Labels: bug

#419 Fix controller-programming.md
  docs/guide/controller-programming.md
Labels: bug

#420 Fixed link failure if Webots installation folder contains parenthesis
  resources/Makefile.include
  resources/Makefile.os.include
Labels: bug

#322 Universal Robots ROS Controller
  docs/guide/ur5e.md
  projects/languages/ros/controllers/ros_python/Makefile
  projects/robots/universal_robots/ur5e/controllers/Makefile
  projects/robots/universal_robots/ur5e/controllers/universal_robot_ros/joint_state_publisher.py
  projects/robots/universal_robots/ur5e/controllers/universal_robot_ros/runtime.ini
  projects/robots/universal_robots/ur5e/controllers/universal_robot_ros/trajectory_follower.py
  projects/robots/universal_robots/ur5e/controllers/universal_robot_ros/universal_robot_ros.py
  projects/robots/universal_robots/ur5e/ressources/ros_package/ur_e_webots/CMakeLists.txt
  projects/robots/universal_robots/ur5e/ressources/ros_package/ur_e_webots/launch/ur5e.launch
  projects/robots/universal_robots/ur5e/ressources/ros_package/ur_e_webots/launch/ur5e_joint_limited.launch
  projects/robots/universal_robots/ur5e/ressources/ros_package/ur_e_webots/package.xml
  projects/robots/universal_robots/ur5e/ressources/ros_package/ur_e_webots/tests/roslaunch_test.xml
Labels: enhancement

#428 Run test_suite in Batch Mode
  tests/test_suite.py
Labels: enhancement

#429 Add Test to Check World and PROTO file Headers.
  projects/objects/drinks/protos/WaterBottle.proto
  projects/objects/kitchen/breakfast/protos/CerealBox.proto
  projects/objects/kitchen/breakfast/protos/HoneyJar.proto
  projects/objects/kitchen/components/protos/HotPlate.proto
  projects/objects/kitchen/components/protos/Sink.proto
  projects/objects/kitchen/components/protos/Worktop.proto
  projects/objects/kitchen/utensils/protos/Carafe.proto
  projects/objects/kitchen/utensils/protos/Cookware.proto
  projects/objects/kitchen/utensils/protos/Fork.proto
  projects/objects/kitchen/utensils/protos/Glass.proto
  projects/objects/kitchen/utensils/protos/Knife.proto
  projects/objects/kitchen/utensils/protos/Lid.proto
  projects/objects/kitchen/utensils/protos/Plate.proto
  projects/objects/kitchen/utensils/protos/Spoon.proto
  projects/objects/kitchen/utensils/protos/WoodenSpoon.proto
  projects/robots/adept/pioneer2/protos/Pioneer2.proto
  projects/robots/bluebotics/shrimp/protos/Shrimp.proto
  projects/robots/epfl/biorob/protos/GhostDog.proto
  projects/robots/epfl/biorob/protos/Salamander.proto
  projects/robots/epfl/biorob/protos/Yamor.proto
  projects/robots/k-team/hemisson/protos/Hemisson.proto
  projects/robots/k-team/khepera1/protos/Khepera1.proto
  projects/robots/k-team/khepera2/protos/Khepera2.proto
  projects/robots/k-team/koala/protos/Koala.proto
  projects/robots/kondo/khr-3hv/protos/Khr3hv.proto
  projects/robots/lego/mindstorms/protos/MindstormsRover.proto
  projects/robots/micromagic/mantis/protos/Mantis.proto
  projects/robots/nasa/protos/Sojourner.proto
  projects/robots/parallax/boebot/protos/BoeBot.proto
  projects/robots/robotis/bioloid/protos/BioloidDog.proto
  projects/robots/softbank/nao/protos/Nao.proto
  projects/robots/softbank/nao/protos/NaoJersey.proto
  projects/robots/softbank/nao/protos/NaoLeftWristH21.proto
  projects/robots/softbank/nao/protos/NaoLeftWristH25Realistic.proto
  projects/robots/softbank/nao/protos/NaoRightWristH21.proto
  projects/robots/softbank/nao/protos/NaoRightWristH25Realistic.proto
  projects/robots/sony/qrio/protos/QRIO.proto
  projects/robots/surveyor/protos/SurveyorSrv1.proto
  projects/robots/unimation/puma/protos/Puma560.proto
  projects/samples/curriculum/protos/Obstacle.proto
  projects/samples/rendering/protos/PingPongBallScaled.proto
  projects/vehicles/protos/bmw/BmwX5CentralMirrorFrame.proto
  scripts/icon_studio/worlds/icon_studio.wbt
  scripts/web_component_studio/worlds/web_component_studio_template.wbt
  tests/manual_tests/worlds/interaction_with_solid_reference_model.wbt
  tests/parser/worlds/nested_def_name.wbt
  tests/protos/protos/ShapeWithGeometryParameter.proto
  tests/protos/protos/TemplateNestedSlotContainer.proto
  tests/protos/protos/TemplateObject.proto
  tests/protos/protos/TemplateObjectBasePart.proto
  tests/protos/protos/TemplateObjectDerivedPart.proto
  tests/protos/protos/TwoSlotsContainer.proto
  tests/protos/worlds/super_parameter_instances.wbt
  tests/protos/worlds/template_nested_slot_container.wbt
  tests/sources/test_header_version.py
Labels: enhancement

#426 Fix Webots-Ros package
  projects/languages/ros/webots_ros/CMakeLists.txt
  projects/languages/ros/webots_ros/package.xml
Labels: bug

#427 Fix wwi_url value in webots.js
  resources/web/wwi/animation.js
  resources/web/wwi/default_url.js
  resources/web/wwi/editor.js
  resources/web/wwi/toolbar.js
  resources/web/wwi/webots.js
Labels: bug

#434 Fix ESLint warnings
  docs/js/viewer.js
Labels: enhancement

#437 Add PEP8 test
  docs/guide/generate_objects_doc.py
  docs/tests/test_menus.py
  docs/tests/test_titles.py
  projects/default/controllers/ros/headersFromMSG.py
  projects/default/controllers/ros/headersFromSRV.py
  projects/default/controllers/ros/headersGenerator.py
  projects/default/controllers/sumo_supervisor/Objects.py
  projects/default/controllers/sumo_supervisor/SumoSupervisor.py
  projects/default/controllers/sumo_supervisor/WebotsVehicle.py
  projects/default/controllers/sumo_supervisor/sumo_supervisor.py
  projects/humans/pedestrian/controllers/pedestrian/pedestrian.py
  projects/objects/factory/valves/controllers/valve_turner/valve_turner.py
  projects/robots/gctronic/e-puck/transfer/populate_xc16_directory.py
  projects/robots/saeon/controllers/vehicle_driver_altino/vehicle_driver_altino.py
  projects/robots/softbank/nao/controllers/nao_demo_python/nao_demo_python.py
  projects/samples/contests/rockin/package_generator.py
  projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/marathon.py
  projects/samples/robotbenchmark/maze_runner/controllers/move_in_maze/move_in_maze.py
  projects/samples/robotbenchmark/maze_runner/controllers/supervisor/supervisor.py
  projects/vehicles/worlds/highway_overtake_net/generate_route.py
  projects/vehicles/worlds/sumo_interface_example_net/generate_route_file.py
  projects/vehicles/worlds/sumo_interface_example_net/plugin.py
  resources/osm_importer/elevation.py
  resources/osm_importer/importer.py
  resources/osm_importer/osm_objects.py
  resources/osm_importer/parser_objects.py
  resources/osm_importer/projection.py
  resources/osm_importer/settings.py
  resources/osm_importer/utils/misc_utils.py
  resources/osm_importer/webots_objects/area.py
  resources/osm_importer/webots_objects/barrier.py
  resources/osm_importer/webots_objects/building.py
  resources/osm_importer/webots_objects/parking_lines.py
  resources/osm_importer/webots_objects/river.py
  resources/osm_importer/webots_objects/road.py
  resources/osm_importer/webots_objects/speed_limit.py
  resources/osm_importer/webots_objects/webots_object.py
  resources/sumo_exporter/crossroad.py
  resources/sumo_exporter/exporter.py
  resources/sumo_exporter/math_utils.py
  resources/sumo_exporter/road.py
  resources/web/server/session_server.py
  resources/web/server/simulation_server.py
  scripts/icon_studio/controllers/icon_creator/icon_creator.py
  src/packaging/check_rpath.py
  tests/manual_tests/test_worlds_warnings.py
  tests/sources/requirements.txt
  tests/sources/test_cppcheck.py
  tests/sources/test_license.py
  tests/sources/test_pep8.py
Labels: enhancement

#436 Fix Cylinder boundingObject representation
  change_logs/ChangeLog.html
  src/webots/nodes/WbCapsule.cpp
  src/webots/nodes/WbCylinder.cpp
  src/webots/nodes/WbGeometry.hpp
  src/wren/StaticMesh.cpp
Labels: bug, enhancement

#440 Add Execution Flag to the Header Version Test.
  tests/sources/test_header_version.py
Labels: enhancement

#443 Hotfix RosGyro
  projects/default/controllers/ros/RosGyro.cpp
Labels: bug

#444 Document RosInertialUnit Axes Switch
  projects/default/controllers/ros/RosInertialUnit.cpp
Labels: enhancement

#445 Fix Crash Loading Normals without NormalIndex
  src/webots/nodes/utils/WbTriangleMesh.cpp
  tests/rendering/worlds/normals.wbt
Labels: bug

#447 Fix broken if conditions in webots.js parsePointSet
  resources/web/wwi/x3d.js
Labels: bug

#446 Remove remaining references to x3dom
  docs/guide/web-scene.md
  resources/web/wwi/webots.js
  src/webots/gui/WbStreamingServer.cpp
  src/webots/gui/WbStreamingServer.hpp
  src/webots/nodes/WbCylinder.cpp
  src/webots/nodes/WbIndexedFaceSet.cpp
  src/webots/nodes/WbLight.cpp
  src/webots/vrml/WbVrmlWriter.cpp
Labels: enhancement

#448 Improve WbFieldChecker functions names
  src/webots/nodes/WbAbstractCamera.cpp
  src/webots/nodes/WbAccelerometer.cpp
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbBox.cpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbCapsule.cpp
  src/webots/nodes/WbColor.cpp
  src/webots/nodes/WbCompass.cpp
  src/webots/nodes/WbCone.cpp
  src/webots/nodes/WbContactProperties.cpp
  src/webots/nodes/WbCylinder.cpp
  src/webots/nodes/WbDistanceSensor.cpp
  src/webots/nodes/WbElevationGrid.cpp
  src/webots/nodes/WbEmitter.cpp
  src/webots/nodes/WbFocus.cpp
  src/webots/nodes/WbFog.cpp
  src/webots/nodes/WbGps.cpp
  src/webots/nodes/WbGyro.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbIndexedFaceSet.cpp
  src/webots/nodes/WbInertialUnit.cpp
  src/webots/nodes/WbLensFlare.cpp
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/WbLight.cpp
  src/webots/nodes/WbLightSensor.cpp
  src/webots/nodes/WbMaterial.cpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbMuscle.cpp
  src/webots/nodes/WbPbrAppearance.cpp
  src/webots/nodes/WbPen.cpp
  src/webots/nodes/WbPhysics.cpp
  src/webots/nodes/WbPlane.cpp
  src/webots/nodes/WbPointLight.cpp
  src/webots/nodes/WbPositionSensor.cpp
  src/webots/nodes/WbRadar.cpp
  src/webots/nodes/WbRangeFinder.cpp
  src/webots/nodes/WbReceiver.cpp
  src/webots/nodes/WbRecognition.cpp
  src/webots/nodes/WbSphere.cpp
  src/webots/nodes/WbSpotLight.cpp
  src/webots/nodes/WbTouchSensor.cpp
  src/webots/nodes/WbTrackWheel.cpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/nodes/WbWorldInfo.cpp
  src/webots/nodes/WbZoom.cpp
  src/webots/nodes/utils/WbFieldChecker.cpp
  src/webots/nodes/utils/WbFieldChecker.hpp
Labels: enhancement

#407 Fix icosphere vs. UV sphere import/export
  change_logs/ChangeLog.html
  docs/reference/images/sphere_tessellation.png
  docs/reference/sphere.md
  include/wren/static_mesh.h
  projects/objects/balls/protos/PingPongBall.proto
  projects/objects/balls/protos/icons/SoccerBall.png
  projects/objects/balls/protos/textures/football_base_color.jpg
  projects/objects/balls/protos/textures/football_normal.jpg
  projects/objects/solids/protos/SolidRoundedBox.proto
  projects/robots/adept/pioneer3/protos/Pioneer3dx.proto
  projects/robots/softbank/nao/protos/LollipopCandy.proto
  projects/samples/rendering/protos/SphereGrid.proto
  resources/nodes/Sphere.wrl
  resources/web/wwi/x3d.js
  src/webots/nodes/WbRadar.cpp
  src/webots/nodes/WbRangeFinder.cpp
  src/webots/nodes/WbSphere.cpp
  src/webots/nodes/WbSphere.hpp
  src/webots/nodes/WbSpotLight.cpp
  src/webots/nodes/utils/WbVisualBoundingSphere.cpp
  src/webots/nodes/utils/WbVisualBoundingSphere.hpp
  src/webots/vrml/WbSFBool.hpp
  src/wren/Config.cpp
  src/wren/StaticMesh.cpp
  src/wren/StaticMesh.hpp
  src/wren/demo/default.cpp
  src/wren/demo/phong.cpp
  tests/api/worlds/pen_sphere_scaled.wbt
Labels: bug

#122 Controlled BallJoint
  change_logs/ChangeLog.html
  docs/reference/balljoint.md
  docs/reference/balljointparameters.md
  docs/reference/images/ballJoint.png
  docs/reference/joint.md
  docs/reference/jointparameters.md
  docs/reference/node-chart.md
  resources/nodes/BallJoint.wrl
  resources/nodes/BallJointParameters.wrl
  resources/nodes/JointParameters.wrl
  src/webots/Makefile
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbBallJoint.hpp
  src/webots/nodes/WbBallJointParameters.cpp
  src/webots/nodes/WbBallJointParameters.hpp
  src/webots/nodes/WbBasicJoint.cpp
  src/webots/nodes/WbHinge2Joint.cpp
  src/webots/nodes/WbHinge2Joint.hpp
  src/webots/nodes/WbHingeJoint.cpp
  src/webots/nodes/WbJoint.hpp
  src/webots/nodes/WbJointDevice.cpp
  src/webots/nodes/WbJointParameters.cpp
  src/webots/nodes/WbJointParameters.hpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbMotor.hpp
  src/webots/nodes/WbRotationalMotor.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  tests/physics/controllers/ball_joint_vs_hinge_joints/.gitignore
  tests/physics/controllers/ball_joint_vs_hinge_joints/Makefile
  tests/physics/controllers/ball_joint_vs_hinge_joints/ball_joint_vs_hinge_joints.c
  tests/physics/controllers/joint_controller/.gitignore
  tests/physics/controllers/joint_controller/Makefile
  tests/physics/controllers/joint_controller/joint_controller.c
  tests/physics/worlds/ball_joint_vs_hinge_joints.wbt
Labels: enhancement

#450 Test Multiple Python Version with Travis
  .travis.yml
  docs/local_exporter.py
  docs/tests/test_images.py
  projects/default/controllers/ros/headersFromMSG.py
  projects/default/controllers/ros/headersFromSRV.py
  projects/default/controllers/ros/headersGenerator.py
  projects/default/controllers/sumo_supervisor/Objects.py
  projects/default/controllers/sumo_supervisor/SumoDisplay.py
  projects/default/controllers/sumo_supervisor/SumoSupervisor.py
  projects/default/controllers/sumo_supervisor/sumo_supervisor.py
  projects/humans/pedestrian/controllers/pedestrian/pedestrian.py
  projects/robots/gctronic/e-puck/transfer/populate_xc16_directory.py
  projects/robots/tinkerbots/controllers/two_wheels_vehicle/two_wheels_vehicle.py
  projects/robots/tinkerbots/controllers/vision_car/vision_car.py
  projects/samples/contests/rockin/package_generator.py
  projects/samples/robotbenchmark/square_path/controllers/square_path_supervisor/real_robot_performance.py
  projects/vehicles/worlds/sumo_interface_example_net/generate_route_file.py
  resources/osm_importer/importer.py
  resources/osm_importer/parser_objects.py
  resources/osm_importer/webots_objects/road.py
  resources/osm_importer/webots_objects/speed_limit.py
  resources/sumo_exporter/road.py
  scripts/icon_studio/controllers/leds/leds.py
  src/packaging/check_rpath.py
  tests/command_test.py
  tests/manual_tests/controllers/procedural_proto_regenerator/procedural_proto_regenerator.py
  tests/manual_tests/test_worlds_warnings.py
  tests/sources/test_clang_format.py
  tests/sources/test_icons.py
  tests/sources/test_pep8.py
Labels: enhancement

#449 Fix test_cppcheck.py
  change_logs/ChangeLog.html
  projects/default/controllers/ros/RosCamera.cpp
  projects/default/controllers/ros/RosSensor.cpp
  projects/robots/gctronic/e-puck/controllers/e-puck2_server/e-puck2_server.c
  projects/robots/gctronic/e-puck/controllers/e-puck2_server/play_melody.h
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/Camera.cpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/EPuckCommandPacket.cpp
  projects/robots/kondo/khr-2hv/controllers/khr-2hv_demo/rcb3_simulator.cpp
  projects/robots/mobsya/thymio/controllers/thymio2_demo/thymio2_demo.c
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/RemoteControlWidget.cpp
  projects/robots/robotis/bioloid/controllers/bioloid_dog/Robot.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/RobotisOp2OutputPacket.cpp
  projects/robots/softbank/nao/controllers/nao_soccer_supervisor/nao_soccer_supervisor.c
  projects/robots/sony/aibo/controllers/ers7_mimic/ers7_mimic.c
  projects/samples/contests/ratslife/controllers/contest_manager/maze_builder.c
  projects/samples/curriculum/controllers/intermediate_behavior_based/intermediate_behavior_based.c
  projects/samples/curriculum/controllers/intermediate_behavior_based/intermediate_behavior_based_corr.c
  projects/samples/curriculum/controllers/intermediate_lfm/intermediate_lfm.c
  projects/samples/curriculum/controllers/novice_linear_camera/novice_linear_camera.c
  projects/samples/howto/controllers/vision/vision.cpp
  projects/samples/robotbenchmark/include/robotbenchmark.h
  projects/vehicles/controllers/autonomous_vehicle/autonomous_vehicle.c
  src/lib/Controller/api/remote_control.c
  src/lib/Controller/api/supervisor.c
  src/wren/Cache.cpp
  src/wren/Cache.hpp
  src/wren/Font.cpp
  src/wren/PostProcessingEffect.cpp
  src/wren/PostProcessingEffect.hpp
  src/wren/ShadowVolumeCaster.cpp
  tests/sources/test_cppcheck.py
Labels: bug

#456 Hotfix Windows Packaging
  src/packaging/exist_in_projects.txt
  src/packaging/exist_in_projects_linux.txt
  src/packaging/exist_in_projects_mac.txt
Labels: bug

#452 Add Simple Example of Hinge2Joint and BallJoint
  change_logs/ChangeLog.html
  docs/guide/images/samples/motor2.png
  docs/guide/images/samples/motor3.png
  docs/guide/samples-devices.md
  projects/samples/devices/controllers/motor2/.gitignore
  projects/samples/devices/controllers/motor2/Makefile
  projects/samples/devices/controllers/motor2/motor2.c
  projects/samples/devices/controllers/motor3/.gitignore
  projects/samples/devices/controllers/motor3/Makefile
  projects/samples/devices/controllers/motor3/motor3.c
  projects/samples/devices/worlds/.motor2.wbproj
  projects/samples/devices/worlds/.motor3.wbproj
  projects/samples/devices/worlds/motor2.wbt
  projects/samples/devices/worlds/motor3.wbt
Labels: enhancement

#337 Improve tutorial 2
  docs/guide/images/tutorial_ball.png
  docs/guide/images/tutorial_def_use.png
  docs/guide/images/tutorial_walls.png
  docs/guide/tutorial-2-modification-of-the-environment-20-minutes.md
  projects/samples/tutorials/worlds/obstacles.wbt
Labels: enhancement

#461 Macos Travis Test
  .travis.yml
  tests/sources/test_clang_format.py
Labels: enhancement

#464 Fix wwi Make Cleanse
  Makefile
  resources/Makefile
  resources/web/wwi/Makefile
Labels: bug

#468 Enhancement appearance thumbnail
  docs/guide/appearances.md
  docs/guide/generate_objects_doc.py
  docs/guide/images/appearances/Asphalt.thumbnail.png
  docs/guide/images/appearances/BrushedAluminium.thumbnail.png
  docs/guide/images/appearances/CarpetFibers.thumbnail.png
  docs/guide/images/appearances/ChequeredParquetry.thumbnail.png
  docs/guide/images/appearances/CorrodedMetal.thumbnail.png
  docs/guide/images/appearances/CorrugatedMetal.thumbnail.png
  docs/guide/images/appearances/DamascusSteel.thumbnail.png
  docs/guide/images/appearances/ElectricConduit.thumbnail.png
  docs/guide/images/appearances/FlexibleAluminiumDuct.thumbnail.png
  docs/guide/images/appearances/GalvanizedMetal.thumbnail.png
  docs/guide/images/appearances/GlossyPaint.thumbnail.png
  docs/guide/images/appearances/HammeredCopper.thumbnail.png
  docs/guide/images/appearances/Leather.thumbnail.png
  docs/guide/images/appearances/MattePaint.thumbnail.png
  docs/guide/images/appearances/MetalPipePaint.thumbnail.png
  docs/guide/images/appearances/OldSteel.thumbnail.png
  docs/guide/images/appearances/OsbWood.thumbnail.png
  docs/guide/images/appearances/PaintedWood.thumbnail.png
  docs/guide/images/appearances/Parquetry.thumbnail.png
  docs/guide/images/appearances/Plaster.thumbnail.png
  docs/guide/images/appearances/RedBricks.thumbnail.png
  docs/guide/images/appearances/RoughConcrete.thumbnail.png
  docs/guide/images/appearances/RoughOak.thumbnail.png
  docs/guide/images/appearances/RoughPine.thumbnail.png
  docs/guide/images/appearances/Roughcast.thumbnail.png
  docs/guide/images/appearances/RustyMetal.thumbnail.png
  docs/guide/images/appearances/SandyGround.thumbnail.png
  docs/guide/images/appearances/ScrewThread.thumbnail.png
  docs/guide/images/appearances/ShinyLeather.thumbnail.png
  docs/guide/images/appearances/SquarePavement.thumbnail.png
  docs/guide/images/appearances/StonePavement.thumbnail.png
  docs/guide/images/appearances/ThreadMetalPlate.thumbnail.png
  docs/guide/images/appearances/VarnishedPine.thumbnail.png
  docs/guide/images/appearances/WireFence.thumbnail.png
  docs/guide/images/generate_thumbnails.py
  docs/guide/object-apartment-structure.md
  docs/guide/object-computers.md
  docs/guide/object-factory.md
  docs/guide/object-floors.md
  docs/guide/object-freight.md
  docs/guide/object-lights.md
  docs/guide/object-school-furniture.md
  docs/guide/object-solids.md
  docs/guide/object-telephone.md
  docs/tests/test_images.py
Labels: enhancement

#470 Robot Component: Fullscreen button
  docs/css/images/fullscreen.png
  docs/css/images/fullscreen_hover.png
  docs/css/webots-doc.css
  docs/js/showdown-extensions.js
  docs/js/viewer.js
Labels: enhancement

#463 Upgrade to `three.js r104`
  docs/dependencies.txt
  docs/local_exporter.py
  resources/web/streaming_viewer/index.html
  resources/web/wwi/.gitignore
  resources/web/wwi/Makefile
  resources/web/wwi/gpu_picker.js
Labels: bug, enhancement

#476 Fix Mac Packaging
  src/packaging/files_core.txt
  src/packaging/webots_distro.c
Labels: bug

#475 Fix Crash when Removing Background Node [to revision]
  change_logs/ChangeLog.html
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbTrack.cpp
Labels: bug

#478 Fix Various Python Regex.
  docs/tests/test_references.py
  docs/tests/test_titles.py
  resources/osm_importer/importer.py
  resources/sumo_exporter/re_definitions.py
Labels: enhancement

#469 Add Python 2.7 Deprecation Warning
  change_logs/ChangeLog.html
  resources/languages/python/controller.i
Labels: enhancement

#480 Fix Python getRangeImageArray Function
  change_logs/ChangeLog.html
  resources/languages/python/controller.i
Labels: bug

#458 Fix tutorial 3
  docs/guide/tutorial-3-appearance-15-minutes.md
Labels: enhancement

#489 ROS doc: Add link to the list of ROS services and messages.
  docs/reference/ros-api.md
Labels: enhancement

#486 Travis Package Creation Test
  .travis.yml
  projects/default/libraries/vehicle/java/Makefile
  projects/default/libraries/vehicle/python/Makefile
  projects/robots/robotis/bioloid/controllers/bioloid_dog/Robot.cpp
  projects/robots/robotis/bioloid/controllers/bioloid_dog/Robot.h
  projects/vehicles/controllers/racing_wheel/Makefile
  resources/languages/java/Makefile
  resources/languages/python/Makefile
  resources/osm_importer/osm_gui/Makefile
  src/packaging/Makefile
  src/packaging/webots_distro.c
  tests/test_compilation.py
Labels: enhancement

#490 fixed world's bounds check
  resources/osm_importer/importer.py
Labels: enhancement

#487 Generalize the modal window to the entire documentation
  docs/css/images/load_animation.gif
  docs/css/webots-doc.css
  docs/js/viewer.js
Labels: enhancement

#496 Removed class declaration in Python code
  docs/guide/tutorial-6-4-wheels-robot.md
Labels: bug

#501 Improve documentation of Light.ambientIntensity
  docs/reference/light.md
Labels: enhancement

#503 Typo
  docs/guide/samples-devices.md
Labels: bug

#504 Improve hyperlink colors (hotfix)
  docs/css/webots-doc.css
Labels: enhancement

#494 Fix Geometry Update not Awakening Solids
  change_logs/ChangeLog.html
  src/webots/engine/WbSimulationCluster.cpp
  src/webots/nodes/WbBox.cpp
  src/webots/nodes/WbCapsule.cpp
  src/webots/nodes/WbCylinder.cpp
  src/webots/nodes/WbElevationGrid.cpp
  src/webots/nodes/WbIndexedFaceSet.cpp
  src/webots/nodes/WbSphere.cpp
  src/webots/ode/WbOdeGeomData.hpp
  tests/lib/ts_assertion.h
  tests/physics/controllers/kinematic_geometry_update/.gitignore
  tests/physics/controllers/kinematic_geometry_update/Makefile
  tests/physics/controllers/kinematic_geometry_update/kinematic_geometry_update.c
  tests/physics/worlds/kinematic_geometry_update.wbt
Labels: bug

#473 Support Equirectangular Cubemaps in webots.min.js
  resources/web/wwi/Makefile
  resources/web/wwi/equirectangular_to_cube_generator.js
  resources/web/wwi/texture_loader.js
  resources/web/wwi/x3d.js
  resources/web/wwi/x3d_scene.js
Labels: enhancement

#507 Removed unsupported ElevationGrid color fields
  docs/reference/elevationgrid.md
  projects/robots/clearpath/moose/worlds/moose_demo.wbt
  projects/robots/neuronics/ipr/worlds/ipr_factory.wbt
  projects/samples/curriculum/worlds/advanced_path_planning.wbt
  projects/samples/howto/worlds/biped.wbt
  resources/nodes/ElevationGrid.wrl
  src/webots/nodes/WbElevationGrid.cpp
  src/webots/nodes/WbElevationGrid.hpp
  src/webots/nodes/WbTrack.cpp
Labels: bug

#509 Update ChangeLog.html
  change_logs/ChangeLog.html
Labels: enhancement
