Repository cyberbotics/webots, pull requests merged in 2019-10, with the labels that each got.

#925 Web interface: document fast button and world selection
  resources/web/wwi/help.php
  resources/web/wwi/help_window.js
  resources/web/wwi/images/documentation/help_web_interface_with_fast.png
  resources/web/wwi/images/documentation/help_world_selection.png
Labels: enhancement

#855 Feature snapcraft build
  .gitignore
  .travis.yml
  Makefile
  README.md
  dependencies/Makefile.linux
  include/controller/c/webots/types.h
  resources/Makefile.java.include
  src/install_scripts/qt_linux_installer.sh
  src/packaging/.gitignore
  src/packaging/Makefile
  src/packaging/files_core.txt
  src/packaging/webots.desktop
  src/packaging/webots_distro.c
  src/webots/Makefile
  src/webots/core/WbDesktopServices.cpp
  src/webots/core/WbDesktopServices.hpp
  src/webots/core/WbFileUtil.cpp
  src/webots/core/WbSysInfo.cpp
  src/webots/core/WbSysInfo.hpp
  src/webots/gui/WbAboutBox.cpp
  src/webots/gui/WbDocumentation.cpp
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbNewControllerWizard.cpp
  src/webots/gui/WbNewVersionDialog.cpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbSingleTaskApplication.cpp
  src/webots/gui/WbVideoRecorder.cpp
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbWebotsUpdateDialog.cpp
  src/webots/launcher/webots-linux.sh
  src/webots/scene_tree/WbAddNodeDialog.cpp
Labels: enhancement

#931 Fix libraries names in Changelog
  docs/reference/changelog-r2019.md
Labels: enhancement

#932 Fix Pi display
  docs/reference/propeller.md
Labels: bug

#935 Fix macOS package creation
  src/packaging/webots_distro.c
Labels: bug

#936 Fix C3D file not defined.
  projects/humans/c3d/controllers/c3d_viewer/c3d_viewer.py
  projects/humans/c3d/protos/C3dViewer.proto
Labels: bug

#938 Fix default values for geometries
  docs/reference/changelog-r2019.md
  resources/web/wwi/x3d.js
Labels: bug

#940 Removed Qt Wayland platform plugin
  src/install_scripts/qt_linux_installer.sh
  src/packaging/files_core.txt
Labels: enhancement

#941 Cleanup libpci
  .travis.yml
  docs/guide/installation-procedure.md
Labels: enhancement

#945 Fix ODE links.
  docs/guide/modeling.md
  docs/guide/programming.md
  docs/guide/tutorial-5-compound-solid-and-physics-attributes.md
Labels: bug

#942 Re-order Guided Tour
  projects/guided_tour.txt
Labels: enhancement

#946 macOS : Remove warning when building a controller in a directory containing spaces
  resources/Makefile.include
Labels: bug

#947 Drop the clean_shm.sh script
  src/bin/clean_shm.sh
Labels: invalid

#948 Improve external URLs robustness
  src/webots/core/WbDesktopServices.cpp
  src/webots/gui/WbMainWindow.cpp
Labels: bug

#953 Apply the update_all_worlds.py script
  projects/samples/devices/worlds/camera.wbt
  projects/samples/devices/worlds/camera_motion_blur.wbt
  projects/samples/devices/worlds/camera_noise_mask.wbt
Labels: enhancement

#951 Fix Propeller VRML export
  src/webots/nodes/WbPropeller.cpp
Labels: bug, regression

#954 Update Mavic 2 PRO web component
  docs/guide/scenes/mavic-2-pro/mavic-2-pro.meta.json
  docs/guide/scenes/mavic-2-pro/mavic-2-pro.x3d
  docs/guide/scenes/mavic-2-pro/textures/brushed_aluminium_base_color.jpg
  docs/guide/scenes/mavic-2-pro/textures/brushed_aluminium_normal.jpg
  docs/guide/scenes/mavic-2-pro/textures/brushed_aluminium_roughness.jpg
Labels: enhancement

#956 Fix OSM importer dependencies installation
  docs/automobile/openstreetmap-importer.md
Labels: bug

#958 Fix C3D runtime issue.
  projects/humans/c3d/controllers/c3d_viewer/c3d_viewer.py
Labels: bug

#959 Update webots_distro.c
  src/packaging/webots_distro.c
Labels: bug

#963 Revert OpenAL modifications, time to find a better fix
  dependencies/Makefile.linux
Labels: enhancement

#968 Update release date
  docs/reference/changelog-r2019.md
Labels: invalid

#966 Fixed clean target
  src/packaging/Makefile
Labels: enhancement

#972 Fix libopenal soft link
  dependencies/Makefile.linux
Labels: bug

#806 Fix package creation on Ubuntu 18.04
  src/packaging/webots_distro.c
Labels: bug

#974 Fix clock not published in synchronized mode.
  projects/default/controllers/ros/Ros.cpp
  projects/default/controllers/ros/Ros.hpp
Labels: bug

#982 Doc improve tutorial
  docs/guide/tutorial-3-appearance.md
  docs/guide/tutorial-6-4-wheels-robot.md
Labels: enhancement

#976 Qt5 update on Windows
  docs/reference/changelog-r2019.md
Labels: enhancement

#978 Fix Extern Controller Synchronization
  docs/guide/running-extern-robot-controllers.md
  docs/reference/changelog-r2019.md
  projects/robots/k-team/khepera3/controllers/khepera3_gripper/khepera3_gripper.c
  src/webots/control/WbControlledWorld.cpp
  src/webots/control/WbControlledWorld.hpp
  tests/api/controllers/extern/extern.c
  tests/api/worlds/extern.wbt
Labels: bug, enhancement

#990 We support Java 8 and later versions
  docs/guide/using-java.md
Labels: enhancement

#984 Fix appveyor build
  .appveyor-build-tag.yml
  .appveyor-build.yml
  bin/.gitignore
  resources/web/wwi/Makefile
  src/install_scripts/.gitignore
  src/install_scripts/bash_profile.appveyor
  src/install_scripts/msys.sh
  src/install_scripts/msys64_installer.sh
  src/install_scripts/nodejs_windows_installer.sh
Labels: bug

#981 Improve PROTO section
  .travis.yml
  docs/reference/images/three_chairs_proto_example.png
  docs/reference/images/three_chairs_proto_example.thumbnail.jpg
  docs/reference/images/two_chairs_v7-2-0.png
  docs/reference/proto-definition.md
  docs/reference/proto-example.md
Labels: enhancement

#992 Fix better scene tree naming
  docs/reference/changelog-r2019.md
  src/webots/scene_tree/WbTreeItem.cpp
Labels: enhancement

#973 Fixed extern controllers on snap
  docs/guide/installation-procedure.md
  docs/guide/running-extern-robot-controllers.md
  src/lib/Controller/api/system.c
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/launcher/webots-linux.sh
Labels: bug

#987 Fix Travis Tests
  .travis.yml
  tests/ros.sh
Labels: enhancement

#983 New geometry: rectangle
  projects/objects/geometries/protos/Rectangle.proto
  projects/objects/geometries/protos/icons/Rectangle.png
  scripts/icon_studio/controllers/icon_creator/objects.json
Labels: enhancement

#926 E-puck 2 long-range distance sensor
  docs/guide/epuck.md
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/DeviceManager.cpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/DeviceManager.hpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/Wrapper.cpp
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.c
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.html
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.js
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/images/e-puck2.png
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/images/placeholder.png
  projects/robots/gctronic/e-puck/protos/E-puck.proto
  projects/robots/gctronic/e-puck/worlds/e-puck2.wbt
Labels: enhancement

#1000 Update FUNDING.yml
  .github/FUNDING.yml
Labels: enhancement

#996 Port simulation_server.py to Python3
  docs/reference/changelog-r2019.md
  resources/web/server/config/simulation/local.json
  resources/web/server/session_server.py
  resources/web/server/simulation_server.py
Labels: bug

#1003 Fix snap external controllers
  docs/guide/running-extern-robot-controllers.md
Labels: bug

#999 Fix possible crash with external controllers.
  src/webots/control/WbControlledWorld.cpp
Labels: bug

#1005 Added an explanation message for MATLAB controllers / snap
  src/webots/control/WbController.cpp
  src/webots/core/WbSysInfo.hpp
  src/webots/gui/WbPreferencesDialog.cpp
Labels: enhancement

#994 Check MD5 for dependencies
  dependencies/Makefile.linux
  dependencies/Makefile.mac
  dependencies/Makefile.windows
Labels: enhancement

#1010 macOS: Fix MD5 check
  dependencies/Makefile.mac
Labels: bug

#1009 Fix exporting first translation/rotation field change
  docs/reference/changelog-r2019.md
  src/webots/engine/WbAnimationRecorder.cpp
Labels: bug

#1008 Fixed clang format version problem
  .appveyor-test-sources-scheduled.yml
  .appveyor.yml
  .gitignore
  .travis.yml
  dependencies/.clang-format-6
  dependencies/.clang-format-9
  dependencies/Makefile.linux
  dependencies/Makefile.mac
  dependencies/Makefile.windows
  tests/sources/test_clang_format.py
Labels: bug

#1015 Fix exception in session_server.py script
  resources/web/server/session_server.py
Labels: bug

#1021 Fix Travis not Publishing Releases
  .travis.yml
Labels: bug

#1023 Fix Clang Format Clean
  dependencies/Makefile.linux
  dependencies/Makefile.mac
  dependencies/Makefile.windows
Labels: bug

#1027 Fix logging messages in the console before GUI initialization
  docs/reference/changelog-r2019.md
  src/webots/core/WbLog.cpp
  src/webots/core/WbLog.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbStreamingServer.cpp
Labels: bug

#1030 Upgraded clang-format to version 9 on appveyor
  .appveyor-test-sources-scheduled.yml
Labels: enhancement

#1035 Update cppcheck version to 1.89 on Travis.
  tests/sources/bin/cfg/std.cfg
  tests/sources/bin/cppcheck
Labels: enhancement

#1033 Fixed Display.imageNew from array in Python
  docs/reference/changelog-r2019.md
  resources/languages/cpp/Field.cpp
  resources/languages/python/controller.i
Labels: bug

#1037 Fix problematic lsb_release in Makefile.os.include
  resources/Makefile.os.include
  src/lib/Controller/Makefile
Labels: bug

#1025 Add support for multiple table types in documentation
  docs/automobile/car-library.md
  docs/automobile/driver-library.md
  docs/doc.php
  docs/guide/running-extern-robot-controllers.md
  docs/guide/tutorial-1-your-first-simulation-in-webots.md
  docs/guide/tutorial-4-more-about-controllers.md
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/js/showdown-extensions.js
  docs/js/viewer.js
  docs/reference/accelerometer.md
  docs/reference/brake.md
  docs/reference/camera.md
  docs/reference/compass.md
  docs/reference/connector.md
  docs/reference/device.md
  docs/reference/differentialwheels.md
  docs/reference/display.md
  docs/reference/distancesensor.md
  docs/reference/emitter.md
  docs/reference/gps.md
  docs/reference/gyro.md
  docs/reference/inertialunit.md
  docs/reference/joystick.md
  docs/reference/keyboard.md
  docs/reference/led.md
  docs/reference/lidar.md
  docs/reference/lightsensor.md
  docs/reference/motion.md
  docs/reference/motor.md
  docs/reference/mouse.md
  docs/reference/pen.md
  docs/reference/positionsensor.md
  docs/reference/radar.md
  docs/reference/rangefinder.md
  docs/reference/receiver.md
  docs/reference/robot.md
  docs/reference/speaker.md
  docs/reference/supervisor.md
  docs/reference/touchsensor.md
  docs/reference/utility-functions.md
  resources/web/wwi/request_methods.js
Labels: enhancement

#1039 Set the timeout to 30 seconds instead of 10 to minimize timeout failures on Travis
  tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py
Labels: bug

#1042 Fix cleanse rule if npm is not installed
  resources/web/wwi/Makefile
Labels: bug, enhancement

#1045 Fix PEP8 Test Failure.
  tests/sources/test_pep8.py
Labels: bug

#1044 macOS: Update Qt
  dependencies/Makefile.mac
  docs/reference/changelog-r2019.md
  src/install_scripts/qt_mac_installer.sh
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/main.cpp
Labels: enhancement
