Repository cyberbotics/webots, pull requests merged in 2019-04, with the labels that each got.

#331 Add links from docs to github folders and files for Objects
  docs/guide/generate_objects_doc.py
  docs/guide/object-advertising-board.md
  docs/guide/object-apartment-structure.md
  docs/guide/object-backgrounds.md
  docs/guide/object-balls.md
  docs/guide/object-bedroom.md
  docs/guide/object-buildings.md
  docs/guide/object-cabinet.md
  docs/guide/object-chairs.md
  docs/guide/object-computers.md
  docs/guide/object-create-wall.md
  docs/guide/object-drinks.md
  docs/guide/object-factory.md
  docs/guide/object-floors.md
  docs/guide/object-fruits.md
  docs/guide/object-garden.md
  docs/guide/object-geometries.md
  docs/guide/object-kitchen.md
  docs/guide/object-lego.md
  docs/guide/object-lights.md
  docs/guide/object-living-room-furniture.md
  docs/guide/object-mirror.md
  docs/guide/object-obstacles.md
  docs/guide/object-paintings.md
  docs/guide/object-panels.md
  docs/guide/object-plants.md
  docs/guide/object-road.md
  docs/guide/object-robotstadium.md
  docs/guide/object-rocks.md
  docs/guide/object-school-furniture.md
  docs/guide/object-shapes.md
  docs/guide/object-solids.md
  docs/guide/object-stairs.md
  docs/guide/object-street-furniture.md
  docs/guide/object-tables.md
  docs/guide/object-television.md
  docs/guide/object-toys.md
  docs/guide/object-traffic.md
  docs/guide/object-trees.md
Labels: enhancement

#334 Improve Tutorial 6
  docs/guide/tutorial-6-4-wheels-robot.md
Labels: enhancement

#297 Improve THREEjs light model
  resources/web/wwi/.gitignore
  resources/web/wwi/x3d.js
  resources/web/wwi/x3d_scene_manager.js
  src/webots/gui/WbHtmlExportDialog.cpp
  src/webots/gui/WbHtmlExportDialog.hpp
  src/webots/gui/WbStreamingServer.cpp
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbBaseNode.hpp
  src/webots/nodes/WbCubemap.cpp
  src/webots/nodes/WbCubemap.hpp
  src/webots/nodes/WbImageTexture.hpp
  src/webots/nodes/WbLight.cpp
  src/webots/nodes/WbPbrAppearance.cpp
  src/webots/vrml/WbVrmlWriter.cpp
Labels: enhancement

#318 Improve tutorial 1
  docs/guide/tutorial-1-your-first-simulation-in-webots-20-minutes.md
  docs/reference/proto-definition.md
  docs/reference/proto.md
Labels: enhancement

#338 Fix PROTO definition
  docs/reference/proto-definition.md
  docs/reference/proto.md
Labels: enhancement

#339 Cleanup Controller Templates.
  resources/templates/controllers/template.c
  resources/templates/controllers/template.cpp
  resources/templates/controllers/template.java
  resources/templates/controllers/template.m
  resources/templates/controllers/template.py
Labels: enhancement

#340 Use Roughness for Infra-Red Distance Sensors.
  change_logs/ChangeLog.html
  docs/reference/distancesensor.md
  projects/robots/gctronic/e-puck/worlds/e-puck_line.wbt
  projects/robots/gctronic/e-puck/worlds/e-puck_line_demo.wbt
  src/webots/nodes/WbDistanceSensor.cpp
  src/webots/nodes/WbPbrAppearance.cpp
  src/webots/nodes/WbPbrAppearance.hpp
  src/webots/nodes/WbShape.cpp
  src/webots/nodes/WbShape.hpp
  tests/api/controllers/distance_sensor_infra-red/distance_sensor_infra-red.c
  tests/api/worlds/distance_sensor_infra-red.wbt
Labels: enhancement

#343 Fix Crash when Copy-Pasting some Node.
  change_logs/ChangeLog.html
  src/webots/nodes/utils/WbNodeOperations.cpp
Labels: bug

#344 Fix Assertion Failure when Adding AnimatedGeometry to Track.
  change_logs/ChangeLog.html
  src/webots/nodes/WbTrack.cpp
Labels: bug

#341 Fix file path in doc
  docs/guide/interfacing-webots-to-third-party-software-with-tcp-ip.md
Labels: enhancement

#345 Fix controller builds using a custom Java Makefile.
  change_logs/ChangeLog.html
  resources/Makefile.java.include
Labels: bug

#333 Fix maze_runner.wbt and obstacle_avoidance.wbt
  projects/objects/apartment_structure/protos/Door.proto
  projects/objects/apartment_structure/protos/Window.proto
  projects/objects/lights/protos/CeilingLight.proto
  projects/objects/school_furniture/protos/Blackboard.proto
  projects/objects/solids/protos/SolidBox.proto
  projects/samples/robotbenchmark/maze_runner/worlds/maze_runner.wbt
  projects/samples/robotbenchmark/obstacle_avoidance/worlds/obstacle_avoidance.wbt
Labels: bug

#347 Fix shadows in pick and place benchmark
  projects/objects/apartment_structure/protos/Ceiling.proto
  projects/objects/apartment_structure/protos/DoorKnob.proto
  projects/objects/apartment_structure/protos/DoorLever.proto
  projects/samples/robotbenchmark/pick_and_place/worlds/pick_and_place.wbt
Labels: enhancement

#346 Fix Missing Links in Doc
  docs/guide/interfacing-webots-to-third-party-software-with-tcp-ip.md
Labels: enhancement

#352 Remove wrong references to Ogre
  docs/guide/starting-webots.md
Labels: bug

#357 Fix check for Hinge2Joint ancestor when inserting a Muscle
  change_logs/ChangeLog.html
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbNodeUtilities.hpp
Labels: bug

#355 Removed useless alpha channels, optimized PNG file sizes
  tests/api/worlds/textures/color_checker_chart.png
  tests/api/worlds/textures/cube-texture-gradient-back.png
  tests/api/worlds/textures/cube-texture-gradient-bottom.png
  tests/api/worlds/textures/cube-texture-gradient-front.png
  tests/api/worlds/textures/cube-texture-gradient-left.png
  tests/api/worlds/textures/cube-texture-gradient-right.png
  tests/api/worlds/textures/cube-texture-gradient-top.png
  tests/api/worlds/textures/green.png
  tests/api/worlds/textures/noise_mask_opaque.png
  tests/api/worlds/textures/noise_mask_transparent.png
  tests/api/worlds/textures/track.png
  tests/api/worlds/textures/white256.png
  tests/rendering/worlds/textures/transparent.png
Labels: bug, enhancement

#364 Fix simulation_server.py for Python3
  resources/web/server/simulation_server.py
Labels: bug

#296 Fix Make Profile
  Makefile
  dependencies/Makefile.linux
  dependencies/Makefile.mac
  dependencies/Makefile.windows
  jenkins.sh
  resources/Makefile.include
  src/ode/Makefile
  src/webots/Makefile
Labels: enhancement

#365 PROTO Tutorial
  docs/guide/images/tutorial_proto.png
  docs/guide/menu.md
  docs/guide/tutorial-7-your-first-proto.md
  docs/guide/tutorial-8-using-ros.md
  docs/guide/tutorials.md
  docs/guide/using-ros.md
  docs/reference/proto-definition.md
  docs/reference/proto.md
Labels: enhancement

#370 Tutorial 7 PROTO file.
  projects/samples/tutorials/protos/FourWheelsRobot.proto
  projects/samples/tutorials/protos/icons/FourWheelsRobot.png
Labels: enhancement

#371 Fixed Python3 compatibility for the icon_creator controller
  scripts/icon_studio/controllers/icon_creator/icon_creator.py
Labels: enhancement

#369 Babel, IE and JS dependencies
  resources/web/wwi/.gitignore
  resources/web/wwi/Makefile
  resources/web/wwi/package.json
  src/install_scripts/msys64_installer.sh
Labels: enhancement

#373 Improve Spotlight default beamWidth
  change_logs/ChangeLog.html
  src/webots/nodes/WbSpotLight.cpp
Labels: enhancement

#380 Updated Qt version on Windows
  src/install_scripts/qt_windows_installer.sh
Labels: bug

#382 Hotfix better Qt5 version management on Windows
  src/install_scripts/qt_windows_installer.sh
Labels: enhancement

#383 Better check for 32 bit libController build on Windows
  src/lib/Controller/Makefile
Labels: enhancement

#374 macOS: Fix build warnings
  src/webots/Makefile
Labels: enhancement

#377 Fix Floor proto
  change_logs/ChangeLog.html
  projects/objects/floors/protos/Floor.proto
  projects/samples/robotbenchmark/humanoid_sprint/worlds/humanoid_sprint.wbt
Labels: bug

#375 THREEjs: Support environment maps
  resources/web/wwi/texture_loader.js
  resources/web/wwi/x3d_scene.js
Labels: enhancement

#390 Upgraded to new version of ICU
  src/packaging/files_msys64.txt
Labels: bug

#391 Added Python3 path before msys2 path to prevent python conflicts
  src/install_scripts/msys.sh
Labels: bug

#395 Remove unused shaders in wwi folder
  resources/web/wwi/animation.js
  resources/web/wwi/shader/point_set.frag
  resources/web/wwi/shader/point_set.vert
Labels: bug

#394 Fix IE 11 support
  resources/web/streaming_viewer/index.html
  resources/web/templates/x3d_playback.html
Labels: bug

#393 Use ES6 classes
  .eslintrc.json
  resources/web/wwi/animation.js
  resources/web/wwi/console.js
  resources/web/wwi/context_menu.js
  resources/web/wwi/dialog_window.js
  resources/web/wwi/editor.js
  resources/web/wwi/help_window.js
  resources/web/wwi/mouse_events.js
  resources/web/wwi/robot_window.js
  resources/web/wwi/selector.js
  resources/web/wwi/server.js
  resources/web/wwi/stream.js
  resources/web/wwi/toolbar.js
  resources/web/wwi/video.js
  resources/web/wwi/viewpoint.js
  resources/web/wwi/webots.js
  resources/web/wwi/x3d.js
  resources/web/wwi/x3d_scene.js
Labels: enhancement

#397 Use ES6 arrow functions, and remove the "var that = this;" pattern
  resources/web/wwi/animation.js
  resources/web/wwi/console.js
  resources/web/wwi/context_menu.js
  resources/web/wwi/dialog_window.js
  resources/web/wwi/editor.js
  resources/web/wwi/help_window.js
  resources/web/wwi/mouse_events.js
  resources/web/wwi/server.js
  resources/web/wwi/stream.js
  resources/web/wwi/texture_loader.js
  resources/web/wwi/toolbar.js
  resources/web/wwi/util.js
  resources/web/wwi/webots.js
  resources/web/wwi/x3d.js
  resources/web/wwi/x3d_scene.js
Labels: enhancement

#399 Hotfix reusing an already loaded texture in webots.js
  resources/web/wwi/texture_loader.js
Labels: bug

#402 Hotfix crash on streaming client connection
  change_logs/ChangeLog.html
  src/webots/gui/WbStreamingServer.cpp
Labels: bug

#405 Add web component for Moose robot
  scripts/web_component_studio/components.json
Labels: enhancement

#406 Use ES6 features in loops
  resources/web/wwi/animation.js
  resources/web/wwi/default_url.js
  resources/web/wwi/editor.js
  resources/web/wwi/request_methods.js
  resources/web/wwi/selector.js
  resources/web/wwi/texture_loader.js
  resources/web/wwi/toolbar.js
  resources/web/wwi/webots.js
  resources/web/wwi/x3d.js
  resources/web/wwi/x3d_scene.js
Labels: enhancement
