Repository cyberbotics/webots, pull requests merged in 2019-11, with the labels that each got.

#1053 Fixed bug in Python API with double arrays
  resources/languages/python/Makefile
  resources/languages/python/controller.i
Labels: bug

#1058 Add instructions to run web scenes on Firefox 68 or later
  docs/guide/web-scene.md
  docs/tests/test_lists.py
Labels: bug

#1059 Improve message about CORS issue when opening the web interface
  src/webots/engine/WbAnimationRecorder.cpp
  src/webots/gui/WbMainWindow.cpp
Labels: enhancement

#1060 Fix none Controllers
  src/webots/control/WbControlledWorld.cpp
  tests/api/worlds/extern.wbt
Labels: bug

#1056 Fix visual cpp templates
  resources/templates/controllers/c.sln
  resources/templates/controllers/c.vcxproj
  resources/templates/controllers/c.vcxproj.filter
  resources/templates/controllers/cpp.sln
  resources/templates/controllers/cpp.vcxproj
  resources/templates/controllers/cpp.vcxproj.filter
  src/webots/core/WbDesktopServices.cpp
  src/webots/core/WbFileUtil.cpp
Labels: bug

#1062 Fixed creation of package on Windows
  src/packaging/copy_msys64_files.py
Labels: bug

#1066 webots.min.js: compile library as module
  resources/web/wwi/.gitignore
  resources/web/wwi/Makefile
Labels: enhancement

#372 IDE section
  docs/guide/debugging-c-cpp-controllers.md
  docs/guide/development-environments.md
  docs/guide/menu.md
  docs/guide/using-c.md
  docs/guide/using-pycharm-with-webots.md
  docs/guide/using-python.md
  docs/guide/using-visual-studio-with-webots.md
  docs/guide/using-your-ide.md
  docs/tests/test_references.py
Labels: enhancement

#1069 Hotfix issues in the babel-plugin-minify-simplify update
  resources/web/wwi/Makefile
Labels: bug

#1068 Fix Windows build
  dependencies/Makefile.windows
  src/packaging/files_msys64.txt
Labels: bug

#1073 improve IK world: use a "none" controller for the root robot
  projects/robots/abb/irb/worlds/inverse_kinematics.wbt
Labels: enhancement

#1072 Cleaner fix for the npm dependency issue
  resources/web/wwi/Makefile
  resources/web/wwi/package.json
Labels: enhancement

#1074 Merge revision to develop
  dependencies/Makefile.windows
  resources/web/wwi/Makefile
  resources/web/wwi/package.json
  src/packaging/files_msys64.txt
Labels: enhancement

#1075 Fix qt platform plugin trouble
  src/webots/control/WbController.cpp
  src/webots/gui/main.cpp
Labels: bug

#1080 Removed useless include statement
  src/webots/gui/main.cpp
Labels: enhancement

#1083 Fix determism in cameras rendering order
  docs/reference/changelog-r2019.md
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/nodes/WbAbstractCamera.cpp
  src/webots/nodes/WbAbstractCamera.hpp
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbRobot.hpp
Labels: bug

#1088 webots.min.js: fix texture animation in webots.min.js
  resources/web/wwi/texture_loader.js
Labels: bug, regression

#1094 Proposal to improve nightly build publishing rules
  src/packaging/publish_release.py
Labels: enhancement

#1091 Fix Lidar cloud point access in controllers
  docs/reference/changelog-r2019.md
  src/lib/Controller/api/abstract_camera.c
  src/lib/Controller/api/abstract_camera.h
  src/webots/core/WbPosixSharedMemory.hpp
  src/webots/nodes/WbAbstractCamera.cpp
Labels: bug

#1097 image scripts: Support Python 3 and drop Python 2
  scripts/image_tools/README.md
  scripts/image_tools/clamp_hdr.py
  scripts/image_tools/convert_hdr_format.py
  scripts/image_tools/downscale_hdr.py
  scripts/image_tools/equirectangular_to_cubemap.py
  scripts/image_tools/images/hdr.py
  scripts/preferences_cleaner/preferences_cleaner.py
  tests/sources/test_license.py
Labels: enhancement

#1098 Python3 support for web component script
  scripts/preferences_cleaner/preferences_cleaner.py
  scripts/web_component_studio/controllers/web_component_studio_supervisor/web_component_studio_supervisor.py
  scripts/web_component_studio/web_component_studio.py
Labels: enhancement

#1103 Slightly improve the robotbenchmark worlds lighting
  projects/samples/robotbenchmark/maze_runner/worlds/maze_runner.wbt
  projects/samples/robotbenchmark/obstacle_avoidance/worlds/obstacle_avoidance.wbt
Labels: enhancement

#1102 Update screenshots for web interface help page
  resources/web/wwi/help.php
  resources/web/wwi/images/documentation/help_console_window.png
  resources/web/wwi/images/documentation/help_editor_menu.png
  resources/web/wwi/images/documentation/help_editor_window.png
  resources/web/wwi/images/documentation/help_info_window.png
  resources/web/wwi/images/documentation/help_robot_window.png
  resources/web/wwi/images/documentation/help_simulation_time.png
  resources/web/wwi/images/documentation/help_web_interface.png
  resources/web/wwi/images/documentation/help_web_interface_with_run.png
  resources/web/wwi/images/documentation/help_world_selection.png
Labels: enhancement

#1108 webots.min.js: Fix variable scope
  resources/web/wwi/toolbar.js
Labels: bug, regression

#884 Improve linux launcher termination
  resources/web/server/kill_old_webots_instances.py
  resources/web/server/session_server.py
  resources/web/server/simulation_server.py
  src/webots/launcher/webots-linux.sh
Labels: bug

#1110 Improve SICK LD-MRS model
  docs/guide/images/samples/sick_point_cloud.png
  docs/guide/images/samples/sick_point_cloud.thumbnail.jpg
  docs/guide/lidar-sensors.md
  docs/guide/object-factory.md
  docs/guide/samples-devices.md
  docs/reference/changelog-r2020.md
  projects/devices/sick/protos/SickLdMrs.proto
  projects/devices/sick/protos/textures/sick_ld_mrs.png
  projects/devices/sick/protos/textures/sick_ld_mrs_8l.png
  projects/devices/sick/protos/textures/sick_ld_mrs_hd.png
  projects/devices/sick/protos/textures/sick_ld_mrs_roughness.jpg
  projects/objects/factory/containers/protos/PlasticCrate.proto
  projects/samples/devices/controllers/conveyor_belt/.gitignore
  projects/samples/devices/controllers/sick_point_cloud/.gitignore
  projects/samples/devices/controllers/sick_point_cloud/Makefile
  projects/samples/devices/controllers/sick_point_cloud/sick_cloud_point
  projects/samples/devices/controllers/sick_point_cloud/sick_point_cloud.c
  projects/samples/devices/controllers/track_conveyor_belt/.gitignore
  projects/samples/devices/controllers/track_conveyor_belt/Makefile
  projects/samples/devices/controllers/track_conveyor_belt/track_conveyor_belt.c
  projects/samples/devices/worlds/.sick_point_cloud.wbproj
  projects/samples/devices/worlds/sick_point_cloud.wbt
  projects/samples/devices/worlds/track.wbt
  resources/lua/modules/webots/wbmath.lua
Labels: enhancement

#1115 Switch the service to retrieve the Webots version from Cyberbotics to GitHub
  src/webots/core/WbWebotsUpdateManager.cpp
Labels: enhancement

#1116 Move `Check for updates...` menu
  docs/guide/the-user-interface.md
  docs/reference/changelog-r2020.md
  src/webots/gui/WbGuidedTour.cpp
  src/webots/gui/WbGuidedTour.hpp
  src/webots/gui/WbMainWindow.cpp
Labels: enhancement

#1105 Fix infrared sensors vs plane collision
  docs/reference/changelog-r2019.md
  src/webots/nodes/WbPlane.cpp
  tests/api/controllers/distance_sensor_infra-red_vs_transformed_planes/.gitignore
  tests/api/controllers/distance_sensor_infra-red_vs_transformed_planes/Makefile
  tests/api/controllers/distance_sensor_infra-red_vs_transformed_planes/distance_sensor_infra-red_vs_transformed_planes.c
  tests/api/worlds/distance_sensor_infra-red_vs_transformed_planes.wbt
Labels: bug

#1117 Fix Nao.selfCollision
  docs/reference/changelog-r2019.md
  projects/robots/softbank/nao/protos/Nao.proto
Labels: bug

#1101 Add new Appearances
  docs/reference/changelog-r2019.md
  projects/appearances/protos/CorrugatedPlates.proto
  projects/appearances/protos/CorrugatedPvc.proto
  projects/appearances/protos/FormedConcrete.proto
  projects/appearances/protos/icons/CorrugatedPlates.png
  projects/appearances/protos/icons/CorrugatedPvc.png
  projects/appearances/protos/icons/FormedConcrete.png
  projects/appearances/protos/textures/corrugated_plates/corrugated_plates_base_color.jpg
  projects/appearances/protos/textures/corrugated_plates/corrugated_plates_metalness.jpg
  projects/appearances/protos/textures/corrugated_plates/corrugated_plates_normal.jpg
  projects/appearances/protos/textures/corrugated_plates/corrugated_plates_occlusion.jpg
  projects/appearances/protos/textures/corrugated_plates/corrugated_plates_roughness.jpg
  projects/appearances/protos/textures/corrugated_pvc/corrugated_pvc_base_color.jpg
  projects/appearances/protos/textures/corrugated_pvc/corrugated_pvc_metalness.jpg
  projects/appearances/protos/textures/corrugated_pvc/corrugated_pvc_normal.jpg
  projects/appearances/protos/textures/corrugated_pvc/corrugated_pvc_occlusion.jpg
  projects/appearances/protos/textures/corrugated_pvc/corrugated_pvc_roughness.jpg
  projects/appearances/protos/textures/formed_concrete/formed_concrete_base_color.jpg
  projects/appearances/protos/textures/formed_concrete/formed_concrete_normal.jpg
  projects/appearances/protos/textures/formed_concrete/formed_concrete_occlusion.jpg
  projects/appearances/protos/textures/formed_concrete/formed_concrete_roughness.jpg
  scripts/icon_studio/controllers/icon_creator/appearances.json
Labels: enhancement

#1121 SICK LD-MRS 800001S01: Improve vertical azimuth constants
  docs/guide/lidar-sensors.md
  projects/devices/sick/protos/SickLdMrs.proto
Labels: enhancement

#1123 Fixed PEP8 Test not Ignoring '.git' Folder
  tests/sources/test_pep8.py
Labels: enhancement

#1122 Fix overwriting DISPLAY variable in simulation server.py
  docs/reference/changelog-r2019.md
  resources/web/server/simulation_server.py
Labels: bug

#1125 Improve nightly upload failure error message.
  src/packaging/publish_release.py
Labels: bug

#1126 Fix typo in comment
  projects/samples/howto/plugins/robot_windows/custom_html_robot_window/custom_html_robot_window.js
Labels: enhancement

#1128 Fix spelling of JavaScript and other typos
  docs/doc.php
  docs/guide/controller-plugin.md
  docs/guide/samples-howto.md
  docs/guide/web-streaming.md
  docs/reference/robot.md
  projects/samples/howto/plugins/robot_windows/custom_html_robot_window/custom_html_robot_window.c
  projects/samples/howto/plugins/robot_windows/custom_html_robot_window/custom_html_robot_window.html
  resources/projects/plugins/robot_windows/generic/generic.c
  resources/web/wwi/webots.js
Labels: enhancement

#1131 Fixed Windows Packaging
  src/packaging/files_core.txt
Labels: bug

#1120 Escape characters before sending message to the robot window
  docs/reference/changelog-r2019.md
  resources/projects/plugins/robot_windows/generic/generic.js
  src/lib/Controller/api/default_robot_window.c
  src/webots/gui/WbRobotWindow.cpp
  src/webots/gui/WbRobotWindow.hpp
Labels: bug

#1132 Fix Robot.supervisor field value in curriculum/advanced_pattern_recognition.wbt
  projects/samples/curriculum/worlds/advanced_pattern_recognition.wbt
Labels: bug

#1133 Fix clang-format config file used in AppVeyor webots-test-sources
  .appveyor.yml
Labels: bug

#1135 SICK LD-MRS: change the way to manage the overlapping layers
  docs/guide/lidar-sensors.md
  projects/devices/sick/protos/SickLdMrs.proto
  projects/samples/devices/worlds/sick_point_cloud.wbt
Labels: enhancement

#1136 Fix Reset of Hidden Kinematic Parameters
  src/webots/nodes/WbSolid.cpp
Labels: bug

#1138 Fix Webots Compilation on Windows
  src/webots/gui/WbRobotWindow.cpp
Labels: bug

#1139 Update shape.md
  docs/reference/shape.md
Labels: enhancement
