Repository cyberbotics/webots, pull requests merged in 2019-06, with the labels that each got.

#516 Fixed wrong variable type
  projects/samples/tutorials/controllers/4_wheels_collision_avoidance/4_wheels_collision_avoidance.c
Labels: enhancement

#506 Windows: distribute patched gcc-9 instead of gcc-7
  include/wren/material.h
  resources/Makefile
  src/install_scripts/msys64_installer.sh
  src/packaging/copy_msys64_files.py
  src/packaging/files_msys64.txt
  src/wren/PhongMaterial.cpp
  src/wren/PhongMaterial.hpp
Labels: bug, enhancement

#515 Fix UnicodeDecodeError when importing OSM on windows.
  resources/osm_importer/importer.py
Labels: bug, enhancement

#519 Fix references to the dropped SphereGrid.cubeMap field
  projects/samples/rendering/worlds/physically_based_rendering.wbt
Labels: invalid

#512 Improve Dependencies Makefiles
  .travis.yml
  dependencies/Makefile.linux
  dependencies/Makefile.mac
  dependencies/Makefile.windows
  src/webots/core/WbWindowsRegistry.cpp
  tests/sources/test_pep8.py
Labels: enhancement

#521 Create FUNDING.yml
  .github/FUNDING.yml
Labels: enhancement

#513 Final code for tutorial 6
  docs/guide/matlab.md
  docs/guide/tutorial-1-your-first-simulation-in-webots-20-minutes.md
  docs/guide/tutorial-4-more-about-controllers-20-minutes.md
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/reference/accelerometer.md
  docs/reference/brake.md
  docs/reference/camera.md
  docs/reference/compass.md
  docs/reference/connector.md
  docs/reference/device.md
  docs/reference/differentialwheels.md
  docs/reference/display.md
  docs/reference/distancesensor.md
  docs/reference/emitter.md
  docs/reference/gps.md
  docs/reference/gyro.md
  docs/reference/inertialunit.md
  docs/reference/joystick.md
  docs/reference/keyboard.md
  docs/reference/led.md
  docs/reference/lidar.md
  docs/reference/lightsensor.md
  docs/reference/motion.md
  docs/reference/motor.md
  docs/reference/mouse.md
  docs/reference/pen.md
  docs/reference/positionsensor.md
  docs/reference/radar.md
  docs/reference/rangefinder.md
  docs/reference/receiver.md
  docs/reference/robot.md
  docs/reference/speaker.md
  docs/reference/supervisor.md
  docs/reference/touchsensor.md
Labels: enhancement

#526 Ported visual_tracking controller to python 3
  projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking/visual_tracking.py
Labels: enhancement

#530 Fix Controller `<extern>` Doc
  docs/reference/robot.md
Labels: bug

#533 Fixed controller to be compatible with both Python 2.7 and 3.x
  projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking/visual_tracking.py
Labels: enhancement

#538 Update README.md
  README.md
Labels: enhancement

#508 Let the streaming server to serve textures
  resources/web/wwi/server.js
  resources/web/wwi/stream.js
  resources/web/wwi/texture_loader.js
  resources/web/wwi/webots.js
  resources/web/wwi/x3d.js
  resources/web/wwi/x3d_scene.js
  src/webots/Makefile
  src/webots/core/WbHttpReply.cpp
  src/webots/core/WbHttpReply.hpp
  src/webots/gui/WbStreamingServer.cpp
  src/webots/gui/WbStreamingServer.hpp
  src/webots/gui/WbStreamingTcpServer.cpp
  src/webots/gui/WbStreamingTcpServer.hpp
Labels: enhancement

#540 Readd selection and context menu functionlity on webots.min.js for mobile devices
  resources/web/wwi/mouse_events.js
  resources/web/wwi/webots.js
Labels: bug, regression

#536 Speed-up cppcheck CI tests
  .travis.yml
  docs/guide/generate_objects_doc.py
  include/controller/c/webots/supervisor.h
  include/controller/cpp/webots/Supervisor.hpp
  projects/robots/k-team/khepera1/controllers/pipe/pipe.c
  resources/projects/libraries/qt_utils/core/MainApplication.cpp
  tests/sources/.gitignore
  tests/sources/generate_diff.py
  tests/sources/test_clang_format.py
  tests/sources/test_cppcheck.py
  tests/sources/test_license.py
Labels: enhancement

#544 Handle Thumbnails in Doc Generator
  docs/guide/generate_objects_doc.py
Labels: enhancement

#550 Rotate the Viewpoint around the picked point
  resources/web/wwi/mouse_events.js
Labels: regression

#546 Fix generate diff script
  .travis.yml
  tests/sources/.gitignore
  tests/sources/generate_diff.py
  tests/sources/parent_branch.sh
Labels: enhancement

#553 Fix TexturedBackground description
  projects/objects/backgrounds/protos/TexturedBackground.proto
Labels: invalid

#541 Appveyor Test
  README.md
  appveyor.yml
  projects/vehicles/plugins/robot_windows/automobile_window/OSMImportWidget.hpp
  tests/sources/generate_diff.py
  tests/sources/test_clang_format.py
  tests/sources/test_license.py
Labels: enhancement

#551 Log webots.min.js modifications
  change_logs/ChangeLog.html
Labels: invalid

#528 Reduce gap between Webots rendering and webots.min.js
  resources/web/wwi/Makefile
  resources/web/wwi/shaders/hdr_resolve.js
  resources/web/wwi/texture_loader.js
  resources/web/wwi/x3d.js
  resources/web/wwi/x3d_scene.js
  src/webots/nodes/WbViewpoint.cpp
Labels: enhancement

#556 Fix telemax warnings
  projects/robots/telerob/telemax_pro/controllers/telemax_demo/telemax_demo.c
Labels: bug

#559 Fix Makefile call order
  dependencies/Makefile.mac
  projects/Makefile
  projects/default/Makefile
Labels: bug

#558 Fix openVR includes installation.
  dependencies/Makefile.windows
Labels: bug

#560 Fix make cleanse on Windows
  projects/default/Makefile
Labels: bug

#552 Use Slot gender mechanism for the Tinkerbots
  change_logs/ChangeLog.html
  docs/guide/tinkerbots.md
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsAxle.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsBase.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsBrickAdapter.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCube.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieBoxWithCrossSlots.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieBoxWithRoundSlots.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieFemaleCube.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieMaleCube.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubiePyramid.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieTriangle.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsDistanceSensor.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsFinger.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsGrabber.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsLightSensor.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsMotor.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsPivot.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsTwister.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsWheel.proto
Labels: enhancement

#561 Improve variable name
  projects/robots/telerob/telemax_pro/controllers/telemax_demo/telemax_demo.c
Labels: enhancement

#548 Upgraded to Inno Setup 6, non-admin installation of Webots
  change_logs/ChangeLog.html
  src/install_scripts/bash_profile.windows
  src/install_scripts/inno_setup_installer.sh
  src/packaging/Makefile
  src/packaging/webots_distro.c
Labels: enhancement

#564 Fix Test Suite 'TRAVIS' Dependency
  tests/test_suite.py
Labels: bug

#555 Fix Python3 Libraries
  projects/default/libraries/vehicle/Makefile
  projects/robots/robotis/darwin-op/libraries/Makefile
  projects/robots/robotis/darwin-op/libraries/python/Makefile
  projects/robots/robotis/darwin-op/libraries/python27/.gitignore
  projects/robots/robotis/darwin-op/libraries/python35/.gitignore
  projects/robots/robotis/darwin-op/libraries/python36/.gitignore
  projects/robots/robotis/darwin-op/libraries/python37/.gitignore
  projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/marathon.py
Labels: enhancement

#565 Fix and simplify tinkerbots demo
  projects/robots/kinematics/tinkerbots/controllers/vehicle/vehicle.c
  projects/robots/kinematics/tinkerbots/worlds/tinkerbots_demo.wbt
Labels: regression

#563 Hotfix --minimize starting option on Ubuntu 18.04
  change_logs/ChangeLog.html
  src/webots/gui/WbGuiApplication.cpp
Labels: bug, regression

#573 Fix insertion of USE PROTO into parent PROTO parameter
  change_logs/ChangeLog.html
  src/webots/nodes/utils/WbNodeOperations.cpp
Labels: bug

#578 Update Makefile.windows
  dependencies/Makefile.windows
Labels: bug

#518 Fix animation
  change_logs/ChangeLog.html
  projects/samples/robotbenchmark/inverted_pendulum/worlds/inverted_pendulum.wbt
  resources/web/templates/x3d_playback.html
  resources/web/wwi/animation.js
  resources/web/wwi/pause.png
  resources/web/wwi/play.png
  resources/web/wwi/x3d_scene.js
  src/webots/engine/WbAnimationRecorder.cpp
  src/webots/engine/WbAnimationRecorder.hpp
  src/webots/nodes/WbLight.cpp
  src/webots/vrml/WbVrmlWriter.cpp
Labels: bug, regression

#577 Fix Muscle.color field name in docs
  docs/reference/muscle.md
Labels: enhancement

#575 Fix ffmpeg dependencies
  src/packaging/copy_msys64_files.py
  src/packaging/ffmpeg_dependencies.sh
  src/packaging/files_msys64.txt
Labels: enhancement

#576 Blog page for Webots R2019b
  change_logs/ChangeLog.html
  docs/blog/Webots-2019-b-release.md
  docs/blog/images/assets/asset_1.png
  docs/blog/images/assets/asset_1.thumbnail.png
  docs/blog/images/assets/asset_10.png
  docs/blog/images/assets/asset_10.thumbnail.png
  docs/blog/images/assets/asset_11.png
  docs/blog/images/assets/asset_11.thumbnail.png
  docs/blog/images/assets/asset_12.png
  docs/blog/images/assets/asset_12.thumbnail.png
  docs/blog/images/assets/asset_2.png
  docs/blog/images/assets/asset_3.png
  docs/blog/images/assets/asset_3.thumbnail.png
  docs/blog/images/assets/asset_4.png
  docs/blog/images/assets/asset_4.thumbnail.png
  docs/blog/images/assets/asset_5.png
  docs/blog/images/assets/asset_5.thumbnail.png
  docs/blog/images/assets/asset_6.png
  docs/blog/images/assets/asset_6.thumbnail.png
  docs/blog/images/assets/asset_7.png
  docs/blog/images/assets/asset_7.thumbnail.png
  docs/blog/images/assets/asset_8.png
  docs/blog/images/assets/asset_8.thumbnail.png
  docs/blog/images/assets/asset_9.png
  docs/blog/images/assets/asset_9.thumbnail.png
  docs/blog/images/blender-add-on.gif
  docs/blog/images/camera_post_processing.png
  docs/blog/images/camera_post_processing.thumbnail.jpg
  docs/blog/images/hall.png
  docs/blog/images/hall.thumbnail.jpg
  docs/blog/images/webotsminjs-camera.png
  docs/blog/images/webotsminjs-camera.thumbnail.jpg
  docs/blog/images/webotsminjs-youbot.png
  docs/blog/images/webotsminjs-youbot.thumbnail.jpg
  docs/blog/menu.md
Labels: enhancement

#441 Hinge2Joint Muscle.
  change_logs/ChangeLog.html
  docs/reference/motor.md
  docs/reference/muscle.md
  projects/samples/geometries/controllers/muscle/muscle.c
  projects/samples/geometries/worlds/muscle.wbt
  resources/nodes/Muscle.wrl
  src/webots/nodes/WbHinge2Joint.cpp
  src/webots/nodes/WbHingeJoint.cpp
  src/webots/nodes/WbJoint.hpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbMuscle.cpp
  src/webots/nodes/WbMuscle.hpp
  src/webots/nodes/WbSliderJoint.cpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
Labels: enhancement

#581 maze_runner benchmark: fix appearance of table
  projects/samples/robotbenchmark/maze_runner/worlds/maze_runner.wbt
  projects/samples/robotbenchmark/maze_runner/worlds/textures/table_top.jpg
Labels: regression

#584 Make travis per commit tests on one platform only
  .travis.yml
Labels: enhancement

#579 Recommend realistic light attenuation
  change_logs/ChangeLog.html
  projects/objects/lights/protos/CeilingLight.proto
  projects/objects/lights/protos/FloorLight.proto
  projects/objects/traffic/protos/ControlledStreetLight.proto
  projects/objects/traffic/protos/StreetLight.proto
  projects/robots/a4/portal/protos/Portal.proto
  projects/robots/a4/portal/worlds/portal_pe.wbt
  projects/robots/adept/pioneer3/worlds/pioneer3dx_collision_avoidance.wbt
  projects/robots/adept/pioneer3/worlds/pioneer3dx_with_kinect.wbt
  projects/robots/epfl/lis/worlds/blimp.wbt
  projects/robots/irobot/create/worlds/create.wbt
  projects/robots/saeon/protos/Altino.proto
  projects/robots/softbank/nao/worlds/challenge.wbt
  projects/robots/softbank/nao/worlds/nao_indoors.wbt
  projects/samples/contests/rockin/worlds/home.wbt
  projects/samples/environments/indoor/worlds/apartment.wbt
  projects/samples/environments/indoor/worlds/kitchen.wbt
  projects/samples/howto/controllers/inverted_pendulum/inverted_pendulum.c
  projects/samples/howto/worlds/inverted_pendulum.wbt
  projects/vehicles/protos/bmw/BmwX5.proto
  projects/vehicles/protos/citroen/CitroenCZero.proto
  projects/vehicles/protos/lincoln/LincolnMKZ.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVR.proto
  projects/vehicles/protos/toyota/ToyotaPrius.proto
  projects/vehicles/worlds/village_realistic.wbt
  src/webots/nodes/WbPointLight.cpp
  src/webots/nodes/WbSpotLight.cpp
Labels: enhancement

#585 Improve the wbr_start documentation
  docs/guide/controller-plugin.md
  docs/reference/robot.md
Labels: enhancement

#580 Travis Nightly Builds for Linux
  .travis.yml
  src/packaging/publish_release.py
  src/packaging/set_commit_and_date_in_version.py
  src/packaging/webots_distro.c
  src/webots/core/WbTelemetry.cpp
  src/webots/core/WbVersion.cpp
  src/webots/core/WbVersion.hpp
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbNewVersionDialog.cpp
  src/webots/gui/WbSingleTaskApplication.cpp
  src/webots/gui/WbSplashScreen.cpp
  tests/test_compilation.py
Labels: enhancement

#583 Improve guided tour order
  projects/guided_tour.txt
  projects/robots/telerob/telemax_pro/controllers/telemax_demo/telemax_demo.c
Labels: enhancement

#586 Fix Robotis library "make clean" rule
  projects/robots/robotis/darwin-op/libraries/Makefile
Labels: bug

#587 Remove obsolete file references
  src/packaging/files_core.txt
Labels: invalid

#588 macOS Fix crash on startup
  src/ode/Makefile
Labels: bug

#589 Add moose controller in the Makefile list
  projects/robots/Makefile
Labels: bug

#590 Fix URe wbproj
  projects/robots/universal_robots/worlds/.ure.wbproj
Labels: enhancement

#592 Release officially e-puck_line_demo.c
  projects/robots/gctronic/e-puck/controllers/e-puck_line_demo/e-puck_line_demo.c
  projects/robots/gctronic/e-puck/worlds/.e-puck_line_demo.wbproj
  src/packaging/omit_in_projects.txt
Labels: invalid

#593 Fix warnings about attenuation in led.wbt
  projects/samples/devices/worlds/led.wbt
Labels: invalid

#594 Fix warning about deprecated wallTileSize in camera_auto_focus
  projects/samples/devices/worlds/camera_auto_focus.wbt
Labels: enhancement

#595 Fix various warning and errors in worlds.
  projects/robots/k-team/hemisson/worlds/hemisson.wbt
  projects/robots/k-team/khepera1/worlds/khepera_k213.wbt
  projects/samples/howto/worlds/center_of_mass.wbt
  projects/samples/robotbenchmark/square_path/worlds/square_path.wbt
  projects/samples/tutorials/worlds/obstacles.wbt
Labels: bug

#597 Update all Worlds.
  projects/languages/ros/worlds/catch_the_bird.wbt
  projects/robots/gctronic/e-puck/worlds/e-puck2.wbt
  projects/robots/gctronic/e-puck/worlds/e-puck2_server.wbt
  projects/robots/kinematics/tinkerbots/worlds/tinkerbots_demo.wbt
  projects/robots/telerob/telemax_pro/worlds/telemax.wbt
  projects/samples/devices/worlds/sick.wbt
  projects/samples/devices/worlds/track.wbt
  projects/samples/environments/indoor/worlds/kitchen.wbt
  projects/samples/howto/worlds/spinning_top.wbt
  projects/samples/tutorials/worlds/my_first_simulation.wbt
  projects/vehicles/worlds/CH_Morges.wbt
  projects/vehicles/worlds/city.wbt
  projects/vehicles/worlds/city_night.wbt
  projects/vehicles/worlds/city_traffic.wbt
  projects/vehicles/worlds/sumo_interface_example.wbt
  projects/vehicles/worlds/village_realistic.wbt
Labels: enhancement

#598 Update known bugs page
  docs/guide/known-bugs.md
  docs/guide/linux.md
Labels: enhancement

#599 Merge master to revision
  docs/reference/muscle.md
Labels: invalid

#600 Update ChangeLog.html
  change_logs/ChangeLog.html
Labels: enhancement

#601 Update translation files for the release
  resources/translations/wb_de.ts
  resources/translations/wb_es.ts
  resources/translations/wb_fr.ts
  resources/translations/wb_generic.ts
  resources/translations/wb_it.ts
  resources/translations/wb_ja_JP.ts
  resources/translations/wb_zh_CN.ts
Labels: enhancement

#602 Merge revision to develop
  docs/reference/muscle.md
Labels: invalid

#605 Added missing DLL needed by GCC 9.1.0
  src/packaging/files_msys64.txt
Labels: bug

#603 Fix Travis Tests on Tags
  .travis.yml
Labels: enhancement

#612 Fix Missing Devices in Guided tour
  projects/guided_tour.txt
Labels: bug

#616 Moved appveyor.yml to hidden file
  .appveyor.yml
Labels: enhancement

#615 Fix Travis Java version
  .travis.yml
Labels: bug

#617 Fix Nightly Version in Splash Screen
  src/webots/gui/WbSplashScreen.cpp
Labels: bug

#618 Fix camera_noise_mask to render more easy the red blob detection
  projects/samples/devices/worlds/camera.wbt
  projects/samples/devices/worlds/camera_motion_blur.wbt
  projects/samples/devices/worlds/camera_noise_mask.wbt
Labels: bug

#621 Fix java controller compilation
  resources/Makefile.java.include
Labels: bug

#613 Doc: fix Webots version
  docs/js/showdown-extensions.js
  src/bin/new_version.sh
  src/bin/new_version_file.sh
Labels: invalid

#622 Fix Nightly Release
  src/packaging/publish_release.py
Labels: bug

#624 Fix Sumo Vehicle Height
  projects/default/controllers/sumo_supervisor/SumoSupervisor.py
Labels: bug

#627 Hotfix rounding fields values on WBT write
  src/webots/scene_tree/WbDoubleEditor.cpp
  src/webots/scene_tree/WbVector2Editor.cpp
  src/webots/scene_tree/WbVector3Editor.cpp
Labels: bug

#629 Fix Tutorial Number
  docs/guide/tutorial-8-using-ros.md
Labels: bug

#631 Fix ROS Instructions
  docs/guide/tutorial-8-using-ros.md
Labels: enhancement

#632 Fix ROS Package
  projects/languages/ros/webots_ros/CMakeLists.txt
Labels: bug

#634 Fix Telemax World Description
  projects/robots/telerob/telemax_pro/worlds/telemax.wbt
Labels: bug

#637 Fix typo in Supervisor deprecation warning
  projects/default/protos/Supervisor.proto
Labels: enhancement

#636 Fix HDR environment maps when disconnecting/connecting the streaming viewer
  resources/web/wwi/x3d_scene.js
Labels: bug

#626 Fix robotis op3 overlays
  projects/robots/robotis/darwin-op/worlds/.robotis_op3.wbproj
  projects/robots/robotis/darwin-op/worlds/.visual_tracking.wbproj
  projects/robots/robotis/darwin-op/worlds/robotis_op3.wbt
Labels: enhancement

#639 Update release date
  change_logs/ChangeLog.html
Labels: invalid

#640 Delete more dangerous DLLs from C:\Windows\System32
  src/packaging/webots_distro.c
Labels: bug, enhancement

#641 Fix Highway Overtake Simulation
  projects/vehicles/controllers/highway_overtake/highway_overtake.py
  projects/vehicles/worlds/.highway_overtake.wbproj
Labels: bug

#643 macOS: Fix controller build in case WEBOTS_HOME contains a space
  resources/Makefile.include
Labels: bug

#642 Always use 'play' in cookie storing the animation status
  resources/web/wwi/animation.js
Labels: bug

#644 Improved Nightly Build Description
  src/packaging/publish_release.py
Labels: enhancement

#645 Add ROSin Acknowledgement
  docs/guide/ure.md
Labels: enhancement

#596 Enable MacOS Nightly Builds
  .travis.yml
  src/packaging/webots_distro.c
Labels: enhancement

#648 Delete Old Nightly Builds
  src/packaging/publish_release.py
Labels: enhancement

#633 Fix test suite on Windows
  .appveyor.yml
  .travis.yml
  src/install_scripts/msys64_installer.sh
  tests/api/controllers/pen_box/pen_box.c
  tests/api/worlds/pen_box.wbt
  tests/sources/__init__.py
  tests/sources/generate_diff.py
  tests/test_suite.py
Labels: bug

#654 Fix default blog page
  docs/doc.php
  src/bin/new_version.sh
  src/bin/new_version_file.sh
Labels: enhancement

#655 Update README.md
  README.md
Labels: enhancement

#659 Add Url to ros package.
  projects/languages/ros/webots_ros/package.xml
Labels: enhancement

#651 Bloom in webots.min.js
  change_logs/ChangeLog.html
  resources/web/wwi/Makefile
  resources/web/wwi/passes/bloom.js
  resources/web/wwi/shaders/blend_bloom.js
  resources/web/wwi/shaders/bright_pass.js
  resources/web/wwi/shaders/gaussian_blur_13_tap.js
  resources/web/wwi/x3d.js
  resources/web/wwi/x3d_scene.js
  src/webots/nodes/WbViewpoint.cpp
Labels: enhancement

#664 webots.min.js: Support texture anistropy
  change_logs/ChangeLog.html
  resources/web/wwi/x3d.js
Labels: enhancement

#667 Feature Several Branches in Nightly Builds
  src/packaging/publish_release.py
Labels: enhancement

#672 Fix Connector Behavior in ROS Controller
  change_logs/ChangeLog.html
  projects/default/controllers/ros/Ros.cpp
Labels: bug

#670 Fix generate diff bug
  tests/sources/generate_diff.py
Labels: bug

#675 Fix travis Python 2.7 and mac
  .travis.yml
Labels: bug

#676 Fix Changelog
  change_logs/ChangeLog.html
Labels: bug

#677 Convert Changelog to MD
  change_logs/ChangeLog.html
  change_logs/ChangeLog4.html
  change_logs/ChangeLog5.html
  change_logs/ChangeLog6.html
  change_logs/ChangeLog7.html
  change_logs/ChangeLog8.html
  change_logs/ChangeLogR2018.html
  docs/README.md
  docs/blog/Webots-2018-b-release.md
  docs/blog/Webots-2019-a-release.md
  docs/reference/change-log-4.md
  docs/reference/change-log-5.md
  docs/reference/change-log-6.md
  docs/reference/change-log-7.md
  docs/reference/change-log-8.md
  docs/reference/change-log-r2018.md
  docs/reference/change-log-r2019.md
  docs/reference/change-log.md
  docs/reference/menu.md
  docs/tests/test_titles.py
  src/packaging/files_core.txt
  src/packaging/webots_distro.c
  src/webots/gui/WbAboutBox.cpp
  src/webots/gui/WbWebotsUpdateDialog.cpp
Labels: enhancement

#679 Restore Changelogs Release Date.
  docs/reference/change-log-4.md
  docs/reference/change-log-5.md
  docs/reference/change-log-6.md
  docs/reference/change-log-7.md
  docs/reference/change-log-8.md
  docs/reference/change-log-r2018.md
  docs/reference/change-log-r2019.md
Labels: bug
