Repository cyberbotics/webots, pull requests merged in 2019-08, with the labels that each got.

#773 Grass PROTO
  projects/appearances/protos/Grass.proto
  projects/appearances/protos/icons/Grass.png
  projects/appearances/protos/textures/grass/grass_artificial_base_color.jpg
  projects/appearances/protos/textures/grass/grass_artificial_normal.jpg
  projects/appearances/protos/textures/grass/grass_artificial_occlusion.jpg
  projects/appearances/protos/textures/grass/grass_maintained_base_color.jpg
  projects/appearances/protos/textures/grass/grass_maintained_normal.jpg
  projects/appearances/protos/textures/grass/grass_maintained_occlusion.jpg
  projects/appearances/protos/textures/grass/grass_mossy_base_color.jpg
  projects/appearances/protos/textures/grass/grass_mossy_normal.jpg
  projects/appearances/protos/textures/grass/grass_mossy_occlusion.jpg
  projects/appearances/protos/textures/grass/grass_prickly_base_color.jpg
  projects/appearances/protos/textures/grass/grass_prickly_normal.jpg
  projects/appearances/protos/textures/grass/grass_prickly_occlusion.jpg
  projects/appearances/protos/textures/grass/grass_prickly_roughness.jpg
  scripts/icon_studio/controllers/icon_creator/appearances.json
Labels: enhancement

#777 Add ROSin Acknowledgement
  docs/guide/ure.md
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/CMakeLists.txt
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/README.md
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/launch/ur10e.launch
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/launch/ur10e_joint_limited.launch
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/launch/ur3e.launch
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/launch/ur3e_joint_limited.launch
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/launch/ur5e.launch
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/launch/ur5e_joint_limited.launch
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/package.xml
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/tests/roslaunch_test.xml
Labels: enhancement

#778 Fix appveyor on master
  .appveyor.yml
  docs/guide/generate_objects_doc.py
  tests/sources/test_pep8.py
Labels: bug

#761 Port RTI World to Webots
  docs/automobile/images/village_center.png
  docs/automobile/images/village_center.thumbnail.jpg
  docs/automobile/menu.md
  docs/automobile/village-center.md
  docs/automobile/worlds.md
  docs/reference/changelog-r2019.md
  projects/appearances/protos/Sand.proto
  projects/appearances/protos/Soil.proto
  projects/appearances/protos/StonePavement.proto
  projects/appearances/protos/icons/Sand.png
  projects/appearances/protos/icons/Soil.png
  projects/appearances/protos/textures/sand/sand_base_color.jpg
  projects/appearances/protos/textures/sand/sand_normal.jpg
  projects/appearances/protos/textures/sand/sand_occlusion.jpg
  projects/appearances/protos/textures/sand/sand_roughness.jpg
  projects/appearances/protos/textures/soil/braun_soil_base_color.jpg
  projects/appearances/protos/textures/soil/braun_soil_normal.jpg
  projects/appearances/protos/textures/soil/braun_soil_occlusion.jpg
  projects/appearances/protos/textures/soil/braun_soil_roughness.jpg
  projects/appearances/protos/textures/soil/grey_soil_base_color.jpg
  projects/appearances/protos/textures/soil/grey_soil_normal.jpg
  projects/appearances/protos/textures/soil/grey_soil_occlusion.jpg
  projects/appearances/protos/textures/soil/grey_soil_roughness.jpg
  projects/appearances/protos/textures/stone_pavement/old_square_stone_pavement_base_color.jpg
  projects/appearances/protos/textures/stone_pavement/old_square_stone_pavement_normal.jpg
  projects/appearances/protos/textures/stone_pavement/old_square_stone_pavement_occlusion.jpg
  projects/appearances/protos/textures/stone_pavement/old_square_stone_pavement_roughness.jpg
  projects/appearances/protos/textures/stone_pavement/recent_stone_pavement_base_color.jpg
  projects/appearances/protos/textures/stone_pavement/recent_stone_pavement_normal.jpg
  projects/appearances/protos/textures/stone_pavement/recent_stone_pavement_occlusion.jpg
  projects/appearances/protos/textures/stone_pavement/recent_stone_pavement_roughness.jpg
  projects/objects/traffic/protos/textures/signs/eu/end_limit_50.png
  projects/vehicles/worlds/.village_center.wbproj
  projects/vehicles/worlds/textures/hedges.png
  projects/vehicles/worlds/textures/road_line_triangle.png
  projects/vehicles/worlds/village_center.wbt
  projects/vehicles/worlds/village_center_net/sumo.edg.xml
  projects/vehicles/worlds/village_center_net/sumo.net.xml
  projects/vehicles/worlds/village_center_net/sumo.nod.xml
  projects/vehicles/worlds/village_center_net/sumo.rou.alt.xml
  projects/vehicles/worlds/village_center_net/sumo.rou.xml
  projects/vehicles/worlds/village_center_net/sumo.sumocfg
  projects/vehicles/worlds/village_center_net/sumo.trip.xml
  scripts/icon_studio/controllers/icon_creator/appearances.json
Labels: enhancement

#714 Update ROS Instructions
  docs/guide/tutorial-8-using-ros.md
  docs/guide/using-ros.md
Labels: enhancement

#782 Fix Header Version
  projects/appearances/protos/Sand.proto
  projects/appearances/protos/Soil.proto
  projects/vehicles/worlds/.village_center.wbproj
  projects/vehicles/worlds/village_center.wbt
Labels: enhancement

#751 Enhancement webots js textures
  resources/web/wwi/animation.js
  resources/web/wwi/texture_loader.js
  resources/web/wwi/x3d.js
  resources/web/wwi/x3d_scene.js
  src/webots/gui/WbGuiApplication.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbImageTexture.hpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/nodes/utils/WbWorld.hpp
Labels: bug, enhancement

#786 Fix ROS Doc
  docs/guide/using-ros.md
Labels: enhancement

#788 Fix typo in webots.min.js:TextureLoader
  resources/web/wwi/texture_loader.js
Labels: enhancement

#787 Modal images dimension
  docs/css/webots-doc.css
Labels: enhancement

#789 Fix Various Code Issues
  docs/tests/test_lists.py
  docs/tests/test_paragraphs.py
  docs/tests/test_titles.py
  projects/default/controllers/ros/headersGenerator.py
  projects/default/controllers/sumo_supervisor/SumoSupervisor.py
  projects/default/controllers/sumo_supervisor/WebotsVehicle.py
  projects/default/controllers/sumo_supervisor/sumo_supervisor.py
  projects/languages/python/controllers/driver/driver.py
  projects/robots/gctronic/e-puck/transfer/populate_xc16_directory.py
  projects/robots/softbank/nao/controllers/nao_demo_python/nao_demo_python.py
  projects/samples/robotbenchmark/highway_driving/controllers/highway_driving_benchmark/highway_driving_benchmark.py
  projects/samples/robotbenchmark/square_path/controllers/square_path_advanced/square_path_advanced.py
  projects/samples/robotbenchmark/square_path/controllers/square_path_supervisor/path_segment.py
  projects/samples/robotbenchmark/square_path/controllers/square_path_supervisor/real_robot_performance.py
  projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking/visual_tracking.py
  projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking_benchmark/visual_tracking_benchmark.py
  projects/samples/robotbenchmark/wall_following/controllers/wall_following_advanced/wall_following_advanced.py
  projects/vehicles/controllers/enable_all_lidars/enable_all_lidars.py
  projects/vehicles/worlds/highway_overtake_net/generate_route.py
  resources/osm_importer/elevation.py
  resources/osm_importer/importer.py
  resources/osm_importer/osm_objects.py
  resources/osm_importer/utils/misc_utils.py
  resources/osm_importer/webots_objects/area.py
  resources/osm_importer/webots_objects/barrier.py
  resources/osm_importer/webots_objects/building.py
  resources/osm_importer/webots_objects/river.py
  resources/osm_importer/webots_objects/road.py
  resources/sumo_exporter/crossroad.py
  resources/web/server/simulation_server.py
  scripts/web_component_studio/controllers/web_component_studio_supervisor/web_component_studio_supervisor.py
  scripts/web_component_studio/web_component_studio.py
  src/packaging/check_rpath.py
  tests/command.py
  tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py
  tests/sources/test_cppcheck.py
  tests/test_suite.py
Labels: enhancement

#656 Complete Appartment Simulation
  docs/guide/images/samples/complete_apartment_a.png
  docs/guide/images/samples/complete_apartment_a.thumbnail.jpg
  docs/guide/images/samples/complete_apartment_b.png
  docs/guide/images/samples/complete_apartment_b.thumbnail.jpg
  docs/guide/images/samples/complete_apartment_c.png
  docs/guide/images/samples/complete_apartment_c.thumbnail.jpg
  docs/guide/images/samples/complete_apartment_d.png
  docs/guide/images/samples/complete_apartment_d.thumbnail.jpg
  docs/guide/samples-environments.md
  docs/reference/changelog-r2020.md
  projects/samples/environments/indoor/worlds/.complete_apartment.wbproj
  projects/samples/environments/indoor/worlds/complete_apartment.wbt
Labels: enhancement

#790 fix-appartment-note
  docs/guide/samples-environments.md
Labels: enhancement

#792 Fixed Installation instructions
  docs/guide/installation-procedure.md
Labels: enhancement

#795 webots.min.js: fix authenticated user check
  resources/web/wwi/editor.js
  resources/web/wwi/toolbar.js
  resources/web/wwi/webots.js
Labels: bug

#799 visual_tracking benchmark: fix URI of camera/display images
  projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking/visual_tracking.py
Labels: bug

#800 Fix read controller python shebang
  docs/guide/using-python.md
  docs/reference/changelog-r2019.md
  src/webots/control/WbController.cpp
Labels: bug

#801 webots.min.js: fix toolbar run button status and context menu
  resources/web/wwi/toolbar.js
  resources/web/wwi/webots.js
  src/webots/gui/WbStreamingServer.cpp
  src/webots/gui/WbStreamingServer.hpp
Labels: bug

#802 Fixed gitignore files for robotis python libraries
  projects/robots/robotis/darwin-op/libraries/python27/.gitignore
  projects/robots/robotis/darwin-op/libraries/python35/.gitignore
  projects/robots/robotis/darwin-op/libraries/python36/.gitignore
  projects/robots/robotis/darwin-op/libraries/python37/.gitignore
Labels: enhancement

#804 Improve Python Sample Controllers
  projects/languages/python/controllers/driver/driver.py
  projects/languages/python/controllers/slave/slave.py
Labels: enhancement

#807 Document PyCharm with Webots
  docs/guide/development-environments.md
  docs/guide/images/pycharm_add_lib.png
  docs/guide/images/pycharm_add_lib.thumbnail.jpg
  docs/guide/images/pycharm_open.png
  docs/guide/images/pycharm_open.thumbnail.jpg
  docs/guide/images/pycharm_path.png
  docs/guide/images/pycharm_path.thumbnail.jpg
  docs/guide/images/pycharm_run.png
  docs/guide/images/pycharm_run.thumbnail.jpg
  docs/guide/images/pycharm_webots.png
  docs/guide/images/pycharm_webots.thumbnail.jpg
  docs/guide/menu.md
  docs/guide/using-pycharm-with-webots.md
Labels: enhancement

#793 Improve External Controller to Wait for Webots.
  docs/reference/changelog-r2019.md
  src/lib/Controller/api/robot.c
  src/lib/Controller/api/system.c
Labels: enhancement

#809 Add a Link to PyCharm Page
  docs/guide/using-python.md
Labels: enhancement

#811 Fix Python37 not released on Linux
  docs/reference/changelog-r2019.md
  src/packaging/files_core.txt
Labels: bug

#812 Improve Vehicle Light Intensity
  docs/reference/changelog-r2019.md
  projects/vehicles/protos/abstract/VehicleLights.proto
  projects/vehicles/protos/bmw/BmwX5BackwardsLight.proto
  projects/vehicles/protos/bmw/BmwX5BrakingLight.proto
  projects/vehicles/protos/bmw/BmwX5FrontLight.proto
  projects/vehicles/protos/bmw/BmwX5LeftIndicator.proto
  projects/vehicles/protos/bmw/BmwX5RearLight.proto
  projects/vehicles/protos/bmw/BmwX5RightIndicator.proto
  projects/vehicles/protos/citroen/CitroenCZeroBrakeLight.proto
  projects/vehicles/protos/citroen/CitroenCZeroHeadLight.proto
  projects/vehicles/protos/citroen/CitroenCZeroLeftIndicator.proto
  projects/vehicles/protos/citroen/CitroenCZeroRightIndicator.proto
  projects/vehicles/protos/generic/Bus.proto
  projects/vehicles/protos/generic/TruckFrontLight.proto
  projects/vehicles/protos/generic/TruckRearLight.proto
  projects/vehicles/protos/lincoln/LincolnMKZ.proto
  projects/vehicles/protos/lincoln/LincolnMKZCoachworkMesh.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVR.proto
  projects/vehicles/protos/tesla/TeslaModel3FrontLights.proto
  projects/vehicles/protos/toyota/ToyotaPriusFrontLight.proto
  projects/vehicles/protos/toyota/ToyotaPriusLeftIndicator.proto
  projects/vehicles/protos/toyota/ToyotaPriusRearLight.proto
  projects/vehicles/protos/toyota/ToyotaPriusRightIndicator.proto
Labels: enhancement

#813 Fix possible dll conflict on windows
  docs/reference/changelog-r2019.md
  src/packaging/files_msys64.txt
Labels: bug

#814 Add Discord to README.md
  README.md
Labels: enhancement

#815 webots.min.js: fix 'this' object in static methods
  docs/reference/changelog-r2019.md
  resources/web/wwi/console.js
  resources/web/wwi/dialog_window.js
  resources/web/wwi/editor.js
  resources/web/wwi/help_window.js
  resources/web/wwi/robot_window.js
  resources/web/wwi/toolbar.js
Labels: bug

#822 webots.min.js: Fix context menu on Firefox/Windows 10
  docs/reference/changelog-r2019.md
  resources/web/wwi/mouse_events.js
Labels: bug, regression

#823 webots.min.js/macOS: Fix `Ctrl + left click`
  docs/reference/changelog-r2019.md
  resources/web/wwi/Makefile
  resources/web/wwi/editor.js
  resources/web/wwi/mouse_events.js
  resources/web/wwi/system_info.js
  resources/web/wwi/webots.js
Labels: regression

#817 webots.min.js: Improve history management of the console
  docs/reference/changelog-r2020.md
  resources/web/wwi/console.js
  resources/web/wwi/images/trash.png
  resources/web/wwi/wwi.css
Labels: enhancement

#826 Update naoqisim repo path
  docs/guide/nao.md
Labels: enhancement

#830 Fixed the installation of npm on Linux
  .travis.yml
Labels: enhancement

#838 Feature C3D
  docs/reference/changelog-r2019.md
  projects/humans/c3d/controllers/c3d_viewer/EB015PI.c3d
  projects/humans/c3d/controllers/c3d_viewer/README.md
  projects/humans/c3d/controllers/c3d_viewer/TESTAPI.c3d
  projects/humans/c3d/controllers/c3d_viewer/TESTBPI.c3d
  projects/humans/c3d/controllers/c3d_viewer/TESTCPI.c3d
  projects/humans/c3d/controllers/c3d_viewer/TESTDPI.c3d
  projects/humans/c3d/controllers/c3d_viewer/c3d.py
  projects/humans/c3d/controllers/c3d_viewer/c3d_viewer.py
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.css
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.html
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.js
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/plot_widget.js
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/timeplot_widget.js
  projects/humans/c3d/protos/C3dBodyRepresentation.proto
  projects/humans/c3d/protos/C3dGroundReactionForce.proto
  projects/humans/c3d/protos/C3dMarker.proto
  projects/humans/c3d/protos/C3dViewer.proto
  projects/humans/c3d/protos/icons/C3dViewer.png
  projects/humans/c3d/worlds/.c3d_viewer.wbproj
  projects/humans/c3d/worlds/c3d_viewer.wbt
  tests/sources/test_license.py
Labels: enhancement

#843 Add missing setMode function to doc
  docs/reference/robot.md
Labels: bug
