Repository cyberbotics/webots, pull requests merged in 2019-02, with the labels that each got.

#151 Update webots version
  Contents/Info.plist
  docs/dependencies.txt
  resources/version.txt
  src/bin/new_version.sh
  src/bin/new_version_file.sh
  src/bin/new_version_file_headers.sh
  src/packaging/webots_version.txt
  src/webots/core/WbApplicationInfo.cpp
Labels: enhancement

#155 Fix macOS build
  src/webots/core/WbSysInfo.cpp
Labels: bug

#153 Fix Travis License Test
  .travis.yml
  README.md
  projects/samples/curriculum/controllers/intermediate_behavior_based/intermediate_behavior_based.c
  projects/samples/curriculum/controllers/intermediate_behavior_based/intermediate_behavior_based_corr.c
  src/webots/gui/WbRenderingDeviceWindow.cpp
  src/webots/gui/WbWrenWindow.cpp
  src/webots/maths/WbMathsUtilities.cpp
  src/webots/nodes/utils/WbTriangleMeshCache.cpp
  tests/sources/test_clang_format.py
  tests/sources/test_license.py
Labels: bug

#154 Fixed gcc7/cygwin flush of stdout/stderr
  change_logs/ChangeLog.html
  include/controller/c/webots/robot.h
Labels: bug

#161 Fix TextureTransform Updates
  change_logs/ChangeLog.html
  src/webots/nodes/WbPbrAppearance.cpp
Labels: bug

#163 Fix display.wbt sample
  projects/samples/devices/controllers/display/display.c
  projects/samples/devices/worlds/.display.wbproj
  projects/samples/devices/worlds/display.wbt
  src/webots/wren/WbWrenTextureOverlay.cpp
Labels: enhancement

#164 Make water in animated_skin example more bluish
  projects/samples/rendering/worlds/animated_skin.wbt
Labels: enhancement

#156 Telemetry option in new version dialog and preferences
  docs/guide/installing-webots.md
  docs/guide/menu.md
  docs/guide/preferences.md
  docs/guide/telemetry.md
  docs/guide/webots-license-agreement.md
  src/webots/Makefile
  src/webots/app/WbApplication.cpp
  src/webots/core/WbStandardPaths.cpp
  src/webots/core/WbTelemetry.cpp
  src/webots/core/WbTelemetry.hpp
  src/webots/core/WbWebotsUpdateManager.cpp
  src/webots/gui/WbAboutBox.cpp
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbNewVersionDialog.cpp
  src/webots/gui/WbNewVersionDialog.hpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbPreferencesDialog.hpp
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbWebotsUpdateDialog.cpp
  src/webots/nodes/WbCubemap.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbPbrAppearance.cpp
  src/webots/vrml/WbProtoModel.cpp
Labels: enhancement

#166 Update files for the release
  change_logs/ChangeLog.html
  resources/translations/wb_de.ts
  resources/translations/wb_es.ts
  resources/translations/wb_fr.ts
  resources/translations/wb_generic.ts
  resources/translations/wb_it.ts
  resources/translations/wb_ja_JP.ts
  resources/translations/wb_zh_CN.ts
Labels: invalid

#168 Add missing wbproj file
  projects/robots/gctronic/e-puck/worlds/.e-puck2_server.wbproj
Labels: invalid

#170 Fixed reference to a msys2 library
  src/packaging/files_msys64.txt
Labels: bug

#167 Fix Tests Makefile.
  tests/Makefile
Labels: bug

#181 Removed useless Transform and Group
  projects/samples/devices/worlds/linear_motor.wbt
Labels: enhancement

#184 Upgraded to Qt 5.12.1 on Windows
  change_logs/ChangeLog.html
  src/install_scripts/qt_windows_installer.sh
Labels: enhancement

#183 Fixed path to Qt plugins for controllers on Windows
  src/webots/control/WbController.cpp
Labels: bug

#180 Fixed recompilation of controller with gcc7
  include/controller/c/webots/robot.h
  projects/robots/robotis/darwin-op/libraries/robotis-op2/robotis/Framework/src/minIni/minIni.c
Labels: bug

#178 Fix e puck2 wifi remote control
  change_logs/ChangeLog.html
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/Communication.cpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/Wrapper.cpp
Labels: bug

#189 Fix Braitenberg Controller
  projects/default/controllers/braitenberg/braitenberg.c
Labels: bug

#188 Safe mode
  change_logs/ChangeLog.html
  docs/guide/starting-webots.md
  src/webots/core/WbPreferences.cpp
  src/webots/gui/WbGuiApplication.cpp
Labels: enhancement

#191 Fix compilation of WbTelemetry.cpp on Windows
  src/webots/core/WbTelemetry.cpp
Labels: bug

#192 Fix OpenGL Telemetry
  src/webots/core/WbSysInfo.cpp
  src/webots/core/WbSysInfo.hpp
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbWrenWindow.cpp
Labels: bug, enhancement

#177 Fix Video Recoding
  change_logs/ChangeLog.html
  src/webots/gui/WbVideoRecorder.cpp
  src/webots/gui/WbVideoRecorder.hpp
  src/webots/gui/WbWrenWindow.cpp
  src/webots/gui/WbWrenWindow.hpp
Labels: bug

#187 Enhancement distributed worlds
  projects/robots/k-team/khepera1/worlds/.khepera.wbproj
  projects/robots/mobsya/thymio/protos/Thymio2Ball.proto
  projects/robots/neuronics/ipr/protos/IprHd6ms90.proto
  projects/robots/softbank/nao/controllers/Makefile
  projects/samples/contests/ratslife/worlds/.ratslife.wbproj
  projects/samples/contests/ratslife/worlds/.ratslife_round.wbproj
  projects/samples/curriculum/worlds/.advanced_genetic_algorithm.wbproj
  projects/samples/devices/worlds/.display.wbproj
  projects/samples/geometries/worlds/.floating_geometries.wbproj
  projects/samples/howto/worlds/.sick_terrain_scanning.wbproj
  projects/samples/howto/worlds/sick_terrain_scanning.wbt
Labels: bug

#193 Fixed design problem in telemetry networking
  src/webots/app/WbApplication.cpp
  src/webots/core/WbTelemetry.cpp
  src/webots/core/WbTelemetry.hpp
Labels: bug

#195 Deny Transform to Differentialwheels
  src/webots/nodes/utils/WbNodeUtilities.cpp
Labels: enhancement

#182 Fix wrong include and shared libray paths
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/Makefile
  projects/samples/howto/controllers/vision/Makefile
  projects/samples/howto/controllers/vision/vision.cpp
Labels: enhancement

#197 Fix texture downscaling (alternative 2)
  src/webots/Makefile
  src/webots/maths/WbImage.cpp
  src/webots/maths/WbImage.hpp
  src/webots/nodes/WbImageTexture.cpp
Labels: bug

#199 Fixed memory leak
  src/webots/maths/WbImage.cpp
  src/webots/maths/WbImage.hpp
  src/webots/nodes/WbImageTexture.cpp
Labels: bug

#203 Optimized image scale down performance
  src/webots/maths/WbImage.cpp
Labels: enhancement

#202 Fix crash on NVIDIA 2Gb GPU.
  src/webots/gui/WbView3D.cpp
  src/webots/nodes/WbCubemap.cpp
Labels: bug

#204 Fixed wrong msys2 library version (Windows)
  src/packaging/files_msys64.txt
Labels: bug

#208 Improve Telemetry Doc.
  docs/guide/telemetry.md
Labels: enhancement

#210 Improve Robotis-OP3 WBPROJ file.
  projects/robots/robotis/darwin-op/worlds/.robotis_op3_motion_player.wbproj
Labels: enhancement

#209 Fixed FFMPEG missing dependencies
  src/packaging/files_msys64.txt
Labels: bug

#213 Fixed typo in path
  src/packaging/files_msys64.txt
Labels: bug

#221 Added a warning if Webots is launched with the --stream and not the --batch option
  src/webots/gui/WbGuiApplication.cpp
Labels: enhancement

#222 Added instructions to launch Webots from a DOS console
  docs/guide/starting-webots.md
Labels: bug

#225 Cleanup-up anti-aliasing preferences
  docs/guide/preferences.md
  docs/guide/telemetry.md
  src/webots/core/WbPreferences.cpp
  src/webots/core/WbTelemetry.cpp
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbPreferencesDialog.hpp
  src/webots/gui/WbView3D.cpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/util/WbPerformanceLog.cpp
Labels: enhancement

#223 Enhancement Tinkerbots parts slots
  projects/robots/tinkerbots/protos/TinkerbotsCube.proto
  projects/robots/tinkerbots/protos/TinkerbotsCubieBoxWithRoundSlots.proto
Labels: enhancement

#228 Remove Duplicated Textures
  projects/appearances/protos/CarLeather.proto
  projects/appearances/protos/SquarePavement.proto
  projects/appearances/protos/icons/CarLeather.png
  projects/appearances/protos/icons/SquarePavement.png
  projects/appearances/protos/textures/car_leather/car_dark_leather_base_color.jpg
  projects/appearances/protos/textures/car_leather/car_leather_normal.jpg
  projects/appearances/protos/textures/car_leather/car_leather_occlusion.jpg
  projects/appearances/protos/textures/car_leather/car_leather_roughness.jpg
  projects/appearances/protos/textures/car_leather/car_light_leather_base_color.jpg
  projects/appearances/protos/textures/square_pavement/square_pavement_base_color.jpg
  projects/appearances/protos/textures/square_pavement/square_pavement_normal.jpg
  projects/appearances/protos/textures/square_pavement/square_pavement_occlusion.jpg
  projects/appearances/protos/textures/square_pavement/square_pavement_roughness.jpg
  projects/objects/road/protos/textures/pavement.jpg
  projects/vehicles/protos/abstract/CarSteeringWheel.proto
  projects/vehicles/protos/bmw/BmwX5Interior.proto
  projects/vehicles/protos/bmw/BmwX5RearInterior.proto
  projects/vehicles/protos/bmw/textures/bmw_dark_leather_base_color.jpg
  projects/vehicles/protos/bmw/textures/bmw_leather_normal.jpg
  projects/vehicles/protos/bmw/textures/bmw_leather_occlusion.jpg
  projects/vehicles/protos/bmw/textures/bmw_leather_roughness.jpg
  projects/vehicles/protos/bmw/textures/bmw_light_leather_base_color.jpg
  projects/vehicles/worlds/textures/pavement.jpg
  projects/vehicles/worlds/village_realistic.wbt
  tests/sources/test_textures.py
Labels: enhancement

#229 Add execution flags for some scripts
  resources/web/server/server.sh
  resources/web/server/session_server.py
  resources/web/server/simulation_server.py
  tests/ros_test_suite.py
  tests/test.sh
  tests/test_sources.py
  tests/test_suite.py
Labels: enhancement

#237 Fix code duplication in WbSolidReference.cpp.
  src/webots/nodes/WbSolidReference.cpp
Labels: enhancement

#241 Fix default quit button on webots.js
  resources/web/wwi/webots.js
Labels: bug

#239 Improve Connector Doc
  docs/reference/connector.md
Labels: enhancement

#244 Remove transparent 1px border
  resources/web/wwi/images/fast.png
Labels: bug

#233 Add an Environmental Variable to Define Resources Path.
  docs/guide/preferences.md
  src/webots/control/WbController.cpp
  src/webots/core/WbControllerPlugin.cpp
  src/webots/core/WbProject.cpp
  src/webots/core/WbProject.hpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbPreferencesDialog.hpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbAddNodeDialog.hpp
  src/webots/scene_tree/WbExtendedStringEditor.cpp
  src/webots/vrml/WbProtoList.cpp
  src/webots/vrml/WbProtoList.hpp
Labels: enhancement

#247 Hotfix cleanup Nao
  projects/robots/softbank/nao/controllers/nao_demo_python/nao_demo_python.py
  projects/robots/softbank/nao/protos/Nao.proto
Labels: enhancement

#246 Clearpath moose
  change_logs/ChangeLog.html
  docs/guide/images/robots/moose/icon.png
  docs/guide/images/robots/moose/model.png
  docs/guide/images/robots/moose/moose_demo.wbt.png
  docs/guide/menu.md
  docs/guide/moose.md
  docs/guide/robots.md
  docs/guide/scenes/moose/moose.meta.json
  docs/guide/scenes/moose/moose.x3d
  docs/guide/scenes/moose/textures/tire_texture_base_color.jpg
  projects/robots/clearpath/moose/controllers/Makefile
  projects/robots/clearpath/moose/controllers/moose_path_following/.gitignore
  projects/robots/clearpath/moose/controllers/moose_path_following/Makefile
  projects/robots/clearpath/moose/controllers/moose_path_following/moose_path_following.c
  projects/robots/clearpath/moose/protos/Moose.proto
  projects/robots/clearpath/moose/protos/MooseWheel.proto
  projects/robots/clearpath/moose/protos/icons/Moose.png
  projects/robots/clearpath/moose/worlds/.moose_demo.wbproj
  projects/robots/clearpath/moose/worlds/moose_demo.wbt
  projects/samples/demos/controllers/uneven_terrain/.gitignore
  projects/samples/demos/worlds/uneven_terrain/sand.jpg
  resources/images/splash_images/moose.png
  scripts/icon_studio/controllers/icon_creator/objects.json
Labels: enhancement

#250 Restore the web component studio
  scripts/icon_studio/controllers/icon_creator/icon_creator.py
  scripts/icon_studio/controllers/leds/leds.py
  scripts/web_component_studio/README.md
  scripts/web_component_studio/components.json
  scripts/web_component_studio/controllers/web_component_studio_supervisor/web_component_studio_supervisor.py
  scripts/web_component_studio/web_component_studio.py
  scripts/web_component_studio/worlds/.gitignore
  scripts/web_component_studio/worlds/.web_component_studio.wbproj
  scripts/web_component_studio/worlds/web_component_studio_template.wbt
  tests/sources/test_license.py
Labels: enhancement

#251 Hotfix moose
  docs/guide/images/samples/uneven_terrain.png
  docs/guide/samples-demos.md
  projects/guided_tour.txt
Labels: invalid

#249 Fixed anti-aliasing preference inverted
  src/webots/nodes/WbAbstractCamera.cpp
  src/webots/nodes/WbViewpoint.cpp
Labels: bug

#243 Improve Connectors
  change_logs/ChangeLog.html
  docs/reference/connector.md
  src/webots/nodes/WbConnector.cpp
  src/webots/nodes/WbConnector.hpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  tests/physics/controllers/connector_static_autolock/.gitignore
  tests/physics/controllers/connector_static_autolock/Makefile
  tests/physics/controllers/connector_static_autolock/connector_static_autolock.c
  tests/physics/worlds/connector_detach.wbt
  tests/physics/worlds/connector_static_autolock.wbt
Labels: enhancement

#252 Add '*.wproj' Test
  tests/sources/test_clang_format.py
  tests/sources/test_cppcheck.py
  tests/sources/test_icons.py
  tests/sources/test_license.py
  tests/sources/test_matlab_functions.py
  tests/sources/test_project_structure.py
  tests/sources/test_proto_names.py
  tests/sources/test_textures.py
Labels: enhancement

#260 Fix tire creaseAngle
  projects/vehicles/protos/abstract/VehicleWheel.proto
Labels: enhancement

#257 Fix Connectors with SolidMergers
  src/webots/nodes/WbConnector.cpp
  tests/physics/controllers/connector_static_autolock/connector_static_autolock.c
  tests/physics/worlds/connector_static_autolock.wbt
Labels: bug

#261 webots.js: remove initialization of showRevert and showQuit in wrong method
  resources/web/wwi/webots.js
Labels: enhancement
