Repository cyberbotics/webots, pull requests merged in 2019-03, with the labels that each got.

#263 Change Appearances Licenses to Apache 2.0
  docs/guide/appearances.md
  projects/appearances/protos/Asphalt.proto
  projects/appearances/protos/BrushedAluminium.proto
  projects/appearances/protos/CarpetFibers.proto
  projects/appearances/protos/ChequeredParquetry.proto
  projects/appearances/protos/GlossyCarPaint.proto
  projects/appearances/protos/MatteCarPaint.proto
  projects/appearances/protos/MetalPipePaint.proto
  projects/appearances/protos/OldSteel.proto
  projects/appearances/protos/PaintedWood.proto
  projects/appearances/protos/Parquetry.proto
  projects/appearances/protos/RedBricks.proto
  projects/appearances/protos/RoughConcrete.proto
  projects/appearances/protos/RoughOak.proto
  projects/appearances/protos/RoughPine.proto
  projects/appearances/protos/Roughcast.proto
  projects/appearances/protos/SandyGround.proto
  projects/appearances/protos/ShinyLeather.proto
  projects/appearances/protos/StonePavement.proto
  projects/appearances/protos/ThreadMetalPlate.proto
  projects/appearances/protos/VarnishedPine.proto
Labels: enhancement

#265 Fix Ros-Automobile Compilation on Windows
  projects/vehicles/controllers/Makefile
Labels: bug

#266 Fix Translation/Rotation Rounding with Handles
  src/webots/gui/WbDragScaleEvent.cpp
  src/webots/gui/WbDragTransformEvent.cpp
  src/webots/maths/WbPrecision.cpp
  src/webots/maths/WbPrecision.hpp
  src/webots/maths/WbRotation.hpp
  src/webots/maths/WbVector3.hpp
  src/webots/scene_tree/WbColorEditor.cpp
  src/webots/scene_tree/WbDoubleEditor.cpp
  src/webots/scene_tree/WbVector2Editor.cpp
  src/webots/scene_tree/WbVector3Editor.cpp
Labels: bug

#270 Fix Matlab Controller on Windows
  change_logs/ChangeLog.html
  docs/guide/using-matlab.md
  lib/matlab/launcher.m
  lib/matlab/mex_mingw64_c.xml
Labels: bug

#271 Fix Windows Packaging
  src/packaging/files_core.txt
Labels: bug

#272 Fix E-puck Light Sensors Calibration.
  change_logs/ChangeLog.html
  projects/robots/gctronic/e-puck/protos/E-puck.proto
Labels: bug

#253 Start controllers from outside of Webots
  change_logs/ChangeLog.html
  docs/guide/debugging-c-cpp-controllers.md
  docs/guide/development-environments.md
  docs/guide/menu.md
  docs/guide/running-extern-robot-controllers.md
  docs/reference/robot.md
  include/controller/c/webots/utils/system.h
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.c
  src/lib/Controller/api/robot.c
  src/lib/Controller/api/scheduler.c
  src/lib/Controller/api/scheduler.h
  src/lib/Controller/api/system.c
  src/lib/Controller/util/g_pipe.c
  src/webots/control/WbControlledWorld.cpp
  src/webots/control/WbControlledWorld.hpp
  src/webots/control/WbController.cpp
  src/webots/core/WbStandardPaths.cpp
  src/webots/nodes/WbRobot.cpp
  src/webots/scene_tree/WbExtendedStringEditor.cpp
  tests/api/controllers/extern/.gitignore
  tests/api/controllers/extern/Makefile
  tests/api/controllers/extern/extern.c
  tests/api/worlds/extern.wbt
Labels: enhancement

#273 Add \f examples printf in devices controllers
  projects/samples/devices/controllers/battery/battery.c
  projects/samples/devices/controllers/gyro/gyro.c
  projects/samples/devices/controllers/motor/motor.c
  projects/samples/devices/controllers/position_sensor/position_sensor.c
  projects/samples/devices/controllers/radar/radar.c
  projects/samples/devices/controllers/receiver_noise/receiver_noise.c
  projects/samples/devices/controllers/spherical_camera/spherical_camera.c
  projects/samples/devices/worlds/receiver_noise.wbt
Labels: enhancement

#277 Improve appearance names
  change_logs/ChangeLog.html
  docs/guide/appearances.md
  docs/guide/images/appearances/CarLeather.png
  docs/guide/images/appearances/GlossyPaint.png
  docs/guide/images/appearances/Leather.png
  docs/guide/images/appearances/MattePaint.png
  docs/guide/object-factory.md
  docs/guide/object-lights.md
  projects/appearances/protos/GlossyPaint.proto
  projects/appearances/protos/Leather.proto
  projects/appearances/protos/MattePaint.proto
  projects/appearances/protos/icons/CarLeather.png
  projects/appearances/protos/icons/GlossyPaint.png
  projects/appearances/protos/icons/Leather.png
  projects/appearances/protos/icons/MattePaint.png
  projects/objects/factory/containers/protos/PlasticCrate.proto
  projects/objects/traffic/protos/StreetLight.proto
  projects/robots/clearpath/moose/protos/Moose.proto
  projects/samples/environments/factory/worlds/hall.wbt
  projects/vehicles/protos/abstract/CarSteeringWheel.proto
  projects/vehicles/protos/bmw/BmwX5Interior.proto
  projects/vehicles/protos/bmw/BmwX5Mesh.proto
  projects/vehicles/protos/bmw/BmwX5RearInterior.proto
  projects/vehicles/protos/citroen/CitroenCZeroMesh.proto
  projects/vehicles/protos/generic/BusShape.proto
  projects/vehicles/protos/generic/MotorbikeMesh.proto
  projects/vehicles/protos/generic/ScooterMesh.proto
  projects/vehicles/protos/generic/Tractor.proto
  projects/vehicles/protos/generic/TruckCab.proto
  projects/vehicles/protos/lincoln/LincolnMKZ.proto
  projects/vehicles/protos/lincoln/LincolnMKZSimple.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVR.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVRSimple.proto
  projects/vehicles/protos/toyota/ToyotaPriusMesh.proto
  scripts/icon_studio/controllers/icon_creator/appearances.json
Labels: enhancement

#279 Improve Sumo Interface Error Message
  projects/default/controllers/sumo_supervisor/sumo_supervisor.py
Labels: enhancement

#280 Fixed Arena protos
  docs/guide/object-floors.md
  projects/objects/floors/protos/CircleArena.proto
  projects/objects/floors/protos/RectangleArena.proto
Labels: bug, enhancement, invalid

#282 Fixed minimum mass of WoodenBox which was too high (for balsa for example)
  projects/objects/factory/containers/protos/WoodenBox.proto
Labels: enhancement

#285 ABB arm movie
  docs/guide/irb4600-40.md
Labels: enhancement

#286 Intermodal containers
  change_logs/ChangeLog.html
  docs/guide/images/objects/freight/IntermodalContainer/model.png
  docs/guide/images/objects/freight/IntermodalOfficeContainer/model.png
  docs/guide/menu.md
  docs/guide/object-freight.md
  docs/guide/objects.md
  projects/objects/freight/protos/IntermodalContainer.proto
  projects/objects/freight/protos/IntermodalOfficeContainer.proto
  projects/objects/freight/protos/icons/IntermodalContainer.png
  projects/objects/freight/protos/icons/IntermodalOfficeContainer.png
  scripts/icon_studio/controllers/icon_creator/objects.json
Labels: enhancement

#293 Add libnss3 to Debian Package
  src/packaging/webots_distro.c
Labels: bug, enhancement

#295 Better reference to license
  README.md
Labels: enhancement

#301 Fix keyboard enum
  change_logs/ChangeLog.html
  docs/reference/keyboard.md
  include/controller/c/webots/keyboard.h
Labels: bug

#289 Upgraded Qt to version 5.12.2 on Windows
  dependencies/Makefile.windows
  src/install_scripts/qt_windows_installer.sh
Labels: bug

#283 Fix tutorial 1
  docs/guide/images/tutorial_e-puck.png
  docs/guide/images/tutorial_gui.png
  docs/guide/installation-procedure.md
  docs/guide/menu.md
  docs/guide/prerequisites.md
  docs/guide/system-requirements.md
  docs/guide/tutorial-1-your-first-simulation-in-webots-20-minutes.md
  docs/guide/tutorial-2-modification-of-the-environment-20-minutes.md
  docs/guide/tutorial-3-appearance-15-minutes.md
  docs/guide/tutorial-4-more-about-controllers-20-minutes.md
  docs/guide/tutorial-5-compound-solid-and-physics-attributes-15-minutes.md
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/guide/tutorial-7-using-ros.md
  docs/guide/tutorials.md
  projects/samples/tutorials/worlds/my_first_simulation.wbt
Labels: enhancement

#308 Fix disabled Fog when visibilityRange is 0
  change_logs/ChangeLog.html
  src/webots/nodes/WbFog.cpp
Labels: bug

#310 Fix Light Doc.
  docs/reference/light.md
Labels: bug

#314 Remove unused functions
  src/webots/nodes/WbAppearance.cpp
  src/webots/nodes/WbAppearance.hpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbImageTexture.hpp
  src/webots/nodes/WbPbrAppearance.hpp
  src/webots/wren/WbWrenTextureOverlay.cpp
  src/webots/wren/WbWrenTextureOverlay.hpp
Labels: enhancement

#306 Fix Track X3D export.
  docs/js/viewer.js
  src/webots/nodes/utils/WbWorld.cpp
Labels: bug

#316 Fixed the display of pi and added explanation about formula
  docs/reference/pointlight.md
Labels: bug

#315 Fix AMD GPU memory reading
  change_logs/ChangeLog.html
  src/webots/gui/WbMainWindow.cpp
  src/wren/GlState.cpp
  src/wren/GlState.hpp
Labels: bug

#320 Cross Language Tutorial
  docs/guide/tutorial-1-your-first-simulation-in-webots-20-minutes.md
  docs/guide/tutorial-4-more-about-controllers-20-minutes.md
  docs/guide/tutorial-6-4-wheels-robot.md
  include/controller/cpp/webots/Motor.hpp
Labels: enhancement
