Repository cyberbotics/webots, pull requests merged in 2020-06, with the labels that each got.

#1715 Fix appveyor build
  src/install_scripts/msys64_installer.sh
Labels: bug

#1713 Fixed controller args with double quotes
  src/webots/control/WbController.cpp
  src/webots/control/WbController.hpp
Labels: bug

#1717 Fixed small typo
  docs/reference/node-chart.md
Labels: documentation

#1719 Fixed another Qt5.15 warning
  src/webots/gui/WbMultimediaStreamingServer.cpp
Labels: bug

#1559 Fix controllers clear console
  docs/reference/utility-functions.md
  projects/robots/clearpath/moose/controllers/moose_path_following/moose_path_following.c
  projects/robots/saeon/controllers/vehicle_driver_altino/vehicle_driver_altino.py
  projects/samples/demos/controllers/moon/moon.c
  projects/samples/devices/controllers/receiver_noise/receiver_noise.c
  projects/samples/devices/worlds/.battery.wbproj
  projects/samples/devices/worlds/.gyro.wbproj
  projects/samples/devices/worlds/.motor.wbproj
  projects/samples/devices/worlds/.position_sensor.wbproj
  projects/samples/devices/worlds/.radar.wbproj
  projects/samples/devices/worlds/.receiver_noise.wbproj
  projects/samples/devices/worlds/.spherical_camera.wbproj
  projects/samples/howto/worlds/.physics.wbproj
  src/webots/core/WbLog.cpp
  src/webots/core/WbLog.hpp
  src/webots/gui/WbConsole.cpp
Labels: bug, enhancement, question

#1721 Fix icon path
  src/packaging/webots_distro.c
  src/packaging/webots_snap.desktop
Labels: bug

#1723 Fix contact point representation update
  docs/reference/changelog-r2020.md
  src/webots/app/WbContactPointsRepresentation.cpp
Labels: bug

#1727 Improve Test Suite Robustness
  tests/command.py
  tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py
  tests/test_suite.py
Labels: enhancement

#1731 FIx Crossroad Bottom Appearance
  projects/objects/road/protos/Crossroad.proto
Labels: bug

#1732 Fix Tiago Gripper
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoGripper.proto
Labels: enhancement

#1730 Better controller starting message and backwards compatibility
  src/webots/control/WbController.cpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/utils/WbTemplateManager.cpp
Labels: bug

#1735 Added Cyberbotics for GitHub sponsor
  .github/FUNDING.yml
Labels: enhancement

#1710 Update to Qt 5.15.0 on Linux
  .travis.yml
  dependencies/Makefile.linux
  docs/reference/changelog-r2020.md
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/Automaton.cpp
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/Model.cpp
  resources/projects/libraries/qt_utils/motion_editor/Motion.cpp
  resources/projects/libraries/qt_utils/motion_editor/Pose.cpp
  src/install_scripts/qt_linux_installer.sh
  src/packaging/files_core.txt
  src/packaging/webots_distro.c
  src/webots/control/WbController.cpp
  src/webots/core/WbTemplateEngine.cpp
  src/webots/gui/WbStreamingServer.cpp
Labels: upgrade

#1742 Added new legged robot from Matt Denton
  docs/reference/changelog-r2020.md
  projects/robots/Makefile
  projects/robots/micromagic/scout/controllers/Makefile
  projects/robots/micromagic/scout/controllers/scout/.gitignore
  projects/robots/micromagic/scout/controllers/scout/Makefile
  projects/robots/micromagic/scout/controllers/scout/scout.c
  projects/robots/micromagic/scout/controllers/scout/scout.motion
  projects/robots/micromagic/scout/worlds/.scout.wbproj
  projects/robots/micromagic/scout/worlds/scout.wbt
Labels: enhancement

#1744 Improve propeller documentation
  docs/reference/propeller.md
Labels: documentation, enhancement

#1740 Display Normals
  docs/guide/the-user-interface.md
  docs/reference/changelog-r2020.md
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbView3D.hpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbTriangleMeshGeometry.cpp
  src/webots/nodes/WbTriangleMeshGeometry.hpp
  src/webots/nodes/utils/WbTriangleMesh.cpp
  src/webots/nodes/utils/WbTriangleMesh.hpp
  src/webots/user_commands/WbActionManager.cpp
  src/webots/user_commands/WbActionManager.hpp
  src/webots/wren/WbWrenRenderingContext.hpp
Labels: enhancement

#1763 Fix compilation warning
  src/webots/gui/WbStreamingServer.cpp
Labels: bug

#1754 Add additional scene interaction options in wbproj
  docs/guide/the-user-interface.md
  docs/reference/changelog-r2020.md
  projects/samples/robotbenchmark/highway_driving/worlds/.highway_driving.wbproj
  projects/samples/robotbenchmark/humanoid_marathon/worlds/.humanoid_marathon.wbproj
  projects/samples/robotbenchmark/humanoid_sprint/worlds/.humanoid_sprint.wbproj
  projects/samples/robotbenchmark/inverted_pendulum/worlds/.inverted_pendulum.wbproj
  projects/samples/robotbenchmark/maze_runner/worlds/.maze_runner.wbproj
  projects/samples/robotbenchmark/obstacle_avoidance/worlds/.obstacle_avoidance.wbproj
  projects/samples/robotbenchmark/pick_and_place/worlds/.pick_and_place.wbproj
  projects/samples/robotbenchmark/pit_escape/worlds/.pit_escape.wbproj
  projects/samples/robotbenchmark/robot_programming/worlds/.robot_programming.wbproj
  projects/samples/robotbenchmark/square_path/worlds/.square_path.wbproj
  projects/samples/robotbenchmark/visual_tracking/worlds/.visual_tracking.wbproj
  projects/samples/robotbenchmark/wall_following/worlds/.wall_following.wbproj
  src/webots/app/WbPerspective.cpp
  src/webots/app/WbPerspective.hpp
  src/webots/core/WbAction.hpp
  src/webots/editor/WbTextEditor.cpp
  src/webots/editor/WbTextEditor.hpp
  src/webots/gui/WbConsole.cpp
  src/webots/gui/WbConsole.hpp
  src/webots/gui/WbDocumentation.cpp
  src/webots/gui/WbDocumentation.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbSimulationView.cpp
  src/webots/gui/WbSimulationView.hpp
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbView3D.hpp
  src/webots/scene_tree/WbFieldEditor.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/scene_tree/WbSceneTree.hpp
  src/webots/user_commands/WbActionManager.cpp
  src/webots/user_commands/WbActionManager.hpp
  src/webots/user_commands/WbContextMenuGenerator.cpp
  src/webots/user_commands/WbUndoStack.cpp
Labels: enhancement

#1736 Update to Qt5.15 on macOS
  dependencies/Makefile.mac
  docs/reference/changelog-r2020.md
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/Automaton.cpp
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/Model.cpp
  resources/projects/libraries/qt_utils/motion_editor/Motion.cpp
  resources/projects/libraries/qt_utils/motion_editor/Pose.cpp
  src/install_scripts/qt_mac_installer.sh
  src/packaging/files_core.txt
  src/packaging/webots_distro.c
  src/webots/control/WbController.cpp
  src/webots/core/WbTemplateEngine.cpp
  src/webots/gui/WbStreamingServer.cpp
Labels: upgrade

#1706 Allow Basic URDF Export
  .gitignore
  docs/reference/changelog-r2020.md
  docs/reference/robot.md
  include/controller/c/webots/robot.h
  include/controller/cpp/webots/Robot.hpp
  lib/controller/matlab/ANSI_BLACK_BACKGROUND.m
  lib/controller/matlab/mgenerate.py
  lib/controller/matlab/wb_robot_get_urdf.m
  projects/default/controllers/ros/Ros.cpp
  projects/default/controllers/ros/Ros.hpp
  projects/default/controllers/ros/include/srv/get_urdf.srv
  projects/languages/ros/webots_ros/CMakeLists.txt
  projects/languages/ros/webots_ros/src/complete_test.cpp
  resources/languages/cpp/Robot.cpp
  src/lib/Controller/Controller.def
  src/lib/Controller/api/messages.h
  src/lib/Controller/api/robot.c
  src/webots/core/WbLanguage.cpp
  src/webots/maths/WbMatrix3.cpp
  src/webots/maths/WbMatrix3.hpp
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbBallJoint.hpp
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbBaseNode.hpp
  src/webots/nodes/WbBasicJoint.cpp
  src/webots/nodes/WbBasicJoint.hpp
  src/webots/nodes/WbGeometry.cpp
  src/webots/nodes/WbGeometry.hpp
  src/webots/nodes/WbHinge2Joint.cpp
  src/webots/nodes/WbHinge2Joint.hpp
  src/webots/nodes/WbJoint.cpp
  src/webots/nodes/WbJoint.hpp
  src/webots/nodes/WbJointParameters.cpp
  src/webots/nodes/WbJointParameters.hpp
  src/webots/nodes/WbLogicalDevice.cpp
  src/webots/nodes/WbLogicalDevice.hpp
  src/webots/nodes/WbPbrAppearance.cpp
  src/webots/nodes/WbPbrAppearance.hpp
  src/webots/nodes/WbPhysics.cpp
  src/webots/nodes/WbPhysics.hpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbRobot.hpp
  src/webots/nodes/WbSliderJoint.cpp
  src/webots/nodes/WbSliderJoint.hpp
  src/webots/nodes/WbSolidDevice.cpp
  src/webots/nodes/WbSolidDevice.hpp
  src/webots/nodes/WbTransform.cpp
  src/webots/nodes/WbTransform.hpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
  src/webots/vrml/WbSFNode.cpp
  src/webots/vrml/WbVrmlWriter.cpp
  src/webots/vrml/WbVrmlWriter.hpp
  tests/api/controllers/robot_urdf/.gitignore
  tests/api/controllers/robot_urdf/Makefile
  tests/api/controllers/robot_urdf/reference_robot.urdf
  tests/api/controllers/robot_urdf/robot_urdf.c
  tests/api/worlds/robot_urdf.wbt
  tests/ros.sh
Labels: enhancement

#1771 Fix typo in web interface help.php
  resources/web/wwi/help.php
Labels: documentation

#1772 Remove outdated log entry
  docs/reference/changelog-r2020.md
Labels: documentation

#1770 Fix Qt 5.15 deprecation warnings reintroduced during merge
  src/webots/gui/WbView3D.cpp
Labels: bug

#1768 Fix self node in supervisor.c for a Robot proto parameter node
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
Labels: bug

#1747 Fix Console
  resources/projects/worlds/.empty.wbproj
  src/webots/app/WbPerspective.cpp
  src/webots/app/WbPerspective.hpp
  src/webots/gui/WbConsole.cpp
  src/webots/gui/WbMainWindow.cpp
Labels: bug

#1766 Update compiling-controllers-in-a-terminal.md
  docs/guide/compiling-controllers-in-a-terminal.md
Labels: documentation

#1776 Improved motor PID control table.
  docs/reference/motor.md
Labels: enhancement

#1775 Fix urdf test
  .travis.yml
  tests/api/controllers/robot_urdf/.gitignore
  tests/api/controllers/robot_urdf/robot_urdf.c
Labels: bug

#1782 Update call to ``inverse_kinematics``
  projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
Labels: bug, upgrade

#1790 Add missign Robotis-op2 supervisor field.
  docs/guide/robotis-op3.md
  docs/reference/changelog-r2020.md
  projects/robots/robotis/darwin-op/protos/RobotisOp2.proto
  projects/robots/robotis/darwin-op/protos/RobotisOp3.proto
Labels: bug

#1791 Fix Typo in Node-Chart
  docs/reference/node-chart.md
Labels: bug

#1792 Fix UnevenTerrain
  docs/guide/object-floors.md
  docs/reference/changelog-r2020.md
  projects/objects/floors/protos/UnevenTerrain.proto
  projects/robots/micromagic/mantis/worlds/mantis.wbt
  projects/robots/sphero/bb8/worlds/bb-8.wbt
Labels: enhancement

#1781 Fixed Typo in PannelWithTubes
  docs/guide/object-panels.md
  docs/reference/changelog-r2020.md
  projects/languages/ros/worlds/pioneer3at.wbt
  projects/objects/panels/protos/PanelWithTubes.proto
  projects/objects/panels/protos/PannelWithTubes.proto
  projects/objects/panels/protos/icons/PanelWithTubes.png
  projects/robots/festo/robotino3/worlds/robotino3.wbt
  projects/robots/pal_robotics/tiago++/worlds/tiago++.wbt
  projects/robots/pal_robotics/tiago_base/worlds/tiago_base.wbt
  projects/robots/pal_robotics/tiago_iron/worlds/tiago_iron.wbt
  projects/robots/pal_robotics/tiago_steel/worlds/tiago_steel.wbt
  projects/robots/pal_robotics/tiago_titanium/worlds/tiago_titanium.wbt
Labels: bug

#1793 Windows uninstaller warns and delete the whole modified installation folder
  src/packaging/webots_distro.c
Labels: enhancement

#1796 Removed unneeded appveyor patch
  .appveyor-build-tag.yml
  .appveyor-build.yml
  .appveyor-test-sources-scheduled.yml
Labels: cleanup

#1799 Fixed noise description
  docs/reference/camera.md
  docs/reference/differentialwheels.md
Labels: documentation

#1801 Fix Various Battery Issues
  docs/reference/changelog-r2020.md
  docs/reference/motor.md
  docs/reference/robot.md
  src/webots/nodes/WbLinearMotor.cpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbRobot.cpp
  tests/api/controllers/battery_empty/.gitignore
  tests/api/controllers/battery_empty/Makefile
  tests/api/controllers/battery_empty/battery_empty.c
  tests/api/worlds/battery.wbt
Labels: bug

#1809 Simpler patch for camera reset bug
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbRobot.hpp
Labels: cleanup

#1802 Fix Camera Reset
  docs/reference/changelog-r2020.md
  src/lib/Controller/api/abstract_camera.c
  src/webots/nodes/WbRobot.cpp
Labels: bug

#1806 Fix URDF Link Naming
  src/webots/vrml/WbNode.cpp
  tests/api/controllers/robot_urdf/reference_robot.urdf
Labels: bug

#1811 correction of Bug https://github.com/cyberbotics/webots/issues/1810
  projects/objects/road/protos/Crossroad.proto
Labels: enhancement

#1659 supervisor.md tutorial pos/rot relative to other nodes
  docs/js/showdown-extensions.js
  docs/reference/supervisor.md
Labels: enhancement

#1814 Add Github Action Doc Test
  .github/workflows/tests_doc.yml
Labels: enhancement

#1815 Add Github Action Sources Test
  .github/workflows/tests_sources.yml
  tests/sources/test_cppcheck.py
Labels: enhancement

#1816 Simplify test_suite.py
  tests/test_suite.py
Labels: cleanup

#1813 Fix Crash with Normals
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbIndexedFaceSet.cpp
  src/webots/nodes/utils/WbTriangleMesh.cpp
  tests/rendering/protos/IndexedFaceSetWithNormals.proto
  tests/rendering/worlds/normals.wbt
Labels: bug, crash

#1820 Update debugging-c-cpp-controllers.md
  docs/guide/debugging-c-cpp-controllers.md
Labels: documentation

#1822 Fix Mesh Node Crash
  src/webots/nodes/WbMesh.cpp
Labels: crash

#1827 Fix cppcheck Warnings
  projects/languages/ros/webots_ros/src/e_puck_line.cpp
  src/lib/Controller/api/remote_control.c
  src/lib/Controller/api/supervisor.c
  src/webots/nodes/WbDisplay.cpp
  src/wren/DrawableTexture.cpp
  src/wren/Font.cpp
  src/wren/PostProcessingEffect.cpp
Labels: enhancement

#1826 Hotfix infra red distance sensors
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbShape.cpp
  tests/api/controllers/distance_sensor_infra-red/distance_sensor_infra-red.c
  tests/api/worlds/distance_sensor_infra-red_vs_transformed_planes.wbt
Labels: bug

#1828 Fix camera/rangefinder vertical field of view doc
  docs/reference/camera.md
  docs/reference/rangefinder.md
Labels: documentation

#1824 Fixes crash when clicking on a node in the scene tree
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/scene_tree/WbTreeItem.hpp
Labels: crash

#1833 Fix parent methods in qobject
  src/webots/app/WbProtoCachedInfo.cpp
  src/webots/gui/WbX3dStreamingServer.cpp
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbBasicJoint.cpp
  src/webots/nodes/WbGroup.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbJointDevice.cpp
  src/webots/nodes/WbLed.cpp
  src/webots/nodes/WbLinearMotor.cpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbMuscle.cpp
  src/webots/nodes/WbSliderJoint.cpp
  src/webots/nodes/WbSlot.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolidReference.cpp
  src/webots/nodes/utils/WbBoundingSphere.cpp
  src/webots/nodes/utils/WbBoundingSphere.hpp
  src/webots/nodes/utils/WbConcreteNodeFactory.cpp
  src/webots/nodes/utils/WbDictionary.cpp
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbSolidUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbTemplateManager.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbField.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
Labels: cleanup

#1817 Create test_suite.yml
  .github/workflows/test_suite.yml
  src/packaging/update_all_worlds.py
  tests/manual_tests/test_worlds_warnings.py
Labels: enhancement

#1836 Fixed rendering of tracks and muscles in robot cameras (master)
  docs/reference/changelog-r2020.md
  src/webots/nodes/utils/WbWrenVertexArrayFrameListener.cpp
  src/wren/Scene.cpp
Labels: bug

#1840 Removed develop worflow dependency
  .github/workflows/test_suite.yml
Labels: cleanup

#1838 docs: add a mechanical loop example
  docs/reference/solidreference.md
Labels: documentation

#1845 Remove Useless Test Suite Workflow Step
  .github/workflows/test_suite.yml
Labels: cleanup

#1761 Fix disabling shift+drag
  docs/reference/changelog-r2020.md
  src/webots/gui/WbView3D.cpp
  src/webots/nodes/WbAbstractTransform.cpp
  src/webots/nodes/WbAbstractTransform.hpp
Labels: bug

#1850 Fix Ubuntu 20.04 Clang-Format File
  dependencies/Makefile.linux
Labels: enhancement

#1851 Fix Texture Filtering Field auto-changed.
  docs/guide/preferences.md
  docs/reference/changelog-r2020.md
  src/webots/core/WbPreferences.cpp
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbPreferencesDialog.hpp
  src/webots/gui/WbView3D.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbImageTexture.hpp
Labels: bug, cleanup, enhancement
