Repository cyberbotics/webots, pull requests merged in 2020-08, with the labels that each got.

#2038 Improve instructions to use pycharm
  docs/guide/using-your-ide.md
Labels: documentation

#2052 Remove Workflow Useless Step
  .github/workflows/test_suite.yml
Labels: enhancement

#2051 Fix Robotino3
  docs/reference/changelog-r2020.md
  projects/robots/festo/robotino3/protos/Robotino3Webcam.proto
  projects/robots/festo/robotino3/worlds/robotino3.wbt
Labels: bug

#2053 Removed ROS controller on macOS.
  docs/guide/using-ros.md
  docs/reference/changelog-r2020.md
  projects/default/Makefile
  projects/vehicles/controllers/Makefile
  src/packaging/exist_in_projects_mac.txt
Labels: bug, cleanup

#2055 Add Warnings when Importing Big Meshes.
  src/webots/nodes/utils/WbNodeOperations.cpp
Labels: enhancement

#2061 Fixed user input test on Windows
  tests/api/controllers/robot_wait_for_user_input_event/robot_wait_for_user_input_event.c
Labels: enhancement

#2060 Added precision to extern controllers setup
  docs/guide/running-extern-robot-controllers.md
Labels: documentation

#2062 Improve Inverse Kinematic Sample
  docs/reference/changelog-r2020.md
  projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
  src/webots/nodes/WbJoint.cpp
Labels: enhancement

#2071 Fixed firejail controllers
  docs/reference/changelog-r2020.md
  src/webots/control/WbController.cpp
Labels: bug

#2068 Fix URDF Export with Track Node
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbTrack.cpp
  src/webots/nodes/WbTrackWheel.cpp
  src/webots/nodes/WbTrackWheel.hpp
  tests/api/controllers/robot_urdf/reference_robot.urdf
  tests/api/worlds/robot_urdf.wbt
Labels: bug

#2070 Fix Procedural PROTOs not Working on Windows Release
  docs/reference/changelog-r2020.md
  src/packaging/files_msys64.txt
Labels: bug

#2063 Fix nested PROTO field redirection
  docs/reference/changelog-r2020.md
  src/webots/vrml/WbNode.cpp
  tests/protos/controllers/nested_mixed_template_proto/nested_mixed_template_proto.c
  tests/protos/protos/Empty.proto
  tests/protos/protos/SlotWithInternalProto.proto
  tests/protos/protos/SolidCylinder.proto
  tests/protos/worlds/proto_nested_2.wbt
Labels: bug

#2081 Cleanup hyperlinks
  docs/guide/starting-webots.md
  src/webots/core/WbTelemetry.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbNewVersionDialog.cpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbSingleTaskApplication.cpp
Labels: cleanup

#2079 Add Python Brew API Compilation.
  .travis.yml
  docs/guide/running-extern-robot-controllers.md
  docs/guide/using-python.md
  docs/reference/changelog-r2020.md
  lib/controller/.gitignore
  resources/languages/Makefile
  resources/languages/python/Makefile
  src/packaging/files_core.txt
  src/webots/control/WbController.cpp
Labels: enhancement

#2074 Add wb_supervisor_get_from_device function
  docs/reference/changelog-r2021.md
  docs/reference/changelog.md
  docs/reference/device.md
  docs/reference/menu.md
  docs/reference/supervisor.md
  include/controller/c/webots/supervisor.h
  include/controller/cpp/webots/Supervisor.hpp
  lib/controller/matlab/mgenerate.py
  lib/controller/matlab/wb_supervisor_node_get_from_device.m
  projects/default/controllers/ros/RosSupervisor.cpp
  projects/default/controllers/ros/RosSupervisor.hpp
  projects/default/controllers/ros/include/srv/supervisor_get_from_string.srv
  projects/languages/ros/webots_ros/CMakeLists.txt
  projects/languages/ros/webots_ros/src/complete_test.cpp
  resources/languages/cpp/Supervisor.cpp
  resources/languages/java/controller.i
  resources/languages/python/controller.i
  src/lib/Controller/Controller.def
  src/lib/Controller/api/messages.h
  src/lib/Controller/api/supervisor.c
  src/webots/core/WbLanguage.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  tests/api/controllers/supervisor_node/supervisor_node.c
  tests/api/worlds/supervisor_node.wbt
Labels: enhancement

#2089 Doc: add Community Projects
  docs/guide/menu.md
  docs/guide/sample-webots-applications.md
  docs/guide/samples-community-projects.md
Labels: documentation

#2092 Updated NPM packages to fix build warning
  resources/web/wwi/package.json
Labels: upgrade

#2077 Cleanup of the streaming server protocol
  docs/reference/changelog-r2020.md
  resources/web/server/simulation_server.py
  resources/web/wwi/server.js
  resources/web/wwi/stream.js
  src/webots/gui/WbMultimediaStreamingServer.cpp
  src/webots/gui/WbMultimediaStreamingServer.hpp
  src/webots/gui/WbStreamingServer.cpp
  src/webots/gui/WbStreamingServer.hpp
Labels: cleanup

#2088 Fix color of the first console message.
  docs/reference/changelog-r2020.md
  src/webots/gui/WbMainWindow.cpp
Labels: bug

#2084 Improve detection of PROTO template regenerator fields
  src/webots/vrml/WbProtoModel.cpp
Labels: enhancement

#2082 Improve update of USE nodes
  src/webots/vrml/WbNode.cpp
Labels: bug

#2103 Improve Doc Test
  .github/workflows/tests_doc.yml
Labels: enhancement

#2099 Fix HelicoidalRoadSegment PROTO
  docs/reference/changelog-r2020.md
  projects/objects/road/protos/HelicoidalRoadSegment.proto
Labels: bug

#2105 Improve streaming error messages
  src/webots/gui/WbMultimediaStreamingServer.cpp
  src/webots/gui/WbX3dStreamingServer.cpp
Labels: enhancement

#2100 Fix use of invalid scene tree selected item
  docs/reference/changelog-r2020.md
  src/webots/scene_tree/WbSceneTree.cpp
Labels: crash

#2102 Fix macOS nightly
  .travis.yml
Labels: bug

#2104 Run workflows on label
  .github/workflows/test_suite.yml
Labels: enhancement, test distribution, test suite, test world update

#2072 Fix SliderJoint URDF export.
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbJoint.cpp
  src/webots/nodes/WbSliderJoint.cpp
  src/webots/nodes/WbTransform.cpp
Labels: bug, test suite

#2111 Fix crash on macOS when deleting the world
  src/webots/gui/WbView3D.cpp
Labels: crash, test suite

#2112 Fix scaled matrix returned by wb_supervisor_node_get_orientation
  docs/reference/changelog-r2020.md
  projects/default/controllers/ros/RosMathUtils.cpp
  src/webots/maths/WbMatrix4.cpp
  src/webots/maths/WbMatrix4.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  tests/api/controllers/supervisor_get_position_orientation/supervisor_get_position_orientation.c
  tests/api/worlds/supervisor_get_position_orientation.wbt
Labels: bug, test suite

#2115 Fix ROS camera recognition topic
  docs/reference/changelog-r2020.md
  projects/default/controllers/ros/RosCamera.cpp
  projects/default/controllers/ros/RosCamera.hpp
Labels: bug, test suite

#2117 Fixed selection of robots with closed loop
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbBasicJoint.cpp
  src/webots/plugins/WbPhysicsPlugin.cpp
Labels: crash, test suite

#2122 Add minimum python version for test_worlds_warnings.py
  tests/manual_tests/test_worlds_warnings.py
Labels: enhancement

#2107 Fix DEF not found on load for default PROTO parameter values
  docs/reference/changelog-r2020.md
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
  src/webots/vrml/WbNodeReader.cpp
  src/webots/vrml/WbNodeReader.hpp
  tests/parser/expected_results.txt
  tests/parser/protos/DefaultDef.proto
  tests/parser/worlds/proto_default_def_parameter.wbt
  tests/protos/controllers/proto_default_def_node/.gitignore
  tests/protos/controllers/proto_default_def_node/Makefile
  tests/protos/controllers/proto_default_def_node/proto_default_def_node.c
  tests/protos/protos/DefaultDef.proto
  tests/protos/worlds/proto_default_def_node.wbt
Labels: bug, test suite

#2113 Feature Export URDF Geometry
  docs/reference/changelog-r2020.md
  docs/reference/robot.md
  src/webots/maths/WbRotation.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolid.hpp
  src/webots/vrml/WbNode.cpp
  tests/api/controllers/robot_urdf/reference_robot.urdf
Labels: enhancement, test distribution, test suite, test world update

#2125 Fix ROS complete_test
  projects/languages/ros/webots_ros/src/complete_test.cpp
Labels: bug, test suite

#2130 Improve conversion.
  scripts/converter/convert_to_enu.py
Labels: enhancement

#2119 Fix issues with extern rendering device windows
  docs/reference/changelog-r2020.md
  src/webots/gui/WbRenderingDeviceWindow.cpp
  src/webots/gui/WbRenderingDeviceWindow.hpp
  tests/rendering/controllers/mirror_supervisor/mirror_supervisor.c
  tests/rendering/worlds/.mirror.wbproj
  tests/rendering/worlds/mirror.wbt
Labels: bug, crash, test suite

#2133 Add comments to setup_viewer.js
  resources/web/streaming_viewer/setup_viewer.js
Labels: enhancement

#2134 Merge master to develop
  docs/discord/development.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions.md
  docs/reference/changelog-r2020.md
  docs/reference/robot.md
  projects/default/controllers/ros/RosCamera.cpp
  projects/default/controllers/ros/RosCamera.hpp
  projects/default/controllers/ros/RosMathUtils.cpp
  projects/languages/ros/webots_ros/src/complete_test.cpp
  scripts/converter/convert_to_enu.py
  src/webots/gui/WbRenderingDeviceWindow.cpp
  src/webots/gui/WbRenderingDeviceWindow.hpp
  src/webots/gui/WbView3D.cpp
  src/webots/maths/WbMatrix4.cpp
  src/webots/maths/WbMatrix4.hpp
  src/webots/maths/WbRotation.cpp
  src/webots/nodes/WbBasicJoint.cpp
  src/webots/nodes/WbJoint.cpp
  src/webots/nodes/WbSliderJoint.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolid.hpp
  src/webots/nodes/WbTransform.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/plugins/WbPhysicsPlugin.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
  src/webots/vrml/WbNodeReader.cpp
  src/webots/vrml/WbNodeReader.hpp
  tests/api/controllers/robot_urdf/reference_robot.urdf
  tests/api/controllers/supervisor_get_position_orientation/supervisor_get_position_orientation.c
  tests/api/worlds/supervisor_get_position_orientation.wbt
  tests/manual_tests/test_worlds_warnings.py
  tests/parser/expected_results.txt
  tests/parser/protos/DefaultDef.proto
  tests/parser/worlds/proto_default_def_parameter.wbt
  tests/protos/controllers/proto_default_def_node/.gitignore
  tests/protos/controllers/proto_default_def_node/Makefile
  tests/protos/controllers/proto_default_def_node/proto_default_def_node.c
  tests/protos/protos/DefaultDef.proto
  tests/protos/worlds/proto_default_def_node.wbt
  tests/rendering/controllers/mirror_supervisor/mirror_supervisor.c
  tests/rendering/worlds/.mirror.wbproj
  tests/rendering/worlds/mirror.wbt
Labels: test suite

#2132 Fix synchronization of libController node list
  docs/reference/changelog-r2020.md
  src/Controller/api/supervisor.c
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  tests/api/controllers/supervisor_import_remove/supervisor_import_remove.c
Labels: bug, test suite

#2137 meter per radian => radian per secod
  docs/reference/motor.md
Labels: documentation

#2127 Attempt to fix ros controller.
  .github/workflows/test_suite.yml
  .travis.yml
  docs/reference/changelog-r2020.md
  projects/default/Makefile
  projects/default/controllers/ros/Makefile
  projects/default/controllers/ros/include/Makefile
  projects/default/controllers/ros/lib/Makefile
  projects/default/controllers/ros/lib/ros/.gitignore
  projects/vehicles/controllers/ros_automobile/Makefile
  scripts/install/bashrc.linux
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/packaging/exist_in_projects_linux.txt
  scripts/packaging/webots_distro.c
  tests/ros.sh
Labels: bug, test distribution, test suite

#2140 Fixed indentation of the URDF export.
  src/webots/nodes/WbSliderJoint.cpp
Labels: bug, test suite

#2141 Disable ODE DEBUG in release mode.
  docs/reference/changelog-r2020.md
  src/ode/Makefile
  src/ode/ode/src/fluid_dynamics/ode_fluid_dynamics.cpp
  src/ode/ode/src/ode.cpp
  src/ode/ode/src/ode_MT/clustering/cluster.cpp
  src/ode/ode/src/ode_MT/threading/threadManagerPthread.cpp
  src/ode/ode/src/ode_MT/util_MT.cpp
  src/ode/ode/src/ode_MT/util_MT.h
Labels: bug, crash, test suite

#2144 Added missing wbproj files
  tests/api/worlds/.gitignore
  tests/api/worlds/.robot_window_html.wbproj
  tests/rendering/worlds/.gitignore
  tests/rendering/worlds/.mirror.wbproj
Labels: cleanup

#2146 Cleanup ODE MT.
  src/ode/ode/src/ode_MT/clustering/cluster.cpp
  src/ode/ode/src/ode_MT/threading/threadManagerPthread.cpp
Labels: bug, test suite

#2142 Fix unsupported PbrAppearance in IndexedLineSet and PointSet
  docs/reference/changelog-r2020.md
  docs/reference/indexedlineset.md
  docs/reference/pbrappearance.md
  docs/reference/pointset.md
  projects/robots/gctronic/e-puck/protos/E-puckDistanceSensor.proto
  projects/robots/gctronic/elisa/protos/Elisa3DistanceSensor.proto
  projects/robots/k-team/khepera1/protos/Khepera1.proto
  projects/samples/devices/worlds/lidar.wbt
  projects/samples/devices/worlds/spherical_camera.wbt
  projects/samples/geometries/worlds/geometric_primitives.wbt
  src/webots/nodes/WbIndexedLineSet.cpp
  src/webots/nodes/WbPointSet.cpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
Labels: bug, regression, test suite

#2148 Fix URDF test on Windows
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbJoint.cpp
  src/webots/nodes/WbSliderJoint.cpp
  src/webots/nodes/WbSolid.cpp
  tests/api/controllers/robot_urdf/reference_robot.urdf
  tests/api/controllers/robot_urdf/robot_urdf.c
Labels: enhancement, test suite, test suite issue

#2143 Fix wrong image in Display in vision.wbt
  docs/reference/changelog-r2020.md
  projects/samples/howto/controllers/vision/vision.cpp
Labels: bug, test suite

#2151 Fixed local_exporter script
  docs/local_exporter.py
Labels: bug

#2153 Fixed make warning due to npm on mac OS
  resources/web/wwi/Makefile
Labels: cleanup

#2152 Fix robot-window not up to date.
  docs/reference/changelog-r2020.md
  src/webots/control/WbController.cpp
  tests/api/controllers/extern/extern.c
  tests/api/worlds/extern.wbt
Labels: bug, test suite

#2023 Add macOS to GitHub Action Worflow
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_mac.yml
Labels: enhancement, test suite

#2087 Adding function to retrieve the state of a connector
  docs/reference/changelog-r2021.md
  docs/reference/connector.md
  include/controller/c/webots/connector.h
  include/controller/cpp/webots/Connector.hpp
  lib/controller/matlab/mgenerate.py
  lib/controller/matlab/wb_connector_is_locked.m
  projects/default/controllers/ros/RosConnector.cpp
  projects/default/controllers/ros/RosConnector.hpp
  projects/languages/ros/webots_ros/src/complete_test.cpp
  resources/languages/cpp/Connector.cpp
  src/Controller/Controller.def
  src/Controller/api/connector.c
  src/webots/core/WbLanguage.cpp
  src/webots/nodes/WbConnector.cpp
  src/webots/nodes/WbConnector.hpp
  tests/api/controllers/connector/connector.c
Labels: enhancement, test suite

#2156 Improve URDF export test.
  tests/api/controllers/robot_urdf/.gitignore
  tests/api/controllers/robot_urdf/robot_urdf.c
  tests/api/controllers/robot_urdf/tiago_reference.urdf
  tests/api/controllers/robot_urdf/ur5e_reference.urdf
  tests/api/worlds/robot_urdf.wbt
Labels: enhancement, test suite

#2155 Fixed conversion from matrix3 to axis angle
  src/webots/maths/WbRotation.cpp
Labels: bug, test suite

#2145 Use motor name as urdf-joint name
  docs/reference/robot.md
  src/webots/nodes/WbJoint.cpp
  tests/api/controllers/robot_urdf/tiago_reference.urdf
  tests/api/controllers/robot_urdf/ur5e_reference.urdf
Labels: enhancement, test suite

#2138 Fix camera image update time check for asynchronous controller
  docs/reference/changelog-r2020.md
  projects/samples/devices/controllers/camera/camera.c
  src/Controller/api/abstract_camera.c
  src/Controller/api/robot_private.h
  src/Controller/api/supervisor.c
Labels: bug, test suite

#2150 OSM_Importer upgrade lib urllib for python3
  docs/reference/changelog-r2020.md
  resources/osm_importer/elevation.py
  resources/osm_importer/importer.py
  resources/osm_importer/osm_objects.py
  resources/osm_importer/parser_objects.py
  resources/osm_importer/projection.py
  resources/osm_importer/settings.py
Labels: enhancement

#2159 Update documentation and changelog for releasing R2020b rev1
  docs/guide/object-road.md
  docs/reference/changelog-r2020.md
Labels: documentation

#2166 Fix ros controller Makefile
  projects/default/controllers/ros/Makefile
Labels: bug, test suite

#2170 Fix Missing Blog Index
  docs/blog/index.md
Labels: enhancement

#2163 Fix Empty Forest
  projects/objects/trees/protos/Forest.proto
Labels: bug

#2162 Hide Indicator Motor in Vehicle Robot-Window
  docs/reference/changelog-r2020.md
  projects/vehicles/plugins/robot_windows/automobile_window/Viewer.cpp
Labels: bug, test suite

#2171 Fixed broken native Qt robot windows on Windows
  projects/robots/gctronic/e-puck/controllers/line_follower/runtime.ini
  projects/robots/gctronic/e-puck/controllers/obstacle/runtime.ini
  projects/robots/robotis/darwin-op/controllers/motion_player/runtime.ini
  projects/robots/robotis/darwin-op/controllers/soccer/runtime.ini
  projects/robots/robotis/darwin-op/controllers/symmetry/runtime.ini
  projects/robots/robotis/darwin-op/controllers/symmetry_matlab/runtime.ini
  projects/robots/robotis/darwin-op/controllers/visual_tracking/runtime.ini
  projects/robots/robotis/darwin-op/controllers/walk/runtime.ini
  projects/samples/curriculum/controllers/beginner_better_collision_avoidance_algorithm/runtime.ini
  projects/samples/curriculum/controllers/beginner_blinking_e-puck/runtime.ini
  projects/samples/curriculum/controllers/beginner_e-puck_dance/runtime.ini
  projects/samples/curriculum/controllers/beginner_finite_state_machine/runtime.ini
  projects/samples/curriculum/controllers/beginner_linear_camera/runtime.ini
  projects/samples/curriculum/controllers/beginner_move_your_e-puck/runtime.ini
  projects/samples/curriculum/controllers/beginner_rally/runtime.ini
  projects/samples/curriculum/controllers/novice_remain_in_shadow/runtime.ini
  projects/samples/curriculum/controllers/novice_train/runtime.ini
  projects/vehicles/controllers/VehicleDriver/runtime.ini
  projects/vehicles/controllers/autonomous_vehicle/runtime.ini
  projects/vehicles/controllers/boomer/runtime.ini
  projects/vehicles/controllers/highway_overtake/runtime.ini
  projects/vehicles/controllers/racing_wheel/runtime.ini
  projects/vehicles/controllers/ros_automobile/runtime.ini
  projects/vehicles/controllers/vehicle_driver/runtime.ini
Labels: bug

#2168 Fix macOS Python 2.7
  resources/languages/Makefile
Labels: bug, test suite

#2174 Fix Ctrl-click in documentation pages
  docs/js/viewer.js
Labels: bug

#2176 Fix importer_demo.sh on Linux
  projects/vehicles/importer_demo.sh
Labels: enhancement
