Repository cyberbotics/webots, pull requests merged in 2020-04, with the labels that each got.

#1511 using Ros::fixedNameString() for fixing String in RosDistanceSensor.cpp
  projects/default/controllers/ros/RosDistanceSensor.cpp
Labels: bug

#1510 Fix matlab tutorial 6
  docs/guide/tutorial-1-your-first-simulation-in-webots.md
  docs/guide/tutorial-4-more-about-controllers.md
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/guide/tutorial-7-your-first-proto.md
  docs/guide/using-matlab.md
  docs/reference/changelog-r2020.md
  projects/samples/tutorials/controllers/4_wheels_collision_avoidance/.gitignore
  projects/samples/tutorials/controllers/e-puck_avoid_collision/.gitignore
  projects/samples/tutorials/controllers/e-puck_go_forward/.gitignore
  projects/samples/tutorials/controllers/epuck_avoid_collision/.gitignore
  projects/samples/tutorials/controllers/epuck_avoid_collision/Makefile
  projects/samples/tutorials/controllers/epuck_avoid_collision/epuck_avoid_collision.c
  projects/samples/tutorials/controllers/epuck_avoid_collision/epuck_avoid_collision.m
  projects/samples/tutorials/controllers/epuck_go_forward/.gitignore
  projects/samples/tutorials/controllers/epuck_go_forward/Makefile
  projects/samples/tutorials/controllers/epuck_go_forward/epuck_go_forward.c
  projects/samples/tutorials/controllers/epuck_go_forward/epuck_go_forward.m
  projects/samples/tutorials/controllers/four_wheels_collision_avoidance/.gitignore
  projects/samples/tutorials/controllers/four_wheels_collision_avoidance/Makefile
  projects/samples/tutorials/controllers/four_wheels_collision_avoidance/four_wheels_collision_avoidance.c
  projects/samples/tutorials/controllers/four_wheels_collision_avoidance/four_wheels_collision_avoidance.m
  projects/samples/tutorials/protos/FourWheelsRobot.proto
  projects/samples/tutorials/worlds/.4_wheels_robot.wbproj
  projects/samples/tutorials/worlds/.appearance.wbproj
  projects/samples/tutorials/worlds/.collision_avoidance.wbproj
  projects/samples/tutorials/worlds/.compound_solid.wbproj
  projects/samples/tutorials/worlds/.my_first_simulation.wbproj
  projects/samples/tutorials/worlds/.obstacles.wbproj
  projects/samples/tutorials/worlds/4_wheels_robot.wbt
  projects/samples/tutorials/worlds/appearance.wbt
  projects/samples/tutorials/worlds/collision_avoidance.wbt
  projects/samples/tutorials/worlds/compound_solid.wbt
  projects/samples/tutorials/worlds/my_first_simulation.wbt
  projects/samples/tutorials/worlds/obstacles.wbt
Labels: bug

#1514 Fix OpenGL error with contact point optionnal rendering
  docs/reference/changelog-r2020.md
  src/wren/DynamicMesh.cpp
  src/wren/DynamicMesh.hpp
Labels: bug

#1517 Update changelog-r2020.md
  docs/reference/changelog-r2020.md
Labels: upgrade

#1518 Add lock()/unlock() call to WbConnector::updateIsLocked()
  src/webots/nodes/WbConnector.cpp
Labels: bug

#1522 Fix Add Node Dialog Crash
  docs/reference/changelog-r2020.md
  src/webots/scene_tree/WbAddNodeDialog.cpp
Labels: bug

#1525 Update System Requirements Doc
  docs/guide/system-requirements.md
Labels: bug

#1508 Enhancement develop console ansi codes
  .gitignore
  docs/guide/controller-programming.md
  docs/reference/changelog-r2020.md
  include/controller/c/webots/utils/ansi_codes.h
  include/controller/cpp/webots/utils/AnsiCodes.hpp
  lib/controller/matlab/ANSI_BLACK_BACKGROUND.m
  lib/controller/matlab/ANSI_BLACK_FOREGROUND.m
  lib/controller/matlab/ANSI_BLUE_BACKGROUND.m
  lib/controller/matlab/ANSI_BLUE_FOREGROUND.m
  lib/controller/matlab/ANSI_BOLD.m
  lib/controller/matlab/ANSI_CLEAR_SCREEN.m
  lib/controller/matlab/ANSI_CYAN_BACKGROUND.m
  lib/controller/matlab/ANSI_CYAN_FOREGROUND.m
  lib/controller/matlab/ANSI_GREEN_BACKGROUND.m
  lib/controller/matlab/ANSI_GREEN_FOREGROUND.m
  lib/controller/matlab/ANSI_MAGENTA_BACKGROUND.m
  lib/controller/matlab/ANSI_MAGENTA_FOREGROUND.m
  lib/controller/matlab/ANSI_RED_BACKGROUND.m
  lib/controller/matlab/ANSI_RED_FOREGROUND.m
  lib/controller/matlab/ANSI_RESET.m
  lib/controller/matlab/ANSI_UNDERLINE.m
  lib/controller/matlab/ANSI_WHITE_BACKGROUND.m
  lib/controller/matlab/ANSI_WHITE_FOREGROUND.m
  lib/controller/matlab/ANSI_YELLOW_BACKGROUND.m
  lib/controller/matlab/ANSI_YELLOW_FOREGROUND.m
  lib/controller/matlab/mgenerate.py
  projects/languages/cpp/controllers/slave/slave.cpp
  projects/languages/java/controllers/Slave/Slave.java
  projects/languages/matlab/controllers/matlab/matlab.m
  projects/languages/python/controllers/slave/slave.py
  projects/robots/clearpath/moose/controllers/moose_path_following/moose_path_following.c
  projects/samples/demos/controllers/moon/moon.c
  projects/samples/devices/controllers/battery/battery.c
  projects/samples/devices/controllers/gyro/gyro.c
  projects/samples/devices/controllers/motor/motor.c
  projects/samples/devices/controllers/position_sensor/position_sensor.c
  projects/samples/devices/controllers/radar/radar.c
  projects/samples/devices/controllers/receiver_noise/receiver_noise.c
  projects/samples/devices/controllers/spherical_camera/spherical_camera.c
  projects/samples/howto/controllers/console/.gitignore
  projects/samples/howto/controllers/console/Makefile
  projects/samples/howto/controllers/console/console.c
  projects/samples/howto/worlds/.console.wbproj
  projects/samples/howto/worlds/console.wbt
  resources/languages/java/Makefile
  resources/languages/java/controller.i
  resources/languages/python/controller.i
  src/webots/control/WbController.cpp
  src/webots/control/WbController.hpp
  src/webots/core/WbLog.cpp
  src/webots/core/WbLog.hpp
  src/webots/gui/WbConsole.cpp
  src/webots/gui/WbConsole.hpp
  src/webots/gui/WbStreamingServer.cpp
  src/webots/gui/WbStreamingServer.hpp
Labels: enhancement

#1533 Update Travis Mac Image
  .travis.yml
Labels: bug

#1539 Fix Various Issues with the OSM Importer
  projects/vehicles/importer_demo.sh
  resources/osm_importer/webots_objects/road.py
  resources/osm_importer/webots_objects/speed_limit.py
Labels: bug

#1528 Translate Supervisor Samples in Doc to other API
  docs/guide/supervisor-programming.md
Labels: enhancement

#1543 Fix Doc about Electric Motors
  docs/automobile/driver-library.md
Labels: enhancement

#1547 Doc: Fix typo in joint parameters
  docs/reference/jointparameters.md
Labels: bug

#1548 Set SoccerBall recognition colors
  projects/objects/balls/protos/SoccerBall.proto
Labels: enhancement

#1532 Renamed webots.exe to webots-bin.exe
  dependencies/Cyberbotics.Webots.Mingw64.Libraries.manifest
  dependencies/Makefile.windows
  docs/guide/starting-webots.md
  docs/reference/changelog-r2020.md
  src/packaging/copy_msys64_files.py
  src/packaging/ffmpeg_dependencies.sh
  src/packaging/files_msys64.txt
  src/packaging/webots_distro.c
  src/webots/Makefile
  src/webots/gui/manifest.xml
  src/webots/launcher/launcher.c
  src/webots/launcher/launcher.rc
  src/webots/launcher/webots-bin.exe.config
  src/webots/launcher/webots.bat
  src/webots/launcher/webots.lnk
  src/webots/launcher/webots_debug.bat
Labels: bug

#1512 Enhancement Variable Truck Size
  docs/reference/changelog-r2020.md
  projects/vehicles/protos/generic/Truck.proto
  projects/vehicles/protos/generic/TruckCab.proto
  projects/vehicles/protos/generic/TruckTank.proto
  projects/vehicles/protos/generic/TruckTrailer.proto
  projects/vehicles/protos/generic/TruckTrailerMesh.proto
  projects/vehicles/protos/generic/TruckTrailerSimple.proto
Labels: enhancement

#1535 enhancement-translate-controller-doc-samples
  docs/guide/controller-programming.md
  docs/guide/supervisor-programming.md
  docs/reference/changelog-r2020.md
  docs/reference/distancesensor.md
Labels: enhancement, good first issue

#1552 Replace Car 'maxWheelVelocity' field by a 'maxVelocity' field.
  docs/automobile/car.md
  docs/reference/changelog-r2020.md
  projects/robots/saeon/protos/Altino.proto
  projects/vehicles/protos/abstract/Car.proto
Labels: enhancement

#1554 Improved translation instructions
  docs/guide/translating-webots-to-your-own-language.md
  resources/translations/README.md
  resources/translations/readme.txt
Labels: enhancement

#1484 Add gyroscope to e-puck proto
  docs/guide/epuck.md
  docs/reference/changelog-r2020.md
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.c
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.css
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.html
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.js
  projects/robots/gctronic/e-puck/protos/E-puck.proto
Labels: bug

#1562 Fix Unwanted Warning with Passive Connectors
  src/webots/nodes/WbConnector.cpp
Labels: bug

#1560 Fix Windows Packaging
  src/webots/Makefile
Labels: bug

#1561 Fix Packaging
  src/packaging/files_core.txt
Labels: bug

#1567 Add libpjeg to tarball package
  src/packaging/webots_distro.c
Labels: enhancement

#1570 Hotfix mercedes-benz texture location.
  projects/vehicles/protos/mercedes_benz/textures/metal_grid_base_color.png
  projects/vehicles/protos/mercedes_benz/textures/metal_grid_normal.png
Labels: bug

#1557 hotfix-no-resize-handles-on-use-node
  docs/reference/changelog-r2020.md
  src/webots/app/WbSelection.cpp
Labels: bug, good first issue

#1573 Fixed 3D view restoration
  docs/reference/changelog-r2020.md
  src/webots/gui/WbSimulationView.cpp
Labels: bug

#1576 Fix docs typo
  docs/guide/the-user-interface.md
  docs/reference/mesh.md
  src/webots/gui/WbImportWizard.cpp
Labels: bug

#1578 Fixed startup from a CMD console
  src/webots/gui/main.cpp
Labels: bug

#1563 fix-crash-elevator-grid
  src/webots/nodes/WbElevationGrid.cpp
  src/webots/nodes/WbGeometry.cpp
  src/webots/vrml/WbSFInt.hpp
Labels: bug, good first issue

#1581 Simplify and fix ROS motor feedback.
  docs/reference/changelog-r2020.md
  projects/default/controllers/ros/RosMotorSensor.cpp
  projects/default/controllers/ros/RosMotorSensor.hpp
  projects/languages/ros/webots_ros/src/complete_test.cpp
Labels: bug

#1583 Update motor.md
  docs/reference/motor.md
Labels: bug

#1584 Fix mac Wireframe shortcut.
  src/webots/user_commands/WbActionManager.cpp
Labels: bug

#1586 Fix mac classic mode.
  Contents/Info.plist
  resources/webots_classic.qss
  resources/webots_dusk.qss
  resources/webots_night.qss
Labels: bug

#1585 Fixed Windows launchers
  src/webots/Makefile
  src/webots/launcher/launcher.c
Labels: enhancement

#1590 Improve generate_diff.py
  .travis.yml
  tests/sources/generate_diff.py
Labels: bug

#1571 Use safe temporary directory on Linux
  src/lib/Controller/api/system.c
  src/webots/launcher/webots-linux.sh
Labels: enhancement

#1592 Fix cppcheck warning
  src/webots/launcher/launcher.c
Labels: bug

#1594 Display more warnings when compiling launcher.c
  src/webots/Makefile
  src/webots/launcher/launcher.c
Labels: enhancement

#1593 Fix Clang Format and Cppcheck
  projects/appearances/protos/textures/metal_galvanized/metal_galvanized_base_color.jpg
  projects/appearances/protos/textures/metal_galvanized/metal_galvanized_metalness.jpg
  projects/appearances/protos/textures/metal_galvanized/metal_galvanized_normal.jpg
  projects/appearances/protos/textures/metal_galvanized/metal_galvanized_roughness.jpg
  projects/appearances/protos/textures/parquetry/light_strip_parquetry_base_color.jpg
  projects/appearances/protos/textures/parquetry/light_strip_parquetry_normal.jpg
  projects/appearances/protos/textures/parquetry/light_strip_parquetry_roughness.jpg
  projects/appearances/protos/textures/plastic/plastic_padded_base_color.jpg
  projects/appearances/protos/textures/plastic/plastic_padded_metalness.jpg
  projects/appearances/protos/textures/plastic/plastic_padded_normal.jpg
  projects/appearances/protos/textures/plastic/plastic_padded_occlusion.jpg
  projects/appearances/protos/textures/plastic/plastic_padded_roughness.jpg
  projects/appearances/protos/textures/plastic/plastic_rough_normal.jpg
  projects/appearances/protos/textures/plastic/plastic_rough_roughness.jpg
  projects/robots/boston_dynamics/spot/protos/textures/camera_2_lens_base_color.jpg
  projects/robots/boston_dynamics/spot/protos/textures/camera_big_lens_base_color.jpg
  projects/robots/boston_dynamics/spot/protos/textures/camera_lens_base_color.jpg
  projects/robots/festo/robotino3/protos/textures/connecteur_A_base_color.jpg
  projects/robots/festo/robotino3/protos/textures/connecteur_B_base_color.jpg
  projects/robots/festo/robotino3/protos/textures/ethernet_port_base_color.jpg
  projects/robots/festo/robotino3/protos/textures/ethernet_port_metalness.jpg
  projects/robots/festo/robotino3/protos/textures/ethernet_port_roughness.jpg
  projects/robots/festo/robotino3/protos/textures/usb_ethernet_port_base_color.jpg
  projects/robots/festo/robotino3/protos/textures/usb_ethernet_port_metalness.jpg
  projects/robots/festo/robotino3/protos/textures/usb_ethernet_port_roughness.jpg
  projects/robots/festo/robotino3/protos/textures/usb_port_base_color.jpg
  projects/robots/festo/robotino3/protos/textures/usb_port_metalness.jpg
  projects/robots/festo/robotino3/protos/textures/usb_port_roughness.jpg
  projects/robots/pal_robotics/tiago_base/protos/textures/metal_stainless_clean_base_color.jpg
  projects/robots/pal_robotics/tiago_base/protos/textures/metal_stainless_clean_roughness.jpg
  projects/robots/pal_robotics/tiago_extensions/protos/textures/acoustic_foam_base_color.jpg
  projects/robots/pal_robotics/tiago_extensions/protos/textures/acoustic_foam_metalness.jpg
  projects/robots/pal_robotics/tiago_extensions/protos/textures/acoustic_foam_normal.jpg
  projects/robots/pal_robotics/tiago_extensions/protos/textures/acoustic_foam_occlusion.jpg
  projects/robots/pal_robotics/tiago_extensions/protos/textures/acoustic_foam_roughness.jpg
  projects/robots/pal_robotics/tiago_extensions/protos/textures/plastic_tarp_45_base_color.jpg
  projects/robots/pal_robotics/tiago_extensions/protos/textures/plastic_tarp_45_normal.jpg
  projects/robots/pal_robotics/tiago_extensions/protos/textures/plastic_tarp_45_roughness.jpg
  projects/robots/pal_robotics/tiago_extensions/protos/textures/tiago_electronic_base_color.jpg
  projects/samples/environments/indoor/worlds/textures/rustic_veneer_wood_base_color.jpg
  projects/samples/environments/indoor/worlds/textures/rustic_veneer_wood_normal.jpg
  projects/samples/environments/indoor/worlds/textures/rustic_veneer_wood_roughness.jpg
  src/lib/Controller/api/system.c
  tests/sources/test_clang_format.py
Labels: bug

#1577 Add aperture to ToF sensor
  docs/guide/epuck.md
  projects/robots/gctronic/e-puck/protos/E-puck.proto
Labels: bug

#1597 Kill webots-bin.exe whenever webots.exe (resp. webotsw.exe) is killed
  src/webots/launcher/launcher.c
Labels: bug

#1607 fix icon path
  src/packaging/webots.desktop
Labels: bug
