Repository cyberbotics/webots, pull requests merged in 2020-05, with the labels that each got.

#1618 Improve the snap documentation
  docs/guide/installation-procedure.md
Labels: enhancement

#1616 fix dir to create tar and update qt download link
  src/install_scripts/qt_linux_installer.sh
Labels: enhancement

#1614 Fix streaming crash
  docs/reference/changelog-r2020.md
  src/webots/gui/WbStreamingServer.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
Labels: bug

#1626 Add Spot Movie to Docs
  docs/guide/spot.md
Labels: enhancement

#1629 Fixed resolution of Velodyne HDL-32E and HDL-64E.
  docs/reference/changelog-r2020.md
  docs/reference/lidar.md
  projects/devices/velodyne/protos/VelodyneHDL-32E.proto
  projects/devices/velodyne/protos/VelodyneHDL-64E.proto
Labels: bug

#1627 Fix Lidar Reset
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbLidar.cpp
Labels: bug

#1631 Fixed missing dependencies
  resources/web/wwi/Makefile
Labels: bug

#1633 Fix macOS Python3.8 compilation warnings.
  projects/default/libraries/vehicle/python/Makefile
  projects/robots/robotis/darwin-op/libraries/python/Makefile
Labels: bug

#1617 Update to Qt 5.14.2 on Linux
  dependencies/Makefile.linux
  docs/reference/changelog-r2020.md
  src/install_scripts/qt_linux_installer.sh
  src/packaging/files_core.txt
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbRobotWindow.cpp
Labels: enhancement

#1635 Fix Ros Camera Recognition Docs
  docs/reference/camera.md
Labels: bug

#1636 Code cleanup
  src/webots/nodes/utils/WbUrl.cpp
Labels: enhancement

#1640 Improved error messages for remote control library
  src/lib/Controller/api/remote_control.c
Labels: enhancement

#1639 Fixed Webots crash
  docs/reference/changelog-r2020.md
  projects/languages/cpp/controllers/driver/driver.cpp
  src/lib/Controller/api/supervisor.c
  src/webots/maths/WbVector2.hpp
  src/webots/maths/WbVector3.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/scene_tree/WbVector2Editor.cpp
  src/webots/scene_tree/WbVector3Editor.cpp
  src/webots/vrml/WbSFVector2.cpp
  src/webots/vrml/WbSFVector3.cpp
Labels: bug

#1644 Fix macOS cleanse target
  Makefile
  dependencies/Makefile.mac
  projects/robots/robotis/darwin-op/libraries/Makefile.mac
Labels: bug

#1646 Fix tests
  tests/physics/controllers/floating_point_precision/floating_point_precision.c
  tests/physics/plugins/physics/ode_dif_exporter/ode_dif_exporter.c
Labels: bug

#1641 Fix ROS Camera Recognition
  projects/default/controllers/ros/Makefile
  projects/default/controllers/ros/include/RecognitionObject.h
  projects/languages/ros/webots_ros/src/complete_test.cpp
Labels: bug

#1649 Fixed buffer overflow reported by gcc 10 on Windows
  projects/samples/contests/ratslife/controllers/contest_manager/round_manager.c
Labels: bug

#1651 Fixed Windows packaging
  src/packaging/files_msys64.txt
Labels: bug

#1653 Add a 'Physics Plugins' Console filter.
  src/webots/core/WbLog.cpp
  src/webots/core/WbLog.hpp
  src/webots/gui/WbConsole.cpp
  src/webots/plugins/WbPhysicsPlugin.cpp
Labels: enhancement

#1420 Generic simulation server
  docs/guide/web-simulation.md
  projects/humans/c3d/worlds/c3d_viewer.wbt
  resources/web/server/README.md
  resources/web/server/async_process.py
  resources/web/server/config/session/default.json
  resources/web/server/config/session/local.json
  resources/web/server/config/simulation/default.json
  resources/web/server/config/simulation/local.json
  resources/web/server/session_server.py
  resources/web/server/simulation_server.py
  resources/web/wwi/server.js
  resources/web/wwi/webots.js
  resources/web/wwi/wwi.css
  src/webots/gui/WbStreamingServer.cpp
Labels: enhancement

#1658 Update worldinfo.md
  docs/reference/worldinfo.md
Labels: bug

#1661 Fix packaging
  src/packaging/files_core.txt
Labels: bug

#1663 Fix cppcheck 2.0 errors
  projects/default/controllers/ros/RosSupervisor.cpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/DeviceManager.hpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/Wrapper.hpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/DeviceManager.hpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/Wrapper.hpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/test.c
  projects/robots/mobsya/thymio/controllers/thymio2_aseba/Thymio2Model.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/DeviceManager.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/FireBird6InputPacket.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Wrapper.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/DeviceManager.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Wrapper.hpp
  projects/robots/robotis/darwin-op/remote_control/main.cpp
  projects/samples/curriculum/controllers/advanced_particle_swarm_optimization/pso.c
  projects/samples/curriculum/controllers/advanced_particle_swarm_optimization_supervisor/advanced_particle_swarm_optimization_supervisor.c
  projects/samples/curriculum/lib/backprop.c
  resources/projects/libraries/qt_utils/motion_editor/Motion.cpp
  resources/projects/libraries/qt_utils/motion_editor/MotionGlobalSettings.hpp
  resources/projects/libraries/qt_utils/motion_editor/MotionPlayer.cpp
  src/lib/Controller/api/motion.c
  src/lib/Controller/api/robot.c
  src/lib/Controller/api/scheduler.c
  src/webots/core/WbTranslator.hpp
  src/webots/engine/WbAnimationRecorder.cpp
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/utils/WbDictionary.hpp
  src/webots/util/WbPerformanceLog.hpp
  src/webots/wren/WbWrenLabelOverlay.hpp
  src/webots/wren/WbWrenRenderingContext.cpp
Labels: enhancement

#1666 Merge master into develop
  projects/default/controllers/ros/RosSupervisor.cpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/DeviceManager.hpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/Wrapper.hpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/DeviceManager.hpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/Wrapper.hpp
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_wifi/test.c
  projects/robots/mobsya/thymio/controllers/thymio2_aseba/Thymio2Model.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/DeviceManager.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/FireBird6InputPacket.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Wrapper.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/DeviceManager.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Wrapper.hpp
  projects/robots/robotis/darwin-op/remote_control/main.cpp
  projects/samples/curriculum/controllers/advanced_particle_swarm_optimization/pso.c
  projects/samples/curriculum/controllers/advanced_particle_swarm_optimization_supervisor/advanced_particle_swarm_optimization_supervisor.c
  projects/samples/curriculum/lib/backprop.c
  resources/projects/libraries/qt_utils/motion_editor/Motion.cpp
  resources/projects/libraries/qt_utils/motion_editor/MotionGlobalSettings.hpp
  resources/projects/libraries/qt_utils/motion_editor/MotionPlayer.cpp
  src/lib/Controller/api/motion.c
  src/lib/Controller/api/robot.c
  src/lib/Controller/api/scheduler.c
  src/webots/core/WbTranslator.hpp
  src/webots/engine/WbAnimationRecorder.cpp
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/utils/WbDictionary.hpp
  src/webots/util/WbPerformanceLog.hpp
  src/webots/wren/WbWrenLabelOverlay.hpp
  src/webots/wren/WbWrenRenderingContext.cpp
Labels: enhancement

#1667 Fixed invalid MATLAB controller function prototypes
  docs/guide/controller-programming.md
  docs/reference/accelerometer.md
  docs/reference/compass.md
  docs/reference/gps.md
  docs/reference/gyro.md
  docs/reference/inertialunit.md
  docs/reference/receiver.md
  docs/reference/supervisor.md
  docs/reference/touchsensor.md
Labels: enhancement

#1544 Fix nested DEF/USE nodes
  docs/reference/changelog-r2020.md
  src/webots/vrml/WbNode.cpp
  tests/api/controllers/modify_nested_def_node/.gitignore
  tests/api/controllers/modify_nested_def_node/Makefile
  tests/api/controllers/modify_nested_def_node/modify_nested_def_node.c
  tests/api/worlds/nested_def_nodes.wbt
Labels: bug

#1672 Added bullets
  docs/guide/using-your-ide.md
Labels: documentation

#1680 Fix Debugging Doc Pathes
  docs/reference/troubleshooting.md
Labels: bug

#1679 Fix MacOS Packaging
  src/packaging/files_core.txt
  src/packaging/webots_distro.c
Labels: bug

#1670 Feature Discord to Doc
  .github/workflows/discord_updater.yml
  docs/README.md
  docs/discord/development.md
  docs/discord/documentation.md
  docs/discord/images/discord.jpg
  docs/discord/index.md
  docs/discord/menu.md
  docs/discord/news.md
  docs/discord/technical-questions.md
  docs/discord/update.py
  docs/generate_thumbnails.py
  docs/js/viewer.js
  docs/reference/changelog-r2020.md
  docs/tests/books.py
  docs/tests/test_hyperlinks.py
  docs/tests/test_images.py
  docs/tests/test_lists.py
  docs/tests/test_md_files.py
  docs/tests/test_menus.py
  docs/tests/test_paragraphs.py
  docs/tests/test_references.py
  docs/tests/test_titles.py
Labels: enhancement

#1682 Giving a more structured look to the documentation
  docs/README.md
Labels: documentation, enhancement

#1684 Fix Python2.7 Test Suite
  docs/discord/update.py
  docs/tests/test_hyperlinks.py
  docs/tests/test_images.py
  docs/tests/test_lists.py
  docs/tests/test_md_files.py
  docs/tests/test_menus.py
  docs/tests/test_paragraphs.py
  docs/tests/test_references.py
  docs/tests/test_titles.py
  src/packaging/copy_msys64_files.py
  tests/sources/test_pep8.py
Labels: bug

#1685 Minor changes to the documentation
  docs/guide/debugging-c-cpp-controllers.md
  docs/guide/using-your-ide.md
Labels: documentation, enhancement

#1689 Fix appveyor pacman update
  .appveyor-build-tag.yml
  .appveyor-build.yml
  .appveyor-test-sources-scheduled.yml
Labels: bug

#1697 Fix Github Action Time
  .github/workflows/discord_updater.yml
Labels: enhancement

#1692 Update controller-start-up.md:- Corrects a few grammatical errors
  docs/guide/controller-start-up.md
Labels: documentation

#1698 Improve controller termination documentation
  docs/guide/controller-programming.md
Labels: documentation

#1699 Revert "Update controller-start-up.md:- Corrects a few grammatical errors"
  docs/guide/controller-start-up.md
Labels: documentation, enhancement

#1352 MJPEG streaming
  docs/guide/starting-webots.md
  docs/guide/web-streaming.md
  resources/web/streaming_viewer/index.html
  resources/web/streaming_viewer/setup_viewer.js
  resources/web/wwi/Makefile
  resources/web/wwi/context_menu.js
  resources/web/wwi/default_url.js
  resources/web/wwi/dialog_window.js
  resources/web/wwi/mouse_events.js
  resources/web/wwi/multimedia_client.js
  resources/web/wwi/stream.js
  resources/web/wwi/toolbar.js
  resources/web/wwi/video.js
  resources/web/wwi/webots.js
  resources/web/wwi/wwi.css
  resources/web/wwi/x3d_scene.js
  src/webots/Makefile
  src/webots/app/WbSelection.cpp
  src/webots/app/WbSelection.hpp
  src/webots/engine/WbMultimediaStreamer.cpp
  src/webots/engine/WbMultimediaStreamer.hpp
  src/webots/gui/WbDragViewpointEvent.cpp
  src/webots/gui/WbDragViewpointEvent.hpp
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbGuiApplication.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/gui/WbMultimediaStreamingLimiter.cpp
  src/webots/gui/WbMultimediaStreamingLimiter.hpp
  src/webots/gui/WbMultimediaStreamingServer.cpp
  src/webots/gui/WbMultimediaStreamingServer.hpp
  src/webots/gui/WbSingleTaskApplication.cpp
  src/webots/gui/WbStreamingServer.cpp
  src/webots/gui/WbStreamingServer.hpp
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbView3D.hpp
  src/webots/gui/WbWrenWindow.cpp
  src/webots/gui/WbWrenWindow.hpp
  src/webots/gui/WbX3dStreamingServer.cpp
  src/webots/gui/WbX3dStreamingServer.hpp
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbBaseNode.hpp
  src/webots/nodes/WbMatter.cpp
  src/webots/nodes/WbMatter.hpp
Labels: enhancement

#1703 Add new mjpeg streaming feature in the change log
  docs/reference/changelog-r2020.md
Labels: documentation

#1707 Fix Mac Compilation
  src/webots/gui/WbMultimediaStreamingLimiter.cpp
  src/webots/gui/WbMultimediaStreamingLimiter.hpp
Labels: bug

#1709 Fix qt5.15 deprecation warnings
  docs/reference/changelog-r2020.md
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/Automaton.cpp
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/AutomatonWidget.cpp
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/Model.cpp
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/e-puck/EPuckFacade.cpp
  resources/projects/libraries/qt_utils/gui/MainWindow.cpp
  resources/projects/libraries/qt_utils/motion_editor/Motion.cpp
  resources/projects/libraries/qt_utils/motion_editor/Pose.cpp
  src/webots/control/WbControlledWorld.cpp
  src/webots/control/WbController.cpp
  src/webots/control/WbController.hpp
  src/webots/control/WbLanguageTools.cpp
  src/webots/control/WbLanguageTools.hpp
  src/webots/core/WbFileUtil.cpp
  src/webots/core/WbTemplateEngine.cpp
  src/webots/core/WbWindowsRegistry.cpp
  src/webots/editor/WbBuildEditor.cpp
  src/webots/editor/WbBuildEditor.hpp
  src/webots/editor/WbTextFind.cpp
  src/webots/gui/WbStreamingServer.cpp
  src/webots/gui/WbVideoRecorder.cpp
  src/webots/gui/WbView3D.cpp
  src/webots/nodes/utils/WbDictionary.cpp
  src/webots/nodes/utils/WbDictionary.hpp
  src/webots/scene_tree/WbFieldEditor.hpp
  src/webots/scene_tree/WbSceneTreeModel.cpp
  src/webots/sound/WbWaveFile.cpp
Labels: upgrade
