Repository cyberbotics/webots, pull requests merged in 2020-12, with the labels that each got.

#2487 Fixed ContactProperties.softCFM limits
  docs/reference/contactproperties.md
  src/webots/nodes/WbContactProperties.cpp
Labels: crash

#2490 Fixed InertialUnit
  docs/reference/changelog-r2021.md
  resources/nodes/InertialUnit.wrl
Labels: cleanup

#2488 Fixed compilation warning of webots_distro.c on mac
  scripts/packaging/Makefile
Labels: cleanup

#2484 Fix npm uninstall
  resources/web/wwi/Makefile
Labels: bug, test suite

#2482 Fix updating device list after importing a joint descendant node
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbBasicJoint.cpp
  src/webots/nodes/WbGroup.cpp
  src/webots/nodes/WbGroup.hpp
  src/webots/nodes/WbSlot.cpp
Labels: bug, test suite

#2226 Convert proto files to multi-file protos
  scripts/proto_splitter/proto2multi.py
Labels: enhancement

#2485 Fix artifacts upload issues
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
Labels: cleanup, test suite

#2499 Fixed world update test on master branch (robotino3.wbt)
  projects/robots/festo/robotino3/worlds/robotino3.wbt
Labels: cleanup, test world update

#2498 Fixed world updatest on develop branch (robotino3.wbt)
  projects/robots/festo/robotino3/worlds/robotino3.wbt
Labels: cleanup, test world update

#2500 extends the exported fields for the stream viewer
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbLight.cpp
  src/webots/nodes/WbViewpoint.cpp
Labels: enhancement, test suite

#2502 Fix Java Makefiles on master branch
  projects/default/libraries/vehicle/java/Makefile
  resources/languages/java/Makefile
Labels: bug, test suite

#2505 Call the physics plugin callback `webots_physics_collide` on Group node
  docs/reference/changelog-r2021.md
  src/webots/engine/WbSimulationCluster.cpp
Labels: test suite

#2514 Fix propagating import information to joint with slot parent
  src/webots/nodes/WbBasicJoint.cpp
Labels: bug, test suite

#2510 Improved device getters in the Python API
  docs/guide/controller-programming.md
  docs/guide/cpp-java-python.md
  docs/guide/tutorial-1-your-first-simulation-in-webots.md
  docs/guide/tutorial-4-more-about-controllers.md
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/reference/changelog-r2021.md
  docs/reference/robot.md
  include/controller/cpp/webots/Robot.hpp
  projects/default/controllers/sumo_supervisor/SumoSupervisor.py
  projects/languages/python/controllers/driver/driver.py
  projects/languages/python/controllers/slave/slave.py
  projects/objects/factory/valves/controllers/valve_turner/valve_turner.py
  projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
  projects/robots/kinematics/tinkerbots/controllers/two_wheels_vehicle/two_wheels_vehicle.py
  projects/robots/kinematics/tinkerbots/controllers/vision_car/vision_car.py
  projects/robots/saeon/controllers/vehicle_driver_altino/vehicle_driver_altino.py
  projects/robots/softbank/nao/controllers/nao_demo_python/nao_demo_python.py
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/scripts/joint_state_publisher.py
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/scripts/trajectory_follower.py
  projects/samples/environments/factory/controllers/led_controller/led_controller.py
  projects/samples/environments/factory/controllers/screw_controller/screw_controller.py
  projects/samples/robotbenchmark/highway_driving/controllers/highway_driving/highway_driving.py
  projects/samples/robotbenchmark/highway_driving/controllers/sensors_visualization/sensors_visualization.py
  projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/marathon.py
  projects/samples/robotbenchmark/humanoid_sprint/controllers/sprinter/sprinter.py
  projects/samples/robotbenchmark/inverted_pendulum/controllers/inverted_pendulum/inverted_pendulum.py
  projects/samples/robotbenchmark/inverted_pendulum/controllers/inverted_pendulum_benchmark/inverted_pendulum_benchmark.py
  projects/samples/robotbenchmark/maze_runner/controllers/move_in_maze/move_in_maze.py
  projects/samples/robotbenchmark/obstacle_avoidance/controllers/avoid_obstacles/avoid_obstacles.py
  projects/samples/robotbenchmark/pick_and_place/controllers/move_conveyor_belt/move_conveyor_belt.py
  projects/samples/robotbenchmark/pick_and_place/controllers/pick_and_place/pick_and_place.py
  projects/samples/robotbenchmark/pit_escape/controllers/pit_escape/pit_escape.py
  projects/samples/robotbenchmark/pit_escape/controllers/pit_escape_advanced/pit_escape_advanced.py
  projects/samples/robotbenchmark/robot_programming/controllers/move/move.py
  projects/samples/robotbenchmark/square_path/controllers/square_path/square_path.py
  projects/samples/robotbenchmark/square_path/controllers/square_path_advanced/square_path_advanced.py
  projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking/visual_tracking.py
  projects/samples/robotbenchmark/wall_following/controllers/wall_following/wall_following.py
  projects/samples/robotbenchmark/wall_following/controllers/wall_following_advanced/wall_following_advanced.py
  projects/vehicles/controllers/highway_overtake/highway_overtake.py
  src/controller/cpp/Brake.cpp
  src/controller/cpp/Motor.cpp
  src/controller/cpp/PositionSensor.cpp
  src/controller/cpp/Robot.cpp
  src/controller/python/controller.i
Labels: enhancement, test suite

#2515 Moved R2020b-rev2 changelog into R2021a
  docs/reference/changelog-r2020.md
  docs/reference/changelog-r2021.md
Labels: documentation

#2524 Added warning about performance of getImageArray
  docs/reference/camera.md
Labels: documentation

#2508 Fix device list update in C++ API after device import
  docs/reference/supervisor.md
  src/controller/cpp/Robot.cpp
  src/controller/java/controller.i
  src/controller/python/controller.i
  tests/Makefile
  tests/lib/TestUtils.hpp
  tests/other_api/.gitignore
  tests/other_api/Makefile
  tests/other_api/controllers/.gitignore
  tests/other_api/controllers/Makefile
  tests/other_api/controllers/cpp_import_device/.gitignore
  tests/other_api/controllers/cpp_import_device/Makefile
  tests/other_api/controllers/cpp_import_device/cpp_import_device.cpp
  tests/other_api/protos/.gitignore
  tests/other_api/worlds/.cpp_import_device.wbproj
  tests/other_api/worlds/cpp_import_device.wbt
  tests/test_suite.py
Labels: bug, test suite

#2526 Clear console on make clean
  src/webots/editor/WbBuildEditor.cpp
Labels: regression, test distribution

#2527 Create Windows nightly builds from GitHub Action
  .appveyor-build-tag.yml
  .appveyor-build.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  .travis.yml
Labels: enhancement, test suite

#2529 Fix lens flare shader compilation failure
  resources/wren/shaders/lens_flare.frag
  resources/wren/shaders/lens_flare.vert
Labels: bug

#2525 Fixed compilation of OpenCV sample controller on Windows
  projects/samples/howto/controllers/vision/Makefile
Labels: bug

#2509 Make Lidar return INF if depth is out-of-range
  docs/reference/changelog-r2021.md
  docs/reference/lidar.md
  docs/reference/rangefinder.md
  projects/samples/devices/controllers/hokuyo/hokuyo.c
  projects/samples/devices/worlds/hokuyo.wbt
  resources/wren/shaders/encode_depth.frag
  resources/wren/shaders/merge_spherical.frag
  resources/wren/shaders/range_noise.frag
  src/webots/wren/WbWrenCamera.cpp
  src/webots/wren/WbWrenRangeNoise.cpp
  src/webots/wren/WbWrenRangeNoise.hpp
  src/webots/wren/WbWrenShaders.cpp
  tests/api/controllers/lidar_point_cloud/lidar_point_cloud.c
  tests/api/controllers/lidar_rotating/lidar_rotating.c
  tests/api/controllers/range_finder_checker/range_finder_checker.c
  tests/lib/ts_assertion.h
Labels: bug, test suite

#2534 Fixed the WREN demos to run on Windows as well
  src/wren/demo/Makefile
  src/wren/demo/phong.cpp
Labels: enhancement

#2535 Improve highway grass shape
  projects/samples/robotbenchmark/highway_driving/worlds/highway_driving.wbt
  projects/vehicles/worlds/highway_overtake.wbt
Labels: enhancement

#2537 Fix pointer in Matlab API
  lib/controller/matlab/wb_supervisor_node_get_velocity.m
  src/controller/matlab/mgenerate.py
Labels: bug, enhancement

#2541 Fix Visual C++ link
  src/controller/c/Controller.def
Labels: bug

#2544 Fix sick example after range finder behavior change (infinity return value)
  projects/samples/devices/controllers/sick/sick.c
Labels: bug

#2538 Fix Windows nightly builds
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
Labels: bug, test distribution

#2546 Fix Java controllers
  src/controller/java/controller.i
Labels: regression

#2547 Fix controller external path for snap packages
  docs/guide/installation-procedure.md
Labels: documentation

#2551 Reduce timestep in the `ure` world to avoid warnings
  projects/robots/universal_robots/worlds/ure.wbt
Labels: bug

#2542 Fix `position_sensor.getMotor()`
  src/controller/python/controller.i
Labels: bug, regression, test suite

#2554 Fixed detection of Visual Studio on Windows
  resources/Makefile.include
Labels: bug

#2560 Fix Python2 support
  src/controller/python/controller.i
Labels: bug, regression

#2558 Fix nightly builds on master
  scripts/packaging/publish_release.py
Labels: bug

#2559 Attempt to fix the nightly builds (develop branch)
  scripts/packaging/publish_release.py
Labels: bug

#2561 Fix ROS speaker service mismatch
  projects/default/controllers/ros/RosSpeaker.cpp
Labels: bug

#2565 Include resources/web/wwi GIF images in package
  scripts/packaging/files_core.txt
Labels: bug

#2562 Minor fixes to the distributed simulations
  projects/guided_tour.txt
  projects/robots/clearpath/moose/controllers/moose_path_following/moose_path_following.c
  projects/samples/devices/worlds/.hokuyo.wbproj
  projects/samples/devices/worlds/.sick.wbproj
  projects/vehicles/worlds/.city.wbproj
Labels: enhancement

#2566 Fix Webots freeze on NaN value in hokuyo.wbt
  projects/samples/devices/controllers/hokuyo/hokuyo.c
Labels: crash, regression

#2567 Fixed object descriptions
  docs/guide/generate_objects_doc.py
  docs/guide/images/objects/containers/PlasticFruitBox/model.thumbnail.png
  docs/guide/object-factory.md
  projects/objects/factory/manhole/protos/SquareManhole.proto
  projects/objects/factory/tools/protos/CapScrew.proto
Labels: documentation

#2568 Set release date
  docs/reference/changelog-r2021.md
Labels: documentation

#2530 R2021a blog post
  docs/blog/Webots-2021-a-release.md
  docs/blog/images/image_segmentation.gif
  docs/blog/images/metal_storage_box.thumbnail.png
  docs/blog/images/plastic_fruit_box.thumbnail.png
  docs/blog/menu.md
  docs/tests/test_titles.py
Labels: documentation

#2572 Update template.py
  resources/templates/controllers/template.py
Labels: documentation

#2575 Fixes movie creation on Windows
  scripts/install/msys64_installer.sh
Labels: bug

#2577 Fix new cppcheck warnings
  projects/samples/howto/controllers/ziegler_nichols/ziegler_nichols.c
  src/webots/scene_tree/WbNodeEditor.cpp
Labels: enhancement

#2576 Reinforce mjpeg dependency test
  scripts/packaging/ffmpeg_dependencies.sh
Labels: enhancement

#2578 Increase Webots version to R2021a rev1
  Contents/Info.plist
  docs/js/showdown-extensions.js
  resources/version.txt
  scripts/packaging/webots_version.txt
  src/webots/core/WbApplicationInfo.cpp
Labels: test suite

#2582 Fix Windows nightly builds
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
Labels: bug

#2583 Automatic detection of Python path in Windows CI
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
Labels: enhancement, test distribution

#2587 Fixed overwriting of LD_LIBRARY_PATH
  scripts/install/bashrc.linux
Labels: bug

#2589 Fix Display external window update
  docs/reference/changelog-r2021.md
  src/webots/gui/WbRenderingDeviceWindow.cpp
  src/webots/gui/WbRenderingDeviceWindow.hpp
  src/webots/nodes/WbAbstractCamera.cpp
  src/webots/nodes/WbAbstractCamera.hpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbCamera.hpp
  src/webots/nodes/WbDisplay.cpp
  src/webots/nodes/WbDisplay.hpp
Labels: bug, test suite

#2590 Merge master into develop
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  docs/reference/changelog-r2021.md
  scripts/install/bashrc.linux
  src/webots/gui/WbRenderingDeviceWindow.cpp
  src/webots/gui/WbRenderingDeviceWindow.hpp
  src/webots/nodes/WbAbstractCamera.cpp
  src/webots/nodes/WbAbstractCamera.hpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbCamera.hpp
  src/webots/nodes/WbDisplay.cpp
  src/webots/nodes/WbDisplay.hpp
Labels: test suite

#2593 removal of the forced reset for solids with ballJoint parents that causes incorrect reset
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbSolid.cpp
Labels: bug, test suite

#2597 Remode deprecated run mode from instructions
  docs/guide/starting-webots.md
  src/webots/gui/WbSingleTaskApplication.cpp
Labels: enhancement

#2599 Regenerate translations files
  resources/translations/wb_de.ts
  resources/translations/wb_es.ts
  resources/translations/wb_fr.ts
  resources/translations/wb_generic.ts
  resources/translations/wb_it.ts
  resources/translations/wb_ja_JP.ts
  resources/translations/wb_zh_CN.ts
Labels: enhancement

#2598 Add CLASSPATH explanation for the automobile library
  docs/automobile/cpp-java-and-python-wrappers-of-the-automobile-libraries.md
Labels: documentation

#2609 Fixes unit for gyro in robot window
  resources/projects/plugins/robot_windows/generic/generic.js
Labels: bug

#2610 use closest contact for ray collision
  docs/reference/changelog-r2021.md
  src/webots/engine/WbSimulationCluster.cpp
Labels: bug
