Repository cyberbotics/webots, pull requests merged in 2020-03, with the labels that each got.

#1423 Fix/Improve UR robots ROS support
  docs/reference/changelog-r2020.md
  projects/robots/universal_robots/controllers/universal_robots_ros/joint_state_publisher.py
  projects/robots/universal_robots/controllers/universal_robots_ros/trajectory_follower.py
  projects/robots/universal_robots/controllers/universal_robots_ros/universal_robots_ros.py
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/README.md
Labels: bug, enhancement

#1425 Fixed status of naoqisim
  docs/reference/changelog-r2018.md
Labels: bug

#1429 Fix Misc Python Issues
  projects/default/controllers/sumo_supervisor/SumoSupervisor.py
  projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking/visual_tracking.py
  resources/web/server/kill_old_webots_instances.py
  resources/web/server/session_server.py
  resources/web/server/simulation_server.py
  src/packaging/generate_projects_files.py
  src/packaging/publish_release.py
Labels: bug, enhancement

#1426 Cleanup ROS libraries to avoid polluting controller path.
  docs/reference/changelog-r2020.md
  projects/default/Makefile
  projects/default/controllers/ros/Makefile
  projects/default/controllers/ros/lib/Makefile
  projects/default/controllers/ros/lib/ros/.gitignore
  projects/default/controllers/ros/runtime.ini
  projects/vehicles/controllers/ros_automobile/Makefile
  projects/vehicles/controllers/ros_automobile/runtime.ini
Labels: bug, enhancement

#1435 Attempt to fix travis nightly builds on Linux and macOS
  src/packaging/exist_in_projects_linux.txt
  src/packaging/exist_in_projects_mac.txt
Labels: bug

#1436 Merge master into develop
  src/packaging/exist_in_projects_linux.txt
  src/packaging/exist_in_projects_mac.txt
Labels: bug

#1438 Fixed English
  docs/reference/contactproperties.md
Labels: bug

#1442 Fixed compilation on Windows
  src/webots/sound/WbSoundEngine.cpp
Labels: bug

#1445 Fixed supervisor crash
  docs/reference/robot.md
  src/webots/nodes/WbRobot.cpp
Labels: bug

#1444 Fixed MATLAB instructions for extern controllers and launcher test
  docs/guide/running-extern-robot-controllers.md
  lib/controller/matlab/launcher.m
Labels: bug

#1447 Update motor.md
  docs/reference/motor.md
Labels: bug

#1448 Fix Simulation Reset Timming
  src/webots/control/WbControlledWorld.cpp
  src/webots/control/WbControlledWorld.hpp
  src/webots/control/WbController.cpp
  src/webots/control/WbController.hpp
  tests/api/worlds/supervisor_reset_simulation.wbt
Labels: bug

#1449 Hotfix Missing Changelog Entry
  docs/reference/changelog-r2020.md
Labels: enhancement

#1440 Fix runtime.ini path section header name
  docs/guide/controller-programming.md
  projects/languages/ros/controllers/ros_python/runtime.ini
  projects/robots/saeon/controllers/vehicle_driver_altino/runtime.ini
  projects/robots/universal_robots/controllers/universal_robots_ros/runtime.ini
  projects/samples/robotbenchmark/highway_driving/controllers/highway_driving/runtime.ini
  projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/runtime.ini
  projects/samples/robotbenchmark/inverted_pendulum/controllers/inverted_pendulum/runtime.ini
  src/webots/control/WbController.cpp
  src/webots/core/WbIniParser.cpp
  tests/api/controllers/runtime_config_file/runtime.ini
Labels: bug, enhancement

#1450 Add condition to protect IndexedLineSet when no coord
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbIndexedLineSet.cpp
Labels: bug

#1451 Improve the Using Numerical Optimization Methods Documentation
  docs/guide/using-numerical-optimization-methods.md
Labels: enhancement

#1452 Improve wb_supervisor_node_get_velocity doc
  docs/reference/supervisor.md
Labels: enhancement

#1453 Add Video to Tiago Doc
  docs/guide/tiagopp.md
Labels: enhancement

#1455 Fix motorized ball joint revert
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbBallJoint.hpp
  src/webots/nodes/WbBasicJoint.hpp
Labels: bug

#1456 Enhancement display triangles geometry node
  docs/reference/changelog-r2020.md
  include/wren/static_mesh.h
  src/webots/nodes/WbGeometry.cpp
  src/webots/nodes/WbGeometry.hpp
  src/webots/scene_tree/WbNodeEditor.cpp
  src/webots/scene_tree/WbNodeEditor.hpp
  src/wren/StaticMesh.cpp
Labels: enhancement, good first issue

#1459 Fix Supervisor set Orientation Normalization
  docs/reference/changelog-r2020.md
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
Labels: bug, enhancement

#1464 Fix R2020b Changelog
  docs/reference/changelog-r2020.md
Labels: enhancement

#1462 Fix MATLAB launcher
  docs/guide/using-matlab.md
  docs/reference/changelog-r2020.md
  lib/controller/matlab/launcher.m
Labels: bug

#1465 Add Missing Changelog Entry
  docs/reference/changelog-r2020.md
Labels: enhancement

#1458 Add rotating camera
  scripts/rotating_camera/controllers/rotating_camera/Makefile
  scripts/rotating_camera/controllers/rotating_camera/_gitignore
  scripts/rotating_camera/controllers/rotating_camera/rotating_camera.c
  scripts/rotating_camera/worlds/.rotating_camera.wbproj
  scripts/rotating_camera/worlds/rotating_camera.wbt
Labels: enhancement

#1468 Improve youbot
  docs/guide/youbot.md
  docs/reference/changelog-r2020.md
  projects/robots/kuka/youbot/protos/Youbot.proto
Labels: enhancement

#1433 Improve tutorial documentation - adding icons - typos
  docs/guide/the-scene-tree.md
  docs/guide/tutorial-1-your-first-simulation-in-webots.md
  docs/guide/tutorial-2-modification-of-the-environment.md
Labels: enhancement

#1457 Add break room world
  docs/guide/images/samples/break_room_a.png
  docs/guide/images/samples/break_room_b.png
  docs/guide/images/samples/break_room_c.png
  docs/guide/images/samples/break_room_d.png
  docs/guide/samples-environments.md
  docs/reference/changelog-r2020.md
  projects/samples/environments/indoor/worlds/.break_room.wbproj
  projects/samples/environments/indoor/worlds/break_room.wbt
  projects/samples/environments/indoor/worlds/textures/light_strip_parquetry_base_color.jpg
  projects/samples/environments/indoor/worlds/textures/light_strip_parquetry_normal.jpg
  projects/samples/environments/indoor/worlds/textures/light_strip_parquetry_roughness.jpg
  projects/samples/environments/indoor/worlds/textures/rustic_veneer_wood_base_color.jpg
  projects/samples/environments/indoor/worlds/textures/rustic_veneer_wood_normal.jpg
  projects/samples/environments/indoor/worlds/textures/rustic_veneer_wood_roughness.jpg
Labels: enhancement

#1469 Fixes Robot documentation
  docs/reference/robot.md
  docs/reference/supervisor.md
Labels: enhancement

#1471 Fixed Test Suite Crash.
  src/webots/nodes/WbGeometry.cpp
Labels: bug

#1476 Fix Test Failure rosdep Missing
  .travis.yml
Labels: bug

#1482 fix python2.7 should be optional to compile webots
  projects/robots/robotis/darwin-op/libraries/Makefile
Labels: bug

#1489 Fix AppVeyor Tests
  tests/sources/generate_diff.py
Labels: bug

#1490 Update Travis OSX Image
  .travis.yml
Labels: enhancement

#1491 Improve Rotation Edition from GUI
  docs/reference/changelog-r2020.md
  src/webots/scene_tree/WbFieldDoubleSpinBox.cpp
  src/webots/scene_tree/WbFieldDoubleSpinBox.hpp
  src/webots/scene_tree/WbRotationEditor.cpp
  src/webots/scene_tree/WbRotationEditor.hpp
Labels: enhancement

#1495 Improve supervisor-programming doc
  docs/guide/supervisor-programming.md
Labels: enhancement

#1494 Update Mesh Node Supported Formats
  docs/reference/mesh.md
  resources/nodes/Mesh.wrl
  src/webots/scene_tree/WbExtendedStringEditor.cpp
Labels: enhancement

#1463 Feature 3d Model Import
  .travis.yml
  dependencies/Makefile.linux
  docs/guide/the-user-interface.md
  docs/reference/changelog-r2020.md
  include/.gitignore
  src/packaging/files_core.txt
  src/packaging/webots_distro.c
  src/webots/Makefile
  src/webots/gui/WbImportWizard.cpp
  src/webots/gui/WbImportWizard.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeOperations.hpp
  src/wren/Makefile
Labels: enhancement

#1501 Fixed Missing Supervisor Checks.
  src/lib/Controller/api/supervisor.c
Labels: bug

#1500 Remove homebrew update on Travis
  .travis.yml
Labels: enhancement

#1497 Attempt to Fix ConveyorPlatform
  projects/objects/factory/conveyors/protos/ConveyorPlatform.proto
Labels: bug

#1505 Fix crash with track texture animation
  docs/reference/changelog-r2020.md
  projects/samples/devices/worlds/track.wbt
  src/webots/nodes/WbTrack.cpp
Labels: bug

#1507 Fix Universal Robot Documented Launch Files.
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/README.md
Labels: bug

#1509 Fix wrong sensor name
  projects/samples/robotbenchmark/square_path/plugins/robot_windows/square_path/square_path.html
Labels: bug
