Repository cyberbotics/webots, pull requests merged in 2020-02, with the labels that each got.

#1315 Simulation server script: connect to check port availability
  docs/guide/web-simulation.md
  resources/web/server/simulation_server.py
Labels: bug

#1317 Fixed Importation of Connectors in PROTO.
  docs/reference/changelog-r2020.md
  src/webots/app/WbProtoCachedInfo.cpp
  src/webots/app/WbProtoCachedInfo.hpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
Labels: bug

#1321 Documentation: fix typos in telemetry page
  docs/guide/telemetry.md
Labels: enhancement

#1320 Update WbProtoCachedInfo.cpp
  src/webots/app/WbProtoCachedInfo.cpp
Labels: enhancement

#1325 Invite new contributors to address beginner issues
  CONTRIBUTING.md
Labels: enhancement

#1322 Feature office chair
  docs/reference/changelog-r2020.md
  projects/objects/chairs/protos/OfficeChair.proto
  projects/objects/chairs/protos/icons/OfficeChair.png
  projects/samples/environments/factory/worlds/hall.wbt
  scripts/icon_studio/controllers/icon_creator/objects.json
Labels: enhancement

#1327 Remove doc.php
  docs/doc.php
Labels: invalid

#1326 Hotfix webots-doc.css
  docs/css/webots-doc.css
  docs/js/viewer.js
Labels: bug

#1328 Fix Display
  docs/reference/changelog-r2020.md
  docs/reference/display.md
  include/controller/c/webots/display.h
  include/controller/cpp/webots/Display.hpp
  lib/controller/matlab/mgenerate.py
  src/lib/Controller/api/display.c
  src/webots/core/WbLanguage.cpp
  src/webots/nodes/WbDisplay.cpp
  src/webots/nodes/WbDisplay.hpp
  tests/api/controllers/display/display.c
  tests/api/controllers/display/image.jpg
  tests/api/controllers/display/image.png
Labels: bug

#1330 Responsive doc
  docs/css/webots-doc.css
  docs/js/viewer.js
Labels: enhancement

#1333 Fixed possible warning due to negative QTimer duration
  src/webots/engine/WbSimulationWorld.cpp
Labels: bug

#1332 Fix Display Compilation Warning
  src/lib/Controller/api/display.c
  src/webots/nodes/WbDisplay.cpp
Labels: enhancement

#1334 Fix misspelling in the Thymio brandname
  docs/guide/thymio2.md
Labels: invalid

#1337 Add Missing WB_IMAGE_ABGR.m file
  lib/controller/matlab/WB_IMAGE_ABGR.m
Labels: bug

#1340 Remove signature from gitignore
  .gitignore
Labels: enhancement

#1343 Improve PROTO tutorial
  docs/guide/tutorial-7-your-first-proto.md
Labels: enhancement

#1348 Fix Universal Robots Splash Screen.
  resources/images/splash_images/ure.jpg
Labels: enhancement

#1331 Add Supervisor Internal Field Functions
  docs/reference/changelog-r2020.md
  docs/reference/supervisor.md
  include/controller/c/webots/supervisor.h
  include/controller/cpp/webots/Node.hpp
  include/controller/cpp/webots/Supervisor.hpp
  lib/controller/matlab/mgenerate.py
  lib/controller/matlab/wb_supervisor_node_get_from_proto_def.m
  lib/controller/matlab/wb_supervisor_node_get_proto_field.m
  projects/default/controllers/ros/RosSupervisor.cpp
  projects/default/controllers/ros/include/srv/node_get_field.srv
  projects/default/controllers/ros/include/srv/supervisor_get_from_def.srv
  projects/languages/ros/webots_ros/src/complete_test.cpp
  resources/languages/cpp/Node.cpp
  resources/languages/cpp/Supervisor.cpp
  resources/languages/java/controller.i
  src/lib/Controller/Controller.def
  src/lib/Controller/api/supervisor.c
  src/webots/core/WbLanguage.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
  tests/api/controllers/supervisor_field/supervisor_field.c
  tests/api/controllers/supervisor_get_from_def/supervisor_get_from_def.c
  tests/api/protos/SolidProto.proto
Labels: enhancement

#1349 Improve ABB PROTO
  docs/guide/irb4600-40.md
  docs/reference/changelog-r2020.md
  projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
  projects/robots/abb/irb/protos/Irb4600-40.proto
  projects/robots/abb/irb/worlds/inverse_kinematics.wbt
Labels: enhancement

#1358 Fix wwi make cleanse
  resources/web/wwi/Makefile
Labels: bug

#1360 Fix Missing Python3.8 Libraries on Windows
  projects/default/libraries/vehicle/Makefile
  projects/default/libraries/vehicle/python/Makefile
  projects/robots/robotis/darwin-op/libraries/Makefile
  projects/robots/robotis/darwin-op/libraries/python/Makefile
Labels: bug

#1363 Fix universal robot ros python version
  projects/robots/universal_robots/controllers/universal_robots_ros/universal_robots_ros.py
  tests/sources/test_license.py
Labels: enhancement

#1364 Add argument check for ROS supervisor functions.
  projects/default/controllers/ros/RosSupervisor.cpp
Labels: enhancement

#1367 Fixed a mistake in the table for IDs
  docs/guide/gripper-actuators.md
Labels: bug

#1370 Fix kill_old_webots_instances.py
  resources/web/server/kill_old_webots_instances.py
  src/packaging/files_core.txt
Labels: bug

#1371 Fix Travis Release
  .travis.yml
Labels: bug

#1373 Updated to the latest version of MSYS2
  dependencies/Makefile.windows
  src/packaging/files_msys64.txt
Labels: bug

#1375 Fixed bounding object collision color update
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbGeometry.cpp
Labels: bug

#1376 Add ROSIN Acknowledgement
  docs/guide/samples-environments.md
  docs/guide/turtlebot3-burger.md
Labels: enhancement

#1380 Move Badges
  README.md
Labels: enhancement

#1382 Updated change log
  docs/reference/changelog-r2020.md
Labels: enhancement

#1383 Fix Reset Simulation Tooltip
  src/webots/user_commands/WbActionManager.cpp
Labels: bug

#1385 Fix Receiver Reset
  src/webots/nodes/WbReceiver.cpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbRobot.hpp
  src/webots/nodes/WbSensor.cpp
  src/webots/nodes/WbSensor.hpp
  src/webots/nodes/utils/WbMouse.cpp
Labels: bug

#1378 Fixed Wrong Matlab Paths
  lib/controller/matlab/allincludes.h
  lib/controller/matlab/launcher.m
Labels: bug

#1388 Fix Missing Changelog Entry
  docs/reference/changelog-r2020.md
Labels: enhancement

#1394 Force stdout/stderr flush when a controller is restarted.
  docs/reference/changelog-r2020.md
  src/webots/control/WbControlledWorld.cpp
Labels: bug

#1393 Fix macOS Travis CI
  .travis.yml
Labels: bug

#1392 Update compiling-controllers-in-a-terminal.md
  docs/guide/compiling-controllers-in-a-terminal.md
Labels: enhancement

#1395 Fix Webots application paths on mac.
  docs/guide/running-extern-robot-controllers.md
  projects/vehicles/importer_demo.sh
Labels: bug

#1397 Add libxkbcommon-x11-0 to dependency of debian-package
  src/packaging/webots_distro.c
Labels: bug

#1400 Improve tutorial 6
  docs/guide/tutorial-6-4-wheels-robot.md
Labels: enhancement

#1401 Feature add metal stainless steel cable appearance
  docs/reference/changelog-r2020.md
  projects/appearances/protos/MetalStainlessSteelCable.proto
  projects/appearances/protos/icons/MetalStainlessSteelCable.png
  projects/appearances/protos/textures/metal_stainless_steel_cable/metal_stainless_steel_cable_base_color.jpg
  projects/appearances/protos/textures/metal_stainless_steel_cable/metal_stainless_steel_cable_metalness.jpg
  projects/appearances/protos/textures/metal_stainless_steel_cable/metal_stainless_steel_cable_normal.jpg
  projects/appearances/protos/textures/metal_stainless_steel_cable/metal_stainless_steel_cable_occlusion.jpg
  projects/appearances/protos/textures/metal_stainless_steel_cable/metal_stainless_steel_cable_roughness.jpg
  scripts/icon_studio/controllers/icon_creator/appearances.json
Labels: enhancement

#1402 Fixed PyCharm documentation
  docs/guide/running-extern-robot-controllers.md
  docs/guide/using-your-ide.md
Labels: bug

#1403 Update keyboard.md
  docs/reference/keyboard.md
Labels: enhancement

#1404 Fix wb_supervisor_simulation_reset doc
  docs/reference/supervisor.md
Labels: bug

#1406 Improve Universal Robot ROS README
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/README.md
Labels: enhancement

#1408 Improve Release Publisher Robustness
  src/packaging/publish_release.py
Labels: enhancement

#1413 Improve contributing.md
  CONTRIBUTING.md
Labels: enhancement

#1415 Awake connectors after detach
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbConnector.cpp
  tests/api/controllers/connector/.gitignore
  tests/api/controllers/connector/Makefile
  tests/api/controllers/connector/connector.c
  tests/api/worlds/connector.wbt
Labels: bug
