Repository cyberbotics/webots, pull requests merged in 2020-11, with the labels that each got.

#2423 Modify shaders to have float in the form 1.0 and not just 1
  resources/wren/shaders/pbr.frag
  resources/wren/shaders/phong.frag
  resources/wren/shaders/phong_stencil_ambient_emissive.frag
  resources/wren/shaders/phong_stencil_diffuse_specular.frag
Labels: enhancement, test suite

#2425 Fix padding of vec3 for std140
  src/wren/GlslLayout.hpp
Labels: bug, test suite

#2427 Feature plastic box
  docs/guide/images/objects/containers/MetalStorageBox/model.png
  docs/guide/images/objects/containers/MetalStorageBox/model.thumbnail.png
  docs/guide/images/objects/containers/PlasticFruitBox/model.png
  docs/guide/images/objects/containers/PlasticFruitBox/model.thumbnail.png
  docs/guide/object-factory.md
  docs/reference/changelog-r2021.md
  projects/objects/factory/containers/protos/MetalStorageBox.proto
  projects/objects/factory/containers/protos/PlasticFruitBox.proto
  projects/objects/factory/containers/protos/icons/MetalStorageBox.png
  projects/objects/factory/containers/protos/icons/PlasticFruitBox.png
  projects/objects/factory/containers/protos/textures/metal_storage_box_base_color.jpg
  projects/objects/factory/containers/protos/textures/metal_storage_box_metalness.jpg
  projects/objects/factory/containers/protos/textures/metal_storage_box_normal.jpg
  projects/objects/factory/containers/protos/textures/metal_storage_box_occlusion.jpg
  projects/objects/factory/containers/protos/textures/metal_storage_box_roughness.jpg
  projects/objects/factory/containers/protos/textures/plastic_fruit_box_base_color.jpg
  projects/objects/factory/containers/protos/textures/plastic_fruit_box_metalness.jpg
  projects/objects/factory/containers/protos/textures/plastic_fruit_box_normal.jpg
  projects/objects/factory/containers/protos/textures/plastic_fruit_box_occlusion.jpg
  projects/objects/factory/containers/protos/textures/plastic_fruit_box_roughness.jpg
  scripts/icon_studio/controllers/icon_creator/objects.json
Labels: enhancement

#2429 Improve Python guide
  docs/guide/using-python.md
Labels: documentation

#2433 Fix the type of GL_R16f, GLRGB16f and GL_RGBA16f in GlFormatParams
  src/wren/Texture.cpp
Labels: bug, test suite

#2430 Fix CI `tests_sources.yml` workflow
  .github/workflows/tests_doc.yml
  .github/workflows/tests_sources.yml
Labels: bug

#2434 Fixed performance issue
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbGeometry.cpp
  src/webots/nodes/WbGeometry.hpp
  src/webots/nodes/WbMatter.cpp
  src/webots/nodes/WbPlane.cpp
  src/webots/nodes/WbPlane.hpp
  src/webots/nodes/WbTransform.cpp
Labels: optimization, regression, test suite

#2437 Minor simplification for Cylinders and Capsules
  src/webots/nodes/WbGeometry.cpp
Labels: cleanup, test suite

#2439 Improve stability and performance of the IK example
  .github/workflows/tests_doc.yml
  .github/workflows/tests_sources.yml
  projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
Labels: enhancement

#2440 Fixed typo
  docs/guide/tutorial-6-4-wheels-robot.md
Labels: documentation

#2444 Update jointparameters.md
  docs/reference/jointparameters.md
Labels: documentation

#2447 modify shaders to have float in the form x.0
  resources/wren/shaders/pbr.frag
  resources/wren/shaders/pbr_stencil_ambient_emissive.frag
Labels: enhancement, test suite

#2449 Improve macOS installation instructions
  docs/guide/installation-procedure.md
Labels: documentation

#2443 Fix Python Display.imageNew and improve documentation
  docs/reference/camera.md
  docs/reference/changelog-r2020.md
  docs/reference/display.md
  resources/languages/python/controller.i
Labels: documentation, test suite

#2451 Enhancement Linux installation scripts
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_optional_compilation_dependencies.sh
Labels: bug, enhancement, test distribution, test ros, test suite

#2454 Merge master into develop
  .github/workflows/discord_updater.yml
  .github/workflows/tests_doc.yml
  .github/workflows/tests_sources.yml
  docs/discord/development-2019.md
  docs/discord/documentation.md
  docs/discord/technical-questions-2019.md
  docs/guide/installation-procedure.md
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/reference/camera.md
  docs/reference/changelog-r2020.md
  docs/reference/display.md
  docs/reference/jointparameters.md
  projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
  resources/languages/python/controller.i
Labels: test suite

#2458 Improved Visual C++ wizard explanations
  docs/guide/using-your-ide.md
Labels: documentation

#2457 Fixed a warning displayed by Visual C++
  resources/languages/cpp/Robot.cpp
Labels: cleanup

#2461 Fix subtitle issue
  docs/guide/installation-procedure.md
Labels: documentation

#2462 Fixed shaders causing compilation errors
  resources/wren/shaders/gtao_combine.frag
  resources/wren/shaders/gtao_spatial_denoise.frag
  resources/wren/shaders/gtao_temporal_denoise.frag
  resources/wren/shaders/smaa_blending_weights.frag
Labels: bug, test suite

#2463 remove unused function
  include/wren/texture_cubemap.h
Labels: cleanup

#2465 Update setup-ros GitHub action
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
Labels: bug, test ros

#2464 Merge master into develop
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  docs/discord/development-2020.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/guide/installation-procedure.md
  docs/guide/language-setup.md
  docs/guide/menu.md
  docs/guide/using-your-ide.md
  resources/languages/cpp/Robot.cpp
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_optional_compilation_dependencies.sh
Labels: test ros, test sources, test suite

#2470 Add a missing 'h' in the header guards
  include/wren/skeleton.h
  include/wren/skeleton_bone.h
Labels: cleanup

#2321 Get point cloud as a buffer
  docs/reference/changelog-r2021.md
  docs/reference/lidar.md
  resources/languages/python/controller.i
Labels: enhancement

#2472 replace rgb16f by rgba16f in order to be compatible with webgl
  src/wren/TextureCubeMapBaker.cpp
Labels: enhancement, test suite

#2471 Fix fields order in c3d_viewer.wbt
  projects/humans/c3d/worlds/c3d_viewer.wbt
Labels: enhancement, test world update

#2473 Upload all the Linux packages using GitHub Actions
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  docs/guide/installation-procedure.md
  docs/guide/running-extern-robot-controllers.md
  docs/guide/system-requirements.md
  docs/reference/changelog-r2020.md
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/packaging/webots_distro.c
Labels: test distribution

#2466 Add xvfb to requirements.
  scripts/install/linux_runtime_dependencies.sh
  scripts/packaging/Makefile
Labels: test suite

#2475 Fix GitHub actions
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
Labels: test ros, test suite, test world update

#2477 Merge master into develop
  .github/workflows/discord_updater.yml
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  docs/discord/development-2020.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/guide/installation-procedure.md
  docs/guide/running-extern-robot-controllers.md
  docs/guide/system-requirements.md
  docs/reference/changelog-r2020.md
  docs/reference/display.md
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/linux_runtime_dependencies.sh
  scripts/packaging/Makefile
  scripts/packaging/webots_distro.c
Labels: test suite

#2478 Publish macOS package from GitHub Action
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
Labels: bug, test suite

#2486 Reduce weight of the fridge doors
  projects/objects/kitchen/fridge/protos/Fridge.proto
Labels: bug

#2479 Robotino3.proto is modified to increase movement speed and accuracy and change orientation to FLU.
  docs/guide/robotino3.md
  projects/robots/festo/robotino3/controllers/robotino3/base.c
  projects/robots/festo/robotino3/controllers/robotino3/base.h
  projects/robots/festo/robotino3/controllers/robotino3/robotino3.c
  projects/robots/festo/robotino3/protos/Robotino3.proto
  projects/robots/festo/robotino3/protos/Robotino3Wheel.proto
  projects/robots/festo/robotino3/worlds/robotino3.wbt
Labels: enhancement
