Repository cyberbotics/webots, pull requests merged in 2020-10, with the labels that each got.

#2289 Document the limits of WorldInfo.CFM
  docs/reference/worldinfo.md
Labels: documentation

#2282 Fix cylinder-to-cylinder collision detection
  docs/reference/changelog-r2020.md
  include/ode/ode/common.h
  src/ode/Makefile
  src/ode/libccd/src/custom/ccdcustom/quat.h
  src/ode/libccd/src/custom/ccdcustom/vec3.h
  src/ode/ode/src/collision_libccd.cpp
  src/ode/ode/src/cylinder.cpp
  src/ode/ode/src/error.h
Labels: bug, test suite

#2271 Enhancement Docker installation instructions
  docs/guide/web-simulation.md
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/linux_runtime_dependencies.sh
Labels: documentation, enhancement

#2298 Improve Python Supervisor Example
  docs/guide/supervisor-programming.md
Labels: enhancement

#2297 Fix Travis Nightlies
  .travis.yml
Labels: bug, test suite

#2301 Various fixes in c3d_viewer.py
  projects/humans/c3d/controllers/c3d_viewer/c3d_viewer.py
Labels: cleanup

#2302 Fixed AppVeyor builds
  .appveyor-build-tag.yml
  .appveyor-build.yml
  .appveyor-test-sources-scheduled.yml
Labels: bug

#2303 Workaround AppVeyor broken server
  .appveyor-build-tag.yml
  .appveyor-build.yml
  .appveyor-test-sources-scheduled.yml
  .appveyor.yml
Labels: bug

#2304 Remove unneeded variable definition in Docker example
  docs/guide/web-simulation.md
Labels: documentation

#2305 Fix pycharm documentation
  docs/guide/running-extern-robot-controllers.md
  docs/guide/using-your-ide.md
Labels: documentation

#2309 Reverted MSYS2 server switch
  .appveyor-build-tag.yml
  .appveyor-build.yml
  .appveyor-test-sources-scheduled.yml
  .appveyor.yml
Labels: bug

#2311 Fix missing function Anchor in doc
  docs/reference/robot.md
Labels: documentation

#2312 Updated to Qt 5.15.1 on Windows
  docs/reference/changelog-r2020.md
  src/webots/core/WbHttpReply.cpp
  src/webots/core/WbTelemetry.cpp
Labels: upgrade

#2314 Merge master into develop
  docs/reference/changelog-r2020.md
  docs/reference/robot.md
  src/webots/core/WbHttpReply.cpp
  src/webots/core/WbTelemetry.cpp
Labels: test suite

#2319 Fix typo in tests
  tests/sources/test_matlab_functions.py
Labels: documentation

#2322 Debug ros test
  tests/ros.sh
Labels: bug

#2324 Fix battery with propeller
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbPropeller.cpp
  src/webots/nodes/WbPropeller.hpp
  src/webots/nodes/WbRotationalMotor.cpp
Labels: bug, test suite

#2328 Fix lua dependency download
  dependencies/Makefile.linux
Labels: test distribution

#2330 Fixed Webots Windows launcher to escape properly spaces in arguments
  docs/reference/changelog-r2020.md
  src/webots/launcher/launcher.c
Labels: bug

#2333 Update tests_sources.yml
  .github/workflows/tests_sources.yml
Labels: enhancement

#2331 Fix downloading lua on Windows
  dependencies/Makefile.windows
Labels: bug, test distribution

#2326 Fix Motor Target Position when Changing Joint Parameter Position
  docs/reference/changelog-r2020.md
  src/Controller/api/motor.c
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbHinge2Joint.cpp
  src/webots/nodes/WbHingeJoint.cpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbMotor.hpp
  src/webots/nodes/WbSliderJoint.cpp
  tests/api/controllers/motor/motor.c
Labels: bug, test suite

#2335 Fix cppcheck issues
  .github/workflows/test_suite_mac.yml
  .github/workflows/tests_sources.yml
  projects/default/controllers/ros/RosConnector.cpp
  projects/default/controllers/ros/RosLidar.cpp
  projects/robots/mobsya/thymio/controllers/thymio2_aseba/Thymio2Model.cpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/SSH.cpp
  src/webots/sound/WbPicoTextToSpeech.cpp
  src/wren/demo/default.cpp
Labels: test distribution, test sources

#2339 Fixed a few typos in the doc
  docs/guide/installation-procedure.md
  docs/guide/using-java.md
  docs/guide/using-matlab.md
  docs/reference/robot.md
Labels: documentation

#2340 Attempt to fix new cppcheck issues.
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbHinge2Joint.cpp
  src/webots/nodes/WbHingeJoint.cpp
  src/webots/nodes/WbSliderJoint.cpp
Labels: test sources

#2337 Merge master into develop
  .github/workflows/test_suite_mac.yml
  .github/workflows/tests_sources.yml
  dependencies/Makefile.windows
  docs/discord/development-2020.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/guide/installation-procedure.md
  docs/guide/using-java.md
  docs/guide/using-matlab.md
  docs/reference/changelog-r2020.md
  docs/reference/robot.md
  projects/default/controllers/ros/RosConnector.cpp
  projects/default/controllers/ros/RosLidar.cpp
  projects/robots/mobsya/thymio/controllers/thymio2_aseba/Thymio2Model.cpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/SSH.cpp
  src/Controller/api/motor.c
  src/webots/launcher/launcher.c
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbHinge2Joint.cpp
  src/webots/nodes/WbHingeJoint.cpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbMotor.hpp
  src/webots/nodes/WbSliderJoint.cpp
  src/webots/sound/WbPicoTextToSpeech.cpp
  src/wren/demo/default.cpp
  tests/api/controllers/motor/motor.c
Labels: test sources, test suite

#2344 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#2346 Fix loading RobotisOp2 robot window in humanoid_marathon simulation
  projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/runtime.ini
Labels: bug

#2347 Fix invalid buffer condition
  src/webots/sound/WbPicoTextToSpeech.cpp
Labels: bug, test sources, test suite

#2348 Improve publish_release.py robustness
  scripts/packaging/publish_release.py
Labels: enhancement

#2318 Add python3.9 support
  .appveyor-build-tag.yml
  .appveyor-build.yml
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/tests_doc.yml
  .github/workflows/tests_sources.yml
  .travis.yml
  docs/guide/using-python.md
  docs/reference/changelog-r2020.md
  lib/controller/.gitignore
  projects/default/libraries/vehicle/Makefile
  projects/default/libraries/vehicle/python/Makefile
  projects/robots/robotis/darwin-op/libraries/Makefile
  projects/robots/robotis/darwin-op/libraries/python/Makefile
  projects/robots/robotis/darwin-op/libraries/python39/.gitignore
  resources/languages/Makefile
  resources/languages/python/Makefile
  scripts/install/bash_profile.windows
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/msys.sh
  scripts/packaging/files_core.txt
Labels: test distribution, test suite

#2351 Add missing supervisor fields
  docs/reference/changelog-r2020.md
  projects/vehicles/protos/generic/Tractor.proto
  projects/vehicles/protos/tesla/TeslaModel3.proto
Labels: bug, enhancement

#2350 Replace ros test
  .github/workflows/test_suite_linux.yml
  .travis.yml
  tests/ros.sh
Labels: test ros

#2327 Fix enabling Help item in context menu for Recognition node
  docs/reference/changelog-r2020.md
  src/webots/scene_tree/WbSceneTree.cpp
Labels: bug, test suite

#1825 Update tutorial-4-more-about-controllers.md
  docs/guide/tutorial-4-more-about-controllers.md
Labels: documentation

#2354 Merge master into develop
  .github/workflows/test_suite_linux.yml
  .travis.yml
  docs/guide/tutorial-4-more-about-controllers.md
  docs/reference/changelog-r2020.md
  projects/vehicles/protos/generic/Tractor.proto
  projects/vehicles/protos/tesla/TeslaModel3.proto
  src/webots/scene_tree/WbSceneTree.cpp
  tests/ros.sh
Labels: test ros, test sources, test suite

#2357 Fixed label color-only change
  docs/reference/changelog-r2020.md
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/wren/WbWrenLabelOverlay.hpp
Labels: bug

#2359 Fix missing 'exposure' field documentation
  docs/reference/camera.md
  docs/reference/viewpoint.md
Labels: bug, documentation

#2358 Improve supervisor sample
  projects/samples/devices/controllers/sample_supervisor/sample_supervisor.c
Labels: enhancement, test suite

#2356 Fixed appveyor Python 3.9 build
  .appveyor-build-tag.yml
  .appveyor-build.yml
Labels: bug

#2360 Merge master into develop
  .appveyor-build-tag.yml
  .appveyor-build.yml
  docs/reference/camera.md
  docs/reference/changelog-r2020.md
  docs/reference/viewpoint.md
  projects/samples/devices/controllers/sample_supervisor/sample_supervisor.c
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/wren/WbWrenLabelOverlay.hpp
Labels: enhancement

#2362 Fixed Python 3.9 support on Windows
  src/webots/control/WbLanguageTools.cpp
Labels: bug

#2364 Fixed TexturedParallelepiped proto
  docs/reference/changelog-r2020.md
  projects/objects/geometries/protos/TexturedParallelepiped.proto
Labels: bug

#2286 Add `--no-rendering` flag
  .github/workflows/test_suite_mac.yml
  docs/guide/images/fast-button.png
  docs/guide/images/rendering-button.png
  docs/guide/images/run-button.png
  docs/guide/installation-procedure.md
  docs/guide/starting-webots-remotely-ssh.md
  docs/guide/the-user-interface.md
  docs/guide/tutorial-1-your-first-simulation-in-webots.md
  docs/reference/changelog-r2021.md
  docs/reference/supervisor.md
  include/controller/c/webots/supervisor.h
  include/controller/cpp/webots/Supervisor.hpp
  lib/controller/matlab/WB_SUPERVISOR_SIMULATION_MODE_FAST.m
  lib/controller/matlab/WB_SUPERVISOR_SIMULATION_MODE_RUN.m
  lib/controller/matlab/mgenerate.py
  resources/icons/dark/fast_button.png
  resources/icons/dark/no_rendering.png
  resources/icons/dark/rendering.png
  resources/icons/dark/run_button.png
  resources/icons/light/fast_button.png
  resources/icons/light/no_rendering.png
  resources/icons/light/rendering.png
  resources/icons/light/run_button.png
  resources/translations/wb_de.ts
  resources/translations/wb_es.ts
  resources/translations/wb_fr.ts
  resources/translations/wb_generic.ts
  resources/translations/wb_it.ts
  resources/translations/wb_ja_JP.ts
  resources/translations/wb_zh_CN.ts
  scripts/web_component_studio/web_component_studio.py
  src/Controller/api/robot.c
  src/webots/app/WbContactPointsRepresentation.cpp
  src/webots/app/WbPerspective.cpp
  src/webots/core/WbAction.hpp
  src/webots/core/WbPreferences.cpp
  src/webots/core/WbSimulationState.cpp
  src/webots/core/WbSimulationState.hpp
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbGuiApplication.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbPreferencesDialog.hpp
  src/webots/gui/WbSimulationView.cpp
  src/webots/gui/WbSimulationView.hpp
  src/webots/gui/WbStreamingServer.cpp
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbView3D.hpp
  src/webots/nodes/WbConnector.cpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/user_commands/WbActionManager.cpp
  src/webots/user_commands/WbActionManager.hpp
  tests/api/controllers/supervisor_simulation_mode/supervisor_simulation_mode.c
  tests/test_suite.py
Labels: enhancement, test suite

#2367 Fix macOS CI test suite
  .github/workflows/test_suite_mac.yml
Labels: bug, test suite

#2366 Fix field operations order in Webots
  docs/reference/changelog-r2020.md
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
Labels: bug, crash, test suite

#2371 Removed duplicated ROS files.
  docs/guide/using-ros.md
  projects/languages/ros/webots_ros/CMakeLists.txt
  projects/languages/ros/webots_ros/README.md
  projects/languages/ros/webots_ros/launch/catch_the_bird.launch
  projects/languages/ros/webots_ros/launch/complete_test.launch
  projects/languages/ros/webots_ros/launch/e_puck_line.launch
  projects/languages/ros/webots_ros/launch/keyboard_teleop.launch
  projects/languages/ros/webots_ros/launch/panoramic_view_recorder.launch
  projects/languages/ros/webots_ros/launch/pioneer3at.launch
  projects/languages/ros/webots_ros/launch/robot_information_parser.launch
  projects/languages/ros/webots_ros/launch/webots.launch
  projects/languages/ros/webots_ros/launch/webots_ros_python.launch
  projects/languages/ros/webots_ros/package.xml
  projects/languages/ros/webots_ros/plugins/robot_windows/info/info.html
  projects/languages/ros/webots_ros/plugins/robot_windows/info/info.js
  projects/languages/ros/webots_ros/scripts/ros_controller.py
  projects/languages/ros/webots_ros/scripts/ros_python.py
  projects/languages/ros/webots_ros/scripts/webots_launcher.py
  projects/languages/ros/webots_ros/src/catch_the_bird.cpp
  projects/languages/ros/webots_ros/src/complete_test.cpp
  projects/languages/ros/webots_ros/src/e_puck_line.cpp
  projects/languages/ros/webots_ros/src/keyboard_teleop.cpp
  projects/languages/ros/webots_ros/src/panoramic_view_recorder.cpp
  projects/languages/ros/webots_ros/src/pioneer3at.cpp
  projects/languages/ros/webots_ros/src/pr2_beer.cpp
  projects/languages/ros/webots_ros/src/robot_information_parser.cpp
  projects/languages/ros/webots_ros/worlds/.catch_the_bird.wbproj
  projects/languages/ros/webots_ros/worlds/.complete_test.wbproj
  projects/languages/ros/webots_ros/worlds/.e-puck_line.wbproj
  projects/languages/ros/webots_ros/worlds/.keyboard_teleop.wbproj
  projects/languages/ros/webots_ros/worlds/.panoramic_view_recorder.wbproj
  projects/languages/ros/webots_ros/worlds/.pioneer3at.wbproj
  projects/languages/ros/webots_ros/worlds/.ros_python.wbproj
  projects/languages/ros/webots_ros/worlds/catch_the_bird.wbt
  projects/languages/ros/webots_ros/worlds/complete_test.wbt
  projects/languages/ros/webots_ros/worlds/e-puck_line.wbt
  projects/languages/ros/webots_ros/worlds/keyboard_teleop.wbt
  projects/languages/ros/webots_ros/worlds/panoramic_view_recorder.wbt
  projects/languages/ros/webots_ros/worlds/pioneer3at.wbt
  projects/languages/ros/webots_ros/worlds/ros_python.wbt
  projects/languages/ros/webots_ros/worlds/textures/floor.png
Labels: cleanup, test ros

#2373 Merge master into develop
  docs/discord/development-2020.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/guide/using-ros.md
  docs/reference/changelog-r2020.md
  projects/languages/ros/webots_ros/CMakeLists.txt
  projects/languages/ros/webots_ros/README.md
  projects/languages/ros/webots_ros/launch/catch_the_bird.launch
  projects/languages/ros/webots_ros/launch/complete_test.launch
  projects/languages/ros/webots_ros/launch/e_puck_line.launch
  projects/languages/ros/webots_ros/launch/keyboard_teleop.launch
  projects/languages/ros/webots_ros/launch/panoramic_view_recorder.launch
  projects/languages/ros/webots_ros/launch/pioneer3at.launch
  projects/languages/ros/webots_ros/launch/robot_information_parser.launch
  projects/languages/ros/webots_ros/launch/webots.launch
  projects/languages/ros/webots_ros/launch/webots_ros_python.launch
  projects/languages/ros/webots_ros/package.xml
  projects/languages/ros/webots_ros/plugins/robot_windows/info/info.html
  projects/languages/ros/webots_ros/plugins/robot_windows/info/info.js
  projects/languages/ros/webots_ros/scripts/ros_controller.py
  projects/languages/ros/webots_ros/scripts/ros_python.py
  projects/languages/ros/webots_ros/scripts/webots_launcher.py
  projects/languages/ros/webots_ros/src/catch_the_bird.cpp
  projects/languages/ros/webots_ros/src/complete_test.cpp
  projects/languages/ros/webots_ros/src/e_puck_line.cpp
  projects/languages/ros/webots_ros/src/keyboard_teleop.cpp
  projects/languages/ros/webots_ros/src/panoramic_view_recorder.cpp
  projects/languages/ros/webots_ros/src/pioneer3at.cpp
  projects/languages/ros/webots_ros/src/pr2_beer.cpp
  projects/languages/ros/webots_ros/src/robot_information_parser.cpp
  projects/languages/ros/webots_ros/worlds/.catch_the_bird.wbproj
  projects/languages/ros/webots_ros/worlds/.complete_test.wbproj
  projects/languages/ros/webots_ros/worlds/.e-puck_line.wbproj
  projects/languages/ros/webots_ros/worlds/.keyboard_teleop.wbproj
  projects/languages/ros/webots_ros/worlds/.panoramic_view_recorder.wbproj
  projects/languages/ros/webots_ros/worlds/.pioneer3at.wbproj
  projects/languages/ros/webots_ros/worlds/.ros_python.wbproj
  projects/languages/ros/webots_ros/worlds/catch_the_bird.wbt
  projects/languages/ros/webots_ros/worlds/complete_test.wbt
  projects/languages/ros/webots_ros/worlds/e-puck_line.wbt
  projects/languages/ros/webots_ros/worlds/keyboard_teleop.wbt
  projects/languages/ros/webots_ros/worlds/panoramic_view_recorder.wbt
  projects/languages/ros/webots_ros/worlds/pioneer3at.wbt
  projects/languages/ros/webots_ros/worlds/ros_python.wbt
  projects/languages/ros/webots_ros/worlds/textures/floor.png
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
Labels: test ros, test suite

#2368 Publish Different GPS Messages for `local` and `WGS 84` Coordinate Systems
  docs/reference/changelog-r2021.md
  docs/reference/gps.md
  projects/default/controllers/ros/RosGPS.cpp
Labels: bug, test ros, test suite

#2378 Fix Distance-Sensors Reading with Cached Textures
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbImageTexture.hpp
  src/webots/nodes/WbPbrAppearance.cpp
  src/webots/nodes/WbPbrAppearance.hpp
  tests/api/controllers/distance_sensor_infra-red_cached_images/.gitignore
  tests/api/controllers/distance_sensor_infra-red_cached_images/Makefile
  tests/api/controllers/distance_sensor_infra-red_cached_images/distance_sensor_infra-red_cached_images.c
  tests/api/worlds/distance_sensor_infra-red_cached_images.wbt
  tests/protos/controllers/modify_proto_template_field/modify_proto_template_field.c
Labels: bug, test ros, test sources, test suite

#2380 PyCharm documentation
  docs/guide/using-your-ide.md
Labels: documentation

#2381 Update modeling.md
  docs/guide/modeling.md
Labels: documentation

#2383 change scene_render to correspond to prototype
  src/wren/demo/default.cpp
Labels: bug

#2375 Fix Supervisor API field operations
  docs/reference/changelog-r2020.md
  docs/reference/supervisor.md
  src/Controller/api/robot.c
  src/Controller/api/robot_private.h
  src/Controller/api/supervisor.c
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
Labels: enhancement, test suite

#2391 Fix BotStudio sliders on mac OS
  docs/reference/changelog-r2020.md
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/e-puck/EPuckSlider.cpp
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/e-puck/EPuckSlider.hpp
Labels: bug

#2394 Update proto-definition.md
  docs/reference/proto-definition.md
Labels: documentation

#2393 Fixed clang format
  .appveyor.yml
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/Serial.cpp
Labels: bug

#2397 Merge master into develop
  .appveyor.yml
  CONTRIBUTING.md
  docs/guide/installation-procedure.md
  docs/guide/modeling.md
  docs/guide/using-your-ide.md
  docs/reference/changelog-r2020.md
  docs/reference/proto-definition.md
  docs/reference/supervisor.md
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/Serial.cpp
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/e-puck/EPuckSlider.cpp
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/e-puck/EPuckSlider.hpp
  src/Controller/api/robot.c
  src/Controller/api/robot_private.h
  src/Controller/api/supervisor.c
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbImageTexture.hpp
  src/webots/nodes/WbPbrAppearance.cpp
  src/webots/nodes/WbPbrAppearance.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  tests/api/controllers/distance_sensor_infra-red_cached_images/.gitignore
  tests/api/controllers/distance_sensor_infra-red_cached_images/Makefile
  tests/api/controllers/distance_sensor_infra-red_cached_images/distance_sensor_infra-red_cached_images.c
  tests/api/worlds/distance_sensor_infra-red_cached_images.wbt
  tests/protos/controllers/modify_proto_template_field/modify_proto_template_field.c
Labels: test suite

#2377 Fix active loop waiting for extern controllers
  docs/reference/changelog-r2020.md
  src/webots/control/WbControlledWorld.cpp
  src/webots/control/WbControlledWorld.hpp
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/engine/WbSimulationWorld.hpp
Labels: bug, test suite

#2395 Fix argument order so `isProto()` returns `true` the node is PROTO
  src/Controller/api/supervisor.c
Labels: bug, regression, test suite

#2398 Add ROSIN Acknowledgment
  docs/guide/epuck.md
Labels: documentation, enhancement

#2401 Improve recognition color of BiscuitBox PROTO
  docs/reference/changelog-r2020.md
  projects/objects/kitchen/breakfast/protos/BiscuitBox.proto
Labels: enhancement

#2399 Merge master into develop
  docs/guide/epuck.md
  docs/reference/changelog-r2020.md
  src/webots/control/WbControlledWorld.cpp
  src/webots/control/WbControlledWorld.hpp
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/engine/WbSimulationWorld.hpp
Labels: test suite

#2403 Update WbViewpoint.hpp
  src/webots/nodes/WbViewpoint.hpp
Labels: cleanup

#2405 Nightly Source and doc Tests on github Actions
  .github/workflows/tests_doc.yml
  .github/workflows/tests_sources.yml
  .travis.yml
Labels: enhancement

#2409 Merge master into develop
  .github/workflows/tests_doc.yml
  .github/workflows/tests_sources.yml
  .travis.yml
  docs/discord/development-2020.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/reference/changelog-r2020.md
  projects/objects/kitchen/breakfast/protos/BiscuitBox.proto
  src/webots/nodes/WbViewpoint.hpp
Labels: test sources, test suite

#2411 Fixed clang-format 11.0.0 issues
  .github/workflows/tests_sources.yml
  projects/robots/k-team/khepera1/controllers/pipe/pipe.c
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Serial.cpp
  projects/robots/softbank/nao/controllers/nao_soccer_supervisor/nao_soccer_supervisor.c
  projects/samples/devices/controllers/spherical_camera/spherical_camera.c
  src/webots/nodes/WbViewpoint.cpp
  tests/api/controllers/gps/gps.c
  tests/api/controllers/gps_coordinates_north_direction/gps_coordinates_north_direction.c
Labels: cleanup

#2410 Cleanup Travis Artefacts in sources tests.
  .github/workflows/tests_sources.yml
  projects/robots/fujitsu/hoap2/controllers/hoap2/hoap2.c
  projects/robots/robotis/turtlebot/controllers/turtlebot3_ostacle_avoidance/turtlebot3_ostacle_avoidance.c
  projects/robots/softbank/nao/controllers/nao_soccer_supervisor/nao_soccer_supervisor.c
  tests/sources/bin/cfg/std.cfg
  tests/sources/bin/cppcheck
  tests/sources/test_clang_format.py
  tests/sources/test_cppcheck.py
Labels: test sources

#2413 Merge master into develop
  .github/workflows/tests_sources.yml
  projects/robots/fujitsu/hoap2/controllers/hoap2/hoap2.c
  projects/robots/k-team/khepera1/controllers/pipe/pipe.c
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Serial.cpp
  projects/robots/robotis/turtlebot/controllers/turtlebot3_ostacle_avoidance/turtlebot3_ostacle_avoidance.c
  projects/robots/softbank/nao/controllers/nao_soccer_supervisor/nao_soccer_supervisor.c
  projects/samples/devices/controllers/spherical_camera/spherical_camera.c
  src/webots/nodes/WbViewpoint.cpp
  tests/api/controllers/gps/gps.c
  tests/api/controllers/gps_coordinates_north_direction/gps_coordinates_north_direction.c
  tests/sources/bin/cfg/std.cfg
  tests/sources/bin/cppcheck
  tests/sources/test_clang_format.py
  tests/sources/test_cppcheck.py
Labels: test suite

#2407 Fix Github Action macOS build
  .github/workflows/test_suite_mac.yml
Labels: test suite

#2408 Attempt to enable source test on Windows Github Action
  .appveyor-test-sources-scheduled.yml
  .appveyor.yml
  .github/workflows/tests_sources.yml
  tests/sources/generate_diff.py
  tests/sources/parent_branch.sh
Labels: test sources

#2406 Fix movie recording behavior on simulation reset from Supervisor controller
  docs/reference/changelog-r2020.md
  src/Controller/api/supervisor.c
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbSimulationView.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/nodes/utils/WbWorld.hpp
Labels: bug, test suite

#2419 Feature Windows Github Action
  .github/workflows/test_suite_windows.yml
Labels: enhancement, test suite

#2421 Github workflows develop
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/tests_sources.yml
Labels: enhancement

#2422 Commercial to Open-source
  docs/guide/citing-webots.md
Labels: documentation, test sources
