Repository cyberbotics/webots, pull requests merged in 2020-01, with the labels that each got.

#1228 Fixed unclosed files in test.
  tests/sources/test_icons.py
Labels: bug

#1237 Fix nightly from master
  .travis.yml
Labels: bug

#1232 Remove Problematic xvfb Hack.
  src/packaging/Makefile
Labels: enhancement

#1239 Extend Travis Tests.
  .travis.yml
Labels: enhancement

#1240 Fix cppcheck errors
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/e-puck/EPuckFacade.cpp
  projects/robots/mobsya/thymio/controllers/thymio2_demo/thymio2_demo.c
  projects/samples/curriculum/controllers/advanced_slam_2/advanced_slam_2.c
  src/lib/Controller/api/camera.c
  src/lib/Controller/api/supervisor.c
  src/lib/Controller/api/system.c
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/vrml/WbProtoList.hpp
  src/webots/vrml/WbProtoModel.hpp
  src/wren/StaticMesh.cpp
  tests/sources/test_cppcheck.py
Labels: bug

#1241 Fix Webots Compilation
  src/webots/nodes/WbBaseNode.cpp
Labels: bug

#1243 Fix Travis Output
  .travis.yml
Labels: enhancement

#1233 Add SUMO_HOME support.
  docs/automobile/sumo-interface.md
  docs/reference/changelog-r2020.md
  projects/default/controllers/sumo_supervisor/SumoSupervisor.py
  projects/default/controllers/sumo_supervisor/sumo_supervisor.py
  projects/vehicles/worlds/sumo_interface_example_net/plugin.py
Labels: enhancement

#1244 Remove OpenCV
  dependencies/Makefile.linux
  dependencies/Makefile.mac
  docs/guide/samples-howto.md
  docs/reference/changelog-r2020.md
  include/.gitignore
  projects/samples/howto/controllers/Makefile
  projects/samples/howto/controllers/vision/Makefile
  projects/samples/howto/controllers/vision/vision.cpp
  src/install_scripts/msys64_installer.sh
  src/packaging/copy_msys64_files.py
  src/packaging/files_core.txt
  src/packaging/files_msys64.txt
  src/packaging/webots_distro.c
Labels: enhancement

#1246 Fixed SUMO and ROS dependencies makefiles.
  projects/default/libraries/Makefile
  projects/default/resources/Makefile
Labels: bug, enhancement

#1249 Fix field name responsible for the ODE number of threads
  docs/guide/modeling.md
Labels: bug

#1248 Fix wb_supervisor_add_force_with_offset()
  docs/reference/changelog-r2020.md
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
Labels: bug

#1254 Improved PROTO guidelines doc
  docs/reference/proto-design-guidelines.md
Labels: enhancement

#1255 Replaced curl with more robust wget
  projects/default/controllers/ros/include/Makefile
  projects/default/libraries/Makefile
  projects/default/resources/Makefile
  projects/robots/gctronic/e-puck/transfer/Makefile
Labels: bug

#1257 Doc - Update reference links of Pioneer 3-AT and 3-DX
  docs/guide/pioneer-3at.md
  docs/guide/pioneer-3dx.md
Labels: bug

#1256 Improve Hall Environment
  docs/guide/appearances.md
  docs/guide/images/appearances/ScratchedPaint.png
  docs/guide/images/appearances/ScratchedPaint.thumbnail.png
  docs/guide/object-apartment-structure.md
  docs/reference/changelog-r2020.md
  projects/appearances/protos/BakelitePlastic.proto
  projects/appearances/protos/ScratchedPaint.proto
  projects/appearances/protos/icons/ScratchedPaint.png
  projects/appearances/protos/textures/bakelite_plastic/bakelite_plastic_base_color_braun.jpg
  projects/appearances/protos/textures/bakelite_plastic/bakelite_plastic_base_color_red.jpg
  projects/appearances/protos/textures/scratched_paint/scratched_paint_base_color.jpg
  projects/appearances/protos/textures/scratched_paint/scratched_paint_metalness.jpg
  projects/appearances/protos/textures/scratched_paint/scratched_paint_roughness.jpg
  projects/objects/apartment_structure/protos/Door.proto
  projects/samples/environments/factory/worlds/hall.wbt
  projects/samples/environments/factory/worlds/textures/metal_grid_base_color.png
  projects/samples/environments/factory/worlds/textures/metal_grid_normal.png
  scripts/icon_studio/controllers/icon_creator/appearances.json
Labels: enhancement

#1258 Improve Doc Generation
  docs/guide/appearances.md
  docs/guide/generate_objects_doc.py
  docs/guide/object-advertising-board.md
  docs/guide/object-backgrounds.md
  docs/guide/object-buildings.md
  docs/guide/object-computers.md
  docs/guide/object-factory.md
  docs/guide/object-floors.md
  docs/guide/object-geometries.md
  docs/guide/object-road.md
  docs/guide/object-shapes.md
  docs/guide/object-street-furniture.md
  docs/guide/object-television.md
  docs/guide/object-traffic.md
  docs/guide/object-trees.md
  projects/appearances/protos/Leather.proto
  projects/objects/buildings/protos/Building.proto
  projects/objects/buildings/protos/FastFoodRestaurant.proto
  projects/objects/buildings/protos/OldResidentialBuilding.proto
  projects/objects/buildings/protos/RandomBuilding.proto
  projects/objects/buildings/protos/ResidentialBuildingWithRoundFront.proto
  projects/objects/buildings/protos/SimpleBuilding.proto
  projects/objects/buildings/protos/SmallResidentialBuilding.proto
  projects/objects/street_furniture/protos/Fence.proto
  projects/objects/trees/protos/SimpleTree.proto
Labels: bug, enhancement

#1264 Fix Travis on macos
  .travis.yml
Labels: bug

#1272 Improve Motion-Blur Sample.
  projects/samples/devices/controllers/camera/camera.c
  projects/samples/devices/worlds/camera_motion_blur.wbt
Labels: enhancement

#1274 Update Webots Version.
  Contents/Info.plist
  docs/js/showdown-extensions.js
  resources/version.txt
  src/packaging/webots_version.txt
  src/webots/core/WbApplicationInfo.cpp
Labels: enhancement

#1276 Improve Supervisor set/get Velocity function
  docs/reference/supervisor.md
Labels: enhancement

#1275 Added missing units to parameter descriptions
  docs/reference/motor.md
  docs/reference/positionsensor.md
Labels: enhancement

#1278 Removed undefined function
  src/lib/Controller/api/robot_private.h
Labels: bug

#1280 Improve Web Component Studio to Support Python3.5
  scripts/web_component_studio/web_component_studio.py
Labels: bug

#1281 Remove Useless Runtime.ini File
  projects/robots/robotis/darwin-op/controllers/soccer/runtime.ini
Labels: bug

#1283 Fixed red planet color
  docs/reference/changelog-r2020.md
  projects/appearances/protos/Soil.proto
  projects/objects/rocks/protos/Rock10cm.proto
  projects/objects/rocks/protos/Rock17cm.proto
  projects/robots/nasa/worlds/sojourner.wbt
Labels: enhancement

#1284 Update Rock10cm.proto
  projects/objects/rocks/protos/Rock10cm.proto
Labels: enhancement

#1286 Add PROTO Field Comment Test
  projects/default/protos/SumoInterface.proto
  projects/devices/generic/protos/Servo.proto
  projects/devices/multisense/protos/MultiSenseS21.proto
  projects/objects/apartment_structure/protos/Door.proto
  projects/objects/bedroom/protos/Bed.proto
  projects/objects/buildings/protos/Building.proto
  projects/objects/factory/pallet/protos/WoodenPalletStack.proto
  projects/objects/panels/protos/Panel.proto
  projects/objects/road/protos/Crossroad.proto
  projects/objects/road/protos/HelicoidalRoadSegment.proto
  projects/objects/road/protos/LaneSeparation.proto
  projects/objects/road/protos/Road.proto
  projects/objects/road/protos/RoadIntersection.proto
  projects/objects/road/protos/Roundabout.proto
  projects/objects/road/protos/StraightRoadSegment.proto
  projects/objects/traffic/protos/CautionPanel.proto
  projects/objects/traffic/protos/ExitPanel.proto
  projects/objects/traffic/protos/ExitSign.proto
  projects/objects/traffic/protos/OrderPanel.proto
  projects/objects/traffic/protos/RectangularPanel.proto
  projects/objects/traffic/protos/SpeedLimitPanel.proto
  projects/objects/traffic/protos/StopPanel.proto
  projects/objects/traffic/protos/YieldPanel.proto
  projects/robots/gctronic/e-puck/protos/E-puck.proto
  projects/robots/gctronic/e-puck/protos/E-puckDistanceSensor.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsAxle.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsBase.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCube.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieBoxWithCrossSlots.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieBoxWithRoundSlots.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieFemaleCube.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieMaleCube.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubiePyramid.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieTriangle.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsDistanceSensor.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsGrabber.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsLightSensor.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsMotor.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsPivot.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsTwister.proto
  projects/robots/kuka/youbot/protos/KukaBox.proto
  projects/robots/mobsya/thymio/protos/Thymio2LED.proto
  projects/robots/saeon/protos/AltinoWheel.proto
  projects/samples/robotbenchmark/pit_escape/protos/Pit.proto
  projects/vehicles/protos/abstract/Car.proto
  projects/vehicles/protos/bmw/BmwX5Wheel.proto
  projects/vehicles/protos/citroen/CitroenCZeroFrontWheel.proto
  projects/vehicles/protos/citroen/CitroenCZeroRearWheel.proto
  projects/vehicles/protos/generic/BusWheel.proto
  projects/vehicles/protos/generic/MotorbikeWheel.proto
  projects/vehicles/protos/generic/ScooterWheel.proto
  projects/vehicles/protos/generic/TruckWheel.proto
  projects/vehicles/protos/toyota/ToyotaPriusWheel.proto
  tests/sources/test_proto.py
Labels: enhancement

#1285 Fix Camera Image Save to JPEG
  docs/reference/changelog-r2020.md
  src/lib/Controller/util/g_image.c
Labels: bug

#1288 Add a Stadium Background
  projects/default/worlds/textures/cubic/stadium_back.hdr
  projects/default/worlds/textures/cubic/stadium_back.png
  projects/default/worlds/textures/cubic/stadium_bottom.hdr
  projects/default/worlds/textures/cubic/stadium_bottom.png
  projects/default/worlds/textures/cubic/stadium_front.hdr
  projects/default/worlds/textures/cubic/stadium_front.png
  projects/default/worlds/textures/cubic/stadium_left.hdr
  projects/default/worlds/textures/cubic/stadium_left.png
  projects/default/worlds/textures/cubic/stadium_right.hdr
  projects/default/worlds/textures/cubic/stadium_right.png
  projects/default/worlds/textures/cubic/stadium_top.hdr
  projects/default/worlds/textures/cubic/stadium_top.png
  projects/objects/backgrounds/protos/TexturedBackground.proto
  projects/objects/backgrounds/protos/TexturedBackgroundLight.proto
  projects/objects/robotstadium/protos/textures/field_quarter_base_color.jpg
  projects/robots/robotis/darwin-op/worlds/soccer.wbt
  projects/robots/softbank/nao/worlds/nao_robocup.wbt
  projects/robots/softbank/nao/worlds/robotstadium_nao_vs_robotis-op2.wbt
  scripts/image_tools/clamp_hdr.py
  scripts/image_tools/downscale_hdr.py
Labels: enhancement

#1289 Fix missing units
  docs/automobile/driver-library.md
  docs/guide/robotis-op2.md
  docs/guide/tutorial-5-compound-solid-and-physics-attributes.md
  docs/reference/accelerometer.md
  docs/reference/changelog-5.md
  docs/reference/connector.md
  docs/reference/differentialwheels.md
  docs/reference/fluid.md
  docs/reference/immersionproperties.md
  docs/reference/lightsensor.md
  docs/reference/linearmotor.md
  docs/reference/motor.md
  docs/reference/physics.md
  docs/reference/positionsensor.md
  docs/reference/receiver.md
  docs/reference/rotationalmotor.md
  docs/reference/spotlight.md
  docs/reference/touchsensor.md
Labels: enhancement

#1292 Add a Pull-Request Template
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
Labels: enhancement

#1293 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement

#1294 Fixed TurtleBot3 Burger max Velocity.
  docs/reference/changelog-r2020.md
  projects/robots/robotis/turtlebot/protos/TurtleBot3Burger.proto
Labels: bug

#1295 Fix macOs extern controller doc
  docs/guide/running-extern-robot-controllers.md
Labels: bug

#1300 Fixed the Center of Mass of the TurtleBot3.
  docs/reference/changelog-r2020.md
  projects/robots/robotis/turtlebot/protos/TurtleBot3Burger.proto
Labels: bug

#1301 Improve support for mail servers in session server script
  docs/guide/web-simulation.md
  resources/web/server/config/session/cyberbotics1.json
  resources/web/server/session_server.py
Labels: enhancement

#1302 webots.min.js: fix texture transform not applied at load
  resources/web/wwi/webots.js
  resources/web/wwi/x3d_scene.js
Labels: bug

#1305 Fix Robot X3D export.
  src/webots/nodes/WbRobot.cpp
Labels: bug

#1306 Fix WGET issue with language on macOS.
  dependencies/Makefile.mac
  projects/default/controllers/ros/include/Makefile
  projects/default/libraries/Makefile
  projects/default/resources/Makefile
  projects/languages/ros/controllers/ros_python/Makefile
  projects/robots/gctronic/e-puck/transfer/Makefile
  projects/robots/robotis/darwin-op/libraries/Makefile.mac
  resources/web/wwi/Makefile
Labels: bug

#1307 Update running-extern-robot-controllers.md
  docs/guide/running-extern-robot-controllers.md
Labels: bug

#1303 Documentation: fix extracting tabs if version is not specified
  docs/doc.php
Labels: bug

#1299 Add python3.8 macOS Support.
  .travis.yml
  docs/guide/using-python.md
  docs/reference/changelog-r2020.md
  resources/languages/Makefile
  resources/languages/python/Makefile
  src/packaging/files_core.txt
Labels: enhancement

#1311 Support Python 3.8 on Windows
  .appveyor-build-tag.yml
  .appveyor-build.yml
  .appveyor-test-sources-scheduled.yml
  .appveyor.yml
  docs/reference/changelog-r2020.md
  resources/languages/Makefile
  resources/languages/python/Makefile
  resources/languages/python/_controller2.def
  resources/languages/python/_controller3.def
  resources/languages/python/controller.i
  src/install_scripts/bash_profile.appveyor
  src/install_scripts/bash_profile.windows
  src/install_scripts/msys.sh
  src/packaging/files_core.txt
  src/webots/control/WbLanguageTools.cpp
  src/webots/gui/WbGuiApplication.cpp
Labels: enhancement

#1312 Fixed flake8 warnings
  src/packaging/copy_msys64_files.py
Labels: enhancement

#1309 Improve Convert to Base Nodes
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbImageTexture.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/scene_tree/WbSceneTree.hpp
  src/webots/user_commands/WbActionManager.cpp
  src/webots/user_commands/WbActionManager.hpp
  src/webots/user_commands/WbContextMenuGenerator.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbVrmlWriter.cpp
  src/webots/vrml/WbVrmlWriter.hpp
Labels: bug, enhancement
