Repository cyberbotics/webots, pull requests merged in 2020-09, with the labels that each got.

#2180 Handle ctrl-click for intra-page anchor links
  docs/js/viewer.js
Labels: bug

#2178 Update supported ros version in tutorial 8
  docs/guide/tutorial-8-using-ros.md
Labels: documentation

#2183 Update OSM importer doc to python3
  docs/automobile/openstreetmap-importer.md
Labels: bug

#2182 Fix PointSet crash
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbPointSet.cpp
  tests/rendering/worlds/point_set.wbt
Labels: crash, test suite

#2172 Enforce check of ros controller in package
  scripts/packaging/exist_in_projects_linux.txt
Labels: bug, test suite

#2184 Update running-extern-robot-controllers.md
  docs/guide/running-extern-robot-controllers.md
Labels: documentation

#2188 Replace flat ElevationGrids with Planes
  projects/robots/irobot/create/worlds/create.wbt
  projects/robots/neuronics/ipr/worlds/ipr_factory.wbt
  projects/samples/curriculum/worlds/advanced_path_planning.wbt
  projects/samples/environments/indoor/worlds/apartment.wbt
  projects/samples/howto/worlds/biped.wbt
  projects/samples/howto/worlds/sick_terrain_scanning.wbt
Labels: cleanup

#2185 Fix UnevenTerrain Size
  docs/reference/changelog-r2020.md
  projects/objects/floors/protos/UnevenTerrain.proto
  projects/robots/micromagic/mantis/worlds/mantis.wbt
  projects/robots/sphero/bb8/worlds/bb-8.wbt
  projects/samples/demos/worlds/anaglyph.wbt
  src/webots/nodes/WbElevationGrid.cpp
  src/wren/StaticMesh.cpp
Labels: bug, test suite

#2192 Cleanup simplify splash screen code
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbSplashScreen.cpp
Labels: cleanup

#2190 Add ros dependencies to snap package too.
  scripts/packaging/webots_distro.c
Labels: bug, test distribution

#2193 Update Webots version on master
  Contents/Info.plist
  docs/js/showdown-extensions.js
  resources/version.txt
  scripts/new_version/new_version.sh
  scripts/new_version/new_version_file_headers.sh
  scripts/packaging/webots_version.txt
  src/webots/core/WbApplicationInfo.cpp
Labels: upgrade

#2200 Fix Webots version in github workflow
  .github/workflows/test_suite_mac.yml
Labels: test suite

#2201 Improve Export Functionnality.
  src/webots/nodes/WbRobot.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbNode.hpp
Labels: enhancement, test suite

#2203 Improve northDirection Field Warning
  src/webots/nodes/WbWorldInfo.cpp
Labels: enhancement, test suite

#2205 Fixed aseba controller link on Windows
  projects/robots/mobsya/thymio/controllers/thymio2_aseba/Makefile
  projects/robots/mobsya/thymio/controllers/thymio2_aseba/Thymio2AsebaHub.cpp
Labels: bug

#2209 Improve error message
  src/webots/scene_tree/WbSceneTree.cpp
Labels: enhancement, test suite

#2210 Fix Memory Leak in Robot-Window
  docs/reference/changelog-r2020.md
  src/Controller/api/default_robot_window.c
Labels: bug, test suite

#2196 Notify when the overlay foreground texture is updated
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbCamera.cpp
  src/webots/wren/WbWrenTextureOverlay.cpp
Labels: bug, test suite

#2207 Improve Linux Runtime Dependencies Script
  .github/workflows/test_suite_linux.yml
  scripts/install/linux_runtime_dependencies.sh
Labels: enhancement, test suite

#2211 Fixed Inverse Kinematics Controller
  docs/reference/changelog-r2020.md
  projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
Labels: bug

#2213 Cleanup Unused 'mAnchor' WbJoint Member
  src/webots/nodes/WbJoint.hpp
Labels: cleanup, test suite

#2216 Merge master into develop
  .github/workflows/test_suite_linux.yml
  docs/reference/changelog-r2020.md
  projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
  scripts/converter/convert_eun_to_nue.py
  scripts/converter/convert_nue_to_enu.py
  scripts/converter/webots_parser.py
  scripts/install/linux_runtime_dependencies.sh
  src/Controller/api/default_robot_window.c
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbJoint.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/wren/WbWrenTextureOverlay.cpp
Labels: test suite

#2218 Fix vehicle library doc
  docs/automobile/car-library.md
  docs/automobile/driver-library.md
Labels: bug, documentation

#2215 Fix noise generation in GLSL
  docs/reference/changelog-r2020.md
  resources/wren/shaders/color_noise.frag
  resources/wren/shaders/color_noise.vert
  resources/wren/shaders/range_noise.frag
  resources/wren/shaders/range_noise.vert
Labels: bug, test suite

#2217 Force 'NUE' in convert_eun_to_nue script
  scripts/converter/convert_eun_to_nue.py
Labels: enhancement

#2219 Add Docker Instructions
  docs/guide/installation-procedure.md
Labels: documentation, feature

#2224 Fix P-Rob3 default field value.
  projects/robots/fp_robotics/p-rob3/protos/P-Rob3.proto
Labels: bug

#2225 Improve Github Action Nightlies Stability
  .github/workflows/test_suite_linux.yml
Labels: enhancement, test world update

#2214 Fix Urdf Joint Origin
  docs/reference/changelog-r2020.md
  projects/objects/factory/tools/protos/CapScrew.proto
  projects/robots/pal_robotics/tiago++/protos/Tiago++.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoGripper.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightArm.proto
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbJoint.cpp
  src/webots/nodes/WbSliderJoint.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/vrml/WbVrmlWriter.cpp
  src/webots/vrml/WbVrmlWriter.hpp
  tests/api/controllers/robot_urdf/.gitignore
  tests/api/controllers/robot_urdf/prob3_reference.urdf
  tests/api/controllers/robot_urdf/tiago_reference.urdf
  tests/api/worlds/robot_urdf.wbt
Labels: bug, test suite

#2227 Remove Useless Transform in Create world
  projects/robots/irobot/create/worlds/create.wbt
Labels: test world update

#2230 Merge master into develop
  .github/workflows/test_suite_linux.yml
  docs/automobile/car-library.md
  docs/automobile/driver-library.md
  docs/discord/development-2020.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/guide/installation-procedure.md
  docs/reference/changelog-r2020.md
  projects/objects/factory/tools/protos/CapScrew.proto
  projects/robots/fp_robotics/p-rob3/protos/P-Rob3.proto
  projects/robots/irobot/create/worlds/create.wbt
  projects/robots/pal_robotics/tiago++/protos/Tiago++.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoGripper.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightArm.proto
  resources/wren/shaders/color_noise.frag
  resources/wren/shaders/color_noise.vert
  resources/wren/shaders/range_noise.frag
  resources/wren/shaders/range_noise.vert
  scripts/converter/convert_eun_to_nue.py
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbJoint.cpp
  src/webots/nodes/WbSliderJoint.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/vrml/WbVrmlWriter.cpp
  src/webots/vrml/WbVrmlWriter.hpp
  tests/api/controllers/robot_urdf/.gitignore
  tests/api/controllers/robot_urdf/prob3_reference.urdf
  tests/api/controllers/robot_urdf/tiago_reference.urdf
  tests/api/worlds/robot_urdf.wbt
Labels: test suite

#2228 EUN Coordinate System
  docs/reference/changelog-r2021.md
  docs/reference/procedural-proto-nodes.md
  docs/reference/worldinfo.md
  resources/nodes/WorldInfo.wrl
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbCompass.cpp
  src/webots/nodes/WbGps.cpp
  src/webots/nodes/WbInertialUnit.cpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/nodes/WbWorldInfo.cpp
  src/webots/nodes/WbWorldInfo.hpp
  tests/api/controllers/compass/compass.c
  tests/api/worlds/compass.wbt
Labels: enhancement, test suite

#2231 Run Test in the Github Action Nightlies
  .github/workflows/test_suite_linux.yml
Labels: enhancement

#2232 Document Brew macOS Installation
  docs/guide/installation-procedure.md
Labels: documentation

#2233 Improve docker doc
  docs/guide/installation-procedure.md
Labels: documentation

#2223 Add Webots Privacy Policy
  docs/guide/menu.md
  docs/guide/privacy-policy.md
  docs/guide/telemetry.md
  src/webots/gui/WbAboutBox.cpp
Labels: documentation, test suite

#2238 Update running-extern-robot-controllers.md
  docs/guide/running-extern-robot-controllers.md
Labels: documentation

#2240 Update Docker Doc
  docs/guide/installation-procedure.md
Labels: enhancement

#2096 Fix deployment of robot windows on the web
  README.md
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.html
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.js
  projects/humans/c3d/protos/C3dViewer.proto
  projects/humans/c3d/worlds/.c3d_viewer.wbproj
  projects/humans/c3d/worlds/c3d_viewer.wbt
  projects/languages/ros/webots_ros/plugins/robot_windows/info/info.html
  projects/objects/factory/valves/protos/LargeValve.proto
  projects/objects/factory/valves/protos/LeverValve.proto
  projects/objects/factory/valves/protos/SmallValve.proto
  projects/objects/factory/valves/protos/textures/valve_handle.jpg
  projects/objects/factory/valves/protos/textures/valve_handle_normal.jpg
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.html
  projects/robots/mobsya/thymio/plugins/robot_windows/thymio2/thymio2.html
  projects/samples/robotbenchmark/highway_driving/plugins/robot_windows/highway_driving/highway_driving.html
  projects/samples/robotbenchmark/humanoid_marathon/plugins/robot_windows/humanoid_marathon/humanoid_marathon.html
  projects/samples/robotbenchmark/humanoid_sprint/plugins/robot_windows/humanoid_sprint/humanoid_sprint.html
  projects/samples/robotbenchmark/inverted_pendulum/plugins/robot_windows/inverted_pendulum/inverted_pendulum.html
  projects/samples/robotbenchmark/maze_runner/plugins/robot_windows/maze_runner/maze_runner.html
  projects/samples/robotbenchmark/obstacle_avoidance/plugins/robot_windows/obstacle_avoidance/obstacle_avoidance.html
  projects/samples/robotbenchmark/pick_and_place/plugins/robot_windows/pick_and_place/pick_and_place.html
  projects/samples/robotbenchmark/pit_escape/plugins/robot_windows/pit_escape/pit_escape.html
  projects/samples/robotbenchmark/robot_programming/plugins/robot_windows/robot_programming/robot_programming.html
  projects/samples/robotbenchmark/square_path/plugins/robot_windows/square_path/square_path.html
  projects/samples/robotbenchmark/viewpoint_control/plugins/robot_windows/viewpoint_control/viewpoint_control.html
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/pan_tilt_camera_view/pan_tilt_camera_view.html
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/visual_tracking/visual_tracking.html
  projects/samples/robotbenchmark/wall_following/plugins/robot_windows/wall_following/wall_following.html
  resources/projects/plugins/robot_windows/generic/generic.html
  resources/web/local/webots.js
  resources/web/server/simulation_server.py
  resources/web/streaming_viewer/index-debug.html
  resources/web/streaming_viewer/index.html
  resources/web/streaming_viewer/setup_viewer.js
  resources/web/wwi/multimedia_client.js
  resources/web/wwi/robot_window.js
  resources/web/wwi/server.js
  resources/web/wwi/stream.js
  resources/web/wwi/webots.js
  resources/web/wwi/wwi.css
  src/webots/core/WbHttpReply.cpp
  src/webots/core/WbHttpReply.hpp
  src/webots/gui/WbMultimediaStreamingServer.cpp
  src/webots/gui/WbRobotWindow.cpp
  src/webots/gui/WbStreamingServer.cpp
  src/webots/gui/WbStreamingServer.hpp
  src/webots/gui/WbX3dStreamingServer.cpp
  tests/api/plugins/robot_windows/info/info.html
Labels: enhancement, test suite

#2237 Add device during robot controller run
  docs/reference/changelog-r2021.md
  resources/projects/plugins/robot_windows/generic/generic.js
  src/Controller/api/default_robot_window.c
  src/Controller/api/messages.h
  src/Controller/api/robot.c
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbRobot.hpp
  tests/api/controllers/supervisor_import_robot_node/supervisor_import_robot_node.c
Labels: enhancement, test suite

#2246 Fix date in About box
  src/webots/gui/WbAboutBox.cpp
Labels: bug, test suite

#2249 Improve streaming viewer and add web simulation quick start
  docs/guide/web-simulation.md
  resources/web/streaming_viewer/index.html
  resources/web/streaming_viewer/setup_viewer.js
  resources/web/streaming_viewer/style.css
Labels: documentation, enhancement

#2256 Fix typos
  Makefile
Labels: enhancement

#2255 Fix forgeUrl in viewer.js
  docs/js/viewer.js
Labels: bug

#2260 Fixed startup of extern controllers with WEBOTS_PID set
  docs/reference/changelog-r2020.md
  src/Controller/api/system.c
Labels: bug

#2261 Fixed debug streaming viewer page
  resources/web/streaming_viewer/index-debug.html
Labels: bug, cleanup

#2263 Merge master into develop
  .github/CODEOWNERS
  .github/workflows/test_suite_linux.yml
  Makefile
  docs/discord/development-2020.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/guide/installation-procedure.md
  docs/guide/menu.md
  docs/guide/privacy-policy.md
  docs/guide/running-extern-robot-controllers.md
  docs/guide/telemetry.md
  docs/js/viewer.js
  docs/reference/changelog-r2020.md
  docs/reference/motor.md
  src/Controller/api/system.c
  src/webots/gui/WbAboutBox.cpp
Labels: test suite

#2265 Fixed Ctrl key keyboard interface on macOS
  docs/reference/changelog-r2020.md
  src/webots/gui/WbView3D.cpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbRobot.hpp
Labels: bug, test suite

#2266 Compute Animation step update after Solid coordinates have been updated
  docs/reference/changelog-r2020.md
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbDistanceSensor.cpp
  src/webots/nodes/WbLightSensor.cpp
  src/webots/nodes/WbRadar.cpp
  src/webots/nodes/WbReceiver.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolid.hpp
  src/webots/nodes/utils/WbObjectDetection.cpp
Labels: bug, test suite

#2250 Allow upload of C3D files from the robot window
  projects/humans/c3d/controllers/c3d_viewer/c3d_viewer.py
  projects/humans/c3d/controllers/c3d_viewer/default.c3d
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.html
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.js
  projects/humans/c3d/worlds/c3d_viewer.wbt
  resources/web/server/server.sh
  resources/web/wwi/stream.js
  resources/web/wwi/webots.js
Labels: bug, enhancement

#2268 Fixed movie recording when WorldInfo.basicTimeStep was greater than 40
  docs/reference/changelog-r2020.md
  src/webots/gui/WbVideoRecorder.cpp
Labels: bug, test suite

#2276 Fix optional rendering on reset
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbDistanceSensor.cpp
Labels: bug, test suite

#2277 Update supervisor.md
  docs/reference/supervisor.md
Labels: documentation

#2275 Update supervisor-programming.md
  docs/guide/supervisor-programming.md
Labels: documentation

#2272 Supervisor documentation: add missing field type values
  docs/reference/supervisor.md
Labels: documentation
