Repository cyberbotics/webots, pull requests merged in 2020-07, with the labels that each got.

#1847 Fix warning for is datatype mismatch in procedural protos
  projects/objects/road/protos/LaneSeparation.proto
  projects/robots/fp_robotics/p-rob3/protos/P-Rob3.proto
  src/webots/vrml/WbField.cpp
  src/webots/vrml/WbProtoModel.cpp
Labels: bug

#1857 Test World Update
  .github/workflows/test_suite.yml
  projects/robots/festo/robotino3/worlds/robotino3.wbt
Labels: enhancement

#1858 Fix memory management in Python RangeFinder.rangeImageGetDepth
  docs/reference/changelog-r2020.md
  resources/languages/python/controller.i
Labels: bug, crash

#1856 Disable Screen Specific Perspective Save
  src/install_scripts/bash_profile.mac
  src/install_scripts/bash_profile.windows
  src/install_scripts/bashrc.linux
  src/webots/app/WbPerspective.cpp
  src/webots/app/WbPerspective.hpp
  src/webots/gui/WbHtmlExportDialog.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbView3D.hpp
  src/webots/nodes/WbLight.cpp
  src/webots/nodes/utils/WbWorld.cpp
Labels: enhancement

#1864 FIx OSM Exporter Empty Road
  resources/osm_importer/webots_objects/road.py
Labels: bug

#1863 Fixed outline offset for boxes
  src/webots/nodes/WbBox.cpp
Labels: enhancement

#1865 Fix Display reset
  docs/reference/changelog-r2020.md
  docs/reference/display.md
  src/webots/nodes/WbDisplay.cpp
  src/webots/nodes/WbDisplay.hpp
  src/webots/nodes/WbImageTexture.cpp
Labels: bug, crash

#1873 Fix Chaining URDF Link Translations
  src/webots/nodes/WbTransform.cpp
Labels: bug

#1877 Fix Remaining WEBOTS_DISABLE_SAVE_PERSPECTIVE_ON_CLOSE
  src/webots/app/WbPerspective.cpp
Labels: cleanup

#1880 Fix runtime.ini Pathes
  projects/default/controllers/ros/runtime.ini
  projects/vehicles/controllers/ros_automobile/runtime.ini
Labels: bug

#1888 Improve MultiSense S21 internal names description
  docs/guide/camera-sensors.md
Labels: documentation, enhancement

#1890 Enhancement webots_ros installation instructions
  docs/guide/tutorial-8-using-ros.md
Labels: documentation

#1893 Fix Github Actions
  .github/workflows/test_suite.yml
Labels: bug

#1876 Move ros_python controller in webots_ros as extern controller
  docs/guide/ure.md
  docs/guide/using-ros.md
  docs/reference/changelog-r2020.md
  projects/languages/Makefile
  projects/languages/ros/controllers/ros_python/.gitignore
  projects/languages/ros/controllers/ros_python/Makefile
  projects/languages/ros/controllers/ros_python/README.md
  projects/languages/ros/controllers/ros_python/runtime.ini
  projects/languages/ros/webots_ros/CMakeLists.txt
  projects/languages/ros/webots_ros/README.md
  projects/languages/ros/webots_ros/launch/catch_the_bird.launch
  projects/languages/ros/webots_ros/launch/complete_test.launch
  projects/languages/ros/webots_ros/launch/e_puck_line.launch
  projects/languages/ros/webots_ros/launch/keyboard_teleop.launch
  projects/languages/ros/webots_ros/launch/panoramic_view_recorder.launch
  projects/languages/ros/webots_ros/launch/pioneer3at.launch
  projects/languages/ros/webots_ros/launch/robot_information_parser.launch
  projects/languages/ros/webots_ros/launch/webots_ros_python.launch
  projects/languages/ros/webots_ros/package.xml
  projects/languages/ros/webots_ros/plugins/robot_windows/info/info.html
  projects/languages/ros/webots_ros/plugins/robot_windows/info/info.js
  projects/languages/ros/webots_ros/scripts/ros_controller.py
  projects/languages/ros/webots_ros/scripts/ros_python.py
  projects/languages/ros/webots_ros/scripts/webots_launcher.py
  projects/languages/ros/webots_ros/src/keyboard_teleop.cpp
  projects/languages/ros/webots_ros/worlds/.catch_the_bird.wbproj
  projects/languages/ros/webots_ros/worlds/.complete_test.wbproj
  projects/languages/ros/webots_ros/worlds/.e-puck_line.wbproj
  projects/languages/ros/webots_ros/worlds/.keyboard_teleop.wbproj
  projects/languages/ros/webots_ros/worlds/.panoramic_view_recorder.wbproj
  projects/languages/ros/webots_ros/worlds/.pioneer3at.wbproj
  projects/languages/ros/webots_ros/worlds/.ros_python.wbproj
  projects/languages/ros/webots_ros/worlds/catch_the_bird.wbt
  projects/languages/ros/webots_ros/worlds/complete_test.wbt
  projects/languages/ros/webots_ros/worlds/e-puck_line.wbt
  projects/languages/ros/webots_ros/worlds/keyboard_teleop.wbt
  projects/languages/ros/webots_ros/worlds/panoramic_view_recorder.wbt
  projects/languages/ros/webots_ros/worlds/pioneer3at.wbt
  projects/languages/ros/webots_ros/worlds/ros_python.wbt
  projects/languages/ros/webots_ros/worlds/textures/floor.png
  projects/robots/universal_robots/controllers/universal_robots_ros/runtime.ini
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/CMakeLists.txt
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/README.md
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/launch/ur10e.launch
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/launch/ur3e.launch
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/launch/ur5e.launch
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/launch/ur_controller.launch
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/package.xml
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/scripts/joint_state_publisher.py
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/scripts/trajectory_follower.py
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/scripts/universal_robots_ros.py
  src/packaging/exist_in_projects.txt
  src/packaging/recurse_in_projects.txt
  tests/ros.sh
  tests/sources/test_license.py
  tests/sources/test_pep8.py
Labels: cleanup, enhancement

#1894 Merge master into develop
  .github/workflows/test_suite.yml
  docs/discord/development.md
  docs/discord/documentation.md
  docs/discord/technical-questions.md
  docs/guide/camera-sensors.md
Labels: bug

#1892 Fix invalid assertion in Display::removeImageTexture
  src/webots/nodes/WbDisplay.cpp
Labels: bug

#1899 Fix test Workflow
  .github/workflows/test_suite.yml
Labels: bug

#1889 Fix node passed to context menu
  docs/reference/changelog-r2020.md
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/scene_tree/WbTreeView.cpp
  src/webots/user_commands/WbContextMenuGenerator.cpp
  src/webots/user_commands/WbContextMenuGenerator.hpp
Labels: bug

#1897 Fix not updated PROTO.
  projects/objects/factory/conveyors/protos/ConveyorBelt.proto
  projects/objects/factory/conveyors/protos/ConveyorPlatform.proto
  projects/samples/robotbenchmark/inverted_pendulum/protos/InvertedPendulumBenchmark.proto
  projects/samples/robotbenchmark/visual_tracking/protos/VisualTrackingBenchmark.proto
  tests/protos/protos/TemplateRobot.proto
Labels: bug

#1900 Fix Perspective Assertion Failure
  src/webots/gui/WbMainWindow.cpp
Labels: bug

#1907 Small typo in change log
  docs/reference/changelog-r2020.md
Labels: cleanup

#1909 Fix Multisense S21 device name
  docs/guide/camera-sensors.md
Labels: documentation

#1908 Make wb_supervisor_movie_is_ready Function Immediate
  docs/reference/changelog-r2020.md
  docs/reference/supervisor.md
  src/lib/Controller/api/supervisor.c
  tests/api/controllers/supervisor_start_stop_movie/supervisor_start_stop_movie.c
Labels: enhancement

#1910 Added main sponsors of Webots for Automobile
  docs/automobile/introduction.md
Labels: documentation

#1911 Update introduction.md
  docs/automobile/introduction.md
Labels: documentation

#1912 Removed odd-looking double dots
  docs/automobile/introduction.md
Labels: documentation

#1913 Improve Spot World Description
  projects/robots/boston_dynamics/spot/worlds/spot.wbt
Labels: enhancement

#1914 Improve Supervsior Sample
  docs/guide/samples-devices.md
  docs/reference/changelog-r2020.md
  projects/samples/devices/controllers/sample_supervisor/sample_supervisor.c
Labels: enhancement

#1920 Fix Changelog
  docs/reference/changelog-r2020.md
Labels: enhancement

#1916 Fix supervisor field update.
  docs/reference/changelog-r2020.md
  src/lib/Controller/api/messages.h
  src/lib/Controller/api/robot.c
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbRobot.hpp
  tests/api/controllers/supervisor_field/supervisor_field.c
  tests/api/controllers/supervisor_node/supervisor_node.c
Labels: bug

#1927 Fix video recording with asynchronous controllers.
  docs/reference/changelog-r2020.md
  src/webots/gui/WbVideoRecorder.cpp
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbView3D.hpp
Labels: bug

#1928 Fix Webots<=>Controller Protocol
  src/lib/Controller/api/messages.h
  src/lib/Controller/api/remote_control.c
  src/lib/Controller/api/robot.c
Labels: bug

#1901 Update test_suite.yml
  .github/workflows/test_suite.yml
  projects/robots/softbank/nao/controllers/nao_soccer_supervisor/nao_soccer_supervisor.c
  src/lib/Controller/Makefile
  src/packaging/Makefile
  src/packaging/webots_distro.c
Labels: enhancement

#1929 Fix travis dependencies
  .travis.yml
Labels: enhancement

#1932 Fixed reproducibility documentation
  docs/guide/modeling.md
Labels: documentation

#1934 Fixed libController assertion failures in release mode
  src/lib/Controller/api/robot_private.h
Labels: bug

#1933 Fixed Background VRML Export.
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbBackground.cpp
Labels: bug

#1935 Fixed libController compilation dependencies
  src/lib/Controller/Makefile
Labels: bug

#1930 Improve Workflow to Upload 20.04 Release
  .github/workflows/test_suite.yml
Labels: enhancement

#1937 Fix set_commit_and_date_in_version.py
  src/packaging/set_commit_and_date_in_version.py
Labels: bug

#1938 Add missing python module to workflow
  .github/workflows/test_suite.yml
Labels: bug

#1879 Added correct joint limits
  docs/reference/changelog-r2020.md
  projects/devices/robotiq/protos/Robotiq3fGripper.proto
  projects/robots/universal_robots/controllers/ure_can_grasper/ure_can_grasper.c
  projects/robots/universal_robots/worlds/ure.wbt
Labels: enhancement

#1940 Improve publish_release Script
  src/packaging/publish_release.py
Labels: enhancement

#1941 Fix hinge2joint Documentation
  docs/reference/balljoint.md
  docs/reference/hinge2joint.md
Labels: bug, documentation

#1943 Fix typo in BallJoint doc
  docs/reference/balljoint.md
Labels: documentation

#1946 Fix publish_release script
  src/packaging/publish_release.py
Labels: bug

#1947 Fixed accelerometer measurements
  docs/reference/accelerometer.md
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbAccelerometer.cpp
Labels: bug

#1951 Update set_commit_and_date_in_version.py
  src/packaging/set_commit_and_date_in_version.py
Labels: bug

#1948 Fix macOS libController build
  src/lib/Controller/Makefile
Labels: bug

#1953 Fix Supervisor Add Force/Torque
  docs/reference/changelog-r2020.md
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  tests/api/controllers/supervisor_force_torque/supervisor_force_torque.c
Labels: bug

#1954 Fix Release Tag
  src/packaging/publish_release.py
Labels: bug

#1949 Rollback macOS Qt version.
  dependencies/Makefile.mac
  docs/reference/changelog-r2020.md
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/Automaton.cpp
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/Model.cpp
  resources/projects/libraries/qt_utils/motion_editor/Motion.cpp
  resources/projects/libraries/qt_utils/motion_editor/Pose.cpp
  src/install_scripts/qt_mac_installer.sh
  src/packaging/files_core.txt
  src/packaging/webots_distro.c
  src/webots/control/WbController.cpp
  src/webots/core/WbTemplateEngine.cpp
  src/webots/gui/WbStreamingServer.cpp
Labels: bug

#1950 Better accelerometer test
  tests/api/controllers/accelerometer/accelerometer.c
  tests/api/worlds/accelerometer.wbt
Labels: enhancement

#1925 Fix internal proto field flag in supervisor.c
  docs/reference/supervisor.md
  include/controller/c/webots/supervisor.h
  include/controller/cpp/webots/Node.hpp
  include/controller/cpp/webots/Supervisor.hpp
  lib/controller/matlab/mgenerate.py
  lib/controller/matlab/wb_supervisor_node_get_from_proto_def.m
  lib/controller/matlab/wb_supervisor_node_is_proto.m
  projects/default/controllers/ros/RosSupervisor.cpp
  projects/default/controllers/ros/RosSupervisor.hpp
  projects/default/controllers/ros/include/srv/node_is_proto.srv
  projects/default/controllers/ros/include/srv/supervisor_get_from_def.srv
  projects/languages/ros/webots_ros/src/complete_test.cpp
  resources/languages/cpp/Node.cpp
  resources/languages/cpp/Supervisor.cpp
  resources/languages/java/controller.i
  src/lib/Controller/Controller.def
  src/lib/Controller/api/supervisor.c
  src/webots/core/WbLanguage.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
  tests/api/controllers/supervisor_field/supervisor_field.c
  tests/api/controllers/supervisor_get_from_def/supervisor_get_from_def.c
  tests/api/worlds/supervisor_get_from_def.wbt
Labels: bug

#1955 Fix libController Makefile
  src/lib/Controller/Makefile
Labels: bug

#1952 Document insertion rules
  docs/reference/connector.md
  docs/reference/node-chart.md
Labels: documentation

#1957 Fixed crash on reverting the world while recording an animation
  docs/reference/changelog-r2020.md
  src/webots/engine/WbAnimationRecorder.cpp
Labels: crash

#1922 Hotfix unique id after regeneration
  docs/reference/changelog-r2020.md
  docs/reference/supervisor.md
  src/lib/Controller/api/messages.h
  src/lib/Controller/api/supervisor.c
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeOperations.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  src/webots/nodes/utils/WbTemplateManager.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
  tests/api/controllers/supervisor_field/supervisor_field.c
  tests/protos/controllers/template_node_id/template_node_id.c
  tests/protos/protos/TemplateRobot.proto
  tests/protos/worlds/template_node_id.wbt
Labels: bug, crash

#1919 Webots R2020b blog post
  docs/blog/Webots-2020-b-release.md
  docs/blog/images/appearances/Marble.thumbnail.png
  docs/blog/images/appearances/MetalStainlessSteelCable.thumbnail.png
  docs/blog/images/appearances/Parquetry_a.thumbnail.png
  docs/blog/images/appearances/Pavement_a.thumbnail.png
  docs/blog/images/appearances/PerforatedMetal.thumbnail.png
  docs/blog/images/appearances/Plastic_a.thumbnail.png
  docs/blog/images/appearances/SolarCell.thumbnail.png
  docs/blog/images/at-st-walker.jpg
  docs/blog/images/consoles.png
  docs/blog/images/p-rob3.jpg
  docs/blog/images/spot.jpg
  docs/blog/images/sprinter.jpg
  docs/blog/menu.md
  docs/guide/appearances.md
  docs/guide/images/appearances/BakelitePlastic_a.thumbnail.png
  docs/guide/images/appearances/BakelitePlastic_b.thumbnail.png
  docs/guide/images/appearances/CarpetFibers_a.thumbnail.png
  docs/guide/images/appearances/CarpetFibers_b.thumbnail.png
  docs/guide/images/appearances/CarpetFibers_c.thumbnail.png
  docs/guide/images/appearances/Grass_a.thumbnail.png
  docs/guide/images/appearances/Grass_b.thumbnail.png
  docs/guide/images/appearances/Grass_c.thumbnail.png
  docs/guide/images/appearances/Grass_d.thumbnail.png
  docs/guide/images/appearances/Leather_a.thumbnail.png
  docs/guide/images/appearances/Leather_b.thumbnail.png
  docs/guide/images/appearances/Leather_c.png
  docs/guide/images/appearances/Parquetry_b.thumbnail.png
  docs/guide/images/appearances/Parquetry_c.thumbnail.png
  docs/guide/images/appearances/Parquetry_d.thumbnail.png
  docs/guide/images/appearances/Pavement_b.thumbnail.png
  docs/guide/images/appearances/Pavement_c.thumbnail.png
  docs/guide/images/appearances/Pavement_d.thumbnail.png
  docs/guide/images/appearances/Pavement_e.thumbnail.png
  docs/guide/images/appearances/Pavement_f.thumbnail.png
  docs/guide/images/appearances/PerforatedMetal.png
  docs/guide/images/appearances/PerforatedMetal.thumbnail.png
  docs/guide/images/appearances/Plastic_a.png
  docs/guide/images/appearances/Plastic_b.png
  docs/guide/images/appearances/Rubber_a.thumbnail.png
  docs/guide/images/appearances/Rubber_b.thumbnail.png
  docs/guide/images/appearances/Soil_a.thumbnail.png
  docs/guide/images/appearances/Soil_b.thumbnail.png
  docs/guide/images/appearances/ThreadMetalPlate_a.thumbnail.png
  docs/guide/images/appearances/ThreadMetalPlate_b.thumbnail.png
  docs/guide/images/appearances/TireRubber_a.thumbnail.png
  docs/guide/images/appearances/TireRubber_b.thumbnail.png
  docs/reference/changelog-r2020.md
Labels: documentation

#1962 Fixed axis typographic convention
  docs/discord/development.md
  docs/discord/documentation.md
  docs/discord/technical-questions.md
  docs/guide/epuck.md
  docs/guide/object-solids.md
  docs/guide/robotis-op2.md
  docs/guide/tutorial-5-compound-solid-and-physics-attributes.md
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/reference/background.md
  docs/reference/box.md
  docs/reference/changelog-5.md
  docs/reference/changelog-8.md
  docs/reference/changelog-r2018.md
  docs/reference/compass.md
  docs/reference/cone.md
  docs/reference/connector.md
  docs/reference/cylinder.md
  docs/reference/elevationgrid.md
  docs/reference/emitter.md
  docs/reference/gyro.md
  docs/reference/inertialunit.md
  docs/reference/lidar.md
  docs/reference/lightsensor.md
  docs/reference/plane.md
  docs/reference/receiver.md
  docs/reference/touchsensor.md
  docs/reference/transform.md
  docs/reference/viewpoint.md
Labels: documentation

#1868 Fix various crashes related to PROTO template regenerator fields
  docs/reference/changelog-r2020.md
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbTemplateManager.cpp
  src/webots/nodes/utils/WbTemplateManager.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  tests/api/controllers/supervisor_set_hinge_position/supervisor_set_hinge_position.c
  tests/manual_tests/protos/TestFloor.proto
  tests/manual_tests/worlds/modify_proto_template_field.wbt
  tests/protos/controllers/modify_proto_template_field/.gitignore
  tests/protos/controllers/modify_proto_template_field/Makefile
  tests/protos/controllers/modify_proto_template_field/modify_proto_template_field.c
  tests/protos/controllers/template_parameter_toggle_from_supervisor/template_parameter_toggle_from_supervisor.c
  tests/protos/protos/TestRectangleArena.proto
  tests/protos/worlds/modify_proto_template_field.wbt
Labels: bug, crash

#1984 Fix unwanted new console after creating a movie.
  src/webots/gui/WbMainWindow.cpp
Labels: bug

#1988 Fix Python 2.7 ANSI Codes.
  resources/languages/python/controller.i
Labels: bug

#1987 Reverted manual changes on Discord pages
  docs/discord/development.md
  docs/discord/documentation.md
  docs/discord/technical-questions.md
Labels: cleanup

#1989 Fix E-Puck Robot-Window
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.c
Labels: bug

#1990 Update Worlds
  projects/samples/environments/factory/worlds/hall.wbt
  projects/vehicles/worlds/CH_Vens.wbt
  projects/vehicles/worlds/village_center.wbt
  projects/vehicles/worlds/village_realistic.wbt
  projects/vehicles/worlds/village_winter.wbt
Labels: cleanup

#1994 Fixed random triangle mesh collision detection bug
  docs/reference/changelog-r2020.md
  src/webots/nodes/WbTriangleMeshGeometry.cpp
  src/webots/nodes/WbTriangleMeshGeometry.hpp
  src/webots/nodes/utils/WbTriangleMesh.cpp
  src/webots/nodes/utils/WbTriangleMesh.hpp
Labels: bug

#1997 Update CH_Morges world
  projects/vehicles/worlds/CH_Morges.wbt
Labels: bug

#1998 Fix computing if node is internal to a proto
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
Labels: bug

#2003 Fix backwards compatibility
  src/webots/nodes/WbWorldInfo.cpp
  src/webots/vrml/WbParser.cpp
Labels: bug

#2004 Fixed accelerometer warning and return value
  src/webots/nodes/WbAccelerometer.cpp
  src/webots/nodes/WbAccelerometer.hpp
Labels: enhancement

#2005 Fix invalid texture paramter of TruckTrailer PROTO inserted by SumoInterface
  projects/default/controllers/sumo_supervisor/Objects.py
Labels: bug

#2000 Check for ikpy version in inverse_kinematic controller
  projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
Labels: enhancement

#2002 Fix various world errors and warnings
  projects/robots/neuronics/ipr/libraries/ipr/IPR.cpp
  projects/robots/saeon/controllers/vehicle_driver_altino/vehicle_driver_altino.py
  projects/samples/curriculum/controllers/beginner_better_collision_avoidance_algorithm/runtime.ini
  projects/samples/curriculum/controllers/beginner_blinking_e-puck/runtime.ini
  projects/samples/curriculum/controllers/beginner_e-puck_dance/runtime.ini
  projects/samples/curriculum/controllers/beginner_finite_state_machine/runtime.ini
  projects/samples/curriculum/controllers/beginner_linear_camera/runtime.ini
  projects/samples/curriculum/controllers/beginner_move_your_e-puck/runtime.ini
  projects/samples/curriculum/controllers/beginner_rally/runtime.ini
  projects/samples/curriculum/controllers/novice_remain_in_shadow/runtime.ini
  projects/samples/curriculum/controllers/novice_train/runtime.ini
Labels: bug

#2014 Fixed Python 3.8 vehicle library which was broken on Windows
  projects/default/libraries/vehicle/python/vehicle.i
  projects/robots/robotis/darwin-op/libraries/python/managers.i
  projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/runtime.ini
Labels: bug

#2011 Add instructions to install rosdep
  docs/guide/tutorial-8-using-ros.md
Labels: documentation

#2017 Fixed ROS worlds
  projects/languages/ros/webots_ros/worlds/catch_the_bird.wbt
  projects/languages/ros/webots_ros/worlds/complete_test.wbt
  projects/languages/ros/webots_ros/worlds/e-puck_line.wbt
  projects/languages/ros/webots_ros/worlds/keyboard_teleop.wbt
  projects/languages/ros/webots_ros/worlds/panoramic_view_recorder.wbt
  projects/languages/ros/webots_ros/worlds/pioneer3at.wbt
  projects/languages/ros/webots_ros/worlds/ros_python.wbt
Labels: bug

#2019 Fixed wrong conversion from WbVector3 to WbVector4
  docs/reference/changelog-r2020.md
  src/webots/gui/WbDragTransformEvent.cpp
Labels: bug

#2018 Fixed Makefile of libController
  src/lib/Controller/Makefile
Labels: bug

#2016 Add auto-cancel for source test workflow
  .github/workflows/test_suite.yml
  .github/workflows/tests_sources.yml
Labels: enhancement

#2013 Fix Laser DistanceSensors
  src/webots/wren/WbWrenRenderingContext.cpp
  src/webots/wren/WbWrenRenderingContext.hpp
Labels: bug

#2006 Fix supervisor.getSelf().remove() crash
  docs/reference/changelog-r2020.md
  docs/reference/supervisor.md
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  tests/api/controllers/supervisor_import_remove/supervisor_import_remove.c
  tests/api/controllers/supervisor_remove_self/.gitignore
  tests/api/controllers/supervisor_remove_self/Makefile
  tests/api/controllers/supervisor_remove_self/supervisor_remove_self.c
  tests/api/worlds/supervisor_import_remove.wbt
Labels: crash

#2020 Attempt to fix appveyor build
  .appveyor-build-tag.yml
  .appveyor-build.yml
  .appveyor-test-sources-scheduled.yml
Labels: bug

#2008 Linux Installation scripts
  .github/workflows/test_suite.yml
  docs/guide/installation-procedure.md
  src/install_scripts/linux_compilation_dependencies.sh
  src/install_scripts/linux_optional_compilation_dependencies.sh
  src/install_scripts/linux_runtime_dependencies.sh
Labels: cleanup, enhancement

#2025 Fixed stability of motor sample
  projects/samples/devices/controllers/motor/motor.c
  projects/samples/devices/worlds/motor.wbt
Labels: enhancement

#2028 Fix Robotino Joint Anchors.
  projects/robots/festo/robotino3/protos/Robotino3.proto
Labels: bug

#2030 Update latest Ubuntu LTS in documentation
  docs/guide/installation-procedure.md
  docs/guide/system-requirements.md
  docs/guide/using-python.md
  docs/reference/changelog-r2020.md
Labels: documentation

#2032 Updated release date
  docs/blog/Webots-2020-b-release.md
  docs/reference/changelog-r2020.md
Labels: documentation

#2001 Python 3 issues on macOS
  docs/guide/using-python.md
  src/webots/control/WbController.cpp
  src/webots/control/WbLanguageTools.cpp
  src/webots/control/WbLanguageTools.hpp
Labels: bug

#2050 Fix Windows Extern Controller Doc
  docs/guide/running-extern-robot-controllers.md
Labels: bug

#2056 Fix Radar Relative Speed Test
  tests/api/controllers/radar_relative_speed/radar_relative_speed.c
Labels: bug
