Repository cyberbotics/webots, pull requests merged in 2021-07, with the labels that each got.

#3237 Fix a controller crash when changing the controller
  docs/reference/changelog-r2021.md
  src/webots/control/WbControlledWorld.cpp
  src/webots/control/WbController.cpp
Labels: bug, test suite

#3260 Calibrate the IPR1 collaboration example
  projects/robots/neuronics/ipr/controllers/ipr1_collaboration/ipr1_collaboration.cpp
Labels: bug

#3263 Fix regular expression not supporting script tag attributes
  src/webots/gui/WbRobotWindow.cpp
Labels: bug, test suite

#3256 Remove deprecated functions from samples
  projects/samples/howto/cylinder_stack/controllers/contact_points_supervisor/contact_points_supervisor.c
  projects/samples/robotbenchmark/highway_driving/controllers/highway_driving_benchmark/highway_driving_benchmark.py
  projects/samples/robotbenchmark/obstacle_avoidance/controllers/supervisor/supervisor.py
Labels: cleanup

#3264 Update samples devices documentation
  docs/guide/images/samples/altimeter.png
  docs/guide/images/samples/altimeter.thumbnail.jpg
  docs/guide/images/samples/camera_segmentation.png
  docs/guide/images/samples/camera_segmentation.thumbnail.jpg
  docs/guide/samples-devices.md
Labels: documentation

#3272 Fix errors in settings tab of generic robot window
  resources/projects/plugins/robot_windows/generic/window_manager.js
Labels: bug

#3297 Fixed MATLAB interface
  lib/controller/matlab/launcher.m
Labels: bug

#3303 Fix texture URL in OSM importer
  projects/vehicles/worlds/CH_Morges.wbt
  projects/vehicles/worlds/city.wbt
  projects/vehicles/worlds/city_night.wbt
  projects/vehicles/worlds/city_traffic.wbt
  projects/vehicles/worlds/textures/road_line_triangle.png
  projects/vehicles/worlds/village.wbt
  projects/vehicles/worlds/village_center.wbt
  projects/vehicles/worlds/village_realistic.wbt
  resources/osm_importer/config.ini
  resources/osm_importer/elevation.py
  resources/osm_importer/utils/misc_utils.py
  resources/osm_importer/webots_objects/barrier.py
  resources/osm_importer/webots_objects/road.py
Labels: bug

#3314 Fix bad url for robostadium net
  projects/objects/robotstadium/protos/RobotstadiumGoal.proto
Labels: bug

#3306 Fixed bad texture URL
  projects/samples/robotbenchmark/humanoid_marathon/worlds/humanoid_marathon.wbt
Labels: bug

#3308 Fixed bad texture URLs
  docs/guide/object-buildings.md
  projects/objects/buildings/protos/RandomBuilding.proto
  projects/objects/buildings/protos/SimpleBuilding.proto
  resources/osm_importer/webots_objects/building.py
Labels: bug

#3315 Fixed discrepancy between guide and reference manual
  docs/reference/index.md
Labels: documentation

#3316 Adjust parameters of guided tour
  projects/guided_tour.txt
  projects/robots/k-team/khepera3/worlds/khepera3_gripper.wbt
  projects/robots/universal_robots/worlds/ure.wbt
Labels: bug

#3317 Recommend for all users installation on Windows
  scripts/packaging/webots_distro.c
Labels: cleanup

#3320 Add missing devices in guided tour
  projects/guided_tour.txt
Labels: enhancement

#3313 Drop Python 2.7
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  docs/guide/controller-programming.md
  docs/guide/running-extern-robot-controllers.md
  docs/guide/using-python.md
  lib/controller/.gitignore
  projects/default/libraries/vehicle/Makefile
  projects/robots/robotis/darwin-op/libraries/Makefile
  scripts/install/bash_profile.windows
  scripts/install/linux_compilation_dependencies.sh
  scripts/packaging/files_core.txt
  src/controller/Makefile
  src/controller/python/Makefile
  src/webots/control/WbLanguageTools.cpp
Labels: cleanup, test distribution, test ros, test suite

#3318 Fix shapely module error in `highway_driving_benchmark.wbt`
  projects/samples/robotbenchmark/highway_driving/controllers/highway_driving_benchmark/highway_driving_benchmark.py
Labels: bug

#3328 Update fabtino.meta.json
  docs/guide/scenes/fabtino/fabtino.meta.json
Labels: cleanup

#3325 Fix names in proto
  docs/guide/scenes/fabtino/fabtino.meta.json
  projects/robots/rec/fabtino/protos/Fabtino.proto
Labels: bug

#3334 Fixed missing binary controller
  projects/samples/howto/Makefile
Labels: bug

#3335 Update Using ROS instructions
  docs/guide/tutorial-8-using-ros.md
Labels: cleanup

#3323 Fix nao room demo
  projects/robots/softbank/nao/worlds/nao_room.wbt
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/utils/WbDownloader.cpp
  src/webots/nodes/utils/WbDownloader.hpp
Labels: bug

#3319 Correction of Sick S300 Lidar parameters
  docs/blog/images/sick_s300.png
  docs/blog/images/sick_s300.thumbnail.png
  docs/guide/images/sensors/sick_s300.png
  docs/guide/images/sensors/sick_s300.thumbnail.png
  docs/guide/images/sensors/sick_s300_icon.png
  projects/devices/sick/protos/SickS300.proto
  projects/devices/sick/protos/icons/SickS300.png
  projects/devices/sick/protos/meshes/sick_s300_black.dae
  projects/devices/sick/protos/meshes/sick_s300_glass.dae
  scripts/icon_studio/controllers/icon_creator/objects.json
Labels: enhancement

#3340 Add missing howto in docs
  docs/guide/images/samples/console.png
  docs/guide/samples-howto.md
  projects/samples/howto/Makefile
  projects/samples/howto/enu_coordinate_system/controllers/four_wheels/.gitignore
  projects/samples/howto/enu_coordinate_system/controllers/four_wheels/Makefile
  projects/samples/howto/enu_coordinate_system/controllers/four_wheels/four_wheels.c
  projects/samples/howto/enu_coordinate_system/worlds/.enu_coordinate_system.wbproj
  projects/samples/howto/enu_coordinate_system/worlds/enu_coordinate_system.wbt
  scripts/converter/convert_all_worlds.py
Labels: documentation

#3343 Update linux_optional_compilation_dependencies.sh
  scripts/install/linux_optional_compilation_dependencies.sh
Labels: cleanup

#3339 Fix texture change controller
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  scripts/packaging/Makefile
  scripts/packaging/Makefile.controllers
  scripts/packaging/update_urls.py
Labels: bug

#3338 Replace default controller for `thymio2_pen.wbt` and `thymio2_ball.wbt`
  projects/robots/mobsya/thymio/worlds/thymio2_ball.wbt
  projects/robots/mobsya/thymio/worlds/thymio2_pen.wbt
Labels: bug

#3344 Fixed wren compilation warnings on Linux
  src/wren/PbrMaterial.cpp
  src/wren/PhongMaterial.cpp
Labels: cleanup

#3347 Fixed GL_INVALID_OPERATION error in robot window
  resources/projects/plugins/robot_windows/generic/timeplot_widget.js
Labels: bug

#3322 Fix `sumo_interface_example.wbt`
  src/controller/python/controller.i
Labels: bug, test ros, test suite

#3345 Fix pointlight reset
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbPointLight.cpp
  src/webots/nodes/WbPointLight.hpp
Labels: bug, test suite

#3346 fix night mode on windows
  scripts/packaging/files_core.txt
Labels: enhancement

#3348 Fix javascript construct
  projects/samples/robotbenchmark/highway_driving/plugins/robot_windows/highway_driving/highway_driving.html
  projects/samples/robotbenchmark/humanoid_marathon/plugins/robot_windows/humanoid_marathon/humanoid_marathon.html
  projects/samples/robotbenchmark/humanoid_sprint/plugins/robot_windows/humanoid_sprint/humanoid_sprint.html
  projects/samples/robotbenchmark/inverted_pendulum/plugins/robot_windows/inverted_pendulum/inverted_pendulum.html
  projects/samples/robotbenchmark/maze_runner/plugins/robot_windows/maze_runner/maze_runner.html
  projects/samples/robotbenchmark/obstacle_avoidance/plugins/robot_windows/obstacle_avoidance/obstacle_avoidance.html
  projects/samples/robotbenchmark/pick_and_place/plugins/robot_windows/pick_and_place/pick_and_place.html
  projects/samples/robotbenchmark/pit_escape/plugins/robot_windows/pit_escape/pit_escape.html
  projects/samples/robotbenchmark/robot_programming/plugins/robot_windows/robot_programming/robot_programming.html
  projects/samples/robotbenchmark/square_path/plugins/robot_windows/square_path/square_path.html
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/pan_tilt_camera_view/pan_tilt_camera_view.html
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/visual_tracking/visual_tracking.html
  projects/samples/robotbenchmark/wall_following/plugins/robot_windows/wall_following/wall_following.html
Labels: bug

#3342 add information about cache size used
  src/webots/gui/WbPreferencesDialog.cpp
Labels: enhancement

#3350 Fix cabinet `primaryAppearance`
  projects/objects/cabinet/protos/Cabinet.proto
  projects/objects/cabinet/protos/CabinetDoor.proto
Labels: bug

#3351 "Fix" floor distorsion
  projects/samples/howto/inverted_pendulum/worlds/inverted_pendulum.wbt
Labels: enhancement, wontfix

#3349 Improve Urls handling
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/nodes/utils/WbDownloader.cpp
Labels: enhancement, test suite

#3356 Fixed Tinkerbots demos
  projects/robots/kinematics/tinkerbots/worlds/braitenberg.wbt
  projects/robots/kinematics/tinkerbots/worlds/vision_car.wbt
Labels: bug

#3359 Fix nightly urls
  scripts/packaging/Makefile
Labels: bug

#3360 Changed arm that respond to force
  projects/robots/robotis/darwin-op/controllers/symmetry_matlab/symmetry_matlab.m
Labels: cleanup

#3355 Fix Cabinet doors and drawers physics
  projects/objects/cabinet/protos/CabinetDoor.proto
  projects/objects/cabinet/protos/CabinetDrawer.proto
  projects/robots/softbank/nao/worlds/nao_room.wbt
Labels: bug, test world update

#3361 Added a warning when opening old worlds relying possibly on local resources
  docs/reference/changelog-r2021.md
  src/webots/vrml/WbTokenizer.cpp
Labels: documentation

#3362 Cleanup useless/broken jquery includes
  src/webots/gui/WbRobotWindow.cpp
Labels: cleanup

#3363 Cleanup JQuery in robot windows
  projects/samples/robotbenchmark/robot_programming/plugins/robot_windows/robot_programming/robot_programming.html
Labels: cleanup

#3365 Reset scroll when changing tab in Robot Window
  resources/projects/plugins/robot_windows/generic/window_manager.js
Labels: cleanup

#3366 Add instructions for force3d_sensor.wbt
  projects/samples/devices/controllers/force3d_sensor/force3d_sensor.c
  projects/samples/devices/worlds/force3d_sensor.wbt
Labels: cleanup

#3364 Fix botstudio crash
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/e-puck/EPuckFacade.cpp
Labels: crash

#3368 Fix relocation of Skins
  src/webots/editor/WbProjectRelocationDialog.cpp
Labels: bug

#3367 Fixed restart of Webots on Windows
  docs/reference/changelog-r2021.md
  src/webots/gui/WbGuiApplication.cpp
  src/webots/launcher/launcher.c
Labels: bug

#3370 Fixed robot window javascript error on reset
  resources/web/local/webots.js
Labels: bug

#3371 Fixed deletion of robot window on reset (Linux and macOS)
  src/webots/gui/WbRobotWindow.cpp
Labels: bug

#3374 Fix incorrect cleaning of WbLights
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbLight.cpp
Labels: bug, crash, test suite

#3375 fix crash controllers
  src/controller/c/supervisor.c
  src/webots/control/WbController.cpp
Labels: bug, regression, test suite

#3373 Fix disabled proto test
  tests/protos/controllers/derived_proto_automatic_IS_redirection/derived_proto_automatic_IS_redirection.c
  tests/protos/controllers/mixed_template_derived_proto/mixed_template_derived_proto.c
  tests/protos/controllers/modify_proto_template_field/modify_proto_template_field.c
  tests/protos/controllers/nested_mixed_template_proto/nested_mixed_template_proto.c
  tests/protos/controllers/proto_nested_parameter/proto_nested_parameter.c
  tests/protos/controllers/proto_regeneration_multiple_instances/proto_regeneration_multiple_instances.c
  tests/protos/controllers/template_deterministic/template_deterministic.c
  tests/protos/controllers/template_nested_slot_container/template_nested_slot_container.c
  tests/protos/controllers/template_node_id/template_node_id.c
  tests/protos/controllers/template_parameter_toggle_from_supervisor/template_parameter_toggle_from_supervisor.c
  tests/protos/controllers/template_proto_follow_solid/template_proto_follow_solid.c
  tests/protos/controllers/template_robot_regenerated/template_robot_regenerated.c
  tests/protos/controllers/template_viewpoint_proto/template_viewpoint_proto.c
  tests/protos/worlds/derived_proto_automatic_IS_redirection_lua.wbt
  tests/protos/worlds/mixed_template_derived_proto.wbt
  tests/protos/worlds/mixed_template_derived_proto_lua.wbt
  tests/protos/worlds/modify_proto_template_field_lua.wbt
  tests/protos/worlds/nested_mixed_template_proto_lua.wbt
  tests/protos/worlds/proto_nested_parameter.wbt
  tests/protos/worlds/proto_nested_parameter_lua.wbt
  tests/protos/worlds/proto_regeneration_multiple_instances.wbt
  tests/protos/worlds/proto_regeneration_multiple_instances_lua.wbt
  tests/protos/worlds/template_deterministic.wbt
  tests/protos/worlds/template_deterministic_lua.wbt
  tests/protos/worlds/template_direct_nested_lua.wbt
  tests/protos/worlds/template_nested_slot_container.wbt
  tests/protos/worlds/template_nested_slot_container_lua.wbt
  tests/protos/worlds/template_node_id.wbt
  tests/protos/worlds/template_node_id_lua.wbt
  tests/protos/worlds/template_parameter_toggle_from_supervisor.wbt
  tests/protos/worlds/template_parameter_toggle_from_supervisor_lua.wbt
  tests/protos/worlds/template_proto_follow_solid.wbt
  tests/protos/worlds/template_proto_follow_solid_lua.wbt
  tests/protos/worlds/template_proto_with_nested_template_parameter_1_lua.wbt
  tests/protos/worlds/template_proto_with_nested_template_parameter_2_lua.wbt
  tests/protos/worlds/template_proto_with_nested_template_parameter_3_lua.wbt
  tests/protos/worlds/template_proto_with_template_parameter_1_lua.wbt
  tests/protos/worlds/template_proto_with_template_parameter_2_lua.wbt
  tests/protos/worlds/template_robot_regenerated.wbt
  tests/protos/worlds/template_robot_regenerated_lua.wbt
  tests/protos/worlds/template_viewpoint_proto.wbt
  tests/protos/worlds/template_viewpoint_proto_lua.wbt
Labels: test suite, test suite issue

#3378 Improved test suite scripts
  tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py
  tests/test_suite.py
Labels: test suite, test suite issue

#3379 Add warning for Safari
  resources/web/wwi/webots.js
Labels: enhancement

#3376 Fix Guided Tour world canceling and switch causing crash
  docs/reference/changelog-r2021.md
  src/webots/gui/WbGuidedTour.cpp
Labels: bug, crash, test suite

#3380 fix repo.txt when ssh
  scripts/get_git_info/get_git_info.sh
Labels: bug

#3230 Fix error in Lidar / RangeFinder measurement when hitting an edge
  docs/reference/changelog-r2021.md
  resources/wren/shaders/merge_spherical.frag
  src/webots/wren/WbWrenCamera.cpp
  src/webots/wren/WbWrenShaders.cpp
  tests/api/controllers/range_finder_horizontal_spherical_projection/range_finder_horizontal_spherical_projection.c
Labels: bug, test suite

#3387 Improve python example
  projects/languages/python/controllers/driver/common.py
  projects/languages/python/controllers/driver/driver.py
  projects/languages/python/controllers/slave/runtime.ini
  projects/languages/python/controllers/slave/slave.py
Labels: enhancement

#3390 Fixed P-Rob3 motor names
  projects/robots/fp_robotics/p-rob3/controllers/p-rob3/p-rob3.c
  projects/robots/fp_robotics/p-rob3/protos/P-Grip.proto
  projects/robots/fp_robotics/p-rob3/protos/P-Rob3.proto
Labels: cleanup

#3388 Disable building of packages on develop
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows_develop.yml
  .github/workflows/tests_sources.yml
Labels: cleanup

#3393 Fix prob3 test
  tests/api/controllers/robot_urdf/prob3_reference.urdf
Labels: bug, test suite

#3391 Fix bug sumo
  src/webots/nodes/utils/WbDownloader.cpp
Labels: bug, crash, test suite

#3399 Reverts #3388
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows_develop.yml
  .github/workflows/tests_sources.yml
Labels: cleanup

#3385 Fix memory problem with Lidar point cloud
  src/controller/c/lidar.c
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/WbLidar.hpp
Labels: bug, test suite

#3389 Acquire the python GIL for all functions except Robot.step()
  src/controller/python/controller.i
Labels: bug

#3402 Fix mac pythonpath
  docs/reference/changelog-r2021.md
  src/webots/control/WbLanguageTools.cpp
  src/webots/control/WbLanguageTools.hpp
Labels: bug

#3404 Sanitize controller name in MATLAB launcher
  docs/reference/changelog-r2021.md
  lib/controller/matlab/launcher.m
Labels: bug

#3394 Fix `BallJoint` reset
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbHinge2Joint.cpp
  tests/physics/controllers/ball_joint_reset/.gitignore
  tests/physics/controllers/ball_joint_reset/Makefile
  tests/physics/controllers/ball_joint_reset/ball_joint_reset.c
  tests/physics/worlds/ball_joint_reset.wbt
Labels: bug, test ros, test suite

#3408 Added Niryo Ned splash screen
  resources/images/splash_images/ned.jpg
Labels: enhancement

#3413 Added explanation about extern controllers and runtime.ini file
  docs/guide/running-extern-robot-controllers.md
Labels: documentation

#3407 Fix HighwaySign proto
  docs/reference/changelog-r2021.md
  projects/objects/traffic/protos/HighwaySign.proto
Labels: bug

#3412 solve thread hanging after webots process finishes
  docs/reference/changelog-r2021.md
  resources/web/server/simulation_server.py
Labels: bug

#3415 Fixed issues with generic robot window
  src/controller/python/controller.i
Labels: bug

#3417 Adjust installation instructions for tarball
  docs/guide/installation-procedure.md
Labels: documentation

#3416 Fix pen evaporation
  projects/samples/devices/controllers/pen/pen.c
  src/controller/c/pen.c
  src/webots/nodes/WbPen.cpp
  src/webots/nodes/utils/WbPaintTexture.cpp
  tests/api/controllers/distance_sensor_infra-red/distance_sensor_infra-red.c
Labels: bug, test suite

#3431 Fix `get_the_candies.wbt`
  projects/robots/softbank/nao/worlds/get_the_candies.wbt
Labels: cleanup

#3428 fix assets downloads on copy
  src/webots/nodes/utils/WbDownloader.cpp
Labels: bug, test suite

#3432 Remove restriction for Robotino from docs
  docs/guide/robotino3.md
Labels: documentation

#3433 Add the MoveIt dependency to documentation
  docs/guide/tutorial-8-using-ros.md
Labels: documentation

#3427 Removed path to node.js and cleaned-up
  scripts/install/msys.sh
Labels: cleanup

#3439 Add ROS and snap usage documentation
  docs/guide/tutorial-8-using-ros.md
Labels: documentation

#3449 Fix robot window linking with an external Python controller
  docs/guide/running-extern-robot-controllers.md
  resources/projects/plugins/robot_windows/generic/Makefile
  src/controller/python/controller.i
Labels: bug, test distribution

#3452 Fix debug leftover in animation export
  src/webots/nodes/WbImageTexture.cpp
Labels: bug

#3455 Released in Master
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/tests/test_md_files.py
Labels: documentation

#3453 shape.md, appearance.md: link to PBRAppearance
  docs/reference/shape.md
Labels: documentation

#3444 Fix typo in the doc
  docs/guide/tutorial-8-using-ros.md
Labels: documentation

#3454 Update appearance.md
  docs/reference/appearance.md
Labels: documentation

#3458 Fix default url branch
  resources/web/wwi/Parser.js
Labels: bug

#3466 Merge master into released
  resources/web/wwi/Parser.js
Labels: test suite

#3456 Fix imageTextures urls format
  src/webots/nodes/WbImageTexture.cpp
Labels: bug

#3436 Fix range finder with fully transparent objects
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbGeometry.cpp
  src/webots/nodes/WbGeometry.hpp
  src/webots/nodes/WbShape.cpp
Labels: enhancement, test suite

#3464 Fix new cppcheck errors appeared on macOS
  projects/default/libraries/vehicle/c/driver/src/driver.c
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/RobotObjectFactory.hpp
  resources/projects/libraries/qt_utils/widgets/LidarWidget.cpp
  src/controller/c/robot.c
Labels: cleanup, test sources, test suite

#3469 Fix branch.txt creation
  scripts/get_git_info/get_git_info.sh
Labels: bug

#3474 Merge master into develop
  docs/reference/changelog-r2021.md
  projects/default/libraries/vehicle/c/driver/src/driver.c
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/RobotObjectFactory.hpp
  resources/projects/libraries/qt_utils/widgets/LidarWidget.cpp
  scripts/get_git_info/get_git_info.sh
  scripts/new_version/new_version.sh
  src/controller/c/robot.c
  src/webots/nodes/WbGeometry.cpp
  src/webots/nodes/WbGeometry.hpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbShape.cpp
Labels: test ros, test suite

#3478 Don't publish the libcontroller if it hasn't changed since yesterday
  scripts/packaging/sync_controller_lib.sh
Labels: bug

#3240 Fix mass computation when inserting a Physics node
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbSolid.cpp
Labels: bug, test suite

#3482 Fix icon_studio controller with Pillow >= 7.1.0
  scripts/icon_studio/controllers/icon_creator/icon_creator.py
Labels: bug

#3484 Fix publish_release.py script
  scripts/packaging/publish_release.py
Labels: bug

#3398 Enhancement project relocation
  src/webots/editor/WbBuildEditor.cpp
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/editor/WbProjectRelocationDialog.hpp
Labels: cleanup, enhancement, test suite

#3461 Update robot.md
  docs/reference/robot.md
Labels: documentation

#3490 Cleanup Lidar isRotating
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/WbLidar.hpp
Labels: cleanup, test suite

#3492 Fix github urls on released
  docs/guide/samples-howto.md
  docs/js/showdown-extensions.js
Labels: bug, documentation

#3494 `ros` default controller: based sleep on WallTime instead of simulated time.
  projects/default/controllers/ros/Ros.cpp
Labels: bug, test ros

#3501 Update samples-howto.md
  docs/guide/samples-howto.md
Labels: documentation

#3441 Replaced memcpy by glGetBufferSubData in FrameBuffer
  src/wren/FrameBuffer.cpp
Labels: cleanup, test ros, test suite

#3499 LIDAR point cloud generation optimisation
  src/webots/nodes/WbLidar.cpp
Labels: optimization, test suite

#3507 Create Debian package from Ubuntu 20.04
  docs/guide/installation-procedure.md
  docs/guide/tutorial-8-using-ros.md
  scripts/packaging/webots_distro.c
Labels: bug, cleanup, test distribution

#3506 Python in virtual env, MacOS
  src/webots/control/WbLanguageTools.cpp
Labels: bug, regression, test suite

#3480 Clean code related to Ubuntu 16.04
  dependencies/Makefile.linux
  docs/guide/system-requirements.md
  docs/reference/changelog-r2021.md
  resources/projects/libraries/qt_utils/gui/MainWindow.cpp
  scripts/install/linux_runtime_dependencies.sh
  scripts/install/linux_test_dependencies.sh
  scripts/packaging/Makefile
  scripts/packaging/webots_distro.c
  src/webots/user_commands/WbContextMenuGenerator.cpp
Labels: cleanup

#3511 Publish libController C++ files
  scripts/packaging/sync_controller_lib.sh
Labels: enhancement, test distribution

#3517 TouchSensor to FLU
  docs/reference/images/touchsensor_force.png
  docs/reference/touchsensor.md
  projects/samples/devices/worlds/force_sensor.wbt
  src/webots/nodes/WbTouchSensor.cpp
  tests/api/worlds/robot_multiple_step.wbt
  tests/api/worlds/touch_sensor_force.wbt
Labels: enhancement, test ros, test suite

#3512 Fixed start of Webots from Windows cmd.exe
  docs/reference/changelog-r2021.md
  src/webots/Makefile
  src/webots/launcher/launcher.c
Labels: bug, test distribution

#3518 Connector to FLU
  docs/reference/connector.md
  docs/reference/images/connector_alignment.png
  docs/reference/images/connector_axes.png
  projects/robots/epfl/biorob/protos/Yamor.proto
  projects/samples/devices/worlds/connector.wbt
  src/webots/nodes/WbConnector.cpp
  src/webots/nodes/WbConnector.hpp
  tests/physics/worlds/connector_detach.wbt
  tests/physics/worlds/connector_static_autolock.wbt
Labels: enhancement, test ros, test suite

#3526 Cleanup FLU connector test
  tests/physics/worlds/connector_static_autolock.wbt
Labels: cleanup
