Repository cyberbotics/webots, pull requests merged in 2021-08, with the labels that each got.

#3527 Add the changelog entry about PR #3499
  docs/reference/changelog-r2021.md
Labels: documentation

#3528 Fixed Windows PATH setting
  scripts/install/msys.sh
Labels: bug

#3522 Fix crash when contact points of a PROTO are requested
  docs/reference/changelog-r2021.md
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  tests/api/controllers/center_of_mass_and_contact_points/center_of_mass_and_contact_points.c
  tests/api/worlds/center_of_mass_and_contact_points.wbt
Labels: bug, test suite

#3493 Change Lidar orientation to FLU
  docs/reference/images/lidar.png
  docs/reference/images/lidar.thumbnail.png
  docs/reference/lidar.md
  projects/robots/robotis/turtlebot/worlds/turtlebot3_burger.wbt
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/WbLidar.hpp
  src/webots/wren/WbWrenCamera.cpp
  src/webots/wren/WbWrenCamera.hpp
  tests/api/worlds/lidar_rotating.wbt
  tests/api/worlds/lidar_vs_range_finder.wbt
Labels: enhancement, test ros, test suite

#3532 Add note about coupled-motor usage in differentials
  docs/reference/motor.md
Labels: documentation

#3496 Change Radar orientation to FLU
  docs/reference/images/radar.png
  docs/reference/images/radar.thumbnail.png
  docs/reference/radar.md
  projects/samples/devices/worlds/radar.wbt
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbCamera.hpp
  src/webots/nodes/WbRadar.cpp
  src/webots/nodes/utils/WbObjectDetection.cpp
  src/webots/nodes/utils/WbObjectDetection.hpp
  tests/api/controllers/radar_target_merging/radar_target_merging.c
  tests/api/worlds/camera_recognition.wbt
  tests/api/worlds/radar_frustum.wbt
  tests/api/worlds/radar_occlusion.wbt
  tests/api/worlds/radar_relative_speed.wbt
  tests/api/worlds/radar_target_merging.wbt
  tests/physics/worlds/dynamic_radar_rays.wbt
  tests/physics/worlds/static_radar_rays.wbt
Labels: enhancement, test suite, test world update

#3520 Fix robotbenchmark robot windows
  projects/samples/robotbenchmark/humanoid_marathon/plugins/robot_windows/humanoid_marathon/humanoid_marathon.html
  projects/samples/robotbenchmark/humanoid_sprint/plugins/robot_windows/humanoid_sprint/humanoid_sprint.html
  projects/samples/robotbenchmark/inverted_pendulum/plugins/robot_windows/inverted_pendulum/inverted_pendulum.html
  projects/samples/robotbenchmark/inverted_pendulum/plugins/robot_windows/inverted_pendulum/inverted_pendulum.js
  projects/samples/robotbenchmark/obstacle_avoidance/plugins/robot_windows/obstacle_avoidance/obstacle_avoidance.html
  projects/samples/robotbenchmark/pick_and_place/plugins/robot_windows/pick_and_place/pick_and_place.html
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/visual_tracking/visual_tracking.html
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/visual_tracking/visual_tracking.js
  src/webots/gui/WbWebPage.cpp
  src/webots/gui/WbWebPage.hpp
Labels: bug, test suite

#3537 Fix matrix to quaternion conversion
  src/webots/maths/WbQuaternion.hpp
Labels: bug, crash, test suite

#3536 Add a figure for roll/tilt/pan axes
  docs/reference/camera.md
  docs/reference/images/roll-tilt-pan.png
Labels: documentation

#3530 Hotfix shift+left drag
  docs/reference/changelog-r2021.md
  src/webots/gui/WbDragTransformEvent.cpp
  src/webots/gui/WbDragTransformEvent.hpp
Labels: bug, test suite

#3546 Update on calculation of front_speed_sum
  docs/reference/changelog-r2021.md
  projects/default/libraries/vehicle/c/driver/src/driver.c
Labels: bug

#3538 Convert the Viewpoint to FLU
  docs/reference/billboard.md
  docs/reference/images/viewpoint.png
  docs/reference/images/viewpoint.thumbnail.png
  docs/reference/viewpoint.md
  resources/nodes/Viewpoint.wrl
  src/webots/app/WbPhysicsVectorRepresentation.cpp
  src/webots/gui/WbDragTransformEvent.cpp
  src/webots/gui/WbDragViewpointEvent.cpp
  src/webots/gui/WbView3D.cpp
  src/webots/maths/WbQuaternion.hpp
  src/webots/maths/WbRotation.cpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/wren/WbCoordinateSystem.cpp
Labels: feature, test suite

#3548 Improve ChangeLog entry
  docs/reference/changelog-r2021.md
Labels: documentation

#3550 Fix indentation of R2021b revision entries
  docs/reference/changelog-r2021.md
Labels: documentation

#3552 Merge released into master
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/samples-howto.md
  docs/js/showdown-extensions.js
  docs/reference/robot.md
Labels: documentation

#3544 Fix updating robot window on extern controller restart
  docs/reference/changelog-r2021.md
  src/webots/control/WbControlledWorld.cpp
  src/webots/nodes/WbRobot.hpp
Labels: bug, test suite

#3533 Convert RangeFinder to FLU
  docs/reference/images/rangefinder.png
  docs/reference/images/rangefinder.thumbnail.png
  docs/reference/rangefinder.md
  projects/samples/devices/worlds/range_finder.wbt
  src/webots/nodes/WbRangeFinder.cpp
  src/webots/nodes/WbRangeFinder.hpp
  tests/api/worlds/lidar_vs_range_finder.wbt
  tests/api/worlds/range_finder.wbt
  tests/api/worlds/range_finder_spherical.wbt
  tests/api/worlds/range_finder_spherical_horizontal_vertical.wbt
Labels: enhancement, test suite

#3551 Complete integrity tests for downloaded resources
  dependencies/Makefile.linux
  dependencies/Makefile.windows
  projects/default/resources/Makefile
  projects/robots/gctronic/e-puck/transfer/Makefile
  projects/robots/robotis/darwin-op/libraries/Makefile.mac
Labels: enhancement, test suite

#3553 Fix `Move Viewpoint to Object` (FLU)
  src/webots/nodes/WbViewpoint.cpp
Labels: bug

#3543 Fix supervisor node set visibility
  docs/reference/changelog-r2021.md
  docs/reference/supervisor.md
  src/webots/engine/WbAnimationRecorder.cpp
  src/webots/engine/WbAnimationRecorder.hpp
  src/webots/gui/WbX3dStreamingServer.cpp
  src/webots/nodes/WbAbstractCamera.cpp
  src/webots/nodes/WbAbstractCamera.hpp
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbBaseNode.hpp
  src/webots/nodes/WbBasicJoint.cpp
  src/webots/nodes/WbBasicJoint.hpp
  src/webots/nodes/WbBillboard.hpp
  src/webots/nodes/WbGeometry.hpp
  src/webots/nodes/WbGroup.cpp
  src/webots/nodes/WbGroup.hpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbMotor.hpp
  src/webots/nodes/WbMuscle.cpp
  src/webots/nodes/WbMuscle.hpp
  src/webots/nodes/WbPropeller.cpp
  src/webots/nodes/WbPropeller.hpp
  src/webots/nodes/WbShape.cpp
  src/webots/nodes/WbShape.hpp
  src/webots/nodes/WbSlot.cpp
  src/webots/nodes/WbSlot.hpp
  src/webots/nodes/WbSolidReference.cpp
  src/webots/nodes/WbSolidReference.hpp
  src/webots/nodes/WbTransform.hpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/nodes/WbViewpoint.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  tests/api/controllers/supervisor_node_set_visibility/supervisor_node_set_visibility.c
  tests/api/worlds/supervisor_node_set_visibility.wbt
Labels: bug, test suite

#3558 Hotfix inaccessible points in `getPointCloud` python API
  docs/reference/changelog-r2021.md
  src/controller/python/controller.i
Labels: bug, regression

#3559 Fix Track FLU documentation
  docs/reference/images/track_belt_concave.png
  docs/reference/images/track_belt_concave.thumbnail.jpg
  docs/reference/images/track_belt_convex.png
  docs/reference/images/track_belt_convex.thumbnail.jpg
  docs/reference/images/track_bounding_object.png
  docs/reference/images/track_bounding_object.thumbnail.jpg
  docs/reference/track.md
Labels: documentation

#3560 Fix Robot.controllerArgs documentation
  docs/reference/robot.md
Labels: documentation

#3473 FLU pen default orientation
  docs/reference/pen.md
  src/webots/nodes/WbPen.cpp
  tests/api/worlds/distance_sensor_infra-red.wbt
  tests/api/worlds/pen.wbt
  tests/api/worlds/pen_box.wbt
  tests/api/worlds/pen_box_scaled.wbt
  tests/api/worlds/pen_capsule.wbt
  tests/api/worlds/pen_capsule_scaled.wbt
  tests/api/worlds/pen_cone.wbt
  tests/api/worlds/pen_cone_scaled.wbt
  tests/api/worlds/pen_cylinder.wbt
  tests/api/worlds/pen_cylinder_scaled.wbt
  tests/api/worlds/pen_elevation_grid.wbt
  tests/api/worlds/pen_elevation_grid_scaled.wbt
  tests/api/worlds/pen_indexed_face_set.wbt
  tests/api/worlds/pen_indexed_face_set_scaled.wbt
  tests/api/worlds/pen_mesh.wbt
  tests/api/worlds/pen_plane.wbt
  tests/api/worlds/pen_sphere.wbt
  tests/api/worlds/pen_sphere_scaled.wbt
Labels: enhancement, test suite, test ros

#3565 Increase scroll velocity when zooming
  docs/reference/changelog-r2021.md
  src/webots/gui/WbView3D.cpp
Labels: enhancement

#3569 Fix FLU Radar
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbRadar.cpp
Labels: bug, test suite

#3568 Publish Python libController
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  include/controller/cpp/webots/Robot.hpp
  scripts/packaging/sync_controller_lib.sh
  src/controller/cpp/Robot.cpp
Labels: feature, test distribution

#3541 Save with Linux line endings on Windows
  projects/robots/softbank/nao/protos/Nao.proto
  projects/vehicles/protos/abstract/VehicleWheel.proto
  scripts/web_component_studio/controllers/web_component_studio_supervisor/web_component_studio_supervisor.py
  scripts/web_component_studio/web_component_studio.py
  src/webots/maths/WbRotation.hpp
  src/webots/maths/WbVector2.hpp
  src/webots/maths/WbVector3.hpp
  src/webots/nodes/WbGeometry.cpp
  src/webots/nodes/WbHinge2Joint.hpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbImageTexture.hpp
  src/webots/nodes/WbJoint.hpp
  src/webots/nodes/WbPbrAppearance.cpp
  src/webots/nodes/WbPointLight.hpp
  src/webots/nodes/utils/WbSolidMerger.hpp
  src/webots/nodes/utils/WbVirtualRealityHeadset.hpp
  src/webots/vrml/WbMFNode.cpp
  src/webots/vrml/WbProtoModel.cpp
  src/webots/vrml/WbRgb.hpp
  src/webots/vrml/WbSFVector3.hpp
  src/webots/vrml/WbVrmlWriter.cpp
  src/webots/vrml/WbVrmlWriter.hpp
  src/webots/wren/WbTesselator.cpp
Labels: cleanup

#3576 Fixed cppcheck error on macOS
  src/webots/nodes/utils/WbTriangleMesh.cpp
Labels: cleanup

#3562 Fix the Viewpoint documentation
  docs/reference/viewpoint.md
  resources/nodes/Viewpoint.wrl
  src/webots/gui/WbNewProjectWizard.cpp
  src/webots/gui/WbNewProjectWizard.hpp
Labels: documentation

#3578 Fixed forest shadow
  projects/objects/trees/protos/Forest.proto
Labels: cleanup

#3575 Fix FLU camera object detection
  src/webots/nodes/WbRadar.cpp
  src/webots/nodes/utils/WbObjectDetection.cpp
  src/webots/nodes/utils/WbObjectDetection.hpp
  tests/api/controllers/camera_recognition/camera_recognition.c
Labels: bug, test suite

#3579 Cleanup remnants of offline doc
  Makefile
Labels: cleanup

#3580 Fix Camera.getImageArray example
  docs/reference/camera.md
Labels: documentation

#3583 Merge released into master
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/reference/camera.md
  docs/reference/robot.md
Labels: documentation

#3540 Implement more fluid object rotation
  docs/reference/changelog-r2021.md
  src/webots/gui/WbDragTransformEvent.cpp
  src/webots/gui/WbDragTransformEvent.hpp
  src/webots/wren/WbTranslateRotateManipulator.cpp
  src/webots/wren/WbTranslateRotateManipulator.hpp
Labels: enhancement

#3586 Update proto-design-guidelines.md
  docs/reference/proto-design-guidelines.md
Labels: documentation

#3521 Emitter and Receiver (Infra-red) to FLU
  docs/reference/emitter.md
  docs/reference/images/emitter_receiver.png
  docs/reference/receiver.md
  src/webots/nodes/WbReceiver.cpp
  tests/api/controllers/emitter_receiver_infra-red/emitter_receiver_infra-red.c
  tests/api/worlds/emitter_receiver_infra-red.wbt
  tests/api/worlds/emitter_receiver_infra-red_aperture.wbt
  tests/physics/controllers/receiver_rays/receiver_rays.c
  tests/physics/worlds/dynamic_receiver_rays.wbt
  tests/physics/worlds/static_receiver_rays.wbt
Labels: enhancement, test suite, test ros

#3588 Added a burnt parameter in Sassafras tree proto (climate change update)
  docs/guide/object-trees.md
  projects/objects/trees/protos/Sassafras.proto
Labels: enhancement

#3590 Restore Billboard keyword
  docs/reference/nodes-and-keywords.md
Labels: documentation

#3593 restore mIs90DegreesRotated init
  src/webots/nodes/WbGeometry.cpp
  src/webots/nodes/WbGeometry.hpp
Labels: cleanup

#3596 Fix typo in C3dViewer.proto
  projects/humans/c3d/protos/C3dViewer.proto
Labels: documentation

#3591 Fix convert to base nodes for textures defined with URLs
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/nodes/utils/WbUrl.hpp
  src/webots/scene_tree/WbSceneTree.cpp
Labels: bug, test suite

#3597 Improve C3DViewer PROTO fields description
  projects/humans/c3d/protos/C3dViewer.proto
Labels: documentation

#3595 Fix missing initialization of new rotation handles nodes
  src/webots/wren/WbTranslateRotateManipulator.cpp
  src/webots/wren/WbTranslateRotateManipulator.hpp
Labels: bug, test suite

#3601 Add test billboard
  tests/Makefile
  tests/test_suite.py
  tests/with_rendering/.gitignore
  tests/with_rendering/Makefile
  tests/with_rendering/controllers/.gitignore
  tests/with_rendering/controllers/Makefile
  tests/with_rendering/controllers/billboard/.gitignore
  tests/with_rendering/controllers/billboard/Makefile
  tests/with_rendering/controllers/billboard/billboard.c
  tests/with_rendering/protos/.gitignore
  tests/with_rendering/worlds/.gitignore
  tests/with_rendering/worlds/billboard.wbt
Labels: enhancement, test suite

#3605 Billboard test to fast mode
  tests/test_suite.py
  tests/with_rendering/controllers/billboard/billboard.c
Labels: enhancement, test suite

#3610 FLU: Convert SolidBox
  projects/objects/solids/protos/SolidBox.proto
Labels: enhancement

#3618 FLU: texture mapping of cube and sphere
  docs/reference/box.md
  docs/reference/images/box.png
  docs/reference/images/sphere.png
  docs/reference/sphere.md
  src/webots/nodes/WbBox.cpp
  src/webots/nodes/WbSphere.cpp
  src/wren/StaticMesh.cpp
  tests/api/worlds/pen_box.wbt
  tests/rendering/worlds/mirror.wbt
Labels: enhancement, test suite

#3620 Docs flu geometires mapping
  docs/reference/capsule.md
  docs/reference/cone.md
  docs/reference/cylinder.md
  docs/reference/elevationgrid.md
  docs/reference/images/capsule.png
  docs/reference/images/cone.png
  docs/reference/images/cylinder.png
  docs/reference/plane.md
Labels: documentation

#3622 FLU: apartment furniture PROTOs
  docs/guide/object-kitchen.md
  docs/guide/object-living-room-furniture.md
  docs/guide/object-paintings.md
  projects/objects/bedroom/protos/Bed.proto
  projects/objects/kitchen/fridge/protos/Fridge.proto
  projects/objects/kitchen/oven/protos/Oven.proto
  projects/objects/living_room_furniture/protos/Armchair.proto
  projects/objects/living_room_furniture/protos/Carpet.proto
  projects/objects/living_room_furniture/protos/Sofa.proto
  projects/objects/paintings/protos/LandscapePainting.proto
  projects/objects/paintings/protos/PortraitPainting.proto
Labels: enhancement

#3624 Avoid changing the `LD_LIBRARY_PATH` environment in the `.bashrc`
  scripts/install/bashrc.linux
Labels: cleanup
