Repository cyberbotics/webots, pull requests merged in 2021-10, with the labels that each got.

#3690 ENU/FLU: conversion of Robotino3 (festo)
  docs/guide/robotino3.md
  projects/devices/sharp/protos/SharpGP2D120.proto
  projects/devices/sharp/protos/SharpGP2Y0A02YK0F.proto
  projects/devices/sharp/protos/SharpGP2Y0A41SK0F.proto
  projects/devices/sharp/protos/SharpGP2Y0A710K0F.proto
  projects/robots/festo/robotino3/protos/Robotino3.proto
  projects/robots/festo/robotino3/protos/Robotino3HokuyoMountingSupport.proto
  projects/robots/festo/robotino3/protos/Robotino3Platform.proto
  projects/robots/festo/robotino3/protos/Robotino3Webcam.proto
  projects/robots/festo/robotino3/protos/Robotino3WebcamMountingSupport.proto
  projects/robots/festo/robotino3/protos/Robotino3Wheel.proto
  projects/robots/festo/robotino3/worlds/robotino3.wbt
Labels: enhancement

#3651 Feature flu square_path
  projects/samples/robotbenchmark/maze_runner/protos/MazeBlock.proto
  projects/samples/robotbenchmark/square_path/protos/SquarePathPioneer3dx.proto
  projects/samples/robotbenchmark/square_path/worlds/square_path.wbt
  projects/samples/robotbenchmark/wall_following/protos/LinkedWalls.proto
  projects/samples/robotbenchmark/wall_following/protos/WallFollowingPioneer3dx.proto
  projects/samples/robotbenchmark/wall_following/worlds/wall_following.wbt
Labels: enhancement

#3732 Fix tests_sources on Windows (master branch)
  .github/workflows/tests_sources.yml
  src/webots/scene_tree/WbPhysicsViewer.cpp
  src/webots/scene_tree/WbPhysicsViewer.hpp
Labels: test sources

#3650 Feature flu pedestrian
  docs/guide/humans.md
  projects/humans/pedestrian/controllers/pedestrian/pedestrian.py
  projects/humans/pedestrian/protos/Pedestrian.proto
  projects/humans/pedestrian/protos/PedestrianHead.proto
  projects/humans/pedestrian/protos/PedestrianLeftFoot.proto
  projects/humans/pedestrian/protos/PedestrianLeftHand.proto
  projects/humans/pedestrian/protos/PedestrianLeftLowerArm.proto
  projects/humans/pedestrian/protos/PedestrianLeftLowerLeg.proto
  projects/humans/pedestrian/protos/PedestrianLeftUpperArm.proto
  projects/humans/pedestrian/protos/PedestrianLeftUpperLeg.proto
  projects/humans/pedestrian/protos/PedestrianNeck.proto
  projects/humans/pedestrian/protos/PedestrianRightFoot.proto
  projects/humans/pedestrian/protos/PedestrianRightHand.proto
  projects/humans/pedestrian/protos/PedestrianRightLowerArm.proto
  projects/humans/pedestrian/protos/PedestrianRightLowerLeg.proto
  projects/humans/pedestrian/protos/PedestrianRightUpperArm.proto
  projects/humans/pedestrian/protos/PedestrianRightUpperLeg.proto
  projects/humans/pedestrian/protos/PedestrianTorso.proto
  projects/humans/pedestrian/worlds/pedestrian.wbt
Labels: enhancement

#3734 Fix crash in Highway_overtake.wbt #3556 due to acos getting out of va…
  docs/reference/changelog-r2021.md
  src/webots/maths/WbMathsUtilities.hpp
  src/webots/maths/WbMatrix3.cpp
  src/webots/maths/WbQuaternion.hpp
  src/webots/maths/WbRotation.cpp
  src/webots/maths/WbRotation.hpp
  src/webots/nodes/WbCylinder.cpp
  src/webots/nodes/WbLightSensor.cpp
  src/webots/nodes/WbMuscle.cpp
  src/webots/nodes/WbSphere.cpp
  src/webots/nodes/WbTrack.cpp
Labels: bug, crash

#3735 Merge master into develop
  .github/workflows/tests_sources.yml
  docs/reference/changelog-r2021.md
  docs/reference/distancesensor.md
  src/webots/maths/WbMathsUtilities.hpp
  src/webots/maths/WbMatrix3.cpp
  src/webots/maths/WbQuaternion.hpp
  src/webots/maths/WbRotation.cpp
  src/webots/maths/WbRotation.hpp
  src/webots/nodes/WbCylinder.cpp
  src/webots/nodes/WbDistanceSensor.cpp
  src/webots/nodes/WbGeometry.hpp
  src/webots/nodes/WbLightSensor.cpp
  src/webots/nodes/WbMuscle.cpp
  src/webots/nodes/WbSphere.cpp
  src/webots/nodes/WbTrack.cpp
  src/webots/scene_tree/WbPhysicsViewer.cpp
  src/webots/scene_tree/WbPhysicsViewer.hpp
Labels: test suite, test sources

#3737 Merge develop into `feature-enu-plan`
  .github/workflows/tests_sources.yml
  docs/reference/changelog-r2021.md
  docs/reference/distancesensor.md
  src/webots/maths/WbMathsUtilities.hpp
  src/webots/maths/WbMatrix3.cpp
  src/webots/maths/WbQuaternion.hpp
  src/webots/maths/WbRotation.cpp
  src/webots/maths/WbRotation.hpp
  src/webots/nodes/WbCylinder.cpp
  src/webots/nodes/WbDistanceSensor.cpp
  src/webots/nodes/WbGeometry.hpp
  src/webots/nodes/WbLightSensor.cpp
  src/webots/nodes/WbMuscle.cpp
  src/webots/nodes/WbSphere.cpp
  src/webots/nodes/WbTrack.cpp
  src/webots/scene_tree/WbPhysicsViewer.cpp
  src/webots/scene_tree/WbPhysicsViewer.hpp
Labels: test suite, test sources

#3736 ENU/FLU: convert hexapod and soccer demo samples
  projects/samples/demos/controllers/hexapod/hexapod.c
  projects/samples/demos/controllers/soccer_player/soccer_player.c
  projects/samples/demos/controllers/soccer_referee_supervisor/soccer_referee_supervisor.c
  projects/samples/demos/worlds/hexapod.wbt
  projects/samples/demos/worlds/soccer.wbt
Labels: enhancement

#3740 Add error message on connection timeout
  resources/web/streaming_viewer/setup_viewer.js
  resources/web/wwi/Server.js
Labels: bug, enhancement

#3741 Fix acos issues
  src/webots/maths/WbMathsUtilities.hpp
Labels: cleanup

#3712 FLU: mantis, mir, bb8, firebird
  docs/guide/firebird6.md
  projects/objects/factory/conveyors/protos/ConveyorPlatform.proto
  projects/robots/festo/robotino3/protos/Robotino3Platform.proto
  projects/robots/k-team/koala/protos/Koala.proto
  projects/robots/k-team/koala/worlds/koala.wbt
  projects/robots/micromagic/mantis/protos/Mantis.proto
  projects/robots/micromagic/mantis/worlds/mantis.wbt
  projects/robots/mir/mir100/protos/Mir100.proto
  projects/robots/mir/mir100/protos/Mir100UltrasonicSensor.proto
  projects/robots/mir/mir100/worlds/mir100.wbt
  projects/robots/nex/protos/FireBird6.proto
  projects/robots/nex/worlds/fire_bird_6.wbt
  projects/robots/nex/worlds/fire_bird_6_remote_control.wbt
  projects/robots/sphero/bb8/protos/BB-8.proto
  projects/robots/sphero/bb8/protos/BB-8BodyShape.proto
  projects/robots/sphero/bb8/protos/BB-8HeadShape.proto
  projects/robots/sphero/bb8/worlds/bb-8.wbt
  projects/samples/demos/worlds/moon.wbt
  projects/samples/robotbenchmark/pit_escape/protos/Pit.proto
  projects/samples/robotbenchmark/pit_escape/worlds/pit_escape.wbt
Labels: enhancement

#3679 ENU/FLU: convert Spot & Atlas
  docs/guide/atlas.md
  docs/guide/spot.md
  projects/robots/boston_dynamics/atlas/protos/Atlas.proto
  projects/robots/boston_dynamics/atlas/protos/LClavSolid.proto
  projects/robots/boston_dynamics/atlas/protos/LFarmSolid.proto
  projects/robots/boston_dynamics/atlas/protos/LFootSolid.proto
  projects/robots/boston_dynamics/atlas/protos/LHandSolid.proto
  projects/robots/boston_dynamics/atlas/protos/LLarmSolid.proto
  projects/robots/boston_dynamics/atlas/protos/LLglutSolid.proto
  projects/robots/boston_dynamics/atlas/protos/LScapSolid.proto
  projects/robots/boston_dynamics/atlas/protos/LTalusSolid.proto
  projects/robots/boston_dynamics/atlas/protos/LUarmSolid.proto
  projects/robots/boston_dynamics/atlas/protos/LUglutSolid.proto
  projects/robots/boston_dynamics/atlas/protos/LUlegSolid.proto
  projects/robots/boston_dynamics/atlas/protos/MtorsoSolid.proto
  projects/robots/boston_dynamics/atlas/protos/PelvisSolid.proto
  projects/robots/boston_dynamics/atlas/protos/RClavSolid.proto
  projects/robots/boston_dynamics/atlas/protos/RFarmSolid.proto
  projects/robots/boston_dynamics/atlas/protos/RFootSolid.proto
  projects/robots/boston_dynamics/atlas/protos/RHandSolid.proto
  projects/robots/boston_dynamics/atlas/protos/RLarmSolid.proto
  projects/robots/boston_dynamics/atlas/protos/RLglutSolid.proto
  projects/robots/boston_dynamics/atlas/protos/RLlegSolid.proto
  projects/robots/boston_dynamics/atlas/protos/RScapSolid.proto
  projects/robots/boston_dynamics/atlas/protos/RTalusSolid.proto
  projects/robots/boston_dynamics/atlas/protos/RUarmSolid.proto
  projects/robots/boston_dynamics/atlas/protos/RUglutSolid.proto
  projects/robots/boston_dynamics/atlas/protos/RUlegSolid.proto
  projects/robots/boston_dynamics/atlas/protos/UtorsoSolid.proto
  projects/robots/boston_dynamics/atlas/worlds/atlas.wbt
  projects/robots/boston_dynamics/spot/protos/Spot.proto
  projects/robots/boston_dynamics/spot/protos/SpotLeftLeg.proto
  projects/robots/boston_dynamics/spot/protos/SpotRightLeg.proto
  projects/robots/boston_dynamics/spot/worlds/spot.wbt
Labels: enhancement

#3646 FLU: convert objects/road
  projects/objects/road/protos/AddLaneRoadSegment.proto
  projects/objects/road/protos/AddLanesRoadSegment.proto
  projects/objects/road/protos/CrashBarrier.proto
  projects/objects/road/protos/Crossroad.proto
  projects/objects/road/protos/CurvedRoadSegment.proto
  projects/objects/road/protos/HelicoidalRoadSegment.proto
  projects/objects/road/protos/LaneSeparation.proto
  projects/objects/road/protos/Road.proto
  projects/objects/road/protos/RoadIntersection.proto
  projects/objects/road/protos/RoadPillars.proto
  projects/objects/road/protos/Roundabout.proto
  projects/objects/road/protos/StraightRoadSegment.proto
  projects/robots/dji/mavic/worlds/mavic_2_pro.wbt
  projects/samples/robotbenchmark/highway_driving/worlds/highway_driving.wbt
  projects/vehicles/worlds/CH_Morges.wbt
  projects/vehicles/worlds/CH_Vens.wbt
  projects/vehicles/worlds/highway.wbt
  projects/vehicles/worlds/village.wbt
  projects/vehicles/worlds/village_center.wbt
  projects/vehicles/worlds/village_realistic.wbt
  projects/vehicles/worlds/village_winter.wbt
Labels: enhancement, test suite

#3747 Fix `StraightStairs` and tiago++ world
  projects/objects/stairs/protos/StraightStairs.proto
  projects/robots/pal_robotics/tiago++/worlds/tiago++.wbt
Labels: bug, test suite

#3744 Attempt to fix VM detection on Windows
  src/webots/core/WbSysInfo.cpp
Labels: bug
