Repository cyberbotics/webots, pull requests merged in 2021-09, with the labels that each got.

#3621 Fix java jdk
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  projects/default/libraries/vehicle/java/Makefile
  resources/Makefile.java.include
  scripts/install/bash_profile.mac
  scripts/install/bash_profile.windows
  scripts/install/bashrc.linux
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/msys64_installer.sh
  src/controller/java/Makefile
Labels: bug, upgrade, test suite

#3626 FLU: convert objects/computers
  projects/objects/computers/protos/ComputerMouse.proto
  projects/objects/computers/protos/DesktopComputer.proto
  projects/objects/computers/protos/Keyboard.proto
  projects/objects/computers/protos/Laptop.proto
  projects/objects/computers/protos/Monitor.proto
Labels: enhancement, test suite

#3636 Clean-up Windows CI build
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  scripts/install/msys64_installer.sh
Labels: cleanup, test suite

#3634 Merge released into master
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/thymio2.md
  docs/reference/nodes-and-keywords.md
  docs/reference/proto-design-guidelines.md
Labels: documentation

#3609 FLU: Convert apartment structure PROTOS
  docs/guide/object-apartment-structure.md
  projects/bounding_objects/protos/PipeBoundingObject.proto
  projects/objects/apartment_structure/protos/Ceiling.proto
  projects/objects/apartment_structure/protos/Door.proto
  projects/objects/apartment_structure/protos/DoorKnob.proto
  projects/objects/apartment_structure/protos/DoorLever.proto
  projects/objects/apartment_structure/protos/Radiator.proto
  projects/objects/apartment_structure/protos/Wall.proto
  projects/objects/apartment_structure/protos/WallPlug.proto
  projects/objects/apartment_structure/protos/Window.proto
  projects/objects/geometries/protos/TexturedBox.proto
Labels: enhancement

#3630 Enhancement web animation
  docs/guide/web-animation.md
  resources/web/templates/x3d_playback.html
  resources/web/wwi/Animation.js
  resources/web/wwi/AnimationSlider.js
  resources/web/wwi/DefaultUrl.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsAnimation.js
  resources/web/wwi/css/animation.css
  resources/web/wwi/fullscreen_handler.js
  resources/web/wwi/init_animation.js
  resources/web/wwi/viewer.js
Labels: enhancement

#3641 Fix animation bug on Firefox
  resources/web/wwi/Animation.js
  resources/web/wwi/WebotsAnimation.js
  resources/web/wwi/css/animation.css
  resources/web/wwi/css/animation_slider.css
Labels: bug

#3637 FLU: convert object/garden
  projects/objects/garden/protos/Barbecue.proto
  projects/objects/garden/protos/DogHouse.proto
  projects/objects/garden/protos/Gnome.proto
  projects/objects/garden/protos/Pergolas.proto
  projects/objects/garden/protos/PicketFence.proto
  projects/objects/garden/protos/PicketFenceWithDoor.proto
  projects/objects/garden/protos/Slide.proto
  projects/objects/garden/protos/Swing.proto
  projects/objects/garden/protos/SwingCouch.proto
  projects/objects/garden/protos/TableWithUmbrella.proto
  projects/objects/garden/protos/WateringCan.proto
  projects/objects/garden/protos/Wheelbarrow.proto
Labels: enhancement

#3613 FLU: solid and shapes objects
  docs/guide/object-solids.md
  projects/bounding_objects/protos/TorusBoundingObject.proto
  projects/objects/solids/protos/SolidPipe.proto
  projects/objects/solids/protos/SolidRoundedBox.proto
  projects/objects/solids/protos/SolidTorus.proto
Labels: enhancement

#3644 Fix pickable cone and cylinder
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbCone.cpp
  src/webots/nodes/WbCylinder.cpp
Labels: bug, test suite

#3640 FLU: convert stairs and floors
  projects/objects/floors/protos/UnevenTerrain.proto
  projects/objects/stairs/protos/StraightStairs.proto
  projects/objects/stairs/protos/StraightStairsLanding.proto
  projects/objects/stairs/protos/StraightStairsRail.proto
Labels: enhancement

#3639 FLU: Obstacles/toys/panels/ball/drinks
  docs/guide/images/objects/obstacles/ThreeSteps/model.png
  docs/guide/images/objects/obstacles/ThreeSteps/model.thumbnail.png
  docs/guide/object-drinks.md
  docs/guide/object-obstacles.md
  docs/guide/object-panels.md
  docs/guide/object-toys.md
  projects/objects/advertising_board/protos/AdvertisingBoard.proto
  projects/objects/balls/protos/RobocupSoccerBall.proto
  projects/objects/drinks/protos/BeerBottle.proto
  projects/objects/drinks/protos/Can.proto
  projects/objects/drinks/protos/WaterBottle.proto
  projects/objects/obstacles/protos/OilBarrel.proto
  projects/objects/obstacles/protos/Ramp30deg.proto
  projects/objects/obstacles/protos/ThreeSteps.proto
  projects/objects/obstacles/protos/icons/ThreeSteps.png
  projects/objects/panels/protos/Panel.proto
  projects/objects/panels/protos/PanelWithTubes.proto
  projects/objects/toys/protos/PaperBoat.proto
  projects/objects/toys/protos/PaperBoat/meshes/geom.obj
  projects/objects/toys/protos/RubberDuck.proto
  projects/objects/toys/protos/RubberDuck/meshes/beak.obj
  projects/objects/toys/protos/RubberDuck/meshes/body.obj
  scripts/icon_studio/controllers/icon_creator/objects.json
Labels: enhancement

#3645 Merge develop into `feature-enu-plan`
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/object-trees.md
  docs/guide/thymio2.md
  docs/guide/web-animation.md
  docs/reference/changelog-r2021.md
  docs/reference/nodes-and-keywords.md
  docs/reference/proto-design-guidelines.md
  projects/default/libraries/vehicle/java/Makefile
  projects/humans/c3d/protos/C3dViewer.proto
  projects/objects/trees/protos/Sassafras.proto
  resources/Makefile.java.include
  resources/web/templates/x3d_playback.html
  resources/web/wwi/Animation.js
  resources/web/wwi/AnimationSlider.js
  resources/web/wwi/DefaultUrl.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsAnimation.js
  resources/web/wwi/css/animation.css
  resources/web/wwi/css/animation_slider.css
  resources/web/wwi/fullscreen_handler.js
  resources/web/wwi/init_animation.js
  resources/web/wwi/viewer.js
  scripts/install/bash_profile.mac
  scripts/install/bash_profile.windows
  scripts/install/bashrc.linux
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/msys64_installer.sh
  src/controller/java/Makefile
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/nodes/utils/WbUrl.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  tests/Makefile
  tests/test_suite.py
  tests/with_rendering/.gitignore
  tests/with_rendering/Makefile
  tests/with_rendering/controllers/.gitignore
  tests/with_rendering/controllers/Makefile
  tests/with_rendering/controllers/billboard/.gitignore
  tests/with_rendering/controllers/billboard/Makefile
  tests/with_rendering/controllers/billboard/billboard.c
  tests/with_rendering/protos/.gitignore
  tests/with_rendering/worlds/.gitignore
  tests/with_rendering/worlds/billboard.wbt
Labels: test suite, test ros

#3631 FLU: Convert street furniture
  docs/guide/object-street-furniture.md
  projects/objects/street_furniture/protos/Atm.proto
  projects/objects/street_furniture/protos/Bench.proto
  projects/objects/street_furniture/protos/BusStop.proto
  projects/objects/street_furniture/protos/BusStopBench.proto
  projects/objects/street_furniture/protos/ClothRecyclingContainer.proto
  projects/objects/street_furniture/protos/DrinkingFountain.proto
  projects/objects/street_furniture/protos/ElectricalCabinet.proto
  projects/objects/street_furniture/protos/EmergencyPhone.proto
  projects/objects/street_furniture/protos/Fence.proto
  projects/objects/street_furniture/protos/FireHydrant.proto
  projects/objects/street_furniture/protos/Fountain.proto
  projects/objects/street_furniture/protos/GlassRecyclingContainer.proto
  projects/objects/street_furniture/protos/GuardShelter.proto
  projects/objects/street_furniture/protos/IceFreezerContainer.proto
  projects/objects/street_furniture/protos/Mailbox.proto
  projects/objects/street_furniture/protos/MetallicTrash.proto
  projects/objects/street_furniture/protos/NewsStand.proto
  projects/objects/street_furniture/protos/OldBench.proto
  projects/objects/street_furniture/protos/PhoneBooth.proto
  projects/objects/street_furniture/protos/PublicBin.proto
  projects/objects/street_furniture/protos/PublicToilet.proto
  projects/objects/street_furniture/protos/PublicToiletMesh.proto
  projects/objects/street_furniture/protos/SimpleBench.proto
  projects/objects/street_furniture/protos/SmallKiosk.proto
  projects/objects/street_furniture/protos/SnackStand.proto
  projects/objects/street_furniture/protos/StoneBench.proto
  projects/objects/street_furniture/protos/StoneFountain.proto
  projects/objects/street_furniture/protos/TrashBin.proto
  projects/objects/street_furniture/protos/TrashContainer.proto
  projects/objects/street_furniture/protos/UndergroundContainer.proto
  projects/objects/street_furniture/protos/UrbanFence.proto
  projects/objects/street_furniture/protos/WorkTrashContainer.proto
Labels: enhancement

#3627 FLU: convert objects/traffic
  projects/objects/traffic/protos/CautionPanel.proto
  projects/objects/traffic/protos/CautionSign.proto
  projects/objects/traffic/protos/ControlledStreetLight.proto
  projects/objects/traffic/protos/CrossRoadsTrafficLight.proto
  projects/objects/traffic/protos/DirectionPanel.proto
  projects/objects/traffic/protos/DivergentIndicator.proto
  projects/objects/traffic/protos/ExitPanel.proto
  projects/objects/traffic/protos/ExitSign.proto
  projects/objects/traffic/protos/GenericTrafficLight.proto
  projects/objects/traffic/protos/HighwayPole.proto
  projects/objects/traffic/protos/HighwaySign.proto
  projects/objects/traffic/protos/OrderPanel.proto
  projects/objects/traffic/protos/OrderSign.proto
  projects/objects/traffic/protos/ParkingLines.proto
  projects/objects/traffic/protos/ParkingMeter.proto
  projects/objects/traffic/protos/PedestrianCrossing.proto
  projects/objects/traffic/protos/Pole.proto
  projects/objects/traffic/protos/RectangularPanel.proto
  projects/objects/traffic/protos/SignPole.proto
  projects/objects/traffic/protos/SpeedLimitPanel.proto
  projects/objects/traffic/protos/SpeedLimitSign.proto
  projects/objects/traffic/protos/StopPanel.proto
  projects/objects/traffic/protos/StopSign.proto
  projects/objects/traffic/protos/StreetLight.proto
  projects/objects/traffic/protos/TrafficCone.proto
  projects/objects/traffic/protos/TrafficLight.proto
  projects/objects/traffic/protos/TrafficLightBigPole.proto
  projects/objects/traffic/protos/TrafficLightHorizontal.proto
  projects/objects/traffic/protos/WorkBarrier.proto
  projects/objects/traffic/protos/YieldPanel.proto
Labels: enhancement, test suite

#3612 Feature flu factory
  docs/guide/object-factory.md
  projects/objects/factory/containers/protos/CardboardBox.proto
  projects/objects/factory/containers/protos/MetalStorageBox.proto
  projects/objects/factory/containers/protos/PlasticCrate.proto
  projects/objects/factory/containers/protos/PlasticFruitBox.proto
  projects/objects/factory/containers/protos/WoodenBox.proto
  projects/objects/factory/conveyors/protos/ConveyorBelt.proto
  projects/objects/factory/conveyors/protos/ConveyorPlatform.proto
  projects/objects/factory/fire_extinguisher/protos/FireExtinguisher.proto
  projects/objects/factory/manhole/protos/SquareManhole.proto
  projects/objects/factory/pallet/protos/WoodenPallet.proto
  projects/objects/factory/pallet/protos/WoodenPalletStack.proto
  projects/objects/factory/pipes/protos/LJoint.proto
  projects/objects/factory/pipes/protos/PipeSection.proto
  projects/objects/factory/pipes/protos/TJoint.proto
  projects/objects/factory/tools/protos/Bolt.proto
  projects/objects/factory/tools/protos/CapScrew.proto
  projects/objects/factory/tools/protos/ElectricalPlug.proto
  projects/objects/factory/tools/protos/EmergencyButton.proto
  projects/objects/factory/tools/protos/EyeScrew.proto
  projects/objects/factory/tools/protos/Hammer.proto
  projects/objects/factory/tools/protos/Nut.proto
  projects/objects/factory/tools/protos/PaintBucket.proto
  projects/objects/factory/tools/protos/PlatformCart.proto
  projects/objects/factory/tools/protos/ScrewHole.proto
  projects/objects/factory/tools/protos/Screwdriver.proto
  projects/objects/factory/tools/protos/Washer.proto
  projects/objects/factory/tools/protos/Wrench.proto
  projects/objects/factory/valves/protos/LargeValve.proto
  projects/objects/factory/valves/protos/LeverValve.proto
  projects/objects/factory/valves/protos/SmallValve.proto
Labels: enhancement

#3654 Fix pickable local mesh
  src/webots/nodes/WbMesh.cpp
Labels: bug, test suite

#3608 Convert nature object to FLU
  projects/objects/fruits/protos/Apple.proto
  projects/objects/fruits/protos/FruitBowl.proto
  projects/objects/fruits/protos/Orange.proto
  projects/objects/plants/protos/BunchOfSunFlowers.proto
  projects/objects/plants/protos/PottedTree.proto
  projects/objects/rocks/protos/Rock10cm.proto
  projects/objects/rocks/protos/Rock17cm.proto
  projects/objects/trees/protos/BigSassafras.proto
  projects/objects/trees/protos/Cypress.proto
  projects/objects/trees/protos/Forest.proto
  projects/objects/trees/protos/Oak.proto
  projects/objects/trees/protos/PalmTree.proto
  projects/objects/trees/protos/Pine.proto
  projects/objects/trees/protos/Sassafras.proto
  projects/objects/trees/protos/SimpleTree.proto
  projects/objects/trees/protos/Tree.proto
Labels: enhancement

#3657 FLU: Fix capscrew in p-rob3
  projects/robots/fp_robotics/p-rob3/protos/P-Rob3.proto
  tests/api/controllers/robot_urdf/prob3_reference.urdf
Labels: bug, test suite

#3628 FLU: convert objects/kitchen
  projects/objects/kitchen/breakfast/protos/BiscuitBox.proto
  projects/objects/kitchen/breakfast/protos/CerealBox.proto
  projects/objects/kitchen/breakfast/protos/HoneyJar.proto
  projects/objects/kitchen/breakfast/protos/JamJar.proto
  projects/objects/kitchen/components/protos/HotPlate.proto
  projects/objects/kitchen/components/protos/Sink.proto
  projects/objects/kitchen/components/protos/Worktop.proto
  projects/objects/kitchen/utensils/protos/Carafe.proto
  projects/objects/kitchen/utensils/protos/Cookware.proto
  projects/objects/kitchen/utensils/protos/Fork.proto
  projects/objects/kitchen/utensils/protos/Glass.proto
  projects/objects/kitchen/utensils/protos/Knife.proto
  projects/objects/kitchen/utensils/protos/Lid.proto
  projects/objects/kitchen/utensils/protos/Plate.proto
  projects/objects/kitchen/utensils/protos/Spoon.proto
  projects/objects/kitchen/utensils/protos/Wineglass.proto
  projects/objects/kitchen/utensils/protos/WoodenSpoon.proto
Labels: enhancement, test suite

#3642 FLU: convert cabinet
  projects/objects/cabinet/protos/Cabinet.proto
  projects/objects/cabinet/protos/CabinetDoor.proto
  projects/objects/cabinet/protos/CabinetDrawer.proto
  projects/objects/cabinet/protos/CabinetHandle.proto
  projects/samples/contests/rockin/worlds/home.wbt
  projects/samples/environments/indoor/worlds/apartment.wbt
  projects/samples/environments/indoor/worlds/break_room.wbt
  projects/samples/environments/indoor/worlds/complete_apartment.wbt
  projects/samples/environments/indoor/worlds/kitchen.wbt
Labels: enhancement, test suite

#3670 Fix broadcast restore state when ready
  resources/web/wwi/Parser.js
  resources/web/wwi/Toolbar.js
Labels: bug

#3673 Documentation improve description of ROS support
  docs/guide/installation-procedure.md
  docs/guide/tutorial-8-using-ros.md
Labels: documentation

#3678 Remove libusb dependency on Linux
  scripts/install/linux_runtime_dependencies.sh
  src/webots/Makefile
Labels: cleanup, test distribution

#3681 Merge released branch into master
  docs/discord/development-2021.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2021.md
  docs/guide/installation-procedure.md
  docs/guide/tutorial-8-using-ros.md
Labels: documentation

#3686 Fix break lights spelling
  projects/default/libraries/vehicle/c/car/src/car.c
  projects/vehicles/controllers/ros_automobile/RosAutomobile.cpp
  projects/vehicles/protos/abstract/VehicleLights.proto
Labels: cleanup

#3680 Feature convert skin worlds to ENU
  projects/humans/skin_animated_humans/worlds/skin_animated_humans.wbt
  projects/samples/devices/worlds/skin.wbt
  tests/api/worlds/skin.wbt
Labels: test suite

#3687 Fix deprecated Floor field in tests
  tests/api/worlds/motions_loop.wbt
  tests/api/worlds/motions_regular.wbt
  tests/api/worlds/motions_reverse.wbt
  tests/manual_tests/worlds/interaction_with_solid_reference_model.wbt
Labels: cleanup, test suite

#3647 convert last objects to FLU
  projects/objects/create_wall/protos/CreateWall.proto
  projects/objects/floors/protos/CircleArena.proto
  projects/objects/freight/protos/IntermodalContainer.proto
  projects/objects/freight/protos/IntermodalOfficeContainer.proto
  projects/objects/gear/protos/Gear.proto
  projects/objects/lego/protos/LegoLargeMotor.proto
  projects/objects/lego/protos/LegoWheel.proto
  projects/objects/lights/protos/CeilingLight.proto
  projects/objects/lights/protos/CeilingSpotLight.proto
  projects/objects/lights/protos/ConstructionLamp.proto
  projects/objects/lights/protos/DoubleFluorescentLamp.proto
  projects/objects/lights/protos/FloorLight.proto
  projects/objects/robotstadium/protos/RobotstadiumGoal.proto
  projects/objects/robotstadium/protos/RobotstadiumSoccerField.proto
  projects/objects/telephone/protos/OfficeTelephone.proto
  projects/objects/telephone/protos/Telephone.proto
  projects/samples/contests/robocup/protos/RobocupGoal.proto
  projects/samples/contests/robocup/protos/RobocupSoccerField.proto
Labels: enhancement, test suite

#3674 FLU: Ned and Microbot
  docs/guide/microbot.md
  projects/objects/computers/protos/Monitor.proto
  projects/robots/niryo/ned/protos/Ned.proto
  projects/robots/niryo/ned/worlds/ned.wbt
  projects/robots/picaxe/microbot/protos/Microbot.proto
  projects/robots/picaxe/microbot/worlds/microbot_pe.wbt
Labels: enhancement

#3691 FLU: Convert Turtlebot3
  docs/guide/lidar-sensors.md
  projects/devices/robotis/protos/RobotisLds01.proto
  projects/robots/robotis/turtlebot/protos/TurtleBot3Burger.proto
  projects/robots/robotis/turtlebot/protos/meshes/Mesh0.obj
  projects/robots/robotis/turtlebot/protos/meshes/Mesh1.obj
  projects/robots/robotis/turtlebot/protos/meshes/Mesh2.obj
  projects/robots/robotis/turtlebot/protos/meshes/bars.obj
  projects/robots/robotis/turtlebot/protos/meshes/battery.obj
  projects/robots/robotis/turtlebot/protos/meshes/body.obj
  projects/robots/robotis/turtlebot/protos/meshes/cm.obj
  projects/robots/robotis/turtlebot/protos/meshes/left.obj
  projects/robots/robotis/turtlebot/protos/meshes/pi.obj
  projects/robots/robotis/turtlebot/protos/meshes/right.obj
  projects/robots/robotis/turtlebot/protos/meshes/screws.obj
  projects/robots/robotis/turtlebot/protos/meshes/sphere.obj
  projects/robots/robotis/turtlebot/protos/meshes/wheel.obj
  projects/robots/robotis/turtlebot/worlds/turtlebot3_burger.wbt
Labels: enhancement

#3696 Fix Nao v3.3 (21 DoF) hands
  docs/reference/changelog-r2021.md
  projects/robots/softbank/nao/protos/NaoLeftWristH21.proto
  projects/robots/softbank/nao/protos/NaoRightWristH21.proto
Labels: bug, regression

#3699 Attempt to fix Window CI build
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  scripts/install/bash_profile.windows
Labels: test distribution

#3703 Update CharacterSkin PROTO appearances
  projects/humans/skin_animated_humans/protos/CharacterSkin.proto
Labels: enhancement

#3619 FLU: Implement backward compability mechanism
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/gui/WbDragTransformEvent.cpp
  src/webots/nodes/utils/WbConcreteNodeFactory.cpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbNodeUtilities.hpp
  src/webots/wren/WbTranslateRotateManipulator.cpp
  tests/protos/controllers/backward_compatibility_enu_flu/.gitignore
  tests/protos/controllers/backward_compatibility_enu_flu/Makefile
  tests/protos/controllers/backward_compatibility_enu_flu/backward_compatibility_enu_flu.c
  tests/protos/protos/Bc21bCameraProto.proto
  tests/protos/worlds/backward_compability_enu_flu.wbt
  tests/sources/test_header_version.py
Labels: enhancement, test distribution, test suite

#3701 FLU: Convert Pioneer robots
  docs/guide/pioneer-3dx.md
  projects/robots/adept/pioneer2/protos/Pioneer2.proto
  projects/robots/adept/pioneer2/worlds/pioneer2.wbt
  projects/robots/adept/pioneer3/protos/Pioneer3Gripper.proto
  projects/robots/adept/pioneer3/protos/Pioneer3at.proto
  projects/robots/adept/pioneer3/protos/Pioneer3dx.proto
  projects/robots/adept/pioneer3/worlds/pioneer3at.wbt
  projects/robots/adept/pioneer3/worlds/pioneer3dx.wbt
  projects/robots/adept/pioneer3/worlds/pioneer3dx_collision_avoidance.wbt
  projects/robots/adept/pioneer3/worlds/pioneer3dx_gripper.wbt
  projects/robots/adept/pioneer3/worlds/pioneer3dx_matlab.wbt
  projects/robots/adept/pioneer3/worlds/pioneer3dx_with_kinect.wbt
  src/webots/nodes/utils/WbKinematicDifferentialWheels.cpp
  src/webots/nodes/utils/WbKinematicDifferentialWheels.hpp
Labels: enhancement

#3702 FLU: Convert JetBot robot and JetsonNano device
  projects/devices/nvidia/protos/JetsonNano.proto
  projects/objects/solids/protos/SolidRoundedBox.proto
  projects/robots/nvidia/jetbot/protos/JetBot.proto
  projects/robots/nvidia/jetbot/protos/JetBotRaspberryPiCamera.proto
  projects/robots/nvidia/jetbot/worlds/jetbot.wbt
Labels: test suite

#3707 Update JetBot documentation after converting to FLU
  docs/guide/jetbot.md
Labels: documentation

#3700 Feature FLU: Aibo Bioloid Qrio
  docs/guide/qrio.md
  projects/robots/robotis/bioloid/protos/BioloidDog.proto
  projects/robots/robotis/bioloid/worlds/bioloid_dog.wbt
  projects/robots/sony/aibo/protos/AiboErs7.proto
  projects/robots/sony/aibo/worlds/aibo_ers7.wbt
  projects/robots/sony/qrio/protos/QRIO.proto
  projects/robots/sony/qrio/worlds/qrio.wbt
Labels: enhancement

#3711 Fix log WebotsJS
  resources/web/wwi/Stream.js
Labels: enhancement

#3693 ENU/FLU: Convert universal robots
  docs/guide/ure.md
  docs/reference/changelog-r2021.md
  projects/objects/factory/conveyors/protos/ConveyorBelt.proto
  projects/robots/universal_robots/protos/UR10e.proto
  projects/robots/universal_robots/protos/UR3e.proto
  projects/robots/universal_robots/protos/UR5e.proto
  projects/robots/universal_robots/worlds/ure.wbt
  projects/samples/devices/worlds/track.wbt
  src/webots/engine/WbSimulationCluster.cpp
  src/webots/nodes/WbTrack.cpp
  tests/api/worlds/supervisor_node_set_joint_position.wbt
Labels: enhancement, test suite

#3705 FLU: Convert Khepera to FLU
  projects/objects/factory/containers/protos/WoodenBox.proto
  projects/robots/k-team/khepera1/protos/Khepera1.proto
  projects/robots/k-team/khepera1/worlds/khepera.wbt
  projects/robots/k-team/khepera1/worlds/khepera_gripper.wbt
  projects/robots/k-team/khepera1/worlds/khepera_gripper_camera.wbt
  projects/robots/k-team/khepera1/worlds/khepera_k213.wbt
  projects/robots/k-team/khepera1/worlds/khepera_kinematic.wbt
  projects/robots/k-team/khepera1/worlds/khepera_pipe.wbt
  projects/robots/k-team/khepera1/worlds/khepera_tcpip.wbt
  projects/robots/k-team/khepera2/protos/Khepera2.proto
  projects/robots/k-team/khepera2/worlds/khepera2.wbt
  projects/robots/k-team/khepera3/protos/Khepera3.proto
  projects/robots/k-team/khepera3/protos/Khepera3_Gripper.proto
  projects/robots/k-team/khepera3/protos/Khepera3_USSensor.proto
  projects/robots/k-team/khepera3/worlds/khepera3.wbt
  projects/robots/k-team/khepera3/worlds/khepera3_gripper.wbt
  projects/robots/k-team/khepera4/protos/Khepera4.proto
  projects/robots/k-team/khepera4/worlds/khepera4.wbt
Labels: enhancement

#3663 Convert Tiago to FLU
  docs/guide/tiago-base.md
  docs/guide/tiago-iron.md
  docs/guide/tiago-steel.md
  docs/guide/tiago-titanium.md
  docs/guide/tiagopp.md
  projects/robots/pal_robotics/tiago++/protos/Tiago++.proto
  projects/robots/pal_robotics/tiago++/worlds/tiago++.wbt
  projects/robots/pal_robotics/tiago_base/protos/TiagoBase.proto
  projects/robots/pal_robotics/tiago_base/worlds/tiago_base.wbt
  projects/robots/pal_robotics/tiago_iron/protos/TiagoIron.proto
  projects/robots/pal_robotics/tiago_iron/worlds/tiago_iron.wbt
  projects/robots/pal_robotics/tiago_steel/protos/TiagoSteel.proto
  projects/robots/pal_robotics/tiago_steel/worlds/tiago_steel.wbt
  projects/robots/pal_robotics/tiago_titanium/protos/TiagoTitanium.proto
  projects/robots/pal_robotics/tiago_titanium/worlds/tiago_titanium.wbt
Labels: enhancement

#3713 FLU: Convert Thymio
  projects/robots/mobsya/thymio/protos/Thymio2.proto
  projects/robots/mobsya/thymio/protos/Thymio2Pen.proto
  projects/robots/mobsya/thymio/worlds/thymio2.wbt
  projects/robots/mobsya/thymio/worlds/thymio2_ball.wbt
  projects/robots/mobsya/thymio/worlds/thymio2_pen.wbt
Labels: enhancement

#3710 Convert Tinkerbots to FLU
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsAxle.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsBase.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCube.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsCubieMaleCube.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsDistanceSensor.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsGrabber.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsLightSensor.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsMotor.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsPivot.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsTwister.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsWheel.proto
  projects/robots/kinematics/tinkerbots/worlds/android_l30.wbt
  projects/robots/kinematics/tinkerbots/worlds/braitenberg.wbt
  projects/robots/kinematics/tinkerbots/worlds/donnergugi.wbt
  projects/robots/kinematics/tinkerbots/worlds/grabber_base.wbt
  projects/robots/kinematics/tinkerbots/worlds/racer.wbt
  projects/robots/kinematics/tinkerbots/worlds/roadster.wbt
  projects/robots/kinematics/tinkerbots/worlds/sensoric_mega_set.wbt
  projects/robots/kinematics/tinkerbots/worlds/tinkerbots_demo.wbt
  projects/robots/kinematics/tinkerbots/worlds/top_dog.wbt
  projects/robots/kinematics/tinkerbots/worlds/vision_car.wbt
Labels: feature

#3720 FLU: shrimp puma hemisson
  projects/robots/bluebotics/shrimp/protos/Shrimp.proto
  projects/robots/bluebotics/shrimp/worlds/shrimp.wbt
  projects/robots/k-team/hemisson/protos/Hemisson.proto
  projects/robots/k-team/hemisson/worlds/hemisson.wbt
  projects/robots/unimation/puma/protos/Puma560.proto
  projects/robots/unimation/puma/worlds/puma560.wbt
Labels: enhancement

#3719 Fix mass calculation of Mesh nodes
  docs/reference/changelog-r2021.md
  src/webots/nodes/utils/WbSolidUtilities.cpp
Labels: bug, test suite

#3723 Merge master into develop
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/reference/changelog-r2021.md
  projects/default/libraries/vehicle/c/car/src/car.c
  projects/robots/softbank/nao/protos/NaoLeftWristH21.proto
  projects/robots/softbank/nao/protos/NaoRightWristH21.proto
  projects/vehicles/controllers/ros_automobile/RosAutomobile.cpp
  projects/vehicles/protos/abstract/VehicleLights.proto
  resources/web/wwi/Stream.js
  scripts/install/bash_profile.windows
  src/webots/nodes/utils/WbSolidUtilities.cpp
  tests/api/worlds/motions_loop.wbt
  tests/api/worlds/motions_regular.wbt
  tests/api/worlds/motions_reverse.wbt
  tests/manual_tests/worlds/interaction_with_solid_reference_model.wbt
Labels: test suite

#3689 Compute boundingSphere for Skin node
  include/wren/skeleton.h
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/WbSkin.hpp
  src/webots/nodes/utils/WbBoundingSphere.cpp
  src/webots/nodes/utils/WbBoundingSphere.hpp
  src/wren/Skeleton.cpp
  src/wren/Skeleton.hpp
Labels: enhancement, test suite

#3729 FLU: fix asymetric friction
  src/webots/nodes/WbBox.cpp
  src/webots/nodes/WbCylinder.cpp
  src/webots/nodes/WbPlane.cpp
  tests/api/worlds/asymmetric_friction.wbt
Labels: bug, test suite

#3730 FLU: fix robot_urdf
  tests/api/controllers/robot_urdf/tiago_reference.urdf
Labels: bug, test suite

#3726 Fix Laser intersecting transparent objects #3468
  docs/reference/changelog-r2021.md
  docs/reference/distancesensor.md
  src/webots/nodes/WbDistanceSensor.cpp
  src/webots/nodes/WbGeometry.hpp
Labels: bug, test suite
