Repository cyberbotics/webots, pull requests merged in 2021-01, with the labels that each got.

#2617 Fix URe ROS example
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/CMakeLists.txt
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/README.md
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/scripts/universal_robots_ros.py
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/setup.py
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/src/ur_e_webots/__init__.py
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/src/ur_e_webots/joint_state_publisher.py
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/src/ur_e_webots/trajectory_follower.py
Labels: bug

#2607 Update README.md
  README.md
Labels: cleanup

#2615 Enhancement of vehicle rear lights for mercedes, lincoln, citroen, bmw and rangerover
  docs/automobile/car.md
  docs/reference/changelog-r2021.md
  projects/vehicles/protos/bmw/BmwX5LeftIndicator.proto
  projects/vehicles/protos/bmw/BmwX5Mesh.proto
  projects/vehicles/protos/bmw/BmwX5RightIndicator.proto
  projects/vehicles/protos/citroen/CitroenCZero.proto
  projects/vehicles/protos/citroen/CitroenCZeroBrakeLight.proto
  projects/vehicles/protos/citroen/CitroenCZeroFogLight.proto
  projects/vehicles/protos/citroen/CitroenCZeroLeftIndicator.proto
  projects/vehicles/protos/citroen/CitroenCZeroRightIndicator.proto
  projects/vehicles/protos/citroen/CitroenCZeroTailLight.proto
  projects/vehicles/protos/lincoln/LincolnMKZ.proto
  projects/vehicles/protos/lincoln/LincolnMKZBrakingLightsMesh.proto
  projects/vehicles/protos/lincoln/LincolnMKZRearAntifogLightsMesh.proto
  projects/vehicles/protos/lincoln/LincolnMKZTailLightsMesh.proto
  projects/vehicles/protos/mercedes_benz/MercedesBenzSprinterLights.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVR.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVRAntifogLightsMesh.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVRBrakingLightsMesh.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVRLeftIndicatorMesh.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVRRearLightsMesh.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVRRightIndicatorMesh.proto
Labels: documentation, enhancement

#2592 Update italian translation
  resources/translations/wb_it.ts
Labels: enhancement

#2623 Fix GPU tests
  docs/reference/changelog-r2021.md
  src/webots/core/WbSysInfo.cpp
  src/webots/core/WbSysInfo.hpp
  src/webots/gui/WbView3D.cpp
Labels: enhancement

#2625 Fixed minor typo
  docs/reference/contactproperties.md
Labels: documentation

#2626 Minor fix
  docs/reference/contactproperties.md
Labels: documentation

#2627 fix compilation error
  src/webots/core/WbSysInfo.cpp
Labels: bug

#2630 Backporting minor doc fixes from the master branch
  docs/reference/contactproperties.md
Labels: documentation

#2629 Fix Cylinder unwrapped texture mapping
  docs/reference/changelog-r2021.md
  src/wren/StaticMesh.cpp
  tests/api/worlds/pen_cylinder_scaled.wbt
Labels: bug, test suite

#2631 Fixed high DPI support on Windows and Linux
  docs/reference/changelog-r2021.md
  src/webots/launcher/launcher.c
  src/webots/launcher/webots-linux.sh
Labels: bug

#2635 Rework of external force/torque logic
  docs/reference/changelog-r2021.md
  src/webots/gui/WbView3D.cpp
Labels: bug

#2638 Update installation-procedure.md
  docs/guide/installation-procedure.md
Labels: documentation

#2647 Update pen.wbt
  projects/samples/devices/worlds/pen.wbt
Labels: cleanup

#2642 Fixes documentation with respect to 3D mouse controls on Mac
  docs/css/webots-doc.css
  docs/guide/bioloid.md
  docs/guide/debugging-c-cpp-controllers.md
  docs/guide/installation-procedure.md
  docs/guide/matlab.md
  docs/guide/samples-devices.md
  docs/guide/samples-howto.md
  docs/guide/the-3d-window.md
  docs/guide/the-scene-tree.md
  docs/guide/tutorial-1-your-first-simulation-in-webots.md
  docs/guide/tutorial-2-modification-of-the-environment.md
  docs/guide/tutorial-3-appearance.md
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/guide/using-your-ide.md
  docs/reference/keyboard.md
Labels: documentation

#2659 Fixed use of deprecated API method
  tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py
Labels: cleanup, test suite

#2667 Handle undefined `setup` variable in `showdown-extensions.js`
  docs/js/showdown-extensions.js
Labels: bug

#2666 Fix lidar point cloud visualisation issue
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbLidar.cpp
Labels: bug, regression

#2670 Fixed wrong indent
  docs/guide/the-user-interface.md
Labels: documentation

#2673 Fix #2663 memory use on Display node
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbDisplay.cpp
Labels: bug

#2664 Expose new API for accessing RangeFinder's raw float buffer in Python
  docs/reference/rangefinder.md
  src/controller/python/controller.i
Labels: enhancement, test suite

#2675 Fixed license year in source test
  tests/sources/test_license.py
Labels: bug

#2674 Add description of the boundingObject color in solid.md
  docs/reference/solid.md
Labels: documentation
