Repository cyberbotics/webots, pull requests merged in 2021-11, with the labels that each got.

#3852 Fix flu mistakes
  projects/robots/dji/mavic/worlds/mavic_2_pro.wbt
  projects/samples/robotbenchmark/pick_and_place/worlds/pick_and_place.wbt
  tests/with_rendering/worlds/billboard.wbt
Labels: bug, test suite

#3851 Cleanup dirty variable in DynamicMesh clear
  src/wren/DynamicMesh.cpp
Labels: cleanup, test suite

#3856 Fix Windows builds due to OpenJDK update
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  scripts/install/bash_profile.windows
Labels: bug, test distribution

#3788 convert sample default robots
  docs/guide/object-kitchen.md
  projects/languages/cpp/controllers/driver/driver.cpp
  projects/languages/cpp/worlds/example.wbt
  projects/languages/java/controllers/Driver/Driver.java
  projects/languages/java/worlds/example.wbt
  projects/languages/python/controllers/driver/driver.py
  projects/languages/python/worlds/example.wbt
  projects/objects/cabinet/protos/CabinetDrawer.proto
  projects/objects/factory/tools/protos/Washer.proto
  projects/objects/kitchen/oven/protos/Oven.proto
  projects/robots/parallax/boebot/protos/BoeBot.proto
  projects/robots/parallax/boebot/worlds/boebot.wbt
  projects/samples/curriculum/protos/Obstacle.proto
  projects/samples/demos/worlds/gantry.wbt
  projects/samples/demos/worlds/stewart_platform.wbt
  projects/samples/environments/factory/worlds/hall.wbt
  projects/samples/environments/indoor/worlds/break_room.wbt
  projects/samples/environments/indoor/worlds/complete_apartment.wbt
  projects/samples/environments/indoor/worlds/kitchen.wbt
  projects/samples/howto/openai_gym/worlds/openai_gym.wbt
  projects/samples/mybot/worlds/mybot.wbt
  projects/samples/mybot/worlds/mybot_camera.wbt
  projects/samples/mybot/worlds/mybot_physics.wbt
  projects/samples/robotbenchmark/inverted_pendulum/worlds/inverted_pendulum.wbt
  projects/samples/robotbenchmark/robot_programming/controllers/supervisor/supervisor.py
  projects/samples/robotbenchmark/robot_programming/worlds/robot_programming.wbt
  projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking/visual_tracking.py
  projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking_benchmark/target_trajectory.txt
  projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking_benchmark/visual_tracking_benchmark.py
  projects/samples/robotbenchmark/visual_tracking/worlds/visual_tracking.wbt
  projects/vehicles/protos/generic/TruckTankSimple.proto
  resources/projects/worlds/empty.wbt
Labels: enhancement, test sources

#3798 Altino to FLU
  docs/guide/altino.md
  projects/robots/saeon/protos/Altino.proto
  projects/robots/saeon/worlds/altino.wbt
Labels: enhancement

#3807 Feature flu various robots
  docs/guide/ipr.md
  projects/robots/fp_robotics/p-rob3/worlds/p-rob3.wbt
  projects/robots/micromagic/scout/worlds/scout.wbt
  projects/robots/neuronics/ipr/controllers/target_coordinates/target_coordinates.c
  projects/robots/neuronics/ipr/protos/IprHd6m180.proto
  projects/robots/neuronics/ipr/protos/IprHd6m90.proto
  projects/robots/neuronics/ipr/protos/IprHd6ms180.proto
  projects/robots/neuronics/ipr/protos/IprHd6ms90.proto
  projects/robots/neuronics/ipr/worlds/ipr_collaboration.wbt
  projects/robots/neuronics/ipr/worlds/ipr_cube.wbt
  projects/robots/neuronics/ipr/worlds/ipr_factory.wbt
  projects/robots/neuronics/ipr/worlds/ipr_models.wbt
  projects/robots/robotcub/icub/worlds/icub_stand.wbt
  projects/samples/robotbenchmark/visual_tracking/worlds/visual_tracking.wbt
  scripts/icon_studio/controllers/icon_creator/icon_creator.py
  scripts/icon_studio/controllers/icon_creator/objects.json
  scripts/icon_studio/worlds/icon_studio.wbt
Labels: enhancement

#3867 Fix node deletion from supervisor not refreshing scene tree
  docs/reference/changelog-r2021.md
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
Labels: bug, test suite

#3866 Fix tutorial 3 broken due to missing texture
  docs/guide/tutorial-3-appearance.md
Labels: documentation

#3868 Fix macOS dependency
  projects/robots/robotis/darwin-op/libraries/Makefile.mac
Labels: bug, test suite

#3871 Merge master in develop
  docs/discord/development-2020.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/tutorial-3-appearance.md
  docs/reference/changelog-r2021.md
  projects/robots/robotis/darwin-op/libraries/Makefile.mac
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
Labels: test suite

#3869 Fix auto-regeneration crash
  docs/reference/changelog-r2021.md
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbView3D.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
Labels: test suite, test sources

#3872 Merge develop in feature enu plan
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  docs/discord/development-2020.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/supervisor-programming.md
  docs/guide/tutorial-3-appearance.md
  docs/reference/changelog-r2021.md
  include/controller/c/webots/vehicle/driver.h
  include/controller/cpp/webots/vehicle/Driver.hpp
  projects/default/libraries/vehicle/Makefile
  projects/default/libraries/vehicle/c/car/Makefile
  projects/default/libraries/vehicle/c/car/car.def
  projects/default/libraries/vehicle/c/car/src/car.c
  projects/default/libraries/vehicle/c/driver/Makefile
  projects/default/libraries/vehicle/c/driver/driver.def
  projects/default/libraries/vehicle/c/driver/src/driver.c
  projects/default/libraries/vehicle/cpp/car/Makefile
  projects/default/libraries/vehicle/cpp/driver/Makefile
  projects/default/libraries/vehicle/cpp/driver/src/Driver.cpp
  projects/default/libraries/vehicle/java/Makefile
  projects/default/libraries/vehicle/python/Makefile
  projects/robots/robotis/darwin-op/libraries/Makefile.mac
  scripts/install/bash_profile.windows
  scripts/packaging/sync_controller_lib.sh
  src/webots/gui/WbOpenSampleWorldDialog.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/wren/DynamicMesh.cpp
Labels: test suite

#3878 Improve API of animation
  docs/guide/web-animation.md
  resources/web/templates/x3d_playback.html
  resources/web/wwi/AnimationSlider.js
  resources/web/wwi/WebotsAnimation.js
  src/webots/nodes/utils/WbWorld.cpp
Labels: enhancement

#3880 Fixed line endings
  docs/reference/altimeter.md
  projects/default/libraries/vehicle/c/car/car.def
  projects/default/libraries/vehicle/c/driver/driver.def
  resources/nodes/Altimeter.wrl
  resources/nodes/Background.wrl
  resources/nodes/Color.wrl
  resources/nodes/Normal.wrl
  resources/nodes/Solid.wrl
  resources/nodes/Speaker.wrl
  resources/nodes/TextureCoordinate.wrl
  resources/nodes/TextureTransform.wrl
Labels: cleanup

#3881 Update Solid.wrl
  resources/nodes/Solid.wrl
Labels: documentation

#3883 Fix lights cast shadow
  src/wren/Scene.cpp
Labels: bug, test suite

#3882 Add supervisor tutorial
  docs/guide/images/tutorial_8_environment.png
  docs/guide/installation-procedure.md
  docs/guide/menu.md
  docs/guide/tutorial-8-the-supervisor.md
  docs/guide/tutorial-9-using-ros.md
  docs/guide/tutorials.md
  docs/guide/using-ros.md
Labels: documentation

#3854 Cleanup wheel acceleration computation
  projects/default/libraries/vehicle/c/driver/src/driver.c
Labels: cleanup, test suite

#3876 Update sumo
  docs/automobile/sumo-exporter.md
  docs/guide/installation-procedure.md
  projects/default/controllers/sumo_supervisor/SumoSupervisor.py
  projects/default/controllers/sumo_supervisor/WebotsVehicle.py
  projects/default/resources/Makefile
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/packaging/webots_distro.c
Labels: enhancement

#3926 Add warning when adding node after simulation has run
  docs/reference/changelog-r2021.md
  resources/icons/core/warning.png
  src/webots/scene_tree/WbAddNodeDialog.cpp
Labels: enhancement

#3930 Add `none` to physics plugin selector window
  src/webots/scene_tree/WbExtendedStringEditor.cpp
Labels: enhancement, test sources

#3932 Merge `released` into `master`
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/images/tutorial_8_environment.png
  docs/guide/installation-procedure.md
  docs/guide/menu.md
  docs/guide/tutorial-8-the-supervisor.md
  docs/guide/tutorial-9-using-ros.md
  docs/guide/tutorials.md
  docs/guide/using-ros.md
Labels: test suite, test sources

#3936 Merge `master` into `develop`
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/images/tutorial_8_environment.png
  docs/guide/installation-procedure.md
  docs/guide/menu.md
  docs/guide/tutorial-8-the-supervisor.md
  docs/guide/tutorial-9-using-ros.md
  docs/guide/tutorials.md
  docs/guide/using-ros.md
  docs/reference/altimeter.md
  docs/reference/changelog-r2021.md
  projects/default/libraries/vehicle/c/car/car.def
  projects/default/libraries/vehicle/c/driver/driver.def
  projects/default/libraries/vehicle/c/driver/src/driver.c
  resources/nodes/Altimeter.wrl
  resources/nodes/Background.wrl
  resources/nodes/Color.wrl
  resources/nodes/Normal.wrl
  resources/nodes/Solid.wrl
  resources/nodes/Speaker.wrl
  resources/nodes/TextureCoordinate.wrl
  resources/nodes/TextureTransform.wrl
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbView3D.hpp
  src/webots/maths/WbAxisAngle.hpp
  src/webots/maths/WbMathsUtilities.hpp
  src/webots/maths/WbRotation.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/wren/Scene.cpp
Labels: test suite, test sources

#3931 Change Python installation detection for macOS
  src/webots/control/WbController.cpp
Labels: bug

#3923 Update supervisor.md
  docs/guide/tutorial-8-the-supervisor.md
  docs/reference/supervisor.md
Labels: documentation

#3937 Merge `develop` into `feature-enu-plan`
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/images/tutorial_8_environment.png
  docs/guide/installation-procedure.md
  docs/guide/menu.md
  docs/guide/tutorial-8-the-supervisor.md
  docs/guide/tutorial-9-using-ros.md
  docs/guide/tutorials.md
  docs/guide/using-ros.md
  docs/reference/altimeter.md
  docs/reference/changelog-r2021.md
  projects/default/libraries/vehicle/c/car/car.def
  projects/default/libraries/vehicle/c/driver/driver.def
  projects/default/libraries/vehicle/c/driver/src/driver.c
  resources/icons/core/warning.png
  resources/nodes/Altimeter.wrl
  resources/nodes/Background.wrl
  resources/nodes/Color.wrl
  resources/nodes/Normal.wrl
  resources/nodes/Solid.wrl
  resources/nodes/Speaker.wrl
  resources/nodes/TextureCoordinate.wrl
  resources/nodes/TextureTransform.wrl
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbView3D.hpp
  src/webots/maths/WbAxisAngle.hpp
  src/webots/maths/WbMathsUtilities.hpp
  src/webots/maths/WbRotation.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbExtendedStringEditor.cpp
  src/wren/Scene.cpp
Labels: test suite, test sources

#3914 Merge web-component
  docs/guide/web-animation.md
  docs/guide/web-scene.md
  docs/guide/web-simulation.md
  resources/web/streaming_viewer/index.html
  resources/web/streaming_viewer/setup_viewer.js
  resources/web/templates/x3d_playback.html
  resources/web/wwi/Animation.js
  resources/web/wwi/WebotsAnimation.js
  resources/web/wwi/WebotsStreaming.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/dependencies/glm-js.min.js
  resources/web/wwi/fullscreen_handler.js
Labels: enhancement

#3939 Fix rendering when switching from wireframe
  docs/reference/changelog-r2021.md
  src/wren/TextureCubeMapBaker.cpp
Labels: bug, test suite

#3940 Fix typo webotsview
  resources/web/wwi/WebotsView.js
Labels: enhancement

#3943 Enhancement of WebotsJS
  docs/guide/web-animation.md
  docs/guide/web-scene.md
  docs/guide/web-simulation.md
  docs/reference/light.md
  resources/web/streaming_viewer/setup_viewer.js
  resources/web/wwi/Animation.js
  resources/web/wwi/Parser.js
  resources/web/wwi/Stream.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/WrenRenderer.js
  resources/web/wwi/X3dScene.js
  resources/wren/shaders/pbr.frag
  resources/wren/shaders/pbr_stencil_diffuse_specular.frag
  resources/wren/shaders/phong.frag
  resources/wren/shaders/phong_stencil_ambient_emissive.frag
  resources/wren/shaders/phong_stencil_diffuse_specular.frag
  resources/wren/shaders/shadow_volume.vert
  src/wren/Constants.hpp
Labels: enhancement

#3949 FLU: Fix nao
  projects/robots/softbank/nao/protos/Nao.proto
Labels: bug

#3948 FLU: fix orthographic mode
  src/webots/gui/WbView3D.cpp
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/nodes/WbViewpoint.hpp
Labels: bug, enhancement, test suite

#3954 Enhancement-useNetconvert
  docs/automobile/sumo-interface.md
  projects/default/protos/SumoInterface.proto
  projects/samples/robotbenchmark/highway_driving/controllers/highway_driving_benchmark/highway_driving_benchmark.py
  projects/vehicles/worlds/city_traffic.wbt
  projects/vehicles/worlds/highway.wbt
  projects/vehicles/worlds/highway_overtake.wbt
  projects/vehicles/worlds/sumo_interface_example.wbt
  projects/vehicles/worlds/village_center.wbt
  src/webots/scene_tree/WbSceneTree.cpp
Labels: enhancement

#3864 FLU: osm_importer
  resources/osm_importer/elevation.py
  resources/osm_importer/importer.py
  resources/osm_importer/osm_objects.py
  resources/osm_importer/utils/misc_utils.py
  resources/osm_importer/webots_objects/area.py
  resources/osm_importer/webots_objects/barrier.py
  resources/osm_importer/webots_objects/building.py
  resources/osm_importer/webots_objects/road.py
  resources/osm_importer/webots_objects/tree.py
  resources/osm_importer/webots_objects/webots_object.py
Labels: enhancement

#3959 Enhancement model webotsjs
  docs/guide/the-user-interface.md
  docs/guide/web-animation.md
  docs/guide/web-scene.md
  docs/guide/web-simulation.md
  resources/translations/wb_de.ts
  resources/translations/wb_es.ts
  resources/translations/wb_fr.ts
  resources/translations/wb_generic.ts
  resources/translations/wb_it.ts
  resources/translations/wb_ja_JP.ts
  resources/translations/wb_zh_CN.ts
  resources/web/templates/x3d_playback.html
  resources/web/wwi/Animation.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/webots.js
  src/webots/gui/WbMainWindow.cpp
  src/webots/nodes/utils/WbWorld.cpp
Labels: enhancement

#3962 Fix lidar C API documentation
  docs/reference/lidar.md
Labels: documentation

#3960 Fix Radar sanity check and restrict field of view to 180°
  docs/reference/changelog-r2021.md
  docs/reference/radar.md
  src/webots/nodes/WbRadar.cpp
  src/webots/nodes/utils/WbObjectDetection.cpp
Labels: enhancement, test suite, test sources

#3961 Fix-test-sumo
  projects/default/resources/Makefile
Labels: bug, test suite

#3965 Fix webots.js texture path
  resources/web/wwi/viewer.js
  resources/web/wwi/webots.js
Labels: bug

#3966 Disable css when not needed
  resources/web/wwi/WebotsView.js
  resources/web/wwi/css/animation.css
  resources/web/wwi/css/wwi.css
Labels: enhancement

#3950 Fix crash when changing a world after the backward compatibility adapta…
  src/webots/nodes/utils/WbNodeUtilities.cpp
Labels: bug, test suite

#3933 Add direct steering of wheels to car library
  docs/automobile/car-library.md
  docs/automobile/driver-library.md
  docs/reference/changelog-r2021.md
  include/controller/c/webots/vehicle/car.h
  include/controller/cpp/webots/vehicle/Car.hpp
  projects/default/libraries/vehicle/c/car/car.def
  projects/default/libraries/vehicle/c/car/src/car.c
  projects/default/libraries/vehicle/c/driver/src/driver.c
  projects/default/libraries/vehicle/cpp/car/src/Car.cpp
  src/webots/core/WbLanguage.cpp
Labels: enhancement, test suite, test sources
