Repository cyberbotics/webots, pull requests merged in 2021-02, with the labels that each got.

#2683 FAQ on Spot SDK
  docs/guide/spot.md
Labels: documentation

#2687 Fix X3D USE node export
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbBaseNode.cpp
Labels: bug, test suite

#2689 Merge master into develop
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbBaseNode.cpp
Labels: test suite

#2693 PaperBoat with Mesh
  projects/objects/toys/protos/PaperBoat.proto
  projects/objects/toys/protos/PaperBoat/geom.obj
  projects/objects/toys/protos/PaperBoat/newspaper.jpg
Labels: enhancement

#2695 Fixed Background irradiance when no colormap is set
  src/webots/nodes/WbBackground.cpp
Labels: bug

#2697 Removed now useless reflections parameter of the TexturedBackground proto
  docs/guide/object-backgrounds.md
  projects/objects/backgrounds/protos/TexturedBackground.proto
Labels: cleanup

#2699 Remove obsolete badges
  README.md
Labels: cleanup

#2688 Update worlds
  projects/samples/howto/custom_robot_window/worlds/.custom_robot_window.wbproj
  projects/samples/robotbenchmark/visual_tracking/worlds/visual_tracking.wbt
Labels: enhancement, test world update

#2668 proto2mesh
  docs/reference/changelog-r2021.md
  projects/objects/toys/protos/RubberDuck.proto
  projects/objects/toys/protos/RubberDuck/beak.obj
  projects/objects/toys/protos/RubberDuck/body.obj
  projects/objects/toys/protos/RubberDuck/eye.jpg
  projects/objects/toys/protos/RubberDuck/eye.obj
  scripts/proto_splitter/proto2mesh.py
Labels: enhancement

#2707 Added sanity check for wrong faces in proto2mesh.py script
  scripts/proto_splitter/proto2mesh.py
Labels: enhancement

#2708 Fixed discord updater
  .github/workflows/discord_updater.yml
Labels: bug

#2701 Nao room
  docs/reference/changelog-r2021.md
  projects/robots/softbank/nao/controllers/nao_demo_python/nao_demo_python.py
  projects/robots/softbank/nao/protos/NaoChallengeRoom.proto
  projects/robots/softbank/nao/protos/NaoRoom.proto
  projects/robots/softbank/nao/protos/icons/NaoChallengeRoom.png
  projects/robots/softbank/nao/protos/icons/NaoRoom.png
  projects/robots/softbank/nao/worlds/.nao_room.wbproj
  projects/robots/softbank/nao/worlds/challenge.wbt
  projects/robots/softbank/nao/worlds/nao_room.wbt
Labels: enhancement

#2711 Add OpenAI Gym Example
  docs/guide/images/samples/openai_gym.png
  docs/guide/images/samples/openai_gym.thumbnail.jpg
  docs/guide/samples-howto.md
  docs/reference/changelog-r2021.md
  projects/samples/howto/openai_gym/controllers/openai_gym/openai_gym.py
  projects/samples/howto/openai_gym/worlds/.openai_gym.wbproj
  projects/samples/howto/openai_gym/worlds/openai_gym.wbt
Labels: enhancement

#2715 Fixed URDF test which was broken by new UR5e model
  tests/api/controllers/robot_urdf/prob3_reference.urdf
  tests/api/controllers/robot_urdf/tiago_reference.urdf
  tests/api/controllers/robot_urdf/ur5e_reference.urdf
Labels: test suite

#2713 regenerate x3d world at loading
  src/webots/gui/WbX3dStreamingServer.cpp
Labels: bug, test suite

#2712 delete step message
  src/webots/gui/WbStreamingServer.cpp
Labels: cleanup, test suite

#2684 fix reproductibility issue when resetting
  src/webots/control/WbControlledWorld.cpp
Labels: bug, test suite

#2657 Build Windows package if test suite label is set
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
Labels: test suite

#2718 Fix link to Qt libraries on Windows
  docs/reference/changelog-r2021.md
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/Makefile
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/Makefile
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/Makefile
  projects/vehicles/controllers/racing_wheel/Makefile
  projects/vehicles/plugins/robot_windows/automobile_window/Makefile
  resources/projects/libraries/qt_utils/Makefile
  resources/projects/plugins/robot_windows/generic_window/Makefile
Labels: bug, test suite

#2721 Upgrade to Qt 5.15.2 on macOS
  dependencies/Makefile.mac
  docs/reference/changelog-r2021.md
  projects/default/libraries/vehicle/python/Makefile
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/Automaton.cpp
  projects/robots/gctronic/e-puck/plugins/robot_windows/botstudio/core/Model.cpp
  projects/robots/robotis/darwin-op/libraries/python/Makefile
  resources/Makefile.os.include
  resources/projects/libraries/qt_utils/motion_editor/Motion.cpp
  resources/projects/libraries/qt_utils/motion_editor/Pose.cpp
  scripts/install/qt_mac_installer.sh
  scripts/packaging/files_core.txt
  scripts/packaging/webots_distro.c
  src/controller/python/Makefile
  src/webots/control/WbController.cpp
  src/webots/core/WbTemplateEngine.cpp
  src/webots/gui/WbGuiApplication.cpp
Labels: test suite, upgrade

#2727 Cleanup unused variable
  src/webots/gui/WbX3dStreamingServer.cpp
  src/webots/gui/WbX3dStreamingServer.hpp
Labels: cleanup, test suite

#2716 Fix urdf test
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/linux_test_dependencies.sh
  tests/api/controllers/robot_urdf/robot_urdf.c
Labels: test suite

#2704 update textures while streaming
  docs/reference/changelog-r2021.md
  src/webots/gui/WbX3dStreamingServer.cpp
Labels: bug, test suite

#2698 Proto2mesh multithreaded
  scripts/proto_splitter/proto2mesh.py
Labels: enhancement

#2725 Fix Camera images not updated after reset
  docs/reference/changelog-r2021.md
  src/controller/c/abstract_camera.c
  src/controller/c/abstract_camera.h
  src/controller/c/camera.c
  src/controller/c/device.c
  src/controller/c/device_private.h
  src/controller/c/lidar.c
  src/controller/c/range_finder.c
  src/controller/c/robot.c
  src/controller/c/robot_private.h
Labels: bug, test suite

#2728 Improved documentation
  docs/guide/preferences.md
Labels: documentation

#2720 Improve synchronization of Supervisor simulation reset
  docs/reference/changelog-r2021.md
  src/webots/app/WbApplication.cpp
  src/webots/editor/WbBuildEditor.cpp
  src/webots/editor/WbBuildEditor.hpp
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/nodes/utils/WbWorld.hpp
Labels: bug, test suite

#2729 Don't test source code on the released branch
  .github/workflows/tests_sources.yml
Labels: bug

#2733 Merge released into master
  .github/workflows/tests_sources.yml
  docs/guide/preferences.md
  docs/guide/spot.md
Labels: documentation

#2738 Fix openai_gym.wbt
  projects/samples/howto/openai_gym/worlds/openai_gym.wbt
Labels: bug

#2737 Postpone sending logs to consoles during the world load
  docs/reference/changelog-r2021.md
  src/webots/app/WbApplication.cpp
  src/webots/app/WbApplication.hpp
  src/webots/core/WbLog.cpp
  src/webots/core/WbLog.hpp
  src/webots/gui/WbMainWindow.cpp
Labels: bug, test suite

#2745 export basictimestep
  src/webots/nodes/WbWorldInfo.cpp
Labels: enhancement, test suite

#2748 Update the-3d-window.md
  docs/guide/images/navigation_mouse_controls.png
  docs/guide/the-3d-window.md
Labels: documentation

#2751 Initialize device reset callback
  src/controller/c/robot.c
Labels: bug, test suite

#2750 Fixed handling of UTF-8 paths for world files opened from Windows GUI
  docs/reference/changelog-r2021.md
  src/webots/launcher/launcher.c
Labels: bug

#2753 minor fix and cleanup of transmission ode joint
  src/ode/ode/src/joints/transmission.cpp
Labels: cleanup

#2732 Allow a robot to be added to the Transform node
  docs/reference/changelog-r2021.md
  docs/reference/transform.md
  src/controller/c/supervisor.c
  src/webots/nodes/WbAbstractTransform.cpp
  src/webots/nodes/WbTransform.cpp
  src/webots/nodes/WbTransform.hpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbNodeUtilities.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
Labels: enhancement, test suite

#2755 Improve webots server caching
  src/webots/core/WbHttpReply.cpp
  src/webots/core/WbHttpReply.hpp
  src/webots/gui/WbMultimediaStreamingServer.cpp
  src/webots/gui/WbMultimediaStreamingServer.hpp
  src/webots/gui/WbStreamingServer.cpp
  src/webots/gui/WbStreamingServer.hpp
  src/webots/gui/WbX3dStreamingServer.cpp
  src/webots/gui/WbX3dStreamingServer.hpp
Labels: enhancement, test suite

#2754 Fix fields order in openai_gym.wbt
  projects/samples/howto/openai_gym/worlds/openai_gym.wbt
Labels: test suite, test world update

#2761 Merge released into master
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/images/navigation_mouse_controls.png
  docs/guide/the-3d-window.md
Labels: documentation

#2741 Fix controllers logs printed in Webots console one step too late
  docs/guide/the-console.md
  docs/reference/changelog-r2021.md
  src/webots/control/WbControlledWorld.cpp
  src/webots/control/WbControlledWorld.hpp
  src/webots/control/WbController.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbSimulationView.hpp
Labels: bug, test suite

#2742 Allow the `wb_supervisor_node_reset_physics` function to reset physics of solid descendants
  docs/reference/changelog-r2021.md
  docs/reference/supervisor.md
  src/webots/nodes/WbMatter.hpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolid.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
Labels: enhancement, test suite

#2762 Merge master into develop
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/images/navigation_mouse_controls.png
  docs/guide/the-3d-window.md
  docs/guide/the-console.md
  docs/reference/changelog-r2021.md
  projects/samples/howto/openai_gym/worlds/openai_gym.wbt
  src/controller/c/robot.c
  src/webots/app/WbApplication.cpp
  src/webots/app/WbApplication.hpp
  src/webots/control/WbControlledWorld.cpp
  src/webots/control/WbControlledWorld.hpp
  src/webots/control/WbController.cpp
  src/webots/core/WbLog.cpp
  src/webots/core/WbLog.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbSimulationView.hpp
  src/webots/launcher/launcher.c
Labels: documentation, test suite, test world update

#2765 Fix vector size
  docs/reference/changelog-r2021.md
  lib/controller/matlab/wb_supervisor_node_get_velocity.m
Labels: bug

#2766 Fix update of PointSet
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbPointSet.cpp
Labels: bug, test suite

#2771 Fix ROS tests
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
Labels: bug, test ros, test suite, test world update

#2768 Fix ENU in the Inertial Unit
  docs/reference/changelog-r2021.md
  docs/reference/images/enu_nue.png
  docs/reference/images/roll_pitch_yaw.png
  docs/reference/inertialunit.md
  projects/default/controllers/ros/RosInertialUnit.cpp
  src/controller/c/inertial_unit.c
  src/webots/nodes/WbInertialUnit.cpp
Labels: bug, test suite

#2774 Add missing help for --no-rendering command line option
  docs/guide/starting-webots.md
  src/webots/gui/WbSingleTaskApplication.cpp
Labels: documentation, enhancement

#2778 Fix TurtleBot3 controller
  projects/robots/robotis/turtlebot/controllers/turtlebot3_ostacle_avoidance/turtlebot3_ostacle_avoidance.c
Labels: bug

#2772 Improve simulation server
  resources/web/server/session_server.py
  resources/web/server/simulation_server.py
  resources/web/server/www/favicon.ico
  resources/web/wwi/monitor.css
Labels: enhancement

#2782 Feature FIFA soccer ball
  docs/guide/appearances.md
  docs/guide/generate_objects_doc.py
  docs/guide/images/objects/balls/FifaSoccerBall/model.png
  docs/guide/images/objects/balls/FifaSoccerBall/model.thumbnail.jpg
  docs/guide/object-balls.md
  docs/guide/object-toys.md
  docs/reference/changelog-r2021.md
  projects/objects/balls/protos/FifaSoccerBall.proto
  projects/objects/balls/protos/icons/FifaSoccerBall.png
Labels: enhancement

#2785 `wb_supervisor_node_restart_controller` doesn't restart external controllers
  docs/reference/supervisor.md
Labels: documentation

#2781 Fix Physics plugin collision for the Group nodes
  docs/reference/changelog-r2021.md
  src/webots/engine/WbSimulationCluster.cpp
  src/webots/engine/WbSimulationCluster.hpp
Labels: bug, test suite
