Repository cyberbotics/webots, pull requests merged in 2021-12, with the labels that each got.

#3955 Correction of the texture mapping for the Mesh node
  docs/reference/changelog-r2021.md
  docs/reference/mesh.md
  src/webots/gui/WbImportWizard.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/scene_tree/WbExtendedStringEditor.cpp
Labels: bug, documentation, test suite, test sources

#3968 Fix extrusion
  projects/objects/geometries/protos/Extrusion.proto
  projects/objects/road/protos/CrashBarrier.proto
  projects/objects/traffic/protos/CautionPanel.proto
  projects/objects/traffic/protos/ExitPanel.proto
  projects/objects/traffic/protos/SpeedLimitPanel.proto
  projects/objects/traffic/protos/StopPanel.proto
  projects/objects/traffic/protos/YieldPanel.proto
  projects/vehicles/worlds/CH_Morges.wbt
  projects/vehicles/worlds/highway_overtake.wbt
  scripts/converter/convert_nue_to_enu_rub.py
Labels: bug, test suite

#3978 Clarify `WbSkin` model supported formats
  docs/reference/skin.md
Labels: documentation

#3981 Fix spoon.proto
  projects/objects/kitchen/utensils/protos/Spoon.proto
Labels: bug

#3991 Better explanation for light sensor demo
  projects/samples/devices/controllers/light_sensor/light_sensor.c
Labels: enhancement, documentation

#3995 Fix gear rotation in `coupled_motors.wbt`
  projects/samples/devices/worlds/coupled_motors.wbt
Labels: cleanup

#3999 Fix lidar tilt in `sick_point_cloud.wbt`
  projects/devices/sick/protos/SickLdMrs.proto
Labels: bug

#4006 Fix tinkerbots_demo.wbt
  projects/robots/kinematics/tinkerbots/controllers/crane/crane.c
  projects/robots/kinematics/tinkerbots/worlds/tinkerbots_demo.wbt
Labels: bug

#3998 Fixed ODE warning in track.wbt sample demo
  projects/samples/devices/controllers/track/track.c
  projects/samples/devices/worlds/track.wbt
Labels: cleanup

#4007 The sojourner video is missing
  docs/guide/sojourner.md
Labels: documentation

#4010 Fixes viewpoint in linear_motor.wbt
  projects/samples/devices/worlds/linear_motor.wbt
Labels: enhancement

#4000 Fix-sumo-mac
  projects/default/resources/Makefile
Labels: bug, test suite

#4004 Fix PR2 meshes
  projects/robots/clearpath/pr2/protos/Pr2.proto
  projects/robots/clearpath/pr2/protos/meshes/Mesh0.obj
  projects/robots/clearpath/pr2/protos/meshes/Mesh1.obj
  projects/robots/clearpath/pr2/protos/meshes/Mesh10.obj
  projects/robots/clearpath/pr2/protos/meshes/Mesh13.obj
  projects/robots/clearpath/pr2/protos/meshes/Mesh14.obj
  projects/robots/clearpath/pr2/protos/meshes/Mesh2.obj
  projects/robots/clearpath/pr2/protos/meshes/Mesh3.obj
  projects/robots/clearpath/pr2/protos/meshes/Mesh4.obj
  projects/robots/clearpath/pr2/protos/meshes/Mesh7.obj
  projects/robots/clearpath/pr2/protos/meshes/Mesh8.obj
  projects/robots/clearpath/pr2/protos/meshes/bl_caster_r_wheel_link_0.obj
  projects/robots/clearpath/pr2/protos/meshes/bl_caster_rotation_joint_0.obj
  projects/robots/clearpath/pr2/protos/meshes/br_caster_r_wheel_link_0.obj
  projects/robots/clearpath/pr2/protos/meshes/br_caster_rotation_joint_0.obj
  projects/robots/clearpath/pr2/protos/meshes/fl_caster_r_wheel_0.obj
  projects/robots/clearpath/pr2/protos/meshes/fr_caster_r_wheel_link_0.obj
  projects/robots/clearpath/pr2/protos/meshes/fr_caster_rotation_joint_0.obj
  projects/robots/clearpath/pr2/protos/meshes/l_forearm_cam_frame_0.obj
  projects/robots/clearpath/pr2/protos/meshes/l_forearm_cam_sensor_0.obj
  projects/robots/clearpath/pr2/protos/meshes/l_forearm_cam_sensor_2.obj
  projects/robots/clearpath/pr2/protos/meshes/l_gripper_l_finger_tip_contact_sensor_0.obj
  projects/robots/clearpath/pr2/protos/meshes/l_gripper_motor_slider_joint_1.obj
  projects/robots/clearpath/pr2/protos/meshes/l_gripper_r_finger_joint_0.obj
  projects/robots/clearpath/pr2/protos/meshes/l_gripper_r_finger_link_0.obj
  projects/robots/clearpath/pr2/protos/meshes/l_shoulder_pan_joint_0.obj
  projects/robots/clearpath/pr2/protos/meshes/l_shoulder_pan_link_0.obj
  projects/robots/clearpath/pr2/protos/meshes/l_wrist_flex_link_0.obj
  projects/robots/clearpath/pr2/protos/meshes/laser_tilt_mount_joint_0.obj
  projects/robots/clearpath/pr2/protos/meshes/r_forearm_cam_frame_0.obj
  projects/robots/clearpath/pr2/protos/meshes/r_gripper_r_finger_joint_0.obj
  projects/robots/clearpath/pr2/protos/meshes/r_gripper_r_finger_link_0.obj
  projects/robots/clearpath/pr2/protos/meshes/r_shoulder_pan_link_0.obj
  projects/robots/clearpath/pr2/protos/meshes/r_shoulder_pan_link_1.obj
  projects/robots/clearpath/pr2/protos/meshes/torso_lift_joint_0.obj
  projects/robots/clearpath/pr2/protos/meshes/torso_lift_motor_screw_joint_0.obj
  scripts/proto_splitter/proto2mesh.py
Labels: bug

#4002 Fix distance sensor orientation
  projects/robots/fp_robotics/p-rob3/protos/P-Grip.proto
  projects/robots/gctronic/e-puck/protos/E-puckDistanceSensor.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsDistanceSensor.proto
  projects/robots/surveyor/protos/SurveyorSrv1.proto
  projects/samples/devices/worlds/accelerometer.wbt
  projects/samples/devices/worlds/altimeter.wbt
  projects/samples/devices/worlds/battery.wbt
  projects/samples/devices/worlds/camera.wbt
  projects/samples/devices/worlds/camera_motion_blur.wbt
  projects/samples/devices/worlds/camera_noise_mask.wbt
  projects/samples/devices/worlds/camera_recognition.wbt
  projects/samples/devices/worlds/camera_segmentation.wbt
  projects/samples/devices/worlds/display.wbt
  projects/samples/devices/worlds/emitter_receiver.wbt
  projects/samples/devices/worlds/gps.wbt
  projects/samples/devices/worlds/gps_lat_long.wbt
  projects/samples/devices/worlds/led.wbt
  projects/samples/devices/worlds/lidar.wbt
  projects/samples/devices/worlds/light_sensor.wbt
  projects/samples/devices/worlds/pen.wbt
  projects/samples/devices/worlds/position_sensor.wbt
  projects/samples/devices/worlds/radar.wbt
  projects/samples/devices/worlds/receiver_noise.wbt
  projects/samples/devices/worlds/spherical_camera.wbt
  projects/samples/howto/binocular/worlds/binocular.wbt
  projects/samples/howto/texture_change/worlds/texture_change.wbt
  projects/samples/howto/url/worlds/url.wbt
  projects/samples/rendering/worlds/animated_skin.wbt
  tests/api/controllers/robot_urdf/prob3_reference.urdf
Labels: bug, regression, test suite, test world update

#4014 Restore rolling friction in changelog
  docs/reference/changelog-r2022.md
Labels: documentation

#4013 Avoid applying the backwards compability fix when USE/DEF is used
  src/webots/nodes/utils/WbNodeUtilities.cpp
Labels: bug

#4015 FLU wiki with focus on backward compability
  docs/wiki_flu.md
Labels: documentation

#4018 add pen limitation on the web
  docs/guide/web-scene.md
Labels: documentation

#4019 Fixed layout perspective of hinge joint with backlash demo
  projects/samples/devices/worlds/.hinge_joint_with_backlash.wbproj
Labels: enhancement

#4023 Fix cylinder of linear_motor.wbt
  projects/samples/devices/worlds/linear_motor.wbt
Labels: enhancement

#3956 Add support for Collada references
  docs/guide/object-shapes.md
  docs/reference/changelog-r2022.md
  docs/reference/mesh.md
  projects/shapes/protos/ColladaShapes.proto
  projects/shapes/protos/icons/ColladaShapes.png
  resources/nodes/Mesh.wrl
  src/webots/Makefile
  src/webots/core/WbQjsCollada.cpp
  src/webots/core/WbQjsCollada.hpp
  src/webots/core/WbTemplateEngine.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbMesh.hpp
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeOperations.hpp
  src/webots/scene_tree/WbExtendedStringEditor.cpp
  src/webots/scene_tree/WbExtendedStringEditor.hpp
Labels: feature, test suite, test ros

#4028 Fix-doc-worldinfo
  docs/reference/worldinfo.md
Labels: documentation

#4026 Fix backward compability crash for DEF nodes
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeOperations.hpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
Labels: bug, crash, test suite

#4025 Fixed crash when X3D exporting invalid geometries
  src/webots/nodes/WbGeometry.cpp
  src/webots/nodes/WbGroup.cpp
  src/webots/nodes/WbShape.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbTransform.cpp
Labels: crash

#4031 Fix example worlds
  projects/languages/cpp/worlds/example.wbt
  projects/languages/java/worlds/example.wbt
  projects/languages/python/worlds/example.wbt
Labels: enhancement

#4027 Fix ratslife crash
  src/webots/nodes/WbImageTexture.cpp
Labels: bug, crash, test suite, test sources

#4032 Fix-doc-installation-procedure
  docs/guide/installation-procedure.md
Labels: documentation

#4033 Update package for snap core20 and noetic
  scripts/packaging/webots_distro.c
Labels: enhancement

#4021 Add ROS Noetic CI tests
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
Labels: enhancement, test suite, test ros

#4016 add updated dialog
  projects/guided_tour.txt
  src/webots/Makefile
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbGuidedTour.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/gui/WbUpdatedDialog.cpp
  src/webots/gui/WbUpdatedDialog.hpp
Labels: enhancement

#4043 Fix depth fighting in `skin.wbt`
  projects/humans/skin_animated_humans/protos/skins/sandra.fbx
Labels: enhancement

#4038 Fix-memory-leak-gl-buffer
  docs/reference/changelog-r2022.md
  src/wren/StaticMesh.cpp
Labels: bug, test suite

#4039 Fix-default-stylesheet
  src/webots/core/WbPreferences.cpp
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbGuiApplication.hpp
Labels: bug

#4046 Fixes behavior when attempting to save in installation folder
  docs/reference/changelog-r2022.md
  src/webots/app/WbPerspective.cpp
  src/webots/app/WbPerspective.hpp
  src/webots/control/WbController.cpp
  src/webots/core/WbFileUtil.cpp
  src/webots/core/WbPreferences.cpp
  src/webots/core/WbPreferences.hpp
  src/webots/editor/WbBuildEditor.cpp
  src/webots/editor/WbTextBuffer.cpp
  src/webots/editor/WbTextEditor.cpp
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/gui/WbNewProjectWizard.cpp
Labels: bug, test sources

#3976 Blogpost release
  docs/blog/Webots-2022-a-release.md
  docs/blog/images/flu-enu.png
  docs/blog/images/skin.png
  docs/blog/index.md
  docs/blog/menu.md
  docs/reference/changelog-r2022.md
  resources/images/splash_images/human_skin.jpg
Labels: documentation

#4048 Merge released into master
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/web-scene.md
Labels: documentation

#4049 Fix-wiki-link
  docs/blog/Webots-2022-a-release.md
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/gui/WbUpdatedDialog.cpp
Labels: test sources

#4050 Merge master into develop
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/web-scene.md
Labels: documentation, test suite, test ros

#4057 Remove mentions of ROS Melodic from the documentation
  docs/blog/Webots-2022-a-release.md
  docs/guide/tutorial-9-using-ros.md
  docs/guide/using-ros.md
  projects/robots/universal_robots/resources/ros_package/ur_e_webots/README.md
Labels: documentation

#4059 update release date
  docs/blog/Webots-2022-a-release.md
  docs/reference/changelog-r2022.md
Labels: documentation

#4055 Switch mSolid endPoint pointer to NULL when using static environnement
  src/webots/nodes/WbSolidReference.cpp
  src/webots/nodes/WbSolidReference.hpp
Labels: cleanup, test suite

#4058 Removed useless include
  src/webots/gui/WbDragScaleEvent.hpp
Labels: cleanup

#4065 Fix underscores in changelog and add flu/enu mention
  docs/reference/changelog-r2022.md
Labels: documentation, cleanup

#4068 Update date in tutorials
  docs/guide/tutorial-3-appearance.md
  docs/guide/tutorial-8-the-supervisor.md
  docs/js/showdown-extensions.js
Labels: documentation

#3971 Feature-export-html5-cloud
  docs/reference/changelog-r2022.md
  resources/icons/dark/animation_black_button.png
  resources/icons/dark/animation_red_button.png
  resources/icons/dark/share_button.png
  resources/icons/dark/share_red_button.png
  resources/icons/light/animation_black_button.png
  resources/icons/light/animation_red_button.png
  resources/icons/light/share_button.png
  resources/icons/light/share_red_button.png
  src/webots/Makefile
  src/webots/core/WbPreferences.cpp
  src/webots/engine/WbAnimationRecorder.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbPreferencesDialog.hpp
  src/webots/gui/WbShareWindow.cpp
  src/webots/gui/WbShareWindow.hpp
  src/webots/gui/WbSimulationView.cpp
Labels: feature

#4075 Fix online documentation
  docs/js/webots_documentation_loader.js
Labels: bug, documentation

#4073 Fixed small memory leaks
  src/webots/core/WbTelemetry.cpp
  src/webots/core/WbWebotsUpdateManager.cpp
  src/webots/nodes/utils/WbDownloader.cpp
Labels: cleanup

#4076 Fix window proto
  projects/objects/apartment_structure/protos/Window.proto
Labels: bug

#4077 Fixed repository computation
  scripts/get_git_info/get_git_info.sh
Labels: bug

#4078 Change welcome message
  src/webots/gui/WbUpdatedDialog.cpp
Labels: cleanup, test sources
