Repository cyberbotics/webots, pull requests merged in 2021-04, with the labels that each got.

#2926 Merge master into develop
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/reference/camera.md
  docs/reference/changelog-r2021.md
  scripts/packaging/publish_release.py
  src/controller/java/controller.i
  src/controller/python/controller.i
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbSimulationView.cpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/utils/WbObjectDetection.cpp
  src/webots/nodes/utils/WbVisualBoundingSphere.cpp
  src/webots/nodes/utils/WbVisualBoundingSphere.hpp
Labels: test suite

#2930 Add height parameter to the Robotino3Platform
  projects/robots/festo/robotino3/protos/Robotino3Platform.proto
Labels: enhancement

#2912 Calibrate the Tiago robot and simulation
  projects/robots/pal_robotics/tiago_base/protos/TiagoBase.proto
  projects/robots/pal_robotics/tiago_steel/worlds/tiago_steel.wbt
Labels: bug

#2928 Fix cppcheck 2.4.1 errors
  projects/robots/epfl/lis/controllers/blimp/js.h
  projects/samples/curriculum/controllers/intermediate_behavior_based/intermediate_behavior_based.c
  projects/samples/curriculum/controllers/intermediate_behavior_based/intermediate_behavior_based_corr.c
  resources/projects/libraries/qt_utils/motion_editor/MotionPlayer.cpp
  resources/projects/libraries/qt_utils/motion_editor/PoseWidget.cpp
  src/controller/c/default_robot_window.c
  src/webots/core/WbSysInfo.cpp
  src/webots/gui/WbMultimediaStreamingLimiter.cpp
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbDevice.cpp
  src/webots/nodes/WbDevice.hpp
  src/webots/nodes/WbDisplay.cpp
  src/webots/nodes/WbLed.cpp
  src/webots/nodes/utils/WbDictionary.cpp
  src/webots/wren/WbWrenCamera.cpp
  src/wren/PbrMaterial.cpp
  src/wren/PhongMaterial.cpp
  src/wren/Scene.hpp
  src/wren/StaticMesh.cpp
  src/wren/StaticMesh.hpp
  tests/sources/test_cppcheck.py
Labels: test sources, test suite

#2935 Updating Darwin-opHinge2.proto with virtual RoboCup procedure
  projects/robots/robotis/darwin-op/protos/Darwin-opHinge2.proto
Labels: enhancement

#2943 update tiago_reference
  tests/api/controllers/robot_urdf/tiago_reference.urdf
Labels: bug, test suite

#2941 fix net
  projects/appearances/protos/Grass.proto
  projects/appearances/protos/textures/grass/grass_artificial_white_base_color.jpg
  projects/default/worlds/textures/net.png
  projects/samples/contests/robocup/protos/RobocupGoal.proto
  projects/samples/contests/robocup/protos/RobocupSoccerField.proto
  projects/samples/contests/robocup/protos/WhiteGrass.proto
Labels: bug, test suite

#2944 Merge master into develop
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/pioneer-3dx.md
  projects/robots/epfl/lis/controllers/blimp/js.h
  projects/samples/curriculum/controllers/intermediate_behavior_based/intermediate_behavior_based.c
  projects/samples/curriculum/controllers/intermediate_behavior_based/intermediate_behavior_based_corr.c
  resources/projects/libraries/qt_utils/motion_editor/MotionPlayer.cpp
  resources/projects/libraries/qt_utils/motion_editor/PoseWidget.cpp
  src/controller/c/default_robot_window.c
  src/webots/core/WbSysInfo.cpp
  src/webots/gui/WbMultimediaStreamingLimiter.cpp
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbDevice.cpp
  src/webots/nodes/WbDevice.hpp
  src/webots/nodes/WbDisplay.cpp
  src/webots/nodes/WbLed.cpp
  src/webots/nodes/utils/WbDictionary.cpp
  src/webots/wren/WbWrenCamera.cpp
  src/wren/PbrMaterial.cpp
  src/wren/PhongMaterial.cpp
  src/wren/Scene.hpp
  src/wren/StaticMesh.cpp
  src/wren/StaticMesh.hpp
  tests/sources/test_cppcheck.py
Labels: test suite

#2950 Print generated URDF test file if test fails
  tests/api/controllers/robot_urdf/robot_urdf.c
Labels: enhancement, test suite

#2954 Fix joint positions in URDF CLI export
  src/webots/gui/WbSingleTaskApplication.cpp
  src/webots/maths/WbVector3.hpp
  src/webots/maths/WbVector4.hpp
  src/webots/nodes/WbBallJoint.hpp
  src/webots/nodes/WbBasicJoint.hpp
  src/webots/nodes/WbHinge2Joint.hpp
  src/webots/nodes/WbHingeJoint.hpp
  src/webots/nodes/WbSliderJoint.hpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
Labels: bug, test suite

#2956 Fix variable name preventing compilation
  src/webots/gui/WbSingleTaskApplication.cpp
Labels: bug, test suite

#2957 Fixed bug in Robot::getDevice()
  docs/reference/changelog-r2021.md
  src/controller/cpp/Robot.cpp
  src/controller/java/controller.i
  src/controller/python/controller.i
Labels: bug, test suite

#2962 Remove hidden parameter field connection
  src/webots/vrml/WbField.cpp
Labels: enhancement, test suite

#2953 Enhancement defaultShader for webgl
  resources/wren/shaders/default.frag
  resources/wren/shaders/default.vert
Labels: enhancement, test suite

#2960 Fix CLI URDF node search
  src/webots/gui/WbSingleTaskApplication.cpp
Labels: bug

#2964 Fix the saving of hidden field for BallJoint
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbGroup.cpp
  src/webots/nodes/WbSolid.cpp
Labels: bug, test suite

#2971 Merge master into develop
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/reference/changelog-r2021.md
  src/controller/cpp/Robot.cpp
  src/controller/java/controller.i
  src/controller/python/controller.i
  src/webots/nodes/WbGroup.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/vrml/WbField.cpp
Labels: test suite

#2961 Fix Camera lens distortion
  docs/reference/changelog-r2021.md
  resources/wren/shaders/lens_distortion.frag
Labels: bug, test suite

#2974 Fix typo in various files
  projects/samples/devices/controllers/gps_lat_long/gps_lat_long.c
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/utils/WbBoundingSphere.hpp
  tests/api/controllers/joint_end_point_collision/joint_end_point_collision.c
Labels: bug

#2972 Fix typo verticalfieldofview
  docs/reference/changelog-r2021.md
  projects/devices/hokuyo/protos/HokuyoUtm30lx.proto
Labels: enhancement

#2978 Fixed C++ include in the doc
  docs/guide/controller-programming.md
Labels: documentation

#2983 Fix updating Lidar.type during simulation run
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/WbLidar.hpp
Labels: crash, test suite

#2987 Fix publish release script
  scripts/packaging/publish_release.py
Labels: bug

#2990 Merge master into develop
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2021.md
  docs/guide/controller-programming.md
  docs/guide/starting-webots.md
  docs/reference/changelog-r2021.md
  projects/devices/hokuyo/protos/HokuyoUtm30lx.proto
  projects/samples/devices/controllers/gps_lat_long/gps_lat_long.c
  resources/wren/shaders/lens_distortion.frag
  scripts/packaging/publish_release.py
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/WbLidar.hpp
  src/webots/nodes/utils/WbBoundingSphere.hpp
  tests/api/controllers/joint_end_point_collision/joint_end_point_collision.c
Labels: test suite, test world update

#2991 Improve wb_supervisor_node_reset_physics
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbMatter.hpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolid.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  tests/api/controllers/supervisor_set_position_of_dynamic_object/supervisor_set_position_of_dynamic_object.c
Labels: bug, test suite

#2995 Remove blank line proto info
  src/webots/vrml/WbProtoModel.cpp
Labels: bug

#2997 Hotfix lib controller update after reset
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  tests/api/controllers/supervisor_update_after_simulation_reset/.gitignore
  tests/api/controllers/supervisor_update_after_simulation_reset/Makefile
  tests/api/controllers/supervisor_update_after_simulation_reset/supervisor_update_after_simulation_reset.c
  tests/api/worlds/supervisor_update_after_reset_simulation.wbt
Labels: crash, test suite

#3001 Fix loading of hidden position3 for Ball
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbHinge2Joint.cpp
  src/webots/nodes/WbJoint.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/utils/WbHiddenKinematicParameters.cpp
  src/webots/vrml/WbNode.cpp
  tests/parser/controllers/hidden_parameter_single/hidden_parameter_single.c
  tests/parser/expected_results.txt
  tests/parser/worlds/hidden_parameter_single.wbt
  tests/physics/controllers/generic_sensor/.gitignore
  tests/physics/controllers/generic_sensor/Makefile
  tests/physics/controllers/generic_sensor/generic_sensor.c
  tests/physics/controllers/hidden_parameter_single/.gitignore
  tests/physics/controllers/hidden_parameter_single/Makefile
  tests/physics/controllers/hidden_parameter_single/hidden_parameter_single.c
  tests/physics/protos/RobotSlot.proto
  tests/physics/protos/RobotWithBallJoint.proto
  tests/physics/protos/RobotWithHinge2Joint.proto
  tests/physics/protos/RobotWithHingeJoint.proto
  tests/physics/protos/RobotWithSliderJoint.proto
  tests/physics/worlds/hidden_parameter_single.wbt
Labels: bug, test suite

#3002 Add loading time and average real time factor to performance log
  docs/reference/changelog-r2021.md
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/util/WbPerformanceLog.cpp
  src/webots/util/WbPerformanceLog.hpp
Labels: enhancement

#2998 Fix configuration of IntertialUnit after reset
  src/webots/nodes/WbInertialUnit.cpp
Labels: bug, test suite

#3016 Merge master into develop
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbHinge2Joint.cpp
  src/webots/nodes/WbJoint.cpp
  src/webots/nodes/WbMatter.hpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolid.hpp
  src/webots/nodes/utils/WbHiddenKinematicParameters.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/vrml/WbNode.cpp
  tests/api/controllers/supervisor_set_position_of_dynamic_object/supervisor_set_position_of_dynamic_object.c
  tests/parser/controllers/hidden_parameter_single/hidden_parameter_single.c
  tests/parser/expected_results.txt
  tests/parser/worlds/hidden_parameter_single.wbt
  tests/physics/controllers/generic_sensor/.gitignore
  tests/physics/controllers/generic_sensor/Makefile
  tests/physics/controllers/generic_sensor/generic_sensor.c
  tests/physics/controllers/hidden_parameter_single/.gitignore
  tests/physics/controllers/hidden_parameter_single/Makefile
  tests/physics/controllers/hidden_parameter_single/hidden_parameter_single.c
  tests/physics/protos/RobotSlot.proto
  tests/physics/protos/RobotWithBallJoint.proto
  tests/physics/protos/RobotWithHinge2Joint.proto
  tests/physics/protos/RobotWithHingeJoint.proto
  tests/physics/protos/RobotWithSliderJoint.proto
  tests/physics/worlds/hidden_parameter_single.wbt
Labels: test suite

#3019 Feature labels animation
  docs/reference/changelog-r2021.md
  resources/web/templates/x3d_playback.html
  resources/web/wwi/animation.js
  resources/web/wwi/webots.js
  resources/web/wwi/x3d_scene.js
  src/webots/engine/WbAnimationRecorder.cpp
  src/webots/engine/WbAnimationRecorder.hpp
  src/webots/gui/WbX3dStreamingServer.cpp
  src/webots/gui/WbX3dStreamingServer.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
Labels: enhancement
