Repository cyberbotics/webots, pull requests merged in 2021-06, with the labels that each got.

#3113 Fix CentOS compilation
  src/webots/Makefile
Labels: bug

#3112 Feature remove offline doc
  Makefile
  docs/.gitignore
  resources/.gitignore
  resources/Makefile
  resources/translations/wb_de.ts
  resources/translations/wb_es.ts
  resources/translations/wb_fr.ts
  resources/translations/wb_generic.ts
  resources/translations/wb_it.ts
  resources/translations/wb_ja_JP.ts
  resources/translations/wb_zh_CN.ts
  scripts/get_branch/get_branch.sh
  scripts/packaging/files_core.txt
  scripts/packaging/files_doc.txt
  scripts/packaging/webots_distro.c
  src/webots/Makefile
  src/webots/app/WbPerspective.cpp
  src/webots/app/WbPerspective.hpp
  src/webots/core/WbApplicationInfo.cpp
  src/webots/core/WbApplicationInfo.hpp
  src/webots/gui/WbDocumentation.cpp
  src/webots/gui/WbDocumentation.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/vrml/WbProtoModel.cpp
  src/webots/vrml/WbProtoModel.hpp
  src/wren/GlState.cpp
Labels: feature, test suite

#3116 Fixes Windows nightly builds
  scripts/packaging/files_msys64.txt
Labels: bug, test distribution

#3117 Update Robot node description
  resources/nodes/Robot.wrl
Labels: bug

#3119 Enhancement guided tour
  projects/guided_tour.txt
  projects/robots/robotis/darwin-op/worlds/soccer.wbt
  projects/robots/softbank/nao/worlds/nao_room.wbt
Labels: enhancement

#3109 Fix search for proto parameter node instance
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbBaseNode.hpp
  src/webots/nodes/WbBasicJoint.cpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  src/webots/scene_tree/WbNodePane.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbNode.cpp
  tests/protos/controllers/nested_parameter_transform_node/nested_parameter_transform_node.c
  tests/protos/worlds/nested_parameter_transform_node.wbt
Labels: bug, test suite

#3122 Add Sick S300 Lidar
  docs/guide/images/sensors/sick_s300.png
  docs/guide/images/sensors/sick_s300.thumbnail.png
  docs/guide/images/sensors/sick_s300_icon.png
  docs/guide/lidar-sensors.md
  docs/guide/sensors.md
  docs/reference/changelog-r2021.md
  projects/devices/sick/protos/SickS300.proto
  projects/devices/sick/protos/icons/SickS300.png
  projects/devices/sick/protos/meshes/sick_s300_black.dae
  projects/devices/sick/protos/meshes/sick_s300_yellow.dae
Labels: feature

#3124 Removed use of undefined variable
  resources/Makefile.include
Labels: cleanup

#3125 Fixed several memory leaks in supervisor API
  src/controller/c/supervisor.c
Labels: bug, test suite

#3129 cleanup webotsjs api
  resources/web/wwi/Server.js
  resources/web/wwi/WebotsStreaming.js
  resources/web/wwi/webots.js
Labels: cleanup, enhancement

#3135 Update mir100.md
  docs/guide/mir100.md
Labels: documentation

#3136 Update keyboard_conveyor_platform.c
  projects/objects/factory/conveyors/controllers/keyboard_conveyor_platform/keyboard_conveyor_platform.c
Labels: cleanup

#3134 Fix world update error Mir100
  projects/robots/mir/mir100/protos/Mir100.proto
  projects/robots/mir/mir100/worlds/mir100.wbt
Labels: bug, test world update

#3126 Fix test suite on windows
  src/webots/maths/WbPrecision.cpp
  src/webots/maths/WbPrecision.hpp
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbJoint.cpp
  src/webots/nodes/WbSliderJoint.cpp
  src/webots/nodes/WbSolid.cpp
  tests/api/controllers/extern/extern.c
  tests/api/controllers/robot_urdf/prob3_reference.urdf
  tests/api/controllers/robot_urdf/robot_urdf.c
  tests/api/controllers/robot_urdf/tiago_reference.urdf
  tests/api/controllers/robot_urdf/ur5e_reference.urdf
  tests/parser/Makefile
  tests/physics/Makefile
  tests/physics/controllers/generic_sensor/generic_sensor.c
  tests/protos/Makefile
  tests/rendering/Makefile
Labels: cleanup, test suite

#3137 fix matlab makefile
  src/controller/matlab/Makefile
Labels: bug

#3141 Fix link to Contact Us section in documentation
  docs/guide/actuators.md
  docs/guide/robots.md
  docs/guide/sensors.md
Labels: documentation

#3147 remove nodejs
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/nodejs_windows_installer.sh
Labels: cleanup, test suite

#3149 Merge released into master
  docs/discord/development-2019.md
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/actuators.md
  docs/guide/controller-plugin.md
  docs/guide/robotis-op2.md
  docs/guide/robotis-op3.md
  docs/guide/robots.md
  docs/guide/sensors.md
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/guide/youbot.md
  docs/js/showdown-extensions.js
  docs/reference/accelerometer.md
  docs/reference/connector.md
  docs/reference/display.md
  docs/reference/distancesensor.md
  docs/reference/gyro.md
  docs/reference/lightsensor.md
  docs/tests/test_references.py
Labels: documentation

#2951 Add JetBot robot
  docs/guide/images/robots/jetbot/JetBotRaspberryPiCamera.png
  docs/guide/images/robots/jetbot/JetBotRaspberryPiCamera.thumbnail.png
  docs/guide/images/robots/jetbot/icon.png
  docs/guide/images/robots/jetbot/jetbot.wbt.png
  docs/guide/images/robots/jetbot/jetbot.wbt.thumbnail.jpg
  docs/guide/images/robots/jetbot/model.png
  docs/guide/images/robots/jetbot/model.thumbnail.png
  docs/guide/images/sbc/nvidia_jetson_nano.png
  docs/guide/images/sbc/nvidia_jetson_nano.thumbnail.png
  docs/guide/images/sbc/nvidia_jetson_nano_icon.png
  docs/guide/jetbot.md
  docs/guide/menu.md
  docs/guide/robots.md
  docs/guide/scenes/jetbot/jetbot.meta.json
  docs/guide/scenes/jetbot/jetbot.x3d
  docs/guide/scenes/jetbot/textures/brushed_aluminium_base_color.jpg
  docs/guide/scenes/jetbot/textures/brushed_aluminium_normal.1.jpg
  docs/guide/scenes/jetbot/textures/brushed_aluminium_normal.jpg
  docs/guide/scenes/jetbot/textures/brushed_aluminium_roughness.1.jpg
  docs/guide/scenes/jetbot/textures/brushed_aluminium_roughness.jpg
  docs/guide/scenes/jetbot/textures/jetson_ethernet_port.jpg
  docs/guide/scenes/jetbot/textures/jetson_power_plug.jpg
  docs/guide/scenes/jetbot/textures/jetson_usb_mini_port.jpg
  docs/guide/scenes/jetbot/textures/jetson_usb_port.jpg
  docs/guide/scenes/jetbot/textures/jetson_video_port.jpg
  docs/guide/scenes/jetbot/textures/pcb_base_color.jpg
  docs/guide/scenes/jetbot/textures/pcb_metalness.jpg
  docs/guide/scenes/jetbot/textures/pcb_normal.jpg
  docs/guide/scenes/jetbot/textures/pcb_occlusion.jpg
  docs/guide/scenes/jetbot/textures/pcb_roughness.jpg
  docs/guide/scenes/jetbot/textures/raspberry_pi_camera.jpg
  docs/guide/single-board-computers.md
  docs/reference/changelog-r2021.md
  projects/devices/nvidia/protos/JetsonNano.proto
  projects/devices/nvidia/protos/icons/JetsonNano.png
  projects/devices/nvidia/protos/meshes/jetson_heat_sink.stl
  projects/devices/nvidia/protos/textures/jetson_ethernet_port.jpg
  projects/devices/nvidia/protos/textures/jetson_power_plug.jpg
  projects/devices/nvidia/protos/textures/jetson_usb_mini_port.jpg
  projects/devices/nvidia/protos/textures/jetson_usb_port.jpg
  projects/devices/nvidia/protos/textures/jetson_video_port.jpg
  projects/robots/Makefile
  projects/robots/nvidia/jetbot/controllers/Makefile
  projects/robots/nvidia/jetbot/controllers/jetbot_basic_motion/.gitignore
  projects/robots/nvidia/jetbot/controllers/jetbot_basic_motion/Makefile
  projects/robots/nvidia/jetbot/controllers/jetbot_basic_motion/jetbot_basic_motion.c
  projects/robots/nvidia/jetbot/libraries/jetbot_python_control/jetbot_python_control.py
  projects/robots/nvidia/jetbot/protos/JetBot.proto
  projects/robots/nvidia/jetbot/protos/JetBotRaspberryPiCamera.proto
  projects/robots/nvidia/jetbot/protos/icons/JetBot.png
  projects/robots/nvidia/jetbot/protos/icons/JetBotRaspberryPiCamera.png
  projects/robots/nvidia/jetbot/protos/meshes/chassis.stl
  projects/robots/nvidia/jetbot/protos/meshes/display.stl
  projects/robots/nvidia/jetbot/protos/meshes/power_bank.stl
  projects/robots/nvidia/jetbot/protos/meshes/wheel.stl
  projects/robots/nvidia/jetbot/protos/textures/raspberry_pi_camera.jpg
  projects/robots/nvidia/jetbot/worlds/.jetbot.wbproj
  projects/robots/nvidia/jetbot/worlds/jetbot.wbt
  scripts/web_component_studio/components.json
Labels: feature, test suite

#3151 Merge master into develop
  docs/discord/development-2019.md
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/actuators.md
  docs/guide/controller-plugin.md
  docs/guide/robotis-op2.md
  docs/guide/robotis-op3.md
  docs/guide/robots.md
  docs/guide/sensors.md
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/guide/youbot.md
  docs/js/showdown-extensions.js
  docs/reference/accelerometer.md
  docs/reference/connector.md
  docs/reference/display.md
  docs/reference/distancesensor.md
  docs/reference/gyro.md
  docs/reference/lightsensor.md
  docs/tests/test_references.py
Labels: documentation

#3153 fix nightly build on windows develop
  .github/workflows/test_suite_windows_develop.yml
  .github/workflows/tests_sources.yml
Labels: bug

#3150 Fix asymmetric friction
  docs/reference/changelog-r2021.md
  src/webots/engine/WbSimulationCluster.cpp
  src/webots/nodes/WbBox.cpp
  src/webots/nodes/WbCylinder.cpp
Labels: bug, test suite

#3144 cleanup web components
  resources/web/wwi/WebotsAnimation.js
  resources/web/wwi/WebotsStreaming.js
Labels: cleanup

#3155 Added Viewpoint in world converter scripts
  docs/reference/viewpoint.md
  scripts/converter/convert_eun_to_nue.py
  scripts/converter/convert_nue_to_enu.py
Labels: enhancement

#3166 Fix size animation web component
  resources/web/templates/x3d_playback.html
  resources/web/wwi/WebotsAnimation.js
Labels: enhancement

#3121 Add Summit-XL Steel
  docs/guide/images/robots/summit_xl_steel/icon.png
  docs/guide/images/robots/summit_xl_steel/model.png
  docs/guide/images/robots/summit_xl_steel/model.thumbnail.png
  docs/guide/images/robots/summit_xl_steel/summit_xl_steel.wbt.png
  docs/guide/images/robots/summit_xl_steel/summit_xl_steel.wbt.thumbnail.jpg
  docs/guide/menu.md
  docs/guide/robots.md
  docs/guide/scenes/summit-xl-steel/summit-xl-steel.meta.json
  docs/guide/scenes/summit-xl-steel/summit-xl-steel.x3d
  docs/guide/scenes/summit-xl-steel/textures/plastic_rough_normal.jpg
  docs/guide/scenes/summit-xl-steel/textures/plastic_rough_roughness.jpg
  docs/guide/summit-xl-steel.md
  docs/reference/changelog-r2021.md
  projects/robots/Makefile
  projects/robots/robotnik/summit_xl_steel/controllers/Makefile
  projects/robots/robotnik/summit_xl_steel/controllers/keyboard_control/.gitignore
  projects/robots/robotnik/summit_xl_steel/controllers/keyboard_control/Makefile
  projects/robots/robotnik/summit_xl_steel/controllers/keyboard_control/keyboard_control.c
  projects/robots/robotnik/summit_xl_steel/protos/SummitXlSteel.proto
  projects/robots/robotnik/summit_xl_steel/protos/icons/SummitXlSteel.png
  projects/robots/robotnik/summit_xl_steel/protos/meshes/omni_wheel_rims_ext.dae
  projects/robots/robotnik/summit_xl_steel/protos/meshes/omni_wheel_rims_int.dae
  projects/robots/robotnik/summit_xl_steel/protos/meshes/omni_wheel_rollers_ext.dae
  projects/robots/robotnik/summit_xl_steel/protos/meshes/omni_wheel_rollers_int.dae
  projects/robots/robotnik/summit_xl_steel/protos/meshes/orbbec_astra.dae
  projects/robots/robotnik/summit_xl_steel/protos/meshes/orbbec_astra_cover.dae
  projects/robots/robotnik/summit_xl_steel/protos/meshes/robotnik_logo_chasis.stl
  projects/robots/robotnik/summit_xl_steel/protos/meshes/summit_xls_chapas_inox_tapas.stl
  projects/robots/robotnik/summit_xl_steel/protos/meshes/summit_xls_chapas_inox_tapas_front.stl
  projects/robots/robotnik/summit_xl_steel/protos/meshes/summit_xls_chassis.dae
  projects/robots/robotnik/summit_xl_steel/worlds/.summit_xl_steel.wbproj
  projects/robots/robotnik/summit_xl_steel/worlds/summit_xl_steel.wbt
  scripts/web_component_studio/components.json
Labels: feature

#3161 Fix `test suite` CI on ubuntu 18
  tests/test_suite.py
Labels: test suite

#3171 Fix export of & in x3d
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolid.hpp
Labels: bug

#3174 Fix Context Menu Refresh
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/scene_tree/WbTreeView.cpp
  src/webots/scene_tree/WbTreeView.hpp
Labels: crash

#3175 Add force/torque scale factor to Worldinfo
  docs/guide/the-3d-window.md
  docs/reference/changelog-r2021.md
  docs/reference/worldinfo.md
  resources/nodes/WorldInfo.wrl
  src/webots/gui/WbDragSolidEvent.cpp
  src/webots/gui/WbDragSolidEvent.hpp
  src/webots/nodes/WbWorldInfo.cpp
  src/webots/nodes/WbWorldInfo.hpp
Labels: enhancement, test suite

#3181 Fix windows nightly build
  scripts/packaging/files_core.txt
Labels: bug, test distribution

#3180 Publish libcontroller from master branch
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  scripts/packaging/sync_controller_lib.sh
Labels: enhancement, test distribution

#3186 Removed obsolete Python 2.7 tests
  .github/workflows/tests_sources.yml
Labels: cleanup

#3190 Don't fire tests on ready_for_review event
  .github/workflows/tests_doc.yml
  .github/workflows/tests_sources.yml
Labels: cleanup

#3189 Fix reconnecting extern controllers
  docs/reference/changelog-r2021.md
  src/webots/control/WbControlledWorld.cpp
Labels: enhancement, test suite

#3191 Fix border color for lens distortion
  docs/reference/changelog-r2021.md
  resources/wren/shaders/lens_distortion.frag
Labels: enhancement, test suite

#3193 Merge R2021b and R2021a rev1 change log
  docs/reference/changelog-r2021.md
Labels: documentation

#3197 Avoid Windows deleting webots-libcontroller header files
  scripts/packaging/sync_controller_lib.sh
Labels: bug

#3200 Fix field/context conversion from JavaScript to Lua
  src/webots/vrml/WbProtoTemplateEngine.cpp
Labels: bug, test suite

#3205 Correct supported sound extensions
  docs/reference/speaker.md
Labels: documentation

#3206 fix matlab gitignore
  lib/controller/matlab/.gitignore
Labels: cleanup

#3192 Fix robot windows of robotbenchmark simulations
  docs/reference/changelog-r2021.md
  projects/samples/robotbenchmark/highway_driving/plugins/robot_windows/highway_driving/highway_driving.html
  projects/samples/robotbenchmark/highway_driving/plugins/robot_windows/highway_driving/highway_driving.js
  projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon_supervisor/marathon_supervisor.c
  projects/samples/robotbenchmark/humanoid_marathon/plugins/robot_windows/humanoid_marathon/humanoid_marathon.html
  projects/samples/robotbenchmark/humanoid_marathon/plugins/robot_windows/humanoid_marathon/humanoid_marathon.js
  projects/samples/robotbenchmark/humanoid_sprint/plugins/robot_windows/humanoid_sprint/humanoid_sprint.html
  projects/samples/robotbenchmark/humanoid_sprint/plugins/robot_windows/humanoid_sprint/humanoid_sprint.js
  projects/samples/robotbenchmark/include/tabs.css
  projects/samples/robotbenchmark/inverted_pendulum/plugins/robot_windows/inverted_pendulum/inverted_pendulum.html
  projects/samples/robotbenchmark/inverted_pendulum/plugins/robot_windows/inverted_pendulum/inverted_pendulum.js
  projects/samples/robotbenchmark/maze_runner/plugins/robot_windows/maze_runner/maze_runner.html
  projects/samples/robotbenchmark/maze_runner/plugins/robot_windows/maze_runner/maze_runner.js
  projects/samples/robotbenchmark/obstacle_avoidance/plugins/robot_windows/obstacle_avoidance/obstacle_avoidance.html
  projects/samples/robotbenchmark/obstacle_avoidance/plugins/robot_windows/obstacle_avoidance/obstacle_avoidance.js
  projects/samples/robotbenchmark/pick_and_place/plugins/robot_windows/pick_and_place/pick_and_place.html
  projects/samples/robotbenchmark/pick_and_place/plugins/robot_windows/pick_and_place/pick_and_place.js
  projects/samples/robotbenchmark/pit_escape/plugins/robot_windows/pit_escape/pit_escape.html
  projects/samples/robotbenchmark/pit_escape/plugins/robot_windows/pit_escape/pit_escape.js
  projects/samples/robotbenchmark/robot_programming/plugins/robot_windows/robot_programming/robot_programming.html
  projects/samples/robotbenchmark/robot_programming/plugins/robot_windows/robot_programming/robot_programming.js
  projects/samples/robotbenchmark/square_path/plugins/robot_windows/square_path/square_path.html
  projects/samples/robotbenchmark/square_path/plugins/robot_windows/square_path/square_path.js
  projects/samples/robotbenchmark/viewpoint_control/plugins/robot_windows/viewpoint_control/topview.png
  projects/samples/robotbenchmark/viewpoint_control/plugins/robot_windows/viewpoint_control/viewpoint_control.html
  projects/samples/robotbenchmark/viewpoint_control/plugins/robot_windows/viewpoint_control/viewpoint_control.js
  projects/samples/robotbenchmark/viewpoint_control/protos/ViewpointControlBenchmark.proto
  projects/samples/robotbenchmark/viewpoint_control/protos/icons/ViewpointControlBenchmark.png
  projects/samples/robotbenchmark/viewpoint_control/worlds/.viewpoint_control.wbproj
  projects/samples/robotbenchmark/viewpoint_control/worlds/viewpoint_control.wbt
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/pan_tilt_camera_view/pan_tilt_camera_view.html
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/pan_tilt_camera_view/pan_tilt_camera_view.js
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/visual_tracking/visual_tracking.html
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/visual_tracking/visual_tracking.js
  projects/samples/robotbenchmark/wall_following/plugins/robot_windows/wall_following/wall_following.html
  projects/samples/robotbenchmark/wall_following/plugins/robot_windows/wall_following/wall_following.js
Labels: bug

#3167 Fix incorrect resetting of Transform
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbPropeller.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolid.hpp
  src/webots/nodes/WbTransform.cpp
  src/webots/nodes/WbTransform.hpp
  src/webots/nodes/utils/WbTemplateManager.cpp
  tests/api/controllers/supervisor_reset_transform/.gitignore
  tests/api/controllers/supervisor_reset_transform/Makefile
  tests/api/controllers/supervisor_reset_transform/supervisor_reset_transform.c
  tests/api/worlds/supervisor_reset_transform.wbt
Labels: bug, test suite

#3196 Various fixes
  docs/reference/lidar.md
  docs/reference/linearmotor.md
  docs/reference/rotationalmotor.md
  src/controller/c/robot.c
  src/webots/control/WbController.hpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/scene_tree/WbTreeItem.cpp
  src/webots/vrml/WbNodeFactory.hpp
Labels: enhancement, test suite

#3204 Fix Windows libcontroller determinism
  src/controller/c/Makefile
  src/controller/cpp/Makefile
Labels: test distribution

#3198 Add the name of a solid next to it in tree
  docs/reference/changelog-r2021.md
  src/webots/scene_tree/WbTreeItem.cpp
Labels: enhancement

#3211 Fix the `wb_supervisor_node_get_contact_points` MATLAB API function
  lib/controller/matlab/wb_supervisor_node_get_contact_points.m
Labels: bug

#3203 Fix reference to Shape documentation page
  docs/reference/billboard.md
Labels: documentation

#3210 Don't create url for generic tabs in docs
  docs/guide/web-simulation.md
  docs/reference/javascript-procedural-proto.md
  resources/web/wwi/viewer.js
Labels: enhancement

#3173 Fix `test ros` CI for ubuntu 18
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  docs/guide/tutorial-8-using-ros.md
  scripts/install/linux_test_dependencies.sh
  scripts/install/linux_web_viewer_dependencies.sh
  scripts/install/msys64_installer.sh
Labels: test ros, test suite

#3213 Add Webots R2021b ROS 2 blog section
  docs/blog/Webots-2021-b-release.md
  docs/blog/images/webots_ros_tiago.gif
Labels: documentation

#3222 Resize labels on window resize
  resources/web/wwi/webots.js
Labels: bug

#3218 Fix crash due to invalid SFColor value
  docs/reference/changelog-r2021.md
  projects/robots/softbank/nao/protos/Nao.proto
  src/webots/nodes/WbCharger.cpp
  src/webots/nodes/WbLed.cpp
  src/webots/nodes/utils/WbFieldChecker.cpp
  src/webots/vrml/WbMFColor.cpp
  src/webots/vrml/WbRgb.hpp
  src/webots/vrml/WbSFColor.cpp
Labels: crash, test suite

#3221 Fix `test ros` on master
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  scripts/install/linux_test_dependencies.sh
  scripts/install/msys64_installer.sh
Labels: bug, test ros, test suite

#3227 Fix kinematic simulation triggering a field regeneration which leads to a crash
  docs/reference/changelog-r2021.md
  src/webots/nodes/utils/WbTemplateManager.cpp
Labels: crash, test suite

#3229 Add acknowledgements to r2021b-blog
  docs/blog/Webots-2021-b-release.md
Labels: documentation

#3233 Fix world update after JS PR
  projects/samples/robotbenchmark/highway_driving/worlds/highway_driving.wbt
  projects/samples/robotbenchmark/humanoid_marathon/worlds/humanoid_marathon.wbt
  projects/vehicles/worlds/CH_Morges.wbt
  projects/vehicles/worlds/village_center.wbt
  projects/vehicles/worlds/village_realistic.wbt
Labels: test world update

#3188 Fix endless regeneration resulting in a crash
  docs/reference/changelog-r2021.md
  src/webots/nodes/utils/WbTemplateManager.cpp
Labels: bug, crash, test suite

#3209 Display the magnitude of linear and rotationnal speed
  docs/reference/changelog-r2021.md
  src/webots/scene_tree/WbVelocityViewer.cpp
Labels: enhancement

#3235 Fix `wb_supervisor_node_get_contact_points` caching
  docs/reference/changelog-r2020.md
  docs/reference/changelog-r2021.md
  docs/reference/supervisor.md
  src/controller/c/supervisor.c
Labels: bug, test suite

#3239 Removed deprecated python methods from the doc
  docs/reference/robot.md
Labels: cleanup, documentation

#3238 Documentation enhancement supervisor node export
  docs/reference/supervisor.md
Labels: documentation

#3242 Merge released into master
  docs/discord/development-2019.md
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
Labels: documentation

#3244 Added the altimeter to the change log
  docs/reference/changelog-r2021.md
Labels: documentation

#3226 Fix regeneration of a PROTO boundingObject
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbMatter.cpp
  src/webots/nodes/WbMatter.hpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbTemplateManager.cpp
  tests/protos/controllers/bounding_object_regeneration/.gitignore
  tests/protos/controllers/bounding_object_regeneration/Makefile
  tests/protos/controllers/bounding_object_regeneration/bounding_object_regeneration.c
  tests/protos/protos/ProtoSolidWithBoundingObject.proto
  tests/protos/protos/RegenerableBoundingObjectBox.proto
  tests/protos/worlds/bounding_object_regeneration.wbt
Labels: bug, crash, test suite

#3253 Fix humanoid-marathon missing road
  projects/objects/road/protos/RoadIntersection.proto
Labels: bug

#3254 Fix unmoving pedestrians
  projects/humans/pedestrian/protos/Pedestrian.proto
Labels: bug
