Repository cyberbotics/webots, pull requests merged in 2021-05, with the labels that each got.

#3031 Fix initial labels in streaming viewer mode
  resources/web/templates/x3d_playback.html
  resources/web/wwi/x3d_scene.js
Labels: bug

#2976 Feature fonts web
  docs/reference/changelog-r2021.md
  resources/web/templates/x3d_playback.html
  resources/web/wwi/fonts/Arial Black.woff2
  resources/web/wwi/fonts/Ariali.woff2
  resources/web/wwi/fonts/Code2000.woff2
  resources/web/wwi/fonts/Code2001.woff2
  resources/web/wwi/fonts/Code2002.woff2
  resources/web/wwi/fonts/Comic Sans MS.woff2
  resources/web/wwi/fonts/Georgia.woff2
  resources/web/wwi/fonts/Impact.woff2
  resources/web/wwi/fonts/Lucida Console.woff2
  resources/web/wwi/fonts/Lucida Sans Unicode.woff2
  resources/web/wwi/fonts/Palatino Linotype.woff2
  resources/web/wwi/fonts/Raleway-Light.woff2
  resources/web/wwi/fonts/SIL-Open-Font-License.txt
  resources/web/wwi/fonts/Tahoma.woff2
  resources/web/wwi/fonts/Trebuchet MS.woff2
  resources/web/wwi/fonts/Verdana.woff2
  resources/web/wwi/webots.js
  resources/web/wwi/wwi.css
Labels: enhancement

#3030 Improve Linux installation instructions
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/linux_runtime_dependencies.sh
  scripts/install/linux_test_dependencies.sh
  src/controller/python/Makefile
Labels: enhancement, test suite

#3042 Disable broken windows tests for test suite label
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
Labels: test suite

#3044 Fix library name in youBot documentation
  docs/guide/youbot.md
Labels: documentation

#3045 Merge master into develop
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  docs/discord/development-2021.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/linux_runtime_dependencies.sh
  scripts/install/linux_test_dependencies.sh
  src/controller/python/Makefile
Labels: test suite

#3025 Correct Youbot wheels
  docs/guide/youbot.md
  docs/reference/changelog-r2021.md
  projects/robots/kuka/youbot/controllers/youbot/youbot.c
  projects/robots/kuka/youbot/controllers/youbot_matlab/arm_decrease_height.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/arm_decrease_orientation.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/arm_increase_height.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/arm_increase_orientation.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/arm_perform_reset.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/automatic_behavior.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_backwards_increment.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_forwards_increment.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_init.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_move.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_reset.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_strafe_left_increment.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_strafe_right_increment.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_turn_left_increment.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_turn_right_increment.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/youbot_matlab.m
  projects/robots/kuka/youbot/libraries/youbot_control/include/arm.h
  projects/robots/kuka/youbot/libraries/youbot_control/include/base.h
  projects/robots/kuka/youbot/libraries/youbot_control/src/arm.c
  projects/robots/kuka/youbot/libraries/youbot_control/src/base.c
  projects/robots/kuka/youbot/libraries/youbot_control/youbot_control.def
  projects/robots/kuka/youbot/worlds/youbot.wbt
  projects/robots/kuka/youbot/worlds/youbot_matlab.wbt
  projects/samples/contests/tower_of_hanoi/worlds/tower_of_hanoi.wbt
Labels: bug, test suite

#3043 Uses Visual C++ 2017 instead of deprecated 2010
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  resources/Makefile.include
  scripts/install/bash_profile.appveyor
  scripts/install/bash_profile.windows
  src/controller/c/Makefile
Labels: bug, test distribution, test suite

#3040 Added mStep increment in ros.cpp
  projects/default/controllers/ros/Ros.cpp
Labels: bug, test ros

#3047 Fix path to the e-puck remote_controls sample
  docs/guide/controller-plugin.md
Labels: documentation

#3039 Fix crash solidReference
  docs/reference/changelog-r2021.md
  src/webots/nodes/utils/WbNodeUtilities.cpp
Labels: crash, test suite

#2979 Feature better animation display
  docs/reference/changelog-r2021.md
  resources/web/streaming_viewer/index.html
  resources/web/templates/x3d_playback.html
  resources/web/wwi/Animation.js
  resources/web/wwi/AnimationSlider.js
  resources/web/wwi/MouseEvents.js
  resources/web/wwi/css/animation.css
  resources/web/wwi/css/animation_slider.css
  resources/web/wwi/css/fonts.css
  resources/web/wwi/css/monitor.css
  resources/web/wwi/css/wwi.css
  resources/web/wwi/css/wwi_mobile.css
  resources/web/wwi/images/LICENSE_icons
  resources/web/wwi/images/icons.svg
  resources/web/wwi/init_animation.js
  resources/web/wwi/nodes/WbBaseNode.js
  resources/web/wwi/nodes/WbScene.js
  resources/web/wwi/nodes/WbViewpoint.js
  resources/web/wwi/nodes/wb_preferences.js
  resources/web/wwi/setup_viewer.js
Labels: enhancement

#3050 Fix Linux Build
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
Labels: bug, test suite

#3048 Merge master in develop
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  docs/guide/youbot.md
  docs/reference/changelog-r2021.md
  projects/default/controllers/ros/Ros.cpp
  projects/robots/kuka/youbot/controllers/youbot/youbot.c
  projects/robots/kuka/youbot/controllers/youbot_matlab/arm_decrease_height.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/arm_decrease_orientation.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/arm_increase_height.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/arm_increase_orientation.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/arm_perform_reset.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/automatic_behavior.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_backwards_increment.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_forwards_increment.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_init.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_move.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_reset.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_strafe_left_increment.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_strafe_right_increment.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_turn_left_increment.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/base_turn_right_increment.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/youbot_matlab.m
  projects/robots/kuka/youbot/libraries/youbot_control/include/arm.h
  projects/robots/kuka/youbot/libraries/youbot_control/include/base.h
  projects/robots/kuka/youbot/libraries/youbot_control/src/arm.c
  projects/robots/kuka/youbot/libraries/youbot_control/src/base.c
  projects/robots/kuka/youbot/libraries/youbot_control/youbot_control.def
  projects/robots/kuka/youbot/worlds/youbot.wbt
  projects/robots/kuka/youbot/worlds/youbot_matlab.wbt
  projects/samples/contests/tower_of_hanoi/worlds/tower_of_hanoi.wbt
  resources/Makefile.include
  scripts/install/bash_profile.appveyor
  scripts/install/bash_profile.windows
  src/controller/c/Makefile
  src/webots/nodes/utils/WbNodeUtilities.cpp
Labels: test suite

#3036 Recursively search for finalized PROTO node
  docs/reference/changelog-r2021.md
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  tests/protos/controllers/nested_parameter_transform_node/.gitignore
  tests/protos/controllers/nested_parameter_transform_node/Makefile
  tests/protos/controllers/nested_parameter_transform_node/nested_parameter_transform_node.c
  tests/protos/protos/NestedParameterTransformNode.proto
  tests/protos/worlds/nested_parameter_transform_node.wbt
Labels: bug, test suite

#3053 Improve description of resolution field
  docs/reference/accelerometer.md
  docs/reference/distancesensor.md
  docs/reference/gyro.md
Labels: documentation

#3055 Wrong backlash default value in the docs
  docs/guide/hinge-joint-with-backlash.md
Labels: documentation

#3021 Fix crash Matlab controller
  resources/projects/plugins/robot_windows/generic/Makefile
Labels: crash, test suite

#3059 Fix wrong implementation of `wbrotation.equal` in LUA module
  resources/lua/modules/webots/wbgeometry.lua
  resources/lua/modules/webots/wblimits.lua
  resources/lua/modules/webots/wbrotation.lua
Labels: bug, cleanup

#3058 Fix missing coupled motors changelog entry
  docs/reference/changelog-r2021.md
Labels: cleanup

#3062 Fix crash after camera spherical change
  src/webots/nodes/WbRenderingDevice.cpp
Labels: crash, test suite

#3032 Improve camera performance
  docs/reference/camera.md
  docs/reference/changelog-r2021.md
  docs/reference/lidar.md
  docs/reference/rangefinder.md
  src/controller/c/abstract_camera.c
  src/controller/c/abstract_camera.h
  src/controller/c/camera.c
  src/controller/c/device.c
  src/controller/c/device_private.h
  src/controller/c/image.c
  src/controller/c/image_private.h
  src/controller/c/lidar.c
  src/controller/c/messages.h
  src/controller/c/range_finder.c
  src/controller/c/remote_control.c
  src/controller/c/robot.c
  src/controller/c/robot_private.h
  src/webots/nodes/WbAbstractCamera.cpp
  src/webots/nodes/WbAbstractCamera.hpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbCamera.hpp
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/WbLidar.hpp
Labels: optimization, test suite

#3067 Fixed Windows packaging
  scripts/packaging/files_msys64.txt
Labels: test distribution

#3066 Fix test world update for `coupled_motors.wbt` sample world
  projects/samples/devices/worlds/coupled_motors.wbt
Labels: test world update

#3070 Merge master into develop
  docs/reference/changelog-r2021.md
  projects/robots/universal_robots/worlds/ure.wbt
  resources/lua/modules/webots/wbgeometry.lua
  resources/lua/modules/webots/wblimits.lua
  resources/lua/modules/webots/wbrotation.lua
  scripts/packaging/files_msys64.txt
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  tests/protos/controllers/nested_parameter_transform_node/.gitignore
  tests/protos/controllers/nested_parameter_transform_node/Makefile
  tests/protos/controllers/nested_parameter_transform_node/nested_parameter_transform_node.c
  tests/protos/protos/NestedParameterTransformNode.proto
  tests/protos/worlds/nested_parameter_transform_node.wbt
Labels: test suite

#3080 Increase default mass for intemediary solids in `HingeJointWithBacklash` and `Hinge2JointWithBacklash`
  docs/guide/hinge-2-joint-with-backlash.md
  docs/guide/hinge-joint-with-backlash.md
  projects/joints/protos/Hinge2JointWithBacklash.proto
  projects/joints/protos/HingeJointWithBacklash.proto
Labels: enhancement

#3083 Fixed compilation problem in WbPrecision.hpp
  src/webots/maths/WbPrecision.hpp
Labels: enhancement

#3077 Allow tuning red color sensitivity of infra-red distance sensor
  docs/reference/changelog-r2021.md
  docs/reference/distancesensor.md
  resources/nodes/DistanceSensor.wrl
  src/webots/nodes/WbDistanceSensor.cpp
  src/webots/nodes/WbDistanceSensor.hpp
Labels: enhancement

#3079 Publish Webots controller to independent repository
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  scripts/packaging/sync_controller_lib.sh
Labels: enhancement, test distribution

#3086 Fix triangle count
  docs/reference/changelog-r2021.md
  include/wren/static_mesh.h
  src/webots/nodes/WbGeometry.cpp
  src/webots/scene_tree/WbNodeEditor.cpp
  src/wren/StaticMesh.cpp
Labels: bug, test suite

#3085 Run Webots step() in ROS controller by default
  projects/default/controllers/ros/Ros.cpp
Labels: bug, test ros

#3096 Rename `webots-controller` to `webots-libcontroller`
  scripts/packaging/sync_controller_lib.sh
Labels: bug

#3089 Upgrade to Qt 5.15.2 on linux and add Qml module
  dependencies/Makefile.linux
  docs/reference/changelog-r2021.md
  scripts/install/qt_linux_installer.sh
  scripts/install/qt_windows_installer.sh
  src/webots/Makefile
  src/webots/gui/WbMainWindow.cpp
Labels: test suite, upgrade

#3098 Hotfix crash due to relative velocities viewer
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbSolid.cpp
Labels: crash

#3095 Fix missmatching tag between text and image
  docs/reference/connector.md
Labels: documentation

#3074 Change macro definition
  include/controller/c/webots/robot.h
Labels: cleanup

#3102 fix far webotsjs
  resources/web/wwi/Parser.js
  resources/web/wwi/nodes/wb_preferences.js
  src/webots/nodes/WbViewpoint.cpp
  src/wren/Scene.cpp
Labels: bug, cleanup

#3099 Fix mismatch between slugify function in documentation test
  docs/guide/robotis-op2.md
  docs/guide/robotis-op3.md
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/js/showdown-extensions.js
  docs/reference/connector.md
  docs/reference/display.md
  docs/reference/lightsensor.md
  docs/tests/test_references.py
Labels: documentation

#2940 Improve controller linking
  docs/guide/running-extern-robot-controllers.md
  src/controller/cpp/Makefile
  src/controller/python/Makefile
Labels: enhancement, test distribution

#3105 Fix box-cylinder collision
  docs/reference/changelog-r2021.md
  src/ode/ode/src/collision_cylinder_box.cpp
Labels: bug, test suite

#3106 Feature api webcomponent
  resources/web/wwi/WebotsStreaming.js
  src/webots/gui/WbStreamingServer.cpp
Labels: enhancement

#3104 Release python global interpreter lock when running c++ code
  docs/reference/changelog-r2021.md
  src/controller/python/Makefile
  src/controller/python/controller.i
Labels: bug, test suite

#3088 Enhancement billboard web
  resources/web/wwi/Parser.js
  resources/web/wwi/Selector.js
  resources/web/wwi/nodes/WbAppearance.js
  resources/web/wwi/nodes/WbBillboard.js
  resources/web/wwi/nodes/WbGeometry.js
  resources/web/wwi/nodes/WbGroup.js
  resources/web/wwi/nodes/WbPBRAppearance.js
  resources/web/wwi/nodes/WbShape.js
  resources/web/wwi/nodes/WbTransform.js
  resources/web/wwi/nodes/WbViewpoint.js
  resources/web/wwi/nodes/WbWorld.js
  resources/web/wwi/nodes/utils/utils.js
  resources/web/wwi/wren/WbWrenRenderingContext.js
  src/webots/nodes/WbBillboard.cpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
Labels: enhancement, test suite

#2442 Improve startup performance of external controller
  docs/reference/changelog-r2021.md
  src/controller/c/robot.c
Labels: enhancement, test suite
