Repository cyberbotics/webots, pull requests merged in 2021-03, with the labels that each got.

#2793 Update node-chart.md
  docs/reference/node-chart.md
Labels: documentation

#2795 export coordinateSystem
  src/webots/nodes/WbWorldInfo.cpp
Labels: enhancement, test suite

#2794 Update immersionproperties.md
  docs/reference/immersionproperties.md
Labels: documentation

#2796 Clear Pen ink on simulation reset
  docs/reference/changelog-r2021.md
  src/webots/nodes/utils/WbPaintTexture.cpp
Labels: bug, test suite

#2797 Separate visible and hidden fields more clearly in the docs
  docs/reference/balljoint.md
  docs/reference/changelog-r2021.md
  docs/reference/hinge2joint.md
  docs/reference/hingejoint.md
  docs/reference/joint.md
  docs/reference/sliderjoint.md
  docs/reference/solid.md
Labels: documentation

#2801 Fix physics example
  projects/samples/howto/physics/plugins/physics/flying_mybot/flying_mybot.c
Labels: bug, test suite

#2802 Update FifaSoccerBall.proto
  docs/guide/generate_objects_doc.py
  docs/guide/object-balls.md
  projects/objects/balls/protos/FifaSoccerBall.proto
Labels: cleanup

#2807 Merge released into master
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/supervisor-programming.md
  docs/reference/balljoint.md
  docs/reference/changelog-r2021.md
  docs/reference/hinge2joint.md
  docs/reference/hingejoint.md
  docs/reference/immersionproperties.md
  docs/reference/joint.md
  docs/reference/node-chart.md
  docs/reference/sliderjoint.md
  docs/reference/solid.md
  docs/reference/supervisor.md
Labels: documentation

#2808 Merge master into develop
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/guide/appearances.md
  docs/guide/generate_objects_doc.py
  docs/guide/images/objects/balls/FifaSoccerBall/model.png
  docs/guide/images/objects/balls/FifaSoccerBall/model.thumbnail.jpg
  docs/guide/object-balls.md
  docs/guide/object-toys.md
  docs/guide/starting-webots.md
  docs/guide/supervisor-programming.md
  docs/reference/balljoint.md
  docs/reference/changelog-r2021.md
  docs/reference/hinge2joint.md
  docs/reference/hingejoint.md
  docs/reference/immersionproperties.md
  docs/reference/joint.md
  docs/reference/node-chart.md
  docs/reference/sliderjoint.md
  docs/reference/solid.md
  docs/reference/supervisor.md
  lib/controller/matlab/wb_supervisor_node_get_velocity.m
  projects/objects/balls/protos/FifaSoccerBall.proto
  projects/objects/balls/protos/icons/FifaSoccerBall.png
  projects/robots/robotis/turtlebot/controllers/turtlebot3_ostacle_avoidance/turtlebot3_ostacle_avoidance.c
  projects/samples/howto/physics/plugins/physics/flying_mybot/flying_mybot.c
  src/webots/engine/WbSimulationCluster.cpp
  src/webots/engine/WbSimulationCluster.hpp
  src/webots/gui/WbSingleTaskApplication.cpp
  src/webots/nodes/WbPointSet.cpp
  src/webots/nodes/utils/WbPaintTexture.cpp
Labels: test suite

#2809 Fixes nightly builds of Webots R2021b on Windows
  scripts/packaging/files_core.txt
Labels: bug

#2803 Fix URDF exporting of leaf nodes
  docs/reference/changelog-r2021.md
  src/webots/vrml/WbMFNode.cpp
  tests/api/controllers/robot_urdf/prob3_reference.urdf
  tests/api/controllers/robot_urdf/tiago_reference.urdf
  tests/api/controllers/robot_urdf/ur5e_reference.urdf
Labels: bug, test suite

#2806 Fix wireframe rendering
  docs/reference/changelog-r2021.md
  resources/wren/shaders/pbr_stencil_ambient_emissive.frag
  src/webots/nodes/WbViewpoint.cpp
  src/webots/wren/WbWrenShaders.cpp
Labels: bug, test suite

#2804 Fix Pen density
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbAppearance.cpp
  src/webots/nodes/WbAppearance.hpp
  src/webots/nodes/WbDistanceSensor.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbImageTexture.hpp
  src/webots/nodes/WbPbrAppearance.cpp
  src/webots/nodes/WbShape.cpp
  src/webots/nodes/WbShape.hpp
  src/webots/nodes/utils/WbPaintTexture.cpp
  src/webots/nodes/utils/WbPaintTexture.hpp
  src/webots/vrml/WbRgb.hpp
  tests/api/controllers/distance_sensor_infra-red/distance_sensor_infra-red.c
  tests/api/controllers/pen/pen.c
Labels: bug, test suite

#2805 Generic gear PROTO
  docs/guide/images/objects/gear/Gear/model.png
  docs/guide/images/samples/gears.png
  docs/guide/images/samples/gears.thumbnail.jpg
  docs/guide/menu.md
  docs/guide/object-gear.md
  docs/guide/objects.md
  docs/guide/samples-howto.md
  projects/objects/gear/protos/Gear.proto
  projects/objects/gear/protos/icons/Gear.png
  projects/samples/howto/gears/controllers/gears/.gitignore
  projects/samples/howto/gears/controllers/gears/Makefile
  projects/samples/howto/gears/controllers/gears/gears.c
  projects/samples/howto/gears/worlds/.gears.wbproj
  projects/samples/howto/gears/worlds/gears.wbt
Labels: feature

#2816 Removed useless texture
  projects/objects/factory/pipes/textures/pipe.jpg
Labels: cleanup

#2799 Fix Lidar.getLayerRangeImage returning full image on Python and Java
  docs/reference/changelog-r2021.md
  docs/reference/lidar.md
  src/controller/java/controller.i
  src/controller/python/controller.i
Labels: bug, test suite

#2817 Fix .jpeg extensions
  projects/objects/factory/fire_extinguisher/protos/FireExtinguisher.proto
  projects/objects/factory/fire_extinguisher/protos/textures/fire_extinguisher_base_color.jpg
  projects/objects/factory/fire_extinguisher/protos/textures/fire_extinguisher_normal.jpg
  projects/vehicles/protos/lincoln/LincolnMKZ.proto
  projects/vehicles/protos/lincoln/LincolnMKZSimple.proto
  projects/vehicles/protos/lincoln/textures/lincoln_mkz_details_base_color.jpg
Labels: cleanup

#2819 Fix textures and meshes folders
  projects/objects/toys/protos/PaperBoat.proto
  projects/objects/toys/protos/PaperBoat/meshes/geom.obj
  projects/objects/toys/protos/PaperBoat/textures/newspaper.jpg
  projects/objects/toys/protos/RubberDuck.proto
  projects/objects/toys/protos/RubberDuck/meshes/beak.obj
  projects/objects/toys/protos/RubberDuck/meshes/body.obj
  projects/objects/toys/protos/RubberDuck/meshes/eye.obj
  projects/objects/toys/protos/RubberDuck/textures/eye.jpg
  projects/robots/nasa/protos/sojourner/photovoltaicPanel.jpg
  projects/robots/nasa/worlds/sojourner.wbt
  projects/robots/nasa/worlds/textures/panel.jpg
  projects/robots/softbank/nao/worlds/challenge.wbt
  projects/robots/softbank/nao/worlds/textures/landmark0.png
  projects/robots/softbank/nao/worlds/textures/landmark1.png
  projects/robots/softbank/nao/worlds/textures/landmark2.png
  projects/robots/softbank/nao/worlds/textures/landmark3.png
  projects/robots/softbank/nao/worlds/textures/landmark4.png
  projects/robots/softbank/nao/worlds/textures/landmark5.png
  projects/robots/softbank/nao/worlds/textures/landmark6.png
  projects/robots/softbank/nao/worlds/textures/landmark7.png
  projects/robots/softbank/nao/worlds/textures/landmark8.png
  projects/robots/softbank/nao/worlds/textures/landmark9.png
  projects/samples/contests/ratslife/protos/e-puck/E-puckFlag.proto
  projects/samples/contests/ratslife/protos/e-puck/textures/rat0.jpg
  projects/samples/contests/ratslife/protos/e-puck/textures/rat1.jpg
  projects/samples/contests/ratslife/worlds/ratslife.wbt
  projects/samples/contests/ratslife/worlds/ratslife_round.wbt
  projects/samples/demos/worlds/gantry.wbt
  projects/samples/demos/worlds/moon.wbt
  projects/samples/demos/worlds/soccer.wbt
  projects/samples/demos/worlds/textures/gantry/1.png
  projects/samples/demos/worlds/textures/gantry/2.png
  projects/samples/demos/worlds/textures/gantry/A.png
  projects/samples/demos/worlds/textures/gantry/B.png
  projects/samples/demos/worlds/textures/gantry/C.png
  projects/samples/demos/worlds/textures/moon/earth.png
  projects/samples/demos/worlds/textures/moon/moon_ground.jpg
  projects/samples/demos/worlds/textures/soccer/blue.png
  projects/samples/demos/worlds/textures/soccer/soccer-256.jpg
  projects/samples/demos/worlds/textures/soccer/soccer_quarter.jpg
  projects/samples/demos/worlds/textures/soccer/yellow.png
Labels: cleanup

#2821 Fixed default python version on Windows
  scripts/install/msys.sh
Labels: enhancement

#2800 Fixed extern controller startup
  docs/reference/changelog-r2021.md
  include/controller/c/webots/utils/system.h
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.c
  src/controller/c/g_pipe.c
  src/controller/c/robot.c
  src/controller/c/scheduler.c
  src/controller/c/system.c
Labels: bug, test suite

#2824 Fixed Makefile in case JAVA_HOME is not set and javac is not available on Linux
  Makefile
Labels: bug, cleanup

#2783 Robocup soccer field
  projects/default/worlds/textures/cubic/stadium_left.hdr
  projects/default/worlds/textures/cubic/stadium_left.png
  projects/default/worlds/textures/cubic/stadium_right.hdr
  projects/default/worlds/textures/cubic/stadium_right.png
  projects/objects/balls/protos/FifaSoccerBall.proto
  projects/objects/balls/protos/RobocupSoccerBall.proto
  projects/objects/balls/protos/icons/RobocupSoccerBall.png
  projects/robots/softbank/nao/worlds/nao_robocup.wbt
  projects/samples/contests/robocup/protos/RobocupGoal.proto
  projects/samples/contests/robocup/protos/RobocupSoccerField.proto
  projects/samples/contests/robocup/protos/WhiteGrass.proto
  projects/samples/contests/robocup/protos/icons/RobocupGoal.png
  projects/samples/contests/robocup/protos/icons/RobocupSoccerField.png
  projects/samples/contests/robocup/protos/icons/WhiteGrass.png
  projects/samples/contests/robocup/protos/textures/whitegrass_artificial_base_color.jpg
  projects/samples/contests/robocup/worlds/.adult.wbproj
  projects/samples/contests/robocup/worlds/.kid.wbproj
  projects/samples/contests/robocup/worlds/adult.wbt
  projects/samples/contests/robocup/worlds/kid.wbt
Labels: feature

#2827 Fix blog index
  docs/blog/index.md
Labels: documentation

#2829 Fix load order in the `ros` controller
  projects/default/controllers/ros/Ros.cpp
  projects/default/controllers/ros/Ros.hpp
Labels: bug

#2825 Fix incorrect device limit constraints in Hinge2Joint and BallJoint
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbBrake.cpp
  src/webots/nodes/WbBrake.hpp
  src/webots/nodes/WbJointDevice.cpp
  src/webots/nodes/WbJointDevice.hpp
  src/webots/nodes/WbMotor.cpp
  tests/parser/controllers/joints_motor_min_max_position/.gitignore
  tests/parser/controllers/joints_motor_min_max_position/Makefile
  tests/parser/controllers/joints_motor_min_max_position/joints_motor_min_max_position.c
  tests/parser/expected_results.txt
  tests/parser/worlds/joints_motor_min_max_position.wbt
Labels: bug, test suite

#2812 Fix update of supervisor field count
  docs/reference/changelog-r2021.md
  src/controller/c/messages.h
  src/controller/c/supervisor.c
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeOperations.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  src/webots/vrml/WbField.cpp
  src/webots/vrml/WbField.hpp
  tests/api/controllers/supervisor_import_remove/supervisor_import_remove.c
  tests/api/controllers/supervisor_notify_import_remove_mf/.gitignore
  tests/api/controllers/supervisor_notify_import_remove_mf/Makefile
  tests/api/controllers/supervisor_notify_import_remove_mf/supervisor_notify_import_remove_mf.c
  tests/api/controllers/supervisor_notify_import_remove_mfnode/.gitignore
  tests/api/controllers/supervisor_notify_import_remove_mfnode/Makefile
  tests/api/controllers/supervisor_notify_import_remove_mfnode/supervisor_notify_import_remove_mfnode.c
  tests/api/worlds/supervisor_import_remove.wbt
  tests/api/worlds/supervisor_import_remove_mf.wbt
Labels: bug, test suite

#2830 Fixed doc generation script
  docs/guide/appearances.md
  docs/guide/generate_objects_doc.py
  docs/guide/images/objects/balls/FifaSoccerBall/model.png
  docs/guide/images/objects/balls/FifaSoccerBall/model.thumbnail.jpg
  docs/guide/images/objects/balls/FifaSoccerBall/model.thumbnail.png
  docs/guide/object-advertising-board.md
  docs/guide/object-backgrounds.md
  docs/guide/object-balls.md
  docs/guide/object-buildings.md
  docs/guide/object-geometries.md
  docs/guide/object-road.md
  docs/guide/object-shapes.md
  docs/guide/object-street-furniture.md
  docs/guide/object-traffic.md
  docs/guide/object-trees.md
  projects/objects/balls/protos/RobocupSoccerBall.proto
Labels: cleanup, documentation

#2834 Update changelog
  docs/reference/changelog-r2021.md
Labels: documentation

#2840 Move joints min max position test suite into API folder
  tests/api/controllers/joints_motor_min_max_position/.gitignore
  tests/api/controllers/joints_motor_min_max_position/Makefile
  tests/api/controllers/joints_motor_min_max_position/joints_motor_min_max_position.c
  tests/api/worlds/joints_motor_min_max_position.wbt
  tests/parser/expected_results.txt
Labels: enhancement, test suite

#2841 Fix background in ENU
  src/webots/nodes/WbBackground.cpp
Labels: bug

#2845 Fix ROS api compilation
  projects/default/controllers/ros/highlevel/WebotsHW.cpp
Labels: bug, test ros

#2786 HingeJointWithBacklash proto to model effect of backlash
  docs/guide/hinge-joint-with-backlash.md
  docs/guide/images/joints/HingeJointWithBacklash/HingeJointWithBacklash.png
  docs/guide/images/joints/HingeJointWithBacklash/HingeJointWithBacklash_icon.png
  docs/guide/images/samples/hinge_joint_with_backlash.png
  docs/guide/images/samples/hinge_joint_with_backlash.thumbnail.jpg
  docs/guide/joints.md
  docs/guide/menu.md
  docs/guide/samples-devices.md
  docs/reference/changelog-r2021.md
  docs/reference/hingejointparameters.md
  projects/joints/protos/HingeJointWithBacklash.proto
  projects/joints/protos/icons/HingeJointWithBacklash.png
  projects/samples/devices/controllers/hinge_joint_with_backlash/.gitignore
  projects/samples/devices/controllers/hinge_joint_with_backlash/Makefile
  projects/samples/devices/controllers/hinge_joint_with_backlash/hinge_joint_with_backlash.c
  projects/samples/devices/worlds/.hinge_joint_with_backlash.wbproj
  projects/samples/devices/worlds/hinge_joint_with_backlash.wbt
  resources/nodes/HingeJointParameters.wrl
  src/webots/nodes/WbHingeJoint.cpp
  src/webots/nodes/WbHingeJoint.hpp
  src/webots/nodes/WbHingeJointParameters.cpp
  src/webots/nodes/WbHingeJointParameters.hpp
  tests/protos/controllers/hinge_joint_with_backlash/.gitignore
  tests/protos/controllers/hinge_joint_with_backlash/Makefile
  tests/protos/controllers/hinge_joint_with_backlash/hinge_joint_with_backlash.c
  tests/protos/controllers/hinge_joint_with_backlash_supervisor/.gitignore
  tests/protos/controllers/hinge_joint_with_backlash_supervisor/Makefile
  tests/protos/controllers/hinge_joint_with_backlash_supervisor/hinge_joint_with_backlash_supervisor.c
  tests/protos/worlds/hinge_joint_with_backlash.wbt
Labels: feature, test suite

#2839 Add RUB to FLU PROTO conversion script
  projects/robots/adept/pioneer3/protos/Pioneer3at.proto
  projects/robots/adept/pioneer3/worlds/pioneer3at.wbt
  projects/samples/howto/openai_gym/worlds/openai_gym.wbt
  projects/samples/howto/sick_terrain_scanning/controllers/sick_terrain_scanning_supervisor/sick_terrain_scanning_supervisor.c
  projects/samples/howto/sick_terrain_scanning/worlds/sick_terrain_scanning.wbt
  scripts/converter/convert_rub_to_flu.py
  scripts/converter/webots_parser.py
Labels: bug, test suite

#2857 Fix PedestrianCrossing PROTO
  docs/reference/changelog-r2021.md
  projects/objects/traffic/protos/PedestrianCrossing.proto
Labels: bug

#2851 Fixed translation/rotation field of the RobocupSoccerField proto
  projects/default/worlds/textures/cubic/stadium_back.png
  projects/samples/contests/robocup/protos/RobocupGoal.proto
  projects/samples/contests/robocup/protos/RobocupSoccerField.proto
  projects/samples/contests/robocup/worlds/adult.wbt
  projects/samples/contests/robocup/worlds/kid.wbt
Labels: bug

#2850 Addition of a Hinge2JointWithBacklash PROTO
  docs/guide/hinge-2-joint-with-backlash.md
  docs/guide/images/joints/Hinge2JointWithBacklash/Hinge2JointWithBacklash.png
  docs/guide/images/joints/Hinge2JointWithBacklash/Hinge2JointWithBacklash_icon.png
  docs/guide/images/samples/hinge_2_joint_with_backlash.png
  docs/guide/images/samples/hinge_2_joint_with_backlash.thumbnail.jpg
  docs/guide/joints.md
  docs/guide/menu.md
  docs/guide/samples-devices.md
  docs/reference/changelog-r2021.md
  projects/joints/protos/Hinge2JointWithBacklash.proto
  projects/joints/protos/icons/Hinge2JointWithBacklash.png
  projects/samples/devices/worlds/.hinge_2_joint_with_backlash.wbproj
  projects/samples/devices/worlds/hinge_2_joint_with_backlash.wbt
  tests/protos/controllers/hinge_2_joint_with_backlash/.gitignore
  tests/protos/controllers/hinge_2_joint_with_backlash/Makefile
  tests/protos/controllers/hinge_2_joint_with_backlash/hinge_2_joint_with_backlash.c
  tests/protos/controllers/hinge_2_joint_with_backlash_supervisor/.gitignore
  tests/protos/controllers/hinge_2_joint_with_backlash_supervisor/Makefile
  tests/protos/controllers/hinge_2_joint_with_backlash_supervisor/hinge_2_joint_with_backlash_supervisor.c
  tests/protos/worlds/hinge_2_joint_with_backlash.wbt
Labels: feature

#2856 Convert DarwinOp to FLU
  projects/robots/adept/pioneer3/worlds/pioneer3at.wbt
  projects/robots/robotis/darwin-op/protos/Darwin-op.proto
  projects/robots/robotis/darwin-op/worlds/darwin-op.wbt
  projects/robots/robotis/darwin-op/worlds/motion.wbt
  projects/robots/robotis/darwin-op/worlds/soccer.wbt
  projects/robots/robotis/darwin-op/worlds/symmetry.wbt
  projects/robots/robotis/darwin-op/worlds/symmetry_matlab.wbt
  projects/robots/robotis/darwin-op/worlds/visual_tracking.wbt
  projects/robots/robotis/darwin-op/worlds/walk.wbt
  projects/robots/softbank/nao/controllers/nao_soccer_supervisor/nao_soccer_supervisor.c
  projects/robots/softbank/nao/worlds/robotstadium_nao_vs_robotis-op2.wbt
  projects/samples/contests/robocup/worlds/adult.wbt
  projects/samples/contests/robocup/worlds/kid.wbt
  projects/samples/environments/factory/worlds/factory.wbt
  projects/samples/howto/sick_terrain_scanning/worlds/sick_terrain_scanning.wbt
  projects/samples/robotbenchmark/humanoid_marathon/worlds/humanoid_marathon.wbt
  scripts/converter/convert_nue_to_enu.py
  scripts/converter/convert_proto.py
  scripts/converter/webots_parser.py
  tests/api/worlds/supervisor_set_position_loop.wbt
Labels: bug, enhancement, test world update

#2831 Artificial turf physics
  projects/objects/balls/protos/RobocupSoccerBall.proto
  projects/samples/contests/robocup/protos/RobocupSoccerField.proto
  projects/samples/contests/robocup/worlds/adult.wbt
  projects/samples/contests/robocup/worlds/kid.wbt
Labels: enhancement

#2863 Improved PROTO design rules documentation
  docs/reference/proto-design-guidelines.md
Labels: documentation

#2864 Recommend FLU orientation for new PROTOs
  docs/reference/proto-design-guidelines.md
Labels: documentation

#2867 Fix `ros_control` velocity feedback
  projects/default/controllers/ros/highlevel/RosControl.cpp
  projects/default/controllers/ros/highlevel/WebotsHW.cpp
  projects/default/controllers/ros/highlevel/WebotsHW.hpp
Labels: bug

#2870 Change initial position of the Tiago arm
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoFrontArm.proto
Labels: bug

#2865 Fixed balls protos with orientation and position rules
  docs/guide/images/objects/balls/RobocupSoccerBall/model.png
  docs/guide/images/objects/balls/RobocupSoccerBall/model.thumbnail.png
  docs/guide/object-backgrounds.md
  docs/guide/object-balls.md
  docs/guide/object-gear.md
  docs/guide/object-toys.md
  projects/objects/balls/protos/Ball.proto
  projects/objects/balls/protos/FifaSoccerBall.proto
  projects/objects/balls/protos/PingPongBall.proto
  projects/objects/balls/protos/RobocupSoccerBall.proto
  projects/objects/balls/protos/SoccerBall.proto
  projects/objects/balls/protos/icons/RobocupSoccerBall.png
Labels: cleanup, documentation

#2872 Update proto-design-guidelines.md
  docs/reference/proto-design-guidelines.md
Labels: documentation

#2871 Merge released into master
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/reference/proto-design-guidelines.md
  docs/reference/worldinfo.md
Labels: documentation

#2873 Merge master into develop
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/reference/changelog-r2021.md
  docs/reference/proto-design-guidelines.md
  docs/reference/worldinfo.md
  projects/objects/traffic/protos/PedestrianCrossing.proto
Labels: test suite, test world update

#2868 Changed chained joints collision logic to ignore superposed joints
  docs/reference/changelog-r2021.md
  docs/reference/robot.md
  src/webots/engine/WbSimulationCluster.cpp
Labels: enhancement, test suite

#2874 Added stadium background with dry grass
  docs/guide/object-backgrounds.md
  docs/reference/changelog-r2021.md
  projects/default/worlds/textures/cubic/stadium_dry_back.hdr
  projects/default/worlds/textures/cubic/stadium_dry_back.png
  projects/default/worlds/textures/cubic/stadium_dry_bottom.hdr
  projects/default/worlds/textures/cubic/stadium_dry_bottom.png
  projects/default/worlds/textures/cubic/stadium_dry_front.hdr
  projects/default/worlds/textures/cubic/stadium_dry_front.png
  projects/default/worlds/textures/cubic/stadium_dry_left.hdr
  projects/default/worlds/textures/cubic/stadium_dry_left.png
  projects/default/worlds/textures/cubic/stadium_dry_right.hdr
  projects/default/worlds/textures/cubic/stadium_dry_right.png
  projects/objects/backgrounds/protos/TexturedBackground.proto
  projects/objects/backgrounds/protos/TexturedBackgroundLight.proto
  projects/samples/contests/robocup/worlds/adult.wbt
  projects/samples/contests/robocup/worlds/kid.wbt
Labels: enhancement

#2875 Improve URDF naming convention
  docs/reference/changelog-r2021.md
  src/webots/vrml/WbNode.cpp
  tests/api/controllers/robot_urdf/prob3_reference.urdf
  tests/api/controllers/robot_urdf/tiago_reference.urdf
  tests/api/controllers/robot_urdf/ur5e_reference.urdf
Labels: enhancement, test suite

#2876 Fix Tiago damping
  docs/reference/changelog-r2021.md
  projects/robots/pal_robotics/tiago_base/protos/TiagoBase.proto
Labels: enhancement

#2879 Improve Charger energy update when robot battery is full
  docs/reference/changelog-r2021.md
  src/webots/nodes/WbCharger.cpp
Labels: bug, test suite

#2849 Ability to restrict Emitter/Receiver channels
  docs/reference/changelog-r2021.md
  docs/reference/emitter.md
  docs/reference/receiver.md
  resources/nodes/Emitter.wrl
  resources/nodes/Receiver.wrl
  src/controller/c/emitter.c
  src/controller/c/messages.h
  src/controller/c/receiver.c
  src/webots/nodes/WbEmitter.cpp
  src/webots/nodes/WbEmitter.hpp
  src/webots/nodes/WbReceiver.cpp
  src/webots/nodes/WbReceiver.hpp
Labels: enhancement

#2882 Retry in case of server error
  scripts/packaging/publish_release.py
Labels: enhancement

#2878 Calibrated Robocup ball
  projects/objects/balls/protos/RobocupSoccerBall.proto
  projects/samples/contests/robocup/worlds/adult.wbt
  projects/samples/contests/robocup/worlds/kid.wbt
Labels: enhancement

#2881 Darwin-op expose backlash
  docs/guide/robotis-op2.md
  docs/reference/changelog-r2021.md
  projects/robots/robotis/darwin-op/protos/Darwin-op.proto
  projects/robots/robotis/darwin-op/protos/RobotisOp2.proto
Labels: enhancement

#2861 Darwin-Op modeled using Hinge2Joints
  docs/guide/images/robots/robotis-op2/darwin-op_hinge_vs_hinge2.wbt.png
  docs/guide/images/robots/robotis-op2/darwin-op_hinge_vs_hinge2.wbt.thumbnail.jpg
  docs/guide/robotis-op2.md
  docs/reference/changelog-r2021.md
  projects/robots/robotis/darwin-op/protos/Darwin-opHinge2.proto
  projects/robots/robotis/darwin-op/protos/RobotisOp2Hinge2.proto
  projects/robots/robotis/darwin-op/protos/icons/Darwin-opHinge2.png
  projects/robots/robotis/darwin-op/protos/icons/RobotisOp2Hinge2.png
  projects/robots/robotis/darwin-op/worlds/.darwin-op_hinge_vs_hinge2.wbproj
  projects/robots/robotis/darwin-op/worlds/darwin-op_hinge_vs_hinge2.wbt
Labels: enhancement

#2887 Added backlash in robocup worlds
  projects/samples/contests/robocup/worlds/adult.wbt
  projects/samples/contests/robocup/worlds/kid.wbt
Labels: enhancement

#2890 Fix incorrect stopCFM and stopERP imposition when world uses non-default global CFM/ERP
  docs/reference/hingejointparameters.md
  resources/nodes/HingeJointParameters.wrl
  src/webots/nodes/WbHingeJoint.cpp
  src/webots/nodes/WbHingeJointParameters.cpp
Labels: bug

#2854 Use WebGL to draw plots in the generic robot window
  docs/reference/changelog-r2021.md
  resources/projects/plugins/robot_windows/generic/canvas.js
  resources/projects/plugins/robot_windows/generic/device_widget.js
  resources/projects/plugins/robot_windows/generic/generic.css
  resources/projects/plugins/robot_windows/generic/generic.html
  resources/projects/plugins/robot_windows/generic/generic.js
  resources/projects/plugins/robot_windows/generic/timeplot_line.js
  resources/projects/plugins/robot_windows/generic/timeplot_widget.js
  resources/projects/plugins/robot_windows/generic/window_manager.js
Labels: enhancement

#2892 Fixed foot-grass friction in Robocup
  projects/samples/contests/robocup/worlds/adult.wbt
  projects/samples/contests/robocup/worlds/kid.wbt
Labels: enhancement

#2893 Replace unnecessary randomness in PROTO
  docs/reference/procedural-proto-nodes.md
  projects/bounding_objects/protos/PipeBoundingObject.proto
  projects/joints/protos/Hinge2JointWithBacklash.proto
  projects/joints/protos/HingeJointWithBacklash.proto
  projects/objects/buildings/protos/RandomBuilding.proto
  projects/objects/buildings/protos/SimpleBuilding.proto
  projects/objects/solids/protos/SolidPipe.proto
  projects/objects/street_furniture/protos/PublicToilet.proto
  projects/objects/traffic/protos/DirectionPanel.proto
  projects/objects/trees/protos/Forest.proto
  tests/protos/protos/TemplateTexture.proto
Labels: cleanup

#2895 Remove tests on Ubuntu 16.04
  .github/workflows/tests_sources.yml
Labels: cleanup

#2897 Fix randomBuilding proto
  docs/reference/changelog-r2021.md
  projects/objects/buildings/protos/RandomBuilding.proto
Labels: bug

#2900 Fixed typo in documentation
  docs/reference/supervisor.md
Labels: documentation

#2885 Add URDF CLI converter
  docs/guide/starting-webots.md
  docs/reference/changelog-r2021.md
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbGuiApplication.hpp
  src/webots/gui/WbSingleTaskApplication.cpp
  src/webots/gui/WbSingleTaskApplication.hpp
Labels: enhancement, test suite

#2904 Fixed documentation about getting device tags
  docs/reference/robot.md
Labels: documentation

#2894 Update c3d robot window
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.css
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.html
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.js
  resources/projects/plugins/robot_windows/generic/device_widget.js
  resources/projects/plugins/robot_windows/generic/generic.css
  resources/projects/plugins/robot_windows/generic/generic.js
  resources/projects/plugins/robot_windows/generic/plot_widget.js
  resources/projects/plugins/robot_windows/generic/radar_widget.js
  resources/projects/plugins/robot_windows/generic/timeplot_widget.js
Labels: enhancement

#2902 Improve publish_release.py by catching all the expections
  scripts/packaging/publish_release.py
Labels: bug

#2907 Merge master into develop
  .github/workflows/tests_sources.yml
  docs/discord/development-2021.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2021.md
  docs/reference/changelog-r2021.md
  docs/reference/emitter.md
  docs/reference/proto-design-guidelines.md
  docs/reference/receiver.md
  docs/reference/robot.md
  docs/reference/supervisor.md
  resources/nodes/Emitter.wrl
  resources/nodes/Receiver.wrl
  scripts/packaging/publish_release.py
  src/controller/c/emitter.c
  src/controller/c/messages.h
  src/controller/c/receiver.c
  src/webots/nodes/WbCharger.cpp
  src/webots/nodes/WbEmitter.cpp
  src/webots/nodes/WbEmitter.hpp
  src/webots/nodes/WbReceiver.cpp
  src/webots/nodes/WbReceiver.hpp
Labels: test suite

#2909 Rework of hinge2withbacklash sequence
  docs/guide/hinge-2-joint-with-backlash.md
  projects/joints/protos/Hinge2JointWithBacklash.proto
  projects/robots/robotis/darwin-op/protos/Darwin-opHinge2.proto
  src/webots/nodes/WbHingeJoint.cpp
  tests/protos/controllers/hinge_2_joint_with_backlash_supervisor/hinge_2_joint_with_backlash_supervisor.c
Labels: enhancement

#2911 Remove conditional around startpoint for HingeJointWithBacklash
  projects/joints/protos/HingeJointWithBacklash.proto
Labels: cleanup

#2921 Fix camera object recognition detection using bounding sphere
  docs/reference/changelog-r2021.md
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbSimulationView.cpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/utils/WbObjectDetection.cpp
  src/webots/nodes/utils/WbVisualBoundingSphere.cpp
  src/webots/nodes/utils/WbVisualBoundingSphere.hpp
Labels: bug, test suite

#2924 Merge released into master
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
Labels: documentation

#2923 Fix CameraRecognitionObject API in Python and Java
  docs/reference/camera.md
  docs/reference/changelog-r2021.md
  src/controller/java/controller.i
  src/controller/python/controller.i
Labels: bug, test suite
