Repository cyberbotics/webots, pull requests merged in 2022-12, with the labels that each got.

#5613 Fix two bugs in feature-web-proto
  resources/web/wwi/nodes/WbHingeJoint.js
  resources/web/wwi/nodes/WbSlot.js
  resources/web/wwi/nodes/utils/WbQuaternion.js
Labels: bug

#5601 Add version information in webotsJS
  resources/web/wwi/InformationPanel.js
  resources/web/wwi/Parser.js
  resources/web/wwi/nodes/WbWorld.js
Labels: enhancement

#5614 Reset button is grey when there is nothing to reset
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/css/toolbar.css
Labels: bug

#5618 Fix pose tracking docs
  docs/reference/supervisor.md
Labels: documentation

#5612 Enhancement display camera
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/nodes/WbAbstractCamera.js
  resources/web/wwi/nodes/WbCamera.js
  resources/web/wwi/nodes/WbRangeFinder.js
  resources/web/wwi/protos/ProtoCamera.proto
  resources/web/wwi/test.html
  resources/web/wwi/wren/WbWrenShaders.js
  scripts/export_function_js/export_function.py
  src/webots/nodes/WbWorldInfo.cpp
Labels: enhancement

#5619 Try to get rid of MSYS/git installation on Windows
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
Labels: cleanup, test webots build

#5620 Fix invalid nodes in pose tracking
  docs/reference/changelog-r2023.md
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
Labels: bug, test sources

#5621 Allow to enable/disable the follow of the given node
  resources/web/wwi/Toolbar.js
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/nodes/WbViewpoint.js
Labels: enhancement

#5624 Removed unused discord updater workflow
  .github/workflows/discord_updater.yml
Labels: cleanup

#5622 Improved the bounding boxes of the nao to make them not collide
  docs/reference/changelog-r2023.md
  projects/robots/softbank/nao/protos/Nao.proto
  projects/robots/softbank/nao/protos/NaoLeftWristH21.proto
  projects/robots/softbank/nao/protos/NaoLeftWristH25Realistic.proto
  projects/robots/softbank/nao/protos/NaoRightWristH21.proto
  projects/robots/softbank/nao/protos/NaoRightWristH25Realistic.proto
Labels: bug

#5628 Web Proto Viewer: RangeFinder and Lidar
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/nodes/WbAbstractCamera.js
  resources/web/wwi/nodes/WbCamera.js
  resources/web/wwi/nodes/WbLidar.js
  resources/web/wwi/nodes/WbRangeFinder.js
  resources/web/wwi/protos/ProtoCamera.proto
  resources/web/wwi/test.html
Labels: enhancement

#5632 Cleanup webotsJs import
  resources/web/wwi/nodes/WbAppearance.js
  resources/web/wwi/nodes/WbBackground.js
  resources/web/wwi/nodes/WbGeometry.js
  resources/web/wwi/nodes/WbPbrAppearance.js
  resources/web/wwi/nodes/WbPointSet.js
  resources/web/wwi/nodes/WbScene.js
  resources/web/wwi/nodes/WbShape.js
  resources/web/wwi/nodes/WbTriangleMeshGeometry.js
  resources/web/wwi/nodes/WbViewpoint.js
  resources/web/wwi/wren/WbWrenBloom.js
  resources/web/wwi/wren/WbWrenGtao.js
  resources/web/wwi/wren/WbWrenHdr.js
  resources/web/wwi/wren/WbWrenPicker.js
  resources/web/wwi/wren/WbWrenPostProcessingEffects.js
  resources/web/wwi/wren/WbWrenShaders.js
Labels: cleanup

#5631 Radar frustum web
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/nodes/WbAbstractCamera.js
  resources/web/wwi/nodes/WbLidar.js
  resources/web/wwi/nodes/WbRadar.js
  resources/web/wwi/protos/ProtoCamera.proto
Labels: enhancement

#5634 Add light sensor optional rendering to the web proto viewer
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/nodes/WbLightSensor.js
  resources/web/wwi/nodes/WbRadar.js
  resources/web/wwi/protos/ProtoSensor.proto
  resources/web/wwi/test.html
Labels: enhancement

#5637 Merge develop in feature-web-proto
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  docs/reference/changelog-r2023.md
  projects/robots/softbank/nao/protos/Nao.proto
  projects/robots/softbank/nao/protos/NaoLeftWristH21.proto
  projects/robots/softbank/nao/protos/NaoLeftWristH25Realistic.proto
  projects/robots/softbank/nao/protos/NaoRightWristH21.proto
  projects/robots/softbank/nao/protos/NaoRightWristH25Realistic.proto
  resources/web/wwi/nodes/WbAppearance.js
  resources/web/wwi/nodes/WbBackground.js
  resources/web/wwi/nodes/WbGeometry.js
  resources/web/wwi/nodes/WbPbrAppearance.js
  resources/web/wwi/nodes/WbPointSet.js
  resources/web/wwi/nodes/WbScene.js
  resources/web/wwi/nodes/WbShape.js
  resources/web/wwi/nodes/WbTriangleMeshGeometry.js
  resources/web/wwi/nodes/WbViewpoint.js
  resources/web/wwi/wren/WbWrenBloom.js
  resources/web/wwi/wren/WbWrenGtao.js
  resources/web/wwi/wren/WbWrenHdr.js
  resources/web/wwi/wren/WbWrenPicker.js
  resources/web/wwi/wren/WbWrenPostProcessingEffects.js
  resources/web/wwi/wren/WbWrenShaders.js
Labels: synchronization

#5640 Fix enable/disable SF tracking in Python API
  docs/reference/changelog-r2023.md
  lib/controller/python/controller/field.py
Labels: bug

#5635 Add pen optional rendering to the web proto viewer
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/nodes/WbAbstractCamera.js
  resources/web/wwi/nodes/WbCamera.js
  resources/web/wwi/nodes/WbLidar.js
  resources/web/wwi/nodes/WbLightSensor.js
  resources/web/wwi/nodes/WbPen.js
  resources/web/wwi/nodes/WbRadar.js
  resources/web/wwi/nodes/WbRangeFinder.js
  resources/web/wwi/protos/ProtoSensor.proto
Labels: enhancement

#5644 Add delete function in devices
  resources/web/wwi/nodes/WbAbstractCamera.js
  resources/web/wwi/nodes/WbLidar.js
  resources/web/wwi/nodes/WbLightSensor.js
  resources/web/wwi/nodes/WbPen.js
  resources/web/wwi/nodes/WbRadar.js
  resources/web/wwi/protos/ProtoCamera.proto
  resources/web/wwi/protos/ProtoSensor.proto
  resources/web/wwi/test.html
Labels: enhancement

#5645 Display connector in web proto viewer
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/nodes/WbConnector.js
  resources/web/wwi/protos/ProtoSensor.proto
  resources/web/wwi/test.html
Labels: enhancement

#5649 Fixed compilation of ROS controller
  projects/default/controllers/ros/RosSupervisor.cpp
Labels: bug, test distribution

#5648 Deprecated supervisor node disable/enable contact point tracking func…
  docs/reference/changelog-r2023.md
  src/controller/c/supervisor.c
Labels: cleanup

#5651 Distribute runtime.ini for BotStudio controllers
  docs/guide/epuck.md
  docs/reference/changelog-r2023.md
  projects/robots/gctronic/e-puck/controllers/line_follower/runtime.ini
  projects/robots/gctronic/e-puck/controllers/obstacle/runtime.ini
  projects/samples/curriculum/controllers/beginner_better_collision_avoidance_algorithm/runtime.ini
  projects/samples/curriculum/controllers/beginner_blinking_e-puck/runtime.ini
  projects/samples/curriculum/controllers/beginner_e-puck_dance/runtime.ini
  projects/samples/curriculum/controllers/beginner_finite_state_machine/runtime.ini
  projects/samples/curriculum/controllers/beginner_linear_camera/runtime.ini
  projects/samples/curriculum/controllers/beginner_move_your_e-puck/runtime.ini
  projects/samples/curriculum/controllers/beginner_rally/runtime.ini
  projects/samples/curriculum/controllers/novice_remain_in_shadow/runtime.ini
  projects/samples/curriculum/controllers/novice_train/runtime.ini
Labels: bug

#5638 Improve enable/disable pose tracking API function
  docs/reference/changelog-r2023.md
  docs/reference/supervisor.md
  src/controller/c/supervisor.c
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  tests/api/controllers/center_of_mass_and_contact_points/center_of_mass_and_contact_points.c
  tests/api/controllers/supervisor_field/supervisor_field.c
  tests/api/controllers/supervisor_get_position_orientation_pose/supervisor_get_position_orientation_pose.c
  tests/api/worlds/supervisor_get_position_orientation_pose.wbt
Labels: bug, enhancement, test suite

#5658 FLU: emergency buttuon
  projects/objects/factory/tools/protos/EmergencyButton.proto
Labels: bug

#5659 Merge master in develop
  docs/reference/changelog-r2023.md
  docs/reference/supervisor.md
  projects/objects/factory/tools/protos/EmergencyButton.proto
  src/controller/c/supervisor.c
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  tests/api/controllers/center_of_mass_and_contact_points/center_of_mass_and_contact_points.c
  tests/api/controllers/supervisor_field/supervisor_field.c
  tests/api/controllers/supervisor_get_position_orientation_pose/supervisor_get_position_orientation_pose.c
  tests/api/worlds/supervisor_get_position_orientation_pose.wbt
Labels: test suite, synchronization

#5641 Display distance sensor in web proto viewer
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/images/icons/arrow_left.svg
  resources/web/wwi/images/icons/clear.svg
  resources/web/wwi/nodes/WbDistanceSensor.js
  resources/web/wwi/nodes/WbLookupTable.js
  resources/web/wwi/nodes/WbTransform.js
  resources/web/wwi/nodes/utils/WbVector3.js
  resources/web/wwi/protos/ProtoSensor.proto
  src/wren/DynamicMesh.cpp
Labels: enhancement

#5660 Slider joint in web proto viewer
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/ProtoManager.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/nodes/WbHingeJoint.js
  resources/web/wwi/nodes/WbJoint.js
  resources/web/wwi/nodes/WbSliderJoint.js
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protos/ProtoBox.proto
Labels: bug

#5664 Enhancement hinge2joints slider
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/nodes/WbHinge2Joint.js
  resources/web/wwi/nodes/WbHingeJoint.js
  resources/web/wwi/test.html
Labels: enhancement

#5667 Merge master into develop
  docs/reference/changelog-r2023.md
  src/controller/c/robot.c
  src/controller/c/scheduler.c
  src/controller/c/scheduler.h
  src/controller/c/tcp_client.c
  src/controller/c/tcp_client.h
Labels: synchronization

#5668 Ball joint slider
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/nodes/WbBallJoint.js
  resources/web/wwi/nodes/WbHinge2Joint.js
  resources/web/wwi/nodes/WbHingeJoint.js
  resources/web/wwi/test.html
Labels: enhancement

#5665 Update altimeter node documentation
  docs/reference/altimeter.md
Labels: documentation

#5674 Fix cadshape move to viewpoint
  src/webots/nodes/WbCadShape.cpp
Labels: bug

#5639 Fix memory leaks
  docs/reference/changelog-r2023.md
  src/webots/gui/WbView3D.cpp
  src/webots/nodes/WbGeometry.cpp
  src/wren/PbrMaterial.cpp
  src/wren/PbrMaterial.hpp
  src/wren/PhongMaterial.cpp
  src/wren/PhongMaterial.hpp
  src/wren/StaticMesh.cpp
  src/wren/Texture.cpp
  src/wren/TextureCubeMapBaker.cpp
Labels: bug, test suite, test sources

#5675 remove unused variable and fix default axis
  src/webots/maths/WbRotation.cpp
  src/webots/maths/WbRotation.hpp
  src/webots/nodes/utils/WbBoundingSphere.cpp
  src/webots/nodes/utils/WbBoundingSphere.hpp
Labels: cleanup

#5676 Fix infinite dictionary update
  docs/reference/changelog-r2023.md
  projects/robots/franka_emika/panda/protos/Panda.proto
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/utils/WbDictionary.cpp
  src/webots/nodes/utils/WbDictionary.hpp
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeOperations.hpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbNodeUtilities.hpp
  src/webots/nodes/utils/WbTemplateManager.cpp
  src/webots/nodes/utils/WbTemplateManager.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbVrmlNodeUtilities.cpp
  src/webots/vrml/WbVrmlNodeUtilities.hpp
Labels: crash, test suite

#5663 Disable Select button in WbExtendedStringEditor for restricted fields
  docs/reference/changelog-r2023.md
  src/webots/scene_tree/WbExtendedStringEditor.cpp
  src/webots/scene_tree/WbExtendedStringEditor.hpp
Labels: enhancement, test webots build

#5671 Fix wrong assertion failure for console redirection
  src/controller/c/robot.c
Labels: bug

#5680 Improve robustness to NaN values in robot window plots
  docs/reference/changelog-r2023.md
  resources/projects/plugins/robot_windows/generic/timeplot_widget.js
Labels: bug

#5685 Better working directory on Windows
  scripts/install/msys.sh
Labels: enhancement

#5691 Add a troubleshooting section for macOS installation with respect to Rosetta
  docs/guide/images/rosetta_setting.png
  docs/guide/installation-procedure.md
Labels: documentation

#5686 Fix infinite loop updating ODE geometries
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbGeometry.cpp
Labels: crash, test suite

#5689 Cleanup libcontroller sync in test suite
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  scripts/packaging/sync_controller_lib.sh
Labels: cleanup

#5692 Add necessary first line in proto file examples
  docs/guide/tutorial-7-your-first-proto.md
Labels: documentation
