Repository cyberbotics/webots, pull requests merged in 2022-02, with the labels that each got.

#4171 Fix paperboat texture mapping
  projects/objects/toys/protos/PaperBoat/meshes/geom.obj
Labels: enhancement

#4173 Fix fire exit image path
  projects/objects/hospital/protos/EmergencyExitSign.proto
  projects/objects/hospital/protos/textures/fire_exit.jpg
  projects/samples/environments/factory/worlds/factory.wbt
Labels: bug

#4067 fix openAL warnings
  src/webots/Makefile
  src/webots/core/WbLog.cpp
  src/webots/core/WbLog.hpp
  src/webots/gui/WbSimulationView.cpp
  src/webots/gui/WbSingleTaskApplication.cpp
  src/webots/launcher/webots-linux.sh
  src/webots/sound/WbSoundClip.cpp
  src/webots/sound/WbSoundEngine.cpp
  src/webots/sound/WbSoundEngine.hpp
  src/webots/sound/WbSoundSource.cpp
  src/webots/util/WbPerformanceLog.cpp
  tests/test_suite.py
Labels: test world update

#4175 Updated to the latest version of MATLAB
  docs/guide/using-matlab.md
Labels: documentation

#4176 Fix-robot-window
  include/controller/c/webots/plugins/robot_window/generic_robot_window/generic.h
  resources/nodes/Robot.wrl
  resources/projects/libraries/generic_robot_window/generic.c
  resources/projects/plugins/robot_windows/generic/generic.js
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbRobotWindow.cpp
Labels: bug, test world update

#4178 Add warning for IS referring to unknown PROTO parameter
  src/webots/vrml/WbNode.cpp
Labels: enhancement, test suite, test sources

#4177 New HDR background: music hall.
  docs/guide/object-backgrounds.md
  docs/reference/changelog-r2022.md
  projects/default/worlds/textures/cubic/music_hall_back.hdr
  projects/default/worlds/textures/cubic/music_hall_back.jpg
  projects/default/worlds/textures/cubic/music_hall_bottom.hdr
  projects/default/worlds/textures/cubic/music_hall_bottom.jpg
  projects/default/worlds/textures/cubic/music_hall_front.hdr
  projects/default/worlds/textures/cubic/music_hall_front.jpg
  projects/default/worlds/textures/cubic/music_hall_left.hdr
  projects/default/worlds/textures/cubic/music_hall_left.jpg
  projects/default/worlds/textures/cubic/music_hall_right.hdr
  projects/default/worlds/textures/cubic/music_hall_right.jpg
  projects/default/worlds/textures/cubic/music_hall_top.hdr
  projects/default/worlds/textures/cubic/music_hall_top.jpg
  projects/objects/backgrounds/protos/TexturedBackground.proto
  projects/objects/backgrounds/protos/TexturedBackgroundLight.proto
  scripts/image_tools/README.md
Labels: enhancement

#4181 Quick fix for the Nao PROTO
  projects/robots/softbank/nao/protos/Nao.proto
Labels: bug

#4180 Enhanced Nao PROTO
  docs/guide/nao.md
  docs/reference/changelog-r2022.md
  projects/robots/softbank/nao/protos/Nao.proto
  projects/robots/softbank/nao/worlds/nao_robocup.wbt
  projects/robots/softbank/nao/worlds/robotstadium_nao_vs_robotis-op2.wbt
Labels: enhancement

#4117 Enhancement web viewer
  docs/guide/web-animation.md
  docs/guide/web-simulation.md
  resources/web/streaming_viewer/index.html
  resources/web/wwi/Animation.js
  resources/web/wwi/InformationPanel.js
  resources/web/wwi/MouseEvents.js
  resources/web/wwi/MultimediaClient.js
  resources/web/wwi/Parser.js
  resources/web/wwi/Stream.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/css/animation.css
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/css/wwi.css
  resources/web/wwi/images/icons.svg
  resources/web/wwi/images/quit.png
  resources/web/wwi/images/quit_grey.png
  resources/web/wwi/images/quit_hover.png
  resources/web/wwi/nodes/utils/WbVector3.js
  resources/web/wwi/nodes/utils/WbVector4.js
  resources/web/wwi/webots.js
  src/webots/gui/WbStreamingServer.cpp
Labels: enhancement

#4184 Merge `released` into `master`
  docs/discord/development-2021.md
  docs/discord/development-2022.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/guide/using-matlab.md
Labels: documentation

#4186 Fix `ScuffedPlastic` and `WornBurlap` line ending
  projects/appearances/protos/ScuffedPlastic.proto
  projects/appearances/protos/WornBurlap.proto
Labels: cleanup

#4183 Fixed world update test
  projects/robots/softbank/nao/worlds/nao_robocup.wbt
  projects/robots/softbank/nao/worlds/robotstadium_nao_vs_robotis-op2.wbt
Labels: test world update

#4172 Fix ColladaShapes colors and orientations
  docs/reference/mesh.md
  resources/nodes/Mesh.wrl
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbMesh.hpp
  src/webots/nodes/utils/WbNodeOperations.cpp
Labels: documentation, test suite, test sources

#4193 Fix camelBase name in WbMesh
  src/webots/nodes/WbMesh.cpp
Labels: test suite, test sources

#4167 Fix values greater than maxRange for the RangeFinder
  docs/reference/changelog-r2022.md
  docs/reference/rangefinder.md
  resources/wren/shaders/encode_depth.frag
  resources/wren/shaders/motion_blur.frag
  src/webots/wren/WbWrenCamera.cpp
  src/webots/wren/WbWrenPostProcessingEffects.cpp
  tests/api/controllers/range_finder_checker/range_finder_checker.c
  tests/api/worlds/range_finder.wbt
Labels: documentation, test suite, test sources

#4197 Enhancement override click function
  resources/web/wwi/Toolbar.js
Labels: enhancement

#4198 Change nao default color to red
  docs/guide/nao.md
  projects/robots/softbank/nao/protos/Nao.proto
Labels: enhancement

#4199 Fix Nao.proto indentation
  projects/robots/softbank/nao/protos/Nao.proto
Labels: documentation

#4201 Convert `gears.wbt` to ENU
  docs/reference/changelog-r2022.md
  projects/samples/howto/gears/worlds/gears.wbt
Labels: cleanup

#4202 Fixed md5sum of libpico.zip on Windows
  dependencies/Makefile.windows
  projects/robots/gctronic/e-puck/plugins/remote_controls/e-puck_bluetooth/Wrapper.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Wrapper.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Wrapper.cpp
  resources/projects/libraries/qt_utils/motion_editor/MotionWidget.cpp
  src/controller/c/motion.c
  src/controller/c/receiver.c
  src/controller/c/speaker.c
  src/webots/nodes/WbAbstractTransform.cpp
  src/webots/nodes/WbCone.cpp
  src/webots/nodes/WbCylinder.cpp
  src/webots/nodes/WbDistanceSensor.cpp
  src/webots/nodes/WbEmitter.cpp
  src/webots/nodes/WbGroup.cpp
  src/webots/nodes/WbLensFlare.cpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbNormal.hpp
  src/webots/nodes/WbRadar.cpp
  src/webots/nodes/WbSolidReference.cpp
  src/webots/nodes/WbTrack.cpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/nodes/WbViewpoint.hpp
  src/webots/user_commands/WbUndoStack.cpp
  src/wren/Renderable.cpp
  src/wren/Scene.cpp
  tests/sources/test_cppcheck.py
  tests/sources/test_line_ending.py
Labels: bug, test distribution, test suite, test sources

#4212 Removed unused variable causing warning
  tests/api/controllers/gps_speed/gps_speed.c
Labels: cleanup

#4213 Removed unused variables
  tests/api/controllers/robot_parallel_step/robot_parallel_step.c
Labels: cleanup

#4218 Fix asset download in `Camera` device
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbCamera.cpp
Labels: bug, test suite

#4221 Add python to controllerArgs
  docs/reference/robot.md
Labels: documentation

#4222 Fix some rotations on PROTOs with dae files
  projects/devices/sick/protos/SickS300.proto
  projects/robots/rec/fabtino/protos/Fabtino.proto
  projects/robots/robotnik/summit_xl_steel/protos/SummitXlSteel.proto
Labels: bug

#4208 Improve robot window to be able to embbed it
  docs/guide/web-simulation.md
  resources/projects/plugins/robot_windows/generic/generic.js
  resources/web/wwi/RobotWindow.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
Labels: enhancement

#4226 Fixed compilation warning
  tests/physics/plugins/physics/ode_dif_exporter/ode_dif_exporter.c
Labels: cleanup

#4228 Fix missing irradiance warning message
  src/webots/nodes/WbBackground.cpp
Labels: cleanup

#4224 Fix bugs tracks
  projects/samples/devices/worlds/track.wbt
  resources/web/streaming_viewer/index.html
  resources/web/wwi/Parser.js
  src/webots/nodes/WbTrack.cpp
  tests/api/worlds/track.wbt
Labels: bug, test suite

#4230 Uploaded new libpico packages compatible with C++17
  dependencies/Makefile.linux
  dependencies/Makefile.mac
Labels: cleanup

#4231 Merge master into develop
  dependencies/Makefile.linux
  dependencies/Makefile.mac
Labels: cleanup

#4232 fix export animation
  src/webots/gui/WbMainWindow.cpp
Labels: bug

#4236 Fix background of url.wbt
  projects/samples/howto/url/worlds/url.wbt
Labels: bug

#4233 Add new matlab command preference
  docs/guide/using-matlab.md
  docs/reference/changelog-r2022.md
  src/webots/control/WbController.cpp
  src/webots/control/WbLanguageTools.cpp
  src/webots/core/WbPreferences.cpp
  src/webots/core/WbPreferences.hpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbPreferencesDialog.hpp
Labels: bug, test suite, test sources

#4234 Automatically convert urls
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/utils/WbUrl.cpp
Labels: bug, enhancement, test suite

#4237 Enhancement-share-simulation
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/gui/WbShareWindow.cpp
  src/webots/gui/WbShareWindow.hpp
Labels: enhancement

#4246 Fix x3d tag
  src/webots/vrml/WbVrmlWriter.cpp
Labels: enhancement

#4245 Fix notification of field change in a PROTO not propagating through DEF/USE
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbMesh.cpp
  src/webots/vrml/WbNode.cpp
  tests/api/controllers/modify_nested_def_node/modify_nested_def_node.c
  tests/api/protos/ProtoShape.proto
  tests/api/worlds/nested_def_nodes.wbt
Labels: test suite, test sources

#4247 Merge `released` into `master`
  docs/discord/development-2019.md
  docs/discord/development-2022.md
  docs/discord/documentation.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2022.md
Labels: documentation

#4249 Fixed compilation on Windows failing after gcc update
  src/webots/Makefile
Labels: bug, cleanup

#4248 Prevent failure in one job (within a matrix) to fail the other
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
Labels: enhancement

#4257 Forbid USE of TrackWheel
  docs/reference/changelog-r2022.md
  projects/samples/devices/worlds/track.wbt
  src/webots/nodes/utils/WbNodeUtilities.cpp
Labels: cleanup, test suite

#4262 Correct parsing of ID
  resources/web/wwi/Parser.js
Labels: bug, feature

#4263 Sanitize urls in webotsjs
  resources/web/wwi/Parser.js
Labels: enhancement, cleanup

#4256 Add anchor rendering
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbBasicJoint.hpp
  src/webots/nodes/WbHinge2Joint.cpp
  src/webots/nodes/WbHingeJoint.cpp
  src/webots/nodes/WbHingeJoint.hpp
Labels: feature, test sources

#4070 Fix physic reset bug
  docs/reference/changelog-r2022.md
  src/ode/ode/src/collision_kernel.cpp
  src/ode/ode/src/ode_MT/clustering/cluster.cpp
  src/ode/ode/src/ode_MT/clustering/cluster.h
  src/ode/ode/src/ode_MT/ode_MT.cpp
  src/ode/ode/src/ode_MT/ode_MT.h
  src/webots/engine/WbSimulationCluster.cpp
  src/webots/nodes/utils/WbSolidMerger.cpp
  src/webots/ode/WbOdeGeomData.hpp
Labels: bug, test suite

#4265 modified behavior of default matlab command
  src/webots/control/WbController.cpp
  src/webots/control/WbLanguageTools.cpp
  src/webots/control/WbLanguageTools.hpp
  src/webots/core/WbPreferences.cpp
  src/webots/core/WbPreferences.hpp
Labels: bug, test suite, test sources

#4270 Fix url search in distributions
  src/webots/core/WbVersion.hpp
  src/webots/nodes/utils/WbUrl.cpp
Labels: cleanup, test suite, test sources

#4216 Fix details on robot window
  projects/samples/howto/custom_robot_window_simple/plugins/robot_windows/custom_robot_window_simple/custom_robot_window_simple.html
  resources/projects/plugins/robot_windows/generic/device_widget.js
  resources/projects/plugins/robot_windows/generic/generic.css
  resources/web/wwi/RobotWindow.js
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbRobotWindow.cpp
  src/webots/gui/WbRobotWindow.hpp
  src/webots/gui/WbStreamingServer.cpp
  src/webots/gui/WbStreamingServer.hpp
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbView3D.hpp
Labels: enhancement

#4277 Merge `released` into `master`
  docs/discord/development-2019.md
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/development-2022.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
Labels: documentation

#4278 Merge `master` into `develop`
  docs/discord/development-2019.md
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/development-2022.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/reference/changelog-r2022.md
  projects/samples/devices/worlds/track.wbt
  resources/web/wwi/Parser.js
  src/ode/ode/src/collision_kernel.cpp
  src/ode/ode/src/ode_MT/clustering/cluster.cpp
  src/ode/ode/src/ode_MT/clustering/cluster.h
  src/ode/ode/src/ode_MT/ode_MT.cpp
  src/ode/ode/src/ode_MT/ode_MT.h
  src/webots/control/WbController.cpp
  src/webots/control/WbLanguageTools.cpp
  src/webots/control/WbLanguageTools.hpp
  src/webots/core/WbPreferences.cpp
  src/webots/core/WbPreferences.hpp
  src/webots/core/WbVersion.hpp
  src/webots/engine/WbSimulationCluster.cpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbSolidMerger.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/ode/WbOdeGeomData.hpp
Labels: test suite, test sources, synchronization

#4279 Improve-code-robot-window
  resources/web/wwi/RobotWindow.js
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbStreamingServer.hpp
Labels: cleanup

#4281 Fix `Skin` segmentation and Range Finder invisibility
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/WbSkin.hpp
Labels: bug, test suite, test sources

#4243 Allow negative scale
  docs/reference/changelog-r2022.md
  docs/reference/indexedfaceset.md
  docs/reference/mesh.md
  docs/reference/transform.md
  include/wren/renderable.h
  projects/shapes/protos/ColladaShapes.proto
  resources/nodes/Mesh.wrl
  src/webots/core/WbQjsCollada.cpp
  src/webots/core/WbQjsCollada.hpp
  src/webots/gui/WbDragResizeEvent.cpp
  src/webots/gui/WbDragResizeEvent.hpp
  src/webots/gui/WbDragScaleEvent.cpp
  src/webots/gui/WbDragTransformEvent.cpp
  src/webots/nodes/WbAbstractTransform.cpp
  src/webots/nodes/WbAbstractTransform.hpp
  src/webots/nodes/WbIndexedFaceSet.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbMesh.hpp
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/WbTriangleMeshGeometry.cpp
  src/webots/nodes/WbTriangleMeshGeometry.hpp
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeOperations.hpp
  src/webots/nodes/utils/WbTriangleMesh.cpp
  src/webots/nodes/utils/WbTriangleMesh.hpp
  src/wren/GlState.cpp
  src/wren/GlState.hpp
  src/wren/Renderable.cpp
  src/wren/Renderable.hpp
  src/wren/Scene.cpp
Labels: enhancement, documentation, test suite, test sources

#4274 Add two nao motion files
  projects/robots/softbank/nao/controllers/nao_demo/nao_demo.c
  projects/robots/softbank/nao/controllers/nao_demo_python/nao_demo_python.py
  projects/robots/softbank/nao/motions/TaiChi.motion
  projects/robots/softbank/nao/motions/WipeForehead.motion
  projects/robots/softbank/nao/worlds/.nao_room.wbproj
Labels: enhancement

#4276 Fix Wrenjs compilation
  resources/Makefile.include
  src/wren/.gitignore
Labels: bug, test suite

#4288 Fix simulation server when worlds is a top folder
  resources/web/server/simulation_server.py
Labels: bug

#4290 Fix update rate of webotsjs
  src/webots/engine/WbAnimationRecorder.cpp
  src/webots/engine/WbAnimationRecorder.hpp
  src/webots/gui/WbStreamingServer.cpp
  src/webots/gui/WbStreamingServer.hpp
  src/webots/gui/WbX3dStreamingServer.cpp
  src/webots/gui/WbX3dStreamingServer.hpp
Labels: enhancement
