Repository cyberbotics/webots, pull requests merged in 2022-05, with the labels that each got.

#4491 Fix basenode conversion
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbLight.cpp
  src/webots/nodes/WbLight.hpp
  src/webots/nodes/WbPointLight.cpp
  src/webots/nodes/WbPointLight.hpp
  src/webots/vrml/WbField.cpp
Labels: bug, test suite, test sources

#4498 Clean-up creation of QProcess in the WbController class
  src/webots/control/WbController.cpp
Labels: cleanup

#4499 Fix bug when clicking on a CadShape
  resources/web/wwi/nodes/WbGroup.js
Labels: bug

#4500 Fix panda demo
  docs/guide/object-factory.md
  projects/objects/factory/tools/protos/Bolt.proto
  projects/objects/factory/tools/protos/EyeScrew.proto
  projects/objects/factory/tools/protos/Nut.proto
  projects/objects/factory/tools/protos/ScrewHole.proto
  projects/objects/factory/tools/protos/Washer.proto
  projects/robots/franka_emika/panda/worlds/panda.wbt
Labels: bug

#4503 Add a function to change the ambiant occlusion level
  docs/guide/web-animation.md
  docs/guide/web-scene.md
  docs/guide/web-simulation.md
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
Labels: enhancement

#4505 Fix warning message during loading
  resources/web/wwi/X3dScene.js
Labels: bug

#4504 Fix web components
  resources/web/wwi/FloatingWindow.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/css/toolbar.css
Labels: bug

#4506 Fix typo in streaming error message
  src/webots/gui/WbX3dStreamingServer.cpp
Labels: enhancement

#4497 WebotsJS: Fix PROTO regeneration and update bugs
  resources/web/wwi/Parser.js
  resources/web/wwi/nodes/WbBaseNode.js
  resources/web/wwi/nodes/WbBox.js
  resources/web/wwi/nodes/WbCapsule.js
  resources/web/wwi/nodes/WbCone.js
  resources/web/wwi/nodes/WbCylinder.js
  resources/web/wwi/nodes/WbDirectionalLight.js
  resources/web/wwi/nodes/WbElevationGrid.js
  resources/web/wwi/nodes/WbGeometry.js
  resources/web/wwi/nodes/WbImageTexture.js
  resources/web/wwi/nodes/WbIndexedLineSet.js
  resources/web/wwi/nodes/WbPlane.js
  resources/web/wwi/nodes/WbPointLight.js
  resources/web/wwi/nodes/WbPointSet.js
  resources/web/wwi/nodes/WbSphere.js
  resources/web/wwi/nodes/WbSpotLight.js
  resources/web/wwi/nodes/WbTrack.js
  resources/web/wwi/nodes/WbTransform.js
  resources/web/wwi/nodes/WbTriangleMeshGeometry.js
  resources/web/wwi/nodes/WbWorld.js
  src/webots/gui/WbX3dStreamingServer.cpp
Labels: bug

#4507 Fix streaming when lights are involved
  src/webots/nodes/WbDirectionalLight.cpp
  src/webots/nodes/WbDirectionalLight.hpp
  src/webots/nodes/WbSpotLight.cpp
  src/webots/nodes/WbSpotLight.hpp
Labels: bug, cleanup, test sources

#4509 Fix collision between kinematic robots
  docs/reference/changelog-r2022.md
  src/webots/engine/WbSimulationCluster.cpp
Labels: bug, test suite, test sources

#4516 Merge master in develop
  .github/workflows/discord_updater.yml
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  .github/workflows/tests_doc.yml
  .github/workflows/tests_sources.yml
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/reference/changelog-r2022.md
  docs/reference/solid.md
  lib/controller/.gitignore
  projects/default/libraries/vehicle/Makefile
  projects/default/libraries/vehicle/python/.gitignore
  projects/default/libraries/vehicle/python/Makefile
  projects/robots/epfl/biorob/worlds/salamander.wbt
  projects/robots/robotis/darwin-op/libraries/Makefile
  projects/robots/robotis/darwin-op/libraries/python/.gitignore
  projects/robots/robotis/darwin-op/libraries/python/Makefile
  projects/robots/robotis/darwin-op/libraries/python310/.gitignore
  projects/samples/geometries/worlds/floating_geometries.wbt
  projects/samples/rendering/worlds/animated_skin.wbt
  resources/web/wwi/X3dScene.js
  scripts/install/bash_profile.windows
  scripts/install/bashrc.linux
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/msys.sh
  scripts/packaging/files_core.txt
  src/controller/Makefile
  src/controller/python/.gitignore
  src/controller/python/Makefile
  src/ode/ode/src/fluid_dynamics/immersion_capsule.cpp
  src/ode/ode/src/fluid_dynamics/immersion_cylinder.cpp
  src/ode/ode/src/fluid_dynamics/immersion_kernel.h
  src/webots/control/WbLanguageTools.cpp
  src/webots/engine/WbSimulationCluster.cpp
  src/webots/gui/WbX3dStreamingServer.cpp
  src/webots/nodes/WbBox.cpp
  src/webots/nodes/WbGeometry.cpp
  src/webots/nodes/utils/WbDictionary.cpp
Labels: test suite, test sources, synchronization

#4517 Restore export of shadows
  src/webots/nodes/WbLight.cpp
  src/webots/nodes/WbLight.hpp
Labels: bug

#4513 Fix loading of remote wavefront files in `CadShape` (that reference material files)
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbCadShape.hpp
  src/webots/nodes/WbMesh.cpp
Labels: bug, test suite, test sources

#4521 Fix mir cameras orientation
  projects/robots/mir/mir100/protos/Mir100.proto
Labels: bug

#4522 Fix SickS300 bounding object
  projects/devices/sick/protos/SickS300.proto
Labels: bug

#4526 Improve Supervisor unlimited power description
  docs/guide/tutorial-8-the-supervisor.md
  docs/reference/supervisor.md
Labels: documentation

#4530 Discord publisher manual trigger
  .github/workflows/discord_updater.yml
Labels: discord publishing

#4532 Merge released in master
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/development-2022.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/guide/tutorial-8-the-supervisor.md
  docs/reference/supervisor.md
Labels: synchronization

#4533 Merge master into develop
  .github/workflows/discord_updater.yml
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/development-2022.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/guide/tutorial-8-the-supervisor.md
  docs/reference/supervisor.md
  projects/devices/sick/protos/SickS300.proto
  projects/robots/mir/mir100/protos/Mir100.proto
Labels: test suite, test sources, synchronization

#4540 Fix errors using to python3.10 and update documentation
  docs/guide/using-python.md
  docs/guide/using-your-ide.md
  src/controller/python/Makefile
  src/webots/control/WbLanguageTools.cpp
Labels: bug, test suite

#4541 Merge master into develop
  docs/guide/using-python.md
  docs/guide/using-your-ide.md
  src/controller/python/Makefile
  src/webots/control/WbLanguageTools.cpp
Labels: test suite, test sources, synchronization

#4502 Add support for Ubuntu 22.04
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  dependencies/Makefile.linux
  docs/guide/installation-procedure.md
  docs/guide/system-requirements.md
  docs/guide/using-python.md
  docs/reference/changelog-r2022.md
  projects/default/libraries/vehicle/Makefile
  projects/default/resources/Makefile
  projects/robots/robotis/darwin-op/libraries/Makefile
  projects/robots/robotis/darwin-op/libraries/python27/.gitignore
  projects/robots/robotis/darwin-op/libraries/python35/.gitignore
  projects/robots/robotis/darwin-op/libraries/python36/.gitignore
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/linux_runtime_dependencies.sh
  scripts/install/linux_test_dependencies.sh
  scripts/packaging/Makefile
  scripts/packaging/exist_in_projects_linux_20.04.txt
  scripts/packaging/exist_in_projects_linux_22.04.txt
  scripts/packaging/files_core.txt
  scripts/packaging/generate_projects_files.py
  scripts/packaging/webots_distro.c
  src/controller/Makefile
  src/controller/python/Makefile
  src/webots/control/WbLanguageTools.cpp
  tests/test_suite.py
Labels: upgrade, test distribution, test suite

#4548 Improve deprecation flags and double initialization
  scripts/packaging/Makefile
  tests/test_suite.py
Labels: cleanup, test suite

#4550 Fix documentation for copying camera image in display
  docs/reference/camera.md
  docs/reference/display.md
Labels: documentation

#4552 Screw the Scara in its example
  projects/robots/epson/scara_t6/worlds/industrial_example.wbt
Labels: enhancement

#4553 Fix surveyor rear box (FLU)
  projects/robots/surveyor/protos/SurveyorSrv1.proto
  projects/robots/surveyor/worlds/srv-1.wbt
Labels: bug

#4544 Enhancement cloud share
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/gui/WbShareWindow.cpp
  src/webots/gui/WbShareWindow.hpp
Labels: enhancement

#4546 Set PointCloud2 fields and point_step
  projects/default/controllers/ros/RosLidar.cpp
Labels: test sources, test ros

#4561 Add a forklift proto
  docs/guide/images/objects/forklift/Forklift/model.png
  docs/guide/images/objects/forklift/Forklift/model.thumbnail.png
  docs/guide/object-factory.md
  docs/guide/objects.md
  docs/reference/changelog-r2022.md
  projects/objects/factory/forklift/protos/Forklift.proto
  projects/objects/factory/forklift/protos/icons/Forklift.png
  projects/objects/factory/forklift/protos/meshes/forklift.mtl
  projects/objects/factory/forklift/protos/meshes/forklift.obj
  projects/objects/factory/forklift/protos/meshes/textures/forklift_base_color.jpg
  projects/objects/factory/forklift/protos/meshes/textures/forklift_metalness.jpg
  projects/objects/factory/forklift/protos/meshes/textures/forklift_normal.jpg
Labels: enhancement

#4562 Merge Released in Master
  docs/discord/development-2022.md
  docs/discord/documentation.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/reference/camera.md
  docs/reference/display.md
Labels: synchronization

#4560 Merge Master into Develop
  docs/discord/development-2022.md
  docs/discord/documentation.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/reference/camera.md
  docs/reference/display.md
  projects/default/controllers/ros/RosLidar.cpp
  projects/robots/surveyor/protos/SurveyorSrv1.proto
  projects/robots/surveyor/worlds/srv-1.wbt
Labels: test suite, test sources, synchronization

#4565 Fix simulation server
  resources/web/server/simulation_server.py
  src/webots/gui/WbTcpServer.hpp
Labels: bug

#4558 Enforce line max lenght for WebotsJS
  .eslintrc.json
  resources/web/wwi/Animation.js
  resources/web/wwi/FloatingRobotWindow.js
  resources/web/wwi/FloatingWindow.js
  resources/web/wwi/MouseEvents.js
  resources/web/wwi/MultimediaClient.js
  resources/web/wwi/Parser.js
  resources/web/wwi/RobotWindow.js
  resources/web/wwi/Stream.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/hdr_loader.js
  resources/web/wwi/nodes/WbBackground.js
  resources/web/wwi/nodes/WbBox.js
  resources/web/wwi/nodes/WbCapsule.js
  resources/web/wwi/nodes/WbCylinder.js
  resources/web/wwi/nodes/WbDirectionalLight.js
  resources/web/wwi/nodes/WbElevationGrid.js
  resources/web/wwi/nodes/WbFog.js
  resources/web/wwi/nodes/WbGeometry.js
  resources/web/wwi/nodes/WbImageTexture.js
  resources/web/wwi/nodes/WbIndexedFaceSet.js
  resources/web/wwi/nodes/WbMaterial.js
  resources/web/wwi/nodes/WbPbrAppearance.js
  resources/web/wwi/nodes/WbPointLight.js
  resources/web/wwi/nodes/WbSpotLight.js
  resources/web/wwi/nodes/WbTrack.js
  resources/web/wwi/nodes/WbTriangleMeshGeometry.js
  resources/web/wwi/nodes/WbViewpoint.js
  resources/web/wwi/nodes/WbWorld.js
  resources/web/wwi/nodes/utils/WbFieldChecker.js
  resources/web/wwi/nodes/utils/WbMatrix3.js
  resources/web/wwi/nodes/utils/WbMatrix4.js
  resources/web/wwi/nodes/utils/WbVector3.js
  resources/web/wwi/nodes/utils/utils.js
  resources/web/wwi/viewer.js
  resources/web/wwi/webots.js
  resources/web/wwi/wren/WbWrenBloom.js
  resources/web/wwi/wren/WbWrenGtao.js
  resources/web/wwi/wren/WbWrenHdr.js
  resources/web/wwi/wren/WbWrenPicker.js
  resources/web/wwi/wren/WbWrenPostProcessingEffects.js
  resources/web/wwi/wren/WbWrenRenderingContext.js
  resources/web/wwi/wren/WbWrenShaders.js
Labels: cleanup

#4568 Fix crash due to Transform updates in Fuild.boundingObject
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbGeometry.cpp
  src/webots/nodes/WbTransform.cpp
Labels: bug, crash, test suite

#4564 Fix test world update
  projects/robots/epson/scara_t6/worlds/industrial_example.wbt
Labels: bug, test world update

#4570 WebotsJS: fix PBR typo
  resources/web/wwi/Parser.js
Labels: bug
