Repository cyberbotics/webots, pull requests merged in 2022-03, with the labels that each got.

#4292 Merge master in develop
  docs/reference/changelog-r2022.md
  resources/Makefile.include
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/WbSkin.hpp
  src/wren/.gitignore
Labels: test suite, test sources

#4286 patch doc robot window
  docs/guide/controller-plugin.md
Labels: documentation

#4294 Fix sending of robot window names for x3d
  src/webots/gui/WbMultimediaStreamingServer.cpp
  src/webots/gui/WbStreamingServer.cpp
Labels: enhancement

#4295 Remove Ubuntu 18 from develop tests
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/tests_sources.yml
Labels: cleanup

#4301 Add callback for scene loading
  docs/guide/web-animation.md
  resources/web/wwi/WebotsView.js
Labels: enhancement

#4300 Improve robustness of parsing array
  resources/web/wwi/Parser.js
Labels: enhancement

#4293 Enhancement-controller-mavic
  docs/guide/mavic-2-pro.md
  docs/reference/changelog-r2022.md
  projects/robots/dji/mavic/controllers/mavic2pro_patrol/mavic2pro_patrol.py
Labels: enhancement

#4306 Fix onready callback function in WebotsView
  docs/guide/web-animation.md
  docs/guide/web-scene.md
  docs/guide/web-simulation.md
  resources/web/streaming_viewer/setup_viewer.js
  resources/web/wwi/WebotsView.js
Labels: bug

#4308 Cleanup robotWindow
  resources/web/wwi/RobotWindow.js
Labels: cleanup

#4103 Add namespace to Ros Nodehandle and remove redundant robot name prefixes from Ros service and topic names
  docs/guide/using-ros.md
  projects/default/controllers/ros/Ros.cpp
  projects/default/controllers/ros/Ros.hpp
  projects/default/controllers/ros/RosAccelerometer.cpp
  projects/default/controllers/ros/RosAltimeter.cpp
  projects/default/controllers/ros/RosBatterySensor.cpp
  projects/default/controllers/ros/RosBrake.cpp
  projects/default/controllers/ros/RosCamera.cpp
  projects/default/controllers/ros/RosCompass.cpp
  projects/default/controllers/ros/RosConnector.cpp
  projects/default/controllers/ros/RosDevice.cpp
  projects/default/controllers/ros/RosDisplay.cpp
  projects/default/controllers/ros/RosDistanceSensor.cpp
  projects/default/controllers/ros/RosEmitter.cpp
  projects/default/controllers/ros/RosGPS.cpp
  projects/default/controllers/ros/RosGyro.cpp
  projects/default/controllers/ros/RosInertialUnit.cpp
  projects/default/controllers/ros/RosJoystick.cpp
  projects/default/controllers/ros/RosKeyboard.cpp
  projects/default/controllers/ros/RosLED.cpp
  projects/default/controllers/ros/RosLidar.cpp
  projects/default/controllers/ros/RosLightSensor.cpp
  projects/default/controllers/ros/RosMotor.cpp
  projects/default/controllers/ros/RosMotorSensor.cpp
  projects/default/controllers/ros/RosMouse.cpp
  projects/default/controllers/ros/RosPen.cpp
  projects/default/controllers/ros/RosPositionSensor.cpp
  projects/default/controllers/ros/RosRadar.cpp
  projects/default/controllers/ros/RosRangeFinder.cpp
  projects/default/controllers/ros/RosReceiver.cpp
  projects/default/controllers/ros/RosSensor.cpp
  projects/default/controllers/ros/RosSensor.hpp
  projects/default/controllers/ros/RosSkin.cpp
  projects/default/controllers/ros/RosSpeaker.cpp
  projects/default/controllers/ros/RosSupervisor.cpp
  projects/default/controllers/ros/RosTouchSensor.cpp
  projects/vehicles/controllers/ros_automobile/RosAutomobile.cpp
Labels: enhancement

#4259 Docker-compose implementation
  docs/reference/changelog-r2022.md
  resources/web/server/config/simulation/docker/Dockerfile.default
  resources/web/server/config/simulation/docker/docker-compose-default.yml
  resources/web/server/config/simulation/docker/docker-compose-theia.yml
  resources/web/server/simulation_server.py
  resources/web/wwi/Server.js
Labels: enhancement

#4316 Fix typo
  resources/web/wwi/webots.js
Labels: bug, cleanup

#4314 Fix `name` and `materialIndex` causing crash on `.obj` meshes
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbMesh.hpp
Labels: bug, crash, test suite, test sources

#4309 Correction of depth measures
  docs/reference/changelog-r2022.md
  resources/wren/shaders/encode_depth.frag
  resources/wren/shaders/encode_depth.vert
Labels: test suite, test sources

#4318 Fix download of invalid url
  src/webots/nodes/utils/WbDownloader.cpp
  src/webots/nodes/utils/WbDownloader.hpp
Labels: bug, test suite, test sources

#4321 Merge `master` into `develop`
  docs/reference/changelog-r2022.md
  resources/web/wwi/Parser.js
  resources/wren/shaders/encode_depth.frag
  resources/wren/shaders/encode_depth.vert
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbBaseNode.hpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbCamera.hpp
  src/webots/nodes/WbJoint.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbMesh.hpp
  src/webots/nodes/WbSliderJoint.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolid.hpp
  src/webots/nodes/utils/WbDownloader.cpp
  src/webots/nodes/utils/WbDownloader.hpp
  src/webots/scene_tree/WbExtendedStringEditor.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
  tests/api/controllers/robot_urdf/epuck.urdf
  tests/api/controllers/robot_urdf/epuck_reference.urdf
  tests/api/worlds/robot_urdf.wbt
Labels: test suite, test sources, synchronization

#4302 Fix indexedFaceSet Ccw flag
  include/wren/shader_program.h
  resources/wren/shaders/pbr.frag
  resources/wren/shaders/pbr_stencil_ambient_emissive.frag
  resources/wren/shaders/pbr_stencil_diffuse_specular.frag
  resources/wren/shaders/phong.frag
  resources/wren/shaders/phong_stencil_ambient_emissive.frag
  resources/wren/shaders/phong_stencil_diffuse_specular.frag
  src/webots/wren/WbWrenShaders.cpp
  src/wren/CustomUniform.cpp
  src/wren/CustomUniform.hpp
  src/wren/Renderable.cpp
  src/wren/Scene.cpp
  src/wren/ShaderProgram.cpp
  src/wren/ShadowVolumeCaster.cpp
Labels: bug, test suite, test sources

#4330 Improve extern controller documentation
  docs/guide/running-extern-robot-controllers.md
  docs/tests/test_paragraphs.py
Labels: documentation

#4333 Cleanup wrenjs makefile
  src/wren/Makefile
Labels: cleanup

#4339 Async close of dockers
  resources/web/server/simulation_server.py
  src/webots/control/WbController.cpp
Labels: enhancement

#4340 Remove unnecessary loop in ColladaShape
  src/webots/nodes/utils/WbNodeOperations.cpp
Labels: enhancement, test suite, test sources

#4334 Enhancement toolbar min size
  resources/web/wwi/Toolbar.js
Labels: enhancement

#4336 Fix robot window message
  docs/reference/changelog-r2022.md
  docs/reference/robot.md
  include/controller/c/webots/plugins/robot_window/robot_wwi.h
  projects/humans/c3d/controllers/c3d_viewer/c3d_viewer.py
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.html
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.c
  projects/robots/mobsya/thymio/controllers/thymio2_demo/thymio2_demo.c
  projects/samples/howto/custom_robot_window/plugins/robot_windows/custom_robot_window/custom_robot_window.c
  projects/samples/howto/custom_robot_window_simple/controllers/custom_robot_window_simple/custom_robot_window_simple.py
  projects/samples/robotbenchmark/highway_driving/controllers/highway_driving_benchmark/highway_driving_benchmark.py
  projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon_supervisor/marathon_supervisor.c
  projects/samples/robotbenchmark/humanoid_marathon/plugins/robot_windows/humanoid_marathon/humanoid_marathon.html
  projects/samples/robotbenchmark/humanoid_sprint/controllers/race_stopwatch/race_stopwatch.c
  projects/samples/robotbenchmark/inverted_pendulum/controllers/inverted_pendulum_benchmark/inverted_pendulum_benchmark.py
  projects/samples/robotbenchmark/maze_runner/controllers/supervisor/supervisor.py
  projects/samples/robotbenchmark/obstacle_avoidance/controllers/supervisor/supervisor.py
  projects/samples/robotbenchmark/pick_and_place/controllers/pick_and_place_benchmark/pick_and_place_benchmark.py
  projects/samples/robotbenchmark/pit_escape/controllers/pit_escape_supervisor/pit_escape_supervisor.c
  projects/samples/robotbenchmark/robot_programming/controllers/supervisor/supervisor.py
  projects/samples/robotbenchmark/square_path/controllers/square_path_supervisor/square_path_supervisor.py
  projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking_benchmark/visual_tracking_benchmark.py
  projects/samples/robotbenchmark/wall_following/controllers/wall_following_supervisor/wall_following_supervisor.c
  projects/vehicles/plugins/robot_windows/automobile/automobile.c
  resources/projects/plugins/robot_windows/generic/generic.c
  src/controller/c/robot.c
  src/controller/cpp/Robot.cpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbRobot.hpp
  tests/api/controllers/robot_window_html/robot_window_html.c
Labels: bug, enhancement

#4238 Replace QNetworkDiskCache with custom cache
  docs/reference/contactproperties.md
  docs/reference/linearmotor.md
  docs/reference/rotationalmotor.md
  resources/nodes/ContactProperties.wrl
  resources/nodes/LinearMotor.wrl
  resources/nodes/RotationalMotor.wrl
  scripts/packaging/update_urls.py
  src/webots/Makefile
  src/webots/core/WbNetwork.cpp
  src/webots/core/WbNetwork.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbPreferencesDialog.hpp
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbContactProperties.cpp
  src/webots/nodes/WbDistanceSensor.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/WbSpeaker.cpp
  src/webots/nodes/WbTriangleMeshGeometry.cpp
  src/webots/nodes/WbTriangleMeshGeometry.hpp
  src/webots/nodes/utils/WbDownloader.cpp
  src/webots/nodes/utils/WbDownloader.hpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/sound/WbContactSound.cpp
  src/webots/sound/WbSoundClip.cpp
  src/webots/sound/WbSoundClip.hpp
  src/webots/sound/WbSoundEngine.cpp
  src/webots/sound/WbSoundEngine.hpp
  src/webots/sound/WbWaveFile.cpp
  src/webots/sound/WbWaveFile.hpp
  src/webots/wren/WbWrenCamera.cpp
  src/webots/wren/WbWrenCamera.hpp
  tests/api/controllers/cache_checker/.gitignore
  tests/api/controllers/cache_checker/Makefile
  tests/api/controllers/cache_checker/cache_checker.c
  tests/api/protos/NestedProtoShapeWithMesh.proto
  tests/api/protos/NestedProtoShapeWithTexture.proto
  tests/api/protos/ProtoShapeWithMesh.proto
  tests/api/protos/ProtoShapeWithTexture.proto
  tests/api/worlds/cache.wbt
  tests/api/worlds/meshes/cube_0.05m.obj
  tests/api/worlds/meshes/cube_0.1m.obj
  tests/api/worlds/textures/green_texture.jpg
  tests/api/worlds/textures/red_texture.jpg
Labels: feature, test suite, test sources

#4348 Removed reference to deprecated example
  docs/guide/using-ros.md
Labels: documentation

#4349 Add support for negative scale on webotsjs
  resources/web/wwi/nodes/WbIndexedFaceSet.js
  resources/web/wwi/nodes/WbTriangleMeshGeometry.js
  resources/web/wwi/nodes/utils/WbTriangleMesh.js
  resources/web/wwi/wren/WbWrenShaders.js
  src/webots/nodes/WbTriangleMeshGeometry.cpp
Labels: enhancement

#4354 Consistent progress bar across themes
  resources/webots_dusk.qss
  resources/webots_night.qss
Labels: enhancement

#4357 Merge `released` into `master`
  docs/discord/development-2021.md
  docs/discord/development-2022.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/guide/running-extern-robot-controllers.md
  docs/guide/using-ros.md
  docs/tests/test_paragraphs.py
Labels: documentation, synchronization

#4360 Fix terminate docker-compose
  resources/web/server/config/simulation/docker/docker-compose-theia.yml
  resources/web/server/simulation_server.py
Labels: bug

#4358 Merge `master` into `develop`
  docs/discord/development-2021.md
  docs/discord/development-2022.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/guide/running-extern-robot-controllers.md
  docs/guide/using-ros.md
  docs/tests/test_paragraphs.py
  resources/webots_dusk.qss
  resources/webots_night.qss
  src/webots/nodes/utils/WbNodeOperations.cpp
Labels: test suite, test sources, synchronization

#4361 Fixed annoying warning
  src/controller/c/supervisor.c
Labels: cleanup, test sources

#4365 Improve the documentation of the CardboardBox proto.
  docs/guide/object-factory.md
  projects/objects/factory/containers/protos/CardboardBox.proto
Labels: documentation

#4373 Fix progress bar text alignment
  resources/webots_dusk.qss
  resources/webots_night.qss
Labels: cleanup

#4370 Fix stdin redirection
  src/webots/gui/main.cpp
Labels: cleanup, test suite

#4375 Fixed assimp renaming on Windows
  scripts/packaging/files_msys64.txt
Labels: bug, test distribution

#4372 Fixed stdout/stderr redirection when all Webots console are closed
  docs/reference/changelog-r2022.md
  src/webots/core/WbLog.cpp
  src/webots/core/WbLog.hpp
  src/webots/gui/WbConsole.cpp
  src/webots/gui/WbConsole.hpp
  src/webots/gui/WbGuiApplication.cpp
Labels: bug

#4366 fix get_field_by_index (#4363)
  docs/reference/changelog-r2022.md
  src/controller/c/supervisor.c
  tests/api/controllers/supervisor_field/supervisor_field.c
Labels: bug, test suite

#4377 Debug develop nightly test
  src/webots/nodes/WbImageTexture.cpp
  tests/test_suite.py
Labels: test suite, test sources

#4378 Feature theia webotsjs
  docs/guide/web-simulation.md
  resources/web/server/simulation_server.py
  resources/web/wwi/FloatingIde.js
  resources/web/wwi/FloatingRobotWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/Server.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/images/IDE.png
Labels: feature

#4383 Fix scheduled tests and nightly header
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
Labels: bug, test distribution, test suite

#4384 Fixed missing DLL in Windows distribution
  scripts/packaging/files_msys64.txt
Labels: bug

#4386 Add parameter name to pit
  projects/samples/robotbenchmark/pit_escape/protos/Pit.proto
Labels: enhancement

#4388 Fix loading of textures and contact properties when the fallback mechanism activates
  src/webots/nodes/WbContactProperties.cpp
  src/webots/nodes/WbImageTexture.cpp
Labels: bug, test suite, test sources

#4364 Allow multiple extra projects. Add WEBOTS_EXTRA_PROJECT_PATH env variable
  docs/guide/preferences.md
  docs/guide/samples-community-projects.md
  docs/reference/changelog-r2022.md
  resources/translations/wb_de.ts
  resources/translations/wb_es.ts
  resources/translations/wb_fr.ts
  resources/translations/wb_generic.ts
  resources/translations/wb_it.ts
  resources/translations/wb_ja_JP.ts
  resources/translations/wb_zh_CN.ts
  src/webots/core/WbControllerPlugin.cpp
  src/webots/core/WbProject.cpp
  src/webots/core/WbProject.hpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbPreferencesDialog.hpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbExtendedStringEditor.cpp
  src/webots/vrml/WbProtoList.cpp
Labels: test suite, test sources

#4350 Fix perspective save and camera overlays
  docs/guide/the-user-interface.md
  docs/reference/changelog-r2022.md
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/gui/WbSimulationView.cpp
  src/webots/wren/WbWrenTextureOverlay.cpp
Labels: bug, test suite, test sources

#4396 Merge `master` into `develop`
  docs/guide/the-user-interface.md
  docs/reference/changelog-r2022.md
  docs/reference/supervisor.md
  projects/default/controllers/ros/RosSupervisor.cpp
  projects/default/controllers/ros/RosSupervisor.hpp
  projects/default/controllers/ros/headersGenerator.py
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/gui/WbSimulationView.cpp
  src/webots/wren/WbWrenTextureOverlay.cpp
Labels: test suite, test sources, test ros, synchronization

#4393 Better asset archive name and cache bugfixes
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  docs/guide/installation-procedure.md
  scripts/get_git_info/get_git_info.sh
  scripts/packaging/generate_asset_cache.py
  src/webots/nodes/WbContactProperties.cpp
Labels: enhancement, test world update, test sources

#4400 Add instructions about minimum cache size for assets
  docs/guide/installation-procedure.md
Labels: documentation

#4402 Fix crash when adding animatedGeometries when no trackwheels are there
  src/webots/nodes/WbTrack.cpp
Labels: bug, crash

#4404 Change theia mention to IDE
  resources/web/server/simulation_server.py
  resources/web/wwi/Server.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/webots.js
Labels: cleanup

#4408 Cleanup Doc of connect()
  docs/guide/web-simulation.md
Labels: cleanup

#4410 Do not create IDE button when IDE is not present
  docs/guide/web-simulation.md
  resources/web/wwi/Toolbar.js
Labels: cleanup

#4394 Add support for track animation in WebotsJS
  docs/reference/changelog-r2022.md
  resources/nodes/TrackWheel.wrl
  resources/web/wwi/Animation.js
  resources/web/wwi/Parser.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/dependencies/quaternion.min.js
  resources/web/wwi/nodes/WbImageTexture.js
  resources/web/wwi/nodes/WbPBRAppearance.js
  resources/web/wwi/nodes/WbTrack.js
  resources/web/wwi/nodes/WbTrackWheel.js
  resources/web/wwi/nodes/WbWorld.js
  resources/web/wwi/nodes/utils/WbBeltPosition.js
  resources/web/wwi/nodes/utils/WbPathSegment.js
  resources/web/wwi/nodes/utils/WbVector4.js
  resources/web/wwi/viewer.js
  src/webots/maths/WbVector2.hpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbPropeller.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbTrack.cpp
  src/webots/nodes/WbTrack.hpp
  src/webots/nodes/WbTrackWheel.cpp
  src/webots/nodes/WbTrackWheel.hpp
Labels: enhancement
