Repository cyberbotics/webots, pull requests merged in 2022-07, with the labels that each got.

#4795 Fix crash in triangle mesh cache
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbTriangleMeshGeometry.cpp
  src/webots/nodes/WbTriangleMeshGeometry.hpp
  src/webots/nodes/utils/WbTriangleMesh.cpp
  src/webots/nodes/utils/WbTriangleMeshCache.cpp
Labels: crash, test suite

#4810 Fixed make clean(se) for proto-list.xml
  Makefile
Labels: cleanup

#4812 Fix sumo contents path
  docs/automobile/images/osm_tutorial_import2.thumbnail.jpg
  docs/automobile/openstreetmap-importer.md
  docs/automobile/scenario-creation-tutorial.md
  docs/automobile/sumo-exporter.md
  projects/default/controllers/sumo_supervisor/sumo_supervisor.py
  projects/vehicles/importer_demo.sh
Labels: bug, documentation

#4776 Hotfix applying PROTO changes on reload
  scripts/packaging/update_urls.py
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
  tests/cache/cache_environment.py
  tests/cache/controllers/generic_checker/generic_checker.c
  tests/cache/controllers/proto_retrieval_and_import/proto_retrieval_and_import.c
  tests/cache/protos/ShapeWithFixedWebTexture.proto
  tests/cache/protos/ShapeWithLocalCyanTexture.proto
  tests/cache/protos/ShapeWithLocalOrangeTexture.proto
  tests/cache/protos/ShapeWithLocalPinkTexture.proto
  tests/cache/protos/textures/cyan_texture.jpg
  tests/cache/protos/textures/orange_texture.jpg
  tests/cache/protos/textures/pink_texture.jpg
  tests/cache/worlds/absolute_proto_with_texture.wbt
  tests/cache/worlds/backwards_compatibility.wbt
  tests/cache/worlds/basenode_with_texture.wbt
  tests/cache/worlds/cache.wbt
  tests/cache/worlds/local_proto_with_texture.wbt
  tests/cache/worlds/proto_retrieval_and_import.wbt
  tests/cache/worlds/relative_proto_with_texture.wbt
  tests/cache/worlds/web_proto_with_texture.wbt
  tests/lib/ts_utils.h
  tests/test_suite.py
Labels: bug, test distribution, test suite

#4819 Fix webots.cloud default URL
  src/webots/core/WbPreferences.cpp
Labels: upgrade

#4822 Fix clarify robot windows URLs with WEBOTS_HOME
  resources/web/wwi/RobotWindow.js
  src/webots/gui/WbRobotWindow.cpp
  src/webots/gui/WbTcpServer.cpp
Labels: enhancement

#4825 Update remaining urls to R2022b
  docs/guide/generate_objects_doc.py
  resources/osm_importer/config.ini
  resources/osm_importer/elevation.py
  resources/osm_importer/utils/misc_utils.py
  resources/osm_importer/webots_objects/barrier.py
  resources/osm_importer/webots_objects/road.py
  scripts/new_version/new_version.sh
Labels: cleanup

#4826 Improve field editor visibility
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/scene_tree/WbSceneTree.hpp
Labels: enhancement

#4827 Fix snap warnings
  scripts/packaging/linux_distro.py
Labels: cleanup

#4828 Fixed font in ephemeral proto warning
  src/webots/scene_tree/WbExternProtoEditor.cpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
Labels: bug

#4770 Feature edit extern PROTO source
  src/webots/core/WbAction.hpp
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/editor/WbProjectRelocationDialog.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbExtendedStringEditor.hpp
  src/webots/scene_tree/WbFieldEditor.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/scene_tree/WbSceneTree.hpp
  src/webots/user_commands/WbActionManager.cpp
  src/webots/user_commands/WbContextMenuGenerator.cpp
  src/webots/user_commands/WbContextMenuGenerator.hpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: enhancement

#4792 Enhancements for local proto behavior
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  resources/osm_importer/importer.py
  resources/osm_importer/utils/misc_utils.py
  src/webots/app/WbApplication.cpp
  src/webots/gui/WbNewProtoWizard.cpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbAddNodeDialog.hpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
  src/webots/vrml/WbProtoTreeItem.cpp
  src/webots/vrml/WbProtoTreeItem.hpp
Labels: enhancement, test suite, test sources

#4809 Fix invalid proto url retrieval
  src/webots/vrml/WbProtoTreeItem.cpp
  src/webots/vrml/WbProtoTreeItem.hpp
Labels: bug, test suite

#4837 Fixed parsing of commented out EXTERNPROTOs
  src/webots/vrml/WbProtoTreeItem.cpp
Labels: bug

#4838 Restore windows nightly
  .github/workflows/test_suite_windows.yml
Labels: cleanup

#4839 Fix workflow
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_windows.yml
Labels: bug

#4834 Fix darwin-op robot window
  resources/Makefile.include
Labels: bug

#4842 Fixed MATLAB on macOS
  lib/controller/matlab/launcher.m
Labels: bug

#4843 Fix broken url
  resources/web/wwi/viewer.js
Labels: bug

#4841 Add EXTERNPROTO to changelog
  docs/reference/changelog-r2022.md
  src/webots/vrml/WbProtoManager.cpp
Labels: documentation, test sources

#4845 Fix rolling_friction urls
  projects/samples/howto/rolling_friction/worlds/rolling_friction.wbt
Labels: bug

#4851 Fix open controller in text editor
  src/webots/scene_tree/WbExtendedStringEditor.cpp
Labels: bug, test suite

#4853 Forgotten R2022a references
  docs/guide/installation-procedure.md
  docs/guide/setup-a-webots-project-repository.md
  docs/reference/proto-design-guidelines.md
Labels: documentation

#4846 Fix guided tour crash in auto mode
  src/webots/gui/WbGuidedTour.cpp
  src/webots/gui/WbGuidedTour.hpp
  src/webots/gui/WbMainWindow.cpp
Labels: crash

#4854 Fix web component studio
  docs/guide/scenes/crazyflie/crazyflie.x3d
  docs/guide/scenes/surveyor/surveyor.x3d
  docs/guide/scenes/tiago-base/tiago-base.x3d
  docs/guide/scenes/tiago-iron/tiago-iron.x3d
  docs/guide/scenes/tiago-steel/tiago-steel.x3d
  docs/guide/scenes/tiago-titanium/tiago-titanium.x3d
  docs/guide/scenes/tiagopp/tiagopp.x3d
  scripts/web_component_studio/web_component_studio.py
  scripts/web_component_studio/worlds/web_component_studio_template.wbt
Labels: bug

#4857 Better fix for darwin-op robot window
  resources/Makefile.include
  scripts/packaging/mac_distro.py
Labels: enhancement

#4745 Add blog post
  docs/blog/Webots-2022-b-release.md
  docs/blog/images/appearances_r2022b.png
  docs/blog/images/assets_r2022b.png
  docs/blog/images/cadshape_r2022b.png
  docs/blog/images/robots_r2022b.png
  docs/blog/menu.md
  docs/reference/changelog-r2022.md
Labels: documentation

#4856 Fix world warnings
  projects/samples/howto/Makefile
  projects/samples/howto/url/worlds/url.wbt
Labels: bug

#4861 Correct typo in Makefile
  projects/samples/howto/Makefile
Labels: bug, test suite

#4862 Add changelog for 2023
  docs/reference/changelog-r2023.md
  docs/reference/menu.md
Labels: documentation

#4866 Fix controllers directory in project relocation
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/nodes/WbRobot.hpp
Labels: bug

#4867 Update FUNDING.yml
  .github/FUNDING.yml
Labels: cleanup

#4870 Reset webotsjs session timeout on close
  resources/web/wwi/Server.js
Labels: bug

#4737 Add new workflow `test webots build` label
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  Makefile
Labels: test webots build

#4871 add .yaml extension
  resources/web/server/simulation_server.py
Labels: bug

#4873 Update webots-cloud.md
  docs/guide/webots-cloud.md
Labels: documentation

#4874 Fix web stream wrong tmp file path
  resources/web/server/simulation_server.py
Labels: bug

#4876 Update discord docs. (#4859)
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
Labels: synchronization

#4877 Merge master in develop
  .github/FUNDING.yml
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  Makefile
  docs/blog/Webots-2022-b-release.md
  docs/blog/images/appearances_r2022b.png
  docs/blog/images/assets_r2022b.png
  docs/blog/images/cadshape_r2022b.png
  docs/blog/images/robots_r2022b.png
  docs/blog/menu.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/guide/webots-cloud.md
  docs/reference/changelog-r2022.md
  projects/samples/howto/Makefile
  projects/samples/howto/url/worlds/url.wbt
  resources/web/server/simulation_server.py
  resources/web/wwi/Server.js
  scripts/converter/declare_externproto.py
  scripts/packaging/mac_distro.py
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/nodes/WbRobot.hpp
Labels: test suite, synchronization

#4878 Fix invalid retrieve of non-top ancestor Robot
  docs/reference/changelog-r2022.md
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbRenderingDeviceWindow.cpp
  src/webots/nodes/WbSpeaker.cpp
Labels: crash, test suite

#4880 Fix clang-format error
  .github/workflows/tests_sources.yml
  scripts/converter/declare_externproto.py
Labels: test sources

#4883 Fix case of PROTO
  src/webots/gui/WbMainWindow.cpp
Labels: enhancement

#4879 Update webots-cloud.md
  docs/guide/webots-cloud.md
Labels: documentation

#4888 Update get_bearing_in_degrees to ENU
  docs/reference/compass.md
Labels: documentation

#4885 Fix recompilation of controllers before creating packages
  scripts/packaging/Makefile
  scripts/packaging/Makefile.controllers
  scripts/packaging/webots_distro.py
Labels: bug, test distribution

#4892 Fix updating the selection from the scene tree
  src/webots/nodes/utils/WbNodeOperations.cpp
Labels: bug

#4889 Fix editing cached PROTO sources
  src/webots/editor/WbTextBuffer.cpp
Labels: bug, test webots build

#4893 Fix early WbExternProtoEditor update
  src/webots/gui/WbMainWindow.cpp
  src/webots/scene_tree/WbExternProtoEditor.cpp
  src/webots/scene_tree/WbFieldEditor.cpp
  src/webots/scene_tree/WbFieldEditor.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/scene_tree/WbSceneTree.hpp
Labels: enhancement, test webots build

#4896 Fix Ephemeral EXTERNPROTO editor layout
  src/webots/scene_tree/WbExternProtoEditor.cpp
Labels: bug

#4901 Merge released in Master
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/reference/compass.md
Labels: synchronization

#4900 Fix missing interface informations in PROTOs
  scripts/packaging/generate_proto_list.py
  src/webots/vrml/WbProtoManager.hpp
Labels: bug

#4902 Merge master in develop
  .github/workflows/tests_sources.yml
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/guide/webots-cloud.md
  docs/reference/changelog-r2022.md
  docs/reference/compass.md
  projects/objects/buildings/protos/MotelReception.proto
  scripts/converter/declare_externproto.py
  scripts/packaging/Makefile
  scripts/packaging/Makefile.controllers
  scripts/packaging/webots_distro.py
  src/webots/editor/WbTextBuffer.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbRenderingDeviceWindow.cpp
  src/webots/nodes/WbSpeaker.cpp
  src/webots/scene_tree/WbExternProtoEditor.cpp
Labels: test suite, synchronization

#4903 Improve robustness
  src/webots/core/WbProject.cpp
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbNewProjectWizard.cpp
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbCadShape.hpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/nodes/utils/WbUrl.hpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoModel.cpp
  src/webots/vrml/WbProtoTreeItem.cpp
  src/webots/vrml/WbProtoTreeItem.hpp
  src/webots/vrml/WbTokenizer.cpp
Labels: cleanup, test sources

#4904 Break if yaml file found
  resources/web/server/simulation_server.py
Labels: cleanup

#4898 Use generic controller in PROTO wizard and favor relative urls rather absolute when editing a proto
  scripts/packaging/generate_proto_list.py
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbNewProtoWizard.cpp
  src/webots/vrml/WbParser.cpp
Labels: bug

#4895 Fix ephemeral related issues
  src/webots/app/WbApplication.cpp
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeOperations.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbExternProtoEditor.cpp
  src/webots/scene_tree/WbExternProtoEditor.hpp
  src/webots/scene_tree/WbFieldEditor.cpp
  src/webots/scene_tree/WbFieldEditor.hpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/scene_tree/WbSceneTree.hpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: bug, test sources

#4897 Fix convert root to basenode
  src/webots/sound/WbContactSound.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
  src/webots/vrml/WbProtoManager.cpp
Labels: bug, test suite

#4916 Add distinction between normal EXTERNPROTO and IMPORTABLE ones
  docs/blog/Webots-2022-b-release.md
  docs/blog/images/appearances_r2022b.thumbnail.jpg
  docs/blog/images/assets_r2022b.thumbnail.jpg
  docs/blog/images/cadshape_r2022b.thumbnail.jpg
  docs/blog/images/robots_r2022b.thumbnail.jpg
  docs/guide/images/ephemeral_externproto.png
  docs/guide/images/importable_externproto.png
  docs/guide/images/scene_tree.png
  docs/guide/images/scene_tree.thumbnail.jpg
  docs/guide/the-scene-tree.md
  docs/reference/supervisor.md
  projects/humans/c3d/worlds/c3d_viewer.wbt
  projects/samples/robotbenchmark/highway_driving/worlds/highway_driving.wbt
  projects/vehicles/worlds/city_traffic.wbt
  projects/vehicles/worlds/highway.wbt
  projects/vehicles/worlds/highway_overtake.wbt
  projects/vehicles/worlds/sumo_interface_example.wbt
  projects/vehicles/worlds/village_center.wbt
  resources/webots_dusk.qss
  resources/webots_night.qss
  scripts/icon_studio/worlds/icon_studio.wbt
  src/webots/app/WbApplication.cpp
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbExternProtoEditor.cpp
  src/webots/scene_tree/WbExternProtoEditor.hpp
  src/webots/scene_tree/WbFieldEditor.cpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNodeReader.cpp
  src/webots/vrml/WbParser.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
  src/webots/vrml/WbProtoModel.cpp
  src/webots/vrml/WbProtoTreeItem.cpp
  src/webots/vrml/WbProtoTreeItem.hpp
  src/webots/vrml/WbToken.cpp
  tests/api/worlds/supervisor_field_import_mf_node.wbt
  tests/cache/worlds/proto_retrieval_and_import.wbt
  tests/protos/worlds/proto_import.wbt
  tests/protos/worlds/super_parameter_instances.wbt
Labels: test suite, test sources

#4913 Disable application edit actions for read-only text files
  src/webots/editor/WbTextBuffer.cpp
  src/webots/editor/WbTextEditor.cpp
  src/webots/gui/WbConsole.cpp
  src/webots/gui/WbView3D.cpp
  src/webots/scene_tree/WbTreeView.cpp
  src/webots/user_commands/WbActionManager.cpp
  src/webots/user_commands/WbActionManager.hpp
Labels: bug, test webots build

#4923 Fixed execution of homebrew python controllers on x86_64
  docs/guide/using-python.md
  src/controller/python/.gitignore
  src/controller/python/Makefile
  src/webots/control/WbController.cpp
Labels: bug

#4928 Merge released in master
  docs/discord/development-2022.md
  docs/discord/documentation.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
Labels: synchronization

#4929 Merge master in develop
  docs/discord/development-2022.md
  docs/discord/documentation.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/guide/setup-a-webots-project-repository.md
  docs/guide/using-python.md
  docs/guide/webots-cloud.md
  resources/web/server/simulation_server.py
  src/controller/python/.gitignore
  src/controller/python/Makefile
  src/webots/control/WbController.cpp
  src/webots/editor/WbTextBuffer.cpp
  src/webots/editor/WbTextEditor.cpp
  src/webots/gui/WbConsole.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbView3D.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/scene_tree/WbTreeView.cpp
  src/webots/user_commands/WbActionManager.cpp
  src/webots/user_commands/WbActionManager.hpp
Labels: test suite, synchronization

#4930 Favor relative urls when saving EXTERNPROTO declarations to file
  src/webots/gui/WbMainWindow.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: cleanup

#4926 Update SoundEngine's viewpoint after regeneration
  src/webots/sound/WbSoundEngine.cpp
  src/webots/sound/WbSoundEngine.hpp
Labels: bug, test suite, test sources

#4907 Update "Transform to" rules
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbNodeUtilities.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/user_commands/WbClipboard.cpp
  src/webots/user_commands/WbClipboard.hpp
  src/webots/user_commands/WbContextMenuGenerator.cpp
Labels: enhancement, test suite

#4934 Expose robot window of simple vehicles
  docs/automobile/ackermannvehicle.md
  docs/automobile/car.md
  projects/vehicles/protos/bmw/BmwX5Simple.proto
  projects/vehicles/protos/citroen/CitroenCZeroSimple.proto
  projects/vehicles/protos/generic/BusSimple.proto
  projects/vehicles/protos/generic/TruckSimple.proto
  projects/vehicles/protos/lincoln/LincolnMKZSimple.proto
  projects/vehicles/protos/mercedes_benz/MercedesBenzSprinterSimple.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVRSimple.proto
  projects/vehicles/protos/tesla/TeslaModel3Simple.proto
  projects/vehicles/protos/toyota/ToyotaPriusSimple.proto
Labels: enhancement

#4937 Fix `generate_objects_doc.py`
  docs/guide/generate_objects_doc.py
Labels: bug

#4918 Update README.md
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  README.md
  docs/guide/images/main_window.png
  docs/guide/images/main_window.thumbnail.jpg
Labels: enhancement

#4935 Remove useless DLLs in the Windows package
  scripts/packaging/files_msys64.txt
Labels: bug, cleanup, test webots build

#4940 Improve graphics of ipr collaboration world
  projects/robots/neuronics/ipr/worlds/ipr_collaboration.wbt
Labels: enhancement

#4920 Improve error messages for worlds and protos prior to R2022b
  src/webots/gui/WbMainWindow.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: bug

#4941 Clear old cache folder
  src/webots/core/WbNetwork.cpp
Labels: cleanup

#4908 Improve tests: restart Webots after each "cache" test
  src/webots/core/WbStandardPaths.cpp
  tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py
  tests/test_suite.py
Labels: test suite issue, test suite

#4943 Fix c3d controller
  projects/humans/c3d/controllers/c3d_viewer/c3d.py
Labels: bug, test sources

#4948 Add appearance IMPORTABLE EXTERNPROTO to icon_studio
  scripts/icon_studio/worlds/icon_studio.wbt
Labels: enhancement

#4958 Fix declare extern protos script on macs
  scripts/converter/declare_externproto.py
Labels: bug

#4947 Debug world-update cache difference
  .github/workflows/test_suite_linux.yml
Labels: cleanup

#4957 Fix infinite loop when searching for 'protos' parent folder
  src/webots/vrml/WbProtoModel.cpp
Labels: crash, test webots build

#4970 Fix project relocation of `skin_animated_humans`
  projects/humans/skin_animated_humans/motions/README.md
  projects/humans/skin_animated_humans/motions/jump.bvh
  projects/humans/skin_animated_humans/motions/run.bvh
  projects/humans/skin_animated_humans/motions/step_down.bvh
  projects/humans/skin_animated_humans/motions/step_up.bvh
  projects/humans/skin_animated_humans/motions/walk.bvh
  projects/humans/skin_animated_humans/worlds/skin_animated_humans.wbt
Labels: bug

#4971 Fixed e-puck robot window
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.c
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.js
Labels: cleanup

#4951 Fixed relocation of textures used by controllers
  projects/robots/irobot/create/controllers/ground/dust.jpg
  projects/robots/irobot/create/controllers/ground/ground.c
  projects/robots/irobot/create/worlds/create.wbt
  projects/samples/geometries/controllers/water_flow_animation/water_flow.jpg
  projects/samples/geometries/controllers/water_flow_animation/water_flow_animation.c
  projects/samples/geometries/worlds/floating_geometries.wbt
  scripts/packaging/generic_distro.py
  scripts/packaging/textures_whitelist.txt
Labels: bug

#4969 Fixed ignored recurse and omitted files and folders
  scripts/packaging/generate_projects_files.py
  scripts/packaging/generic_distro.py
Labels: bug

#4975 Fix typo in webotsjs timer
  resources/web/wwi/Parser.js
  resources/web/wwi/WebotsView.js
Labels: bug

#4979 Fixes robot window in PROTOs of robots
  docs/guide/firebird6.md
  projects/robots/Makefile
  projects/robots/nex/plugins/remote_controls/Makefile
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Communication.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Communication.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Device.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Device.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/DeviceManager.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/DeviceManager.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/FB6_AllSensorCommandesponse.txt
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/FireBird6InputPacket.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/FireBird6InputPacket.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/FireBird6OutputPacket.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/FireBird6OutputPacket.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Makefile
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Motor.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Packet.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Packet.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Sensor.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Serial.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Serial.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/SingleValueSensor.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Time.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Time.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/TripleValuesSensor.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Wrapper.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/Wrapper.hpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/entry_points.cpp
  projects/robots/nex/plugins/remote_controls/fire_bird_6_remote_control/entry_points.hpp
  projects/robots/nex/plugins/robot_windows/Makefile
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/AccelerometerGroupBox.cpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/AccelerometerGroupBox.hpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/EncoderGroupBox.cpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/EncoderGroupBox.hpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/FireBird6Representation.cpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/FireBird6Representation.hpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/Gui.cpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/Gui.hpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/GyroGroupBox.cpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/GyroGroupBox.hpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/MagnetometerGroupBox.cpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/MagnetometerGroupBox.hpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/MainWidget.cpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/MainWidget.hpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/Makefile
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/RemoteControlWidget.cpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/RemoteControlWidget.hpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/entry_points.cpp
  projects/robots/nex/plugins/robot_windows/fire_bird_6_window/entry_points.hpp
  projects/robots/nex/protos/FireBird6.proto
  projects/robots/nex/worlds/.fire_bird_6_remote_control.wbproj
  projects/robots/nex/worlds/fire_bird_6_remote_control.wbt
  projects/robots/nvidia/jetbot/protos/JetBot.proto
  projects/robots/robotis/bioloid/protos/BioloidDog.proto
Labels: bug, cleanup

#4972 Fixed display of ground sensors in e-puck robot window
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.c
  projects/robots/gctronic/e-puck/plugins/robot_windows/e-puck/e-puck.js
Labels: bug

#4980 Update web-simulation.md
  docs/guide/web-simulation.md
Labels: documentation

#4982 Enforce UTF-8 encoding for Python IO
  scripts/install/bash_profile.windows
Labels: bug

#4983 Merge released in master
  docs/discord/development-2022.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2022.md
Labels: synchronization

#4974 Fix impossible relocation of controllers outside of local project in distributions
  src/webots/editor/WbProjectRelocationDialog.cpp
Labels: bug

#4986 Fix mime type for models
  src/webots/core/WbHttpReply.cpp
Labels: bug

#4973 Fix handling tokenizer errors
  src/webots/app/WbApplication.cpp
Labels: crash, test suite

#4956 Show warning if file to be exported exists already
  src/webots/Makefile
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: bug, test sources, test webots build

#4984 Remove server
  docs/guide/prerequisites-and-overview.md
  docs/guide/protocol-and-quick-start.md
  docs/guide/session-server.md
  docs/guide/simulation-server.md
  resources/web/server/.gitignore
  resources/web/server/async_process.py
  resources/web/server/config/session/local.json
  resources/web/server/config/simulation/cyberbotics1.json
  resources/web/server/config/simulation/cyberbotics2.json
  resources/web/server/config/simulation/docker/Dockerfile.default
  resources/web/server/config/simulation/docker/docker-compose-default.yml
  resources/web/server/config/simulation/docker/docker-compose-theia.yml
  resources/web/server/config/simulation/local.json
  resources/web/server/config/simulation/video.json
  resources/web/server/kill_old_webots_instances.py
  resources/web/server/log/session/.gitignore
  resources/web/server/log/simulation/.gitignore
  resources/web/server/server.sh
  resources/web/server/session_server.py
  resources/web/server/simulation_server.py
  scripts/packaging/files_core.txt
Labels: enhancement, cleanup, test webots build

#4987 Fixed generated proto temporary filename
  src/webots/core/WbLanguage.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
Labels: enhancement
