Repository cyberbotics/webots, pull requests merged in 2022-09, with the labels that each got.

#5158 Add space to empty.wbt
  resources/projects/worlds/empty.wbt
Labels: cleanup

#5160 Add missing documentation link in Mavic2Pro PROTO
  projects/robots/dji/mavic/protos/Mavic2Pro.proto
Labels: enhancement

#5157 Fix alias not propagating in derived proto and empty add-node
  docs/reference/changelog-r2022.md
  src/webots/vrml/WbNode.cpp
Labels: bug, test suite, test sources, test worlds

#5159 Restore lost declaration after cut-paste
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: bug, test sources

#5162 Fix noise mask on distrib
  src/webots/nodes/WbCamera.cpp
  src/webots/wren/WbWrenCamera.cpp
Labels: bug, test sources

#5167 Update Webots-2022-b-release.md
  docs/blog/Webots-2022-b-release.md
Labels: bug

#5169 Fix issues between relative URL and PROTO wizard
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbNewProtoWizard.cpp
  src/webots/gui/WbNewProtoWizard.hpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/nodes/utils/WbUrl.hpp
Labels: bug, test suite, test sources

#5170 Add missing declaration in osm_importer
  resources/osm_importer/utils/misc_utils.py
Labels: bug

#5171 Added scale update in animations
  resources/web/wwi/X3dScene.js
Labels: enhancement

#5149 Enhancement viewpoint standard views
  docs/guide/images/context_menu.png
  docs/guide/images/scene_tree.png
  docs/guide/the-user-interface.md
  docs/reference/changelog-r2022.md
  src/webots/core/WbAction.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbSimulationView.cpp
  src/webots/gui/WbView3D.cpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/nodes/WbViewpoint.hpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbNodeUtilities.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/scene_tree/WbSceneTree.hpp
  src/webots/user_commands/WbActionManager.cpp
  src/webots/user_commands/WbContextMenuGenerator.cpp
Labels: enhancement, test webots build

#5175 Fix convert root to basenode and other conversion issues
  src/webots/control/WbControlledWorld.hpp
  src/webots/control/WbController.cpp
  src/webots/core/WbFileUtil.cpp
  src/webots/core/WbFileUtil.hpp
  src/webots/core/WbProject.cpp
  src/webots/core/WbVersion.hpp
  src/webots/editor/WbFindReplaceDialog.cpp
  src/webots/engine/WbSimulationWorld.hpp
  src/webots/gui/WbRobotWindow.cpp
  src/webots/nodes/WbHingeJointParameters.hpp
  src/webots/nodes/utils/WbJoystickInterface.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/nodes/utils/WbWorld.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoModel.cpp
  src/wren/Debug.hpp
  src/wren/Material.cpp
  src/wren/Material.hpp
  src/wren/PostProcessingEffect.cpp
  src/wren/Primitive.hpp
  src/wren/ShaderProgram.cpp
Labels: bug, test sources

#5177 Fixed compilation failure
  src/webots/editor/WbFindReplaceDialog.cpp
Labels: bug, test sources

#5184 Show warning if the file to be edited isn't cached
  src/webots/gui/WbMainWindow.cpp
Labels: cleanup

#5182 Upload the meshes folder to webots.cloud in case of animation/scene
  src/webots/gui/WbMainWindow.cpp
Labels: bug

#5179 Fix project relocation dialog layout
  src/webots/editor/WbProjectRelocationDialog.cpp
Labels: bug

#5191 Fix copy of binary controllers
  resources/Makefile.include
  src/webots/app/WbApplication.cpp
  src/webots/editor/WbBuildEditor.cpp
  src/webots/editor/WbProjectRelocationDialog.cpp
Labels: bug, enhancement, test sources

#5185 Fix `CadShape` animations
  resources/web/wwi/nodes/WbCadShape.js
  src/webots/nodes/WbBackground.cpp
Labels: bug

#5193 Fix field editor size update
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbExternProtoEditor.cpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: bug, test webots build

#5196 Fix UNDO crash
  src/webots/user_commands/WbUndoStack.cpp
Labels: bug, test sources

#4882 Update dates
  docs/blog/Webots-2022-b-release.md
  docs/blog/index.md
  docs/reference/changelog-r2022.md
Labels: documentation, cleanup

#5200 Improve `complete_apartment.wbt` title
  docs/guide/webots-cloud.md
  projects/samples/environments/indoor/worlds/complete_apartment.wbt
Labels: documentation

#5201 Fix robot window camera layout
  resources/projects/plugins/robot_windows/generic/generic.css
Labels: cleanup

#5203 Specify the default value of notify and shareIdleTime
  docs/guide/simulation-server.md
Labels: documentation

#5206 Fix incorrect insertion in IMPORTABLE EXTERNPROTO list
  src/webots/scene_tree/WbAddNodeDialog.cpp
Labels: bug

#5208 Fix upload of resources that have a space in their name
  src/webots/gui/WbMainWindow.cpp
Labels: bug

#5205 Improve web documentation
  docs/guide/advanced-configuration.md
  docs/guide/images/web_interface_ide.png
  docs/guide/protocol-and-quick-start.md
  docs/guide/session-server.md
  docs/guide/setup-a-webots-project-repository.md
  docs/guide/simulation-server.md
  docs/guide/web-animation.md
  docs/guide/web-scene.md
  docs/guide/web-streaming.md
  docs/guide/webots-cloud.md
Labels: documentation

#5210 Fix wrong web URL in error message
  src/webots/vrml/WbProtoManager.cpp
Labels: bug, test webots build

#5211 Add actions to show field editor
  docs/guide/images/context_menu.png
  docs/guide/images/scene_tree.png
  docs/reference/changelog-r2022.md
  resources/icons/dark/edit_field_button.png
  resources/icons/light/edit_field_button.png
  src/webots/core/WbAction.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/scene_tree/WbSceneTree.hpp
  src/webots/user_commands/WbActionManager.cpp
  src/webots/user_commands/WbContextMenuGenerator.cpp
Labels: enhancement, test webots build

#5212 Doc fix webots.cloud link
  docs/blog/Webots-2022-b-release.md
  docs/guide/webots-cloud.md
Labels: documentation

#5216 Update docker name
  docs/guide/advanced-configuration.md
  docs/guide/setup-a-webots-project-repository.md
  docs/guide/simulation-server.md
  docs/guide/webots-cloud.md
Labels: documentation

#5204 Add animals PROTO to R2022b
  projects/objects/animals/protos/Cat.proto
  projects/objects/animals/protos/Cow.proto
  projects/objects/animals/protos/Deer.proto
  projects/objects/animals/protos/Dog.proto
  projects/objects/animals/protos/Fox.proto
  projects/objects/animals/protos/Horse.proto
  projects/objects/animals/protos/Rabbit.proto
  projects/objects/animals/protos/Sheep.proto
  projects/objects/animals/protos/cat/meshes/cat.obj
  projects/objects/animals/protos/cat/textures/cat_basecolor.jpg
  projects/objects/animals/protos/cow/meshes/cow.obj
  projects/objects/animals/protos/cow/textures/cow_basecolor.jpg
  projects/objects/animals/protos/cow/textures/cow_basecolor_black.jpg
  projects/objects/animals/protos/cow/textures/cow_normal.jpg
  projects/objects/animals/protos/cow/textures/cow_roughness.jpg
  projects/objects/animals/protos/deer/meshes/deer.obj
  projects/objects/animals/protos/deer/textures/deer_basecolor.jpg
  projects/objects/animals/protos/deer/textures/deer_normal.jpg
  projects/objects/animals/protos/dog/meshes/dog.obj
  projects/objects/animals/protos/dog/textures/dog_basecolor.jpg
  projects/objects/animals/protos/fox/meshes/fox.obj
  projects/objects/animals/protos/fox/textures/fox_basecolor.jpg
  projects/objects/animals/protos/fox/textures/fox_normal.jpg
  projects/objects/animals/protos/fox/textures/fox_occlusion.jpg
  projects/objects/animals/protos/horse/meshes/horse.obj
  projects/objects/animals/protos/horse/meshes/horse_hair.obj
  projects/objects/animals/protos/horse/textures/horse_basecolor.jpg
  projects/objects/animals/protos/horse/textures/horse_hair_basecolor.png
  projects/objects/animals/protos/horse/textures/horse_occlusion.jpg
  projects/objects/animals/protos/horse/textures/horse_roughness.jpg
  projects/objects/animals/protos/icons/Cat.png
  projects/objects/animals/protos/icons/Cow.png
  projects/objects/animals/protos/icons/Deer.png
  projects/objects/animals/protos/icons/Dog.png
  projects/objects/animals/protos/icons/Fox.png
  projects/objects/animals/protos/icons/Horse.png
  projects/objects/animals/protos/icons/Rabbit.png
  projects/objects/animals/protos/icons/Sheep.png
  projects/objects/animals/protos/rabbit/meshes/rabbit.obj
  projects/objects/animals/protos/rabbit/textures/rabbit_basecolor.jpg
  projects/objects/animals/protos/rabbit/textures/rabbit_normal.jpg
  projects/objects/animals/protos/rabbit/textures/rabbit_roughness.png
  projects/objects/animals/protos/sheep/meshes/sheep.obj
  projects/objects/animals/protos/sheep/textures/sheep_basecolor.jpg
  projects/objects/animals/protos/sheep/textures/sheep_normal.jpg
  projects/objects/buildings/protos/Barn.proto
  projects/objects/buildings/protos/icons/Barn.png
  projects/objects/buildings/protos/meshes/barn.obj
  projects/objects/buildings/protos/textures/barn_basecolor.png
Labels: enhancement

#5221 Fixed OpenJDK installation on Windows
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
Labels: bug, test sources

#5220 Fix .deb and .dmg package creation
  scripts/packaging/generate_asset_cache.py
  scripts/packaging/generic_distro.py
  scripts/packaging/webots_distro.py
Labels: bug

#5226 add thumbnail as parameter for animation
  docs/guide/web-animation.md
Labels: documentation

#5224 Fix lidar rotating head export to x3d
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/WbLidar.hpp
Labels: bug, test suite

#5230 Update changelog-r2022.md
  docs/reference/changelog-r2022.md
Labels: documentation

#5232 Correct declare.py
  scripts/converter/declare_externproto.py
Labels: bug

#5234 Improve InertialUnit documentation
  docs/reference/inertialunit.md
Labels: documentation

#5233 Update WbLidar.cpp style
  src/webots/nodes/WbLidar.cpp
Labels: cleanup

#5231 fix WbLightSensor: collect behavior of recieving light of SpotLight
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbLightSensor.cpp
Labels: bug

#5238 Merge released in master
  docs/guide/advanced-configuration.md
  docs/guide/setup-a-webots-project-repository.md
  docs/guide/simulation-server.md
  docs/guide/web-animation.md
  docs/guide/webots-cloud.md
  docs/reference/inertialunit.md
Labels: synchronization

#5229 simulation-server doc correction
  docs/guide/simulation-server.md
Labels: documentation

#5236 Fix labels reset
  resources/web/wwi/Animation.js
  resources/web/wwi/webots.js
Labels: bug

#5242 Update deprecated option in icon_creator.py
  scripts/icon_studio/controllers/icon_creator/icon_creator.py
Labels: enhancement

#5244 Make conversion script more robust
  scripts/converter/declare_externproto.py
Labels: bug

#5239 GPS: Remove wrong const attribute
  docs/reference/gps.md
  include/controller/c/webots/gps.h
  include/controller/cpp/webots/GPS.hpp
  src/controller/c/gps.c
  src/controller/cpp/GPS.cpp
Labels: cleanup

#5237 Fix webotsJS follow viewpoint
  docs/reference/changelog-r2022.md
  resources/web/wwi/nodes/WbViewpoint.js
Labels: bug

#5245 Allow progress text to be on two lines
  resources/web/wwi/css/progress.css
Labels: enhancement

#5246 Merge master in develop
  docs/guide/advanced-configuration.md
  docs/guide/setup-a-webots-project-repository.md
  docs/guide/simulation-server.md
  docs/guide/web-animation.md
  docs/guide/webots-cloud.md
  docs/reference/changelog-r2022.md
  docs/reference/gps.md
  docs/reference/inertialunit.md
  include/controller/c/webots/gps.h
  include/controller/cpp/webots/GPS.hpp
  resources/web/wwi/Animation.js
  resources/web/wwi/css/progress.css
  resources/web/wwi/nodes/WbViewpoint.js
  resources/web/wwi/webots.js
  scripts/converter/declare_externproto.py
  scripts/icon_studio/controllers/icon_creator/icon_creator.py
  src/controller/c/gps.c
  src/controller/cpp/GPS.cpp
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/WbLidar.hpp
  src/webots/nodes/WbLightSensor.cpp
Labels: test suite, synchronization

#5248 Change keyword `docker:` to `loading:`
  resources/web/wwi/Server.js
Labels: enhancement

#5252 Fixed a typo in the doc
  docs/guide/tutorial-8-the-supervisor.md
Labels: documentation

#5253 Fixed an axis typo
  docs/guide/tutorial-5-compound-solid-and-physics-attributes.md
Labels: documentation

#5254 Changed a figure's caption to correspond more to it
  docs/guide/tutorial-2-modification-of-the-environment.md
Labels: documentation

#5119 Feature web terminal
  .eslintrc.json
  docs/guide/images/web_interface_terminal.png
  docs/guide/web-streaming.md
  resources/web/wwi/FloatingRobotWindow.js
  resources/web/wwi/Terminal.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/dependencies/ansi_up.js
  resources/web/wwi/images/icons/clear.svg
Labels: feature

#5260 Fix recusion in animation update
  docs/reference/changelog-r2022.md
  resources/web/wwi/Animation.js
Labels: bug

#5259 Better figure order
  docs/guide/tutorial-6-4-wheels-robot.md
Labels: documentation

#5261 Merge master in develop
  docs/reference/changelog-r2022.md
  resources/web/wwi/Animation.js
  resources/web/wwi/Server.js
Labels: synchronization

#5243 added section to correct corners that are separated by commas instead…
  scripts/converter/convert_nue_to_enu_rub_to_flu.py
Labels: bug, test sources

#5265 Feature custom web window
  docs/guide/web-animation.md
  docs/reference/changelog-r2023.md
  resources/web/wwi/Animation.js
  resources/web/wwi/FloatingCustomWindow.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/css/toolbar.css
Labels: feature

#5268 Fix measurement of spot light
  src/webots/nodes/WbLightSensor.cpp
Labels: bug, test suite

#5269 Fix counting test suite failures
  tests/test_suite.py
Labels: test suite issue, test suite

#5271 Merge master into develop
  scripts/converter/convert_nue_to_enu_rub_to_flu.py
  src/webots/nodes/WbLightSensor.cpp
  tests/test_suite.py
Labels: test suite, synchronization

#5272 Enhance robot window in webots.js for mjpeg mode
  docs/reference/changelog-r2023.md
  resources/web/wwi/Parser.js
  resources/web/wwi/Server.js
  resources/web/wwi/Stream.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/webots.js
  src/webots/gui/WbTcpServer.cpp
  src/webots/gui/WbTcpServer.hpp
  src/webots/gui/WbX3dStreamingServer.cpp
  src/webots/gui/WbX3dStreamingServer.hpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbWorldInfo.cpp
Labels: enhancement, cleanup

#5168 New ROSbot PROTO with associated devices PROTOs
  docs/guide/images/robots/rosbot/distance_sensors.png
  docs/guide/images/robots/rosbot/icon.png
  docs/guide/images/robots/rosbot/model.png
  docs/guide/images/robots/rosbot/model.thumbnail.png
  docs/guide/images/robots/rosbot/rosbot.wbt.png
  docs/guide/images/robots/rosbot/rosbot.wbt.thumbnail.png
  docs/guide/images/sensors/astra.png
  docs/guide/images/sensors/astra.thumbnail.png
  docs/guide/images/sensors/astra_icon.png
  docs/guide/images/sensors/mpu-9250.png
  docs/guide/images/sensors/mpu-9250.thumbnail.png
  docs/guide/images/sensors/mpu-9250_icon.png
  docs/guide/images/sensors/rplidara2.png
  docs/guide/images/sensors/rplidara2.thumbnail.png
  docs/guide/images/sensors/rplidara2_icon.png
  docs/guide/imu-sensors.md
  docs/guide/lidar-sensors.md
  docs/guide/menu.md
  docs/guide/range-finder-sensors.md
  docs/guide/robots.md
  docs/guide/rosbot.md
  docs/guide/scenes/rosbot/rosbot.meta.json
  docs/guide/scenes/rosbot/rosbot.x3d
  docs/guide/sensors.md
  docs/reference/changelog-r2023.md
  projects/devices/orbbec/protos/Astra.proto
  projects/devices/orbbec/protos/icons/Astra.png
  projects/devices/orbbec/protos/meshes/astra.obj
  projects/devices/slamtec/protos/RpLidarA2.proto
  projects/devices/slamtec/protos/icons/RpLidarA2.png
  projects/devices/slamtec/protos/meshes/rplidar_bottom.obj
  projects/devices/slamtec/protos/meshes/rplidar_top.obj
  projects/devices/tdk/protos/Mpu-9250.proto
  projects/devices/tdk/protos/icons/Mpu-9250.png
  projects/robots/Makefile
  projects/robots/husarion/rosbot/controllers/Makefile
  projects/robots/husarion/rosbot/controllers/rosbot/.gitignore
  projects/robots/husarion/rosbot/controllers/rosbot/Makefile
  projects/robots/husarion/rosbot/controllers/rosbot/rosbot.c
  projects/robots/husarion/rosbot/protos/Rosbot.proto
  projects/robots/husarion/rosbot/protos/icons/Rosbot.png
  projects/robots/husarion/rosbot/protos/meshes/black_ports.obj
  projects/robots/husarion/rosbot/protos/meshes/box.obj
  projects/robots/husarion/rosbot/protos/meshes/metallic_connections.obj
  projects/robots/husarion/rosbot/protos/meshes/proximity_sensors.obj
  projects/robots/husarion/rosbot/protos/meshes/screw.obj
  projects/robots/husarion/rosbot/protos/meshes/upper.obj
  projects/robots/husarion/rosbot/protos/meshes/wheel_rim.obj
  projects/robots/husarion/rosbot/protos/meshes/wheel_tire.obj
  projects/robots/husarion/rosbot/worlds/.rosbot.wbproj
  projects/robots/husarion/rosbot/worlds/rosbot.wbt
  scripts/web_component_studio/components.json
Labels: feature

#5274 Improve default PROTO translation field documentation
  docs/reference/proto-design-guidelines.md
Labels: documentation

#5273 Fix handling errors in CadShape URLs in the web interface
  resources/web/wwi/nodes/WbCadShape.js
Labels: bug

#5277 Merge released in master
  docs/guide/simulation-server.md
  docs/guide/tutorial-2-modification-of-the-environment.md
  docs/guide/tutorial-5-compound-solid-and-physics-attributes.md
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/guide/tutorial-8-the-supervisor.md
  docs/reference/proto-design-guidelines.md
Labels: synchronization

#5280 Fix rosbot web component
  docs/guide/scenes/rosbot/rosbot.meta.json
  docs/guide/scenes/rosbot/rosbot.x3d
Labels: bug, documentation

#5284 Fix controller restart after crash
  docs/reference/changelog-r2022.md
  src/webots/control/WbController.cpp
Labels: bug
