Repository cyberbotics/webots, pull requests merged in 2022-10, with the labels that each got.

#5287 Fix pointSet shader for web
  resources/wren/shaders/point_set.frag
Labels: bug, test suite

#5293 Fix ecma version and coding style
  .eslintrc.json
  resources/web/wwi/nodes/WbCadShape.js
  resources/web/wwi/system_info.js
Labels: cleanup

#5299 Merge master in develop
  .eslintrc.json
  resources/web/wwi/nodes/WbCadShape.js
  resources/web/wwi/system_info.js
Labels: synchronization

#5301 Fixed Qt6.4 deprecation warnings
  docs/reference/changelog-r2022.md
  src/webots/gui/WbMultimediaStreamingServer.cpp
  src/webots/gui/WbSimulationView.cpp
Labels: upgrade

#5302 Merge master into develop
  docs/reference/changelog-r2022.md
  src/webots/gui/WbMultimediaStreamingServer.cpp
  src/webots/gui/WbSimulationView.cpp
Labels: synchronization

#5307 WebotsJS private variables
  resources/web/wwi/Animation.js
  resources/web/wwi/AnimationSlider.js
  resources/web/wwi/DefaultUrl.js
  resources/web/wwi/FloatingWindow.js
  resources/web/wwi/MouseEvents.js
  resources/web/wwi/MultimediaClient.js
  resources/web/wwi/Parser.js
  resources/web/wwi/Progress.js
  resources/web/wwi/RobotWindow.js
  resources/web/wwi/Server.js
  resources/web/wwi/Stream.js
  resources/web/wwi/Terminal.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/WrenRenderer.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/image_loader.js
  resources/web/wwi/nodes/WbAppearance.js
  resources/web/wwi/nodes/WbBackground.js
  resources/web/wwi/nodes/WbBaseNode.js
  resources/web/wwi/nodes/WbBillboard.js
  resources/web/wwi/nodes/WbBox.js
  resources/web/wwi/nodes/WbCadShape.js
  resources/web/wwi/nodes/WbCapsule.js
  resources/web/wwi/nodes/WbCylinder.js
  resources/web/wwi/nodes/WbDirectionalLight.js
  resources/web/wwi/nodes/WbElevationGrid.js
  resources/web/wwi/nodes/WbFog.js
  resources/web/wwi/nodes/WbGeometry.js
  resources/web/wwi/nodes/WbImageTexture.js
  resources/web/wwi/nodes/WbIndexedLineSet.js
  resources/web/wwi/nodes/WbLight.js
  resources/web/wwi/nodes/WbPlane.js
  resources/web/wwi/nodes/WbPointLight.js
  resources/web/wwi/nodes/WbPointSet.js
  resources/web/wwi/nodes/WbScene.js
  resources/web/wwi/nodes/WbShape.js
  resources/web/wwi/nodes/WbSphere.js
  resources/web/wwi/nodes/WbSpotLight.js
  resources/web/wwi/nodes/WbTextureTransform.js
  resources/web/wwi/nodes/WbTriangleMeshGeometry.js
  resources/web/wwi/nodes/WbViewpoint.js
  resources/web/wwi/nodes/utils/WbTriangleMesh.js
  resources/web/wwi/webots.js
  resources/web/wwi/wren/WbWrenBloom.js
  resources/web/wwi/wren/WbWrenGtao.js
  resources/web/wwi/wren/WbWrenHdr.js
  resources/web/wwi/wren/WbWrenPicker.js
Labels: cleanup

#5308 Fix macOS compilation due to imu.c
  projects/samples/devices/controllers/imu/imu.c
Labels: bug

#5310 Fix TCP extern controller connection when world is loading
  docs/reference/changelog-r2022.md
  src/webots/gui/WbTcpServer.cpp
Labels: bug, crash

#5315 Added missing or misplaced altimeter references in the reference manual
  docs/reference/menu.md
  docs/reference/nodes-and-api-functions.md
  docs/reference/physics.md
  docs/reference/robot-window-plugin.md
  docs/reference/robot.md
  docs/reference/solid.md
  docs/reference/worldinfo.md
Labels: documentation

#5318 Merge released into master
  docs/reference/camera.md
  docs/reference/menu.md
  docs/reference/nodes-and-api-functions.md
  docs/reference/physics.md
  docs/reference/robot-window-plugin.md
  docs/reference/robot.md
  docs/reference/solid.md
  docs/reference/worldinfo.md
Labels: synchronization

#5319 Merge master into develop
  docs/reference/camera.md
  docs/reference/changelog-r2022.md
  docs/reference/menu.md
  docs/reference/nodes-and-api-functions.md
  docs/reference/physics.md
  docs/reference/robot-window-plugin.md
  docs/reference/robot.md
  docs/reference/solid.md
  docs/reference/worldinfo.md
  src/webots/control/WbControlledWorld.cpp
  src/webots/gui/WbTcpServer.cpp
  src/webots/nodes/WbLidar.cpp
Labels: test suite, synchronization

#5322 Fix missing import
  resources/web/wwi/nodes/WbCadShape.js
Labels: bug

#5323 Add cadshape fieldmodel
  resources/web/wwi/protoDesigner/classes/FieldModel.js
Labels: enhancement

#5328 Enhancement add new web nodes
  resources/web/wwi/Parser.js
  resources/web/wwi/nodes/WbAccelerometer.js
  resources/web/wwi/nodes/WbAltimeter.js
  resources/web/wwi/nodes/WbBallJoint.js
  resources/web/wwi/nodes/WbBallJointParameters.js
  resources/web/wwi/nodes/WbBrake.js
  resources/web/wwi/nodes/WbCamera.js
  resources/web/wwi/nodes/WbCharger.js
  resources/web/wwi/nodes/WbCompass.js
  resources/web/wwi/nodes/WbConnector.js
  resources/web/wwi/nodes/WbDisplay.js
  resources/web/wwi/nodes/WbDistanceSensor.js
  resources/web/wwi/nodes/WbEmitter.js
  resources/web/wwi/nodes/WbGps.js
  resources/web/wwi/nodes/WbGroup.js
  resources/web/wwi/nodes/WbGyro.js
  resources/web/wwi/nodes/WbHinge2Joint.js
  resources/web/wwi/nodes/WbHingeJoint.js
  resources/web/wwi/nodes/WbHingeJointParameters.js
  resources/web/wwi/nodes/WbInertialUnit.js
  resources/web/wwi/nodes/WbJoint.js
  resources/web/wwi/nodes/WbJointParameters.js
  resources/web/wwi/nodes/WbLed.js
  resources/web/wwi/nodes/WbLidar.js
  resources/web/wwi/nodes/WbLightSensor.js
  resources/web/wwi/nodes/WbLinearMotor.js
  resources/web/wwi/nodes/WbLogicalDevice.js
  resources/web/wwi/nodes/WbMotor.js
  resources/web/wwi/nodes/WbPen.js
  resources/web/wwi/nodes/WbPositionSensor.js
  resources/web/wwi/nodes/WbRadar.js
  resources/web/wwi/nodes/WbRangeFinder.js
  resources/web/wwi/nodes/WbReceiver.js
  resources/web/wwi/nodes/WbRotationalMotor.js
  resources/web/wwi/nodes/WbSliderJoint.js
  resources/web/wwi/nodes/WbSlot.js
  resources/web/wwi/nodes/WbSolid.js
  resources/web/wwi/nodes/WbSpeaker.js
  resources/web/wwi/nodes/WbTouchSensor.js
  resources/web/wwi/nodes/WbTrack.js
  resources/web/wwi/protoDesigner/classes/FieldModel.js
  resources/web/wwi/protoDesigner/classes/ProtoParser.js
  resources/web/wwi/protos/ProtoBallJoint.proto
  resources/web/wwi/protos/ProtoHinge.proto
  resources/web/wwi/protos/ProtoHinge2.proto
  resources/web/wwi/protos/ProtoPropeller.proto
  resources/web/wwi/protos/ProtoSlider.proto
  resources/web/wwi/protos/ProtoSolidDevice.proto
  resources/web/wwi/protos/ProtoTrack.proto
  resources/web/wwi/test.html
Labels: enhancement

#5334 Remove references to lidar device from RangeFinder section
  docs/reference/rangefinder.md
Labels: documentation

#5335 Merge released into master
  docs/reference/rangefinder.md
Labels: synchronization

#5337 Fix black buttons in RangeFinder overlay
  docs/reference/changelog-r2022.md
  resources/wren/shaders/overlay.frag
Labels: bug, test suite

#5266 Add Camera fisheye effect
  docs/guide/camera-sensors.md
  docs/reference/camera.md
  docs/reference/changelog-r2023.md
  docs/reference/images/camera_projection_model.png
  docs/reference/images/spherical_and_cylindrical_camera_images.png
  docs/reference/lidar.md
  docs/reference/rangefinder.md
  projects/devices/hokuyo/protos/HokuyoUrg04lx.proto
  projects/devices/hokuyo/protos/HokuyoUrg04lxug01.proto
  projects/devices/hokuyo/protos/HokuyoUtm30lx.proto
  projects/devices/ibeo/protos/IbeoLux.proto
  projects/devices/sick/protos/SickLms291.proto
  projects/devices/velodyne/protos/VelodyneHDL-32E.proto
  projects/devices/velodyne/protos/VelodyneHDL-64E.proto
  projects/devices/velodyne/protos/VelodynePuck.proto
  projects/robots/clearpath/pr2/protos/Pr2.proto
  projects/samples/devices/worlds/spherical_camera.wbt
  resources/nodes/Camera.wrl
  resources/nodes/Lidar.wrl
  resources/nodes/RangeFinder.wrl
  resources/wren/shaders/merge_spherical.frag
  src/controller/c/abstract_camera.c
  src/controller/c/abstract_camera.h
  src/controller/c/camera.c
  src/controller/c/lidar.c
  src/controller/c/range_finder.c
  src/webots/nodes/WbAbstractCamera.cpp
  src/webots/nodes/WbAbstractCamera.hpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbDisplay.cpp
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/WbRangeFinder.cpp
  src/webots/nodes/WbRenderingDevice.cpp
  src/webots/nodes/WbRenderingDevice.hpp
  src/webots/wren/WbWrenCamera.cpp
  src/webots/wren/WbWrenCamera.hpp
  src/webots/wren/WbWrenShaders.cpp
  tests/api/controllers/camera_checker/camera_checker.c
  tests/api/worlds/camera_color_spherical.wbt
  tests/api/worlds/lidar_vs_range_finder.wbt
  tests/api/worlds/range_finder_horizontal_spherical_projection.wbt
  tests/api/worlds/range_finder_spherical.wbt
  tests/api/worlds/range_finder_spherical_horizontal_vertical.wbt
Labels: cleanup, feature, test suite

#5340 Improve visibility of overlay close button
  resources/wren/shaders/overlay.vert
  resources/wren/textures/cyan_close_symbol.png
  resources/wren/textures/magenta_close_symbol.png
  resources/wren/textures/yellow_close_symbol.png
  resources/wren/textures/yellow_resize_symbol.png
  src/webots/wren/WbWrenTextureOverlay.cpp
Labels: enhancement

#5342 Refactor animation recorder
  src/webots/engine/WbAnimationRecorder.cpp
  src/webots/engine/WbAnimationRecorder.hpp
Labels: enhancement, cleanup

#5344 Merge develop in feature web proto
  docs/guide/camera-sensors.md
  docs/reference/camera.md
  docs/reference/changelog-r2023.md
  docs/reference/images/camera_projection_model.png
  docs/reference/images/spherical_and_cylindrical_camera_images.png
  docs/reference/lidar.md
  docs/reference/rangefinder.md
  projects/devices/hokuyo/protos/HokuyoUrg04lx.proto
  projects/devices/hokuyo/protos/HokuyoUrg04lxug01.proto
  projects/devices/hokuyo/protos/HokuyoUtm30lx.proto
  projects/devices/ibeo/protos/IbeoLux.proto
  projects/devices/sick/protos/SickLms291.proto
  projects/devices/velodyne/protos/VelodyneHDL-32E.proto
  projects/devices/velodyne/protos/VelodyneHDL-64E.proto
  projects/devices/velodyne/protos/VelodynePuck.proto
  projects/robots/clearpath/pr2/protos/Pr2.proto
  projects/samples/devices/worlds/spherical_camera.wbt
  resources/nodes/Camera.wrl
  resources/nodes/Lidar.wrl
  resources/nodes/RangeFinder.wrl
  resources/wren/shaders/merge_spherical.frag
  src/controller/c/abstract_camera.c
  src/controller/c/abstract_camera.h
  src/controller/c/camera.c
  src/controller/c/lidar.c
  src/controller/c/range_finder.c
  src/webots/engine/WbAnimationRecorder.cpp
  src/webots/engine/WbAnimationRecorder.hpp
  src/webots/nodes/WbAbstractCamera.cpp
  src/webots/nodes/WbAbstractCamera.hpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbDisplay.cpp
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/WbRangeFinder.cpp
  src/webots/nodes/WbRenderingDevice.cpp
  src/webots/nodes/WbRenderingDevice.hpp
  src/webots/wren/WbWrenCamera.cpp
  src/webots/wren/WbWrenCamera.hpp
  src/webots/wren/WbWrenShaders.cpp
  tests/api/controllers/camera_checker/camera_checker.c
  tests/api/worlds/camera_color_spherical.wbt
  tests/api/worlds/lidar_vs_range_finder.wbt
  tests/api/worlds/range_finder_horizontal_spherical_projection.wbt
  tests/api/worlds/range_finder_spherical.wbt
  tests/api/worlds/range_finder_spherical_horizontal_vertical.wbt
Labels: synchronization

#5346 Restore the description of base node
  docs/reference/changelog-r2022.md
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/vrml/WbTokenizer.cpp
  src/webots/vrml/WbTokenizer.hpp
Labels: bug

#5348 Fix deprecated field in PR2 camera
  projects/robots/clearpath/pr2/protos/Pr2.proto
Labels: cleanup, test worlds

#5353 Fix ChangeLog indent
  docs/reference/changelog-r2022.md
Labels: documentation

#5354 Fix ccw of indexed face set for web proto
  resources/web/wwi/nodes/WbIndexedFaceSet.js
  resources/web/wwi/nodes/utils/WbTriangleMesh.js
Labels: bug

#5341 Fix PROTO declaration error when copy and pasting inserted nodes
  docs/reference/changelog-r2022.md
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: bug, test suite

#5350 Improve warnings and suggested path in save and wizard dialogs
  docs/reference/changelog-r2022.md
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbNewProjectWizard.cpp
  src/webots/gui/WbNewWorldWizard.cpp
Labels: enhancement, test webots build

#5359 Fix duplicated CadShape mesh load and improve warnings
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbCadShape.hpp
  src/webots/nodes/WbMesh.cpp
Labels: enhancement, test suite

#5368 Webots.js: remove decimal points from progress value
  resources/web/wwi/Parser.js
Labels: enhancement

#5366 Replace deprecated QPair
  src/webots/core/WbAction.hpp
  src/webots/core/WbFileUtil.cpp
  src/webots/core/WbFileUtil.hpp
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolidDevice.cpp
  src/webots/nodes/WbSolidDevice.hpp
  src/webots/nodes/utils/WbDictionary.cpp
  src/webots/nodes/utils/WbDictionary.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.hpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/nodes/utils/WbWorld.hpp
  src/webots/nodes/utils/WbWrenVertexArrayFrameListener.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/user_commands/WbClipboard.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
  src/webots/vrml/WbWriter.hpp
  src/webots/wren/WbWrenTextureOverlay.cpp
Labels: cleanup, test suite

#5314 Improve PROTO web loader
  projects/robots/franka_emika/panda/protos/Panda.proto
  resources/web/wwi/Parser.js
  resources/web/wwi/ProtoManager.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/nodes/utils/id_provider.js
  resources/web/wwi/protoDesigner/ProtoDesigner.js
  resources/web/wwi/protoDesigner/classes/Asset.js
  resources/web/wwi/protoDesigner/classes/AssetLibrary.js
  resources/web/wwi/protoDesigner/classes/FieldModel.js
  resources/web/wwi/protoDesigner/classes/Observable.js
  resources/web/wwi/protoDesigner/classes/Parameter.js
  resources/web/wwi/protoDesigner/classes/Proto.js
  resources/web/wwi/protoDesigner/classes/ProtoParser.js
  resources/web/wwi/protoDesigner/classes/utility/utility.js
  resources/web/wwi/protoDesigner/index.html
  resources/web/wwi/protoVisualizer/FieldModel.js
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Parameter.js
  resources/web/wwi/protoVisualizer/TemplateEngine.js
  resources/web/wwi/protoVisualizer/Token.js
  resources/web/wwi/protoVisualizer/Tokenizer.js
  resources/web/wwi/protoVisualizer/Vrml.js
  resources/web/wwi/protoVisualizer/scripts/basenode_encoder.py
  resources/web/wwi/protoVisualizer/templating/.gitignore
  resources/web/wwi/protoVisualizer/templating/jsTemplate.js
  resources/web/wwi/protoVisualizer/templating/modules/webots/wbgeometry.js
  resources/web/wwi/protoVisualizer/templating/modules/webots/wbrandom.js
  resources/web/wwi/protoVisualizer/templating/modules/webots/wbrotation.js
  resources/web/wwi/protoVisualizer/templating/modules/webots/wbutility.js
  resources/web/wwi/protoVisualizer/templating/modules/webots/wbvector2.js
  resources/web/wwi/protoVisualizer/templating/modules/webots/wbvector3.js
  resources/web/wwi/protos/DemoFieldChange.proto
  resources/web/wwi/protos/DemoRegeneration.proto
  resources/web/wwi/protos/TestProto.proto
  resources/web/wwi/test.html
  src/webots/core/WbTemplateEngine.cpp
Labels: feature

#4936 Improve Python scripts
  docs/guide/generate_objects_doc.py
  docs/local_exporter.py
  docs/tests/test_hyperlinks.py
  projects/default/controllers/sumo_supervisor/SumoSupervisor.py
  projects/default/controllers/sumo_supervisor/sumo_supervisor.py
  projects/default/libraries/vehicle/python/vehicle.i
  projects/robots/epson/scara_t6/controllers/scara_food_industry/scara_food_industry.py
  projects/robots/gctronic/e-puck/transfer/populate_xc16_directory.py
  projects/robots/robotis/darwin-op/libraries/python/managers.i
  projects/samples/contests/rockin/package_generator.py
  projects/samples/howto/docker/launcher_without_docker.py
  projects/samples/robotbenchmark/highway_driving/controllers/highway_driving_benchmark/highway_driving_benchmark.py
  projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/marathon.py
  projects/samples/robotbenchmark/include/robotbenchmark.py
  projects/samples/robotbenchmark/inverted_pendulum/controllers/inverted_pendulum_benchmark/inverted_pendulum_benchmark.py
  projects/samples/robotbenchmark/maze_runner/controllers/supervisor/supervisor.py
  projects/samples/robotbenchmark/obstacle_avoidance/controllers/supervisor/supervisor.py
  projects/samples/robotbenchmark/pick_and_place/controllers/pick_and_place_benchmark/pick_and_place_benchmark.py
  projects/samples/robotbenchmark/robot_programming/controllers/supervisor/supervisor.py
  projects/samples/robotbenchmark/square_path/controllers/square_path_supervisor/square_path_supervisor.py
  projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking_benchmark/visual_tracking_benchmark.py
  resources/sumo_exporter/exporter.py
  scripts/converter/convert_all_worlds.py
  scripts/converter/convert_geometries.py
  scripts/icon_studio/controllers/icon_creator/icon_creator.py
  scripts/packaging/generate_asset_cache.py
  scripts/packaging/generate_projects_files.py
  scripts/packaging/publish_release.py
  scripts/packaging/set_commit_and_date_in_version.py
  scripts/packaging/update_urls.py
  src/controller/matlab/mgenerate.py
  src/controller/python/controller.i
  tests/sources/test_clang_format.py
  tests/sources/test_cppcheck.py
  tests/sources/test_header_version.py
  tests/sources/test_icons.py
  tests/sources/test_license.py
  tests/sources/test_line_ending.py
  tests/sources/test_matlab_functions.py
  tests/sources/test_pep8.py
  tests/sources/test_project_structure.py
  tests/sources/test_proto.py
  tests/sources/test_textures.py
  tests/test_suite.py
  tests/test_worlds.py
Labels: enhancement, test suite, test sources, test worlds

#5367 Reopen robot window when extern controller reconnects
  docs/reference/changelog-r2022.md
  src/webots/control/WbControlledWorld.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbRobot.hpp
Labels: enhancement, test webots build

#5370 Extend proto visualizer
  resources/web/wwi/ProtoManager.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Parameter.js
  resources/web/wwi/protoVisualizer/Tokenizer.js
  resources/web/wwi/protoVisualizer/Vrml.js
  resources/web/wwi/protos/DemoFieldChange.proto
  resources/web/wwi/protos/DemoRegeneration.proto
  resources/web/wwi/protos/SubRegeneration.proto
  resources/web/wwi/test.html
Labels: enhancement

#5375 Add support for 5+ vertices polygon
  resources/web/wwi/nodes/WbMesh.js
  resources/web/wwi/nodes/utils/WbTriangleMesh.js
  resources/web/wwi/nodes/utils/WbVector3.js
Labels: enhancement

#5380 Fix INFO condition when changing controller
  src/webots/control/WbControlledWorld.cpp
Labels: bug

#5381 Hotfix compilation error
  src/webots/control/WbControlledWorld.cpp
Labels: bug

#5329 Fix the external controller connection
  src/webots/control/WbControlledWorld.cpp
  src/webots/control/WbControlledWorld.hpp
  src/webots/control/WbController.cpp
  src/webots/gui/WbTcpServer.cpp
Labels: bug, test suite, test sources

#5383 Merge released into master
  docs/reference/motion.md
  docs/reference/proto-design-guidelines.md
Labels: synchronization

#5376 Implement first use case of webots.cloud/proto
  resources/web/wwi/FloatingCustomWindow.js
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/ProtoManager.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/images/icons/proto_parameter.svg
  resources/web/wwi/protoVisualizer/FieldModel.js
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Token.js
  resources/web/wwi/protoVisualizer/Tokenizer.js
  resources/web/wwi/protoVisualizer/Vrml.js
  resources/web/wwi/protoVisualizer/vrml_type.js
  resources/web/wwi/test.html
Labels: enhancement

#5397 Fix crash when robot with extern controller is deleted
  src/webots/control/WbController.cpp
Labels: bug, crash
