Repository cyberbotics/webots, pull requests merged in 2022-01, with the labels that each got.

#4082 Supported 3d model imports docs
  docs/guide/the-user-interface.md
Labels: documentation

#4083 Re-introduce name in MultiSenseS21 range finder device
  projects/devices/multisense/protos/MultiSenseS21.proto
Labels: regression

#4084 Added docker image upgrade instructions
  docs/guide/installation-procedure.md
Labels: documentation

#4088 Document rescaling functionality
  docs/guide/images/manipulators.png
  docs/guide/images/manipulators_label.png
  docs/guide/images/pose_manipulator.png
  docs/guide/images/resize_manipulator.png
  docs/guide/the-3d-window.md
Labels: documentation

#4096 Allow the use of WebotsView in Safari
  resources/web/wwi/webots.js
Labels: enhancement

#4095 Merge master in develop
  docs/discord/development-2019.md
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/documentation.md
  docs/discord/menu.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/discord/technical-questions.md
  docs/guide/images/manipulators.png
  docs/guide/images/manipulators_label.png
  docs/guide/images/pose_manipulator.png
  docs/guide/images/resize_manipulator.png
  docs/guide/installation-procedure.md
  docs/guide/the-3d-window.md
  docs/guide/the-user-interface.md
  docs/guide/tutorial-3-appearance.md
  docs/guide/tutorial-8-the-supervisor.md
  docs/js/showdown-extensions.js
  docs/js/webots_documentation_loader.js
  docs/reference/changelog-r2022.md
  projects/devices/multisense/protos/MultiSenseS21.proto
  projects/objects/apartment_structure/protos/Window.proto
  resources/web/wwi/webots.js
  scripts/get_git_info/get_git_info.sh
  src/webots/core/WbTelemetry.cpp
  src/webots/core/WbWebotsUpdateManager.cpp
  src/webots/nodes/utils/WbDownloader.cpp
Labels: test suite

#4098 Fix rotation spinner snap value
  src/webots/scene_tree/WbFieldDoubleSpinBox.cpp
Labels: bug

#4069 Allow ROS 2 to access the Supervisor instance
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  include/controller/cpp/webots/Robot.hpp
  include/controller/cpp/webots/Supervisor.hpp
  src/controller/cpp/Robot.cpp
  src/controller/cpp/Supervisor.cpp
Labels: enhancement, test suite, deploy libcontroller

#4106 Remove `static` mention
  docs/reference/proto-design-guidelines.md
Labels: documentation, cleanup

#4105 Remove webots -> libcontroller notification of relayed commands in motor couplings
  src/controller/c/motor.c
  src/webots/nodes/WbMotor.cpp
Labels: test suite, test sources

#4102 Avoid exporting SolidReference to URDF
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbJoint.cpp
Labels: bug, test suite

#4109 Update cpp-java-python.md
  docs/guide/cpp-java-python.md
Labels: documentation

#4101 fix village winter texture
  projects/vehicles/worlds/textures/snowy_road/snowy_road_base_color.jpg
  projects/vehicles/worlds/textures/snowy_road/snowy_road_normal.jpg
  projects/vehicles/worlds/textures/snowy_road/snowy_road_occlusion.jpg
  projects/vehicles/worlds/textures/snowy_road/snowy_road_roughness.jpg
  projects/vehicles/worlds/village_winter.wbt
Labels: enhancement

#4104 Feature PROTO wizard
  docs/guide/the-user-interface.md
  docs/reference/changelog-r2022.md
  resources/templates/protos/template.proto
  resources/webots_classic.qss
  resources/webots_dusk.qss
  resources/webots_night.qss
  src/webots/Makefile
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/gui/WbNewProtoWizard.cpp
  src/webots/gui/WbNewProtoWizard.hpp
  src/webots/vrml/WbNodeModel.cpp
  src/webots/vrml/WbNodeModel.hpp
  src/webots/vrml/WbProtoList.cpp
  src/webots/vrml/WbProtoList.hpp
  src/webots/vrml/WbVariant.cpp
  tests/parser/expected_results.txt
  tests/sources/test_header_version.py
Labels: feature, test suite, test sources

#4107 Add `robot_step_begin()` and `robot_step_end()` API functions for controller optimization
  docs/reference/robot.md
  include/controller/c/webots/robot.h
  include/controller/cpp/webots/Robot.hpp
  lib/controller/matlab/.gitignore
  projects/samples/howto/parallel_robot_step/controllers/parallel_robot_step/.gitignore
  projects/samples/howto/parallel_robot_step/controllers/parallel_robot_step/Makefile
  projects/samples/howto/parallel_robot_step/controllers/parallel_robot_step/parallel_robot_step.c
  projects/samples/howto/parallel_robot_step/worlds/.parallel_robot_step.wbproj
  projects/samples/howto/parallel_robot_step/worlds/parallel_robot_step.wbt
  src/controller/c/Controller.def
  src/controller/c/brake.c
  src/controller/c/display.c
  src/controller/c/motor.c
  src/controller/c/position_sensor.c
  src/controller/c/robot.c
  src/controller/c/robot_private.h
  src/controller/c/skin.c
  src/controller/c/supervisor.c
  src/controller/cpp/Robot.cpp
  src/controller/matlab/mgenerate.py
  src/controller/python/controller.i
  src/webots/core/WbLanguage.cpp
  tests/api/controllers/robot_parallel_step/.gitignore
  tests/api/controllers/robot_parallel_step/Makefile
  tests/api/controllers/robot_parallel_step/robot_parallel_step.c
  tests/api/worlds/robot_parallel_step.wbt
Labels: feature, test suite

#4118 Fixed broken dependencies in libCppController
  src/controller/cpp/Makefile
Labels: bug

#3977 Improve web simulation
  docs/guide/web-simulation.md
  projects/robots/gctronic/e-puck/controllers/e-puck/Dockerfile
  resources/web/server/config/session/amazon.json
  resources/web/server/config/session/default.json
  resources/web/server/config/session/local.json
  resources/web/server/config/simulation/amazon.json
  resources/web/server/config/simulation/cyberbotics1.json
  resources/web/server/config/simulation/cyberbotics2.json
  resources/web/server/config/simulation/default.json
  resources/web/server/config/simulation/local.json
  resources/web/server/session_server.py
  resources/web/server/simulation_server.py
  resources/web/wwi/Server.js
  resources/web/wwi/webots.js
  scripts/get_git_info/get_git_info.sh
  src/webots/control/WbControlledWorld.cpp
  src/webots/control/WbControlledWorld.hpp
  src/webots/control/WbController.cpp
  src/webots/control/WbController.hpp
  src/webots/core/WbFileUtil.cpp
  src/webots/core/WbFileUtil.hpp
Labels: enhancement, test suite

#4130 Delete test Dockerfile
  projects/robots/gctronic/e-puck/controllers/e-puck/Dockerfile
Labels: bug

#4135 Merge `released` into `master`
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/development-2022.md
  docs/discord/development.md
  docs/discord/menu.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/guide/cpp-java-python.md
  docs/reference/proto-design-guidelines.md
Labels: documentation

#4136 Fix check in WbServer.js
  resources/web/wwi/Server.js
Labels: bug

#4133 Fix insufficient check in Solid's `postPhysicsStep` resulting in exploding Track
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbSolid.cpp
Labels: bug, test suite, test sources

#4140 Fix world save API
  docs/reference/changelog-r2022.md
  docs/reference/supervisor.md
  src/controller/c/supervisor.c
Labels: bug, test suite

#4142 Added step_begin and step_end to r2022 changelog
  docs/reference/changelog-r2022.md
Labels: documentation

#4143 Added precision in r2022b changelog
  docs/reference/changelog-r2022.md
Labels: documentation

#4145 Update Urls
  docs/guide/using-matlab.md
  docs/reference/proto-design-guidelines.md
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.html
  projects/vehicles/plugins/robot_windows/automobile/automobile.html
  resources/osm_importer/config.ini
  resources/osm_importer/elevation.py
  resources/osm_importer/utils/misc_utils.py
  resources/osm_importer/webots_objects/barrier.py
  resources/osm_importer/webots_objects/road.py
Labels: bug

#4147 Generalize update of Webots version in world file header
  scripts/converter/convert_nue_to_enu_rub_to_flu.py
Labels: enhancement

#4150 Fix typo in `WbTextureTransform`
  src/webots/nodes/WbTextureTransform.hpp
  src/webots/nodes/WbTrack.cpp
Labels: cleanup

#4149 Fix mobile navigation
  resources/web/wwi/MouseEvents.js
Labels: bug

#4155 Fix broken video link
  docs/guide/nao.md
Labels: documentation

#4137 Remove-webkit-webengine
  dependencies/Makefile.linux
  dependencies/Makefile.mac
  dependencies/Makefile.windows
  resources/Makefile.include
  resources/qt_warning_filters.conf
  resources/translations/qt_de.ts
  resources/translations/qt_es.ts
  resources/translations/qt_fr.ts
  resources/translations/qt_it.ts
  resources/translations/qt_ja_JP.ts
  resources/translations/qt_zh_CN.ts
  resources/web/local/.gitignore
  resources/web/local/webots.css
  resources/web/local/webots.js
  resources/webots_dusk.qss
  resources/webots_night.qss
  scripts/install/msys64_installer.sh
  scripts/install/qt_linux_installer.sh
  scripts/install/qt_mac_installer.sh
  scripts/install/qt_windows_installer.sh
  scripts/packaging/files_core.txt
  scripts/packaging/files_msys64.txt
  scripts/packaging/update_all_worlds.py
  scripts/packaging/webots_distro.c
  src/webots/Makefile
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbRobotWindowStreamingServer.cpp
  src/webots/gui/WbRobotWindowStreamingServer.hpp
  src/webots/gui/WbRobotWindowTransportLayer.cpp
  src/webots/gui/WbRobotWindowTransportLayer.hpp
  src/webots/gui/WbWebPage.cpp
  src/webots/gui/WbWebPage.hpp
  tests/manual_tests/test_worlds_warnings.py
  tests/test_suite.py
Labels: cleanup, test sources

#4141 feature convert robot windows
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.html
  projects/humans/c3d/plugins/robot_windows/c3d_viewer_window/c3d_viewer_window.js
  projects/robots/mobsya/thymio/plugins/robot_windows/thymio2/thymio2.html
  projects/robots/mobsya/thymio/plugins/robot_windows/thymio2/thymio2.js
  projects/samples/howto/custom_robot_window/plugins/robot_windows/custom_robot_window/custom_robot_window.html
  projects/samples/howto/custom_robot_window/plugins/robot_windows/custom_robot_window/custom_robot_window.js
  projects/samples/robotbenchmark/highway_driving/plugins/robot_windows/highway_driving/highway_driving.html
  projects/samples/robotbenchmark/highway_driving/plugins/robot_windows/highway_driving/highway_driving.js
  projects/samples/robotbenchmark/highway_driving/worlds/.highway_driving.wbproj
  projects/samples/robotbenchmark/humanoid_marathon/plugins/robot_windows/humanoid_marathon/humanoid_marathon.html
  projects/samples/robotbenchmark/humanoid_marathon/plugins/robot_windows/humanoid_marathon/humanoid_marathon.js
  projects/samples/robotbenchmark/humanoid_marathon/worlds/.humanoid_marathon.wbproj
  projects/samples/robotbenchmark/humanoid_sprint/plugins/robot_windows/humanoid_sprint/humanoid_sprint.html
  projects/samples/robotbenchmark/humanoid_sprint/plugins/robot_windows/humanoid_sprint/humanoid_sprint.js
  projects/samples/robotbenchmark/humanoid_sprint/worlds/.humanoid_sprint.wbproj
  projects/samples/robotbenchmark/inverted_pendulum/plugins/robot_windows/inverted_pendulum/inverted_pendulum.html
  projects/samples/robotbenchmark/inverted_pendulum/plugins/robot_windows/inverted_pendulum/inverted_pendulum.js
  projects/samples/robotbenchmark/inverted_pendulum/worlds/.inverted_pendulum.wbproj
  projects/samples/robotbenchmark/maze_runner/plugins/robot_windows/maze_runner/maze_runner.html
  projects/samples/robotbenchmark/maze_runner/plugins/robot_windows/maze_runner/maze_runner.js
  projects/samples/robotbenchmark/maze_runner/worlds/.maze_runner.wbproj
  projects/samples/robotbenchmark/obstacle_avoidance/plugins/robot_windows/obstacle_avoidance/obstacle_avoidance.html
  projects/samples/robotbenchmark/obstacle_avoidance/plugins/robot_windows/obstacle_avoidance/obstacle_avoidance.js
  projects/samples/robotbenchmark/obstacle_avoidance/worlds/.obstacle_avoidance.wbproj
  projects/samples/robotbenchmark/pick_and_place/plugins/robot_windows/pick_and_place/pick_and_place.html
  projects/samples/robotbenchmark/pick_and_place/plugins/robot_windows/pick_and_place/pick_and_place.js
  projects/samples/robotbenchmark/pick_and_place/worlds/.pick_and_place.wbproj
  projects/samples/robotbenchmark/pit_escape/plugins/robot_windows/pit_escape/pit_escape.html
  projects/samples/robotbenchmark/pit_escape/plugins/robot_windows/pit_escape/pit_escape.js
  projects/samples/robotbenchmark/robot_programming/plugins/robot_windows/robot_programming/robot_programming.html
  projects/samples/robotbenchmark/robot_programming/plugins/robot_windows/robot_programming/robot_programming.js
  projects/samples/robotbenchmark/square_path/plugins/robot_windows/square_path/square_path.html
  projects/samples/robotbenchmark/square_path/plugins/robot_windows/square_path/square_path.js
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/pan_tilt_camera_view/pan_tilt_camera_view.html
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/pan_tilt_camera_view/pan_tilt_camera_view.js
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/visual_tracking/visual_tracking.html
  projects/samples/robotbenchmark/visual_tracking/plugins/robot_windows/visual_tracking/visual_tracking.js
  projects/samples/robotbenchmark/wall_following/plugins/robot_windows/wall_following/wall_following.html
  projects/samples/robotbenchmark/wall_following/plugins/robot_windows/wall_following/wall_following.js
  projects/vehicles/plugins/robot_windows/automobile/automobile.html
  projects/vehicles/plugins/robot_windows/automobile/automobile.js
  src/webots/gui/WbStreamingServer.cpp
Labels: enhancement

#4158 Fix television
  projects/objects/television/protos/Television.proto
Labels: bug

#4148 Fix node string display
  src/webots/gui/WbNewProtoWizard.cpp
  src/webots/scene_tree/WbValueEditor.cpp
  src/webots/vrml/WbField.cpp
  src/webots/vrml/WbMultipleValue.cpp
  src/webots/vrml/WbSingleValue.hpp
  src/webots/vrml/WbVariant.cpp
  src/webots/vrml/WbVariant.hpp
  tests/parser/expected_results.txt
Labels: bug, test suite, test sources

#4156 Advertise simulation servers
  docs/guide/web-simulation.md
  resources/web/server/session_server.py
  resources/web/server/simulation_server.py
  resources/web/wwi/Server.js
  resources/web/wwi/webots.js
Labels: enhancement, feature

#4159 SickLms291 size fix #4152
  projects/devices/sick/protos/SickLms291.proto
Labels: bug
