Repository cyberbotics/webots, pull requests merged in 2022-06, with the labels that each got.

#4569 Fix support polygon access out of bounds
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbSolid.cpp
Labels: bug, crash, test suite

#4575 Fix assimpjs loading
  resources/web/wwi/Parser.js
Labels: bug

#4549 Python webots_distro
  Makefile
  scripts/packaging/.gitignore
  scripts/packaging/Makefile
  scripts/packaging/check_rpath.py
  scripts/packaging/copy_msys64_files.py
  scripts/packaging/generate_asset_cache.py
  scripts/packaging/generate_projects_files.py
  scripts/packaging/generic_distro.py
  scripts/packaging/linux_distro.py
  scripts/packaging/mac_distro.py
  scripts/packaging/update_urls.py
  scripts/packaging/webots_distro.c
  scripts/packaging/webots_distro.py
  scripts/packaging/windows_distro.py
Labels: cleanup, test distribution

#4579 Fix SWIG deprecation warning with Python 3.10 on Windows
  src/controller/python/Makefile
Labels: cleanup, test suite

#4581 Use forward slashs in Qt plugins path
  src/webots/gui/main.cpp
Labels: cleanup

#4582 Fix local IDE
  resources/web/wwi/FloatingIde.js
Labels: bug

#4583 Silence gcc false positive warning
  src/webots/nodes/WbConnector.cpp
Labels: cleanup

#4585 Server kills simulation after x time
  docs/guide/web-simulation.md
  resources/web/server/simulation_server.py
  resources/web/wwi/Server.js
Labels: enhancement

#4586 Fixed compilation warning on macOS
  src/webots/nodes/WbConnector.cpp
Labels: cleanup

#4588 Fixed compilation warning on Linux
  src/webots/nodes/WbConnector.cpp
Labels: cleanup

#4589 Fix compilation on Windows CI
  src/webots/nodes/WbConnector.cpp
Labels: bug, cleanup

#4591 Trigger release only on nightly and release tags
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_windows.yml
Labels: enhancement, test sources

#4603 Improved documentation about camera objects array lifecyle
  docs/reference/camera.md
Labels: documentation

#4605 Fix loading of broken image to be non-blocking
  resources/web/wwi/image_loader.js
Labels: enhancement

#4606 Improve export dialog
  docs/guide/images/animation-button.png
  docs/guide/images/share-button.png
  docs/guide/the-user-interface.md
  docs/guide/web-animation.md
  docs/guide/web-scene.md
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/gui/WbShareWindow.cpp
Labels: enhancement

#4608 Fix urdf export crashes
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbBaseNode.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
Labels: crash, test suite, test ros

#4610 Improve texture mapping of salamander head
  projects/samples/rendering/worlds/skins/salamander.fbx
  projects/samples/rendering/worlds/textures/salamander_base_color.jpg
Labels: enhancement

#4612 Remove empty transform
  projects/vehicles/worlds/village_realistic.wbt
Labels: cleanup

#4616 Fixed reinitialization of Camera memory mapped file
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/nodes/WbCamera.cpp
Labels: bug, crash

#4617 Remove i686 code (libController 32 bits on Windows)
  dependencies/Makefile.windows
  docs/reference/changelog-r2022.md
  resources/Makefile.include
  scripts/install/msys64_installer.sh
  scripts/packaging/windows_distro.py
  src/controller/c/Makefile
Labels: cleanup, test suite

#4615 Fix cadshape with .mtl spaced name
  src/webots/nodes/WbCadShape.cpp
Labels: bug

#4613 Fix scene navigation
  resources/web/wwi/MouseEvents.js
  resources/web/wwi/wren/WbWrenPicker.js
  resources/wren/shaders/web_depth.frag
  src/webots/maths/WbMatrix4.hpp
Labels: bug

#4623 Cleanup remove obsolete readmes
  src/webots/app/README.TXT
  src/webots/control/README.TXT
  src/webots/core/README.TXT
  src/webots/editor/README.TXT
  src/webots/engine/README.TXT
  src/webots/gui/README.TXT
  src/webots/maths/README.TXT
  src/webots/nodes/README.TXT
  src/webots/ode/README.TXT
  src/webots/plugins/README.TXT
  src/webots/scene_tree/README.TXT
  src/webots/user_commands/README.TXT
  src/webots/util/README.TXT
  src/webots/vrml/README.TXT
  src/webots/wren/README.TXT
Labels: cleanup

#4621 Enhancement optimize image scaledown
  docs/reference/changelog-r2022.md
  src/webots/Makefile
  src/webots/core/WbPreferences.cpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbView3D.cpp
  src/webots/maths/WbImage.cpp
  src/webots/maths/WbImage.hpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbPbrAppearance.cpp
Labels: enhancement

#4619 Fix segmentation color change
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbBaseNode.hpp
  src/webots/nodes/WbBasicJoint.cpp
  src/webots/nodes/WbBasicJoint.hpp
  src/webots/nodes/WbCadShape.hpp
  src/webots/nodes/WbGeometry.hpp
  src/webots/nodes/WbGroup.cpp
  src/webots/nodes/WbGroup.hpp
  src/webots/nodes/WbShape.cpp
  src/webots/nodes/WbShape.hpp
  src/webots/nodes/WbSkin.hpp
  src/webots/nodes/WbSlot.cpp
  src/webots/nodes/WbSlot.hpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolid.hpp
  tests/api/controllers/camera_recognition/camera_recognition.c
  tests/api/worlds/camera_recognition.wbt
Labels: bug, test suite

#4629 Fix finish button
  resources/webots_dusk.qss
  resources/webots_night.qss
Labels: bug

#4626 Fix Skin bones orientations when using Webots nodes
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/WbSkin.hpp
Labels: bug, test suite

#4630 Update Makefile.mac
  dependencies/Makefile.mac
Labels: bug, test suite

#4631 Merge master in develop
  docs/discord/development-2019.md
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/development-2022.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2019.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
  docs/guide/installation-procedure.md
  docs/reference/camera.md
  docs/reference/changelog-r2022.md
  projects/samples/rendering/worlds/skins/salamander.fbx
  projects/samples/rendering/worlds/textures/salamander_base_color.jpg
  src/webots/gui/WbSingleTaskApplication.cpp
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbJoint.cpp
  src/webots/nodes/WbSolid.hpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
Labels: test suite, test sources, synchronization

#4634 Fix busy TCP port message
  src/webots/gui/WbTcpServer.cpp
Labels: enhancement

#4638 Fixed missing Linux compilation dependency
  projects/default/controllers/ros/Makefile
  projects/default/libraries/vehicle/python/Makefile
  projects/robots/robotis/darwin-op/libraries/python/Makefile
  projects/vehicles/controllers/ros_automobile/Makefile
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/msys64_installer.sh
  src/controller/python/Makefile
  src/wren/Makefile
Labels: bug

#4622 Fix preferences dialog
  resources/stylesheet.linux.qss
  resources/stylesheet.macos.qss
  resources/stylesheet.windows.qss
  resources/webots_classic.qss
  resources/webots_dusk.qss
  resources/webots_night.qss
  src/webots/gui/WbPreferencesDialog.cpp
Labels: cleanup, test suite

#4633 Fix crash trying to convert PROTO nodes to new Webots format
  docs/reference/changelog-r2022.md
  src/webots/nodes/utils/WbNodeUtilities.cpp
Labels: crash

#4647 Fixed optional python library build
  projects/default/libraries/vehicle/python/Makefile
  projects/robots/robotis/darwin-op/libraries/python/Makefile
  src/controller/python/Makefile
Labels: bug

#4645 WebotsJS: fix elevation grid bounding object
  resources/web/wwi/Parser.js
  resources/web/wwi/nodes/WbElevationGrid.js
Labels: bug

#4644 Add support of subnets and netmasks for remote extern controllers
  docs/guide/running-extern-robot-controllers.md
  src/controller/c/scheduler.c
  src/webots/control/WbController.cpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbTcpServer.cpp
Labels: enhancement

#4649 Hotfix for coding style
  src/webots/core/WbSimulationState.cpp
Labels: cleanup

#4639 Fix test suite in debug mode
  src/webots/control/WbControlledWorld.cpp
  src/webots/maths/WbVector2.hpp
  src/webots/maths/WbVector3.hpp
Labels: bug

#4646 Enhancement share reset and thumbnail robustness
  src/webots/core/WbPreferences.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbPreferencesDialog.hpp
  src/webots/gui/WbSimulationView.cpp
  src/webots/gui/WbSimulationView.hpp
Labels: enhancement

#4651 Fixed Python 3.10 controller execution on Windows
  src/webots/control/WbLanguageTools.cpp
Labels: bug

#4660 Fix typo for webscene
  resources/web/wwi/WebotsView.js
Labels: bug

#4658 Fix crash on save
  src/webots/gui/WbView3D.cpp
Labels: bug, crash

#4659 Fix animation time start
  src/webots/engine/WbAnimationRecorder.cpp
  src/webots/engine/WbAnimationRecorder.hpp
Labels: enhancement, test suite

#4662 Fix black sphere bug
  src/wren/StaticMesh.cpp
Labels: bug

#4663 Enhance thumbnail upload robustness
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
Labels: enhancement

#4656 Use assimp-5.2.3 on Windows
  dependencies/Makefile.windows
  scripts/install/msys64_installer.sh
  scripts/packaging/files_msys64.txt
  scripts/packaging/webots_distro.py
  src/webots/Makefile
  src/wren/Makefile
Labels: bug, test suite

#4672 Remove R2022a windows nigthly
  .github/workflows/test_suite_windows.yml
Labels: bug

#4671 Update Preferences documentation
  docs/guide/preferences.md
Labels: documentation

#4661 Fix redundant copy of libode.so
  resources/Makefile.include
  src/ode/Makefile
Labels: bug, test suite

#4666 Fix doc progress bar
  resources/web/wwi/Parser.js
  resources/web/wwi/Progress.js
  resources/web/wwi/css/progress.css
Labels: bug

#4674 Fixed index of red cylinder on contact point demo
  projects/samples/howto/cylinder_stack/controllers/contact_points_supervisor/contact_points_supervisor.c
Labels: bug

#4681 Documentation update images
  docs/guide/images/streaming-server-screenshot.png
  docs/guide/images/streaming-server-screenshot.thumbnail.jpg
  docs/guide/images/web_interface_exit_fullscreen.png
  docs/guide/images/web_interface_fullscreen.png
  docs/guide/images/web_interface_info.png
  docs/guide/images/web_interface_quit.png
  docs/guide/images/web_interface_reset.png
  docs/guide/images/web_interface_robot_window.png
  docs/guide/images/web_interface_settings.png
  docs/guide/images/web_interface_step.png
  docs/guide/web-streaming.md
Labels: documentation

#4679 Fixed highway driving robotbenchmark
  projects/samples/robotbenchmark/highway_driving/protos/HighwayDrivingBenchmark.proto
  projects/samples/robotbenchmark/highway_driving/worlds/highway_driving.wbt
Labels: bug

#4682 Fixed PEP8 in generate_proto_list.py
  scripts/packaging/generate_proto_list.py
  scripts/packaging/webots_distro.py
Labels: cleanup, test suite

#4664 Improve documentation of viewpoint rotation
  docs/guide/the-3d-window.md
  src/webots/gui/WbMainWindow.cpp
Labels: documentation, test suite

#4686 Remove note about running old versions of Webots
  docs/guide/installation-procedure.md
Labels: documentation

#4683 Fix local streaming
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/nodes/utils/WbUrl.hpp
Labels: bug, test suite, test sources

#4689 Fix scheduled tests
  .github/workflows/test_suite_linux_develop.yml
Labels: bug

#4676 Fix download OpenSSL package only on Ubuntu 22.04
  dependencies/Makefile.linux
Labels: bug

#4688 Fix nightly tests
  .github/workflows/test_suite_linux_develop.yml
  projects/samples/robotbenchmark/highway_driving/worlds/highway_driving.wbt
Labels: bug

#4698 Fix Qt plugin path on Windows
  src/webots/gui/main.cpp
Labels: bug

#4693 Fix icon studio
  projects/objects/buildings/protos/LargeResidentialTowerFloor.proto
  projects/objects/buildings/protos/LargeResidentialTowerRoof.proto
  scripts/icon_studio/controllers/icon_creator/objects.json
  scripts/icon_studio/worlds/icon_studio.wbt
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/scene_tree/WbExternProtoEditor.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: bug, test sources

#4695 Fix iOS and Safari toolbar issues
  resources/web/wwi/Progress.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/system_info.js
Labels: bug

#4704 Fixed bug and duplicate function definition in Python API
  src/controller/python/controller.i
Labels: bug

#4707 Improve Using-ROS tutorial documentation
  docs/guide/tutorial-9-using-ros.md
Labels: documentation

#4706 Remove webots_ros from sample worlds
  src/webots/gui/WbOpenSampleWorldDialog.cpp
Labels: cleanup

#4703 Add the Crazyflie robot
  docs/guide/crazyflie.md
  docs/guide/images/robots/crazyflie/crazyflie.wbt.jpg
  docs/guide/images/robots/crazyflie/icon.png
  docs/guide/images/robots/crazyflie/model.png
  docs/guide/menu.md
  docs/guide/robots.md
  docs/reference/changelog-r2022.md
  projects/robots/bitcraze/crazyflie/controllers/crazyflie_controller/.gitignore
  projects/robots/bitcraze/crazyflie/controllers/crazyflie_controller/Makefile
  projects/robots/bitcraze/crazyflie/controllers/crazyflie_controller/crazyflie_controller.c
  projects/robots/bitcraze/crazyflie/controllers/crazyflie_controller/pid_controller.c
  projects/robots/bitcraze/crazyflie/controllers/crazyflie_controller/pid_controller.h
  projects/robots/bitcraze/crazyflie/protos/Crazyflie.proto
  projects/robots/bitcraze/crazyflie/protos/icons/Crazyflie.png
  projects/robots/bitcraze/crazyflie/protos/meshes/ccw_prop.dae
  projects/robots/bitcraze/crazyflie/protos/meshes/cf2_assembly.dae
  projects/robots/bitcraze/crazyflie/protos/meshes/cw_prop.dae
  projects/robots/bitcraze/crazyflie/worlds/.crazyflie.wbproj
  projects/robots/bitcraze/crazyflie/worlds/crazyflie.wbt
  scripts/web_component_studio/components.json
  tests/sources/test_license.py
Labels: enhancement

#4699 Fix nightlies on develop side
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  scripts/packaging/webots_distro.py
  tests/cache/cache_environment.py
Labels: bug, test suite, test world update, test sources

#4697 Fix nightlies on master side
  .github/workflows/test_suite_linux_develop.yml
Labels: bug

#4710 Fixed crazyflie controller compilation from upper Makefile
  docs/guide/crazyflie.md
  projects/robots/Makefile
  projects/robots/bitcraze/crazyflie/controllers/Makefile
  projects/robots/bitcraze/crazyflie/controllers/crazyflie/.gitignore
  projects/robots/bitcraze/crazyflie/controllers/crazyflie/Makefile
  projects/robots/bitcraze/crazyflie/controllers/crazyflie/crazyflie.c
  projects/robots/bitcraze/crazyflie/controllers/crazyflie/pid_controller.c
  projects/robots/bitcraze/crazyflie/controllers/crazyflie/pid_controller.h
  projects/robots/bitcraze/crazyflie/controllers/crazyflie_controller/.gitignore
  projects/robots/bitcraze/crazyflie/protos/Crazyflie.proto
  tests/sources/test_license.py
Labels: bug

#4713 Improved extern controllers documentation
  docs/guide/running-extern-robot-controllers.md
  docs/guide/using-your-ide.md
Labels: documentation

#4700 Cleanup Linux package dependencies
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  scripts/install/linux_compilation_dependencies.sh
  scripts/packaging/generate_projects_files.py
  scripts/packaging/linux_distro.py
Labels: cleanup, test distribution

#4718 Fix documentation for opening robot windows
  docs/guide/epuck.md
  docs/guide/robotis-op2.md
  docs/guide/thymio2.md
Labels: documentation

#4734 Remove broken dependency on Ubuntu 22.04
  scripts/install/linux_compilation_dependencies.sh
Labels: bug, test suite

#4736 Add missing ephemeral EXTERNPROTO needed by SumoInterface
  projects/vehicles/worlds/city_traffic.wbt
  projects/vehicles/worlds/highway_overtake.wbt
  projects/vehicles/worlds/sumo_interface_example.wbt
  projects/vehicles/worlds/village_center.wbt
Labels: bug

#4712 Fix world info in Guided Tour
  src/webots/gui/WbGuidedTour.cpp
  src/webots/gui/WbGuidedTour.hpp
Labels: bug, test suite

#4741 Fix macOS workflow on master
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
Labels: bug

#4743 Removed the 'Include all PROTO files' option from the relocation dialog
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/editor/WbProjectRelocationDialog.hpp
Labels: cleanup

#4747 Fix test world update
  .github/workflows/test_suite_linux_develop.yml
Labels: bug

#4746 Fix nightlies develop side
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
Labels: bug, test suite

#4731 Fix declaration of EXTERNPROTO in new world
  src/webots/core/WbProject.cpp
  src/webots/core/WbProject.hpp
  src/webots/gui/WbNewProjectWizard.cpp
Labels: bug, test distribution

#4748 Fixed hang after copy/paste of robots on Linux
  src/webots/control/WbController.cpp
Labels: bug

#4758 MacOS update SUMO from 1.10.0 to 1.13.0
  docs/reference/changelog-r2022.md
  projects/default/resources/Makefile
Labels: bug, test distribution

#4738 Hotfix View Proto Source functionality
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/editor/WbTextBuffer.cpp
  src/webots/editor/WbTextBuffer.hpp
  src/webots/editor/WbTextEditor.cpp
  src/webots/editor/WbTextEditor.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/scene_tree/WbExtendedStringEditor.hpp
  src/webots/scene_tree/WbFieldEditor.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/scene_tree/WbSceneTree.hpp
Labels: bug, test suite

#4765 Fixed camera reset
  src/webots/nodes/WbAbstractCamera.cpp
Labels: crash

#4760 Fix windows nightly
  scripts/packaging/generate_proto_list.py
Labels: bug, test distribution

#4766 Fixed compilation of controllers on Windows
  scripts/packaging/files_msys64.txt
Labels: bug

#4739 Fix warnings wb_robot_step() from ros controllers
  src/controller/c/robot.c
Labels: bug

#4769 Update changelog-r2022.md
  docs/reference/changelog-r2022.md
Labels: documentation

#4768 Fix forest relocation
  src/webots/editor/WbProjectRelocationDialog.cpp
Labels: bug

#4774 Add Panda splash-image
  resources/images/splash_images/mavic2pro.jpg
  resources/images/splash_images/panda.jpg
  resources/images/splash_images/robotino3.jpg
  resources/images/splash_images/spot.jpg
  resources/images/splash_images/tiago++.jpg
Labels: enhancement

#4775 Improve error message
  src/controller/c/supervisor.c
Labels: enhancement

#4782 Added template.proto to distributions
  scripts/packaging/files_core.txt
  scripts/packaging/generic_distro.py
Labels: bug

#4787 Fixed relocation of projects
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/editor/WbProjectRelocationDialog.hpp
Labels: bug, test sources

#4788 adding the missing EXTERNPROTO definitions to the highway.wbt world
  projects/vehicles/worlds/highway.wbt
Labels: bug

#4789 Add 'clean-urls' target to main Makefile
  Makefile
  scripts/packaging/update_urls.py
Labels: enhancement, test distribution

#4790 Fixed path to proto robot windows
  src/webots/vrml/WbProtoModel.cpp
Labels: bug

#4791 Fix macOS contents path
  projects/robots/robotis/darwin-op/libraries/managers/src/RobotisOp2DirectoryManager.cpp
  src/webots/core/WbStandardPaths.cpp
Labels: bug

#4780 Fix crazyflie web component
  docs/guide/crazyflie.md
  docs/guide/scenes/crazyflie/crazyflie.meta.json
  docs/guide/scenes/crazyflie/crazyflie.x3d
  projects/robots/bitcraze/crazyflie/worlds/.crazyflie.wbproj
  projects/robots/bitcraze/crazyflie/worlds/crazyflie.wbt
  scripts/web_component_studio/components.json
Labels: bug

#4803 Fix robot window can't find files outside local project
  resources/web/wwi/RobotWindow.js
  src/webots/gui/WbRobotWindow.cpp
  src/webots/gui/WbTcpServer.cpp
Labels: bug, test sources

#4801 Debug test-suite CI wrong url
  scripts/packaging/update_urls.py
Labels: test suite

#4794 Skip version check for VRML files
  src/webots/vrml/WbTokenizer.cpp
Labels: bug, test suite

#4806 Hotfix darwin-op motion path
  projects/robots/robotis/darwin-op/libraries/managers/src/RobotisOp2DirectoryManager.cpp
Labels: bug

#4802 Attempt to fix random robot window test failures
  tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py
Labels: bug
