Repository cyberbotics/webots, pull requests merged in 2022-11, with the labels that each got.

#5378 Resolve circular dependencies
  src/webots/Makefile
  src/webots/app/WbApplication.cpp
  src/webots/app/WbApplication.hpp
  src/webots/core/WbDownloadManager.cpp
  src/webots/core/WbDownloadManager.hpp
  src/webots/core/WbDownloader.cpp
  src/webots/core/WbDownloader.hpp
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/nodes/WbAbstractTransform.cpp
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbBox.cpp
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbCapsule.cpp
  src/webots/nodes/WbCharger.cpp
  src/webots/nodes/WbCone.cpp
  src/webots/nodes/WbContactProperties.cpp
  src/webots/nodes/WbCylinder.cpp
  src/webots/nodes/WbElevationGrid.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbImageTexture.hpp
  src/webots/nodes/WbIndexedFaceSet.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbPbrAppearance.cpp
  src/webots/nodes/WbPbrAppearance.hpp
  src/webots/nodes/WbPlane.cpp
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSphere.cpp
  src/webots/nodes/WbTrack.cpp
  src/webots/nodes/utils/WbDownloader.cpp
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeOperations.hpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbNodeUtilities.hpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbExternProtoEditor.cpp
  src/webots/scene_tree/WbNodeEditor.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/user_commands/WbClipboard.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbParser.cpp
  src/webots/vrml/WbParser.hpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
  src/webots/vrml/WbProtoTreeItem.cpp
  src/webots/vrml/WbUrl.cpp
  src/webots/vrml/WbUrl.hpp
  src/webots/vrml/WbVrmlNodeUtilities.cpp
  src/webots/vrml/WbVrmlNodeUtilities.hpp
Labels: cleanup, test suite

#5413 Fix isTemplate flag not passed from base PROTO
  docs/reference/changelog-r2022.md
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbProtoModel.cpp
  src/webots/vrml/WbProtoModel.hpp
Labels: regression, test suite

#5415 Removed obsolete dependency
  scripts/packaging/files_msys64.txt
Labels: bug

#5412 Move FAQ to GitHub Discussions
  docs/blog/Webots-2020-a-release.md
  docs/guide/general-faq.md
  docs/guide/menu.md
  docs/guide/modeling.md
  docs/guide/programming.md
  docs/guide/speed-performance.md
  docs/guide/tutorial-3-appearance.md
  docs/guide/webots-faq.md
Labels: documentation

#5420 Update axis orientation in wrl
  resources/nodes/Capsule.wrl
  resources/nodes/Cone.wrl
  resources/nodes/Cylinder.wrl
Labels: bug, documentation

#5414 Copy icon when editing cached remote PROTO
  src/webots/Makefile
  src/webots/gui/WbMainWindow.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbAddNodeDialog.hpp
  src/webots/scene_tree/WbProtoIcon.cpp
  src/webots/scene_tree/WbProtoIcon.hpp
Labels: enhancement, test webots build

#5429 Fix js template files in files_core.txt
  scripts/packaging/files_core.txt
Labels: bug

#5432 Fix wrong .gitignore
  projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/.gitignore
Labels: cleanup

#5404 Web proto: second usecase: joints
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/ImageLoader.js
  resources/web/wwi/InformationPanel.js
  resources/web/wwi/MeshLoader.js
  resources/web/wwi/Parser.js
  resources/web/wwi/Progress.js
  resources/web/wwi/ProtoManager.js
  resources/web/wwi/Server.js
  resources/web/wwi/Stream.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/image_loader.js
  resources/web/wwi/mesh_loader.js
  resources/web/wwi/nodes/WbBaseNode.js
  resources/web/wwi/nodes/WbBillboard.js
  resources/web/wwi/nodes/WbCadShape.js
  resources/web/wwi/nodes/WbGeometry.js
  resources/web/wwi/nodes/WbHingeJoint.js
  resources/web/wwi/nodes/WbImageTexture.js
  resources/web/wwi/nodes/WbJoint.js
  resources/web/wwi/nodes/WbJointParameters.js
  resources/web/wwi/nodes/WbMesh.js
  resources/web/wwi/nodes/WbPointLight.js
  resources/web/wwi/nodes/WbShape.js
  resources/web/wwi/nodes/WbSpotLight.js
  resources/web/wwi/nodes/WbTrack.js
  resources/web/wwi/nodes/utils/WbMatrix3.js
  resources/web/wwi/nodes/utils/WbQuaternion.js
  resources/web/wwi/nodes/utils/WbVector4.js
  resources/web/wwi/nodes/utils/math_utilities.js
  resources/web/wwi/nodes/utils/math_utils.js
  resources/web/wwi/nodes/utils/node_utilities.js
  resources/web/wwi/nodes/utils/utils.js
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Parameter.js
  resources/web/wwi/protoVisualizer/Vrml.js
  resources/web/wwi/test.html
  resources/web/wwi/viewer.js
  resources/web/wwi/webots.js
Labels: enhancement

#5431 Remove robotis python library from package
  lib/controller/python/controller/supervisor.py
  projects/robots/robotis/darwin-op/libraries/Makefile
  scripts/packaging/recurse_in_projects.txt
  tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py
Labels: cleanup, test distribution, test suite

#5439 Fix Windows nightly builds
  scripts/packaging/files_msys64.txt
Labels: bug

#5436 Cleanup boolean values in shaders
  resources/wren/shaders/gtao.frag
  resources/wren/shaders/merge_spherical.frag
  resources/wren/shaders/motion_blur.frag
  resources/wren/shaders/pbr_stencil_ambient_emissive.frag
  src/webots/nodes/WbViewpoint.cpp
  src/webots/wren/WbWrenCamera.cpp
  src/webots/wren/WbWrenGtao.cpp
  src/webots/wren/WbWrenGtao.hpp
  src/webots/wren/WbWrenMotionBlur.cpp
  src/webots/wren/WbWrenMotionBlur.hpp
  src/webots/wren/WbWrenShaders.cpp
  src/wren/ShaderProgram.cpp
Labels: cleanup, test suite

#5430 Fix SFNode field flagged empty in libController
  docs/reference/changelog-r2023.md
  src/controller/c/supervisor.c
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/vrml/WbField.cpp
Labels: bug, test suite

#5443 Merge `develop` into `feature-web-proto`
  docs/reference/changelog-r2023.md
  lib/controller/python/controller/supervisor.py
  projects/default/libraries/vehicle/python/vehicle.i
  projects/robots/robotis/darwin-op/libraries/Makefile
  projects/robots/robotis/darwin-op/libraries/python/managers.i
  projects/samples/robotbenchmark/humanoid_marathon/controllers/marathon/marathon.py
  resources/wren/shaders/gtao.frag
  resources/wren/shaders/merge_spherical.frag
  resources/wren/shaders/motion_blur.frag
  resources/wren/shaders/pbr_stencil_ambient_emissive.frag
  scripts/packaging/recurse_in_projects.txt
  src/controller/c/supervisor.c
  src/webots/nodes/WbViewpoint.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/vrml/WbField.cpp
  src/webots/wren/WbWrenCamera.cpp
  src/webots/wren/WbWrenGtao.cpp
  src/webots/wren/WbWrenGtao.hpp
  src/webots/wren/WbWrenMotionBlur.cpp
  src/webots/wren/WbWrenMotionBlur.hpp
  src/webots/wren/WbWrenShaders.cpp
  src/wren/ShaderProgram.cpp
  tests/default/controllers/test_suite_supervisor/test_suite_supervisor.py
Labels: enhancement, test sources

#5448 Improved error message of empty animation
  src/webots/engine/WbAnimationRecorder.cpp
Labels: bug

#5447 Stop pending animation on close
  src/webots/engine/WbAnimationRecorder.cpp
  src/webots/gui/WbMainWindow.cpp
Labels: bug, test sources, test webots build

#5442 Improve robot window robustness to concatenated messages
  docs/reference/changelog-r2023.md
  resources/web/wwi/RobotWindow.js
Labels: bug

#5453 Fix header required for PROTO files
  docs/reference/changelog-r2023.md
  src/webots/vrml/WbTokenizer.cpp
Labels: bug

#5450 Documentation update for R2023a
  docs/guide/images/objects/animals/Cat/model.thumbnail.png
  docs/guide/images/objects/animals/Cow/model.thumbnail.png
  docs/guide/images/objects/animals/Deer/model.thumbnail.png
  docs/guide/images/objects/animals/Dog/model.thumbnail.png
  docs/guide/images/objects/animals/Fox/model.thumbnail.png
  docs/guide/images/objects/animals/Horse/model.thumbnail.png
  docs/guide/images/objects/animals/Rabbit/model.thumbnail.png
  docs/guide/images/objects/animals/Sheep/model.thumbnail.png
  docs/guide/images/objects/buildings/Barn/model.thumbnail.png
  docs/guide/images/robots/rosbot/distance_sensors.thumbnail.jpg
  docs/guide/images/robots/rosbot/model.thumbnail.png
  docs/guide/images/robots/rosbot/rosbot.wbt.thumbnail.jpg
  docs/guide/images/robots/rosbot/rosbot.wbt.thumbnail.png
  docs/guide/images/samples/inertial_unit.thumbnail.jpg
  docs/guide/images/sensors/astra.thumbnail.png
  docs/guide/images/sensors/mpu-9250.thumbnail.png
  docs/guide/images/sensors/rplidara2.thumbnail.png
  docs/guide/imu-sensors.md
  docs/guide/rosbot.md
  docs/reference/camera.md
  docs/reference/images/camera_projection_model.thumbnail.png
  docs/reference/images/spherical_and_cylindrical_camera_images.thumbnail.jpg
  projects/vehicles/worlds/boomer.wbt
Labels: documentation

#5460 Fix crash double `root to base node`
  docs/reference/changelog-r2023.md
  src/webots/scene_tree/WbSceneTree.cpp
Labels: bug, test webots build

#5461 Fix suggested project path
  src/webots/gui/WbNewProjectWizard.cpp
Labels: cleanup

#5471 Fixed missing exported function for Visual C++
  src/controller/c/Controller.def
Labels: bug

#5459 Added info regarding the name tag
  docs/reference/accelerometer.md
Labels: documentation

#5475 Merge released in master
  docs/blog/Webots-2020-a-release.md
  docs/guide/general-faq.md
  docs/guide/menu.md
  docs/guide/modeling.md
  docs/guide/programming.md
  docs/guide/speed-performance.md
  docs/guide/tutorial-3-appearance.md
  docs/guide/using-your-ide.md
  docs/guide/webots-faq.md
  docs/reference/accelerometer.md
Labels: synchronization

#5474 Update translations for the release
  resources/translations/wb_de.ts
  resources/translations/wb_es.ts
  resources/translations/wb_fr.ts
  resources/translations/wb_generic.ts
  resources/translations/wb_it.ts
  resources/translations/wb_ja_JP.ts
  resources/translations/wb_zh_CN.ts
Labels: enhancement

#5476 Merge master in develop
  docs/blog/Webots-2020-a-release.md
  docs/guide/general-faq.md
  docs/guide/menu.md
  docs/guide/modeling.md
  docs/guide/programming.md
  docs/guide/speed-performance.md
  docs/guide/tutorial-3-appearance.md
  docs/guide/using-your-ide.md
  docs/guide/webots-faq.md
  docs/reference/accelerometer.md
Labels: synchronization

#5482 Add a better error message to help debugging the problem
  src/webots/core/WbTemplateEngine.cpp
Labels: enhancement

#5484 Fixed tmp path on macOS
  src/webots/core/WbStandardPaths.cpp
Labels: bug

#5486 Fix tmp path on mac os
  src/controller/c/system.c
Labels: bug

#5483 Fix external force/torque instructions
  docs/guide/the-3d-window.md
  resources/translations/wb_de.ts
  resources/translations/wb_es.ts
  resources/translations/wb_fr.ts
  resources/translations/wb_generic.ts
  resources/translations/wb_it.ts
  resources/translations/wb_ja_JP.ts
  resources/translations/wb_zh_CN.ts
  src/webots/gui/WbMainWindow.cpp
Labels: documentation, test sources

#5487 remove path normalization + replace optparse
  projects/default/controllers/sumo_supervisor/sumo_supervisor.py
Labels: bug

#5500 Fixed Python API Node.resetPhysics
  lib/controller/python/controller/node.py
Labels: bug

#5498 Improve extern controller name
  src/webots/gui/WbNewControllerWizard.cpp
Labels: enhancement

#5495 Fix line feed character in 3D navigation instructions
  src/webots/gui/WbMainWindow.cpp
Labels: enhancement

#5488 Fix motor sound on macOS
  docs/reference/changelog-r2023.md
  src/webots/sound/WbMotorSoundManager.cpp
Labels: bug

#5504 Fix gtao shader in webotsJS
  include/wren/glsl_layout.h
  resources/web/wwi/wren/WbWrenShaders.js
  resources/wren/shaders/gtao.frag
  src/webots/wren/WbWrenShaders.cpp
  src/wren/GlslLayout.cpp
  src/wren/PostProcessingEffect.cpp
Labels: bug, test suite

#5508 Add `isInitializationPossible` to Python API
  include/controller/c/webots/vehicle/driver.h
  include/controller/cpp/webots/vehicle/Driver.hpp
  lib/controller/python/vehicle/driver.py
  projects/default/libraries/vehicle/c/driver/driver.def
  projects/default/libraries/vehicle/c/driver/src/driver.c
Labels: bug

#5512 Removed obsolete Java controller warning for non-ASCII path
  src/webots/control/WbController.cpp
Labels: cleanup

#5511 Improve the position of the viewpoint in the create.wbt
  projects/robots/irobot/create/worlds/create.wbt
Labels: enhancement

#5513 Fix dialog popup opening/closing
  src/webots/core/WbDownloadManager.cpp
Labels: bug

#5505 Fix test suite
  tests/test_suite.py
Labels: test suite

#5516 Add missing methods in Python API
  lib/controller/python/vehicle/driver.py
Labels: bug

#5372 Fix gps speed
  docs/reference/changelog-r2022.md
  docs/reference/gps.md
  src/webots/nodes/WbGps.cpp
  tests/api/controllers/gps_speed/gps_speed.c
  tests/api/worlds/gps_speed.wbt
Labels: test suite

#5517 Fix motion blur shader
  src/webots/wren/WbWrenShaders.cpp
Labels: bug, test distribution, test suite

#5518 Backport gtao fixes
  include/wren/glsl_layout.h
  resources/web/wwi/wren/WbWrenShaders.js
  resources/wren/shaders/gtao.frag
  src/webots/wren/WbWrenShaders.cpp
  src/wren/GlslLayout.cpp
  src/wren/PostProcessingEffect.cpp
Labels: bug

#5520 Cleanup after innosetup install
  scripts/install/inno_setup_installer.sh
Labels: cleanup

#5527 Merge master into develop
  docs/reference/changelog-r2022.md
  docs/reference/gps.md
  src/webots/nodes/WbGps.cpp
  tests/api/controllers/gps_speed/gps_speed.c
  tests/api/worlds/gps_speed.wbt
Labels: test suite, synchronization

#5521 Clean-up python API
  lib/controller/python/controller/accelerometer.py
  lib/controller/python/controller/altimeter.py
  lib/controller/python/controller/ansi_codes.py
  lib/controller/python/controller/brake.py
  lib/controller/python/controller/camera.py
  lib/controller/python/controller/compass.py
  lib/controller/python/controller/connector.py
  lib/controller/python/controller/constants.py
  lib/controller/python/controller/device.py
  lib/controller/python/controller/display.py
  lib/controller/python/controller/distance_sensor.py
  lib/controller/python/controller/emitter.py
  lib/controller/python/controller/field.py
  lib/controller/python/controller/gps.py
  lib/controller/python/controller/gyro.py
  lib/controller/python/controller/inertial_unit.py
  lib/controller/python/controller/joystick.py
  lib/controller/python/controller/keyboard.py
  lib/controller/python/controller/led.py
  lib/controller/python/controller/lidar.py
  lib/controller/python/controller/light_sensor.py
  lib/controller/python/controller/motion.py
  lib/controller/python/controller/motor.py
  lib/controller/python/controller/mouse.py
  lib/controller/python/controller/node.py
  lib/controller/python/controller/pen.py
  lib/controller/python/controller/position_sensor.py
  lib/controller/python/controller/radar.py
  lib/controller/python/controller/range_finder.py
  lib/controller/python/controller/receiver.py
  lib/controller/python/controller/robot.py
  lib/controller/python/controller/sensor.py
  lib/controller/python/controller/skin.py
  lib/controller/python/controller/speaker.py
  lib/controller/python/controller/supervisor.py
  lib/controller/python/controller/touch_sensor.py
  src/webots/control/WbLanguageTools.cpp
Labels: enhancement, cleanup

#5446 Add blog post R2023a
  docs/blog/Webots-2023-a-release.md
  docs/blog/images/assets_r2023a.png
  docs/blog/images/assets_r2023a.thumbnail.png
  docs/blog/images/devices_r2023a.png
  docs/blog/images/devices_r2023a.thumbnail.png
  docs/blog/images/rosbot.png
  docs/blog/images/rosbot.thumbnail.png
  docs/blog/index.md
  docs/blog/menu.md
  docs/reference/changelog-r2022.md
  docs/reference/changelog-r2023.md
Labels: documentation

#5534 Fix typo
  src/wren/Transform.hpp
Labels: cleanup

#5532 Fix adding vectors element-wise in visual_tracking.wbt
  lib/controller/python/controller/field.py
  projects/samples/robotbenchmark/visual_tracking/controllers/visual_tracking_benchmark/visual_tracking_benchmark.py
Labels: bug, regression

#5535 Fixed camera image data type
  lib/controller/python/controller/camera.py
Labels: bug

#5537 Add automatic branch synchronization
  .github/workflows/sync_develop_master.yml
Labels: enhancement

#5546 Switched to Python 3.11
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
Labels: bug

#5549 Rename branches synchronizer workflow
  .github/workflows/sync_protected_branches.yml
Labels: cleanup, test sources

#5551 Fix accessibility to view in webotsview
  resources/web/wwi/WebotsView.js
Labels: bug

#5552 Attempt to fix Windows build
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
Labels: bug

#5557 Clean-up Windows workflows
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
Labels: cleanup

#5555 Remove downscale of texture quality
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbImageTexture.hpp
Labels: bug

#5554 Fix libController path in Python API on macOS
  lib/controller/python/controller/wb.py
Labels: bug

#5545 Update the last mentions of R2022b to R2023a
  docs/guide/advanced-configuration.md
  docs/guide/generate_objects_doc.py
  docs/guide/installation-procedure.md
  docs/guide/object-advertising-board.md
  docs/guide/object-road.md
  docs/guide/object-rocks.md
  docs/guide/object-shapes.md
  docs/guide/object-solids.md
  docs/guide/object-street-furniture.md
  docs/guide/object-traffic.md
  docs/guide/setup-a-webots-project-repository.md
  docs/guide/simulation-server.md
  docs/guide/webots-cloud.md
  docs/reference/contactproperties.md
  docs/reference/linearmotor.md
  docs/reference/rotationalmotor.md
  projects/samples/howto/docker/README.md
  projects/samples/howto/docker/launcher.py
  resources/osm_importer/config.ini
  resources/osm_importer/elevation.py
  resources/osm_importer/utils/misc_utils.py
  resources/osm_importer/webots_objects/barrier.py
  resources/osm_importer/webots_objects/road.py
  resources/translations/wb_de.ts
  resources/translations/wb_es.ts
  resources/translations/wb_fr.ts
  resources/translations/wb_generic.ts
  resources/translations/wb_it.ts
  resources/translations/wb_ja_JP.ts
  resources/translations/wb_zh_CN.ts
  resources/web/wwi/viewer.js
  scripts/new_version/new_version.sh
  src/webots/vrml/WbProtoManager.cpp
Labels: documentation

#5559 Add ROSbot splash image
  resources/images/splash_images/rosbot.jpg
Labels: enhancement

#5556 Fix Python import in documentation
  docs/reference/supervisor.md
  lib/controller/python/controller/__init__.py
  lib/controller/python/controller/camera.py
Labels: documentation

#5560 Fix automatic protected branches sync
  .github/workflows/sync_protected_branches.yml
Labels: bug

#5558 Updated extern controller setup for Python
  docs/guide/running-extern-robot-controllers.md
  lib/controller/python/controller/wb.py
Labels: documentation, cleanup

#5572 Add default argument for some methods in Python API
  lib/controller/python/controller/node.py
  lib/controller/python/controller/supervisor.py
Labels: bug

#5571 `removeSF()` calls the wrong C method
  lib/controller/python/controller/field.py
Labels: bug

#5575 Fixed Field.setMF/insertMF for vectors
  lib/controller/python/controller/field.py
Labels: bug

#5578 Fix returned node
  lib/controller/python/controller/node.py
Labels: bug

#5576 Fix `SFNode` removal and string insertion
  src/controller/c/supervisor.c
Labels: bug, test suite, test sources

#5580 Add documentation line for step functions in Python
  docs/reference/robot.md
Labels: documentation

#5582 Fixed Python Supervisor API documentation
  docs/reference/supervisor.md
Labels: documentation

#5585 Fixed supervisor setLabel API function
  docs/reference/supervisor.md
  include/controller/cpp/webots/Supervisor.hpp
Labels: cleanup

#5581 Fixed OpenAI Gym sample
  docs/reference/changelog-r2023.md
  projects/samples/howto/openai_gym/controllers/openai_gym/openai_gym.py
Labels: bug

#5591 Fix Python Node.disablePoseTracking
  lib/controller/python/controller/node.py
Labels: bug

#5589 Update snap size
  docs/guide/installation-procedure.md
Labels: documentation

#5506 Rewrite gps position test
  tests/api/controllers/gps/gps.c
Labels: test suite

#5602 Merge develop in feature-web-proto
  .github/workflows/sync_protected_branches.yml
  docs/blog/Webots-2023-a-release.md
  docs/guide/running-extern-robot-controllers.md
  docs/reference/changelog-r2023.md
  docs/reference/robot.md
  docs/reference/supervisor.md
  include/controller/cpp/webots/Supervisor.hpp
  lib/controller/python/controller/__init__.py
  lib/controller/python/controller/camera.py
  lib/controller/python/controller/field.py
  lib/controller/python/controller/node.py
  lib/controller/python/controller/supervisor.py
  lib/controller/python/controller/wb.py
  projects/samples/howto/openai_gym/controllers/openai_gym/openai_gym.py
  resources/translations/wb_de.ts
  resources/translations/wb_es.ts
  resources/translations/wb_fr.ts
  resources/translations/wb_generic.ts
  resources/translations/wb_it.ts
  resources/translations/wb_ja_JP.ts
  resources/translations/wb_zh_CN.ts
  resources/web/wwi/WebotsView.js
  src/controller/c/supervisor.c
Labels: synchronization

#5605 Add libtess
  resources/web/wwi/dependencies/libtess.min.js
Labels: bug

#5603 Fixed Python supervisor setSimulationMode
  docs/reference/changelog-r2023.md
  lib/controller/python/controller/supervisor.py
Labels: bug
