Repository cyberbotics/webots, pull requests merged in 2022-08, with the labels that each got.

#4990 Fixed absolute EXTERNPROTO path
  src/webots/vrml/WbProtoManager.cpp
Labels: enhancement, cleanup

#4992 Speedup loading worlds
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: enhancement, test suite

#4988 Fixed generation of relative URLs
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/nodes/utils/WbUrl.hpp
  src/webots/scene_tree/WbExtendedStringEditor.cpp
  src/webots/scene_tree/WbExtendedStringEditor.hpp
Labels: enhancement, cleanup

#4993 Ameliorate load progress status
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/nodes/WbGroup.cpp
  src/webots/nodes/WbGroup.hpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/utils/WbWorld.cpp
Labels: test sources

#4995 Better Windows alias for atom
  scripts/install/bash_profile.windows
Labels: enhancement

#4978 Replace blind search for asset locations with context-based search and add handle same PROTO having different urls
  projects/objects/buildings/protos/StripBuilding.proto
  src/webots/control/WbController.cpp
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/gui/WbNewProjectWizard.cpp
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbContactProperties.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbImageTexture.hpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbMesh.hpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/utils/WbConcreteNodeFactory.cpp
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/nodes/utils/WbUrl.hpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbAddNodeDialog.hpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
  src/webots/scene_tree/WbNodeEditor.cpp
  src/webots/scene_tree/WbNodeEditor.hpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNodeReader.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
  src/webots/vrml/WbProtoTreeItem.cpp
  src/webots/vrml/WbProtoTreeItem.hpp
  tests/cache/worlds/textures/blue_texture.jpg
  tests/protos/worlds/textures/green.jpg
  tests/protos/worlds/textures/grey.jpg
  tests/rendering/controllers/texture_color_checker/.gitignore
  tests/rendering/controllers/texture_color_checker/Makefile
  tests/rendering/controllers/texture_color_checker/texture_color_checker.c
  tests/rendering/protos/ExposedTexture.proto
  tests/rendering/protos/InternalTexture.proto
  tests/rendering/protos/depth_2/NestedShapeWithParameter.proto
  tests/rendering/protos/depth_2/NestedShapeWithoutParameter.proto
  tests/rendering/protos/depth_2/NestedSolidWithParameter.proto
  tests/rendering/protos/depth_2/NestedSolidWithoutParameter.proto
  tests/rendering/protos/depth_2/depth_3/HighlyNestedSolid.proto
  tests/rendering/protos/depth_2/depth_3/depth_4/CustomAppearance.proto
  tests/rendering/protos/textures/blue_texture.jpg
  tests/rendering/protos/textures/cyan_texture.jpg
  tests/rendering/protos/textures/green_texture.jpg
  tests/rendering/protos/textures/red_texture.jpg
  tests/rendering/worlds/relative_asset_resolution.wbt
  tests/rendering/worlds/textures/black_texture.jpg
  tests/rendering/worlds/textures/orange_texture.jpg
  tests/rendering/worlds/textures/pink_texture.jpg
  tests/rendering/worlds/textures/yellow_texture.jpg
Labels: enhancement, test suite, test sources

#4998 Converted FlowerPot to meshes
  projects/objects/plants/protos/FlowerPot.proto
  projects/objects/plants/protos/meshes/flowers.obj
  projects/objects/plants/protos/meshes/vase.obj
Labels: enhancement

#4999 Fix turtlebot meshes
  projects/robots/robotis/turtlebot/protos/TurtleBot3Burger.proto
  projects/robots/robotis/turtlebot/protos/meshes/bars.obj
  projects/robots/robotis/turtlebot/protos/meshes/battery.obj
  projects/robots/robotis/turtlebot/protos/meshes/body_floor.obj
  projects/robots/robotis/turtlebot/protos/meshes/cards.obj
  projects/robots/robotis/turtlebot/protos/meshes/holders.obj
  projects/robots/robotis/turtlebot/protos/meshes/inner_wheel.obj
  projects/robots/robotis/turtlebot/protos/meshes/motors.obj
  projects/robots/robotis/turtlebot/protos/meshes/screws.obj
  projects/robots/robotis/turtlebot/protos/meshes/tire.obj
  projects/robots/robotis/turtlebot/protos/meshes/wheel_shape.obj
  projects/robots/robotis/turtlebot/protos/meshes/wheel_support.obj
Labels: enhancement

#5000 P-Rob3 meshes
  projects/robots/fp_robotics/p-rob3/protos/P-Grip.proto
  projects/robots/fp_robotics/p-rob3/protos/P-Rob3.proto
  projects/robots/fp_robotics/p-rob3/protos/meshes/base_link_0.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/base_link_1.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/base_link_2.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/base_link_3.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/finger.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/finger_connector_shape.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/grip_link_0.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/grip_link_1.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/grip_link_2.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_1_2_0.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_1_2_1.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_1_2_2.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_1_2_3.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_2_3_0.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_2_3_1.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_2_3_2.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_3_4_0.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_3_4_1.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_3_4_2.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_3_4_3.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_4_5_0.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_4_5_1.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_4_5_2.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_5_6_0.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_5_6_1.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_5_6_2.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/link_6_top_0.obj
  projects/robots/fp_robotics/p-rob3/protos/meshes/screw.obj
Labels: enhancement

#5001 DripStand meshes
  projects/objects/hospital/protos/DripStand.proto
  projects/objects/hospital/protos/meshes/base.obj
  projects/objects/hospital/protos/meshes/bottle.obj
  projects/objects/hospital/protos/meshes/bottle_holder.obj
  projects/objects/hospital/protos/meshes/caster_wheel.obj
  projects/objects/hospital/protos/meshes/connector.obj
  projects/objects/hospital/protos/meshes/hook.obj
  projects/objects/hospital/protos/meshes/knob.obj
  projects/objects/hospital/protos/meshes/lower_tube.obj
  projects/objects/hospital/protos/meshes/metal_plate.obj
  projects/objects/hospital/protos/meshes/top_button.obj
  projects/objects/hospital/protos/meshes/upper_tube.obj
Labels: enhancement

#5002 Curtain meshes
  projects/objects/hospital/protos/Curtain.proto
  projects/objects/hospital/protos/meshes/curtain.obj
Labels: enhancement

#5004 Minor improvement to EXTERNPROTO tooltips
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbExternProtoEditor.cpp
Labels: enhancement

#5005 Helmet mesh
  projects/samples/rendering/protos/Helmet.proto
  projects/samples/rendering/protos/meshes/helmet.obj
Labels: enhancement

#5006 Hotfix relative PROTO search
  src/webots/vrml/WbProtoManager.cpp
  tests/cache/protos/NestedProto.proto
  tests/cache/worlds/web_proto_with_relative_proto.wbt
Labels: bug, test suite, test sources

#5009 ABB IRB IndexedFaceSet to meshes
  projects/robots/abb/irb/protos/Irb4600-40.proto
  projects/robots/abb/irb/protos/Irb4600-40/meshes/base.obj
  projects/robots/abb/irb/protos/Irb4600-40/meshes/link_1.obj
  projects/robots/abb/irb/protos/Irb4600-40/meshes/link_2.obj
  projects/robots/abb/irb/protos/Irb4600-40/meshes/link_3.obj
  projects/robots/abb/irb/protos/Irb4600-40/meshes/link_4.obj
  projects/robots/abb/irb/protos/Irb4600-40/meshes/link_5.obj
  projects/robots/abb/irb/protos/Irb4600-40/meshes/link_6.obj
Labels: enhancement

#5013 Enhancement floating window layers
  resources/web/wwi/FloatingIde.js
  resources/web/wwi/FloatingRobotWindow.js
  resources/web/wwi/FloatingWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/css/toolbar.css
Labels: enhancement

#5011 Ned meshes
  projects/robots/niryo/ned/protos/Ned.proto
  projects/robots/niryo/ned/protos/meshes/arm_link_0.obj
  projects/robots/niryo/ned/protos/meshes/arm_link_1.obj
  projects/robots/niryo/ned/protos/meshes/base_gripper.obj
  projects/robots/niryo/ned/protos/meshes/base_link_0.obj
  projects/robots/niryo/ned/protos/meshes/base_link_1.obj
  projects/robots/niryo/ned/protos/meshes/base_link_2.obj
  projects/robots/niryo/ned/protos/meshes/base_link_3.obj
  projects/robots/niryo/ned/protos/meshes/base_link_4.obj
  projects/robots/niryo/ned/protos/meshes/base_link_5.obj
  projects/robots/niryo/ned/protos/meshes/elbow_link.obj
  projects/robots/niryo/ned/protos/meshes/forearm_link_0.obj
  projects/robots/niryo/ned/protos/meshes/forearm_link_1.obj
  projects/robots/niryo/ned/protos/meshes/hand_link_0.obj
  projects/robots/niryo/ned/protos/meshes/hand_link_1.obj
  projects/robots/niryo/ned/protos/meshes/jaw_1.obj
  projects/robots/niryo/ned/protos/meshes/jaw_2.obj
  projects/robots/niryo/ned/protos/meshes/shoulder_link_0.obj
  projects/robots/niryo/ned/protos/meshes/shoulder_link_1.obj
  projects/robots/niryo/ned/protos/meshes/wrist_link_0.obj
  projects/robots/niryo/ned/protos/meshes/wrist_link_1.obj
Labels: enhancement

#5010 Fix ikpy warning
  projects/robots/abb/irb/controllers/inverse_kinematics/inverse_kinematics.py
Labels: bug

#5014 Fix convert root to basenode missing declaration
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
  src/webots/vrml/WbWriter.cpp
  src/webots/vrml/WbWriter.hpp
Labels: bug, test suite, test sources

#5023 Open generated template PROTO sources in read-only mode
  docs/reference/changelog-r2022.md
  src/webots/core/WbNetwork.cpp
  src/webots/core/WbNetwork.hpp
  src/webots/core/WbStandardPaths.cpp
  src/webots/core/WbStandardPaths.hpp
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/editor/WbTextBuffer.cpp
  src/webots/editor/WbTextEditor.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbContactProperties.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoModel.cpp
  src/webots/vrml/WbProtoTreeItem.cpp
  src/webots/vrml/WbTokenizer.cpp
  src/webots/vrml/WbTokenizer.hpp
Labels: enhancement, test suite, test sources

#5027 Cleanup not used function arguments
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbAddNodeDialog.hpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: cleanup, test webots build

#5025 Remove PROTO nodes copy in test suite
  scripts/packaging/generic_distro.py
  tests/api/protos/.gitignore
  tests/cache/protos/.gitignore
  tests/other_api/protos/.gitignore
  tests/parser/protos/.gitignore
  tests/physics/protos/.gitignore
  tests/protos/protos/.gitignore
  tests/rendering/protos/.gitignore
  tests/test_suite.py
  tests/with_rendering/protos/.gitignore
Labels: cleanup, test suite

#5017 ros controller argument "--robot-description" bug fix
  projects/default/controllers/ros/Ros.cpp
Labels: bug

#5029 Fixed Qt plugins path on Windows
  src/webots/gui/main.cpp
Labels: bug

#5016 Robotino meshes
  projects/robots/festo/robotino3/protos/Robotino3.proto
  projects/robots/festo/robotino3/protos/meshes/base_black_rubber.obj
  projects/robots/festo/robotino3/protos/meshes/base_bottom_support.obj
  projects/robots/festo/robotino3/protos/meshes/base_extension_plate.obj
  projects/robots/festo/robotino3/protos/meshes/base_ir_metal_ring.obj
  projects/robots/festo/robotino3/protos/meshes/base_ir_metal_ring_cover.obj
  projects/robots/festo/robotino3/protos/meshes/base_metal_half_ring.obj
  projects/robots/festo/robotino3/protos/meshes/base_metal_inner_separator.obj
  projects/robots/festo/robotino3/protos/meshes/base_metal_side_separator_2.obj
  projects/robots/festo/robotino3/protos/meshes/base_metal_top_separator.obj
  projects/robots/festo/robotino3/protos/meshes/cap_0.obj
  projects/robots/festo/robotino3/protos/meshes/cap_1.obj
  projects/robots/festo/robotino3/protos/meshes/cap_2.obj
  projects/robots/festo/robotino3/protos/meshes/head_bottom_support.obj
  projects/robots/festo/robotino3/protos/meshes/head_button.obj
  projects/robots/festo/robotino3/protos/meshes/head_button_light.obj
  projects/robots/festo/robotino3/protos/meshes/head_extension_plate.obj
  projects/robots/festo/robotino3/protos/meshes/head_festo_logo.obj
  projects/robots/festo/robotino3/protos/meshes/head_handle.obj
  projects/robots/festo/robotino3/protos/meshes/head_left_metal_cover.obj
  projects/robots/festo/robotino3/protos/meshes/head_right_metal_cover.obj
  projects/robots/festo/robotino3/protos/meshes/head_vga_port.obj
  projects/robots/festo/robotino3/protos/meshes/side_sep.obj
  projects/robots/festo/robotino3/protos/meshes/wheel_cover.obj
Labels: enhancement

#5035 Robotis LDS-01 meshes
  projects/devices/robotis/protos/RobotisLds01.proto
  projects/devices/robotis/protos/meshes/base.obj
  projects/devices/robotis/protos/meshes/belt.obj
  projects/devices/robotis/protos/meshes/turret.obj
  projects/devices/robotis/protos/meshes/wheel.obj
Labels: enhancement

#5037 Tiago arms to meshes
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoFrontArm.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoLeftArm.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightArm.proto
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/arm_1_sh1.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/arm_1_sh2.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/arm_1_sh3.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/arm_2_sh1.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/arm_3_sh1.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/arm_3_sh2.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/arm_3_sh3.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/arm_4_sh1.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/arm_4_sh2.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/arm_4_sh3.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/arm_5_sh1.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/arm_6_sh1.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/arm_7_sh1.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/shoulder.obj
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/wrist_connector.obj
Labels: enhancement

#5039 Bed meshes
  projects/objects/bedroom/protos/Bed.proto
  projects/objects/bedroom/protos/Bed/meshes/back_pillows.obj
  projects/objects/bedroom/protos/Bed/meshes/blanket.obj
  projects/objects/bedroom/protos/Bed/meshes/frame.obj
  projects/objects/bedroom/protos/Bed/meshes/front_pillows.obj
  projects/objects/bedroom/protos/Bed/meshes/mattress.obj
  projects/objects/bedroom/protos/Bed/meshes/screws.obj
  projects/objects/bedroom/protos/Bed/textures/duvet.jpg
  projects/objects/bedroom/protos/PhotoFrame.proto
  projects/objects/bedroom/protos/PhotoFrame/textures/child_picture.jpg
Labels: enhancement

#5042 I3 fix
  src/webots/launcher/webots-linux.sh
Labels: bug

#5041 Update Makefile
  Makefile
Labels: cleanup

#5046 Style webotsJS
  resources/web/wwi/FloatingRobotWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/Progress.js
  resources/web/wwi/Server.js
  resources/web/wwi/Stream.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/nodes/WbViewpoint.js
Labels: cleanup

#5047 Fix loading mjpeg
  resources/web/wwi/Progress.js
  resources/web/wwi/Toolbar.js
Labels: bug

#5048 Improved the output of the Makefile
  resources/Makefile.include
  scripts/packaging/generate_proto_list.py
Labels: enhancement

#5043 Fix high DPI scaling bug on i3 window manager (Linux)
  src/webots/launcher/webots-linux.sh
Labels: bug

#5050 Add globals to eslintrc
  .eslintrc.json
Labels: cleanup

#5040 Fixed Fanatec steering wheel mesh
  projects/vehicles/protos/abstract/CarSteeringWheel.proto
  projects/vehicles/protos/abstract/CarSteeringWheel/textures/car_steering_wheel_metal_base_color.jpg
  projects/vehicles/protos/abstract/CarSteeringWheel/textures/car_steering_wheel_metal_metalness.jpg
  projects/vehicles/protos/abstract/CarSteeringWheel/textures/car_steering_wheel_metal_normal.jpg
  projects/vehicles/protos/abstract/CarSteeringWheel/textures/car_steering_wheel_metal_roughness.jpg
  projects/vehicles/protos/abstract/FanatecCslEliteSteeringWheel.proto
  projects/vehicles/protos/abstract/FanatecCslEliteSteeringWheel/meshes/buttons.obj
  projects/vehicles/protos/abstract/FanatecCslEliteSteeringWheel/meshes/center_front.obj
  projects/vehicles/protos/abstract/FanatecCslEliteSteeringWheel/meshes/center_rear.obj
  projects/vehicles/protos/abstract/FanatecCslEliteSteeringWheel/meshes/led.obj
  projects/vehicles/protos/abstract/FanatecCslEliteSteeringWheel/meshes/plastic.obj
  projects/vehicles/protos/abstract/FanatecCslEliteSteeringWheel/meshes/wheel.obj
  projects/vehicles/protos/abstract/FanatecCslEliteSteeringWheel/textures/fanatec_csl_elite_steering_wheel.jpg
  projects/vehicles/protos/abstract/GenericTireAppearance.proto
  projects/vehicles/protos/abstract/GenericTireAppearance/textures/tire_texture_base_color.jpg
  projects/vehicles/protos/abstract/GenericTireAppearance/textures/tire_texture_normal.jpg
  projects/vehicles/protos/abstract/GenericTireAppearance/textures/tire_texture_occlusion.jpg
  projects/vehicles/protos/abstract/GenericTireAppearance/textures/tire_texture_roughness.jpg
  projects/vehicles/protos/abstract/textures/rim_texture.jpg
Labels: enhancement

#5033 Fix EXTERNPROTO backward compatibility script on Windows
  scripts/converter/declare_externproto.py
Labels: bug

#5052 Update broken link in webots cloud documentation
  docs/guide/webots-cloud.md
Labels: documentation

#5055 Fix condition on high DPI detection in Linux launcher
  src/webots/launcher/webots-linux.sh
Labels: bug

#5049 Exclusive IMPORTABLE list check for supervisor imported nodes
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeOperations.hpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: bug

#5053 Add a paragraph about the simulation examples repository in the doc
  docs/guide/webots-cloud.md
Labels: documentation

#5051 Fixed local and webots URLs for proto editing
  src/webots/gui/WbImportWizard.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbAddNodeDialog.hpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: bug, test suite

#5059 Fix assertion crash when importing some PROTOs with supervisor
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeOperations.hpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: bug, crash

#5057 Improve new IMPORTABLE EXTERNPROTO dialog
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbAddNodeDialog.hpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
Labels: enhancement

#5065 Grey out share button when not available
  src/webots/gui/WbMainWindow.cpp
Labels: enhancement

#5067 Eslintrc: add missing variable
  .eslintrc.json
Labels: cleanup

#5015 Fix streaming of simulations with relatively defined assets
  resources/web/wwi/Parser.js
  resources/web/wwi/image_loader.js
  resources/web/wwi/nodes/WbCadShape.js
  src/webots/gui/WbTcpServer.cpp
  src/webots/gui/WbX3dStreamingServer.cpp
  src/webots/gui/WbX3dStreamingServer.hpp
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbImageTexture.hpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/nodes/utils/WbUrl.hpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbField.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoTreeItem.cpp
  src/webots/vrml/WbWriter.hpp
Labels: bug, test suite

#5068 Fix warning missing icon
  resources/images/missing_proto_icon.png
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/nodes/utils/WbUrl.hpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
Labels: cleanup

#5069 Fix PROTO wizard wrong or missing declarations
  src/webots/gui/WbNewProtoWizard.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: bug, test sources

#5073 Remove IMPORTABLE assertion in findModel
  src/webots/vrml/WbProtoManager.cpp
Labels: bug

#5030 Tiago base IndexedFaceSet to meshes
  projects/robots/pal_robotics/tiago_base/protos/TiagoBase.proto
  projects/robots/pal_robotics/tiago_base/protos/meshes/antenna_shape.obj
  projects/robots/pal_robotics/tiago_base/protos/meshes/base.obj
  projects/robots/pal_robotics/tiago_base/protos/meshes/bumper_shape.obj
  projects/robots/pal_robotics/tiago_base/protos/meshes/caster_support.obj
  projects/robots/pal_robotics/tiago_base/protos/meshes/rim.obj
  projects/robots/pal_robotics/tiago_base/protos/meshes/small_wheel_shape.obj
  projects/robots/pal_robotics/tiago_base/protos/meshes/tire.obj
Labels: enhancement

#5074 Regenerate Tiago web component
  docs/guide/scenes/tiago-base/tiago-base.meta.json
  docs/guide/scenes/tiago-base/tiago-base.x3d
  docs/guide/scenes/tiago-iron/tiago-iron.meta.json
  docs/guide/scenes/tiago-iron/tiago-iron.x3d
  docs/guide/scenes/tiago-steel/tiago-steel.meta.json
  docs/guide/scenes/tiago-steel/tiago-steel.x3d
  docs/guide/scenes/tiago-titanium/tiago-titanium.meta.json
  docs/guide/scenes/tiago-titanium/tiago-titanium.x3d
  docs/guide/scenes/tiagopp/tiagopp.meta.json
  docs/guide/scenes/tiagopp/tiagopp.x3d
Labels: documentation, cleanup

#5070 Fix incomplete proto wizard generation
  src/webots/vrml/WbProtoManager.cpp
Labels: bug, test sources

#5062 Set parenthood in shallow nodes
  src/webots/nodes/WbAbstractAppearance.cpp
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbBaseNode.hpp
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbPbrAppearance.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
Labels: bug, test suite, test sources

#5064 Fix crash on reset due to dictionary update
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/WbBaseNode.hpp
  src/webots/nodes/WbGeometry.cpp
  src/webots/nodes/WbGeometry.hpp
  src/webots/nodes/utils/WbDictionary.cpp
  src/webots/wren/WbWrenAbstractManipulator.cpp
Labels: crash, test suite

#5032 Add declaration to session after modifying a default PROTO parameter
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeOperations.hpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbNodeUtilities.hpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbNodeEditor.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
  src/webots/vrml/WbProtoTreeItem.hpp
Labels: bug, test suite

#5075 Move Wizard menu in File/New menu
  docs/blog/Webots-2022-b-release.md
  docs/guide/images/main_window.png
  docs/guide/images/main_window.thumbnail.jpg
  docs/guide/images/streaming-server-screenshot.png
  docs/guide/images/streaming-server-screenshot.thumbnail.jpg
  docs/guide/images/tutorial_8_environment.png
  docs/guide/images/tutorial_8_environment.thumbnail.jpg
  docs/guide/modeling.md
  docs/guide/programming.md
  docs/guide/the-standard-file-hierarchy-of-a-project.md
  docs/guide/the-user-interface.md
  docs/guide/tutorial-1-your-first-simulation-in-webots.md
  docs/guide/tutorial-4-more-about-controllers.md
  docs/guide/tutorial-8-the-supervisor.md
  docs/guide/using-your-ide.md
  docs/reference/changelog-r2022.md
  docs/reference/compiling-the-physics-plugin.md
  src/webots/Makefile
  src/webots/app/WbApplication.cpp
  src/webots/app/WbApplication.hpp
  src/webots/core/WbAction.hpp
  src/webots/core/WbProject.cpp
  src/webots/core/WbProject.hpp
  src/webots/core/WbStandardPaths.cpp
  src/webots/core/WbStandardPaths.hpp
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/editor/WbProjectRelocationDialog.hpp
  src/webots/gui/WbGuiApplication.cpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/gui/WbNewControllerWizard.cpp
  src/webots/gui/WbNewPhysicsPluginWizard.cpp
  src/webots/gui/WbNewProjectWizard.cpp
  src/webots/gui/WbNewProjectWizard.hpp
  src/webots/gui/WbNewProtoWizard.cpp
  src/webots/gui/WbNewWorldWizard.cpp
  src/webots/gui/WbNewWorldWizard.hpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/nodes/utils/WbWorld.hpp
  src/webots/user_commands/WbActionManager.cpp
  src/webots/user_commands/WbActionManager.hpp
Labels: bug, cleanup

#5098 Cleanup #5091 code
  src/webots/gui/WbMainWindow.cpp
Labels: cleanup, test sources

#5097 Fix executing color edit dialog when running in fast mode
  docs/reference/changelog-r2022.md
  src/webots/scene_tree/WbColorEditor.cpp
Labels: bug, test webots build

#5099 Silence false GCC 12.2.0 warning
  src/webots/nodes/WbConnector.cpp
Labels: cleanup

#5100 Merge released in master
  docs/discord/development-2020.md
  docs/discord/development-2021.md
  docs/discord/development-2022.md
  docs/discord/documentation.md
  docs/discord/news.md
  docs/discord/technical-questions-2020.md
  docs/discord/technical-questions-2021.md
  docs/discord/technical-questions-2022.md
Labels: synchronization

#5093 Feature camera info publisher
  projects/default/controllers/ros/RosCamera.cpp
  projects/default/controllers/ros/RosCamera.hpp
  projects/default/controllers/ros/RosRangeFinder.cpp
  projects/default/controllers/ros/RosRangeFinder.hpp
Labels: enhancement

#5106 Fix tiago++ right arm shoulder
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightArm.proto
Labels: bug

#5108 Converted Lua protos to JavaScript
  projects/objects/chairs/protos/OfficeChair.proto
  projects/objects/lights/protos/CeilingSpotLight.proto
  projects/objects/lights/protos/ConstructionLamp.proto
  projects/robots/nvidia/jetbot/protos/JetBot.proto
Labels: cleanup

#5112 Fix jetbot without chassis
  projects/robots/nvidia/jetbot/protos/JetBot.proto
Labels: bug, cleanup

#5107 Cleanup `WbNetwork` to a singleton class
  src/webots/core/WbNetwork.cpp
  src/webots/core/WbNetwork.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbContactProperties.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbSkin.cpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoModel.cpp
  src/webots/vrml/WbProtoTreeItem.cpp
Labels: cleanup

#5109 Fix the switching of worlds in webotsJS
  src/webots/gui/WbTcpServer.cpp
Labels: bug

#5113 Fix additional mesh loading
  src/webots/nodes/WbMesh.cpp
Labels: bug, cleanup

#5117 Load meshes only once
  src/webots/nodes/WbTriangleMeshGeometry.cpp
Labels: question, cleanup, test suite

#5103 Fixed running Webots in UTF-8 path
  dependencies/Makefile.windows
  docs/reference/changelog-r2022.md
  src/webots/gui/main.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/utils/WbDisplayFont.cpp
  src/webots/nodes/utils/WbDisplayFont.hpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbProtoModel.cpp
  src/webots/vrml/WbProtoModel.hpp
  src/wren/FileImport.cpp
  src/wren/Font.cpp
  src/wren/Font.hpp
  src/wren/ShaderProgram.cpp
Labels: bug

#5116 Fix URL format when converting to base node
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/nodes/utils/WbUrl.hpp
Labels: bug

#5121 Removed unused method in WbProtoManager class
  src/webots/vrml/WbProtoManager.cpp
  src/webots/vrml/WbProtoManager.hpp
Labels: cleanup

#5087 Merge worlds warning and worlds update tests in single test
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  projects/samples/robotbenchmark/visual_tracking/worlds/visual_tracking.wbt
  scripts/packaging/update_all_worlds.py
  tests/test_worlds.py
Labels: enhancement

#5080 Fix resizing geometries and rescaling transform objects
  docs/reference/changelog-r2022.md
  src/webots/app/WbPhysicsVectorRepresentation.cpp
  src/webots/gui/WbDragResizeEvent.cpp
  src/webots/gui/WbDragTransformEvent.cpp
  src/webots/gui/WbDragTransformEvent.hpp
  src/webots/nodes/WbAbstractTransform.cpp
  src/webots/nodes/WbAbstractTransform.hpp
  src/webots/nodes/WbBox.cpp
  src/webots/nodes/WbCapsule.cpp
  src/webots/nodes/WbCone.cpp
  src/webots/nodes/WbCylinder.cpp
  src/webots/nodes/WbElevationGrid.cpp
  src/webots/nodes/WbGeometry.cpp
  src/webots/nodes/WbGeometry.hpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbPlane.cpp
  src/webots/nodes/WbSphere.cpp
  src/webots/nodes/WbTriangleMeshGeometry.cpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/nodes/WbViewpoint.hpp
  src/webots/scene_tree/WbNodeEditor.cpp
  src/webots/wren/WbTranslateRotateManipulator.cpp
  src/webots/wren/WbWrenAbstractResizeManipulator.cpp
  src/webots/wren/WbWrenAbstractResizeManipulator.hpp
Labels: bug, test suite

#5129 Print postponed log messages when load is cancelled
  src/webots/app/WbApplication.cpp
Labels: bug, regression, test webots build

#5130 Display progress while loading world tokens
  src/webots/app/WbApplication.cpp
  src/webots/vrml/WbParser.cpp
Labels: enhancement

#5136 Fix urls that are send to webotsJS with a space
  src/webots/gui/WbX3dStreamingServer.cpp
Labels: bug

#5133 Fix apply skyColor to appearance on background updates
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbBackground.hpp
Labels: bug

#5134 Fix conversion to `<generic>` and warn user
  src/webots/gui/WbMainWindow.cpp
  src/webots/nodes/WbRobot.cpp
Labels: bug, enhancement

#5140 Fix supervisor import robot node test
  tests/api/controllers/supervisor_import_robot_node/supervisor_import_robot_node.c
  tests/api/worlds/supervisor_import_robot_node.wbt
Labels: bug

#5139 Sanitize PBR fields at creation
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbPbrAppearance.cpp
  src/webots/nodes/WbPbrAppearance.hpp
Labels: bug

#5142 Fix crash transparency
  src/webots/vrml/WbNode.cpp
Labels: crash, test suite

#5132 Improve warning for missing resources with absolute path display
  docs/reference/changelog-r2022.md
  src/webots/nodes/WbBackground.cpp
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbContactProperties.cpp
  src/webots/nodes/WbImageTexture.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/utils/WbUrl.cpp
  src/webots/nodes/utils/WbUrl.hpp
  src/webots/sound/WbSoundEngine.cpp
  src/webots/wren/WbWrenCamera.cpp
Labels: bug, enhancement, test sources

#5147 Fix relative url relocation
  src/webots/editor/WbProjectRelocationDialog.cpp
  src/webots/editor/WbProjectRelocationDialog.hpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/nodes/utils/WbWorld.hpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
Labels: bug, test sources

#5151 Fix Importable EXTERNPROTO panel size
  src/webots/scene_tree/WbExternProtoEditor.cpp
  src/webots/scene_tree/WbExternProtoEditor.hpp
  src/webots/scene_tree/WbFieldEditor.cpp
  src/webots/scene_tree/WbFieldEditor.hpp
  src/webots/vrml/WbProtoManager.cpp
Labels: bug, test sources
