Repository cyberbotics/webots, pull requests merged in 2023-01, with the labels that each got.

#5704 Documented units for spring and damping constants
  docs/reference/jointparameters.md
Labels: documentation

#5705 Fixed crash in Python API when using several cameras with different resolutions
  docs/reference/changelog-r2023.md
  lib/controller/python/controller/camera.py
Labels: crash

#5709 Fix `openai_gym` instructions
  projects/samples/howto/openai_gym/controllers/openai_gym/openai_gym.py
Labels: bug

#5710 Merge develop into feature web proto
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  docs/guide/images/rosetta_setting.png
  docs/guide/installation-procedure.md
  docs/guide/tutorial-7-your-first-proto.md
  docs/reference/changelog-r2023.md
  docs/reference/jointparameters.md
  lib/controller/python/controller/camera.py
  scripts/packaging/sync_controller_lib.sh
  src/webots/nodes/WbGeometry.cpp
Labels: synchronization

#5694 Add coupled motors in proto's gripper
  docs/guide/scenes/ScaraT6/ScaraT6.x3d
  docs/guide/scenes/ipr/ipr.meta.json
  docs/guide/scenes/nao/nao.meta.json
  docs/guide/scenes/nao/nao.x3d
  docs/guide/scenes/ned/ned.meta.json
  docs/guide/scenes/p-rob3/p-rob3.meta.json
  docs/guide/scenes/panda/panda.meta.json
  docs/guide/scenes/portal/portal.meta.json
  docs/guide/scenes/pr2/pr2.meta.json
  docs/guide/scenes/puma/puma.meta.json
  docs/guide/scenes/tiago-steel/tiago-steel.meta.json
  docs/guide/scenes/tiagopp/tiagopp.meta.json
  docs/guide/scenes/youbot/youbot.meta.json
  docs/guide/scenes/youbot/youbot.x3d
  docs/reference/changelog-r2023.md
  projects/robots/a4/portal/controllers/portal_pe/portal_pe.c
  projects/robots/a4/portal/protos/Portal.proto
  projects/robots/clearpath/pr2/controllers/pr2_demo/pr2_demo.c
  projects/robots/clearpath/pr2/protos/Pr2.proto
  projects/robots/fp_robotics/p-rob3/controllers/p-rob3/p-rob3.c
  projects/robots/fp_robotics/p-rob3/protos/P-Grip.proto
  projects/robots/franka_emika/panda/controllers/panda_arm_demo/panda_arm_demo.c
  projects/robots/franka_emika/panda/protos/PandaHand.proto
  projects/robots/k-team/khepera3/controllers/khepera3_gripper/khepera3_gripper.c
  projects/robots/k-team/khepera3/protos/Khepera3_Gripper.proto
  projects/robots/kuka/youbot/libraries/youbot_control/src/gripper.c
  projects/robots/kuka/youbot/protos/Youbot.proto
  projects/robots/neuronics/ipr/controllers/ipr1_collaboration/ipr1_collaboration.cpp
  projects/robots/neuronics/ipr/controllers/ipr2_collaboration/ipr2_collaboration.cpp
  projects/robots/neuronics/ipr/controllers/ipr_factory/ipr_factory.cpp
  projects/robots/neuronics/ipr/libraries/ipr/IPR.cpp
  projects/robots/neuronics/ipr/libraries/ipr/IPR.hpp
  projects/robots/neuronics/ipr/protos/IprHd6m180.proto
  projects/robots/neuronics/ipr/protos/IprHd6m90.proto
  projects/robots/neuronics/ipr/protos/IprHd6ms180.proto
  projects/robots/neuronics/ipr/protos/IprHd6ms90.proto
  projects/robots/niryo/ned/controllers/ned/ned.c
  projects/robots/niryo/ned/controllers/ned_python/ned_python.py
  projects/robots/niryo/ned/protos/Ned.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoGripper.proto
  projects/robots/unimation/puma/protos/Puma560.proto
  projects/samples/robotbenchmark/pick_and_place/controllers/pick_and_place/pick_and_place.py
  tests/api/controllers/robot_urdf/prob3_reference.urdf
  tests/api/controllers/robot_urdf/tiago_reference.urdf
Labels: enhancement

#5711 Support coupled motors on slider update
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/nodes/WbHingeJoint.js
  resources/web/wwi/test.html
Labels: enhancement

#5435 Add support for SFNode editing in Web PROTO
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/FloatingWindow.js
  resources/web/wwi/InformationPanel.js
  resources/web/wwi/NodeSelectorWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/Progress.js
  resources/web/wwi/ProtoManager.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/nodes/WbBackground.js
  resources/web/wwi/nodes/WbBaseNode.js
  resources/web/wwi/nodes/WbCadShape.js
  resources/web/wwi/nodes/WbFog.js
  resources/web/wwi/nodes/WbGeometry.js
  resources/web/wwi/nodes/WbGroup.js
  resources/web/wwi/nodes/WbImageTexture.js
  resources/web/wwi/nodes/WbLight.js
  resources/web/wwi/nodes/WbPbrAppearance.js
  resources/web/wwi/nodes/WbShape.js
  resources/web/wwi/nodes/WbTransform.js
  resources/web/wwi/nodes/WbWorld.js
  resources/web/wwi/nodes/utils/utils.js
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Parameter.js
  resources/web/wwi/protoVisualizer/Vrml.js
  resources/web/wwi/protoVisualizer/temporary-proto-list.xml
  resources/web/wwi/protos/CustomCopper.proto
  resources/web/wwi/protos/TestProto.proto
  resources/web/wwi/test.html
  resources/web/wwi/viewer.js
  resources/web/wwi/webots.js
  src/controller/python/controller.i
Labels: enhancement

#5722 Fix Fabtino wheel orientation
  projects/robots/rec/fabtino/protos/Fabtino.proto
Labels: bug

#5716 Fix race condition when testing node removal.
  tests/api/controllers/supervisor_import_remove/supervisor_import_remove.c
  tests/api/controllers/supervisor_notify_import_remove_mfnode/supervisor_notify_import_remove_mfnode.c
Labels: test suite

#5715 Fix error when running individual tests.
  tests/test_suite.py
Labels: test suite

#5720 Add support for field restrictions to web proto
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/NodeSelectorWindow.js
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Parameter.js
  resources/web/wwi/protoVisualizer/Token.js
  resources/web/wwi/protoVisualizer/Vrml.js
  resources/web/wwi/protos/TestRestrictions.proto
  resources/web/wwi/test.html
Labels: feature

#5721 Cleanup parameters
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/test.html
Labels: cleanup

#5718 Web proto viewer: add support for missing parameters type
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Vrml.js
  resources/web/wwi/protos/ProtoCylinder.proto
  resources/web/wwi/protos/ProtoMf.proto
  resources/web/wwi/test.html
Labels: enhancement

#5726 Keep track of selected node pane tab
  docs/reference/changelog-r2023.md
  src/webots/scene_tree/WbNodePane.cpp
  src/webots/scene_tree/WbNodePane.hpp
Labels: enhancement, test suite

#5728 Add support for MFNode in web proto
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/NodeSelectorWindow.js
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/images/icons/clear.svg
  resources/web/wwi/protoVisualizer/Parameter.js
  resources/web/wwi/protoVisualizer/Vrml.js
  resources/web/wwi/protos/TestProto.proto
  resources/web/wwi/test.html
Labels: feature

#5730 Handle blank field
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/test.html
Labels: bug

#5727 Cleanup WbObjectDetection class
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbCamera.hpp
  src/webots/nodes/WbRadar.cpp
  src/webots/nodes/WbRadar.hpp
  src/webots/nodes/utils/WbObjectDetection.cpp
  src/webots/nodes/utils/WbObjectDetection.hpp
Labels: cleanup, test suite

#5731 Enhancement sphere for appearances
  resources/web/wwi/ProtoManager.js
  resources/web/wwi/protoVisualizer/Parameter.js
  resources/web/wwi/test.html
Labels: enhancement

#5732 Fix informationPanel in mjpeg
  resources/web/wwi/InformationPanel.js
Labels: bug

#5733 Fix notification after regeneration
  resources/web/wwi/X3dScene.js
  resources/web/wwi/nodes/WbBaseNode.js
Labels: bug

#5735 Fix transparency in webotsjs
  resources/web/wwi/ImageLoader.js
  resources/web/wwi/Parser.js
  resources/web/wwi/nodes/WbCadShape.js
  resources/web/wwi/nodes/WbImageTexture.js
  resources/web/wwi/test.html
  resources/web/wwi/viewer.js
  src/webots/nodes/WbImageTexture.cpp
Labels: bug

#5736 Make installation scripts more robust
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/linux_runtime_dependencies.sh
  scripts/install/linux_test_dependencies.sh
  scripts/install/linux_web_viewer_dependencies.sh
Labels: test distribution

#5741 Merge master in develop
  docs/reference/rangefinder.md
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/linux_runtime_dependencies.sh
  scripts/install/linux_test_dependencies.sh
  scripts/install/linux_web_viewer_dependencies.sh
Labels: synchronization

#5734 Add documentation to webots.cloud
  projects/appearances/webots.yaml
  projects/devices/generic/webots.yaml
  projects/robots/pal_robotics/tiago_base/webots.yaml
  projects/robots/pal_robotics/tiago_iron/webots.yaml
  projects/robots/softbank/nao/protos/Nao.proto
  projects/robots/softbank/nao/protos/docs/images/nao/nao_challenge.wbt.png
  projects/robots/softbank/nao/protos/docs/images/nao/nao_challenge.wbt.thumbnail.jpg
  projects/robots/softbank/nao/protos/docs/images/nao/nao_demo.wbt.png
  projects/robots/softbank/nao/protos/docs/images/nao/nao_demo.wbt.thumbnail.jpg
  projects/robots/softbank/nao/protos/docs/images/nao/nao_get_the_candies.wbt.png
  projects/robots/softbank/nao/protos/docs/images/nao/nao_get_the_candies.wbt.thumbnail.jpg
  projects/robots/softbank/nao/protos/docs/images/nao/nao_indoors.wbt.png
  projects/robots/softbank/nao/protos/docs/images/nao/nao_indoors.wbt.thumbnail.jpg
  projects/robots/softbank/nao/protos/docs/images/nao/nao_robocup.wbt.png
  projects/robots/softbank/nao/protos/docs/images/nao/nao_robocup.wbt.thumbnail.jpg
  projects/robots/softbank/nao/protos/docs/images/nao/nao_vs_robotis-op2.wbt.png
  projects/robots/softbank/nao/protos/docs/images/nao/nao_vs_robotis-op2.wbt.thumbnail.jpg
  projects/robots/softbank/nao/protos/docs/nao.md
  projects/robots/softbank/nao/webots.yaml
  resources/web/wwi/ProtoManager.js
  resources/web/wwi/css/toolbar.css
  resources/web/wwi/proto_viewer.js
  resources/web/wwi/viewer.js
  scripts/packaging/generate_asset_cache.py
  scripts/web_component_studio/components.json
  tests/sources/test_textures.py
Labels: enhancement, documentation

#5749 Enhancement get rid of proto list for webotsjs
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/NodeSelectorWindow.js
  resources/web/wwi/protoVisualizer/temporary-proto-list.xml
  resources/web/wwi/protos/TestProto.proto
  resources/web/wwi/test.html
Labels: enhancement

#5751 Fix devices scale
  resources/web/wwi/ProtoManager.js
  resources/web/wwi/nodes/WbDevice.js
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Parameter.js
  resources/web/wwi/protoVisualizer/Vrml.js
Labels: bug

#5750 Cleanup web proto viewer
  resources/web/wwi/Animation.js
  resources/web/wwi/Parser.js
  resources/web/wwi/ProtoManager.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/nodes/WbDevice.js
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Parameter.js
  resources/web/wwi/protoVisualizer/TemplateEngine.js
  resources/web/wwi/protoVisualizer/Vrml.js
  resources/web/wwi/protoVisualizer/test_proto_viewer.html
  resources/web/wwi/protos/CustomCopper.proto
  resources/web/wwi/protos/DemoFieldChange.proto
  resources/web/wwi/protos/DemoRegeneration.proto
  resources/web/wwi/protos/MyTrafficLightBigPole.proto
  resources/web/wwi/protos/ProtoAppearance.proto
  resources/web/wwi/protos/ProtoBallJoint.proto
  resources/web/wwi/protos/ProtoBox.proto
  resources/web/wwi/protos/ProtoCamera.proto
  resources/web/wwi/protos/ProtoCapsule.proto
  resources/web/wwi/protos/ProtoCone.proto
  resources/web/wwi/protos/ProtoCoupled.proto
  resources/web/wwi/protos/ProtoElevationGrid.proto
  resources/web/wwi/protos/ProtoGeom.proto
  resources/web/wwi/protos/ProtoHinge.proto
  resources/web/wwi/protos/ProtoHinge2.proto
  resources/web/wwi/protos/ProtoIfs.proto
  resources/web/wwi/protos/ProtoMesh.proto
  resources/web/wwi/protos/ProtoMf.proto
  resources/web/wwi/protos/ProtoPBRAppearance.proto
  resources/web/wwi/protos/ProtoPlane.proto
  resources/web/wwi/protos/ProtoPointSet.proto
  resources/web/wwi/protos/ProtoPropeller.proto
  resources/web/wwi/protos/ProtoSensor.proto
  resources/web/wwi/protos/ProtoSolidDevice.proto
  resources/web/wwi/protos/ProtoSphere.proto
  resources/web/wwi/protos/ProtoTrack.proto
  resources/web/wwi/protos/SubRegeneration.proto
  resources/web/wwi/protos/TestProto.proto
  resources/web/wwi/protos/TestRestrictions.proto
  resources/web/wwi/protos/meshes/flowers.obj
  resources/web/wwi/protos/meshes/suzanne.obj
  resources/web/wwi/protos/meshes/vase.obj
  resources/web/wwi/protos/textures/apple.jpg
  resources/web/wwi/test.html
  src/webots/engine/WbAnimationRecorder.cpp
  src/webots/nodes/WbPbrAppearance.cpp
Labels: cleanup

#5744 Use pycodestyle instead of pep8
  docs/README.md
  docs/tests/requirements.txt
  docs/tests/test_pep8.py
  lib/controller/python/controller/__init__.py
  lib/controller/python/controller/camera.py
  lib/controller/python/vehicle/__init__.py
  projects/default/controllers/ros/headersGenerator.py
  projects/default/controllers/sumo_supervisor/SumoSupervisor.py
  projects/default/controllers/sumo_supervisor/WebotsVehicle.py
  projects/robots/epson/scara_t6/controllers/scara/scara.py
  projects/robots/epson/scara_t6/controllers/scara_food_industry/scara_food_industry.py
  projects/robots/niryo/ned/controllers/ned_python/ned_python.py
  projects/samples/robotbenchmark/highway_driving/controllers/highway_driving_benchmark/highway_driving_benchmark.py
  projects/vehicles/controllers/highway_overtake/highway_overtake.py
  resources/osm_importer/parser_objects.py
  resources/osm_importer/projection.py
  resources/osm_importer/webots_objects/building.py
  resources/osm_importer/webots_objects/road.py
  resources/osm_importer/webots_objects/speed_limit.py
  resources/sumo_exporter/crossroad.py
  resources/sumo_exporter/math_utils.py
  resources/sumo_exporter/road.py
  scripts/export_function_js/export_function.py
  tests/sources/requirements.txt
  tests/sources/test_pep8.py
Labels: cleanup, test sources

#5754 Fix labels when going back
  resources/web/wwi/Animation.js
Labels: bug

#5756 Add multiplier support for web protos
  projects/robots/a4/portal/protos/Portal.proto
  projects/robots/a4/portal/protos/docs/images/portal/portal_pe.wbt.png
  projects/robots/a4/portal/protos/docs/images/portal/portal_pe.wbt.thumbnail.jpg
  projects/robots/a4/portal/protos/docs/portal.md
  projects/robots/a4/portal/webots.yaml
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/nodes/WbMotor.js
Labels: enhancement

#5760 Merge develop in feature-web-proto
  README.md
  docs/README.md
  docs/tests/requirements.txt
  docs/tests/test_pep8.py
  lib/controller/python/controller/__init__.py
  lib/controller/python/controller/camera.py
  lib/controller/python/vehicle/__init__.py
  projects/default/controllers/ros/headersGenerator.py
  projects/default/controllers/sumo_supervisor/SumoSupervisor.py
  projects/default/controllers/sumo_supervisor/WebotsVehicle.py
  projects/robots/epson/scara_t6/controllers/scara/scara.py
  projects/robots/epson/scara_t6/controllers/scara_food_industry/scara_food_industry.py
  projects/robots/niryo/ned/controllers/ned_python/ned_python.py
  projects/samples/robotbenchmark/highway_driving/controllers/highway_driving_benchmark/highway_driving_benchmark.py
  projects/vehicles/controllers/highway_overtake/highway_overtake.py
  resources/osm_importer/parser_objects.py
  resources/osm_importer/projection.py
  resources/osm_importer/webots_objects/building.py
  resources/osm_importer/webots_objects/road.py
  resources/osm_importer/webots_objects/speed_limit.py
  resources/sumo_exporter/crossroad.py
  resources/sumo_exporter/math_utils.py
  resources/sumo_exporter/road.py
  resources/web/wwi/Animation.js
  scripts/export_function_js/export_function.py
  tests/sources/requirements.txt
  tests/sources/test_pep8.py
Labels: synchronization

#5759 Turn Pionneer3Gripper into a coupled motor
  projects/robots/adept/pioneer3/controllers/pioneer3dx_gripper/pioneer3dx_gripper.c
  projects/robots/adept/pioneer3/protos/Pioneer3Gripper.proto
  projects/robots/adept/pioneer3/worlds/pioneer3dx_gripper.wbt
Labels: bug, enhancement

#5753 Make the robot window appear by default for competitions
  docs/guide/web-streaming.md
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
Labels: enhancement

#5763 Fix z-indexes
  resources/web/wwi/FloatingCustomWindow.js
  resources/web/wwi/FloatingIde.js
  resources/web/wwi/FloatingWindow.js
  resources/web/wwi/Terminal.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/css/progress.css
  resources/web/wwi/css/toolbar.css
Labels: bug

#5764 Add a add button for mf field
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/css/toolbar.css
Labels: enhancement

#5755 Fix labels multiple insertion
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  src/webots/wren/WbWrenLabelOverlay.hpp
Labels: bug

#5770 remove useless dependency
  docs/dependencies.txt
Labels: cleanup

#5771 Improve Charger behavior
  docs/reference/changelog-r2023.md
  docs/reference/charger.md
  src/webots/nodes/WbCharger.cpp
  src/webots/nodes/WbCharger.hpp
Labels: enhancement, test suite

#5772 Fix floating window resize
  resources/web/wwi/FloatingWindow.js
Labels: bug

#5774 Fix retrieving cached PROTO internal fields in Supervisor API
  docs/reference/changelog-r2023.md
  src/controller/c/supervisor.c
Labels: bug, test suite

#5775 Avoid having Field.type undefined
  lib/controller/python/controller/field.py
Labels: bug

#5776 Hotfix to use more contacts
  docs/reference/changelog-r2023.md
  src/webots/engine/WbSimulationCluster.cpp
  tests/physics/controllers/contact_points/.gitignore
  tests/physics/controllers/contact_points/Makefile
  tests/physics/controllers/contact_points/contact_points.c
  tests/physics/worlds/contact_points.wbt
  tests/physics/worlds/meshes/cone.stl
Labels: bug, test suite

#5786 Merge master into develop
  docs/reference/changelog-r2023.md
  src/webots/engine/WbSimulationCluster.cpp
  tests/physics/controllers/contact_points/.gitignore
  tests/physics/controllers/contact_points/Makefile
  tests/physics/controllers/contact_points/contact_points.c
  tests/physics/worlds/contact_points.wbt
  tests/physics/worlds/meshes/cone.stl
Labels: test suite, synchronization

#5788 Fix src image condition
  resources/web/wwi/Progress.js
Labels: bug

#5789 Feature robot window on startup for stream
  docs/guide/web-streaming.md
  resources/web/wwi/Stream.js
  resources/web/wwi/Toolbar.js
  resources/web/wwi/WebotsView.js
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbTcpServer.cpp
Labels: enhancement

#5797 Fix Motor.enableForceFeedback Python API function
  docs/reference/changelog-r2023.md
  lib/controller/python/controller/motor.py
Labels: bug, regression

#5800 Remove unused material references
  projects/default/worlds/meshes/suzanne.obj
  projects/objects/toys/protos/PaperBoat/meshes/geom.obj
  projects/objects/toys/protos/RubberDuck/meshes/beak.obj
  projects/objects/toys/protos/RubberDuck/meshes/body.obj
  projects/robots/epson/scara_t6/protos/meshes/arm.obj
  projects/robots/epson/scara_t6/protos/meshes/arm_nuts.obj
  projects/robots/epson/scara_t6/protos/meshes/base.obj
  projects/robots/epson/scara_t6/protos/meshes/base_arm.obj
  projects/robots/epson/scara_t6/protos/meshes/bulb.obj
  projects/robots/epson/scara_t6/protos/meshes/bulb_socket.obj
  projects/robots/epson/scara_t6/protos/meshes/button.obj
  projects/robots/epson/scara_t6/protos/meshes/button_socket.obj
  projects/robots/epson/scara_t6/protos/meshes/cable.obj
  projects/robots/epson/scara_t6/protos/meshes/connector.obj
  projects/robots/epson/scara_t6/protos/meshes/main_connector.obj
  projects/robots/epson/scara_t6/protos/meshes/nuts.obj
  projects/robots/epson/scara_t6/protos/meshes/shaft.obj
  projects/robots/festo/robotino3/protos/meshes/base_extension_plate.obj
  projects/robots/festo/robotino3/protos/meshes/base_ir_metal_ring_cover.obj
  projects/robots/festo/robotino3/protos/meshes/cap_1.obj
  projects/robots/festo/robotino3/protos/meshes/head_bottom_support.obj
  projects/robots/festo/robotino3/protos/meshes/head_extension_plate.obj
  projects/robots/festo/robotino3/protos/meshes/head_festo_logo.obj
  projects/robots/festo/robotino3/protos/meshes/head_left_metal_cover.obj
  projects/robots/festo/robotino3/protos/meshes/head_right_metal_cover.obj
  projects/robots/festo/robotino3/protos/meshes/head_vga_port.obj
  projects/robots/festo/robotino3/protos/meshes/side_sep.obj
  projects/robots/mir/mir100/protos/meshes/mir_100_base.obj
  projects/robots/mir/mir100/protos/meshes/mir_100_inside.obj
  projects/vehicles/protos/mercedes_benz/meshes/bumper.obj
  projects/vehicles/protos/mercedes_benz/meshes/coachwork.obj
  projects/vehicles/protos/mercedes_benz/meshes/coachwork_front.obj
  projects/vehicles/protos/mercedes_benz/meshes/front_logo.obj
  projects/vehicles/protos/mercedes_benz/meshes/mirrors.obj
  projects/vehicles/protos/mercedes_benz/meshes/plastic.obj
  projects/vehicles/protos/mercedes_benz/meshes/polymer.obj
  projects/vehicles/protos/mercedes_benz/meshes/roof_and_rear.obj
  projects/vehicles/protos/mercedes_benz/meshes/windows.obj
  tests/cache/worlds/meshes/cube_0.05m.obj
  tests/cache/worlds/meshes/cube_0.1m.obj
  tests/rendering/worlds/meshes/colored_cube.obj
Labels: cleanup

#5802 Fix missing mtl import
  tests/rendering/worlds/meshes/colored_cube.obj
Labels: bug

#5796 Make robot collisions thread-safe.
  src/webots/engine/WbSimulationCluster.cpp
  src/webots/engine/WbSimulationCluster.hpp
Labels: test suite

#5792 Hotfix to find all contacts quickly
  projects/robots/rec/fabtino/worlds/fabtino.wbt
  projects/robots/robotnik/summit_xl_steel/worlds/summit_xl_steel.wbt
  src/webots/engine/WbSimulationCluster.cpp
  src/webots/engine/WbSimulationCluster.hpp
Labels: bug, test suite, test worlds

#5773 Feature reset message for webots server
  src/webots/gui/WbTcpServer.cpp
  src/webots/gui/WbX3dStreamingServer.cpp
Labels: enhancement

#5782 Update documentation to 2022b+
  docs/reference/images/three_chairs_proto_example.png
  docs/reference/images/three_chairs_proto_example.thumbnail.jpg
  docs/reference/proto-example.md
Labels: documentation
