Repository cyberbotics/webots, pull requests merged in 2023-04, with the labels that each got.

#6034 Fix mesh double loading
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbMesh.cpp
Labels: bug, test suite

#6043 Update cppcheck to 2.10 on Ubuntu
  .github/workflows/tests_sources.yml
  src/webots/core/WbWebotsUpdateManager.cpp
  src/webots/editor/WbBuildEditor.cpp
  src/webots/gui/WbDragSolidEvent.cpp
  src/webots/gui/WbDragTransformEvent.cpp
  src/webots/gui/WbDragViewpointEvent.cpp
  src/webots/gui/WbView3D.cpp
  src/webots/nodes/WbAbstractCamera.cpp
  src/webots/nodes/WbCharger.cpp
  src/webots/nodes/WbDisplay.cpp
  src/webots/nodes/WbEmitter.cpp
  src/webots/nodes/WbGroup.cpp
  src/webots/nodes/WbLed.cpp
  src/webots/nodes/WbLensFlare.cpp
  src/webots/nodes/WbLightSensor.cpp
  src/webots/nodes/WbMotor.cpp
  src/webots/nodes/WbRadar.cpp
  src/webots/nodes/WbReceiver.cpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/WbTrack.cpp
  src/webots/nodes/WbViewpoint.cpp
  src/webots/sound/WbSoundClip.cpp
  src/webots/sound/WbWaveFile.cpp
  src/webots/vrml/WbProtoTreeItem.cpp
  src/webots/wren/WbWrenLabelOverlay.cpp
  src/webots/wren/WbWrenPicker.cpp
  tests/sources/test_cppcheck.py
Labels: test sources, test webots build

#6047 Fix mesh bounding object
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbFluid.hpp
  src/webots/nodes/WbMatter.hpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolid.hpp
Labels: bug, test suite, test sources

#6062 Rosbot XL documentation webots.cloud
  projects/robots/husarion/rosbot_xl/protos/RosbotXl.proto
  projects/robots/husarion/rosbot_xl/protos/docs/images/rosbot_xl/rosbot_xl.wbt.png
  projects/robots/husarion/rosbot_xl/protos/docs/images/rosbot_xl/rosbot_xl.wbt.thumbnail.jpg
  projects/robots/husarion/rosbot_xl/protos/docs/rosbotxl.md
Labels: documentation

#6067 Cleanup wrong code
  src/webots/control/WbController.cpp
Labels: cleanup

#6068 Clean-up warning filter
  resources/qt_warning_filters.conf
Labels: cleanup

#6071 Fixed load progress dialog parenting
  src/webots/gui/WbMainWindow.cpp
Labels: cleanup

#6080 Fix python getRangeImageArray API function name
  docs/reference/changelog-r2023.md
  lib/controller/python/controller/lidar.py
Labels: bug

#6083 Added technical user support documentation
  docs/guide/introduction-to-webots.md
Labels: documentation

#6048 Ensured correct mass is set during MoI matrix generation from bounding object #4906
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbSolid.cpp
Labels: bug, test suite

#6081 Fix contact points warnings
  projects/robots/nasa/worlds/sojourner.wbt
  projects/samples/rendering/worlds/animated_skin.wbt
  src/webots/engine/WbSimulationCluster.cpp
  src/webots/engine/WbSimulationCluster.hpp
Labels: cleanup

#5967 Fix camera recognition
  docs/reference/changelog-r2023.md
  src/webots/maths/WbAffinePlane.cpp
  src/webots/maths/WbAffinePlane.hpp
  src/webots/nodes/WbAbstractCamera.cpp
  src/webots/nodes/WbAbstractCamera.hpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbCamera.hpp
  src/webots/nodes/WbDevice.cpp
  src/webots/nodes/WbDevice.hpp
  src/webots/nodes/WbElevationGrid.cpp
  src/webots/nodes/WbLens.hpp
  src/webots/nodes/WbLidar.cpp
  src/webots/nodes/WbRadar.cpp
  src/webots/nodes/WbRangeFinder.cpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbRobot.hpp
  src/webots/nodes/utils/WbObjectDetection.cpp
  src/webots/nodes/utils/WbObjectDetection.hpp
  src/webots/wren/WbWrenCamera.hpp
  tests/api/controllers/camera_recognition/camera_recognition.c
  tests/api/worlds/camera_recognition.wbt
  tests/api/worlds/radar_frustum.wbt
  tests/lib/ts_assertion.h
Labels: bug, test distribution, test suite

#6097 Restore missing const
  src/webots/nodes/utils/WbObjectDetection.cpp
  src/webots/nodes/utils/WbObjectDetection.hpp
Labels: cleanup, test sources

#6088 Fix crash when mTriangleMesh is NULL
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbTransform.cpp
  src/webots/nodes/WbTriangleMeshGeometry.cpp
Labels: crash, test suite

#6100 Fix computation of Camera recognition object relative orientation
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbCamera.cpp
  tests/api/controllers/camera_recognition/camera_recognition.c
Labels: bug, test suite

#6106 Configurable window glass
  docs/reference/changelog-r2023.md
  projects/objects/apartment_structure/protos/Window.proto
Labels: enhancement

#6108 Update TIAGo finger joint names
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoGripper.proto
  tests/api/controllers/robot_urdf/tiago_reference.urdf
Labels: cleanup, test suite, test sources

#6103 Fix tmp path to include username on Linux and macOS
  docs/reference/changelog-r2023.md
  src/controller/c/robot.c
  src/webots/core/WbStandardPaths.cpp
  src/webots/core/WbTemplateEngine.cpp
  src/webots/gui/WbVideoRecorder.cpp
Labels: bug
