Repository cyberbotics/webots, pull requests merged in 2023-05, with the labels that each got.

#6110 Webots.cloud: .md for sensors
  projects/devices/delphi/protos/docs/delphiesr.md
  projects/devices/hokuyo/protos/docs/hokuyourg04lx.md
  projects/devices/hokuyo/protos/docs/hokuyourg04lxug01.md
  projects/devices/hokuyo/protos/docs/hokuyoutm30lx.md
  projects/devices/ibeo/protos/docs/ibeolux.md
  projects/devices/microsoft/protos/docs/kinect.md
  projects/devices/multisense/protos/docs/multisenses21.md
  projects/devices/orbbec/protos/docs/astra.md
  projects/devices/robotis/protos/docs/robotislds01.md
  projects/devices/sharp/protos/docs/sharpgp2d120.md
  projects/devices/sharp/protos/docs/sharpgp2y0a02yk0f.md
  projects/devices/sharp/protos/docs/sharpgp2y0a41sk0f.md
  projects/devices/sharp/protos/docs/sharpgp2y0a710k0f.md
  projects/devices/sick/protos/docs/sickldmrs.md
  projects/devices/sick/protos/docs/sicklms291.md
  projects/devices/sick/protos/docs/sicks300.md
  projects/devices/slamtec/protos/docs/rplidara2.md
  projects/devices/smartmicro/protos/docs/smsumrr-0a29.md
  projects/devices/smartmicro/protos/docs/smsumrr-0a30.md
  projects/devices/smartmicro/protos/docs/smsumrr-0a31.md
  projects/devices/tdk/protos/docs/mpu-9250.md
  projects/devices/velodyne/protos/docs/velodynehdl-32e.md
  projects/devices/velodyne/protos/docs/velodynehdl-64e.md
  projects/devices/velodyne/protos/docs/velodynepuck.md
Labels: documentation

#6113 Fix tmp path for extern controllers
  src/controller/c/robot.c
  src/webots/gui/WbVideoRecorder.cpp
Labels: bug, test suite, test sources

#6107 Improvements crazyflie
  projects/default/protos/textures/fast_helix.png
  projects/robots/bitcraze/crazyflie/controllers/crazyflie/crazyflie.c
  projects/robots/bitcraze/crazyflie/controllers/crazyflie/pid_controller.c
  projects/robots/bitcraze/crazyflie/controllers/crazyflie_py_wallfollowing/crazyflie_py_wallfollowing.py
  projects/robots/bitcraze/crazyflie/controllers/crazyflie_py_wallfollowing/pid_controller.py
  projects/robots/bitcraze/crazyflie/controllers/crazyflie_py_wallfollowing/wall_following.py
  projects/robots/bitcraze/crazyflie/protos/Crazyflie.proto
  projects/robots/bitcraze/crazyflie/worlds/.crazyflie_apartment.wbproj
  projects/robots/bitcraze/crazyflie/worlds/crazyflie_apartment.wbt
  projects/robots/dji/mavic/protos/Mavic2Pro.proto
Labels: enhancement, test sources

#6118 Fix ODE hinge joints limits
  docs/reference/changelog-r2023.md
  src/ode/ode/src/joints/joint.cpp
  src/ode/ode/src/joints/joint.h
Labels: bug

#6116 FLU: fix ceiling
  projects/samples/environments/indoor/worlds/complete_apartment.wbt
  projects/samples/environments/indoor/worlds/kitchen.wbt
Labels: bug

#6122 Fixed GCC 13 compilation warnings
  src/ode/OPCODE/Ice/IceAABB.cpp
  src/ode/OPCODE/Ice/IceAABB.h
  src/ode/ode/src/joints/transmission.cpp
  src/webots/gui/WbNewProtoWizard.cpp
  src/webots/nodes/WbConnector.cpp
  src/webots/scene_tree/WbInsertExternProtoDialog.cpp
Labels: cleanup

#6111 Stop extern controller counter during Webots world loading
  docs/reference/changelog-r2023.md
  src/controller/c/robot.c
  src/controller/c/scheduler.c
  src/controller/c/tcp_client.c
  src/webots/app/WbApplication.cpp
Labels: enhancement, test sources

#6124 Fix mesh related bugs
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbMesh.hpp
Labels: bug, test suite, test sources

#6131 Fix errors loading template PROTO nodes
  docs/reference/changelog-r2023.md
  src/webots/vrml/WbProtoTemplateEngine.cpp
Labels: bug, test suite

#6139 Update crazyflie_apartment.wbt
  projects/robots/bitcraze/crazyflie/worlds/crazyflie_apartment.wbt
Labels: enhancement

#6138 Remove scale field from devices WRL and improve JS basenode encoder
  resources/nodes/Accelerometer.wrl
  resources/nodes/Altimeter.wrl
  resources/nodes/Camera.wrl
  resources/nodes/Charger.wrl
  resources/nodes/Compass.wrl
  resources/nodes/Connector.wrl
  resources/nodes/Display.wrl
  resources/nodes/DistanceSensor.wrl
  resources/nodes/Emitter.wrl
  resources/nodes/GPS.wrl
  resources/nodes/Gyro.wrl
  resources/nodes/InertialUnit.wrl
  resources/nodes/LED.wrl
  resources/nodes/Lidar.wrl
  resources/nodes/LightSensor.wrl
  resources/nodes/Microphone.wrl
  resources/nodes/Pen.wrl
  resources/nodes/Radar.wrl
  resources/nodes/Radio.wrl
  resources/nodes/RangeFinder.wrl
  resources/nodes/Receiver.wrl
  resources/nodes/Speaker.wrl
  resources/nodes/TouchSensor.wrl
  resources/web/wwi/protoVisualizer/FieldModel.js
  resources/web/wwi/protoVisualizer/scripts/basenode_encoder.py
Labels: enhancement, test suite

#6136 Enhancement backward compatibility pose
  scripts/converter/convert_transform_to_pose.py
  scripts/converter/webots_parser.py
  src/webots/nodes/utils/WbConcreteNodeFactory.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNodeReader.cpp
  src/webots/vrml/WbVrmlNodeUtilities.cpp
  src/webots/vrml/WbVrmlNodeUtilities.hpp
  tests/parser/expected_results.txt
Labels: enhancement, test sources

#6141 Fix node comparison
  src/webots/vrml/WbNode.cpp
Labels: bug, test suite, test sources

#6142 FLU: fix radiator
  projects/objects/apartment_structure/protos/Radiator.proto
Labels: bug

#6143 Better fix to comparison issue
  src/webots/vrml/WbNode.cpp
Labels: bug, test suite, test sources

#6146 Fixed test worlds
  projects/robots/sony/aibo/worlds/aibo_ers7.wbt
Labels: cleanup

#6149 Fix pose webotsjs
  resources/web/wwi/nodes/WbDistanceSensor.js
  resources/web/wwi/nodes/WbPose.js
  resources/web/wwi/nodes/WbTransform.js
Labels: bug

#6145 Merge master in develop
  projects/objects/apartment_structure/protos/Radiator.proto
  src/webots/vrml/WbNode.cpp
Labels: test suite, test sources, synchronization

#6152 Merge master in develop
  projects/devices/velodyne/protos/VelodyneHDL-32E.proto
  projects/devices/velodyne/protos/VelodyneHDL-64E.proto
  projects/humans/pedestrian/protos/PedestrianHead.proto
  projects/humans/pedestrian/protos/PedestrianLeftFoot.proto
  projects/humans/pedestrian/protos/PedestrianLeftHand.proto
  projects/humans/pedestrian/protos/PedestrianLeftLowerArm.proto
  projects/humans/pedestrian/protos/PedestrianLeftLowerLeg.proto
  projects/humans/pedestrian/protos/PedestrianLeftUpperArm.proto
  projects/humans/pedestrian/protos/PedestrianLeftUpperLeg.proto
  projects/humans/pedestrian/protos/PedestrianNeck.proto
  projects/humans/pedestrian/protos/PedestrianRightFoot.proto
  projects/humans/pedestrian/protos/PedestrianRightHand.proto
  projects/humans/pedestrian/protos/PedestrianRightLowerArm.proto
  projects/humans/pedestrian/protos/PedestrianRightLowerLeg.proto
  projects/humans/pedestrian/protos/PedestrianRightUpperArm.proto
  projects/humans/pedestrian/protos/PedestrianRightUpperLeg.proto
  projects/humans/pedestrian/protos/PedestrianTorso.proto
  projects/objects/buildings/protos/BungalowStyleHouse.proto
  projects/objects/buildings/protos/ModernHouse.proto
  projects/objects/buildings/protos/SimpleTwoFloorsHouse.proto
  projects/objects/geometries/protos/Extrusion.proto
  projects/objects/street_furniture/protos/BusStopBench.proto
  projects/objects/street_furniture/protos/BusStopMesh.proto
  projects/robots/neuronics/ipr/protos/IprHd6m180.proto
  projects/robots/neuronics/ipr/protos/IprHd6ms180.proto
  projects/robots/robotis/bioloid/protos/BioloidDog.proto
  projects/robots/sony/qrio/protos/QRIO.proto
  projects/samples/geometries/worlds/webots_box.wbt
  projects/vehicles/protos/bmw/BmwX5AntiFogLight.proto
  projects/vehicles/protos/bmw/BmwX5BackwardsLight.proto
  projects/vehicles/protos/bmw/BmwX5BrakingLight.proto
  projects/vehicles/protos/bmw/BmwX5RearLight.proto
  projects/vehicles/worlds/village_realistic.wbt
  resources/nodes/IndexedFaceSet.wrl
  src/webots/Makefile
  src/webots/gui/WbImportWizard.cpp
  src/webots/gui/WbImportWizard.hpp
  src/webots/gui/WbMainWindow.cpp
  src/webots/nodes/WbIndexedFaceSet.cpp
Labels: test suite, test sources, synchronization

#6155 Fix documentation urls in proto
  projects/objects/paintings/protos/PortraitPainting.proto
  projects/objects/street_furniture/protos/DrinkingFountain.proto
  projects/objects/street_furniture/protos/OldBench.proto
  projects/objects/tables/protos/RoundTable.proto
  projects/objects/trees/protos/Tree.proto
  projects/robots/husarion/rosbot/protos/Rosbot.proto
  projects/robots/irobot/create/protos/Create.proto
  projects/robots/k-team/khepera3/protos/Khepera3.proto
  projects/robots/k-team/khepera4/protos/Khepera4.proto
  projects/robots/kinematics/tinkerbots/protos/TinkerbotsBrickAdapter.proto
  projects/robots/nvidia/jetbot/protos/JetBot.proto
  projects/robots/pal_robotics/tiagopp/protos/Tiago++.proto
  projects/robots/sony/qrio/protos/QRIO.proto
  projects/robots/unimation/puma/protos/Puma560.proto
  projects/vehicles/protos/abstract/AckermannVehicle.proto
  projects/vehicles/protos/abstract/Car.proto
  projects/vehicles/protos/abstract/SimpleVehicle.proto
  projects/vehicles/protos/abstract/VehicleWheel.proto
  projects/vehicles/protos/bmw/BmwX5.proto
  projects/vehicles/protos/bmw/BmwX5Simple.proto
  projects/vehicles/protos/citroen/CitroenCZero.proto
  projects/vehicles/protos/citroen/CitroenCZeroSimple.proto
  projects/vehicles/protos/generic/Bus.proto
  projects/vehicles/protos/generic/BusSimple.proto
  projects/vehicles/protos/generic/MotorbikeSimple.proto
  projects/vehicles/protos/generic/ScooterSimple.proto
  projects/vehicles/protos/generic/Tractor.proto
  projects/vehicles/protos/generic/Truck.proto
  projects/vehicles/protos/generic/TruckSimple.proto
  projects/vehicles/protos/lincoln/LincolnMKZ.proto
  projects/vehicles/protos/lincoln/LincolnMKZSimple.proto
  projects/vehicles/protos/mercedes_benz/MercedesBenzSprinter.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVR.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVRSimple.proto
  projects/vehicles/protos/toyota/ToyotaPrius.proto
  projects/vehicles/protos/toyota/ToyotaPriusSimple.proto
Labels: documentation

#6158 Fix compilation warnings on macOS
  projects/robots/epfl/lis/controllers/blimp/js.h
  src/wren/StaticMesh.cpp
Labels: bug, test distribution, test sources

#6026 Display in the tree the name of the solid at the extremity of a joint
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbBasicJoint.cpp
  src/webots/nodes/WbBasicJoint.hpp
  src/webots/nodes/WbSlot.cpp
  src/webots/nodes/WbSlot.hpp
  src/webots/nodes/WbSolidReference.cpp
  src/webots/nodes/WbSolidReference.hpp
  src/webots/scene_tree/WbTreeItem.cpp
  src/webots/user_commands/WbClipboard.cpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
Labels: enhancement, test suite, test webots build

#6159 Upgrade action version to solve deprecation errors
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
  .github/workflows/test_suite_windows.yml
  .github/workflows/test_suite_windows_develop.yml
  .github/workflows/tests_doc.yml
  .github/workflows/tests_sources.yml
  .github/workflows/tests_sources_with_latest_cppcheck.yml
Labels: test distribution, test suite
