Repository cyberbotics/webots, pull requests merged in 2023-02, with the labels that each got.

#5818 Add persistantDockerImages mention to server doc
  docs/guide/simulation-server.md
Labels: documentation

#5807 Fixed stdout/stderr redirection with extern Python controllers on Windows
  docs/reference/changelog-r2023.md
  lib/controller/python/controller/robot.py
Labels: bug

#5817 Merge master in develop
  docs/guide/the-console.md
  docs/reference/images/three_chairs_proto_example.png
  docs/reference/images/three_chairs_proto_example.thumbnail.jpg
  docs/reference/proto-example.md
  projects/samples/devices/controllers/laser_pointer/laser_pointer.c
Labels: synchronization

#5825 Add tips on swap
  docs/guide/advanced-configuration.md
Labels: documentation

#5826 Fixed warning filters
  resources/qt_warning_filters.conf
Labels: enhancement, cleanup

#5812 Update changelog to reflect PR 5792 and 5796.
  docs/reference/changelog-r2023.md
Labels: documentation

#5811 Fix web proto issues related to vehicles
  projects/vehicles/protos/abstract/VehicleWheel.proto
  projects/vehicles/protos/tesla/TeslaModel3.proto
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/NodeSelectorWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/ProtoManager.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/nodes/WbBallJoint.js
  resources/web/wwi/nodes/WbHinge2Joint.js
  resources/web/wwi/nodes/WbHingeJoint.js
  resources/web/wwi/nodes/WbImageTexture.js
  resources/web/wwi/nodes/WbJoint.js
  resources/web/wwi/nodes/WbSliderJoint.js
  resources/web/wwi/nodes/WbSlot.js
  resources/web/wwi/nodes/WbTransform.js
  resources/web/wwi/nodes/utils/WbBoundingSphere.js
  resources/web/wwi/nodes/utils/node_utilities.js
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Vrml.js
Labels: bug, enhancement

#5779 Refactor node and PROTO creation
  src/webots/gui/WbSingleTaskApplication.cpp
  src/webots/nodes/WbBaseNode.cpp
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbTemplateManager.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/vrml/WbField.cpp
  src/webots/vrml/WbField.hpp
  src/webots/vrml/WbNode.cpp
  src/webots/vrml/WbNode.hpp
  src/webots/vrml/WbVrmlNodeUtilities.cpp
  src/webots/vrml/WbVrmlNodeUtilities.hpp
Labels: bug, cleanup, test suite, test worlds

#5629 Feature extern controllers launcher
  .gitignore
  docs/guide/running-extern-robot-controllers.md
  docs/reference/changelog-r2023.md
  scripts/packaging/files_core.txt
  src/controller/Makefile
  src/controller/launcher/Makefile
  src/controller/launcher/webots_controller.c
  src/webots/control/WbController.cpp
  tests/sources/test_clang_format.py
  tests/sources/test_cppcheck.py
  tests/sources/test_license.py
Labels: feature, test sources

#5830 Fix web proto prefix
  resources/web/wwi/protoVisualizer/Node.js
Labels: bug

#5813 Log test suite performance
  tests/.gitignore
  tests/command.py
  tests/command_test.py
  tests/test_suite.py
Labels: test suite

#5831 Enhancement display of vectors
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/css/toolbar.css
Labels: enhancement

#5836 Report system failures from test_suite.py.
  tests/test_suite.py
Labels: test suite

#5806 Don't use port that is already in use
  docs/reference/changelog-r2023.md
  src/webots/gui/WbTcpServer.cpp
  tests/test_suite.py
Labels: test suite

#5838 Hotfix-nonblocking-loop-when-running-test-suite
  tests/command.py
Labels: test suite

#5845 Make bash scripts exit when any command fails.
  scripts/install/inno_setup_installer.sh
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/linux_runtime_dependencies.sh
  scripts/install/linux_test_dependencies.sh
  scripts/install/linux_web_viewer_dependencies.sh
  scripts/install/msys.sh
  scripts/install/msys64_installer.sh
  scripts/install/qt_linux_installer.sh
  scripts/install/qt_mac_installer.sh
  scripts/install/qt_windows_installer.sh
Labels: enhancement, test suite

#5847 Update Python receiver get data documentation
  docs/reference/receiver.md
Labels: documentation

#5824 Allow cache tests to be run from a local branch
  tests/cache/cache_environment.py
Labels: test suite

#5724 Fix crash during PROTO regeneration due to invalid search of parent field
  docs/reference/changelog-r2023.md
  src/webots/nodes/utils/WbTemplateManager.cpp
Labels: bug, crash, test suite

#5848 Fix documentation about wwi
  docs/reference/robot.md
Labels: cleanup

#5849 Fix small typo.
  docs/reference/robot.md
Labels: documentation

#5844 Add support for controller arguments to the extern controller launcher
  docs/guide/running-extern-robot-controllers.md
  src/controller/launcher/webots_controller.c
Labels: enhancement, test sources

#5850 Enhancement led support
  resources/web/wwi/Parser.js
  resources/web/wwi/nodes/WbAppearance.js
  resources/web/wwi/nodes/WbLed.js
  resources/web/wwi/nodes/WbShape.js
  resources/web/wwi/nodes/utils/WbFieldChecker.js
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Vrml.js
Labels: enhancement

#5851 Enhancement for simgait
  docs/guide/web-animation.md
  resources/web/wwi/Animation.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/webots.js
Labels: enhancement

#5854 Fix dependencies installations on Ubuntu 20.04
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/linux_runtime_dependencies.sh
  scripts/install/linux_test_dependencies.sh
  scripts/install/linux_web_viewer_dependencies.sh
Labels: bug, regression

#5857 Merge master in develop
  docs/reference/changelog-r2023.md
  docs/reference/receiver.md
  docs/reference/robot.md
  scripts/install/inno_setup_installer.sh
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_optional_compilation_dependencies.sh
  scripts/install/linux_runtime_dependencies.sh
  scripts/install/linux_test_dependencies.sh
  scripts/install/linux_web_viewer_dependencies.sh
  scripts/install/msys.sh
  scripts/install/msys64_installer.sh
  scripts/install/qt_linux_installer.sh
  scripts/install/qt_mac_installer.sh
  scripts/install/qt_windows_installer.sh
  tests/cache/cache_environment.py
  tests/command.py
Labels: test suite, synchronization

#5843 Fix wrong save world warning
  docs/reference/changelog-r2023.md
  src/webots/gui/WbMainWindow.cpp
Labels: bug, test webots build

#5839 Hotfix for retrieval of sibling devices returning wrong devices for BallJoint's device3 devices.
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbJointDevice.cpp
  tests/physics/controllers/joint_controller/joint_controller.c
  tests/physics/worlds/ball_joint_vs_hinge_joints.wbt
Labels: bug, test suite

#5834 Hotfix for inaccurate HingeJoint, Hinge2Joint, and BallJoint position under velocity control
  docs/reference/changelog-r2023.md
  src/ode/ode/src/joints/amotor.cpp
  src/webots/maths/WbMathsUtilities.hpp
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbHinge2Joint.cpp
  src/webots/nodes/WbHingeJoint.cpp
  tests/api/controllers/motor/motor.c
  tests/api/controllers/motor2_velocity/.gitignore
  tests/api/controllers/motor2_velocity/Makefile
  tests/api/controllers/motor2_velocity/motor2_velocity.c
  tests/api/controllers/motor3_velocity/.gitignore
  tests/api/controllers/motor3_velocity/Makefile
  tests/api/controllers/motor3_velocity/motor3_velocity.c
  tests/api/worlds/motor.wbt
  tests/api/worlds/motor2_velocity.wbt
  tests/api/worlds/motor3_velocity.wbt
  tests/physics/controllers/coupled_motor/coupled_motor.c
Labels: test suite, test worlds

#5769 Make contact point handling configurable (was: Stop silently ignoring more than 10 contacts)
  docs/reference/changelog-r2023.md
  docs/reference/contactproperties.md
  resources/nodes/ContactProperties.wrl
  src/webots/engine/WbSimulationCluster.cpp
  src/webots/engine/WbSimulationCluster.hpp
  src/webots/nodes/WbContactProperties.cpp
  src/webots/nodes/WbContactProperties.hpp
Labels: test suite

#5858 Fix uninitialized set_exposure variable.
  src/controller/c/camera.c
Labels: test suite

#5859 Document not to access image data during a step.
  docs/reference/camera.md
  docs/reference/lidar.md
  docs/reference/rangefinder.md
  docs/reference/robot.md
Labels: bug, documentation

#5795 Fix north in worlds imported from OpenStreetMap
  resources/osm_importer/projection.py
  resources/osm_importer/utils/misc_utils.py
Labels: question

#5867 Fix delete physic
  resources/web/wwi/X3dScene.js
Labels: bug

#5864 Enhancement webotsjs propeller
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/nodes/WbGroup.js
  resources/web/wwi/nodes/WbPropeller.js
  src/webots/nodes/WbPropeller.cpp
Labels: enhancement

#5877 Fix MFNode insertion in web PROTO
  resources/web/wwi/protoVisualizer/Parameter.js
Labels: bug

#5883 WebotsJS: Add devices to robots
  resources/web/wwi/NodeSelectorWindow.js
Labels: enhancement

#5884 WebotsJS: default value MF
  resources/web/wwi/protoVisualizer/Vrml.js
Labels: enhancement

#5891 WebotsJS: fix web mf
  resources/web/wwi/FloatingProtoParameterWindow.js
Labels: bug

#5895 Fix variable name
  projects/devices/robotis/protos/RobotisLds01.proto
Labels: bug

#5898 Merge master in develop
  projects/devices/robotis/protos/RobotisLds01.proto
Labels: synchronization

#5897 Fix typos in Python Car Lib
  lib/controller/python/vehicle/car.py
Labels: bug

#5885 Prepend libController path to environment
  docs/reference/changelog-r2023.md
  src/webots/control/WbController.cpp
Labels: bug

#5899 Fix parent when exporting SliderJoint to URDF
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbSliderJoint.cpp
Labels: bug

#5889 Connector: Fix status after reset
  docs/reference/changelog-r2023.md
  docs/reference/supervisor.md
  src/webots/nodes/WbConnector.cpp
Labels: bug, test suite

#5900 Better reload/reset table
  docs/css/webots-doc.css
  docs/reference/supervisor.md
Labels: documentation

#5860 Don't use Camera in robot_parallel_step test.
  tests/api/controllers/robot_parallel_step/robot_parallel_step.c
Labels: test suite issue, test suite

#5905 Fix Camera recognition for scaled objects
  docs/reference/changelog-r2023.md
  src/webots/nodes/utils/WbObjectDetection.cpp
Labels: bug, test suite

#5907 WebotsJS: Translate device
  resources/web/wwi/WebotsView.js
Labels: enhancement

#5909 Fix naming of php file
  resources/web/wwi/WebotsView.js
Labels: cleanup

#5906 Robots insertion
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbNodeUtilities.hpp
Labels: enhancement

#5894 WebotsJS: fix parameters bugs
  projects/joints/protos/Hinge2JointWithBacklash.proto
  projects/joints/protos/HingeJointWithBacklash.proto
  projects/joints/webots.yaml
  resources/web/wwi/nodes/WbBallJoint.js
  resources/web/wwi/nodes/WbDevice.js
  resources/web/wwi/nodes/WbHinge2Joint.js
  resources/web/wwi/nodes/WbHingeJoint.js
  resources/web/wwi/nodes/WbJoint.js
  resources/web/wwi/nodes/WbViewpoint.js
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Vrml.js
Labels: enhancement

#5911 Slot Tiago
  docs/guide/tiagopp.md
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoBody.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoFrontArm.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoGripper.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoLeftArm.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoLeftHey5.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightArm.proto
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoRightHey5.proto
  projects/robots/pal_robotics/tiago_steel/protos/TiagoSteel.proto
  projects/robots/pal_robotics/tiago_titanium/protos/TiagoTitanium.proto
  projects/robots/pal_robotics/tiagopp/protos/Tiagopp.proto
  projects/robots/pal_robotics/tiagopp/protos/docs/tiagopp.md
  tests/api/controllers/robot_urdf/tiago_reference.urdf
Labels: cleanup

#5896 Add version comparison between libController and Webots
  docs/reference/changelog-r2023.md
  src/controller/c/Makefile
  src/controller/c/robot.c
  src/webots/nodes/WbRobot.cpp
Labels: feature, test suite, test sources

#5915 WebotsJS: Fix devices position
  resources/web/wwi/WebotsView.js
Labels: enhancement

#5887 Make supervisor_export_image test image content.
  .github/workflows/test_suite_linux.yml
  tests/api/controllers/supervisor_export_image/supervisor_export_image.c
  tests/api/worlds/supervisor_export_image.wbt
  tests/with_rendering/controllers/supervisor_export_image/.gitignore
  tests/with_rendering/controllers/supervisor_export_image/Makefile
  tests/with_rendering/controllers/supervisor_export_image/supervisor_export_image.c
  tests/with_rendering/worlds/.gitignore
  tests/with_rendering/worlds/.supervisor_export_image.wbproj
  tests/with_rendering/worlds/supervisor_export_image.wbt
Labels: test suite

#5917 Avoid printing some warnings in CI
  src/webots/gui/WbGuiApplication.cpp
  src/webots/sound/WbSoundEngine.cpp
Labels: cleanup

#5902 Hotfix-supervisor-export-image-immediately
  docs/reference/changelog-r2023.md
  src/webots/gui/WbSimulationView.cpp
  src/webots/gui/WbView3D.cpp
  tests/with_rendering/controllers/supervisor_export_image/supervisor_export_image.c
Labels: test suite

#5923 Fix missing version
  projects/samples/tutorials/protos/FourWheelsRobot.proto
Labels: bug, cleanup

#5922 Delete empty shapes folder and icon
  projects/shapes/protos/icons/ColladaShapes.png
Labels: cleanup

#5914 WebotsJs: Fix nested slot resolution
  resources/web/wwi/NodeSelectorWindow.js
Labels: enhancement

#5927 Rename Mavic gyro variables to velocity
  projects/robots/dji/mavic/controllers/mavic2pro/mavic2pro.c
Labels: cleanup

#5926 Update FourWheelsRobot.proto version
  projects/samples/tutorials/protos/FourWheelsRobot.proto
Labels: bug

#5928 WebotsJS: Fix nested templateregenerator
  resources/web/wwi/protoVisualizer/Node.js
Labels: bug

#5929 WebotsJS: Fix default texture mapping
  resources/web/wwi/nodes/utils/WbTriangleMesh.js
Labels: bug, test sources

#5931 Fix typo
  projects/objects/buildings/protos/RandomBuilding.proto
Labels: bug

#5933 Remove ajax call
  resources/web/wwi/WebotsView.js
Labels: enhancement

#5934 Fix render on regeneration
  resources/web/wwi/protoVisualizer/Parameter.js
Labels: bug

#5935 Fix urls generated by js in the body of a proto
  resources/web/wwi/protoVisualizer/Node.js
Labels: bug

#5944 Fix regeneration propagation for Web PROTO
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Parameter.js
Labels: bug

#5941 Fix crash when inserting in node in regenerating PROTO paramter
  src/webots/nodes/utils/WbNodeOperations.cpp
Labels: crash, test suite

#5947 Fix regeneration seed logic on the web
  projects/objects/trees/protos/SimpleTree.proto
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/TemplateEngine.js
Labels: bug

#5945 WebotsJS: Fix robot-window when switching worlds
  src/webots/gui/WbMultimediaStreamingServer.cpp
  src/webots/gui/WbTcpServer.cpp
  src/webots/gui/WbX3dStreamingServer.cpp
Labels: bug
