Repository cyberbotics/webots, pull requests merged in 2023-03, with the labels that each got.

#5954 Fix dependency error
  resources/web/wwi/FloatingProtoParameterWindow.js
Labels: bug, test sources

#5886 Fix issues resolving Solid name clash
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolid.hpp
  src/webots/nodes/utils/WbConcreteNodeFactory.cpp
  src/webots/nodes/utils/WbNodeOperations.cpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbTemplateManager.cpp
  src/webots/nodes/utils/WbTemplateManager.hpp
  src/webots/vrml/WbNode.cpp
Labels: bug, crash, test suite

#5956 Fix basetype for role attribution
  resources/web/wwi/protoVisualizer/Vrml.js
Labels: bug

#5962 Missing IS
  projects/objects/kitchen/utensils/protos/Spoon.proto
Labels: bug

#5950 Fix WbMFNode::setItem functionality
  src/webots/nodes/WbBallJoint.cpp
  src/webots/nodes/WbGroup.cpp
  src/webots/nodes/WbGroup.hpp
  src/webots/nodes/WbHinge2Joint.cpp
  src/webots/nodes/WbJoint.cpp
  src/webots/nodes/WbTrack.cpp
  src/webots/nodes/WbTransform.cpp
  src/webots/nodes/utils/WbTemplateManager.cpp
  src/webots/scene_tree/WbSceneTree.cpp
  src/webots/scene_tree/WbTreeItem.cpp
  src/webots/vrml/WbField.cpp
  src/webots/vrml/WbField.hpp
  src/webots/vrml/WbMFNode.cpp
  src/webots/vrml/WbMFNode.hpp
Labels: cleanup, test suite

#5957 Fix USE node setup in WbDictionary
  src/webots/nodes/utils/WbDictionary.cpp
Labels: bug, test suite, test sources

#5961 Fix update of joint endPoint after regeneration
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbBasicJoint.cpp
  src/webots/nodes/WbSolid.cpp
  src/webots/nodes/WbSolid.hpp
Labels: bug, test suite

#5958 FLU fix joint of valves
  projects/objects/factory/valves/protos/LargeValve.proto
  projects/objects/factory/valves/protos/SmallValve.proto
Labels: bug

#5965 Fix test_suite overwriting local Webots configuration
  tests/test_suite.py
Labels: bug, test suite issue, test suite

#5968 Fixed Python getContactPoints API function
  docs/reference/changelog-r2023.md
  include/controller/c/webots/contact_point.h
  lib/controller/python/controller/node.py
Labels: bug

#5971 Documentation update to docker compose v2
  docs/guide/setup-a-webots-project-repository.md
  docs/guide/simulation-server.md
  projects/samples/howto/docker/README.md
  projects/samples/howto/docker/launcher.py
  projects/samples/howto/docker/launcher_without_docker.py
  projects/samples/howto/docker/simulation/worlds/camera.wbt
Labels: documentation

#5974 Fix contact points
  src/controller/c/supervisor.c
  src/controller/cpp/Node.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
Labels: bug, test suite

#5976 Merge master in develop
  src/controller/c/supervisor.c
  src/controller/cpp/Node.cpp
  src/webots/nodes/utils/WbSupervisorUtilities.cpp
  tests/api/controllers/supervisor_get_position_orientation_pose/supervisor_get_position_orientation_pose.c
Labels: synchronization

#5977 WebotsJS: Fix mf restrictions
  resources/web/wwi/protoVisualizer/Parameter.js
Labels: bug

#5959 Fix invalid robot names
  docs/reference/changelog-r2023.md
  src/controller/c/robot.c
  src/controller/c/scheduler.c
  src/controller/c/sha1.c
  src/controller/c/sha1.h
  src/controller/c/system.c
  src/controller/launcher/webots_controller.c
  src/webots/control/WbController.cpp
  src/webots/core/WbStandardPaths.cpp
  src/webots/core/WbTemplateEngine.cpp
  src/webots/gui/WbTcpServer.cpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbRobot.hpp
  tests/sources/test_clang_format.py
  tests/sources/test_cppcheck.py
  tests/sources/test_license.py
Labels: test sources

#5979 WebotsJS: Comparison without value
  resources/web/wwi/protoVisualizer/Parameter.js
Labels: bug

#5981 Fix `mavic2pro_patrol` controller
  docs/reference/changelog-r2023.md
  projects/robots/dji/mavic/controllers/mavic2pro_patrol/mavic2pro_patrol.py
Labels: bug

#5984 Add mavic2pro WorldInfo settings
  docs/guide/mavic-2-pro.md
Labels: documentation

#5980 Fix some issues related to scaled objects
  src/webots/nodes/WbAbstractTransform.hpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbCapsule.cpp
  src/webots/nodes/WbCone.cpp
  src/webots/nodes/WbCylinder.cpp
  src/webots/nodes/WbPlane.cpp
  src/webots/nodes/utils/WbBoundingSphere.cpp
  src/webots/nodes/utils/WbBoundingSphere.hpp
  src/webots/nodes/utils/WbObjectDetection.cpp
  src/webots/nodes/utils/WbPaintTexture.cpp
  tests/api/controllers/pen_capsule_scaled/pen_capsule_scaled.c
  tests/api/controllers/pen_sphere_scaled/pen_sphere_scaled.c
  tests/api/worlds/pen_capsule_scaled.wbt
  tests/api/worlds/pen_cone_scaled.wbt
  tests/api/worlds/pen_cylinder_scaled.wbt
  tests/api/worlds/pen_elevation_grid_scaled.wbt
  tests/api/worlds/pen_indexed_face_set_scaled.wbt
  tests/api/worlds/pen_sphere_scaled.wbt
Labels: bug, test suite

#5988 Merge master in develop
  docs/guide/mavic-2-pro.md
  docs/reference/changelog-r2023.md
  projects/robots/dji/mavic/controllers/mavic2pro_patrol/mavic2pro_patrol.py
  src/webots/nodes/WbAbstractTransform.hpp
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbCapsule.cpp
  src/webots/nodes/WbCone.cpp
  src/webots/nodes/WbCylinder.cpp
  src/webots/nodes/WbPlane.cpp
  src/webots/nodes/utils/WbBoundingSphere.cpp
  src/webots/nodes/utils/WbBoundingSphere.hpp
  src/webots/nodes/utils/WbObjectDetection.cpp
  src/webots/nodes/utils/WbPaintTexture.cpp
  tests/api/controllers/pen_capsule_scaled/pen_capsule_scaled.c
  tests/api/controllers/pen_sphere_scaled/pen_sphere_scaled.c
  tests/api/worlds/pen_capsule_scaled.wbt
  tests/api/worlds/pen_cone_scaled.wbt
  tests/api/worlds/pen_cylinder_scaled.wbt
  tests/api/worlds/pen_elevation_grid_scaled.wbt
  tests/api/worlds/pen_indexed_face_set_scaled.wbt
  tests/api/worlds/pen_sphere_scaled.wbt
Labels: synchronization

#5989 Fix smile of MyBot robot
  projects/samples/devices/worlds/accelerometer.wbt
  projects/samples/devices/worlds/camera_recognition.wbt
  projects/samples/devices/worlds/camera_segmentation.wbt
  projects/samples/devices/worlds/force_sensor.wbt
  projects/samples/howto/binocular/worlds/binocular.wbt
  projects/samples/howto/physics/worlds/physics.wbt
  projects/samples/howto/texture_change/worlds/texture_change.wbt
  projects/samples/mybot/worlds/mybot.wbt
  projects/samples/mybot/worlds/mybot_camera.wbt
  projects/samples/mybot/worlds/mybot_physics.wbt
Labels: enhancement

#5990 WebotsJS: Fix mf node regeneration
  resources/web/wwi/protoVisualizer/Field.js
  resources/web/wwi/protoVisualizer/Node.js
  resources/web/wwi/protoVisualizer/Parameter.js
Labels: bug, enhancement

#5994 Fix bounding sphere radius for Sphere and CadShape
  src/webots/nodes/WbCadShape.cpp
  src/webots/nodes/WbSphere.cpp
Labels: bug, test suite

#5995 Fix webotsjs type in parser
  resources/web/wwi/Parser.js
Labels: bug

#5985 WebotsJS: Fix bounding sphere computation
  resources/web/wwi/Parser.js
  resources/web/wwi/nodes/WbBox.js
  resources/web/wwi/nodes/WbCadShape.js
  resources/web/wwi/nodes/WbCapsule.js
  resources/web/wwi/nodes/WbCone.js
  resources/web/wwi/nodes/WbCylinder.js
  resources/web/wwi/nodes/WbDevice.js
  resources/web/wwi/nodes/WbPlane.js
  resources/web/wwi/nodes/WbSphere.js
Labels: synchronization

#5997 Fix mf regeneration derivatedProto
  resources/web/wwi/protoVisualizer/Parameter.js
Labels: bug

#5999 Fix instructions for the location of the webots.yml file
  docs/guide/webots-cloud.md
Labels: documentation

#6001 Fix webjs undefined
  resources/web/wwi/ImageLoader.js
Labels: bug

#5943 Add support for controllerArgs in MATLAB by moving from scripts to functions
  docs/guide/controller-programming.md
  docs/guide/controller-start-up.md
  docs/guide/matlab.md
  docs/guide/supervisor-programming.md
  docs/guide/tutorial-1-your-first-simulation-in-webots.md
  docs/guide/tutorial-4-more-about-controllers.md
  docs/guide/tutorial-6-4-wheels-robot.md
  docs/guide/tutorial-8-the-supervisor.md
  docs/guide/using-matlab.md
  docs/reference/changelog-r2023.md
  lib/controller/matlab/launcher.m
  projects/languages/matlab/controllers/matlab/matlab.m
  projects/robots/adept/pioneer3/controllers/pioneer3dx_matlab/pioneer3dx_matlab.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/gripper_init.m
  projects/robots/kuka/youbot/controllers/youbot_matlab/youbot_matlab.m
  projects/robots/mir/mir100/controllers/Makefile
  projects/robots/mir/mir100/controllers/keyboard_matlab/keyboard_matlab.m
  projects/robots/robotis/darwin-op/controllers/symmetry_matlab/symmetry_matlab.m
  projects/robots/softbank/nao/controllers/nao_matlab/nao_matlab.m
  projects/robots/softbank/nao/controllers/supervisor_matlab/supervisor_matlab.m
  projects/samples/howto/force_control/controllers/force_control_matlab/force_control_matlab.m
  projects/samples/tutorials/controllers/epuck_avoid_collision/epuck_avoid_collision.m
  projects/samples/tutorials/controllers/epuck_go_forward/epuck_go_forward.m
  projects/samples/tutorials/controllers/four_wheels_collision_avoidance/four_wheels_collision_avoidance.m
  resources/templates/controllers/template.m
  src/controller/launcher/webots_controller.c
  src/webots/control/WbController.cpp
  src/webots/control/WbLanguageTools.cpp
Labels: enhancement

#6006 Fix flu vehicles
  projects/vehicles/protos/abstract/AckermannVehicle.proto
  projects/vehicles/protos/abstract/VehicleWheel.proto
  projects/vehicles/protos/bmw/BmwX5Simple.proto
  projects/vehicles/protos/bmw/BmwX5Wheel.proto
  projects/vehicles/protos/citroen/CitroenCZeroFrontWheel.proto
  projects/vehicles/protos/citroen/CitroenCZeroRearWheel.proto
  projects/vehicles/protos/citroen/CitroenCZeroSimple.proto
  projects/vehicles/protos/generic/BusSimple.proto
  projects/vehicles/protos/generic/MotorbikeBackwardsLight.proto
  projects/vehicles/protos/generic/MotorbikeDriver.proto
  projects/vehicles/protos/generic/MotorbikeFrontLight.proto
  projects/vehicles/protos/generic/MotorbikeLeftIndicator.proto
  projects/vehicles/protos/generic/MotorbikeMesh.proto
  projects/vehicles/protos/generic/MotorbikeRightIndicator.proto
  projects/vehicles/protos/generic/MotorbikeSimple.proto
  projects/vehicles/protos/generic/ScooterBackwardsLight.proto
  projects/vehicles/protos/generic/ScooterDriver.proto
  projects/vehicles/protos/generic/ScooterFrontLight.proto
  projects/vehicles/protos/generic/ScooterLeftIndicator.proto
  projects/vehicles/protos/generic/ScooterMesh.proto
  projects/vehicles/protos/generic/ScooterRightIndicator.proto
  projects/vehicles/protos/generic/ScooterSimple.proto
  projects/vehicles/protos/generic/TractorFrontWheel.proto
  projects/vehicles/protos/generic/TractorRearWheel.proto
  projects/vehicles/protos/generic/Truck.proto
  projects/vehicles/protos/generic/TruckRearLight.proto
  projects/vehicles/protos/generic/TruckSimple.proto
  projects/vehicles/protos/generic/TruckTank.proto
  projects/vehicles/protos/generic/TruckTankMesh.proto
  projects/vehicles/protos/generic/TruckTankSimple.proto
  projects/vehicles/protos/generic/TruckTrailer.proto
  projects/vehicles/protos/generic/TruckTrailerMesh.proto
  projects/vehicles/protos/generic/TruckTrailerSimple.proto
  projects/vehicles/protos/lincoln/LincolnMKZSimple.proto
  projects/vehicles/protos/mercedes_benz/MercedesBenzSprinterSimple.proto
  projects/vehicles/protos/range_rover/RangeRoverSportSVRSimple.proto
  projects/vehicles/protos/tesla/TeslaModel3.proto
  projects/vehicles/protos/toyota/ToyotaPriusSimple.proto
  projects/vehicles/protos/toyota/ToyotaPriusWheel.proto
  tests/physics/worlds/move_hinge_2_joint.wbt
Labels: bug, enhancement, test suite, test worlds

#6010 Bump windows version of sumo
  docs/reference/changelog-r2023.md
  projects/default/resources/Makefile
Labels: enhancement, test distribution

#6011 Fix moose wheels
  projects/robots/clearpath/moose/protos/Moose.proto
Labels: bug

#6013 Merge master in develop
  docs/reference/changelog-r2023.md
  projects/default/resources/Makefile
  projects/robots/clearpath/moose/protos/Moose.proto
Labels: synchronization

#5996 Fix & improve `test worlds`
  .github/workflows/test_suite_linux.yml
  .github/workflows/test_suite_linux_develop.yml
  projects/robots/mobsya/thymio/worlds/thymio2.wbt
  projects/robots/mobsya/thymio/worlds/thymio2_ball.wbt
  projects/robots/mobsya/thymio/worlds/thymio2_pen.wbt
  projects/samples/robotbenchmark/maze_runner/worlds/maze_runner.wbt
  projects/samples/robotbenchmark/obstacle_avoidance/worlds/obstacle_avoidance.wbt
  projects/samples/robotbenchmark/robot_programming/worlds/robot_programming.wbt
  tests/test_worlds.py
Labels: bug, test sources, test worlds

#5973 Add Husarion ROSbot XL and Husarion World
  docs/reference/changelog-r2023.md
  projects/devices/slamtec/protos/RpLidarA2.proto
  projects/devices/tdk/protos/Mpu-9250.proto
  projects/robots/husarion/rosbot/controllers/rosbot/rosbot.c
  projects/robots/husarion/rosbot/protos/Rosbot.proto
  projects/robots/husarion/rosbot/protos/meshes/body.obj
  projects/robots/husarion/rosbot/protos/meshes/cover.obj
  projects/robots/husarion/rosbot_xl/protos/RosbotXl.proto
  projects/robots/husarion/rosbot_xl/protos/icons/RosbotXl.png
  projects/robots/husarion/rosbot_xl/protos/meshes/body.dae
  projects/robots/husarion/rosbot_xl/protos/meshes/body_collision.stl
  projects/robots/husarion/rosbot_xl/protos/meshes/mecanum_a.dae
  projects/robots/husarion/rosbot_xl/protos/meshes/mecanum_b.dae
  projects/robots/husarion/rosbot_xl/protos/meshes/wheel_a.dae
  projects/robots/husarion/rosbot_xl/protos/meshes/wheel_b.dae
  projects/robots/husarion/rosbot_xl/worlds/.rosbot_xl.wbproj
  projects/robots/husarion/rosbot_xl/worlds/meshes/husarion_world.dae
  projects/robots/husarion/rosbot_xl/worlds/rosbot_xl.wbt
Labels: enhancement, test sources

#6002 Simplify tmp directory computation for extern controllers
  .github/workflows/tests_sources.yml
  .github/workflows/tests_sources_with_latest_cppcheck.yml
  docs/reference/changelog-r2023.md
  projects/default/controllers/ros/highlevel/RosControl.cpp
  projects/robots/epfl/lis/controllers/blimp/js.h
  src/controller/c/system.c
  src/webots/core/WbSysInfo.hpp
  src/webots/gui/WbNewControllerWizard.hpp
  src/webots/maths/WbMathsUtilities.hpp
  src/webots/nodes/WbAbstractCamera.cpp
  src/webots/nodes/WbCharger.cpp
  src/webots/nodes/WbDisplay.cpp
  src/webots/nodes/WbLed.cpp
  src/webots/nodes/WbLightSensor.cpp
  src/webots/nodes/WbReceiver.cpp
  src/webots/nodes/WbRobot.cpp
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/utils/WbNodeUtilities.cpp
  src/webots/nodes/utils/WbTriangleMeshCache.cpp
  src/webots/scene_tree/WbAddNodeDialog.hpp
  src/webots/user_commands/WbContextMenuGenerator.cpp
  src/wren/Cache.cpp
  src/wren/Camera.cpp
  src/wren/Config.cpp
  src/wren/CustomUniform.cpp
  src/wren/Debug.hpp
  src/wren/DirectionalLight.cpp
  src/wren/DrawableTexture.cpp
  src/wren/DynamicMesh.cpp
  src/wren/Font.cpp
  src/wren/FrameBuffer.cpp
  src/wren/Frustum.cpp
  src/wren/GlState.cpp
  src/wren/Id.cpp
  src/wren/JSHelper.cpp
  src/wren/LightNode.cpp
  src/wren/Material.cpp
  src/wren/Node.cpp
  src/wren/Overlay.cpp
  src/wren/PbrMaterial.cpp
  src/wren/PhongMaterial.cpp
  src/wren/PointLight.cpp
  src/wren/PositionalLight.cpp
  src/wren/PostProcessingEffect.cpp
  src/wren/Primitive.cpp
  src/wren/Renderable.cpp
  src/wren/Scene.cpp
  src/wren/ShaderProgram.cpp
  src/wren/ShadowVolumeCaster.cpp
  src/wren/StaticMesh.cpp
  src/wren/Texture.cpp
  src/wren/Texture2d.cpp
  src/wren/TextureCubeMap.cpp
  src/wren/TextureRtt.cpp
  src/wren/TextureTransform.cpp
  src/wren/Transform.cpp
  src/wren/TransformNode.cpp
  src/wren/UniformBuffer.cpp
  src/wren/Viewport.cpp
Labels: bug, test sources

#6022 Fix nightly builds
  src/webots/nodes/WbCharger.cpp
Labels: bug, test sources, test webots build

#6030 Fix OBJ DAE
  resources/web/wwi/nodes/WbCadShape.js
  resources/web/wwi/nodes/WbMesh.js
Labels: bug

#6029 Fixed clean-up of the motion library causing problems with the Python API
  docs/reference/changelog-r2023.md
  src/controller/c/motion.c
Labels: bug

#6038 Doc clear-cache
  docs/guide/starting-webots.md
  src/webots/gui/WbSingleTaskApplication.cpp
Labels: documentation

#6040 Fixed CeilingSpotLight SolidPipe translation
  projects/objects/lights/protos/CeilingSpotLight.proto
  projects/robots/mir/mir100/protos/Mir100.proto
  projects/samples/devices/worlds/hinge_2_joint_with_backlash.wbt
  projects/samples/devices/worlds/motor2.wbt
  projects/samples/devices/worlds/motor3.wbt
  projects/samples/environments/factory/worlds/hall.wbt
  projects/samples/geometries/worlds/extended_solids.wbt
  projects/vehicles/worlds/village_center.wbt
Labels: bug
