Repository cyberbotics/webots, pull requests merged in 2023-11, with the labels that each got.

#6417 Fix missing points in lidar scan
  resources/wren/shaders/merge_spherical.frag
  src/webots/nodes/WbLidar.cpp
  src/webots/wren/WbWrenCamera.cpp
Labels: test suite

#6436 Fixed test suite on macOS
  .github/workflows/test_suite_mac.yml
Labels: test webots build

#6447 Fixed e-puck speed
  projects/robots/gctronic/e-puck/protos/docs/e-puck.md
Labels: documentation
