Repository cyberbotics/webots, pull requests merged in 2023-06, with the labels that each got.

#6164 Fix url test worlds
  projects/robots/bitcraze/crazyflie/worlds/crazyflie_apartment.wbt
Labels: bug, test worlds

#6134 Fix ubuntu classic theme
  resources/icons/dark/checkboxCheckmark.png
  resources/icons/dark/menu-drop-down.png
  resources/icons/dark/tree_branch_closed.png
  resources/icons/dark/tree_branch_closed_hover.png
  resources/icons/dark/tree_branch_open.png
  resources/icons/dark/tree_branch_open_hover.png
  resources/webots_classic.qss
  src/webots/gui/WbPreferencesDialog.cpp
  src/webots/gui/WbSimulationView.cpp
Labels: bug

#6167 Add proto formatter script
  docs/reference/changelog-r2023.md
  scripts/proto_formatter/README.md
  scripts/proto_formatter/proto_formatter.py
Labels: enhancement

#6172 Fix MATLAB API function
  docs/reference/changelog-r2023.md
  lib/controller/matlab/wb_camera_recognition_get_objects.m
Labels: bug

#6157 Upgrade QT to 6.4.3 on MacOS
  dependencies/Makefile.mac
  docs/reference/changelog-r2023.md
  projects/robots/Makefile
  projects/robots/robotis/darwin-op/plugins/robot_windows/Makefile
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/Makefile
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/SSH.cpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/SSH.hpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/TransferWidget.cpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/TransferWidget.hpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/Viewer.cpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/Viewer.hpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/ZIP.cpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/ZIP.hpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/common.hpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/entry_points.cpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/entry_points.hpp
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/images/remote.png
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/images/remote_op2.png
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/images/send.png
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/images/send_op2.png
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/images/start_position.png
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/images/start_position_op2.png
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/images/stop.png
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/images/stop_op2.png
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/images/uninstall.png
  projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/images/uninstall_op2.png
  projects/robots/robotis/darwin-op/protos/Darwin-op.proto
  projects/robots/robotis/darwin-op/protos/Darwin-opHinge2.proto
  scripts/install/qt_mac_installer.sh
  scripts/packaging/mac_distro.py
  tests/sources/test_cppcheck.py
Labels: enhancement, test suite, test sources

#6178 Remove remote_controle of darwin-op
  projects/robots/Makefile
  projects/robots/robotis/darwin-op/config/rc.local_custom
  projects/robots/robotis/darwin-op/config/rc.local_original
  projects/robots/robotis/darwin-op/config/version.txt
  projects/robots/robotis/darwin-op/plugins/remote_controls/Makefile
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Camera.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Camera.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Communication.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Communication.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Device.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Device.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/DeviceManager.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/DeviceManager.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Led.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Makefile
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Motor.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Packet.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Packet.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/RobotisOp2InputPacket.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/RobotisOp2InputPacket.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/RobotisOp2OutputPacket.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/RobotisOp2OutputPacket.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Sensor.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/SingleValueSensor.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Time.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Time.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/TripleValuesSensor.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Wrapper.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/Wrapper.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/entry_points.cpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/entry_points.hpp
  projects/robots/robotis/darwin-op/plugins/remote_controls/robotis-op2_tcpip/stb_image.h
  projects/robots/robotis/darwin-op/remote_control/Makefile.robotis-op2
  projects/robots/robotis/darwin-op/remote_control/config.ini
  projects/robots/robotis/darwin-op/remote_control/libjpeg-turbo/include/jconfig.h
  projects/robots/robotis/darwin-op/remote_control/libjpeg-turbo/include/jerror.h
  projects/robots/robotis/darwin-op/remote_control/libjpeg-turbo/include/jmorecfg.h
  projects/robots/robotis/darwin-op/remote_control/libjpeg-turbo/include/jpeglib.h
  projects/robots/robotis/darwin-op/remote_control/libjpeg-turbo/lib/.gitignore
  projects/robots/robotis/darwin-op/remote_control/libjpeg-turbo/lib/libturbojpeg.a
  projects/robots/robotis/darwin-op/remote_control/main.cpp
  projects/robots/robotis/darwin-op/remote_control/remote.cpp
  projects/robots/robotis/darwin-op/remote_control/remote.hpp
Labels: cleanup

#6180 Disallow add node
  resources/web/wwi/NodeSelectorWindow.js
Labels: enhancement

#6181 Removed old unused file
  resources/web/wwi/request_doc.php
Labels: cleanup

#6171 Harmonize qss instruction for dark and dusk
  resources/icons/dark/spinbox_down_arrow.png
  resources/icons/dark/spinbox_up_arrow.png
  resources/icons/light/checkboxCheckmark.png
  resources/webots_classic.qss
  resources/webots_dusk.qss
  resources/webots_night.qss
  src/webots/scene_tree/WbFieldEditor.cpp
Labels: enhancement

#6183 Fix node pane line edit
  resources/webots_classic.qss
Labels: bug

#3924 Fix performance degradation in `ElevationGrid`
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbElevationGrid.cpp
  src/webots/scene_tree/WbTreeItem.cpp
  src/webots/scene_tree/WbTreeItem.hpp
  src/webots/vrml/WbField.cpp
  src/webots/vrml/WbMFBool.cpp
  src/webots/vrml/WbMFColor.cpp
  src/webots/vrml/WbMFDouble.cpp
  src/webots/vrml/WbMFInt.cpp
  src/webots/vrml/WbMFNode.cpp
  src/webots/vrml/WbMFRotation.cpp
  src/webots/vrml/WbMFString.cpp
  src/webots/vrml/WbMFVector2.cpp
  src/webots/vrml/WbMFVector3.cpp
  src/webots/vrml/WbMultipleValue.hpp
Labels: enhancement, test suite, test sources

#6192 Fix classic theme
  resources/webots_classic.qss
  resources/webots_dusk.qss
  resources/webots_night.qss
Labels: bug

#6185 Fixed test suite on Windows
  tests/command.py
Labels: bug, cleanup, test suite

#6190 Fix Connector ODE body detection
  docs/reference/changelog-r2023.md
  docs/reference/connector.md
  src/webots/nodes/WbConnector.cpp
  src/webots/nodes/WbConnector.hpp
Labels: bug, enhancement, test suite

#6198 Fix background when choosing controller
  resources/webots_classic.qss
Labels: bug

#6201 Disable shadow reception computation on mesh when shadows are globally disabled
  docs/reference/changelog-r2023.md
  src/wren/StaticMesh.cpp
Labels: cleanup, optimization

#6165 Feature ROBOTIQ grippers
  docs/reference/changelog-r2023.md
  projects/devices/robotiq/protos/Robotiq2f140Gripper.proto
  projects/devices/robotiq/protos/Robotiq2f85Gripper.proto
  projects/devices/robotiq/protos/RobotiqEPickGripper.proto
  projects/devices/robotiq/protos/icons/Robotiq2f140Gripper.png
  projects/devices/robotiq/protos/icons/Robotiq2f85Gripper.png
  projects/devices/robotiq/protos/icons/RobotiqEPickGripper.png
  projects/devices/robotiq/protos/meshes/robotiq_2f140_inner_finger.stl
  projects/devices/robotiq/protos/meshes/robotiq_2f140_inner_knuckle.stl
  projects/devices/robotiq/protos/meshes/robotiq_2f140_outer_finger.stl
  projects/devices/robotiq/protos/meshes/robotiq_2f140_outer_knuckle.stl
  projects/devices/robotiq/protos/meshes/robotiq_2f85_inner_finger.stl
  projects/devices/robotiq/protos/meshes/robotiq_2f85_inner_knuckle.stl
  projects/devices/robotiq/protos/meshes/robotiq_2f85_outer_finger.stl
  projects/devices/robotiq/protos/meshes/robotiq_2f85_outer_knuckle.stl
  projects/devices/robotiq/protos/meshes/robotiq_base_link.stl
  projects/devices/robotiq/protos/meshes/robotiq_epick.stl
  projects/objects/factory/tools/protos/SuctionCup.proto
  projects/objects/factory/tools/protos/icons/SuctionCup.png
  projects/objects/factory/tools/protos/meshes/suction_cup.obj
  projects/robots/pal_robotics/tiago/controllers/tiago_robotiq_grippers/tiago_robotiq_grippers.py
  projects/robots/pal_robotics/tiago/worlds/.tiago_robotiq_grippers.wbproj
  projects/robots/pal_robotics/tiago/worlds/tiago_robotiq_grippers.wbt
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoRobotiqGripper.proto
  projects/robots/pal_robotics/tiago_extensions/protos/icons/TiagoRobotiqGripper.png
  resources/projects/libraries/generic_robot_window/generic.c
  resources/projects/plugins/robot_windows/generic/device_widget.js
  resources/projects/plugins/robot_windows/generic/window_manager.js
  src/controller/c/default_robot_window.c
Labels: feature

#6203 Fix checkbox check mark first launch
  resources/webots_classic.qss
  resources/webots_dusk.qss
  resources/webots_night.qss
  src/webots/gui/WbNewVersionDialog.cpp
  src/webots/gui/WbNewVersionDialog.hpp
Labels: bug

#6205 Fix vacuum gripper in webotsJS
  resources/web/wwi/nodes/WbGeometry.js
  resources/web/wwi/nodes/WbVacuumGripper.js
  resources/web/wwi/nodes/wb_node_type.js
Labels: bug

#6218 Fixes random crashes with skins and meshes
  docs/reference/changelog-r2023.md
  src/webots/app/WbPerspective.cpp
  src/webots/nodes/WbMesh.cpp
  src/webots/nodes/WbSkin.cpp
Labels: crash

#6219 Fix video dialog QCheckBox
  resources/webots_classic.qss
  resources/webots_dusk.qss
  resources/webots_night.qss
Labels: bug

#6225 Fix bounding object scale
  projects/objects/balls/protos/RobocupSoccerBall.proto
  projects/objects/bathroom/protos/Toilet.proto
  projects/objects/bathroom/protos/WashingMachine.proto
  projects/objects/factory/containers/protos/MetalStorageBox.proto
Labels: bug

#6226 Fix led crash
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbCharger.cpp
  src/webots/nodes/WbLed.cpp
Labels: bug, crash, test sources

#6228 Fix khr3hv dimensions
  docs/reference/changelog-r2023.md
  projects/robots/kondo/khr-3hv/protos/Khr3hv.proto
Labels: bug

#6229 Update documentation for the release
  docs/blog/Webots-2023-a-release.md
  docs/blog/images/assets_r2023a.thumbnail.jpg
  docs/blog/images/assets_r2023a.thumbnail.png
  docs/blog/images/devices_r2023a.thumbnail.jpg
  docs/blog/images/devices_r2023a.thumbnail.png
  docs/blog/images/rosbot.thumbnail.png
  docs/css/webots-doc.css
  docs/generate_doc_util.py
  docs/guide/advanced-configuration.md
  docs/guide/installation-procedure.md
  docs/guide/setup-a-webots-project-repository.md
  docs/guide/simulation-server.md
  docs/guide/webots-cloud.md
  docs/reference/contactproperties.md
  docs/reference/images/three_chairs_proto_example.thumbnail.jpg
  docs/reference/javascript-procedural-proto.md
  docs/reference/linearmotor.md
  docs/reference/proto-design-guidelines.md
  docs/reference/rotationalmotor.md
  projects/samples/howto/docker/README.md
  projects/samples/howto/docker/launcher.py
  resources/osm_importer/config.ini
  resources/osm_importer/elevation.py
  resources/osm_importer/utils/misc_utils.py
  resources/osm_importer/webots_objects/barrier.py
  resources/osm_importer/webots_objects/road.py
  resources/web/wwi/NodeSelectorWindow.js
  resources/web/wwi/proto_viewer.js
  scripts/new_version/new_version.sh
Labels: documentation

#6230 Add R2023b splash screen
  resources/images/splash_images/tiago++.jpg
  resources/images/splash_images/vacuum_gripper.jpg
Labels: enhancement

#6233 Fix double Lidar head export
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbLidar.cpp
Labels: bug, test sources

#6199 Fix issues with manipulators of scaled Transform nodes
  src/webots/app/WbSelection.cpp
  src/webots/gui/WbDragPoseEvent.cpp
  src/webots/gui/WbDragPoseEvent.hpp
  src/webots/nodes/WbAbstractPose.cpp
Labels: bug, regression, test suite

#6239 Doc fix ros tutorial instruction
  docs/guide/tutorial-9-using-ros.md
Labels: bug, documentation, test sources

#6241 Update README.md
  README.md
Labels: documentation

#6243 Fix bounding sphere updates
  resources/web/wwi/nodes/utils/WbBoundingSphere.js
  src/webots/nodes/WbCamera.cpp
  src/webots/nodes/WbCamera.hpp
  src/webots/nodes/WbSkin.cpp
  src/webots/nodes/WbTransform.cpp
  src/webots/nodes/utils/WbBoundingSphere.cpp
  src/webots/nodes/utils/WbVisualBoundingSphere.cpp
Labels: bug, test suite

#6197 Blog post
  docs/blog/Webots-2023-b-release.md
  docs/blog/images/devices_r2023b.png
  docs/blog/images/devices_r2023b.thumbnail.png
  docs/blog/images/rosbot_xl.png
  docs/blog/images/rosbot_xl.thumbnail.png
  docs/blog/index.md
  docs/blog/menu.md
  docs/reference/changelog-r2023.md
Labels: documentation

#6245 Remove SUMO from Webots package
  docs/automobile/city-traffic.md
  docs/automobile/scenario-creation-tutorial.md
  docs/automobile/sumo-exporter.md
  docs/automobile/sumo-interface-example.md
  docs/automobile/sumo-interface.md
  docs/guide/installation-procedure.md
  docs/reference/changelog-r2023.md
  projects/default/Makefile
  projects/default/controllers/sumo_supervisor/sumo_supervisor.py
  projects/default/resources/.gitignore
  projects/default/resources/Makefile
  projects/vehicles/importer_demo.sh
  scripts/packaging/linux_distro.py
  scripts/packaging/recurse_in_projects.txt
  tests/sources/test_license.py
  tests/sources/test_pep8.py
Labels: cleanup

#6251 Fix right click macos
  src/webots/gui/WbSimulationView.cpp
  src/webots/gui/WbSimulationView.hpp
  src/webots/gui/WbView3D.cpp
  src/webots/gui/WbView3D.hpp
  src/webots/scene_tree/WbTreeView.cpp
  src/webots/user_commands/WbContextMenuGenerator.cpp
  src/webots/user_commands/WbContextMenuGenerator.hpp
Labels: bug, test sources

#6231 Doc upgrade guide
  docs/automobile/openstreetmap-importer.md
  docs/automobile/sumo-exporter.md
  docs/blog/Webots-2020-b-release.md
  docs/blog/Webots-2022-a-release.md
  docs/guide/from-2021b-to-2022a.md
  docs/guide/from-2022a-to-2022b.md
  docs/guide/from-2023a-to-2023b.md
  docs/guide/general-bugs.md
  docs/guide/images/importable_proto_button.jpg
  docs/guide/images/spot_enu.png
  docs/guide/images/spot_nue.png
  docs/guide/introduction-to-webots.md
  docs/guide/menu.md
  docs/guide/privacy-policy.md
  docs/guide/sample-webots-applications.md
  docs/guide/samples-howto.md
  docs/guide/transfer-to-your-own-robot.md
  docs/guide/translating-webots-to-your-own-language.md
  docs/guide/tutorial-8-the-supervisor.md
  docs/guide/tutorials.md
  docs/guide/upgrading-webots.md
  docs/guide/using-ros.md
  docs/guide/using-webots-makefiles.md
  docs/guide/using-your-ide.md
  docs/guide/verifying-your-graphics-driver-installation.md
  docs/guide/web-animation.md
  docs/guide/web-scene.md
  docs/guide/web-streaming.md
  docs/guide/webots-cloud.md
  docs/reference/changelog-r2022.md
  docs/reference/physics.md
  docs/reference/solid.md
  docs/tests/test_titles.py
  resources/translations/wb_de.ts
  resources/translations/wb_es.ts
  resources/translations/wb_fr.ts
  resources/translations/wb_generic.ts
  resources/translations/wb_it.ts
  resources/translations/wb_ja_JP.ts
  resources/translations/wb_zh_CN.ts
  scripts/converter/convert_nue_to_enu_rub_to_flu.py
  scripts/converter/convert_transform_to_pose.py
  scripts/converter/declare_externproto.py
  scripts/new_version/new_version.sh
  src/webots/engine/WbSimulationWorld.cpp
  src/webots/gui/WbUpdatedDialog.cpp
  src/webots/vrml/WbProtoManager.cpp
Labels: documentation

#6253 Run system sumo with snap Webots
  docs/automobile/sumo-interface.md
  docs/guide/installation-procedure.md
  projects/default/controllers/sumo_supervisor/sumo_supervisor.py
  projects/default/protos/SumoInterface.proto
Labels: bug

#6255 Added missing line feed and final dots
  src/controller/c/robot.c
Labels: cleanup

#6258 Removed conflicting Qt5 environment variable on Windows
  docs/reference/changelog-r2023.md
  src/webots/launcher/launcher.c
Labels: bug

#6259 SUMO extern controller options
  docs/automobile/sumo-interface.md
  projects/default/controllers/sumo_supervisor/sumo_supervisor.py
Labels: documentation

#6264 Update release date
  docs/blog/Webots-2023-b-release.md
  docs/reference/changelog-r2023.md
Labels: documentation, test sources

#6268 Doc update size
  docs/guide/installation-procedure.md
  docs/guide/setup-a-webots-project-repository.md
Labels: documentation

#6269 Remove open-roberta outdated exemple
  docs/guide/web-streaming.md
Labels: documentation, cleanup

#6272 Merge master in develop
  docs/blog/Webots-2023-b-release.md
  docs/guide/installation-procedure.md
  docs/guide/setup-a-webots-project-repository.md
  docs/guide/web-streaming.md
  docs/reference/changelog-r2023.md
Labels: test sources, synchronization

#6274 Bug x3d uselist
  resources/web/wwi/X3dScene.js
Labels: bug, test sources
