Repository cyberbotics/webots, pull requests merged in 2023-10, with the labels that each got.

#6402 Fix snap build
  scripts/install/linux_optional_compilation_dependencies.sh
Labels: bug, test sources

#6401 Robotiq coupling link
  projects/robots/pal_robotics/tiago_extensions/protos/TiagoRobotiqGripper.proto
  projects/robots/pal_robotics/tiago_extensions/protos/meshes/pal_robotiq_coupling.stl
Labels: enhancement, test sources

#6412 Fix the EvelationGrid height used for ODE
  docs/reference/changelog-r2023.md
  src/webots/nodes/WbElevationGrid.cpp
Labels: bug, test suite

#6415 Fix deprecated Qt methods
  resources/projects/libraries/qt_utils/motion_editor/MotionWidget.cpp
  resources/projects/libraries/qt_utils/motion_editor/PoseWidget.cpp
Labels: upgrade, test suite
