Repository cyberbotics/webots, pull requests merged in 2023-07, with the labels that each got.

#6287 Clean-up
  src/webots/app/WbSelection.cpp
Labels: cleanup

#6293 Merge master in develop
  docs/guide/system-requirements.md
  docs/reference/javascript-procedural-proto.md
  src/webots/app/WbSelection.cpp
Labels: test sources, synchronization

#6288 Fix PROTO load when a context path contains backslash
  docs/reference/changelog-r2023.md
  src/webots/core/WbTemplateEngine.cpp
  src/webots/core/WbTemplateEngine.hpp
  src/webots/vrml/WbProtoTemplateEngine.cpp
Labels: bug, test distribution, test suite

#6295 Add Silo and Ditch PROTO models
  docs/reference/changelog-r2023.md
  projects/objects/buildings/protos/Silo.proto
  projects/objects/buildings/protos/icons/Silo.png
  projects/objects/floors/protos/Ditch.proto
  projects/objects/floors/protos/icons/Ditch.png
  projects/vehicles/worlds/boomer.wbt
  scripts/icon_studio/controllers/icon_creator/objects.json
  scripts/icon_studio/worlds/icon_studio.wbt
Labels: enhancement, test sources

#6296 Bump version to R2023b-rev1
  Contents/Info.plist
  docs/js/showdown-extensions.js
  resources/version.txt
  scripts/packaging/webots_version.txt
  src/webots/core/WbApplicationInfo.cpp
  src/webots/gui/WbUpdatedDialog.cpp
Labels: test suite, test sources, synchronization

#6297 Enhancement overlays menu
  docs/reference/changelog-r2023.md
  src/webots/gui/WbMainWindow.cpp
  src/webots/gui/WbMainWindow.hpp
  src/webots/nodes/utils/WbWorld.cpp
  src/webots/nodes/utils/WbWorld.hpp
  src/webots/user_commands/WbContextMenuGenerator.cpp
  src/webots/user_commands/WbContextMenuGenerator.hpp
Labels: enhancement, test webots build

#6299 Fixed missing dependency of libController from version.txt
  src/controller/c/Makefile
Labels: bug

#6301 Fix fog billboard js
  resources/web/wwi/Parser.js
Labels: bug, test sources

#6302 Cleanup instanceof
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/nodes/WbBackground.js
  resources/web/wwi/nodes/WbBillboard.js
  resources/web/wwi/nodes/WbCylinder.js
  resources/web/wwi/nodes/WbDevice.js
  resources/web/wwi/nodes/WbGroup.js
  resources/web/wwi/nodes/WbImageTexture.js
  resources/web/wwi/nodes/WbJoint.js
  resources/web/wwi/nodes/WbLed.js
  resources/web/wwi/nodes/WbShape.js
  resources/web/wwi/nodes/WbSlot.js
  resources/web/wwi/nodes/utils/utils.js
  src/webots/nodes/WbShape.cpp
  src/webots/nodes/WbShape.hpp
Labels: enhancement, cleanup, optimization

#6307 Fix missing changelog reference
  docs/reference/changelog.md
Labels: documentation

#6308 Merge master in develop
  resources/web/wwi/FloatingProtoParameterWindow.js
  resources/web/wwi/Parser.js
  resources/web/wwi/WebotsView.js
  resources/web/wwi/X3dScene.js
  resources/web/wwi/nodes/WbBackground.js
  resources/web/wwi/nodes/WbBillboard.js
  resources/web/wwi/nodes/WbCylinder.js
  resources/web/wwi/nodes/WbDevice.js
  resources/web/wwi/nodes/WbGroup.js
  resources/web/wwi/nodes/WbImageTexture.js
  resources/web/wwi/nodes/WbJoint.js
  resources/web/wwi/nodes/WbLed.js
  resources/web/wwi/nodes/WbShape.js
  resources/web/wwi/nodes/WbSlot.js
  resources/web/wwi/nodes/utils/utils.js
  src/webots/nodes/WbShape.cpp
  src/webots/nodes/WbShape.hpp
Labels: test sources, synchronization

#6310 Fix missing node type
  resources/web/wwi/nodes/WbLookupTable.js
  resources/web/wwi/nodes/WbPropeller.js
Labels: bug

#6313 Fix apt installation instructions
  docs/guide/installation-procedure.md
Labels: documentation

#6320 Fix assertion failure with Skin node
  src/webots/nodes/utils/WbBoundingSphere.cpp
Labels: bug, test sources

#6324 Update rotating lidar angle range
  docs/reference/changelog-r2024.md
  docs/reference/changelog.md
  docs/reference/menu.md
  src/webots/nodes/WbLidar.cpp
Labels: test suite, test sources

#6327 Cleanup depecrated fields of display
  docs/reference/changelog-r2024.md
  resources/nodes/Display.wrl
Labels: cleanup

#6330 Fix duplicate entry in changelog
  docs/reference/changelog-r2023.md
Labels: documentation, cleanup

#6309 Fix handling scaled nodes in Webots/WREN
  docs/reference/changelog-r2023.md
  src/webots/maths/WbAxisAngle.hpp
  src/webots/maths/WbMatrix3.cpp
  src/webots/maths/WbMatrix3.hpp
  src/webots/maths/WbRotation.cpp
  src/webots/maths/WbRotation.hpp
  src/webots/nodes/WbAbstractPose.cpp
  src/webots/nodes/WbAbstractPose.hpp
  src/webots/nodes/WbInertialUnit.cpp
  src/webots/nodes/WbTrackWheel.cpp
  src/webots/nodes/WbTransform.cpp
  src/webots/scene_tree/WbPositionViewer.cpp
  src/webots/scene_tree/WbPositionViewer.hpp
  tests/protos/controllers/hinge_2_joint_with_backlash_supervisor/hinge_2_joint_with_backlash_supervisor.c
Labels: bug, cleanup, test suite

#6342 Fix version number to 2023b
  projects/samples/howto/url/controllers/url/url.c
  projects/samples/howto/url/worlds/url.wbt
  resources/translations/wb_de.ts
  resources/translations/wb_es.ts
  resources/translations/wb_fr.ts
  resources/translations/wb_generic.ts
  resources/translations/wb_it.ts
  resources/translations/wb_ja_JP.ts
  resources/translations/wb_zh_CN.ts
  resources/web/wwi/ProtoManager.js
  tests/api/worlds/camera_color.wbt
Labels: cleanup, test suite, test worlds
