Repository cyberbotics/webots, pull requests merged in 2024-12, with the labels that each got.

#6719 Fix main branch builds
  .github/workflows/test_suite_linux_develop.yml
  projects/vehicles/plugins/robot_windows/automobile_window/AbstractWidget.cpp
  projects/vehicles/plugins/robot_windows/automobile_window/GeneralInformationWidget.cpp
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_runtime_dependencies.sh
Labels: test webots build

#6720 Fix Windows build
  projects/samples/robotbenchmark/include/robotbenchmark.h
  src/controller/c/robot.c
  src/webots/gui/WbNewProtoWizard.cpp
  src/webots/scene_tree/WbBoolEditor.cpp
Labels: test distribution

#6736 Restore Support for Ubuntu 20.04 in Dependency Installation Scripts
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_runtime_dependencies.sh
Labels: test suite issue, test suite

#6737 Pin empy Version in Ros CI Test
  .github/workflows/test_suite_linux.yml
Labels: test suite issue, test ros

#6739 Remove Support for Ubuntu 20.04 in Dependency Installation Scripts
  scripts/install/linux_compilation_dependencies.sh
  scripts/install/linux_runtime_dependencies.sh
Labels: test suite

#6735 Fix `WbField::isParameter` for Unconnected Fields
  docs/reference/changelog-r2024.md
  src/webots/nodes/utils/WbTemplateManager.cpp
  src/webots/nodes/utils/WbTemplateManager.hpp
  src/webots/scene_tree/WbAddNodeDialog.cpp
  src/webots/scene_tree/WbExtendedStringEditor.cpp
  src/webots/vrml/WbField.cpp
  src/webots/vrml/WbField.hpp
Labels: test suite

#6744 Fix Crash When Loading an Invalid Background HDR Image
  docs/reference/changelog-r2024.md
  src/webots/nodes/WbBackground.cpp
Labels: bug, crash

#6742 Fix Heron Warnings (Port #6717)
  projects/robots/clearpath/heron/protos/Heron.proto
  projects/robots/clearpath/heron/stl/heron_base.stl
  projects/robots/clearpath/heron/worlds/ocean.wbt
  projects/robots/clearpath/heron/worlds/swarm.wbt
Labels: test suite issue, test worlds

#6748 Launch Webots on x11 server
  src/webots/launcher/webots-linux.sh
Labels: test distribution, test webots build
