Repository cyberbotics/webots, pull requests merged in 2024-10, with the labels that each got.

#6677 Fix bug where the wrong y coord was used for one corner of the box drawn to represent a box-plane collision.
  docs/reference/changelog-r2024.md
  src/webots/app/WbContactPointsRepresentation.cpp
Labels: test suite

#6678 Show box-plane contact point normals when showing contact points.
  docs/reference/changelog-r2024.md
  src/webots/app/WbContactPointsRepresentation.cpp
Labels: test suite

#6688 Improve speed, accuracy, and readability of dCollideBoxPlane.
  docs/reference/changelog-r2024.md
  src/ode/ode/src/box.cpp
  tests/api/controllers/supervisor_node_set_joint_position/supervisor_node_set_joint_position.c
  tests/api/worlds/supervisor_node_set_joint_position.wbt
Labels: enhancement, test suite

#6691 Fix Bounding Box Initialization when a Geometry is Inserted into a Shape
  docs/reference/changelog-r2024.md
  src/webots/nodes/WbGeometry.cpp
  src/webots/nodes/WbMatter.cpp
Labels: crash, test suite
