Repository cyberbotics/webots, pull requests merged in 2024-07, with the labels that each got.

#6585 Remote assets per URL
  docs/reference/changelog-r2024.md
  src/webots/vrml/WbProtoManager.cpp
Labels: enhancement

#6584 Fix `Brake`s added to the second axis of a `Hinge2Joint` being applied to the non-transformed axis.
  docs/reference/changelog-r2024.md
  src/webots/nodes/WbHinge2Joint.cpp
  tests/physics/controllers/hinge_2_joint_damping_axis/.gitignore
  tests/physics/controllers/hinge_2_joint_damping_axis/Makefile
  tests/physics/controllers/hinge_2_joint_damping_axis/hinge_2_joint_damping_axis.c
  tests/physics/worlds/hinge_2_joint_damping_axis.wbt
Labels: test suite

#6588 Allow non-nightly builds on weekends.
  scripts/packaging/publish_release.py
Labels: test distribution

#6590 [CI] Install Swig on Mac
  .github/workflows/test_suite_mac.yml
  .github/workflows/test_suite_mac_develop.yml
Labels: test distribution

#6593 6592 invalid sound path results in crash
  docs/reference/changelog-r2024.md
  src/webots/nodes/WbSpeaker.cpp
  src/webots/sound/WbWaveFile.cpp
Labels: bug

#6586 Fix windows nightly build
  scripts/packaging/files_msys64.txt
  scripts/packaging/windows_distro.py
  src/webots/maths/WbMathsUtilities.cpp
Labels: test distribution

#6595 Fix macos CI being slow.
  src/webots/sound/WbSoundEngine.cpp
Labels: test distribution, test suite

#6598 Fix Thumbnail Generation
  docs/generate_thumbnails.py
Labels: bug
